oss-review-toolkit/ort

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1420)
=> PipTest: Upgrade the expected Werkzeug version to 0.15.2

analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/CocoaPods.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/Nuget.kt, analyzer/src/main/kotlin/managers/PIP.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/SBT.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/Yarn.kt, build.gradle, model/src/main/kotlin/HashAlgorithm.kt, model/src/main/kotlin/Identifier.kt, model/src/main/kotlin/Package.kt, model/src/main/kotlin/Project.kt, model/src/main/kotlin/config/PathExclude.kt, spdx-utils/src/main/kotlin/SpdxExpression.kt, utils/src/main/kotlin/Extensions.kt
Please see the commit message for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1423)
=> KDoc Improvements

.mailmap
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1424)
=> Update mail mappings

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt, spdx-utils/src/main/kotlin/SpdxLicenseAliasMapping.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1425)
=> Improve documentation for SPDX classes

reporter/src/main/kotlin/reporters/NoticeReporter.kt, spdx-utils/src/main/kotlin/Extensions.kt, spdx-utils/src/test/kotlin/ExtensionsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1426)
=> Do not hard-code filtering-out of public domain licenses

analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml, analyzer/src/funTest/kotlin/DotNetTest.kt, analyzer/src/funTest/kotlin/NuGetTest.kt, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/NuGet.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1431)
=> More minor DotNet / NuGet related clean-ups

scanner/src/main/kotlin/scanners/ScanCode.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1441)
=> ScanCode: Improve the comment about the ScanCode LicenseRef namespace

cli/build.gradle.kts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1442)
=> Gradle: Apply a minor "cli" build script simplification

analyzer/src/funTest/assets/projects/synthetic/bower-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/python3-django-expected-output.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1447)
=> PipTest: Upgrade the expected pytz dependency to version 2019.1

build.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1444)
=> Minor build improvements

gradle.properties
See https://bmuschko.github.io/gradle-docker-plugin/#v4_7_0_april_9_2019.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1449)
=> Gradle: Upgrade Docker plugins to version 4.7.0

utils/src/main/kotlin/DeclaredLicenseProcessor.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1451)
=> DeclaredLicenseProcessor: Apply a minor code simplification

gradle.properties, utils/build.gradle.kts
See https://github.com/JetBrains/kotlin/releases/tag/v1.3.30.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1448)
=> Gradle: Upgrade Kotlin to version 1.3.30

analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1460)
=> NpmVersionUrlTest: Upgrade the expected component-emitter version to 1.3.0

gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/5.4/release-notes.html.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1456)
=> Gradle: Upgrade to version 5.4

scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanCodeTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1459)
=> Scancode no exceptions

evaluator/src/main/kotlin/Evaluator.kt, evaluator/src/main/kotlin/PackageRule.kt, evaluator/src/main/kotlin/Rule.kt, evaluator/src/main/kotlin/RuleSet.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1463)
=> Rules api integration

.gitignore, build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/IdeaExtKotlinDsl.kt, model/build.gradle.kts, spdx-utils/build.gradle.kts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1468)
=> Gradle: Gather common Kotlin DSL extension functions in the buildSrc project

evaluator/src/main/kotlin/LicenseView.kt, evaluator/src/main/kotlin/PackageRule.kt, evaluator/src/main/kotlin/RuleSet.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1466)
=> Evaluator improvements

analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/SBT.kt, analyzer/src/main/kotlin/managers/Yarn.kt
This is a fixup for f78de43.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1471)
=> analzer: Fix comment formatting for expressions functions

analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt, analyzer/src/main/kotlin/Analyzer.kt, analyzer/src/main/kotlin/DotNetSupport.kt, analyzer/src/test/kotlin/NpmTest.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, cli/src/main/kotlin/commands/RequirementsCommand.kt, model/src/main/kotlin/AnalyzerResult.kt, model/src/main/kotlin/ProjectAnalyzerResult.kt, model/src/test/kotlin/IdentifierTest.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, scanner/src/main/kotlin/Scanner.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, utils/src/test/kotlin/UtilsTest.kt
This silences an inspection hint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1470)
=> Use Kotlin's forEach instead of Java's Map.forEach

gradle.properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1478)
=> Gradle: Fix a trivial spacing issue in properties

.appveyor.yml
This is a fixup for 8aa9446.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1477)
=> AppVeyor: Remove an empty statement

analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/SBT.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/test/kotlin/PackageJsonUtilsTest.kt, buildSrc/src/main/kotlin/IdeaExtKotlinDsl.kt, cli/src/funTest/kotlin/MainTest.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Cvs.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, model/src/main/kotlin/Hash.kt, model/src/main/kotlin/HashAlgorithm.kt, model/src/test/kotlin/PackageReferenceTest.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/ReportTableModel.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, spdx-utils/build.gradle.kts, spdx-utils/src/main/kotlin/SpdxLicense.kt, spdx-utils/src/main/kotlin/SpdxLicenseException.kt, spdx-utils/src/test/kotlin/SpdxExpressionTest.kt, utils/src/main/kotlin/Extensions.kt, utils/src/main/kotlin/ProcessCapture.kt, utils/src/test/kotlin/RedirectionTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1476)
=> Inspections

analyzer/src/funTest/kotlin/BabelTest.kt, analyzer/src/funTest/kotlin/BowerTest.kt, analyzer/src/funTest/kotlin/BundlerTest.kt, analyzer/src/funTest/kotlin/DotNetSupportTest.kt, analyzer/src/funTest/kotlin/DotNetTest.kt, analyzer/src/funTest/kotlin/GoDepTest.kt, analyzer/src/funTest/kotlin/GradleAndroidTest.kt, analyzer/src/funTest/kotlin/GradleKotlinScriptTest.kt, analyzer/src/funTest/kotlin/GradleLibraryTest.kt, analyzer/src/funTest/kotlin/GradleTest.kt, analyzer/src/funTest/kotlin/MavenTest.kt, analyzer/src/funTest/kotlin/NpmTest.kt, analyzer/src/funTest/kotlin/NpmVersionUrlTest.kt, analyzer/src/funTest/kotlin/NuGetTest.kt, analyzer/src/funTest/kotlin/PhpComposerTest.kt, analyzer/src/funTest/kotlin/PipTest.kt, analyzer/src/funTest/kotlin/StackTest.kt, analyzer/src/funTest/kotlin/YarnTest.kt, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/PIP.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/SBT.kt, analyzer/src/main/kotlin/managers/Unmanaged.kt, analyzer/src/test/kotlin/PackageManagerTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1475)
=> Definition file absolute

model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/Repository.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1480)
=> Nested VCS matching

analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/CocoaPods.kt, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/NuGet.kt, analyzer/src/main/kotlin/managers/PIP.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/SBT.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/Unmanaged.kt, analyzer/src/main/kotlin/managers/Yarn.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1483)
=> analyzer: Apply a minor formatting fix to all package manager constructors

gradle.properties
See https://github.com/JetBrains/kotlin/releases/tag/v1.3.31.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1484)
=> Gradle: Upgrade Kotlin to version 1.3.31

analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/PIP.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/SBT.kt, analyzer/src/main/kotlin/managers/Yarn.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1486)
=> Before after resolution

cli/src/funTest/kotlin/MainTest.kt, cli/src/main/kotlin/commands/RequirementsCommand.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1489)
=> Fix requirements

cli/src/funTest/kotlin/MainTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1490)
=> MainTest clean-ups

analyzer/src/funTest/kotlin/GradleTest.kt, analyzer/src/main/resources/scripts/init.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1491)
=> Gradle tests

analyzer/src/main/kotlin/managers/PIP.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1494)
=> PIP: Improve a comment wording

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1495)
=> Logo anchors

analyzer/src/main/kotlin/managers/Pip.kt
=> Pip: Write a meaningful error to the report if installing dependencies fails

spdx-utils/src/test/kotlin/SpdxExpressionParserTest.kt
Simplify comparision to the expected type of expression.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1499)
=> SpdxExpressionParserTest: Slightly refactor code for easier debugging

evaluator/src/main/kotlin/DependencyRule.kt, evaluator/src/main/kotlin/PackageRule.kt, evaluator/src/main/kotlin/Rule.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1502)
=> Rules api improvements

spdx-utils/src/main/kotlin/SpdxExpression.kt, spdx-utils/src/test/kotlin/SpdxExpressionParserTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1500)
=> Spdx parser no viable input

utils/src/main/kotlin/ProcessCapture.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1508)
=> ProcessCapture: Improve the error message fallback to stdout

analyzer/src/main/kotlin/DotNetSupport.kt, analyzer/src/main/kotlin/MavenSupport.kt, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/Pip.kt, analyzer/src/main/kotlin/managers/Stack.kt, cli/src/main/kotlin/Main.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Subversion.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, utils/src/main/kotlin/CommandLineTool.kt, utils/src/main/kotlin/Extensions.kt, utils/src/main/kotlin/Os.kt, utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1507)
=> Improve code readability by consistently using orEmpty() calls

analyzer/src/main/kotlin/managers/Pip.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1510)
=> Pip: Improve logging in setupVirtualEnv()

evaluator/src/main/kotlin/PackageRule.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1511)
=> Rule matchers

analyzer/src/main/resources/scripts/init.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1512)
=> Gradle unresolvable version

cli/src/main/kotlin/Main.kt, reporter/src/funTest/assets/static-html-reporter-test-expected-output.html, reporter/src/funTest/kotlin/reporters/StaticHtmlReporterTest.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, reporter/src/main/resources/static-html-reporter.css
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1513)
=> Static HTML creation info

model/src/main/kotlin/Hash.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1515)
=> Hash: Remove a duplicate blank line

analyzer/src/funTest/assets/projects/external/directories-expected-output.yml, analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml, analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml, cli/src/main/kotlin/Main.kt, model/src/main/kotlin/Environment.kt, reporter/src/funTest/assets/npm-test-with-exclude-scan-results.yml, reporter/src/funTest/assets/npm-test-without-exclude-scan-results.yml, reporter/src/funTest/assets/static-html-reporter-test-input.yml, scanner/src/funTest/assets/analyzer-result.yml, scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml, test-utils/src/main/kotlin/Utils.kt
This can be helpful to debug issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1518)
=> Also capture the Java version ORT is running on

build.gradle.kts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1523)
=> Funtest deps

scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/FileCounter.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanCodeTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1525)
=> Scancode cleanups

scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanCodeTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1526)
=> Some more small ScanCode clean-ups

analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1532)
=> BundlerTest: Update an expected homepage URL

analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml, downloader/src/funTest/kotlin/BeanUtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1535)
=> NpmVersionUrlTest: Update the expected cloneable-readable dependency

.mailmap
=> mailmap: Add Sebastian's new company address

analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, model/src/main/kotlin/AnalyzerResult.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1544)
=> PhpComposer: Cut the circle for cyclic dependencies

.github/main.workflow
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1546)
=> GitHub: Add a workflow to rebase PRs automatically

analyzer/src/main/kotlin/managers/Npm.kt, cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/ScannerCommand.kt, docs/GettingStarted.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1550)
=> NPM related improvements for Getting Started

analyzer/src/main/kotlin/DotNetSupport.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1549)
=> Detekt issues

analyzer/src/funTest/kotlin/StackTest.kt
To avoid any differences in expected results when Stack gets updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1556)
=> StackTest: Pin the Stack version also on Linux

gradle.properties
See https://bmuschko.github.io/gradle-docker-plugin/#v4_10_0_june_12_2019.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1554)
=> Gradle: Upgrade the Docker plugins to version 4.10.0

evaluator/src/test/kotlin/DependencyRuleTest.kt, evaluator/src/test/kotlin/LicenseViewTest.kt, evaluator/src/test/kotlin/PackageRuleTest.kt, evaluator/src/test/kotlin/RuleSetTest.kt, evaluator/src/test/kotlin/RuleTest.kt, evaluator/src/test/kotlin/TestData.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1462)
=> evaluator: Add tests for the rules API

model/src/main/kotlin/config/Excludes.kt, model/src/test/kotlin/config/ExcludesTest.kt, reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1558)
=> Handle all matching project excludes

model/src/main/kotlin/OrtResult.kt
This simplifies a bit by removing (redundant) handling of null values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1560)
=> OrtResult: Extract functions to get packages, projects and excludes

scanner/src/main/kotlin/scanners/ScanCode.kt, spdx-utils/src/main/kotlin/SpdxUtils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1552)
=> Lowercase license files

build.gradle.kts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1562)
=> Build improvements

analyzer/src/main/kotlin/managers/Gradle.kt, utils/src/main/kotlin/Utils.kt
By manually applying system properties from Gradle properties. Also see
https://github.com/gradle/gradle/issues/6825.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1563)
=> Gradle: Support downloading via a proxy

gradle.properties
See https://blog.jetbrains.com/kotlin/2019/06/kotlin-1-3-40-released/.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1566)
=> Gradle: Upgrade to Kotlin 1.3.40

analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1567)
=> NpmVersionUrlTest: Update expected test results

cli/src/main/kotlin/commands/ReporterCommand.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1569)
=> ReporterCommand: Add tilde expansion in paths in two missing places

model/src/main/kotlin/config/PathExcludeReason.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1565)
=> Add path exclude reason

downloader/src/funTest/kotlin/MercurialDownloadTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1570)
=> Fix Mercurial test

downloader/src/funTest/kotlin/GitDownloadTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1572)
=> Fix the GitDownloadTest

analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/CocoaPods.kt, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/NuGet.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/Pip.kt, analyzer/src/main/kotlin/managers/Sbt.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/Unmanaged.kt, analyzer/src/main/kotlin/managers/Yarn.kt, cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, downloader/src/main/kotlin/vcs/Cvs.kt, evaluator/src/main/kotlin/LicenseView.kt, model/src/main/kotlin/AnalyzerResult.kt, model/src/main/kotlin/Identifier.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/FileCounter.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, spdx-utils/src/main/kotlin/SpdxExpressionDefaultVisitor.kt
For simplicity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1547)
=> Make more use of expression functions

build.gradle.kts, model/src/main/kotlin/TextLocation.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1575)
=> Copyright check improvements

reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1578)
=> Static HTML reporter improvements

model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/config/Excludes.kt, model/src/test/kotlin/config/ExcludesTest.kt, reporter/src/main/kotlin/reporters/NoticeReporter.kt
See individual commits for the details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1557)
=> Speed up `is project excluded`

scanner/src/funTest/kotlin/scanners/FileCounterTest.kt, scanner/src/funTest/kotlin/storages/ArtifactoryStorageTest.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/ScanResultsStorage.kt, scanner/src/main/kotlin/Scanner.kt, scanner/src/main/kotlin/storages/ArtifactoryStorage.kt, scanner/src/main/kotlin/storages/FileBasedStorage.kt, scanner/src/main/kotlin/storages/NoStorage.kt, scanner/src/test/kotlin/ScanResultsStorageTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1574)
=> Storage refactoring

scanner/src/main/kotlin/storages/FileBasedStorage.kt, scanner/src/main/kotlin/storages/NoStorage.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1584)
=> scanner: Restore the HERE Copyright for files that were based on HERE code

.detekt.yml, cli/src/main/kotlin/commands/ScannerCommand.kt, model/src/main/kotlin/config/LocalFileStorageConfiguration.kt, model/src/main/kotlin/config/ScannerConfiguration.kt, scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml, scanner/src/funTest/kotlin/storages/AbstractStorageTest.kt, scanner/src/funTest/kotlin/storages/ArtifactoryStorageTest.kt, scanner/src/funTest/kotlin/storages/LocalFileStorageTest.kt, scanner/src/main/kotlin/ScanResultsStorage.kt, scanner/src/main/kotlin/storages/LocalFileStorage.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1583)
=> Add a local file based scan results storage

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1586)
=> README: Document the new default local file scan results storage

Jenkinsfile, docker/build.sh, docker/build/Dockerfile, docker/lib, docker/run.sh, docker/run/Dockerfile, docker/test.sh, docker/test/Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1589)
=>  Add new Dockerfiles and an initial Jenkinsfile to easily run ORT on a Git project 

docker/build.sh, docker/lib, docker/test.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1591)
=> Docker build improvements

buildSrc/build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/5.5/release-notes.html.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1594)
=> Gradle: Upgrade to version 5.5

downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/GitRepo.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, downloader/src/main/kotlin/vcs/Subversion.kt, model/src/test/kotlin/PackageCurationTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1603)
=> Trivial simplifications

analyzer/src/main/kotlin/managers/Stack.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1604)
=> Stack: Simplify the mapping to enriched package information

analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/GoDep.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1611)
=> Detekt fixes

analyzer/src/main/kotlin/managers/Bundler.kt
Make sure all error messages mention the gem meta-data was requested
for, and add a specific error message for bad gateway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1612)
=> Bundler: Align error messages in `queryRubygems`

Jenkinsfile, cli/src/main/kotlin/commands/ScannerCommand.kt, scanner/src/main/kotlin/storages/ArtifactoryStorage.kt, scanner/src/main/kotlin/storages/FileBasedStorage.kt, scanner/src/main/kotlin/storages/LocalFileStorage.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1614)
=> scanner: Refactor code a bit to be able to log the scan results file count

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1620)
=> README: Improve the section about ORT development

gradle.properties
See https://github.com/JetBrains/kotlin/releases/tag/v1.3.41.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1619)
=> Gradle: Upgrade the Kotlin plugin to version 1.3.41

Jenkinsfile
To ensure it is not polluted with files from a previously cloned
project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1621)
=> Jenkinsfile: Remove the project directory before cloning into it

analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1623)
=> NpmVersionUrlTest: Update the expected version of xtend

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1628)
=> README: State that the Analyzer is a SCA tool

analyzer/src/main/kotlin/DotNetSupport.kt, analyzer/src/main/kotlin/PackageManager.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1625)
=> VcsType fixups

build.gradle.kts, model/build.gradle.kts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1632)
=> Prepare publishing via Maven

cli/src/main/kotlin/commands/ScannerCommand.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1624)
=> ScannerCommand: Log about the local file storage at info level if in use

build.gradle.kts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1633)
=> Work around a Dokka runtime bug

utils/src/main/kotlin/ArchiveUtils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1635)
=> ArchiveUtils: Sort TAR_GZIP_EXTENSIONS alphabetically

docker/run/Dockerfile
Fixes #1640.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1641)
=> docker: Add Python 3 for running ORT

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml, analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml, downloader/src/test/kotlin/GitTest.kt, downloader/src/test/kotlin/SubversionTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1647)
=> PipTest: Upgrade the expected Werkzeug version to 0.15.5

evaluator/src/main/kotlin/LicenseView.kt, evaluator/src/test/kotlin/LicenseViewTest.kt
Add new license views and tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1650)
=> License views

gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat
For the release notes see:
https://docs.gradle.org/5.5.1/release-notes.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1654)
=> Upgrade Gradle to 5.5.1

analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml, spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1655)
=> SpdxDeclaredLicenseMapping: Add an entry for `PSFL`

analyzer/src/main/kotlin/managers/Pip.kt, docker/build.sh, docker/lib, docker/run.sh, docker/test.sh, model/src/main/kotlin/Environment.kt, utils/src/main/kotlin/Ci.kt, utils/src/main/kotlin/OkHttpClientHelper.kt, utils/src/main/kotlin/Os.kt, utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1660)
=> Various proxy-related improvements

analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1662)
=> PipTest: Upgrade the expected pyparsing version to 2.4.2

scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/storages/ArtifactoryStorage.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1618)
=> Avoid creating temporary files for HTTP downloads

analyzer/src/main/kotlin/MavenSupport.kt
Add support for parsing Git URLs for Maven projects that omit the type
fragment and use an SCP-like URL, for example
"scm:git@github.com:facebook/facebook-android-sdk.git".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1657)
=> MavenSupport: Add support for projects that use an SCP-like Git URL

cli/src/main/kotlin/commands/ReporterCommand.kt, reporter/src/funTest/kotlin/reporters/ExcelReporterTest.kt, reporter/src/funTest/kotlin/reporters/NoticeReporterTest.kt, reporter/src/funTest/kotlin/reporters/StaticHtmlReporterTest.kt, reporter/src/funTest/kotlin/reporters/WebAppReporterTest.kt, reporter/src/main/kotlin/DefaultLicenseTextProvider.kt, reporter/src/main/kotlin/LicenseTextProvider.kt, reporter/src/main/kotlin/Reporter.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/NoticeReporter.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, reporter/src/main/kotlin/reporters/WebAppReporter.kt, spdx-utils/src/main/kotlin/SpdxUtils.kt, spdx-utils/src/test/kotlin/SpdxUtilsTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1664)
=> Custom license ids

build.gradle.kts, gradle.properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1666)
=> Use the "reckon" plugin to determine the project version

analyzer/src/funTest/assets/projects/synthetic/python3-django-expected-output.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1668)
=> PipTest: Update expected test results

README.md, analyzer/src/main/kotlin/managers/Pub.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1670)
=> Pub improvements

.jitpack.yml, README.md
Also see https://github.com/jitpack/jitpack.io/issues/3898 and
https://jitpack.io/docs/BUILDING/#custom-commands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1667)
=> Help JitPack.io to determine the right build command

docker/run/Dockerfile
Add Flutter (which includes Pub) to the Docker container for running
ORT. Note that the ANDROID_SDK is not installed, so Android dependencies
of Flutter projects will not be detected.
=> Add Pub/Flutter to the Docker container

downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Git.kt
=> Split VCS download() into helper functions for Git

downloader/src/funTest/kotlin/GitDownloadTest.kt, downloader/src/main/kotlin/VersionControlSystem.kt
=> Add revision candidate logging

downloader/src/main/kotlin/VersionControlSystem.kt
=> VersionControlSystem: Fix exception handling if no revision matches

analyzer/src/funTest/assets/projects/external/dart-http-expected-output.yml
=> PubTest: Update expected test results

analyzer/src/main/kotlin/managers/Npm.kt
=> Npm: Guard against npmrc lines without an equal sign

analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Npm.kt, downloader/src/main/kotlin/VersionControlSystem.kt, utils/src/main/kotlin/Extensions.kt, utils/src/main/kotlin/OkHttpClientHelper.kt, utils/src/main/kotlin/Utils.kt
=> Rework URL parsing and catching of exceptions for safety

downloader/src/funTest/kotlin/GitDownloadTest.kt, downloader/src/funTest/kotlin/MercurialDownloadTest.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Mercurial.kt
=> Split VCS download() into helper functions for Mercurial

analyzer/src/main/kotlin/managers/Npm.kt, utils/src/main/kotlin/OkHttpClientHelper.kt
=> Improve npmrc parsing, again

analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Pub.kt, cli/src/funTest/kotlin/MainTest.kt, evaluator/src/test/kotlin/RuleSetTest.kt, model/src/main/kotlin/VcsType.kt, model/src/test/kotlin/config/ExcludesTest.kt, reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt, scanner/src/main/kotlin/storages/NoStorage.kt, utils/src/main/kotlin/DeclaredLicenseProcessor.kt, utils/src/main/kotlin/Extensions.kt
=> Fix detekt 1.0.0 issues

.github/main.workflow, .github/workflows/rebase.yml
FYI, I was able to opt-in our project to the Actions 2.0 beta.
=>  Migrate from HCL-file based Actions 1.0 to YAML-file based Actions 2.0

model/src/main/kotlin/OrtResult.kt, reporter/src/funTest/assets/static-html-reporter-test-expected-output.html, reporter/src/funTest/kotlin/reporters/StaticHtmlReporterTest.kt, utils/src/main/kotlin/DeclaredLicenseProcessor.kt
=> Make getDeclaredLicensesForId() return processed licenses

README.md
=> README: Fix indentation for a code block

gradle/wrapper/gradle-wrapper.properties, spdx-utils/build.gradle.kts
See https://docs.gradle.org/5.6/release-notes.html.
=> Gradle: Upgrade to version 5.6

analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/NuGet.kt, analyzer/src/main/kotlin/managers/Unmanaged.kt, analyzer/src/main/kotlin/managers/utils/DotNetSupport.kt, analyzer/src/test/kotlin/managers/utils/DotNetSupportTest.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, downloader/src/funTest/kotlin/DownloaderTest.kt, model/src/main/kotlin/AnalyzerResult.kt, spdx-utils/src/main/kotlin/SpdxExpressionDefaultVisitor.kt
=> Misc. DotNet / NuGet improvements

Jenkinsfile
To showcase all currently maintained output formats.
=> Jenkinsfile: Let the reporter also generate a NOTICE file

.detekt.yml, helper-cli/src/main/kotlin/Main.kt, helper-cli/src/main/kotlin/commands/GenerateProjectExcludesCommand.kt, helper-cli/src/main/kotlin/commands/GenerateRuleViolationResolutionsCommand.kt, helper-cli/src/main/kotlin/commands/ImportPathExcludesCommand.kt, helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
=> Helper CLI improvements

analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/Pip.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/utils/MavenSupport.kt, cli/src/main/kotlin/commands/RequirementsCommand.kt, downloader/src/main/kotlin/Downloader.kt, model/src/main/kotlin/AnalyzerResult.kt, model/src/main/kotlin/Identifier.kt, scanner/src/main/kotlin/storages/FileBasedStorage.kt
Succeeding lines have to be indented.
=> Fix highlighting of multi-line TODOs in IntelliJ

scanner/src/test/kotlin/ScanResultsStorageTest.kt
=> ScanResultsStorageTest: Remove superfluous type

scanner/src/main/kotlin/storages/PostgresStorage.kt
The null character '\u0000' is not allowed in PostgreSQL JSONB
columns [1], so we need to escape it before storing scan results in
PostgreSQL.
[1] https://www.postgresql.org/docs/11/datatype-json.html
=> PostgresStorage: Escape the null character in scan results

cli/src/main/kotlin/commands/ScannerCommand.kt, scanner/src/funTest/kotlin/storages/PostgresStorageTest.kt, scanner/src/main/kotlin/ScanResultsStorage.kt, scanner/src/main/kotlin/storages/PostgresStorage.kt
=> Storage configuration improvements

gradle.properties, utils/build.gradle.kts
=> Upgrade Kotlin to version 1.3.50

.travis.yml
=> Travis: Upgrade the go-lang and go-dep versions

evaluator/src/main/kotlin/PackageRule.kt, evaluator/src/main/kotlin/RuleSet.kt
=> evaluator: Fix-up minor left overs introduced by a class renaming

evaluator/src/main/kotlin/Evaluator.kt, evaluator/src/test/kotlin/EvaluatorTest.kt, reporter/src/main/kotlin/reporters/NoticeReporter.kt, utils/build.gradle.kts, utils/src/main/kotlin/ScriptRunner.kt, utils/src/main/resources/META-INF/services/javax.script.ScriptEngineFactory
This supports direct access to bound variables. For details see
https://youtrack.jetbrains.com/issue/KT-15125.
=> utils: Use the new kotlin-scripting-jsr223

gradle.properties
See https://arturbosch.github.io/detekt/changelog.html#101.
=> Gradle: Upgrade the detekt plugin to version 1.0.1

model/src/main/kotlin/config/ArtifactoryStorageConfiguration.kt, model/src/main/kotlin/config/LocalFileStorageConfiguration.kt, model/src/main/kotlin/config/PostgresStorageConfiguration.kt, scanner/src/main/kotlin/storages/ArtifactoryStorage.kt, scanner/src/main/kotlin/storages/LocalFileStorage.kt, scanner/src/main/kotlin/storages/PostgresStorage.kt
=>  Improve and align storage / configuration docs

analyzer/src/main/kotlin/managers/Sbt.kt, cli/src/main/kotlin/Main.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
It is slightly longer but reads more natural.
=> Make some if/else conditions with empty strings more Kotlin-ish

utils/src/main/kotlin/Extensions.kt, utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/ExtensionsTest.kt
=> Percent encode fixes

analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/NuGet.kt, spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt
=> Miscellaneous DotNet/NuGet-related improvements

analyzer/src/main/kotlin/managers/Cargo.kt
=> Cargo: Document the class with a link to the package manager's homepage

model/src/main/kotlin/TextLocation.kt, model/src/test/assets/expected-scan-results.yml, model/src/test/kotlin/ScanResultContainerTest.kt, reporter/src/funTest/assets/static-html-reporter-test-input.yml
=> Add a sanity check in the Textlocation constructor

model/src/main/kotlin/ScanSummary.kt, model/src/main/kotlin/util/FindingsMatcher.kt, model/src/test/kotlin/utils/FindingsMatcherTest.kt, scanner/src/main/kotlin/scanners/ScanCode.kt
This is the beginning of some test refactoring.
=> Minor findings matcher improvements

cli/src/main/kotlin/commands/ReporterCommand.kt, reporter/src/funTest/kotlin/reporters/ExcelReporterTest.kt, reporter/src/funTest/kotlin/reporters/NoticeReporterTest.kt, reporter/src/funTest/kotlin/reporters/StaticHtmlReporterTest.kt, reporter/src/funTest/kotlin/reporters/WebAppReporterTest.kt, reporter/src/main/kotlin/Reporter.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/NoticeReporter.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, reporter/src/main/kotlin/reporters/WebAppReporter.kt, test-utils/src/main/kotlin/Utils.kt
=> Reporter test improvements

model/src/main/kotlin/util/FindingsMatcher.kt, model/src/test/kotlin/utils/FindingsMatcherTest.kt
=> Findings matcher text improvements

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
=> PipTest: Update expected test dependencies

spdx-utils/src/main/kotlin/SpdxExpression.kt
=> SpdxExpression: Improve class documentation a bit

analyzer/src/main/kotlin/Analyzer.kt
=> Analyzer: Verify project types to match the respective package manager

analyzer/src/main/kotlin/managers/Cargo.kt
And improve the failure message along the way.
=> Cargo: Use require() to shorten code

analyzer/src/test/kotlin/managers/utils/PackageJsonUtilsTest.kt, reporter/src/funTest/kotlin/reporters/NoticeReporterTest.kt
=> Consistently use the "should" infix operator in tests

analyzer/src/funTest/assets/projects/synthetic/cargo-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/cargo-subcrate-client-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/cargo-subcrate-integration-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/cargo-subcrate-lib-expected-output.yml, analyzer/src/main/kotlin/managers/Cargo.kt
=> Cargo: Use a separate scope for build dependencies

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt, utils/src/main/kotlin/DeclaredLicenseProcessor.kt, utils/src/test/kotlin/DeclaredLicenseProcessorTest.kt
=> Improve processing of declared license URLs

docs/Configuration.md, docs/examples/cargo.ort.yml
See individual commits for details. Complementary to https://github.com/heremaps/oss-review-toolkit/pull/1805
=> docs: Add .ort.yml example for Cargo (Rust)

cli/src/funTest/kotlin/MainTest.kt, downloader/build.gradle.kts, downloader/src/main/kotlin/vcs/Cvs.kt, spdx-utils/build.gradle.kts, spdx-utils/src/main/kotlin/LicenseFileMatcher.kt, spdx-utils/src/main/kotlin/SpdxUtils.kt, spdx-utils/src/test/kotlin/SpdxUtilsTest.kt, utils/build.gradle.kts, utils/src/main/kotlin/Extensions.kt, utils/src/main/kotlin/Utils.kt
=> More utilities

analyzer/src/main/kotlin/managers/Cargo.kt, model/src/main/kotlin/util/FindingsMatcher.kt
=> More Cargo code improvements

downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, model/src/main/kotlin/util/FindingsMatcher.kt, spdx-utils/src/main/kotlin/LicenseFileMatcher.kt
=> Matcher cleanups

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
=> PipTest: Update the expected Werkzeug version to 0.16.0

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt, spdx-utils/src/main/kotlin/SpdxLicenseAliasMapping.kt, spdx-utils/src/test/kotlin/SpdxDeclaredLicenseMappingTest.kt, spdx-utils/src/test/kotlin/SpdxLicenseAliasMappingTest.kt
=> Spdx test fixes

analyzer/build.gradle.kts, analyzer/src/main/kotlin/Analyzer.kt
This is an experiment to execute different package managers in parallel
to check how it influences the analyzer performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1615)
=> analyzer: Run package managers in parallel

scanner/src/main/kotlin/LocalScanner.kt
Instead use the approach suggested in the documentation of
`newFixedThreadPoolContext`:
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/new-fixed-thread-pool-context.html
=> scanner: Do not use the obsolete coroutines API anymore

clearly-defined/src/main/kotlin/ClearlyDefinedService.kt, cli/src/main/kotlin/commands/ScannerCommand.kt, model/src/main/kotlin/PackageCuration.kt, model/src/main/kotlin/ScannerDetails.kt, spdx-utils/build.gradle.kts, spdx-utils/src/main/kotlin/SpdxLicense.kt, spdx-utils/src/main/kotlin/SpdxLicenseException.kt, utils/src/main/kotlin/Utils.kt
=> Always use named argument for `ignoreCase` in `String.equals()`

analyzer/src/main/kotlin/managers/Npm.kt
=> Npm unlicensed

analyzer/src/main/kotlin/managers/Npm.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, spdx-utils/build.gradle.kts, spdx-utils/src/main/kotlin/SpdxLicense.kt
=> Spdx non license ids

analyzer/src/main/kotlin/managers/utils/DotNetSupport.kt
=> Dot net improvements

scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt
=> Scanner collections

analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/NuGet.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/Pip.kt, analyzer/src/main/kotlin/managers/Pub.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/utils/PackageJsonUtils.kt, evaluator/src/test/kotlin/TestData.kt, model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/ScanSummary.kt, reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt
=> Avoid temporary creations of collections in more places

docs/Configuration.md, model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/config/Curations.kt, model/src/main/kotlin/config/LicenseFindingCuration.kt, model/src/main/kotlin/config/RepositoryConfiguration.kt, model/src/main/kotlin/util/FindingCurationMatcher.kt, model/src/test/kotlin/config/LicenseFindingCurationTest.kt, model/src/test/kotlin/utils/FindingCurationMatcherTest.kt
has to be merged after https://github.com/heremaps/oss-review-toolkit/pull/1844.
=> License finding curations

docs/Configuration.md
=> Configuration.md: Remove a trailing comma

analyzer/src/main/kotlin/managers/Stack.kt
And provide a few real-world version string examples.
=> Stack: Support version numbers followed by a space

model/src/test/kotlin/utils/FindingsMatcherTest.kt
Only the top commit is relevant, maybe as a basis for a discussion about the use of random values in unit tests.
=> Random default values in tests

analyzer/src/funTest/assets/projects/synthetic/python3-django-expected-output.yml
=> PipTest: Update the expected pytz dependency to version 2019.3

downloader/src/main/kotlin/vcs/GitWorkingTree.kt
Git supports multiple remotes per working tree. Previously, simply the
first remote in the order reported by Git was used, but this is not
necessarily the remote that we want. We are interested in where the code
in the working tree comes from, so first try to use the remote that the
currently checked out branch pulls from, and only afterwards fall back
to "origin", if present, or the first other remote.
=> GitWorkingTree: First try to use the pull remote of the current branch

utils/src/main/kotlin/DeclaredLicenseProcessor.kt
=> DeclaredLicenseProcessor: Rewrite an empty-check before reducing

helper-cli/src/main/kotlin/commands/SortRepositoryConfigurationCommand.kt, helper-cli/src/main/kotlin/common/Utils.kt
=> SortRepositoryConfigurationCommand: Also sort curations

gradle.properties, spdx-utils/build.gradle.kts
See https://arturbosch.github.io/detekt/changelog.html#111.
=> Gradle: Upgrade detekt to version 1.1.1

analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml
=> BundlerTest: Update an expected homepage URL to use https

docker/lib
=> Docker build proxy

scanner/src/main/kotlin/scanners/Licensee.kt
See https://github.com/licensee/licensee/releases/tag/v9.12.0.
=> Licensee: Upgrade to version 9.12.0

analyzer/src/main/kotlin/managers/Pub.kt, downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, utils/src/main/kotlin/ArchiveUtils.kt, utils/src/main/kotlin/FileMatcher.kt
=> Consistently use all lower case for `filename` vars

docs/GettingStarted.md
*Edit:* I decided to not add the result files for now but only apply the wording improvements.
=> GettingStarted: Improve the wording a bit

Jenkinsfile, cli/src/main/kotlin/commands/DownloaderCommand.kt, cli/src/main/kotlin/commands/ScannerCommand.kt, docs/GettingStarted.md
=> Align parameters

.appveyor.yml, .travis.yml, README.md, analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-py.yml, analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml, analyzer/src/funTest/assets/projects/synthetic/conan-py/conanfile.py, analyzer/src/funTest/assets/projects/synthetic/conan-txt/conanfile.txt, analyzer/src/funTest/kotlin/managers/ConanTest.kt, analyzer/src/main/kotlin/managers/Conan.kt, analyzer/src/main/resources/META-INF/services/com.here.ort.analyzer.PackageManagerFactory, analyzer/src/test/kotlin/managers/PackageManagerTest.kt, docker/run/Dockerfile
This PR adds support for Conan package manager for the Analyzer. There are also two funTests for Conan module. Additions to travis, appvoyer and Dockerfile have been done as well.
Let's next work on this PR with review and test processes and see if something needs to be changed or added. In case of questions or comments, please contact me, @kallesoranko or @benmarsden
=> Conan package manager support for Analyzer

analyzer/src/funTest/assets/projects/synthetic/conan-py/.gitignore, analyzer/src/funTest/assets/projects/synthetic/conan-txt/.gitignore
=> analyzer: Ignore files generated by Conan in Git

docker/run/Dockerfile
=> Fix installing Conan in the Docker image to run ORT

analyzer/src/main/kotlin/Analyzer.kt
Make sure that the coroutine dispatcher and the wrapped thread pool are
always closed. Otherwise, if an uncatched exception is thrown in any of the
package managers, the process never finishes, because the main thread
throws an exception at the end of the `coroutineScope`, but the thread
pool is still running.
=> analyzer: Make sure the coroutine dispatcher is closed

.codecov.yml
=> codecov: Add some missing path fixes for newer modules

model/src/main/kotlin/config/LicenseFindingCuration.kt
=> LicenseFindingCuration: Do not serialize null values

analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
=> PipTest: Upgrade expected pyparsing and six dependencies

docker/build.sh, docker/run.sh, docker/run/Dockerfile, docker/test.sh
=> docker: Upgrade composer to the version now available in Debian Sid

analyzer/src/main/kotlin/Analyzer.kt
=> Analyzer: Convert try-finally to use() for the dispatcher

scanner/src/main/kotlin/scanners/Askalono.kt
See https://github.com/amzn/askalono/releases/tag/0.4.0.
=> Askalono: Upgrade to version 0.4.0

analyzer/build.gradle.kts, analyzer/src/main/kotlin/Analyzer.kt, analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt, analyzer/src/main/kotlin/curation/FallbackPackageCurationProvider.kt, analyzer/src/main/kotlin/curation/FilePackageCurationProvider.kt, analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt, analyzer/src/test/kotlin/curation/FilePackageCurationProviderTest.kt, cli/src/main/kotlin/commands/AnalyzerCommand.kt, helper-cli/src/main/kotlin/common/Utils.kt
=> Support multiple curation providers

analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
=> PipTest: Upgrade the expected pyparsing version to 2.4.5

helper-cli/src/main/kotlin/commands/ExportPathExcludesCommand.kt, helper-cli/src/main/kotlin/commands/ExtractRepositoryConfigurationCommand.kt, helper-cli/src/main/kotlin/commands/FormatRepositoryConfigurationCommand.kt, helper-cli/src/main/kotlin/commands/GenerateProjectExcludesCommand.kt, helper-cli/src/main/kotlin/commands/GenerateRuleViolationResolutionsCommand.kt
=> Helper-cli: Describe the parameters of several commands.

analyzer/src/main/kotlin/managers/GoDep.kt, cli/src/main/kotlin/commands/DownloaderCommand.kt, model/src/main/kotlin/PackageCuration.kt
=> Slightly simplify code by using require()

gradle.properties
See https://blog.jetbrains.com/kotlin/2019/11/kotlin-1-3-60-released/.
=> Gradle: Upgrade Kotlin to version 1.3.60

evaluator/src/main/kotlin/LicenseView.kt, reporter/src/funTest/assets/static-html-reporter-test-expected-output.html, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, spdx-utils/src/main/kotlin/SpdxExpression.kt, spdx-utils/src/test/kotlin/SpdxExpressionTest.kt, utils/src/main/kotlin/DeclaredLicenseProcessor.kt
=> rules/reporter: Support Spdx WITH operator for concluded and declared licenses

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt, build.gradle.kts, clearly-defined/build.gradle.kts, clearly-defined/src/main/kotlin/ClearlyDefinedService.kt, clearly-defined/src/test/kotlin/ClearlyDefinedServiceTest.kt, cli/src/main/kotlin/Main.kt, cli/src/main/kotlin/commands/ClearlyDefinedUploadCommand.kt, downloader/src/main/kotlin/VcsHost.kt, utils/src/main/kotlin/Utils.kt
=> Add a sub-command to upload curations to ClearlyDefined 

analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/utils/DotNetSupport.kt, utils/src/main/kotlin/OkHttpClientHelper.kt
=> Always use any specified HTTP(S) proxy

analyzer/src/main/kotlin/managers/Npm.kt
See e.g. https://github.com/dominictarr/pause-stream/blob/f59aad0/package.json#L28-L31.
=> NPM: Support invalid license nodes with an array of licenses

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt, clearly-defined/src/main/kotlin/ClearlyDefinedService.kt, clearly-defined/src/test/kotlin/ClearlyDefinedServiceTest.kt, cli/src/main/kotlin/commands/ClearlyDefinedUploadCommand.kt
=> ClearlyDefined improvements

Jenkinsfile
=> Jenkinsfile: Support specifying tags as VCS revisions

analyzer/src/main/kotlin/managers/Npm.kt
=> Npm: Fix quoting "url" in code comments

.gitignore, docker/lib
=> Docker improvements

downloader/src/main/kotlin/VcsHost.kt, reporter/src/main/kotlin/reporters/ReportTableModel.kt, reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
=> VCS link improvements

downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/Mercurial.kt
=> Take the Git / Mercurial exit code into account

downloader/src/main/kotlin/vcs/Subversion.kt, downloader/src/test/kotlin/vcs/SubversionTest.kt
=> SVN cleanups

downloader/src/main/kotlin/vcs/Subversion.kt
This fixes SVNException being exposed to the user and resembles more
closely the previous implementation when the "svn" CLI was called.
This is a fixup for 3d14475.
=> Subversion: Return empty results in case of an SVNException

scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml, scanner/src/funTest/kotlin/storages/AbstractStorageTest.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/ScanResultsStorage.kt, scanner/src/main/kotlin/storages/FileBasedStorage.kt, scanner/src/main/kotlin/storages/NoStorage.kt, scanner/src/main/kotlin/storages/PostgresStorage.kt
Improve error handling in the scan results storage. See the commit messages for details.
=> Scan results storage errors

model/src/main/kotlin/TextLocation.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/Licensee.kt
To get rid of the magic numbers.
=> TextLocation: Add a constant for unknown line numbers

analyzer/src/main/kotlin/managers/Cargo.kt
In the previous code, the same package ID string was search for " "
three times, with indexOf(), substringBefore(), and split(). Change that
to only a single split() call for clarity and efficiency.
=> Cargo: Split a dependency's package ID only once

analyzer/src/main/kotlin/PackageManager.kt, spdx-utils/src/main/kotlin/SpdxUtils.kt
=> Ignore VCS directories in the Analyzer

build.gradle.kts
=> Fix IntelliJ not finding a root assemble task

analyzer/src/funTest/kotlin/GitRepoTest.kt
This reverts commit 4dd2f32ee214f692f2c1a566208c8e2f4673b293.
=> Revert "GitRepoTest: Temporarily disable the test on Travis"

analyzer/src/funTest/kotlin/managers/GradleKotlinScriptTest.kt
This reverts commit 4b78f8b28f262a0e9f78f5c3a717da03c1676436.
=> Revert "GradleKotlinScriptTest: Temporarily disable the test on Travis"

build.gradle.kts, gradle.properties
=> Detekt upgrade

build.gradle.kts
By explicitly specifying the "packageListUrl" property.
=> Gradle: Fix running the "dokka" task

analyzer/src/main/kotlin/managers/Cargo.kt
=> Cargo: Improve readability of getResolvedVersion() a bit

downloader/src/funTest/kotlin/CvsDownloadTest.kt, downloader/src/funTest/kotlin/SubversionDownloadTest.kt
=> downloader: Fix a few trivial formatting / indentation issues in tests

downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Cvs.kt, downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/GitRepo.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, downloader/src/main/kotlin/vcs/Subversion.kt
=> VCS API improvements

analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-lockfile.yml
=> BundlerTest: Update expected output to contain the homepage URL

gradle.properties
See https://github.com/arturbosch/detekt/releases/tag/1.2.2.
=> Gradle: Upgrade the detekt plugin to version 1.2.2

spdx-utils/src/main/kotlin/SpdxUtils.kt, spdx-utils/src/test/kotlin/SpdxUtilsTest.kt
Like the one added in 34113ba.
=> SpdxUtilsTest: Loop over VCS_DIRECTORIES to not forget new entries

.travis.yml, README.md, analyzer/src/funTest/assets/projects/synthetic/gomod-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/gomod/go.mod, analyzer/src/funTest/assets/projects/synthetic/gomod/main.go, analyzer/src/funTest/kotlin/managers/GoModTest.kt, analyzer/src/main/kotlin/managers/GoMod.kt, analyzer/src/main/resources/META-INF/services/com.here.ort.analyzer.PackageManagerFactory, analyzer/src/test/kotlin/managers/PackageManagerTest.kt, docs/Configuration.md, docs/examples/go-mod.ort.yml
The [Go Modules](https://github.com/golang/go/wiki/Modules) package manager for Go.
=> GoMod: Initial rather experimental implementation

analyzer/src/funTest/kotlin/managers/BundlerTest.kt, analyzer/src/funTest/kotlin/managers/GoDepTest.kt, analyzer/src/funTest/kotlin/managers/PhpComposerTest.kt, analyzer/src/funTest/kotlin/managers/PubTest.kt, downloader/src/funTest/kotlin/BabelTest.kt, downloader/src/funTest/kotlin/BeanUtilsTest.kt, model/src/test/kotlin/config/OrtConfigurationTest.kt, model/src/test/kotlin/config/RepositoryConfigurationTest.kt
=> Reduce a bit of repetitive code in tests by using "with"

README.md
=> README: Improve the wording for GoMod support

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt, model/src/main/kotlin/PackageCurationData.kt, model/src/main/kotlin/VcsInfo.kt, model/src/main/kotlin/VcsInfoCurationData.kt, model/src/test/kotlin/PackageCurationTest.kt
=> Curation data improvements

docker/README.md
=> docker: Add a separate README to explain the different Docker files

model/src/main/kotlin/Provenance.kt, reporter/src/main/kotlin/reporters/NoticeByPackageReporter.kt, scanner/src/main/kotlin/LocalScanner.kt
Add a function to calculate a hash of the string representation to the
Provenance class to reduce code duplication.
=> Provenance: Add a function to calculate the hash

analyzer/src/main/kotlin/managers/Cargo.kt, cli/src/main/kotlin/commands/RequirementsCommand.kt, docker/run.sh, docker/run/Dockerfile
=> Docker fix PIP wheel & Cargo stuff

model/src/main/kotlin/LicenseFindings.kt, reporter/src/main/kotlin/reporters/NoticeByPackageReporter.kt, utils/src/main/kotlin/CopyrightStatementsProcessor.kt, utils/src/test/kotlin/CopyrightStatementsProcessorTest.kt
=> CopyrightStatementsProcessor: Minor code style improvements

analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-py.yml, analyzer/src/funTest/kotlin/managers/ConanTest.kt
=> Fix ConanTest

downloader/src/main/kotlin/vcs/Cvs.kt
=> Cvs: Implement the new API for initializing / updating the working tree 

downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/GitRepo.kt
=> GitRepo: Implement the new API for initializing / updating the working tree

gradle.properties
See https://arturbosch.github.io/detekt/changelog.html#130.
=> Gradle: Upgrade detekt to version 1.3.0

analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
=> PipTest: Update the expected pyparsing version to 2.4.6

docs/config-file-ort-yml.md
Fix copy-paste mistake after last documentation update.
=> docs: Fix incorrect example exclude and resolution values

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt, build.gradle.kts, evaluator/src/main/kotlin/PackageRule.kt, evaluator/src/main/kotlin/Rule.kt
=> Dokka fixes

model/src/main/kotlin/CopyrightFindings.kt
=> CopyrightFindings: Clarify the co-existance with CopyrightFinding

analyzer/src/funTest/kotlin/managers/DotNetTest.kt, analyzer/src/funTest/kotlin/managers/NuGetTest.kt, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/NuGet.kt, analyzer/src/main/kotlin/managers/utils/DotNetSupport.kt
=> DotNet improvements

.appveyor.yml, .travis.yml, analyzer/src/funTest/assets/projects/synthetic/npm-babel/package.json, analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/npm-version-urls/package.json, analyzer/src/funTest/assets/projects/synthetic/npm/no-lockfile/package.json, analyzer/src/funTest/assets/projects/synthetic/npm/node-modules/package-lock.json, analyzer/src/funTest/assets/projects/synthetic/npm/node-modules/package.json, analyzer/src/funTest/assets/projects/synthetic/npm/package-lock/package.json, analyzer/src/funTest/assets/projects/synthetic/npm/shrinkwrap/npm-shrinkwrap.json, analyzer/src/funTest/assets/projects/synthetic/npm/shrinkwrap/package.json, analyzer/src/funTest/assets/projects/synthetic/yarn-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/yarn/package.json, analyzer/src/main/kotlin/managers/Yarn.kt, docker/run/Dockerfile, reporter-web-app/build.gradle.kts
=> Synthetic package.json cleanup + Yarn upgrade

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt
See individual commits for details
=> Declared license mapping update

downloader/src/funTest/kotlin/SubversionWorkingTreeTest.kt
=> SubversionWorkingTreeTest: Add the new "docutils-0.16" tag as expected

README.md
=> README: Add a badge for the REUSE status

gradle.properties
See https://arturbosch.github.io/detekt/changelog.html#140.
=> Gradle: Upgrade detekt to version 1.4.0

model/src/main/kotlin/Environment.kt
=> Improvements to the Environment class

README.md
=> Update instructions for the new multi-stage Docker file 

.gitattributes
=> Update Git attributes

model/src/main/kotlin/CopyrightFindings.kt
=> CopyrightFindings: Fix a typo

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt, analyzer/src/test/kotlin/managers/utils/MavenSupportTest.kt, utils/src/main/kotlin/OkHttpClientHelper.kt, utils/src/main/kotlin/Os.kt
=> Add proxy support for Maven projects

cli/src/main/kotlin/commands/ReporterCommand.kt, reporter/src/main/kotlin/DefaultLicenseTextProvider.kt, reporter/src/main/kotlin/ReporterInput.kt, reporter/src/main/kotlin/model/Statistics.kt, reporter/src/main/kotlin/reporters/EvaluatedModelReporter.kt, reporter/src/main/kotlin/utils/StatisticsCalculator.kt
=> Fix various reporter package vs directory issues

downloader/src/funTest/kotlin/vcs/CvsWorkingTreeTest.kt
=> CvsWorkingTreeTest: Disable tests that currently fail due to SF issues

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml, analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml, analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml
=> Fix Stack test (and Pip test)

reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, scanner/src/main/kotlin/ScanResultsStorage.kt, utils/src/main/kotlin/Utils.kt
This allows a database administrator to see what applications are connected to the server and what resources they are using.
=> Set the PostgreSQL application name

downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Subversion.kt
=> Subversion fixes

downloader/src/funTest/kotlin/vcs/GitWorkingTreeTest.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/GitWorkingTree.kt
=> Continue the effort to replace Git CLI with JGit

analyzer/src/funTest/assets/projects/synthetic/yarn-workspaces-expected-output.yml, analyzer/src/main/kotlin/managers/Npm.kt
=> Yarn: Implement support for workspaces

docs/how-to-add-support-for-new-package-manager.md
While at it improve the wording of the sentence.
=> docs: Fix a typo

.detekt.yml, spdx-utils/build.gradle.kts, spdx-utils/src/main/kotlin/SpdxLicense.kt, spdx-utils/src/main/kotlin/SpdxLicenseException.kt
=> Detekt vs ktlint

docs/getting-started.md
=> getting-started: Fix broken links

README.md
=> README: Use the correct REUSE badge / info URLs

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
=> PipTest: Update the expected Werkzeug version to 1.0.0

analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml, analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-lockfile.yml
=> BundlerTest: Update the expected Rack homepage URL

downloader/src/main/kotlin/vcs/GitWorkingTree.kt
Not just GitAPIException, as invalid URIs may throw an
NotSupportedException.
Fixes #2191.
=> GitWorkingTree: Handle any exception thrown by JGit as an error

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt, analyzer/src/test/kotlin/managers/utils/MavenSupportTest.kt
=> MavenSupport: Work around the common mistake to omit the provider

Dockerfile
=> Dockerfile: Upgrade Debian Sid packages to be able to build again

Dockerfile
=> Dockerfile: Fix a typo in a comment

docs/examples/licenses.yml
=> examples/licenses: Fix a typo

docs/config-file-ort-yml.md
=> docs/config-file-ort-yml: Fix a typo

docs/config-file-copyright-garbage-yml.md, docs/config-file-curations-yml.md, docs/examples/curations.yml, docs/examples/rules.kts, docs/file-rules-kts.md
See individual commit for details
=> Minor docs fixes

model/src/main/kotlin/config/Excludes.kt
=> Excludes: Add explicit return type for readability

downloader/src/main/kotlin/VersionControlSystem.kt
=> Disregard VCS types whose CLI is not in PATH

Jenkinsfile
=> Jenkinsfile credentials

gradle/wrapper/gradle-wrapper.properties
For the release notes see:
https://docs.gradle.org/6.2/release-notes.html
=> Upgrade Gradle to version 6.2

model/src/main/kotlin/utils/FindingsMatcher.kt
Remove the when in favor of returning early in order to eliminate a
partially unneeded variable and to reduce the level of nesting.
=> FindingsMatcher: Minor code style improvement

helper-cli/src/main/kotlin/common/Utils.kt
=> Fix some inspection hints in the helper CLI

cli/src/main/kotlin/commands/ScannerCommand.kt, utils/src/funTest/kotlin/storage/HttpFileStorageTest.kt, utils/src/main/kotlin/storage/LocalFileStorage.kt, utils/src/main/kotlin/storage/XZCompressedLocalFileStorage.kt, utils/src/test/kotlin/storage/LocalFileStorageTest.kt, utils/src/test/kotlin/storage/XZCompressedLocalFileStorageTest.kt
=> Compressed local file storage

Dockerfile, Jenkinsfile, analyzer/src/main/kotlin/managers/Gradle.kt, scripts/set_gradle_proxy.sh
=> Set any proxy also when running ORT in Docker

helper-cli/src/main/kotlin/commands/GenerateScopeExcludesCommand.kt
=> GenerateScopeExcludesCommand: Add `pmd` scope

README.md
=> README: Trim trailing whitespace

cli/src/main/kotlin/OrtMain.kt
=> OrtMain: Trivially simplify a condition in fixupUserHomeProperty()

downloader/src/main/kotlin/Downloader.kt
=> Minor downloader improvements

model/src/test/kotlin/ProjectAnalyzerResultTest.kt, scanner/src/funTest/kotlin/storages/AbstractStorageTest.kt
Use some kotlintest matchers instead of manually checking the content of collections and maps.
=> Kotlintest matchers

scripts/set_gradle_proxy.sh
=> set_gradle_proxy: Also extract username and password

scripts/import_proxy_certs.sh
=> Improve import proxy

gradle.properties, gradle/wrapper/gradle-wrapper.properties, gradlew.bat
=> Dependency updates

analyzer/src/main/kotlin/managers/Npm.kt
Proposed as replacement for #2248.
=> Npm: Handle file reference in declared license

cli/src/main/kotlin/commands/ScannerCommand.kt, model/src/main/kotlin/OrtResult.kt, scanner/src/main/kotlin/Scanner.kt
=> ScannerCommand: Add an option to skip excluded packages

analyzer/src/main/kotlin/managers/Maven.kt
=> Maven: Add "com.sun:tools:" as possible coordinates for tools.jar

gradle.properties
See https://arturbosch.github.io/detekt/changelog.html#160.
=> Gradle: Upgrade the detekt plugin to version 1.6.0

downloader/src/main/kotlin/vcs/Git.kt
The check was removed as part of the JGit migration in 9634064, but we
still need it as we still use the Git CLI to update the working tree.
=> Git: Re-add the Git CLI version check

cli/src/main/kotlin/commands/DownloaderCommand.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Cvs.kt, downloader/src/main/kotlin/vcs/GitBase.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, downloader/src/main/kotlin/vcs/Subversion.kt
=> Downloader VCS defaults

analyzer/src/main/kotlin/managers/Npm.kt, utils/src/main/kotlin/Extensions.kt, utils/src/test/kotlin/ExtensionsTest.kt
=> Symlink tests

cli/src/main/kotlin/commands/DownloaderCommand.kt, utils/src/main/kotlin/ArchiveUtils.kt
=> Add support for unpacking ".tar.xz" archives

reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
Fix handling erroneous dependency trees in the evaluated model.
=> Evaluated model fix

reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json, reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml, reporter/src/main/kotlin/model/EvaluatedModel.kt, reporter/src/main/kotlin/model/EvaluatedModelMapper.kt, reporter/src/main/kotlin/model/Statistics.kt, reporter/src/main/kotlin/utils/StatisticsCalculator.kt
To have the stats together in a single place.
=> Move license stats from `EvaluatedModel` to `Statistics`

.travis.yml, analyzer/src/funTest/kotlin/GitRepoTest.kt
=> Travis: Upgrade to the current Ubuntu LTS release 18.04

reporter/src/main/kotlin/model/CopyrightStatement.kt, reporter/src/main/kotlin/model/DependencyTreeNode.kt, reporter/src/main/kotlin/model/EvaluatedFinding.kt, reporter/src/main/kotlin/model/EvaluatedFindingType.kt, reporter/src/main/kotlin/model/EvaluatedModel.kt, reporter/src/main/kotlin/model/EvaluatedModelMapper.kt, reporter/src/main/kotlin/model/EvaluatedOrtIssue.kt, reporter/src/main/kotlin/model/EvaluatedOrtIssueType.kt, reporter/src/main/kotlin/model/EvaluatedPackage.kt, reporter/src/main/kotlin/model/EvaluatedPackagePath.kt, reporter/src/main/kotlin/model/EvaluatedProcessedDeclaredLicense.kt, reporter/src/main/kotlin/model/EvaluatedRuleViolation.kt, reporter/src/main/kotlin/model/EvaluatedScanResult.kt, reporter/src/main/kotlin/model/LicenseId.kt, reporter/src/main/kotlin/model/ScopeName.kt
Several improvements of the evaluated model. Please see the commit messages for details.
=> Evaluated model improvements

README.md
=> Fix typo on sslmode value

reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
=> EvaluatedModelMapper: Improve handling of erroneous dependency trees

.mailmap
=> Update mailmap with recent contributors

scanner/src/funTest/kotlin/scanners/AbstractScannerTest.kt, scanner/src/funTest/kotlin/scanners/AskalonoScannerTest.kt, scanner/src/funTest/kotlin/scanners/BoyterLcScannerTest.kt, scanner/src/funTest/kotlin/scanners/LicenseeScannerTest.kt, scanner/src/funTest/kotlin/scanners/ScanCodeScannerTest.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt
=> Rework scanner tests

analyzer/src/main/kotlin/managers/Npm.kt
Prefer using FileFilter with listFiles() instead of first listing all
files and then filtering them later.
=> Npm: Filter the file list already while generating it

scanner/src/funTest/kotlin/scanners/FileCounterScannerTest.kt
=> File counter test improvements

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
=> PipTest: Upgrade the expected click version to 7.1

build.gradle.kts, cli/src/main/kotlin/commands/ScannerCommand.kt, scanner/src/funTest/kotlin/scanners/AbstractScannerTest.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/FileCounter.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt
=> Slightly refactor the functions to scan a path

analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
=> NpmVersionUrlTest: Update the expected minimist dependency

model/src/main/kotlin/config/RepositoryConfiguration.kt
=> RepositoryConfiguration: Make the value filter classes private

helper-cli/src/main/kotlin/commands/ListStoredScanResultsCommand.kt, model/src/main/kotlin/Result.kt, scanner/src/funTest/kotlin/storages/AbstractStorageTest.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/ScanResultsStorage.kt, scanner/src/main/kotlin/storages/FileBasedStorage.kt, scanner/src/main/kotlin/storages/NoStorage.kt, scanner/src/main/kotlin/storages/PostgresStorage.kt
Use a result class for the return values of `ScanResultsStorage`.
=> Storage result

analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/npm-version-urls/package-lock.json
Also add a lockfile to prevent the frequent updates of the expected results.
=> Fix npm version url test

.reuse/dep5
=> reuse: Fix the source URL after the repository move

analyzer/src/main/kotlin/managers/Pip.kt, downloader/src/funTest/kotlin/vcs/GitWorkingTreeTest.kt
=> More URL updates

analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/Sbt.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, helper-cli/src/main/kotlin/commands/ExportLicenseFindingCurationsCommand.kt, helper-cli/src/main/kotlin/commands/ExportPathExcludesCommand.kt, helper-cli/src/main/kotlin/commands/FormatRepositoryConfigurationCommand.kt, helper-cli/src/main/kotlin/commands/GenerateProjectExcludesCommand.kt, helper-cli/src/main/kotlin/commands/GenerateScopeExcludesCommand.kt, helper-cli/src/main/kotlin/commands/SortRepositoryConfigurationCommand.kt, reporter/src/main/kotlin/model/EvaluatedModelMapper.kt, scanner/src/main/kotlin/ScanResultsStorage.kt, utils/src/main/kotlin/Extensions.kt, utils/src/main/kotlin/Os.kt, utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/UtilsTest.kt
=> Miscellaneous improvements

.github/workflows/rebase.yml
=> Rebase action

scanner/src/funTest/kotlin/scanners/AbstractScannerTest.kt, scanner/src/funTest/kotlin/scanners/AskalonoScannerTest.kt, scanner/src/funTest/kotlin/scanners/BoyterLcScannerTest.kt, scanner/src/funTest/kotlin/scanners/LicenseeScannerTest.kt, scanner/src/funTest/kotlin/scanners/ScanCodeScannerTest.kt
=> Abstract scanner fixes

downloader/src/funTest/kotlin/vcs/CvsDownloadTest.kt, downloader/src/funTest/kotlin/vcs/CvsWorkingTreeTest.kt
=> CVS maintenance

reporter-web-app/src/components/PackageLicenses.js, reporter-web-app/src/models/WebAppPackage.js
=> reporter-web-app: Fix 't.webAppPackage is undefined' error

analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/Cargo.kt, analyzer/src/main/kotlin/managers/Conan.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/GoMod.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/Pip.kt, analyzer/src/main/kotlin/managers/Pipenv.kt, analyzer/src/main/kotlin/managers/Pub.kt, analyzer/src/main/kotlin/managers/Sbt.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/Yarn.kt, cli/src/funTest/kotlin/OrtMainTest.kt, cli/src/main/kotlin/commands/RequirementsCommand.kt, downloader/src/main/kotlin/vcs/Cvs.kt, downloader/src/main/kotlin/vcs/GitBase.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/FileCounter.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, utils/src/main/kotlin/CommandLineTool.kt
=> RequirementsCommand: Show the version of found tools

analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/Pip.kt, analyzer/src/main/kotlin/managers/Pipenv.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/ScanCode.kt
If the substring is expected to be in the beginning.
=> Prefer removePrefix() over substringAfter()

scanner/src/main/kotlin/scanners/ScanCode.kt
=> ScanCode: Emphasize that the version string might span over multiple lines

analyzer/src/main/kotlin/managers/GoDep.kt
=> GoDep: Remove an eventual "v" prefix from the version string

.appveyor.yml, .travis.yml, build.gradle.kts, detekt-rules/src/main/kotlin/OrtCopyrightHeader.kt, detekt-rules/src/main/kotlin/OrtRuleSet.kt, model/src/main/kotlin/config/RuleViolationResolutionReason.kt, spdx-utils/build.gradle.kts
=> Implement the copyright check via detekt

Dockerfile
=> Dockerfile: Align the formatting for "apk add" to that for "apt-get install"

gradle.properties
See https://arturbosch.github.io/detekt/changelog.html#170.
=> Gradle: Upgrade the detekt plugin to version 1.7.0

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt, spdx-utils/src/main/kotlin/SpdxLicenseAliasMapping.kt, spdx-utils/src/test/kotlin/SpdxDeclaredLicenseMappingTest.kt, spdx-utils/src/test/kotlin/SpdxLicenseAliasMappingTest.kt
=> spdx-utils: Move the runtime key checks to unit tests 

README.md
=> README: Update the AppVeyor badge link for the oss-review-toolkit org

analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml
=> Test updates

analyzer/src/main/kotlin/managers/Sbt.kt
Newer versions of Sbt prompt the user for action if the directory
running Sbt in does neither contain a "build.sbt" file nor a "project"
directory. On Linux, the prompt is avoided with "-batch", but that
option is not supported on Windows. Also, wrapping the call in
"suppressInput" does not work on Windows as that just feeds "nul" into
stdin whereas (c)ontinue or (q)uit is expected.
As an easy measure, simply create a temporary directory with an empty
"build.sbt" file to run in. This should also work with older versions of
the official Sbt launcher [1] as well as third-party runners like
sbt-extras [2] which neither support a "--script-version" option.
[1] https://github.com/sbt/sbt-launcher-package
[2] https://github.com/paulp/sbt-extras
Signed-off-by: Sebastian Schuberth …
=> Sbt: Avoid an interactive prompt when getting the version

analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/GoMod.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/Pip.kt, analyzer/src/main/kotlin/managers/Pub.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/utils/MavenSupport.kt, utils/src/main/kotlin/Utils.kt
=> Add compatibility with virtualenv 20.0

.mailmap
=> mailmap: Consolidate dependabot commits

analyzer/src/main/kotlin/managers/Sbt.kt
Several minor improvements for SBT, see the commit messages for details.
=> SBT: Minor improvements

.appveyor.yml, .travis.yml
=> Improve Gradle distribution caching in CI

.gitattributes, scanner/src/test/kotlin/ScanCodeTest.kt
=> ScanCodeTest: Add comments about the misuse of the "resultFile"

analyzer/src/main/kotlin/managers/GoMod.kt, analyzer/src/main/kotlin/managers/Pub.kt, cli/src/main/kotlin/OrtMain.kt, cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/ClearlyDefinedUploadCommand.kt, cli/src/main/kotlin/commands/DownloaderCommand.kt, cli/src/main/kotlin/commands/EvaluatorCommand.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, cli/src/main/kotlin/commands/ScannerCommand.kt, utils/src/main/kotlin/Extensions.kt, utils/src/test/kotlin/ExtensionsTest.kt
=> Expand tilde fixes

reporter/src/main/kotlin/model/EvaluatedModel.kt, reporter/src/main/kotlin/reporters/EvaluatedModelReporter.kt, reporter/src/main/kotlin/reporters/WebAppReporter.kt
Disable pretty print for the JSON injected into the web app report.
=> Web App Reporter: Remove whitespace from JSON

model/src/main/kotlin/utils/SimplePackageConfigurationProvider.kt
=> SimplePackageConfigurationProvider: Fix a typo

scanner/src/main/kotlin/scanners/Licensee.kt
=> Licensee: Fix a typo

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
=> PipTest: Update the expected Werkzeug version

analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
=> Use the original Maven Scm object to determine the browsable URL

model/src/main/kotlin/VcsInfo.kt
=> VcsInfo: Simplify the implementation of merge()

gradle.properties
See https://arturbosch.github.io/detekt/changelog.html#173.
=> Gradle: Upgrade the detekt plugin to version 1.7.3

spdx-utils/src/main/kotlin/SpdxLicenseAliasMapping.kt
Found in
https://git.coolaj86.com/coolaj86/semver-utils.js/src/tag/v1.1.4/package.json#L21.
=> SpdxLicenseAliasMapping: Add APACHEv2

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt
=> Add declared license mappings

Dockerfile, scripts/import_proxy_certs.sh
=> Improvements to the proxy script

downloader/src/main/kotlin/vcs/Cvs.kt, downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/GitRepo.kt, downloader/src/main/kotlin/vcs/Mercurial.kt
=> Fix getting the Git Repo version

cli/src/main/kotlin/commands/RequirementsCommand.kt
=> Fix the Git Repo requirement check

analyzer/src/funTest/assets/projects/external/dart-http-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/pub-expected-output-any-version.yml, analyzer/src/funTest/assets/projects/synthetic/pub-expected-output-project-with-flutter.yml, analyzer/src/funTest/assets/projects/synthetic/pub/any-version/pubspec.yaml, analyzer/src/funTest/assets/projects/synthetic/pub/no-lockfile/pubspec.yaml, analyzer/src/funTest/assets/projects/synthetic/pub/project-with-flutter/pubspec.yaml, analyzer/src/main/kotlin/managers/Pub.kt
=> Various improvements to Pub meta-data parsing

model/src/test/kotlin/utils/LicenseResolverTest.kt
=> LicenseResolverTest: Some more tests

reporter-web-app/src/components/AboutModal.js
=> AboutModal: Fix a typo

reporter-web-app/src/components/PackageFindingsTable.js, reporter-web-app/src/models/WebAppOrtResult.js, reporter-web-app/src/models/WebAppScope.js, reporter-web-app/src/models/WebAppTreeNode.js, reporter-web-app/src/reducers/selectors.js
=> Reporter web app improvements

model/src/main/kotlin/config/PackageConfiguration.kt
=> PackageConfiguration: Do not serialize (default) null values

evaluator/src/test/kotlin/LicenseViewTest.kt, evaluator/src/test/kotlin/RuleSetTest.kt, evaluator/src/test/kotlin/TestData.kt, spdx-utils/src/main/kotlin/SpdxExpression.kt, utils/src/main/kotlin/DeclaredLicenseProcessor.kt, utils/src/test/kotlin/DeclaredLicenseProcessorTest.kt
=> Only allow valid license identifiers in processed declared licenses

model/src/main/kotlin/config/PackageConfiguration.kt, model/src/main/kotlin/utils/LicenseResolver.kt, model/src/test/kotlin/utils/LicenseResolverTest.kt
Documentation will be updated in a following PR.
=> Implement license finding curations for packages

cli/src/main/kotlin/commands/ScannerCommand.kt, utils/src/main/kotlin/storage/LocalFileStorage.kt, utils/src/main/kotlin/storage/XZCompressedLocalFileStorage.kt
=> Scan storage improvements

analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
=> PipTest: Update expected dependencies

analyzer/src/test/kotlin/managers/utils/NodeSupportTest.kt
=> NodeSupportTest: Fix a typo in a dummy "password"

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt
=> Add more declared license mappings

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt, model/src/main/kotlin/Severity.kt
=> Continue analysis on socket timeouts for ClearlyDefined

reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
Prior to this change license finding curations were not handled at all.
This change always applies license finding curation so that the report
becomes consistent with the HTML report concerning the application of
these curations.
=> EvaluatedModelMapper: Apply the license finding curations

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt, cli/src/main/kotlin/OrtMain.kt, downloader/src/funTest/kotlin/vcs/CvsWorkingTreeTest.kt, downloader/src/funTest/kotlin/vcs/GitWorkingTreeTest.kt, downloader/src/funTest/kotlin/vcs/MercurialWorkingTreeTest.kt, downloader/src/funTest/kotlin/vcs/SubversionWorkingTreeTest.kt, reporter/src/main/kotlin/reporters/NoticeByPackageReporter.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/ScanResultsStorage.kt, utils/src/main/kotlin/OkHttpClientHelper.kt, utils/src/main/kotlin/Utils.kt, utils/src/main/kotlin/storage/HttpFileStorage.kt
=> Rework ORT user home / data directory related code

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt, downloader/src/main/kotlin/Downloader.kt, helper-cli/src/main/kotlin/common/Utils.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, utils/src/main/kotlin/ProcessCapture.kt, utils/src/main/kotlin/Redirection.kt, utils/src/main/kotlin/storage/FileArchiver.kt
=> Temp dir improvements

Dockerfile
Do not run both commands that barely change and commands that often
change in a single layer, and reorder layers so that layers that barely
change come first, so subsequent layers are less often invalidated.
=> Dockerfile: Improve caching of layers

helper-cli/src/main/kotlin/commands/GenerateProjectExcludesCommand.kt, helper-cli/src/main/kotlin/common/Utils.kt
=> Minor helper cli improvements

reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
Fixes #2314.
Signed-off-by: Julia Schaak <julia.schaak@bosch.io>
=> Distinguish declared and detected licenses in CycloneDx reporter

reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
=> CycloneDxReporter: Apply a minor formatting fix

model/src/main/resources/reference.conf, model/src/test/kotlin/config/OrtConfigurationTest.kt
=> model: Add missing jdbc prefixes for PostgreSQL storage configuration

README.md
=> README: Document that at least PostgreSQL version 9.4 is required

README.md
=> README: Document that the PostgreSQL schema already needs to exist

Jenkinsfile, cli/src/main/kotlin/OrtMain.kt, model/src/main/kotlin/config/OrtConfiguration.kt
=> Allow to use an ORT configuration repository in the Jenkins pipeline

scanner/src/main/kotlin/storages/PostgresStorage.kt
=> PostgreSQL storage improvements

reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json, reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml, reporter/src/main/kotlin/model/DependencyTreeNode.kt, reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
=> DependencyTreeNode: Remove the no more needed `title` property

.appveyor.yml, .travis.yml, analyzer/src/main/kotlin/Analyzer.kt, analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/Pip.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/utils/DotNetSupport.kt, analyzer/src/main/kotlin/managers/utils/MavenSupport.kt, cli/src/main/kotlin/commands/ClearlyDefinedUploadCommand.kt, downloader/src/main/kotlin/Downloader.kt, helper-cli/src/main/kotlin/common/Utils.kt, reporter/src/main/kotlin/Reporter.kt, reporter/src/main/kotlin/reporters/AmazonOssAttributionBuilderReporter.kt, scanner/src/main/kotlin/Scanner.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, utils/src/main/kotlin/OkHttpClientHelper.kt, utils/src/main/kotlin/storage/HttpFileStorage.kt
=> Merge HTTP cache dirs

analyzer/src/funTest/assets/projects/synthetic/maven/pom.xml, reporter-web-app/src/components/SummaryView.js
=> Some fixes for alerts reported by LGTM.com

model/src/main/kotlin/utils/OrtResultExtensions.kt, reporter/src/funTest/assets/NPM-is-windows-1.0.2-expected-NOTICE, reporter/src/funTest/assets/notice-by-package-reporter-expected-results, reporter/src/funTest/assets/notice-by-package-reporter-expected-results-with-license-files, reporter/src/funTest/assets/npm-test-with-exclude-expected-NOTICE, reporter/src/funTest/assets/npm-test-without-exclude-expected-NOTICE, reporter/src/funTest/kotlin/reporters/NoticeByPackageReporterTest.kt, reporter/src/main/kotlin/reporters/AbstractNoticeReporter.kt
Handle concluded and declared licenses in the notice reporter.
=> Notice reporter licenses

analyzer/src/main/kotlin/Analyzer.kt, downloader/src/main/kotlin/Downloader.kt, reporter/src/main/kotlin/Reporter.kt
=> Remove tool names

helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt, model/src/main/kotlin/CopyrightFindings.kt, model/src/main/kotlin/LicenseFinding.kt, model/src/main/kotlin/LicenseFindings.kt, model/src/main/kotlin/TextLocation.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, reporter/src/main/kotlin/utils/Comparators.kt, spdx-utils/src/main/kotlin/SpdxUtils.kt, utils/src/main/kotlin/CopyrightStatementsProcessor.kt
=> Static comparators

downloader/src/main/kotlin/vcs/Git.kt
Override (the by default empty) configureJSch() which gets called by
createDefaultJSch() to further configure JSch instead of overriding
createDefaultJSch() itself. Also, do not set non-host-specific
configuration on the session, but globally on JSch.
=> Git: Slightly refactor configuring JSch

helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
As specifying --severity only makes sense if --only-offending is also
specified, choose a name which makes this relation more obvious.
=> ListLicensesCommand: Rename the options --only-offending and --severity

Jenkinsfile
In case optional steps, like scanning, are omitted, we cannot hard-code
the result file name in the next step. Solve this by creating a symbolic
link with a constant name that always points to the current result file.
=> Jenkinsfile: Fix picking the result file when skipping steps

reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json, reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml, reporter/src/main/kotlin/model/DependencyTreeNode.kt, reporter/src/main/kotlin/model/EvaluatedOrtIssue.kt, reporter/src/main/kotlin/model/EvaluatedPackage.kt, reporter/src/main/kotlin/model/EvaluatedProcessedDeclaredLicense.kt, reporter/src/main/kotlin/model/EvaluatedRuleViolation.kt, reporter/src/main/kotlin/model/EvaluatedScanResult.kt
This results in a bit smaller files.
=> EvaluatedModel: Do not serialize several empty / null fields anymore

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt
Found in:
- https://github.com/RIAEvangelist/easy-stack/blob/5ca591d/package.json#L27
- https://github.com/RIAEvangelist/node-ipc/blob/3c95b0e/package.json#L55
=> SpdxDeclaredLicenseMapping: Add DBAD

spdx-utils/src/main/kotlin/SpdxExpression.kt, spdx-utils/src/test/kotlin/SpdxExpressionTest.kt, utils/src/test/kotlin/DeclaredLicenseProcessorTest.kt
=> Remove the spdxLicenses function

model/src/main/kotlin/ScanSummary.kt
=> ScanSummary: Make use of Jackson's syntactic sugar for Kotlin

gradle.properties
See https://github.com/detekt/detekt/releases/tag/v1.9.0.
=> Gradle: Upgrade the detekt plugin to version 1.9.0

spdx-utils/src/main/antlr/org/ossreviewtoolkit/spdx/SpdxExpression.g4, spdx-utils/src/main/kotlin/Extensions.kt, spdx-utils/src/main/kotlin/SpdxExpression.kt, spdx-utils/src/main/kotlin/SpdxExpressionDefaultVisitor.kt, spdx-utils/src/test/kotlin/SpdxExpressionParserTest.kt, spdx-utils/src/test/kotlin/SpdxExpressionTest.kt
Improve the inheritance tree of `SpdxExpression`, see the commit messages for details.
=> SPDX Improvements

reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
Invert the filter condition in order to fix-up 4f6f87b.
=> StaticHtmlReporter: Fix-up a filter condition

analyzer/src/main/kotlin/managers/Gradle.kt
=> Gradle: Improve the code comment about applying system properties

helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt, helper-cli/src/main/kotlin/commands/ListPackagesCommand.kt, helper-cli/src/main/kotlin/commands/MergeRepositoryConfigurationsCommand.kt
=> helper-cli: Simplify parsing comma separated command line options

gradle.properties
See https://github.com/detekt/detekt/releases/tag/v1.9.1.
=> Gradle: Upgrade the detekt plugin to version 1.9.1

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt, downloader/src/main/kotlin/VcsHost.kt, downloader/src/test/kotlin/VcsHostTest.kt
=> Use the GitHub user / organization name in ClearlyDefined source locations

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt
Please see individual commits for details
=> Add license mappings

analyzer/src/main/kotlin/managers/Pip.kt
=> Pip: Fix a code comment

analyzer/src/funTest/assets/projects/external/qmstr-expected-output.yml, analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
=> Test fixes

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt, analyzer/src/test/kotlin/managers/utils/MavenSupportTest.kt, downloader/src/main/kotlin/vcs/Git.kt, utils/src/main/kotlin/OrtAuthenticator.kt, utils/src/main/kotlin/OrtProxySelector.kt, utils/src/main/kotlin/Utils.kt
=> Add a proxy selector and authenticator

reporter-web-app/config/jest/babelTransform.js, reporter-web-app/config/webpack.config.js, reporter-web-app/package.json, reporter-web-app/scripts/start.js, reporter-web-app/src/App.css, reporter-web-app/src/components/IssuesTable.js, reporter-web-app/src/components/RuleViolationsTable.js, reporter-web-app/src/components/TableView.js, reporter-web-app/src/models/WebAppOrtResult.js, reporter-web-app/src/models/WebAppPackage.js, reporter-web-app/src/reducers/index.js, reporter-web-app/src/reducers/selectors.js, reporter-web-app/yarn.lock
Please see individual commits for details.
=> Various web app report improvements

cli/src/main/kotlin/commands/ReporterCommand.kt, helper-cli/build.gradle.kts, helper-cli/src/main/kotlin/commands/GenerateTimeoutErrorResolutionsCommand.kt, helper-cli/src/main/kotlin/commands/RemoveConfigurationEntriesCommand.kt, model/src/main/kotlin/utils/DefaultResolutionProvider.kt, model/src/main/kotlin/utils/ResolutionProvider.kt, reporter/src/funTest/kotlin/reporters/EvaluatedModelReporterTest.kt, reporter/src/funTest/kotlin/reporters/StaticHtmlReporterTest.kt, reporter/src/main/kotlin/ReporterInput.kt, reporter/src/main/kotlin/utils/ReportTableModelMapper.kt, reporter/src/main/kotlin/utils/StatisticsCalculator.kt
=> Remove the project dependency of the helper-cli on the reporter

.azure-pipelines/LinuxAnalyzerTest.yml, .azure-pipelines/LinuxTest.yml, .azure-pipelines/StaticAnalysis.yml, .azure-pipelines/WindowsAnalyzerTest.yml, .azure-pipelines/WindowsTest.yml, gradle.properties, settings.gradle.kts, utils/src/main/kotlin/OkHttpClientHelper.kt
Some small changes to make the Azure build more stable. See the commit messages for details.
=> Azure stability

README.md, scanner/src/funTest/kotlin/storages/PostgresStorageTest.kt, scanner/src/main/kotlin/storages/PostgresStorage.kt
=> Postgres UTF8 encoding hints

analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/utils/NodeSupport.kt, analyzer/src/test/kotlin/managers/utils/NodeSupportTest.kt, utils/src/main/kotlin/OkHttpClientHelper.kt, utils/src/main/kotlin/OrtProxySelector.kt, utils/src/main/kotlin/Os.kt, utils/src/main/kotlin/Utils.kt
=> OkHttp proxy selector / authenticator

analyzer/src/main/kotlin/managers/GoDep.kt
=> Godeps hints

gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/6.5/release-notes.html.
=> Upgrade Gradle to version 6.5

utils/src/main/kotlin/OrtAuthenticator.kt
To not parse .netrc on every authentication request.
=> OrtAuthenticator: Cache server authentications

cli/src/main/kotlin/commands/DownloaderCommand.kt
=> Various small Downloader improvements

downloader/src/main/kotlin/VersionControlSystem.kt
This avoids output like
Adding Git revision '3.5.2' (taken from package meta-data) as a candidate.
Adding Git revision '3.5.2' (guessed from version '3.5.2') as a candidate.
Note that the created (linked hash) set is guaranteed to preserve the
element iteration order.
=> VersionControlSystem: Do not add the same revision candidate multiple times

Jenkinsfile, analyzer/src/main/kotlin/managers/Gradle.kt
=> Jenkinsfile fixes for authenticated downloads

utils/src/main/kotlin/OrtAuthenticator.kt
On Windows, creating files with leading dots used to not be possible in
Windows Explorer, which is why there is a convention to use a "_netrc"
file instead of a ".netrc" (see [1], [2]).
[1] https://stackoverflow.com/a/6031266/1127485
[2] https://ec.haxx.se/usingcurl/usingcurl-netrc
=> OrtAuthenticator: Support "_netrc" files (for Windows)

spdx-utils/src/main/resources/declared-license-mapping.yml
=> Declared license mappings

analyzer/src/main/kotlin/PackageManager.kt, build.gradle.kts, cli/src/main/kotlin/commands/ReporterCommand.kt
=> Replace measureTimeMillis with measureTime

utils/src/main/kotlin/storage/FileArchiver.kt, utils/src/main/kotlin/storage/FileStorage.kt, utils/src/main/kotlin/storage/HttpFileStorage.kt, utils/src/main/kotlin/storage/LocalFileStorage.kt
=> Store exists check

utils/src/test/kotlin/LoggerTest.kt
=> Logger test improvements

utils/src/main/kotlin/OrtAuthenticator.kt
=> OrtAuthenticator: Fix a typo

reporter/src/main/kotlin/reporters/NoticeByPackageReporter.kt, utils/src/main/kotlin/Logger.kt
=> Add and make use of functions to log a specific message only once

evaluator/src/test/kotlin/TestData.kt, helper-cli/src/main/kotlin/common/Utils.kt, model/src/main/kotlin/licenses/License.kt, model/src/main/kotlin/utils/LicenseResolver.kt, model/src/test/kotlin/PackageCurationTest.kt, reporter/src/funTest/kotlin/TestData.kt, reporter/src/main/kotlin/model/EvaluatedModelMapper.kt, spdx-utils/src/main/kotlin/Extensions.kt, spdx-utils/src/test/kotlin/SpdxExpressionTest.kt, utils/src/main/kotlin/DeclaredLicenseProcessor.kt
=> spdx-utils: Add the convenience function `toSpdx()`

cli/src/main/kotlin/commands/ReporterCommand.kt, reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt
=> Fix Antenna template loading for Java > 8 

Jenkinsfile
=> Separate Jenkinsfile Docker build time

model/src/test/kotlin/config/OrtConfigurationTest.kt, reporter/src/funTest/kotlin/reporters/CycloneDxReporterTest.kt, spdx-utils/src/main/kotlin/SpdxUtils.kt, utils/src/main/kotlin/Extensions.kt, utils/src/test/kotlin/ExtensionsTest.kt, utils/src/test/kotlin/storage/LocalFileStorageTest.kt
=> Extension hash

cli/src/main/kotlin/commands/ReporterCommand.kt
To quickly give an overview of how bad a failed reporter run was.
=> ReporterCommand: Print the number of successfully created reports

analyzer/src/main/kotlin/managers/utils/DotNetSupport.kt
=> DotNetSupport: Remove an argument that is default anyway

reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt
=> AntennaAttributionDocumentReporter: Add sanity checks regarding the template file

downloader/src/main/kotlin/vcs/Subversion.kt
=> Subversion: Add authenticated proxy support

spdx-utils/src/main/kotlin/SpdxExpression.kt
=> SpdxExpression: Document SpdxLicenseWithExceptionExpression.parse()

cli/src/funTest/kotlin/ExamplesTest.kt
=> ExamplesTest: Also test that all examples files are covered

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt, model/src/main/kotlin/OrtIssue.kt, reporter/src/main/kotlin/reporters/NoticeSummaryReporter.kt, utils/src/main/kotlin/Logger.kt
=> Logging improvements

analyzer/src/main/kotlin/managers/Gradle.kt, cli/src/main/kotlin/OrtMain.kt, model/src/main/kotlin/OrtIssue.kt, utils/src/main/kotlin/Utils.kt
=> Fixup user home

analyzer/src/funTest/kotlin/managers/DotNetTest.kt, analyzer/src/funTest/kotlin/managers/NuGetTest.kt, analyzer/src/test/kotlin/managers/utils/NodeSupportTest.kt, model/src/test/kotlin/AnalyzerResultTest.kt, model/src/test/kotlin/IdentifierTest.kt, model/src/test/kotlin/ProjectAnalyzerResultTest.kt, model/src/test/kotlin/ProjectTest.kt, model/src/test/kotlin/ScopeTest.kt, model/src/test/kotlin/config/OrtConfigurationTest.kt, spdx-utils/src/test/kotlin/SpdxExpressionTest.kt, test-utils/src/main/kotlin/Extensions.kt, utils/src/test/kotlin/DeclaredLicenseProcessorTest.kt, utils/src/test/kotlin/ExtensionsTest.kt
=> Fun test improvements

downloader/src/funTest/kotlin/vcs/CvsWorkingTreeTest.kt, downloader/src/funTest/kotlin/vcs/SubversionWorkingTreeTest.kt, downloader/src/main/kotlin/vcs/Subversion.kt
=> Follow-up fixes for Subversion proxy support

downloader/src/main/kotlin/Downloader.kt, downloader/src/main/kotlin/WorkingTree.kt
=> Clarify the meaning of the path in VcsInfo for a WorkingTree

downloader/src/funTest/kotlin/vcs/CvsWorkingTreeTest.kt, downloader/src/funTest/kotlin/vcs/GitWorkingTreeTest.kt, downloader/src/funTest/kotlin/vcs/MercurialWorkingTreeTest.kt, downloader/src/funTest/kotlin/vcs/SubversionWorkingTreeTest.kt, downloader/src/main/kotlin/Downloader.kt
=> Downloader cleanups

reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt
Previously, the AttributionDocumentGeneratorImpl was only able to
generate an attribution document with a provided template JAR via
the --report-option template.path. This procedure is useless for
user without technical experience.
Now, it is able to generate an attribution document with a provided
template directory, which has to contain four template PDF files.
The file names have to match the following:
- cover.pdf: Template PDF file for the cover page.
- copyright.pdf: Template PDF file for the project copyright page.
- content.pdf: Template PDF file for the packages of the project.
- back.pdf: Template PDF file for the back page.
Resolves #2676.
=> AntennaAttributionDocumentReporter: Make it work with directories

utils/src/main/kotlin/CopyrightStatementsProcessor.kt, utils/src/test/assets/copyright-statements-expected-output.yml
Various improvements of the `CopyrightStatementsProcessor`, see the commit messages for details.
=> Copyright processor improvements

reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt
=> AntennaAttributionDocumentReporter: Fix a variable to be a value

analyzer/src/funTest/kotlin/managers/MavenTest.kt, analyzer/src/main/kotlin/managers/Conan.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/Pub.kt, analyzer/src/main/kotlin/managers/utils/MavenSupport.kt, cli/src/main/kotlin/OrtMain.kt, cli/src/main/kotlin/commands/AnalyzerCommand.kt, downloader/src/funTest/kotlin/vcs/CvsWorkingTreeTest.kt, downloader/src/funTest/kotlin/vcs/GitWorkingTreeTest.kt, downloader/src/funTest/kotlin/vcs/MercurialWorkingTreeTest.kt, downloader/src/funTest/kotlin/vcs/SubversionWorkingTreeTest.kt, reporter/src/main/kotlin/reporters/NoticeByPackageReporter.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/ScanResultsStorage.kt, utils/src/main/kotlin/OkHttpClientHelper.kt, utils/src/main/kotlin/OrtAuthenticator.kt, utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/ExtensionsTest.kt
=> Fixup get user home

docs/how-to-add-support-for-new-package-manager.md
I stumbled across some typos and structured the Q&A to be able to differentiate between questions and answers.
Signed-off-by: Piet Brauer <piet.brauer@mhp.com>
=> docs: Improve readability

reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt
Initially, the AntennaAttributionDocumentReporter was able to generate
only one report for a single project and failed if there were mutliple
projects.
After 6fa5c9e reporters are allowed to generate multiple reports.
Therefor the AntennaAttributionDocumentReporter iterates over the
projects and creates for each project a own attribution document with
project name and version as file name prefix.
Resolves #2754.
=> AntennaAttributionDocumentReporter: Support multiple project reports

reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt
This extends the existing work-around until we have a proper fix for #2755.
=> AntennaAttributionDocumentReporter: Replace more unavailable characters

model/src/main/kotlin/config/PackageConfiguration.kt
Minor improvements of the `PackageConfiguration`.
=> Package configuration improvements

model/src/main/kotlin/Identifier.kt, reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt
=> Fix the project names in Antenna reports

analyzer/src/funTest/kotlin/managers/MavenTest.kt, analyzer/src/main/kotlin/managers/Conan.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/Pub.kt, cli/src/main/kotlin/OrtMain.kt, utils/src/main/kotlin/OrtAuthenticator.kt, utils/src/main/kotlin/Os.kt, utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/ExtensionsTest.kt
=> Fix fixup logging

analyzer/src/main/kotlin/managers/Npm.kt, model/src/main/kotlin/config/LicenseFindingCuration.kt, model/src/main/kotlin/licenses/LicenseFindingCurationResult.kt, model/src/main/kotlin/utils/FindingCurationMatcher.kt, model/src/test/kotlin/utils/FindingCurationMatcherTest.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, spdx-utils/build.gradle.kts, spdx-utils/src/main/kotlin/SpdxConstants.kt, spdx-utils/src/main/kotlin/SpdxLicense.kt, spdx-utils/src/main/kotlin/SpdxUtils.kt
=> Consistently use SpdxConstants.NONE and SpdxConstants.NOASSERTION

analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt
=> Improvements for ClearlyDefined tests

analyzer/src/main/kotlin/managers/GoMod.kt, build.gradle.kts
=> Split improvements

cli/build.gradle.kts, cli/src/main/kotlin/OrtMain.kt, cli/src/main/kotlin/commands/UploadResultCommand.kt
=> CLI: Add a command to upload ORT results to PostgreSQL

reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json, reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml, reporter/src/funTest/kotlin/reporters/SpdxDocumentReporterTest.kt, reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt, spdx-utils/src/main/kotlin/model/SpdxDocument.kt
Address the findings from @swinslow:
- https://github.com/oss-review-toolkit/ort/pull/2800#discussion_r447702079
- https://github.com/oss-review-toolkit/ort/pull/2800#discussion_r447703206
See also this related discussion:
- https://github.com/oss-review-toolkit/ort/pull/2773#discussion_r445522327
=> Spdx document model fixes

reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json, reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml, reporter/src/funTest/kotlin/reporters/SpdxDocumentReporterTest.kt, reporter/src/main/kotlin/reporters/SpdxDocumentReporter.kt, reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt
See individual commit messages for the details.
=> SpdxDocumentReporter: Report information about the dependencies

reporter/src/funTest/kotlin/reporters/SpdxDocumentReporterTest.kt, reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt
See individual commit messages for the details.
=> SpdxReporter: Omit excluded packages

evaluator/src/test/kotlin/TestData.kt, model/src/main/kotlin/CuratedPackage.kt, model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/Package.kt, model/src/test/kotlin/config/ExcludesTest.kt, reporter/src/funTest/kotlin/TestData.kt, reporter/src/funTest/kotlin/reporters/SpdxDocumentReporterTest.kt
For less verbosity in the callers.
=> CuratedPackage: Assign a default value to curations

README.md
=> README.md: Add SPDX document to the list of supported report formats

README.md
=> README: Add a badge for the LGTM service

docs/examples/rules.kts, model/src/main/kotlin/Project.kt, model/src/test/kotlin/AnalyzerResultTest.kt
See the individual commit messages for the details.
=> Leave reporting unmapped declared license issues up to the evaluator rules

analyzer/src/main/kotlin/curation/FilePackageCurationProvider.kt, cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/EvaluatorCommand.kt, cli/src/main/kotlin/commands/ScannerCommand.kt, model/src/main/kotlin/FileFormat.kt
=> File format changes

downloader/src/funTest/kotlin/DownloaderTest.kt
=> DownloaderTest: Fix a typo

reporter/build.gradle.kts, reporter/src/funTest/kotlin/reporters/SpdxDocumentReporterTest.kt, reporter/src/main/kotlin/reporters/SpdxDocumentReporter.kt, reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt, spdx-utils/src/main/kotlin/SpdxModelMapper.kt, spdx-utils/src/test/kotlin/SpdxDocumentModelTest.kt
=> Spdx utils changes

scanner/src/main/kotlin/LocalScanner.kt
The PostgresStorage handling is currently implemented such that multiple
scan results may get stored for a single identifier, scanner details
provenance tuple. This situation is in fact not unlikely as the time
interval between (1) the look-up of a stored scan result for a package
and (2) the actual scan executed due to the failed look-up may be
relatively large. I've observed this interval to span more than three
hours and the scan storage I'm using for some packages has even six
equal scan results which all do end-up in the OrtResults, increasing its
size unnecessarily.
While the above mentioned time interval should be reduced, and ideally
it also should be made impossible that multiple scan results with equal
identifier, provenance and scanner details can be stored in the first
place, …
=> LocalScanner: De-duplicate scan results retrieved from the storage

cli/src/main/kotlin/commands/ClearlyDefinedUploadCommand.kt
For providing a short summary.
=> ClearlyDefinedUploadCommand: Output the number of successful uploads

scanner/src/main/kotlin/LocalScanner.kt
=> LocalScanner: Fix a trivial formatting issue

.travis.yml, Dockerfile
=> Add the Android SDK to the Dockerfile

analyzer/src/funTest/assets/projects/synthetic/spdx-project-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/spdx/package/README.md, analyzer/src/funTest/assets/projects/synthetic/spdx/package/libs/curl/README.md, analyzer/src/funTest/assets/projects/synthetic/spdx/package/libs/curl/package.spdx.yml, analyzer/src/funTest/assets/projects/synthetic/spdx/project/README.md, analyzer/src/funTest/assets/projects/synthetic/spdx/project/libs/curl/README.md, analyzer/src/funTest/assets/projects/synthetic/spdx/project/libs/openssl/README.md, analyzer/src/funTest/assets/projects/synthetic/spdx/project/libs/xyz/README.md, analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml, analyzer/src/funTest/kotlin/managers/SpdxDocumentFileTest.kt, analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt, analyzer/src/main/resources/META-INF/services/org.ossreviewtoolkit.analyzer.PackageManagerFactory, analyzer/src/test/kotlin/PackageManagerTest.kt
=> Add a generic package manager based on SPDX documents

spdx-utils/src/main/kotlin/SpdxUtils.kt, spdx-utils/src/main/kotlin/model/SpdxExternalReference.kt
=> spdx-utils: Miscellaneous fixes

model/src/main/kotlin/Identifier.kt, model/src/main/kotlin/ScanRecord.kt, model/src/main/kotlin/TextLocation.kt, model/src/main/kotlin/licenses/LicenseInfoResolver.kt, model/src/main/kotlin/utils/LicenseResolver.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/utils/ReportTableModelMapper.kt, scanner/src/main/kotlin/LocalScanner.kt
=> Miscellaneous code inspection warning fixes

docs/getting-started.md
=> docs/getting-started.md: Fix a broken file reference

reporter-web-app/config/webpack.config.js, reporter-web-app/src/models/WebAppOrtResult.js, reporter-web-app/src/reducers/index.js
Fix several warnings and recommendations found by the
LGTM.com security scanner.
Closes #2832.
=> reporter-web-app: Fix issues flagged by LGTM

CONTRIBUTING.md
=> contributing: Add section on project governance

analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt, analyzer/src/funTest/kotlin/managers/Extensions.kt, analyzer/src/funTest/kotlin/managers/MavenTest.kt, clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceTest.kt, cli/src/funTest/kotlin/OrtMainTest.kt, downloader/src/funTest/kotlin/BabelTest.kt, downloader/src/funTest/kotlin/BeanUtilsTest.kt, downloader/src/funTest/kotlin/DownloaderTest.kt, model/src/test/kotlin/PackageTest.kt, model/src/test/kotlin/config/OrtConfigurationTest.kt, model/src/test/kotlin/config/RepositoryConfigurationTest.kt, model/src/test/kotlin/utils/FindingCurationMatcherTest.kt, reporter/src/test/kotlin/reporters/ExcelReporterTest.kt, scanner/src/funTest/kotlin/scanners/AbstractScannerTest.kt, spdx-utils/src/test/kotlin/SpdxDeclaredLicenseMappingTest.kt, spdx-utils/src/test/kotlin/SpdxLicenseTest.kt, spdx-utils/src/test/kotlin/SpdxSimpleLicenseMappingTest.kt, spdx-utils/src/test/kotlin/SpdxUtilsTest.kt, test-utils/src/main/kotlin/Extensions.kt, utils/src/test/kotlin/DeclaredLicenseProcessorTest.kt, utils/src/test/kotlin/ExtensionsTest.kt, utils/src/test/kotlin/OrtAuthenticatorTest.kt, utils/src/test/kotlin/UtilsTest.kt
Improve the null handling in tests and make it more consistent. See the commit messages for details.
=> Improve null handling in tests

analyzer/src/main/kotlin/managers/Pip.kt
See the individual commit messages for the details.
=> Pip: Fallback to obtaining package meta data locally

cli/src/main/kotlin/commands/ReporterCommand.kt, model/src/main/kotlin/config/PackageConfiguration.kt, model/src/main/kotlin/licenses/LicenseInfoResolver.kt, model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt, reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json, reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml, reporter/src/funTest/assets/static-html-reporter-test-expected-output.html, reporter/src/funTest/assets/static-html-reporter-test-input.yml, reporter/src/main/kotlin/ReporterInput.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, reporter/src/main/kotlin/utils/ReportTableModel.kt, reporter/src/main/kotlin/utils/ReportTableModelMapper.kt
Use the license API introduced in #2667 in the `StaticHtmlReporter` and `ExcelReporter`.
=> License API StaticHtmlReporter/ExcelReporter

reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
=> CycloneDxReporter: Migrate to the new license API

model/src/main/kotlin/licenses/LicenseView.kt, model/src/test/kotlin/licenses/LicenseViewTest.kt, model/src/test/kotlin/licenses/TestData.kt
=> Use LicenseView to filter ResolvedLicenseInfo

model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt, reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt, spdx-utils/src/main/kotlin/SpdxExpression.kt
=> Migrate the Antenna reporter to the new license API

model/src/test/kotlin/licenses/AbstractLicenseViewTest.kt, model/src/test/kotlin/licenses/LicenseViewFilterTest.kt, model/src/test/kotlin/licenses/LicenseViewLicensesTest.kt, model/src/test/kotlin/licenses/LicenseViewTest.kt
=> Minor improvements of the `LicenseView` tests

Jenkinsfile
As of [1] not only the evaluator, but also the analyzer and scanner
return "unstable" status codes in case of issues being present (but
general execution succeeded). Handle these like in the evaluator for
rule violations by marking the Jenkins stage as unstable instead
throwing an error.
[1] https://github.com/oss-review-toolkit/ort/pull/2847
=> Jenkinsfile: Handle unstable status codes in analyzer and scanner stages

Dockerfile
=> Dockerfile: Pass https_proxy to sdkmanager

cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/EvaluatorCommand.kt, cli/src/main/kotlin/commands/ScannerCommand.kt, model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/utils/OrtResultExtensions.kt
=> Add labels to the ORT result

cli/src/main/kotlin/commands/ReporterCommand.kt, reporter/src/funTest/kotlin/reporters/NoticeByPackageReporterTest.kt, reporter/src/funTest/kotlin/reporters/NoticeSummaryReporterTest.kt, reporter/src/funTest/kotlin/reporters/SpdxDocumentReporterTest.kt, reporter/src/main/kotlin/ReporterInput.kt, reporter/src/main/kotlin/reporters/AbstractNoticeReporter.kt, reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt, reporter/src/main/kotlin/reporters/CycloneDxReporter.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/NoticeByPackageReporter.kt, reporter/src/main/kotlin/reporters/NoticeSummaryReporter.kt, reporter/src/main/kotlin/reporters/SpdxDocumentReporter.kt, reporter/src/main/kotlin/utils/ReportTableModel.kt, reporter/src/main/kotlin/utils/ReportTableModelMapper.kt
Several improvements related to report specific options. See the commit messages for details.
=> Reporter options improvements

reporter/src/main/kotlin/reporters/CycloneDxReporter.kt, reporter/src/main/kotlin/reporters/GitLabLicenseModelReporter.kt, utils/src/main/kotlin/Ci.kt, utils/src/main/kotlin/Extensions.kt
=> Introduce and use an isTrue() extension function for Strings

reporter/src/main/kotlin/reporters/ExcelReporter.kt
=> ExcelReporter: Simplify the code of createSummarySheet() a bit

gradle.properties
See https://detekt.github.io/detekt/changelog.html#1110.
=> Gradle: Upgrade the detekt plugin to version 1.11.0

Jenkinsfile, docs/config-file-copyright-garbage-yml.md, docs/config-file-curations-yml.md, docs/config-file-licenses-yml.md, docs/config-file-ort-yml.md, docs/config-file-resolutions-yml.md, docs/file-rules-kts.md, docs/getting-started.md, docs/notice-pre-processor-kts.md
=> Fix example links in docs

analyzer/src/main/kotlin/Analyzer.kt, analyzer/src/main/kotlin/managers/GoDep.kt, cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/ClearlyDefinedUploadCommand.kt, cli/src/main/kotlin/commands/DownloaderCommand.kt, cli/src/main/kotlin/commands/EvaluatorCommand.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, cli/src/main/kotlin/commands/ScannerCommand.kt, cli/src/main/kotlin/commands/UploadResultCommand.kt
=> Fix handling of relative paths passed on the CLI

gradle.properties
See https://github.com/detekt/detekt/releases/tag/v1.11.1.
=> Gradle: Upgrade the detekt plugin to version 1.11.1

gradle.properties
See https://github.com/detekt/detekt/releases/tag/v1.11.2.
=> Gradle: Upgrade the detekt plugin to version 1.11.2

cli/build.gradle.kts, helper-cli/build.gradle.kts, test-utils/build.gradle.kts, utils/src/main/kotlin/OrtAuthenticator.kt, utils/src/main/kotlin/OrtProxySelector.kt
=> Logging fixes

Jenkinsfile
As it might be distracting to see for exceptions that are handled
internally.
=> Jenkinsfile: Make showing the stack trace optional

.github/workflows/markdown-link-check.yml, README.md
=> Markdown link check

reporter/src/main/kotlin/utils/ReportTableModelMapper.kt
See individual commit messages for the details.
=> ReportTableModelMapper: Miscellaneous / minor fixes

README.md
=> README: Add a system requirements section

downloader/src/funTest/kotlin/vcs/GitDownloadTest.kt, downloader/src/funTest/kotlin/vcs/GitWorkingTreeTest.kt, downloader/src/main/kotlin/VersionControlSystem.kt
=> Improve the test to not prompt for Git credentials

analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml, analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml, analyzer/src/main/kotlin/PackageManager.kt, downloader/src/main/kotlin/VcsHost.kt
=> Bitbucket fixes

docs/config-file-resolutions-yml.md
Add the described flag in the example call.
=> Update config-file-resolutions-yml.md - add flag to example

utils/src/main/kotlin/OrtProxySelector.kt
=> Add support for the no_proxy environment variable

helper-cli/src/main/kotlin/HelperMain.kt, helper-cli/src/main/kotlin/commands/GeneratePackageConfigurationsCommand.kt, helper-cli/src/main/kotlin/common/Utils.kt
=> helper-cli: Add a command to generate package configurations

downloader/src/main/kotlin/VcsHost.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/test/kotlin/VcsHostTest.kt
=> Miscellaneous downloader / VCS improvements

analyzer/src/main/kotlin/managers/Pip.kt, helper-cli/src/main/kotlin/commands/FormatRepositoryConfigurationCommand.kt, helper-cli/src/main/kotlin/commands/SortRepositoryConfigurationCommand.kt, helper-cli/src/main/kotlin/commands/VerifySourceArtifactCurationsCommand.kt
=> Misc fixes

analyzer/src/funTest/kotlin/managers/DotNetTest.kt, analyzer/src/funTest/kotlin/managers/NuGetTest.kt, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/NuGet.kt, analyzer/src/main/kotlin/managers/utils/DotNetSupport.kt, analyzer/src/test/kotlin/managers/utils/DotNetSupportTest.kt
=> Clean up code in the DotNet package managers a bit

helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
=> ListLicensesCommand: Slightly improve the output

spdx-utils/src/main/resources/declared-license-mapping.yml
=> Add license mappings for .NET

analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/NuGet.kt, analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt, analyzer/src/test/kotlin/managers/utils/NuGetSupportTest.kt
=> Clarify NuGet vs DotNet

model/src/main/kotlin/VcsType.kt
=> VcsType: Fix a typo

analyzer/src/funTest/kotlin/managers/DotNetTest.kt, analyzer/src/funTest/kotlin/managers/NuGetTest.kt, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/NuGet.kt, analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt, analyzer/src/test/kotlin/managers/utils/NuGetSupportTest.kt
=> Misc. minor NuGet improvements

helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
This reverts commit 1d2b9f84731d86ac3eb66ec40741e8b5144ed5e5.
=> ListLicenseCommand: Add the --license-allow-list option

model/src/main/kotlin/Package.kt
=> Package: Explicitly state the return type of collectIssues()

analyzer/src/main/kotlin/managers/DotNet.kt
=> DoNet: Fix a typo

analyzer/src/main/kotlin/managers/Npm.kt
=> Npm: Simplify the code to detect dependency cycles a bit

.appveyor.yml, .azure-pipelines/LinuxAnalyzerTest.yml, .azure-pipelines/LinuxTest.yml, .azure-pipelines/WindowsAnalyzerTest.yml, .azure-pipelines/WindowsTest.yml, build.gradle.kts, test-utils/src/main/kotlin/ProjectConfig.kt
Print the full test names including context in the Azure Pipelines and AppVeyor test reports.
=> Kotest extensions junitxml

README.md
=> README: Explain how to run tests from the IDE

reporter/src/funTest/assets/notice-template-reporter-expected-results, reporter/src/funTest/assets/notice-template-reporter-expected-results-with-license-files, reporter/src/main/kotlin/reporters/NoticeTemplateReporter.kt, reporter/src/main/resources/template.notice/default.ftl
=> NoticeTemplateReporter helpers

model/src/main/kotlin/Package.kt, model/src/test/kotlin/PackageTest.kt
=> Package: Make diff() adhere to isMetaDataOnly

reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, reporter/src/main/kotlin/utils/ReportTableModel.kt
=> reporter: Consistently use "rule violation" instead of "evaluator issue"

model/src/main/kotlin/PackageCurationData.kt, utils/src/main/kotlin/DeclaredLicenseProcessor.kt
Slightly refactor / improve the code locations where the delcared license mapping curations will get integrated in a following PR.
See also #2898.
=> Declared license mapping curation preparations

evaluator/src/main/kotlin/Rule.kt, evaluator/src/test/kotlin/PackageRuleTest.kt, evaluator/src/test/kotlin/RuleTest.kt, evaluator/src/test/kotlin/TestData.kt
=> evaluator: Add matchers for labels

gradle.properties
See https://github.com/ben-manes/gradle-versions-plugin/releases/tag/v0.31.0.
=> Gradle: Upgrade the versions plugin to version 0.31.0

model/src/main/kotlin/LicenseFindings.kt, utils/src/main/kotlin/DeclaredLicenseProcessor.kt, utils/src/main/kotlin/Utils.kt
=> Minor code improvements

examples/curations.yml
=> examples/curations: Illustrate how to discard a declared license string

model/src/main/kotlin/licenses/ResolvedLicenseFileInfo.kt, model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt, reporter/src/main/kotlin/reporters/AmazonOssAttributionBuilderReporter.kt, reporter/src/main/resources/template.notice/default.ftl, reporter/src/main/resources/template.notice/summary.ftl
=> Reprocess merged copyrights

README.md
=> README: Remove a superfluous closing parenthesis

model/src/test/kotlin/VcsInfoTest.kt
=> VcsInfoTest: Make several assertions more compact

gradle.properties
See https://github.com/JetBrains/kotlin/releases/tag/v1.4.10.
=> Gradle: Upgrade Kotlin to version 1.4.10

spdx-utils/src/main/resources/declared-license-mapping.yml
Found in [1].
[1]: https://jcenter.bintray.com/org/matomo/sdk/tracker/4.1.2/tracker-4.1.2.pom
=> Add declared license mapping for "BSD-3 Clause"

utils/src/test/kotlin/FileMatcherTest.kt
=> FileMatcher test improvements

evaluator/src/test/kotlin/EvaluatorTest.kt
=> Evaluator test fixes

README.md, cli/src/funTest/kotlin/ExamplesTest.kt, cli/src/main/kotlin/commands/EvaluatorCommand.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, cli/src/main/kotlin/utils/PackageConfigurationOption.kt, docs/config-file-copyright-garbage-yml.md, docs/config-file-curations-yml.md, docs/config-file-licenses-yml.md, docs/config-file-package-configuration-yml.md, docs/config-file-resolutions-yml.md, docs/file-rules-kts.md, docs/getting-started.md, docs/how-to-fix-text-provider-kts.md, docs/notice-pre-processor-kts.md, docs/reporters/AntennaAttributionDocumentReporter.md, evaluator/src/main/kotlin/RuleSet.kt, evaluator/src/test/kotlin/EvaluatorTest.kt, evaluator/src/test/kotlin/RuleSetTest.kt, helper-cli/src/main/kotlin/common/PackageConfigurationOption.kt, helper-cli/src/main/kotlin/common/Utils.kt, model/src/main/kotlin/utils/OrtResultExtensions.kt, model/src/main/kotlin/utils/SimplePackageConfigurationProvider.kt, model/src/test/kotlin/licenses/LicenseViewFilterTest.kt, reporter/src/main/kotlin/ReporterInput.kt, utils/src/main/kotlin/Constants.kt
=> Rework some configuration CLI options, their defaults and documentation

scanner/src/main/kotlin/Scanner.kt
=> Scanner: Fix a typo in an exception message

README.md, cli/src/main/kotlin/commands/EvaluatorCommand.kt
=> Rules config

README.md
=> README: Document ORT's environment variables

cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/DownloaderCommand.kt, cli/src/main/kotlin/commands/EvaluatorCommand.kt, cli/src/main/kotlin/commands/Extensions.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, cli/src/main/kotlin/commands/ScannerCommand.kt, cli/src/main/kotlin/commands/UploadCurationsCommand.kt, cli/src/main/kotlin/commands/UploadResultCommand.kt
=> Improve formatting of command line arguments

cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/Constants.kt, cli/src/main/kotlin/commands/DownloaderCommand.kt, cli/src/main/kotlin/commands/EvaluatorCommand.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, cli/src/main/kotlin/commands/ScannerCommand.kt
=> Improve wording of command line arguments

README.md, cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/EvaluatorCommand.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, docs/config-file-copyright-garbage-yml.md, docs/config-file-curations-yml.md, docs/config-file-licenses-yml.md, docs/config-file-ort-yml.md, docs/config-file-package-configuration-yml.md, docs/config-file-resolutions-yml.md, docs/dir-custom-license-texts.md, docs/file-rules-kts.md, docs/getting-started.md, docs/how-to-fix-text-provider-kts.md, docs/notice-templates.md, utils/src/main/kotlin/Constants.kt
=> Add default locations for all global configuration files

spdx-utils/src/main/resources/declared-license-mapping.yml
Found in [1].
[1]:https://repo.maven.apache.org/maven2/org/apache/tomcat/tomcat-servlet-api/9.0.31/tomcat-servlet-api-9.0.31.pom
=> Add a new declared Apache-2.0 and CDDL-1.0  license mapping

buildSrc/src/main/kotlin/IdeaExtKotlinDsl.kt, gradle.properties
Unfortunately, there is no changelog.
=> Gradle: Upgrade the idea-ext plugin to version 0.9

gradle.properties, utils/build.gradle.kts, utils/src/test/kotlin/LoggerTest.kt
=> Add tests for logging only once using the mockk library

analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Conan.kt, analyzer/src/main/kotlin/managers/GoMod.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/Pip.kt, analyzer/src/main/kotlin/managers/Pub.kt, analyzer/src/main/kotlin/managers/utils/NodeSupport.kt, analyzer/src/test/kotlin/managers/utils/NodeSupportTest.kt, helper-cli/src/main/kotlin/commands/ImportLicenseFindingCurationsCommand.kt, helper-cli/src/main/kotlin/commands/ImportPathExcludesCommand.kt, helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt, helper-cli/src/main/kotlin/commands/MapCopyrightsCommand.kt, helper-cli/src/main/kotlin/common/Utils.kt, model/src/main/kotlin/PackageReference.kt, model/src/main/kotlin/licenses/LicenseConfiguration.kt, model/src/test/kotlin/utils/FindingsMatcherTest.kt, model/src/test/kotlin/utils/LicenseResolverTest.kt, reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt, scanner/src/main/kotlin/storages/PostgresStorage.kt, utils/src/main/kotlin/LicenseFilenamePatterns.kt
=> Prefer the more readable += operator over add() throughout the code base

detekt-rules/src/main/kotlin/OrtImportOrder.kt
=> OrtImportOrder: Clarify what "invalid order" actually means

CONTRIBUTING.md
=> Improve contributing wording

reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
The component attribute in the report is extended with the `dependencyType` attribute.
It can assume the values "direct" or "transitive", depending on how the
respective package has been imported into the analyzed project.
Closes #2929.
Signed-off-by: Korbinian Singhammer <external.Korbinian.Singhammer2@bosch.io>
=> CycloneDxReporter: Add dependency type in report

spdx-utils/src/main/kotlin/model/SpdxPackage.kt
=> SpdxPackage: Fix a comment to be KDoc

model/src/main/kotlin/Package.kt, model/src/main/kotlin/PackageCurationData.kt, model/src/test/kotlin/PackageCurationTest.kt
=> Add modified flag for packages

downloader/src/main/kotlin/VcsHost.kt
To avoid recompilation on every function all.
=> VcsHost: Extract Regex patterns to constants

model/src/main/kotlin/PackageCurationData.kt
=> PackageCurationData: Fix-up applying isModified

analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
=> Spdx doc file improvements

analyzer/src/main/kotlin/managers/Carthage.kt
=> Carthage improvements

scanner/src/main/kotlin/scanners/Askalono.kt
See https://github.com/jpeddicord/askalono/releases/tag/0.4.3.
Note that Askalono is now distributed in ZIP archives instead of plain
executables.
=> Askalono: Upgrade to version 0.4.3

CONTRIBUTING.md
=> CONTRIBUTING: Add a few so far unwritten coding conventions

reporter/src/funTest/assets/gitlab-license-model-test-expected-output.json, reporter/src/funTest/assets/gitlab-license-model-test-skip-excluded-expected-output.json, reporter/src/main/kotlin/gitlab/GitLabLicenseModelMapper.kt, spdx-utils/src/main/kotlin/SpdxConstants.kt, spdx-utils/src/main/kotlin/SpdxExpression.kt
Signed-off-by: zhernovs <ext-andriy.zhernovskyi@here.com>
=> reporter: Add URL for SPDX licenses to GitLab license model

scanner/src/main/kotlin/scanners/Askalono.kt, utils/src/main/kotlin/ArchiveUtils.kt
=> Fix ZIP mode bits when unpacking

model/src/main/kotlin/config/RuleViolationResolutionReason.kt
=> RuleViolationResolution: Add `not modified` as reason

scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, utils/src/main/kotlin/ArchiveUtils.kt
=> Archive utils improvements

gradle.properties
See https://github.com/detekt/detekt/releases/tag/v1.14.0.
=> Gradle: Upgrade the detekt plugin to version 1.14.0

scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/main/kotlin/scanners/ScanCodeResultParser.kt, scanner/src/test/kotlin/ScanCodeTest.kt, scanner/src/test/kotlin/ScannerDetailsTest.kt, scanner/src/test/kotlin/scanners/ScanCodeResultParserTest.kt
=> Scancode test improvements

analyzer/src/main/kotlin/managers/Pip.kt
To consistently filter out "UNKOWN" and '"".
=> Pip: Consistently filter out unkown

analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
=> SpdxDocumentFile: Improve exception messages for missing packages

analyzer/src/funTest/assets/projects/synthetic/spdx-project-expected-output.yml, analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
Generate a sourceArtifact with a file document location and don't set ConcludedLicense when it's not needed
=> Analyzer with SpdxDocument improvements

analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
=> SpdxDocumentFile: Trivially improve some code comments

utils/src/main/kotlin/OrtAuthenticator.kt, utils/src/test/kotlin/OrtAuthenticatorTest.kt
=> Netrc ignore whitespace

gradle.properties
See https://github.com/detekt/detekt/releases/tag/v1.14.1.
=> Gradle: Upgrade the detekt plugin to version 1.14.1

README.md, docs/hints-for-use-with-docker.md
Describes common issues and how to resolve them, as well as general tips, based on working with the docker image for a while.
=> Provide (additional) documentation for usage of the docker image

analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
This is a common mistake and thus is now exposed more visibly.
=> SpdxDocumentFile: Create OrtIssues when SPDXIDs match case-insensitively

analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt, reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt, spdx-utils/src/main/kotlin/SpdxConstants.kt, spdx-utils/src/main/kotlin/SpdxExpression.kt, spdx-utils/src/main/kotlin/model/SpdxAnnotation.kt, spdx-utils/src/main/kotlin/model/SpdxPackage.kt
=> Check SPDX string fields for valid prefixes

utils/src/main/kotlin/CopyrightStatementsProcessor.kt
=> Minor improvements to the CopyrightStatementsProcessor

analyzer/src/main/kotlin/managers/GoMod.kt, cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/EvaluatorCommand.kt, cli/src/main/kotlin/commands/ScannerCommand.kt, helper-cli/src/main/kotlin/commands/GenerateTimeoutErrorResolutionsCommand.kt, helper-cli/src/main/kotlin/common/Utils.kt, model/src/main/kotlin/ScanResult.kt, model/src/main/kotlin/licenses/LicenseView.kt, model/src/main/kotlin/utils/FindingsMatcher.kt, reporter/src/main/kotlin/reporters/SpdxDocumentReporter.kt, reporter/src/main/kotlin/utils/ReportTableModelMapper.kt, reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt, scanner/src/test/kotlin/scanners/ScanCodeResultParserTest.kt
This further improves c68021d.
=> Map straight to sets instead of converting

README.md
=> README: Add a link to the GitLab integration example video

analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
=> PipFunTest: Update expected test results

README.md
=> README: Clarify that we recommend ScanCode over other implementations

utils/src/test/kotlin/ExtensionsTest.kt
=> ExtensionsTest: Make checks for not throwing explicit

README.md
Fix inaccessible link to core development team
=> README: Fix inaccessible link to core development team

.azure-pipelines/DockerBuild.yml, Dockerfile, README.md
=> Use Docker BuildKit to speed up the build

README.md, model/src/main/kotlin/config/ScanStorageConfiguration.kt
=> Fix storage config link

reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt
Merge copyright entries and filter excluded copyrights.
Resolves #3200.
=> AntennaAttributionDocumentReporter: Aggregate copyright statements

analyzer/src/funTest/kotlin/managers/CarthageFunTest.kt, analyzer/src/funTest/kotlin/managers/GoDepFunTest.kt
=> analyzer: Do not hard-code the GitHub project replacements

gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/6.7/release-notes.html.
=> Upgrade Gradle to version 6.7

integrations/Jenkinsfile
=> Jenkinsfile comments

reporter/src/funTest/kotlin/reporters/ExcelReporterFunTest.kt
=> Excel merged cells test

model/src/main/kotlin/config/OrtConfiguration.kt
=> OrtConfiguration: Log the configuration file being used for debugging

gradle.properties
See https://github.com/detekt/detekt/releases/tag/v1.14.2.
=> Gradle: Upgrade detekt to version 1.14.2

gradle.properties
See https://github.com/Kotlin/dokka/releases/tag/v1.4.10.2.
=> Gradle: Upgrade dokka to version 1.4.10.2

model/src/main/kotlin/utils/FindingsMatcher.kt
The `matchedRootLicenseFindings` were added to `matchedFindings` by
the `+=` operator which does an add-or-replace operation. Effectivly
this discards all copyright statements from the root license file in
case there are unmatched copyrights. Fix this by merging the copyright
statements properly.
While at it use merge() also for merging `matchedFileFindings` for
consistency, even if this is not necessary for fixing this bug.
=> FindingsMatcher: Fix broken merging of matched root license findings

build.gradle.kts
See https://github.com/kotest/kotest-intellij-plugin/commit/114ec28.
=> Gradle: Account for the kotest plugin to create Gradle run configs now

.mailmap
=> Update mailmap to beautify / complete some contributor names

examples/curations.yml
Also see https://yaml-multiline.info/.
=> examples: Demonstrate the use of block scalar style comments in YAML

clearly-defined/src/main/kotlin/ClearlyDefinedService.kt, model/src/main/kotlin/ScannerDetails.kt
This PR adds some minor functionality, which is going to be needed by the implementation of the ClearlyDefinedStorage. It includes the following changes:
* A function isCompatibleVersion() is extracted out of the ScannerDetails class, which is going to be used to check for the version compatibility of scan results, independent on other properties.
* Support for another query endpoint has been added to the ClearlyDefinedService class. This endpoint is going to be used to find all the results available related to a specific package identifier.
=> Oheger bosch/scanner/clearly defined helper functionality

analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/resources/scripts/init.gradle, cli/src/main/kotlin/OrtMain.kt
=> Gradle mem info

utils/src/main/kotlin/OkHttpClientHelper.kt
=> OkHttpClientHelper: Improve a code comment regarding authenticators

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
=> ClearlyDefinedPackageCurationProvider: Do not take curations with "OTHER"

analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
=> PipFunTest: Update the expected pytz version to 2020.4

analyzer/src/main/kotlin/managers/Sbt.kt
=> Sbt version guard

analyzer/src/main/kotlin/managers/Gradle.kt
Increase the default max heap memory for gradle projects
from 512 MiB (see [1]) to 8 GiB.
[1] https://docs.gradle.org/current/userguide/build_environment.html#sec:configuring_jvm_memory
Resolves #3248.
=> Gradle: Set the default max heap size to 8 GiB

model/src/main/kotlin/Identifier.kt
Like in Maven packages with a group of "io.bosch".
=> Identifier: Add "io" to the list of known organization namespaces

reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt, spdx-utils/src/main/kotlin/SpdxConstants.kt, spdx-utils/src/main/kotlin/model/SpdxDocument.kt, spdx-utils/src/main/kotlin/model/SpdxFile.kt, spdx-utils/src/main/kotlin/model/SpdxPackage.kt, spdx-utils/src/main/kotlin/model/SpdxSnippet.kt
=> Introduce and use a constant for the SPDXRef prefix

cli/src/main/kotlin/commands/EvaluatorCommand.kt, downloader/src/main/kotlin/Downloader.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/ScanResultsStorage.kt, scanner/src/main/kotlin/storages/PostgresStorage.kt, utils/src/main/kotlin/storage/FileArchiver.kt
Add several performance related log statements. See the commit messages for details.
=> Performance logging

gradle.properties
See https://github.com/ben-manes/gradle-versions-plugin/releases/tag/v0.35.0.
=> Gradle: Upgrade the versions plugin to version 0.35.0

downloader/src/main/kotlin/vcs/Subversion.kt, utils/src/main/kotlin/OrtAuthenticator.kt
=> Subversion: Add authentication support via the Java Authenticator

gradle.properties
See https://github.com/ben-manes/gradle-versions-plugin/releases/tag/v0.36.0.
=> Gradle: Upgrade the versions plugin to version 0.36.0

spdx-utils/src/main/kotlin/SpdxExpression.kt
=> Spdx validate none

downloader/src/main/kotlin/vcs/Git.kt, utils/src/main/kotlin/OrtAuthenticator.kt
=> Auth schemes

spdx-utils/src/main/resources/declared-license-mapping.yml
[1] https://github.com/pyproj4/pyproj/blob/v2.4.0rel/setup.py
=> declared-license-mapping: Add entry for OSI Approved

README.md
=> README: Improve the scan storage configuration instructions

model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt, reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json, reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml, reporter/src/funTest/assets/static-html-reporter-test-input.yml, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
=> StaticHtmlReporter: Fix license URLs

reporter/src/main/kotlin/reporters/NoticeTemplateReporter.kt
=> NoticeTemplateReporter: Be more specific in a file existence check

spdx-utils/src/main/resources/declared-license-mapping.yml
Found in [1].
[1] https://maven.google.com/com/google/android/libraries/places/places/2.3.0/places-2.3.0.pom
=> Add declared license mapping for "Google Maps Platform Terms of Service"

downloader/src/main/kotlin/Downloader.kt, model/src/main/kotlin/Hash.kt
=> Download hash improvements

downloader/src/funTest/kotlin/DownloaderFunTest.kt
=> DownloaderFunTest: Update an expected exception message

.github/pull_request_template.md, CONTRIBUTING.md
=> Add a PR template the reminds one to write good commit messages

model/src/main/kotlin/OrtResult.kt
=> OrtResult: Fix a typo

cli/src/main/kotlin/commands/DownloaderCommand.kt, downloader/src/main/kotlin/Downloader.kt
=> Improvements to downloading source artifacts

.azure-pipelines/LinuxAnalyzerTest.yml, .azure-pipelines/WindowsAnalyzerTest.yml, model/src/main/kotlin/Scope.kt
=> Fix Azure analyzer tests

analyzer/src/main/kotlin/managers/Gradle.kt
=> Gradle: Add a comment that the daemon is always used

scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/FileCounter.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/LocalScannerTest.kt
=> Scanner version handling improvements

downloader/src/main/kotlin/Downloader.kt
=> Make download functions public

.azure-pipelines/DockerBuild.yml, Dockerfile, build.gradle.kts, gradle.properties, model/.gitignore, model/build.gradle.kts, model/src/main/kotlin/Environment.kt, scripts/docker_build.sh, scripts/import_proxy_certs.sh, spdx-utils/build.gradle.kts
=> Rework ORT versioning

spdx-utils/src/main/resources/declared-license-mapping.yml
[1] https://github.com/zeromq/jeromq/blob/v0.3.5/pom.xml
Please ensure that your pull request adheres to our [contribution guidelines](../CONTRIBUTING.md). Thank you!
=> Add declared license mapping for the GNU license found in [1]

model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt, model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
=> LicenseInfoResolver simplifications

README.md, docs/reporters/AsciidocTemplateReporter.md, reporter/src/main/kotlin/reporters/AsciidocTemplateReporter.kt, reporter/src/main/kotlin/reporters/NoticeTemplateReporter.kt, reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt, reporter/src/main/resources/templates/asciidoc/default.ftl
=> Asciidoc improvements

gradle.properties
See https://github.com/antlr/antlr4/releases/tag/4.9.
=> Gradle: Upgrade ANTLR to version 4.9

scanner/src/main/kotlin/LocalScanner.kt
=> LocalScanner: Fix a typo in a comment
