oss-review-toolkit/ort

- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/2)
> Scanner refactoring

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/5)
> README: Add a Travis CI build badge

- .mention-bot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/6)
> Configure mention-bot to create review requests instead of comments

- scanner/src/main/kotlin/scanners/ScanCode.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/11)
> Fix running ScanCode on Windows

- scanner/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/ScanResultsCache.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/12)
> scanner: Write basic cache statistics to the summary file

- .travis.yml
- analyzer/src/funTest/kotlin/NpmTest.kt
- analyzer/src/funTest/kotlin/PipTest.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- scanner/build.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/13)
> Windows test fixes

- README.md
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/15)
> Add an AppVeyor CI configuration file for running checks on Windows

- scanner/src/main/kotlin/Main.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/16)
> scanner: Also add the declared licenses to the scan summary

- analyzer/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/Main.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/24)
> Remove a few superfluous type declarations in JCommander parameters

- analyzer/src/main/kotlin/managers/Maven.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/26)
> analyzer: Simplify parseVcsUrl() a bit

- analyzer/src/main/kotlin/managers/PIP.kt
- graph/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/Scanner.kt
Fix various findings of the IntelliJ code inspector.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/25)
> Inspect code

- analyzer/src/funTest/kotlin/GradleTest.kt
- analyzer/src/funTest/kotlin/MavenTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/27)
> Optimize tests

- analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- downloader/src/main/kotlin/Main.kt
- model/src/main/kotlin/Package.kt
- model/src/main/kotlin/Project.kt
- scanner/src/main/kotlin/Scanner.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/29)
> Do not allow any project / package properties to be null anymore

- .travis.yml
- analyzer/src/main/kotlin/managers/NPM.kt
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/31)
> Npm upgrade tools

- analyzer/src/funTest/kotlin/GradleTest.kt
- analyzer/src/funTest/kotlin/MavenTest.kt
- analyzer/src/funTest/kotlin/NpmTest.kt
- analyzer/src/funTest/kotlin/PipTest.kt
- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/PackageManagerFactory.kt
- analyzer/src/main/kotlin/managers/Bower.kt
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/CocoaPods.kt
- analyzer/src/main/kotlin/managers/Godep.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/SBT.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/30)
> Package manager factory

- analyzer/src/main/kotlin/PackageManager.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/32)
> PackageManager: Simplify toString() by using an expression body

- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/test/kotlin/ScanCodeTest.kt
- scanner/src/test/resources/esprima-2.7.3_scancode-2.2.1.json
- scanner/src/test/resources/esprima-2.7.3_scancode-2.2.1.post59.970c46191.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/34)
> Ignore ScanCode timeouts

- analyzer/src/main/kotlin/managers/Maven.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/35)
> Code simplifications

- analyzer/src/funTest/kotlin/MainTest.kt
- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/PackageManagerFactory.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/36)
> Fix toString() usage for the PackageManager class

- analyzer/src/funTest/kotlin/GradleTest.kt
- analyzer/src/funTest/kotlin/MavenTest.kt
- analyzer/src/funTest/kotlin/NpmTest.kt
- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/41)
> Simplify the VersionControlSystem class a bit

- analyzer/src/main/kotlin/managers/Gradle.kt
The return@ syntax might be hard to read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/45)
> Gradle: Rework code slight to get rid of return@

- scanner/src/main/kotlin/ArtifactoryCache.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/46)
> scanner: Say so if scan results come from the local cache

- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/resources/META-INF/plexus/components.xml
Please see the individual commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/48)
> Maven improvements

- analyzer/src/main/kotlin/managers/Bower.kt
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/CocoaPods.kt
- analyzer/src/main/kotlin/managers/Godep.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/SBT.kt
- model/src/main/kotlin/PackageReference.kt
- model/src/main/kotlin/Scope.kt
- scanner/src/main/kotlin/ArtifactoryCache.kt
- scanner/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/test/kotlin/ScanResultsCacheTest.kt
- util/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/49)
> Inspection fixes

- util/src/main/kotlin/Utils.kt
- util/src/test/kotlin/UtilsTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/51)
> util: Fix normalizeVcsUrl() for empty URLs

- analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml
- analyzer/src/funTest/assets/projects/external/jgnash-expected-output.yml
- analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-app.yml
- analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-lib-without-repo.yml
- analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-lib.yml
- analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-root.yml
- analyzer/src/funTest/assets/projects/synthetic/project-maven-expected-output-app.yml
- analyzer/src/funTest/assets/projects/synthetic/project-maven-expected-output-lib.yml
- analyzer/src/funTest/assets/projects/synthetic/project-maven-expected-output-root.yml
- analyzer/src/funTest/assets/projects/synthetic/project-npm-expected-output.yml
- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/resources/init.gradle
- model/src/main/kotlin/AnalyzerResult.kt
- model/src/main/kotlin/Project.kt
- scanner/src/main/kotlin/Main.kt
- util/src/main/kotlin/Utils.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/52)
> Various fixes

- .gitmodules
- .travis.yml
- analyzer/src/funTest/assets/projects/external/directories-expected-output.yml
- analyzer/src/funTest/kotlin/SbtTest.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/SBT.kt
- appveyor.yml
- util/src/main/kotlin/ProcessCapture.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/55)
> Add SBT support via "sbt makePom"

- analyzer/src/main/kotlin/managers/NPM.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/58)
> NPM: Do not shadow the outer json variable

- analyzer/src/funTest/kotlin/NpmTest.kt
- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- model/src/main/kotlin/AnalyzerResult.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/56)
> Analyzer error handling

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/61)
> README: Briefly explain how the toolkit works at a high level

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/62)
> README: Improve docs for the list of supported package managers

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/63)
> Gradle: Upgrade Kotlin to version 1.1.61

- .gitmodules
- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
- analyzer/src/funTest/kotlin/PipTest.kt
- analyzer/src/main/kotlin/managers/PIP.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/64)
> Fix handling project meta-data for requirements.txt projects

- analyzer/src/funTest/kotlin/MainTest.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/67)
> Minor code optimizations by using sequences

- analyzer/src/main/kotlin/managers/NPM.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/70)
> NPM: Make the hashAlgorithm var an immutable val

- analyzer/src/main/kotlin/Main.kt
- build.gradle
- downloader/src/main/kotlin/Main.kt
- graph/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/69)
> Use Kotlin 1.2.0 and features

- analyzer/src/main/kotlin/managers/NPM.kt
- build.gradle
- detekt.yml
- util/src/test/kotlin/UtilsTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/71)
> Detekt line length

- analyzer/src/main/kotlin/managers/NPM.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/72)
> Improvements to parsing bogus NPM package.json files

- analyzer/src/main/kotlin/managers/NPM.kt
- util/src/main/kotlin/Utils.kt
- util/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/74)
> Miscellanous minor NPM related improvements

- analyzer/src/funTest/kotlin/TestTags.kt
- analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt
- analyzer/src/funTest/kotlin/gradle/GradleLoggingSubprojectTest.kt
- analyzer/src/funTest/kotlin/gradle/GradleWrapperSubprojectTest.kt
- analyzer/src/funTest/kotlin/gradle/K9MailTest.kt
- analyzer/src/funTest/kotlin/gradle/RobolectricTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/75)
> Add missing Copyright headers to newly created Kotlin files

- .travis.yml
For simplicity do not do this for AppVeyor, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/76)
> Travis: Add a simple check for added Copyright headers on Kotlin files

- analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt
- analyzer/src/funTest/kotlin/gradle/GradleLoggingSubprojectTest.kt
- analyzer/src/funTest/kotlin/gradle/GradleWrapperSubprojectTest.kt
- analyzer/src/funTest/kotlin/gradle/K9MailTest.kt
- analyzer/src/funTest/kotlin/gradle/RobolectricTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/78)
> Minor formatting fixes and code simplifications

- analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/79)
> Minor cleanups in BaseGradleSpec

- downloader/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/82)
> Some minor VCS related code simplifications

- analyzer/src/main/kotlin/managers/SBT.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/83)
> Sbt log no format

- analyzer/build.gradle
- analyzer/src/funTest/kotlin/gradle/GradleLoggingSubprojectTest.kt
- appveyor.yml
- scanner/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/84)
> Expensive test fixes

- downloader/build.gradle
- downloader/src/funTest/kotlin/MercurialTest.kt
- downloader/src/funTest/kotlin/TestTags.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- util/src/main/kotlin/ProcessCapture.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/81)
> Add Mercurial support

- downloader/src/main/kotlin/vcs/Mercurial.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/97)
> Mercurial: Accept "hg" as an alias in isApplicableProvider()

- downloader/src/funTest/kotlin/GitTest.kt
- downloader/src/funTest/kotlin/MercurialTest.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- util/src/main/kotlin/ProcessCapture.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/99)
> Improvements getting a VCS' version

- downloader/src/main/kotlin/vcs/Mercurial.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/100)
> Mercurial: Also check that the vcsRevision is not blank

- downloader/src/main/kotlin/Main.kt
- model/src/main/kotlin/OutputFormat.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/104)
> Always put JvmField annotations onto their own line

- downloader/src/funTest/kotlin/DirectoryTest.kt
- downloader/src/funTest/kotlin/DownloaderTest.kt
- downloader/src/main/kotlin/Main.kt
- model/src/main/kotlin/Package.kt
- util/src/main/kotlin/Utils.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/98)
> Downloader functional tests

- downloader/src/funTest/kotlin/MercurialTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/106)
> Mercurial test improvements

- downloader/src/funTest/kotlin/GitTest.kt
- downloader/src/main/kotlin/vcs/Git.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/107)
> Git test improvements

- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/test/kotlin/VersionControlSystemTest.kt
- util/src/main/kotlin/Utils.kt
- util/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/109)
> Improvements to splitting VCS URLs

- downloader/build.gradle
- downloader/src/funTest/kotlin/SubversionTest.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/110)
> Resolve #86: Add SVN support

- downloader/src/funTest/kotlin/GitTest.kt
- downloader/src/funTest/kotlin/MercurialTest.kt
- downloader/src/funTest/kotlin/SubversionTest.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/111)
> Svn follow up

- util/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/113)
> Minor normalize package name improvements

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
Unfortunately, the test is not stable as Python does not support lock
files or similar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/115)
> Update expected output for python-flask

- model/src/main/kotlin/Package.kt
- model/src/main/kotlin/PackageReference.kt
- util/src/main/kotlin/Utils.kt
- util/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/114)
> Use a reversible encoding for package name normalization

- analyzer/src/main/kotlin/MavenSupport.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/118)
> MavenSupport: Some minor code improvements

- analyzer/build.gradle
- build.gradle
- downloader/build.gradle
- model/build.gradle
- scanner/build.gradle
- util/build.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/119)
> Gradle: Move more common code to the root project

- model/src/main/kotlin/Project.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/126)
> Project: Minor formatting fix by removing a blank line

- .travis.yml
- appveyor.yml
- build.gradle
- util/src/main/kotlin/DiskCache.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/128)
> Diskcache improvements

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/147)
> Gradle: Upgrade to Kotlin 1.2.10

- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- analyzer/src/funTest/kotlin/integration/GradleIntegrationTest.kt
- analyzer/src/funTest/kotlin/integration/OssReviewToolkitIntegrationTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/145)
> Add integration tests

- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml
- analyzer/src/funTest/kotlin/GradleTest.kt
- analyzer/src/main/resources/init.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/154)
> Improve handling of unresolvable Gradle configurations

- README.md
Kotlin/Gradle/Java newbies will benefit from just a little more guidance. It's easy but it's not obvious that it's easy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/156)
> update the getting started steps in the README

- .travis.yml
- appveyor.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/159)
> CI changes

- Dockerfile
- docker-build.sh
- docker-run.sh
/cc @iamwillbar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/160)
> Docker improvements, part two

- .editorconfig
- .travis.yml
- analyzer/src/funTest/kotlin/NpmTest.kt
- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- analyzer/src/funTest/kotlin/integration/GradleIntegrationTest.kt
- analyzer/src/funTest/kotlin/integration/OssReviewToolkitIntegrationTest.kt
- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/MavenLogger.kt
- analyzer/src/main/kotlin/PackageManagerFactory.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- build.gradle
- detekt.yml
- downloader/src/funTest/kotlin/DirectoryTest.kt
- downloader/src/funTest/kotlin/DownloaderTest.kt
- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- graph/src/main/kotlin/Main.kt
- model/src/main/kotlin/Package.kt
- scanner/src/main/kotlin/ArtifactoryCache.kt
- scanner/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/ScanResultsCache.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/test/kotlin/ScanResultsCacheTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/161)
> Lint improvements

- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- analyzer/src/funTest/kotlin/integration/VueJsIntegrationTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/163)
> Test vue js

- .travis.yml
- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- appveyor.yml
- scanner/src/main/kotlin/ArtifactoryCache.kt
- utils/src/main/kotlin/Utils.kt
Align cache directories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/165)
> Cache dirs

- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- downloader/src/main/kotlin/Main.kt
- graph/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/ScanResultsCache.kt
This ensures consistent use of the same name for the tools within code.
Also introduce a constant where the string is only used once for
consistency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/168)
> Add constants for tool names

- analyzer/src/main/kotlin/PackageManager.kt
- scanner/src/main/kotlin/ArtifactoryCache.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/169)
> Make HTTP_CACHE_PATH const

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/178)
> Travis: Deploy test result artifacts to S3 for easier debugging

- downloader/src/test/kotlin/MercurialTest.kt
- downloader/src/test/kotlin/SubversionTest.kt
To simplify and unify code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/180)
> downloader: Use the new File.unpack() in remaining tests

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/181)
> README: Add hint to use en_US.UTF-8 as locale

- downloader/src/funTest/kotlin/MercurialTest.kt
- downloader/src/funTest/kotlin/SubversionTest.kt
- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
This nicely simplifies the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/183)
> Make VersionControlSystem.download() take VcsInfo as the argument

- downloader/src/main/kotlin/vcs/Subversion.kt
The surrounding code expects and only handles the DownloadException. This
avoids an unnecessary crash when the SVN repository could not be checked
out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/185)
> Subversion: Wrap IOException in download() in DownloadException

- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- downloader/src/funTest/kotlin/DownloaderTest.kt
- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/vcs/Git.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/186)
> Various directory handling fixes

- analyzer/src/main/kotlin/managers/Maven.kt
Do print a warning instead of aborting when a project cannot be built in
the prepareResolution() function. The projects built there are not
necessarily required for dependency resolution, so better try to continue
instead of aborting already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/187)
> Maven: Do not abort when project cannot be built in prepareResolution()

- downloader/src/funTest/kotlin/MercurialTest.kt
- downloader/src/funTest/kotlin/SubversionTest.kt
- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/188)
> Some VCS related improvements

- downloader/src/funTest/kotlin/GitTest.kt
- downloader/src/funTest/kotlin/MercurialTest.kt
- downloader/src/funTest/kotlin/SubversionTest.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- downloader/src/test/kotlin/GitTest.kt
- downloader/src/test/kotlin/MercurialTest.kt
- downloader/src/test/kotlin/SubversionTest.kt
/cc @jeffmcaffer @iamwillbar 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/189)
> Implement guessing of VCS revisions based on package versions

- downloader/src/funTest/kotlin/GitTest.kt
- downloader/src/funTest/kotlin/MercurialTest.kt
- downloader/src/funTest/kotlin/SubversionTest.kt
To ensure a consistent ordering across platforms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/192)
> downloader: Sort the list of actual files in tests

- downloader/src/funTest/kotlin/DownloaderTest.kt
These are now covered by the reworked VCS-specific functional tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/193)
> DownloaderTest: Remove VCS-related tests

- scanner/src/main/kotlin/scanners/ScanCode.kt
This also ensures to only use 1 process on Travis CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/199)
> ScanCode: Auto-detect the number of processes to use

- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/198)
> downloader: Move isAtLeastVersion() to the VersionControlSystem base class

- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/200)
> Various small PIP-related fixes and improvements

- downloader/src/main/kotlin/vcs/Git.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/202)
> Git: Add a performance optimization to limit history depth to fetch

- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/test/kotlin/VersionControlSystemTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/203)
> VersionControlSystem: Split arbitrary GitHub extra path components

- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- downloader/src/test/kotlin/GitTest.kt
- downloader/src/test/kotlin/MercurialTest.kt
- downloader/src/test/kotlin/SubversionTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/210)
> Fixes for issues discovered while analyzing Vue.js

- downloader/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/207)
> Rework console output to use logging instead of p()

- analyzer/src/funTest/kotlin/BabelTest.kt
- analyzer/src/funTest/kotlin/MainTest.kt
- analyzer/src/funTest/kotlin/NpmTest.kt
- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- downloader/src/funTest/kotlin/DirectoryTest.kt
- downloader/src/funTest/kotlin/DownloaderTest.kt
- downloader/src/funTest/kotlin/GitTest.kt
- downloader/src/funTest/kotlin/MercurialTest.kt
- downloader/src/funTest/kotlin/SubversionTest.kt
- downloader/src/test/kotlin/ArchiveUtilsTest.kt
- downloader/src/test/kotlin/GitTest.kt
- downloader/src/test/kotlin/MercurialTest.kt
- downloader/src/test/kotlin/SubversionTest.kt
- scanner/src/funTest/kotlin/ScanPathTest.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/213)
> Do not follow symlinks or junctions when recursively deleting files

- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- downloader/src/main/kotlin/Main.kt
- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
To be in line with safeMkdirs().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/214)
> Throw an exception if safeDeleteRecursively() fails

- build.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/215)
> Dep upgrades

- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/217)
> Support normalizing crazy GitHub URLs

- analyzer/src/funTest/kotlin/BabelTest.kt
- analyzer/src/funTest/kotlin/NpmTest.kt
- downloader/src/funTest/kotlin/BabelTest.kt
- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/216)
> More fixes for scanning Vue.js

- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/test/kotlin/VersionControlSystemTest.kt
- model/src/main/kotlin/VcsInfo.kt
- model/src/test/kotlin/VcsInfoTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/227)
> Support Gitlab more consistently

- .travis.yml
- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- appveyor.yml
- build.gradle
- downloader/src/funTest/kotlin/DownloaderTest.kt
- downloader/src/funTest/kotlin/GitTest.kt
- downloader/src/funTest/kotlin/MercurialTest.kt
- downloader/src/funTest/kotlin/SubversionTest.kt
- scanner/src/funTest/kotlin/ScanPathTest.kt
- scanner/src/test/kotlin/ScanCodeTest.kt
- utils-test/src/main/kotlin/TestTags.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/232)
>  Exclude the ScanCodeTest from Travis Cron runs

- analyzer/src/funTest/kotlin/GradleTest.kt
- analyzer/src/funTest/kotlin/MavenTest.kt
- downloader/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/235)
> Miscellaneous minor changes

- downloader/src/main/kotlin/vcs/Git.kt
For NPM packages is it sometimes the case that the "gitHead" from the
registry points to a non-fetchable commit, but the repository still has
a tag for the package version (pointing to a different commit). Allow to
fall back to the guessed revision based on the version in such cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/236)
> Git: Fall back to a guessed revision if checking out the specified one failed

- analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- downloader/src/funTest/kotlin/BabelTest.kt
- downloader/src/funTest/kotlin/DownloaderTest.kt
- downloader/src/main/kotlin/Main.kt
- model/src/main/kotlin/HashAlgorithm.kt
- model/src/main/kotlin/RemoteArtifact.kt
- model/src/test/kotlin/PackageCurationTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/234)
>  Introduce the HashAlgorithm enum class 

- model/src/main/kotlin/HashAlgorithm.kt
See https://github.com/FasterXML/jackson-module-kotlin/issues/75#issuecomment-314302483.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/241)
> HashAlgorithm: Make Jackson actually discover the JsonCreator function

- analyzer/src/main/kotlin/managers/NPM.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/243)
> Better support private NPM packages

- downloader/src/main/kotlin/vcs/Git.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/245)
> Git: Also log if no revision could be guessed

- .travis.yml
- appveyor.yml
- scanner/src/funTest/kotlin/ScanPathTest.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/246)
>  Support Licensee as a scanner

- build.gradle
See https://github.com/JetBrains/kotlin/blob/1.2.20/ChangeLog.md#1221.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/248)
> Gradle: Update to Kotlin 1.2.21

- analyzer/src/main/kotlin/managers/NPM.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/250)
> NPM: Log an info for DefinitelyTyped special case handling

- analyzer/src/main/kotlin/MavenSupport.kt
Ignore local repositories in MavenSupport.requestRemoteArtifact() because
remote artifacts should never point to local files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/253)
> Maven: Ignore local repositories when looking for remote artifacts

- downloader/src/main/kotlin/Main.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/254)
> downloader: Improve logging a bit

- build.gradle
- gradle.properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/255)
> Dependency upgrades

- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle/lib/build.gradle
- analyzer/src/main/kotlin/GradleSupport.kt
- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/resources/init.gradle
See the individual commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/257)
> Gradle extensions and classifiers

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
- analyzer/src/main/kotlin/managers/PIP.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/256)
> Populate the source artifact field from PyPI metadata

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/259)
> README: List supported license scanners

- analyzer/src/main/kotlin/MavenSupport.kt
By only taking the first line into account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/260)
> MavenSupport: Avoid a newline character becoming part of the hash

- analyzer/src/main/kotlin/managers/PIP.kt
- downloader/src/main/kotlin/ArchiveUtils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/262)
> Miscellaneous minor style / doc improvements

- downloader/src/main/kotlin/Main.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/265)
> downloader: Yet some more minor logging improvements

- analyzer/src/main/kotlin/MavenSupport.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/267)
> MavenSupport: Minor performance improvement by reading lines as a sequence

- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
For some background information see
https://github.com/nexB/scancode-toolkit/issues/884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/268)
> scanner: Add some code to assist with debugging scanner issues

- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- analyzer/src/funTest/kotlin/MainTest.kt
- analyzer/src/main/kotlin/Main.kt
- analyzer/src/test/kotlin/MergedResultsBuilderTest.kt
- model/src/main/kotlin/MergedAnalyzerResult.kt
- model/src/main/kotlin/Project.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/258)
> Merge analyzer result into single YAML

- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-root.yml
- analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-app.yml
- analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-lib.yml
- analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-root.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
- analyzer/src/funTest/kotlin/BabelTest.kt
- analyzer/src/funTest/kotlin/GradleTest.kt
- analyzer/src/funTest/kotlin/MainTest.kt
- analyzer/src/funTest/kotlin/MavenTest.kt
- analyzer/src/funTest/kotlin/NpmTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/277)
> Fix MainTest and do some related cleanups

- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/test/kotlin/GitTest.kt
- downloader/src/test/kotlin/MercurialTest.kt
- downloader/src/test/kotlin/SubversionTest.kt
- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/276)
> Rework guessing revision names for versions and testing thereof

- analyzer/src/funTest/kotlin/BabelTest.kt
- analyzer/src/funTest/kotlin/MainTest.kt
- analyzer/src/funTest/kotlin/NpmTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/278)
> analyzer: Align the use of normalizeVcsUrl() in tests

- scanner/src/main/kotlin/Main.kt
Resolves #90
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/239)
> Limit scan result to specified scopes

- README.md
- Add description for new `--merge-results` analyzer's parameter.
- Add description for new `--scopes` scanner's parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/279)
> Update usage description for analyzer and scanner new parameters

- analyzer/src/main/kotlin/Main.kt
- analyzer/src/test/kotlin/MergedResultsBuilderTest.kt
- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- graph/src/main/kotlin/Main.kt
- model/src/main/kotlin/MergedAnalyzerResult.kt
- model/src/main/kotlin/OutputFormat.kt
- model/src/main/kotlin/Package.kt
- model/src/main/kotlin/PackageReference.kt
- model/src/main/kotlin/Project.kt
- model/src/main/kotlin/Scope.kt
- scanner/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/280)
> Miscellaneous minor improvements throughout the code base

- README.md
- analyzer/src/main/kotlin/MavenSupport.kt
- appveyor.yml
- downloader/src/funTest/kotlin/DownloaderTest.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/283)
> Support downloads from SourceForge

- appveyor.yml
- build.gradle
- gradle.properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/284)
> Enable the Gradle build cache

- appveyor.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/285)
> Enable scheduled builds on AppVeyor

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/289)
> README: Minor wording improvement

- downloader/src/funTest/kotlin/GitDownloadTest.kt
- downloader/src/funTest/kotlin/MercurialDownloadTest.kt
- downloader/src/funTest/kotlin/SubversionDownloadTest.kt
- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/288)
> Miscellaneous minor VCS improvements

- .travis.yml
- appveyor.yml
- downloader/src/funTest/kotlin/CvsDownloadTest.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/test/kotlin/CvsTest.kt
Resolves #112.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/291)
> downloader: Add CVS support

- analyzer/src/main/kotlin/managers/NPM.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/294)
> Consistenly use the raw name as part of the identifier

- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml
- analyzer/src/main/resources/init.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/295)
> Fix gradle names

- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/297)
> Implement recursive download of Git submodules

- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- downloader/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/ArtifactoryCache.kt
- scanner/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/302)
> Misc improvements

- scanner/src/funTest/kotlin/ScanPathTest.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/303)
> Miscellaneous scanner-related minor improvements

- README.md
- scanner/src/funTest/kotlin/ScanPathTest.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
See https://github.com/boyter/lc.
/cc @boyter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/304)
> scanner: Add Ben Boyter's lc as a scanner

- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/305)
> scanner: Only bootstrap a scanner if it is not in PATH

- scanner/src/main/kotlin/scanners/BoyterLc.kt
lc can scan multiple directories and / or files now as
https://github.com/boyter/lc/issues/6 got resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/307)
> BoyterLc: Upgrade lc to version 1.1.1

- scanner/src/main/kotlin/Scanner.kt
- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/308)
> utils: Return the actual path for an executable in the PATH environment

- build.gradle
- scanner/src/funTest/kotlin/ScanPathTest.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- utils/src/main/kotlin/ProcessCapture.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/309)
> Miscellanous scanner-related improvements

- appveyor.yml
- build.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/310)
> Generate and archive dokka artifacts 

- downloader/src/main/kotlin/vcs/Cvs.kt
Otherwise the fall-back to download source artifacts does not kick in
for CVS downloads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/312)
> Cvs: Wrap IOExceptions in a DownloadException

- scanner/src/funTest/kotlin/ScanPathTest.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/314)
> Stabilize Boyter lc support

- analyzer/src/main/resources/init.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/313)
> Gradle lenient configuration

- analyzer/src/main/kotlin/managers/SBT.kt
To suppress interactive prompts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/317)
> Sbt: Always run in batch mode on non-Windows

- analyzer/src/main/kotlin/managers/Gradle.kt
If a ProjectBuildingException occurs while parsing a dependency handle this
exception and add the error to the PackageReference instead of aborting
building the dependency tree.
This align the Gradle implementation with the Maven implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/318)
> Gradle: Handle ProjectBuildingException the same way as in Maven

- analyzer/src/main/kotlin/managers/SBT.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/319)
> Sbt: Do not try to generate POMs for sub-modules in a multi-module project

- scanner/src/main/kotlin/scanners/ScanCode.kt
If an error occured while scanning a file, also add the affected file path
to the scan results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/321)
> ScanCode: Add the affected file to the error message

- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/323)
> Make normalizeVcsUrl() ensure the generic "git" SSH user name for GitHub

- scanner/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/Scanner.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/328)
> Use the processed VCS information as part of the scanner cache key

- analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-app.yml
- analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-lib.yml
- analyzer/src/funTest/assets/projects/synthetic/maven/lib/pom.xml
- analyzer/src/funTest/assets/projects/synthetic/maven/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/327)
> Maven properties

- analyzer/src/main/kotlin/managers/SBT.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/335)
> Potentially allow executions of "sbt makePom" in sub-projects to fail

- analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
- analyzer/src/funTest/kotlin/SbtTest.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- downloader/src/funTest/kotlin/CvsDownloadTest.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/336)
> Use the correct project directory in SBT mode 

- scanner/src/main/kotlin/ArtifactoryCache.kt
Please see the individual commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/337)
> Artifactory io exceptions

- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
This is a fixup for afeac51.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/338)
> analyzer: Fix expected results for MainTest

- scanner/src/main/kotlin/scanners/ScanCode.kt
This includes a massive refactoring with lots of performance
improvements. For details see
https://github.com/nexB/scancode-toolkit/pull/885
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/340)
> Upgrade ScanCode to the latest development version

- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/339)
> Support downloading the latest revision from "trunk" for Subversion

- scanner/src/main/kotlin/scanners/ScanCode.kt
Otherwise upgrades between major versions of ScanCode are not guaranteed
to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/341)
> ScanCode: Explicitly (re-)configure as part of bootstrapping

- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/343)
> utils: Enhance filterVersionNames() to work with different capitalization

- scanner/src/main/kotlin/Scanner.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/344)
> Scanner: Log when a scanner gets bootstrapped

- analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-app.yml
- analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-lib.yml
- analyzer/src/funTest/assets/projects/synthetic/maven/lib/pom.xml
- analyzer/src/main/kotlin/MavenSupport.kt
- utils/src/main/kotlin/ArchiveUtils.kt
See the individual commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/349)
> Pom source artifact

- analyzer/src/main/kotlin/MavenSupport.kt
When searching for an artifact in remote repositories handle the
NoRepositoryLayoutException that occurs if the repository uses an
unsupported layout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/348)
> Maven: Handle NoRepositoryLayoutException

- utils/src/main/kotlin/ArchiveUtils.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/352)
> ArchiveUtils: Minor code improvements

- scanner/src/main/kotlin/Main.kt
This also fixes issues where the local path was still referred to as a
package identifier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/353)
> scanner: Inline the scanEntry() function to allow some simplifications

- scanner/src/main/kotlin/LocalScanner.kt
Catch ScanExceptions occuring when scanning a package to prevent the whole
scan from stopping because a single package could not be scanned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/354)
> LocalScanner: Catch scan exceptions for single packages

- analyzer/src/main/kotlin/managers/Maven.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/355)
> downloader: Return the correct working tree root for GitRepo

- build.gradle
This contains a revert for commit e182e72.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/357)
> Gradle: Upgrade to dokka version 0.9.16

- analyzer/src/main/kotlin/managers/PIP.kt
- utils/src/main/kotlin/ProcessCapture.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/356)
> Create stdout and stderr files in the same temporary directory

- downloader/src/main/kotlin/vcs/Cvs.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/359)
> Cvs: Make use of the new searchUpwardsForSubdirectory() function

- analyzer/src/main/kotlin/managers/Maven.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/360)
> Make searchUpwardsForSubdirectory() an extension function

- downloader/src/test/kotlin/GitTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/365)
> GitTest: Fix tests by adding new tag 0.11.0 to expected tags list

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/364)
> Add a CONTRIBUTING.md file to explain our contribution guidelines

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/367)
> CONTRIBUTING: Mention the CLA

- scanner/src/main/kotlin/scanners/ScanCode.kt
- utils/src/main/kotlin/Utils.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/363)
> scanner: Allow for slight variation on run dir

- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/Unmanaged.kt
Please see the individual commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/371)
> Unmanaged projects

- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app-3.4.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle/gradle/wrapper/gradle-wrapper.properties
- analyzer/src/funTest/kotlin/GradleTest.kt
Also adapt the compatibility test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/374)
> analyzer: Upgrade Gradle test project to Gradle 4.6

- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/test/kotlin/ScanCodeTest.kt
- scanner/src/test/resources/very-long-json-lines_scancode-2.2.1.post277.4d68f9377.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/379)
> Handle ScanCode MemoryErrors similar to timeouts

- model/src/main/kotlin/AnalyzerResult.kt
- scanner/src/main/kotlin/Main.kt
See the individual commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/378)
> Include analyzer errors in the scan summary

- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/test/kotlin/ScanCodeTest.kt
- scanner/src/test/resources/esprima-2.7.3_scancode-2.2.1.post277.4d68f9377.json
The ScanCode error message has changed with the last ScanCode update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/381)
> scanner: Update the pattern to match ScanCode timeout errors

- scanner/src/main/kotlin/scanners/ScanCode.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/382)
> ScanCode: Clarify where the "(File: ...)" part in the patterns comes from

- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/385)
> Upgrade Ben Boyter's lc scanner

- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/PackageManagerFactory.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/384)
> Quick fixes

- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- downloader/src/funTest/kotlin/CvsDownloadTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/386)
> Cron fixes

- analyzer/src/main/kotlin/managers/PIP.kt
The new --json-tree option allows to call pipdeptree only once now, see
https://github.com/naiquevin/pipdeptree/pull/91
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/389)
> PIP: Upgrade pipdeptree to version 0.11.0 which allows to simplify code

- GettingStarted.md
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/388)
> Getting Started

- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/SBT.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- utils/src/main/kotlin/ProcessCapture.kt
- utils/src/main/kotlin/Utils.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/393)
> ProcessCapture: Add isSuccess() and isError() convenience functions

- model/src/main/kotlin/AnalyzerResult.kt
- model/src/test/kotlin/AnalyzerResultTest.kt
- scanner/src/main/kotlin/Main.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/391)
> Analyzer result improvements

- downloader/src/main/kotlin/vcs/Git.kt
This is to ensure e.g. git-describe works locally in such cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/394)
> Git: Create a local tag when doing a shallow fetch of a remote tag

- model/src/main/kotlin/AnalyzerResult.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/395)
> AnalyzerResult: Only collect project errors if they are not empty

- analyzer/src/funTest/kotlin/GradleTest.kt
- downloader/src/funTest/kotlin/CvsDownloadTest.kt
- downloader/src/funTest/kotlin/MercurialDownloadTest.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/test/kotlin/CvsTest.kt
- downloader/src/test/kotlin/MercurialTest.kt
- downloader/src/test/kotlin/SubversionTest.kt
- downloader/src/test/kotlin/VersionControlSystemTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/401)
> Test config changes

- downloader/src/funTest/kotlin/BeanUtilsTest.kt
- downloader/src/funTest/kotlin/SubversionDownloadTest.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/test/kotlin/SubversionTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/402)
> Miscellaneous VCS test related improvements

- analyzer/src/main/kotlin/PackageManager.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/403)
> Introduce a list of directories to ignore during analysis, plus another small change

- scanner/src/funTest/kotlin/ScanPathTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/404)
> Discard cached scan results with a file count of 0

- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/406)
> Align Git history depth to 50

- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-root.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle/app/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle/lib/build.gradle
- analyzer/src/funTest/kotlin/GradleTest.kt
- analyzer/src/main/kotlin/GradleSupport.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/resources/init.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/407)
> Support Gradle publishing

- analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle/app/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-app.yml
- analyzer/src/funTest/kotlin/MavenTest.kt
- analyzer/src/main/kotlin/MavenSupport.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/408)
> Maven module dependencies

- analyzer/src/main/kotlin/MavenSupport.kt
Use the global settings file when creating ProjectBuildingRequests. This
enables the user to configure what is described here:
https://maven.apache.org/settings.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/413)
> MavenSupport: Use the global settings file

- downloader/src/main/kotlin/Main.kt
- model/src/main/kotlin/Identifier.kt
- model/src/main/kotlin/MergedAnalyzerResult.kt
- utils/src/main/kotlin/ArchiveUtils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/420)
> Downloader improvements

- downloader/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/422)
> Downloader blank name

- utils/src/main/kotlin/ArchiveUtils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/423)
> Archive utils fixes

- analyzer/src/main/kotlin/managers/NPM.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- model/src/main/kotlin/PackageCurationData.kt
- scanner/src/main/kotlin/ArtifactoryCache.kt
- scanner/src/main/kotlin/LocalScanner.kt
- utils/src/main/kotlin/Utils.kt
And where it improves readability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/424)
> Use takeIf/takeUnless if it is shorter than using if/else

- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/test/kotlin/ScanCodeTest.kt
- scanner/src/test/resources/kotlin-annotation-processing-gradle-1.2.21_scancode.json
Fix the documentation for mapTimeoutErrors() and do some minor
alignments along the way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/426)
> scanner: Map ScanCode messages for unkown errors in general

- downloader/src/funTest/kotlin/DirectoryTest.kt
- downloader/src/main/kotlin/Main.kt
- model/src/main/kotlin/Package.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/425)
> Downloader target dir

- analyzer/src/main/kotlin/PackageManager.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/431)
> Packagemanager: Extend ignored directories to Python virtualenvs

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/432)
> Gradle: Upgrade to Kotlin 1.2.31

- utils/src/main/kotlin/DiskCache.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/433)
> DiskCache: Properly close the Snapshot in asKey()

- analyzer/src/main/kotlin/MavenSupport.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/429)
> Maven session settings

- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
Also apply some minor improvements to filterVersionNames() along the
way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/438)
> utils: Verify that filterVersionNames() does not return empty strings

- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- analyzer/src/funTest/kotlin/MainTest.kt
- analyzer/src/test/kotlin/MergedResultsBuilderTest.kt
- model/src/main/kotlin/Identifier.kt
- model/src/main/kotlin/MergedAnalyzerResult.kt
- model/src/main/kotlin/Package.kt
- model/src/main/kotlin/Project.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/440)
> Merged analyzer result improvements

- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- analyzer/src/funTest/kotlin/BabelTest.kt
- analyzer/src/funTest/kotlin/GradleTest.kt
- analyzer/src/funTest/kotlin/MainTest.kt
- analyzer/src/funTest/kotlin/MavenTest.kt
- analyzer/src/funTest/kotlin/NpmTest.kt
- analyzer/src/funTest/kotlin/SbtTest.kt
- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/PackageCurationProvider.kt
- analyzer/src/test/kotlin/PackageManagerTest.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- model/src/main/kotlin/MergedAnalyzerResult.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/447)
> Fix merged results tests on windows

- analyzer/src/main/kotlin/Main.kt
- model/src/main/kotlin/MergedAnalyzerResult.kt
- model/src/main/kotlin/Package.kt
- model/src/main/kotlin/PackageReference.kt
- model/src/main/kotlin/Project.kt
- model/src/main/kotlin/Scope.kt
- model/src/test/kotlin/MergedAnalyzerResultTest.kt
- model/src/test/kotlin/MergedResultsBuilderTest.kt
- model/src/test/kotlin/ProjectTest.kt
Various model refactorings and improvements as a preparation to support the all-dependencies file in the scanner. For details see the commit messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/445)
> Various model refactorings and improvements

- downloader/src/main/kotlin/vcs/Git.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/448)
> Git: Disable fetching single revisions from GitHub SSH URLs

- .gitmodules
- .travis.yml
- analyzer/build.gradle
- analyzer/src/funTest/assets/projects/external/godep-expected-output.yml
- analyzer/src/funTest/assets/projects/external/qmstr-expected-output.yml
- analyzer/src/funTest/assets/projects/external/sprig-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/all-managers/Gopkg.toml
- analyzer/src/funTest/assets/projects/synthetic/godep/no-lockfile/Gopkg.toml
- analyzer/src/funTest/assets/projects/synthetic/godep/no-lockfile/main.go
- analyzer/src/funTest/kotlin/GoDepTest.kt
- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/test/kotlin/PackageManagerTest.kt
- appveyor.yml
- docs/README.md
- gradle.properties
- utils/src/main/kotlin/ProcessCapture.kt
This addresses #91 in a roundabout way, using the import feature of [dep](https://github.com/golang/dep).
The name `GoDep` is bad because it sounds like [godep](https://github.com/tools/godep) when it actually is [dep](https://github.com/golang/dep). But `Dep` is also bad because it is very generic. I don't have a strong opinion on this.
I could not find a way to avoid copying the project to a temporary directory. It needs to be inside a `GOPATH` and a `GOPATH` mandates all code to be in a directory called `src`. Plus running `dep ensure`/`dep init` and `go get` downloads lots of files to various locations, which would be harder to clean up individually than `node_modules` or a virtualenv. Speaking of, downloading everything multiple times is really ugly and slow. Maybe we can keep …
> Add a package manager implementation for Go dep

- Dockerfile
This is a preparation for getting the image deployed to Docker Hub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/452)
> Dockerfile: Add a license header

- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml
- analyzer/src/main/resources/init.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/454)
> analyzer: Fix identifiers in case of Gradle resolution errors

- docs/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/458)
> README: Add Yarn to list of supported package managers

- analyzer/src/main/kotlin/managers/GoDep.kt
Because we can.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/461)
> GoDep: Make NO_LOCKFILE const

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
Python packages now seem to be hosted at pythonhosted.org.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/468)
> analyzer: Update PIP expected test results

- .mailmap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/471)
> Add a .mailmap file to associate commits from different mail addresses

- downloader/src/main/kotlin/Main.kt
- model/build.gradle
- model/src/main/kotlin/Identifier.kt
- model/src/main/kotlin/Mappers.kt
- model/src/main/kotlin/Provenance.kt
- model/src/main/kotlin/ScanResult.kt
- model/src/main/kotlin/ScanResultContainer.kt
- model/src/main/kotlin/ScanSummary.kt
- model/src/main/kotlin/ScannerDetails.kt
- model/src/test/assets/expected-scan-results.yml
- model/src/test/kotlin/ScanResultContainerTest.kt
- scanner/src/funTest/kotlin/HttpCacheTest.kt
- scanner/src/funTest/kotlin/ScanPathTest.kt
- scanner/src/main/kotlin/ArtifactoryCache.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/ScanResultsCache.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
Create a new output format for the scanner tool that contains much more information, for example provenance information about the scanned source. For details see the commit messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/460)
> New scan result format

- model/src/main/kotlin/ScannerDetails.kt
Also rename the variable to be more speaking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/475)
> ScannerDetails: Use an EnumSet instead of a list of enums

- docs/GettingStarted.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/479)
> docs: Mention required Go tools in Getting Started

- analyzer/src/main/kotlin/GradleSupport.kt
- analyzer/src/main/resources/init.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/482)
> Gradle interop fixes

- analyzer/src/funTest/kotlin/integration/GradleIntegrationTest.kt
- analyzer/src/funTest/kotlin/integration/VueJsIntegrationTest.kt
- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- downloader/src/funTest/kotlin/BabelTest.kt
- downloader/src/funTest/kotlin/BeanUtilsTest.kt
- downloader/src/funTest/kotlin/CvsDownloadTest.kt
- downloader/src/funTest/kotlin/DirectoryTest.kt
- downloader/src/funTest/kotlin/DownloaderTest.kt
- downloader/src/funTest/kotlin/GitDownloadTest.kt
- downloader/src/funTest/kotlin/MercurialDownloadTest.kt
- downloader/src/funTest/kotlin/SubversionDownloadTest.kt
- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/test/kotlin/VersionControlSystemTest.kt
- model/src/main/kotlin/PackageCurationData.kt
- model/src/main/kotlin/VcsInfo.kt
- model/src/test/assets/expected-scan-results.yml
- model/src/test/kotlin/PackageCurationTest.kt
- model/src/test/kotlin/ScanResultContainerTest.kt
- model/src/test/kotlin/VcsInfoTest.kt
- scanner/src/funTest/kotlin/HttpCacheTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/476)
> VcsInfo: Add a field for the resolved revision

- analyzer/src/main/kotlin/managers/PIP.kt
Resolves #489.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/492)
> PIP: Use the new URL for PyPI

- scanner/src/main/kotlin/scanners/Licensee.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/493)
> Licensee: Work around Travis CI not being able to handle gem user installs

- downloader/src/main/kotlin/VersionControlSystem.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/501)
> VersionControlSystem: Minor code simplification in isAtLeastVersion()

- analyzer/src/main/kotlin/managers/SBT.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/503)
> SBT: Support Scala projects that do not contain a build file in their root

- .gitattributes
- analyzer/src/funTest/kotlin/GoDepTest.kt
- analyzer/src/funTest/kotlin/MainTest.kt
- analyzer/src/funTest/kotlin/NpmTest.kt
- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- analyzer/src/funTest/kotlin/integration/GradleIntegrationTest.kt
- analyzer/src/funTest/kotlin/integration/VueJsIntegrationTest.kt
- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/MavenLogger.kt
- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/resources/init.gradle
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- downloader/src/test/kotlin/CvsTest.kt
- downloader/src/test/kotlin/GitTest.kt
- downloader/src/test/kotlin/MercurialTest.kt
- downloader/src/test/kotlin/SubversionTest.kt
- model/src/main/kotlin/MergedAnalyzerResult.kt
- model/src/test/kotlin/MergedAnalyzerResultTest.kt
- scanner/src/test/kotlin/ScanResultsCacheTest.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/504)
> Simplify path handling throughout the code base

- build.gradle
This fixes https://youtrack.jetbrains.com/issue/KT-23901.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/508)
> Gradle: Upgrade to Kotline 1.2.41

- analyzer/src/main/resources/init.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/511)
> init.gradle: Use a dedicated error message if the result is null

- scanner/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/514)
> Scanner refactorings

- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- analyzer/src/funTest/kotlin/MainTest.kt
- analyzer/src/main/kotlin/Main.kt
- model/src/main/kotlin/MergedAnalyzerResult.kt
- model/src/test/kotlin/MergedAnalyzerResultTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/515)
> Remove local paths from MergedAnalyzerResult

- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/resources/bundler_dependencies.rb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/517)
> Helper script resources

- docs/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/519)
> Add Bundler to the list of supported package managers

- .appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/520)
> AppVeyor: Sort cache directories alphabetically

- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/Unmanaged.kt
- downloader/src/main/kotlin/Main.kt
- graph/src/main/kotlin/Main.kt
- model/src/main/kotlin/AnalyzerResult.kt
- model/src/main/kotlin/MergedAnalyzerResult.kt
- model/src/main/kotlin/ProjectAnalyzerResult.kt
- model/src/test/kotlin/AnalyzerResultTest.kt
- model/src/test/kotlin/MergedAnalyzerResultTest.kt
- model/src/test/kotlin/ProjectAnalyzerResultTest.kt
- model/src/test/kotlin/ProjectTest.kt
- scanner/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/518)
> Rename analyzer results

- downloader/src/main/kotlin/Main.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/522)
> downloader: Rename a variable as we have no "merged" analyzer result anymore

- docs/README.md
- scanner/src/funTest/kotlin/ScanPathTest.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- utils/src/main/kotlin/OS.kt
/cc @jpeddicord
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/525)
> Add basic support for the Askalono scanner

- model/src/main/kotlin/ScanResult.kt
- scanner/src/funTest/kotlin/HttpCacheTest.kt
- scanner/src/main/kotlin/ArtifactoryCache.kt
- scanner/src/main/kotlin/ScanResultsCache.kt
Please see the commit message for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/524)
> Raw result optional

- analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output.yml
- analyzer/src/main/kotlin/managers/Bundler.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/526)
> Bundler fixes

- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- downloader/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/528)
> Simple names

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/530)
> Gradle: Upgrade to detekt version 1.0.0.RC7

- scanner/src/main/kotlin/scanners/Askalono.kt
This now officially has a Windows binary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/538)
> Askalono: Upgrade to version 0.2.0

- scanner/src/main/kotlin/LocalScanner.kt
- utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/542)
> No bootstrap empty

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/543)
> Gradle: (Re-)Configure all test tasks in a single place

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/544)
> Gradle: Use single quotes where no variable interpolation is required

- scanner/src/main/kotlin/ArtifactoryCache.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/547)
> Beautify log output a bit in some places

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml
- analyzer/src/funTest/assets/projects/synthetic/bundler/gemspec/Gemfile.lock
- analyzer/src/funTest/assets/projects/synthetic/bundler/gemspec/test-project.gemspec
- analyzer/src/funTest/assets/projects/synthetic/pip-expected-output.yml
- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/548)
> Take a homepage URL into account when enriching VCS info

- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/549)
> Scancode upgrade

- downloader/src/main/kotlin/Main.kt
- utils/src/main/kotlin/ArchiveUtils.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/552)
> Add support for unpacking Ruby Gems as source artifacts

- scanner/src/main/kotlin/ArtifactoryCache.kt
- scanner/src/test/kotlin/ScannerDetailsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/550)
> Scan cache logging

- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/test/kotlin/NpmTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/557)
> analyzer: Add another check for crazy NPM URLs not to mess with

- .appveyor.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/560)
> Trivial AppVeyor file changes

- analyzer/src/main/kotlin/managers/PhpComposer.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/562)
> PhpComposer: Generalize the version string check

- analyzer/src/main/kotlin/managers/GoDep.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/563)
> GoDep: Assign to vcsProcessed only once

- analyzer/src/funTest/kotlin/GoDepTest.kt
- analyzer/src/funTest/kotlin/NpmTest.kt
- analyzer/src/funTest/kotlin/SbtTest.kt
See https://github.com/kotlintest/kotlintest/issues/336.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/565)
> Stop using FreeSpec tests as they spordically seem to be skipped

- analyzer/src/funTest/kotlin/BabelTest.kt
- analyzer/src/funTest/kotlin/BundlerTest.kt
- analyzer/src/funTest/kotlin/GradleTest.kt
- analyzer/src/funTest/kotlin/MainTest.kt
- analyzer/src/funTest/kotlin/MavenTest.kt
- analyzer/src/funTest/kotlin/NpmTest.kt
- analyzer/src/funTest/kotlin/PhpComposerTest.kt
- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- downloader/src/funTest/kotlin/CvsDownloadTest.kt
- downloader/src/funTest/kotlin/DownloaderTest.kt
- downloader/src/funTest/kotlin/GitDownloadTest.kt
- downloader/src/funTest/kotlin/MercurialDownloadTest.kt
- downloader/src/funTest/kotlin/SubversionDownloadTest.kt
- scanner/src/funTest/kotlin/ScanPathTest.kt
- utils-test/src/main/kotlin/TestTags.kt
- utils-test/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/567)
> Patch expected result fun

- analyzer/src/funTest/assets/projects/synthetic/php-composer-expected-output.yml
- analyzer/src/main/kotlin/managers/PhpComposer.kt
As agreed on at
https://github.com/heremaps/oss-review-toolkit/pull/170#issuecomment-391286402
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/569)
> PhpComposer: Use the "vendor" part of the name as the namespace

- model/src/main/kotlin/AnalyzerResult.kt
If multiple projects with the same id are found in one run of the analyzer
create an error instead of overwriting the projects in the analyzer result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/561)
> analyzer: Create an error if multiple projects with the same id are found

- analyzer/src/main/kotlin/Main.kt
This is a fixup for c5a39e0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/571)
> analyzer: Fix creation of output directory

- downloader/src/main/kotlin/Main.kt
- model/src/main/kotlin/OutputFormat.kt
- reporter/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/576)
> Enum improvements

- downloader/src/main/kotlin/vcs/GitRepo.kt
- scanner/src/main/kotlin/ScanResultsCache.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/578)
> Minor fixes

- scanner/src/funTest/kotlin/ScanPathTest.kt
- scanner/src/funTest/kotlin/scanners/ScanPathTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/FileCounter.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/test/kotlin/ScanCodeTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/579)
> Remove scanner result

- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
Patch level upgrades should not break compatibility, so allow changes in
this part of the versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/581)
> analyzer: Relax version checks for package managers

- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/588)
> Limit filename length

- model/src/main/kotlin/AnalyzerResult.kt
Compare paths to paths, and swap the order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/587)
> AnalyzerResult: Fix the message about duplicates

- reporter/src/main/kotlin/reporters/TableReporter.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/590)
> TableReporter: Minor code simplifications by using flatMap()

- build.gradle
In particular, this fixes
https://github.com/arturbosch/detekt/issues/807.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/591)
> Gradle: Upgrade detekt to version 1.0.0.RC7-2

- reporter/src/main/kotlin/reporters/ExcelReporter.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/593)
> ExcelReporter: Fix the implementation of joinWithLimit()

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- analyzer/src/main/kotlin/managers/PIP.kt
- downloader/src/funTest/kotlin/GitRepoDownloadTest.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- model/src/main/kotlin/AnalyzerResult.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/596)
> Various GitRepo and path-related changes

- scanner/src/funTest/assets/analyzer-result.yml
- scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
- scanner/src/funTest/kotlin/scanners/FileCounterTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/600)
> File counter test fixes

- downloader/src/main/kotlin/VersionControlSystem.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/602)
> VersionControlSystem: Cache results of forUrl() to speed things up

- analyzer/src/funTest/kotlin/integration/GradleIntegrationTest.kt
- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- downloader/src/funTest/kotlin/CvsDownloadTest.kt
- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- model/src/main/kotlin/AnalyzerResult.kt
- model/src/main/kotlin/HashAlgorithm.kt
- model/src/main/kotlin/Identifier.kt
- model/src/main/kotlin/Scope.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
- scanner/src/main/kotlin/Main.kt
- utils/src/main/kotlin/OS.kt
- utils/src/main/kotlin/Utils.kt
Using "in" is shorter. Also this increases consistency because "in" is
already used in several places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/604)
> Replace calls of "contains" with "in" operator

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/611)
> Travis: Install git-repo for the GitRepoDownloadTest

- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- reporter/src/test/kotlin/reporters/ExcelReporterTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/612)
> Excel create sheet

- .appveyor.yml
Install the Android SDK on AppVeyor and enable the Android tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/610)
> Appveyor android

- .appveyor.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/614)
> Appveyor trivial

- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- utils/src/main/kotlin/SpdxUtils.kt
Inspired by
https://github.com/benbalter/licensee/blob/0d87ecc0f59189a670597d001641abf775433362/docs/what-we-look-at.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/615)
> Introduce a shared list of common license file names

- model/src/main/kotlin/ScanResult.kt
- model/src/main/kotlin/ScanResultContainer.kt
- utils/src/main/kotlin/SpdxUtils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/617)
> Doc improvements

- analyzer/src/main/kotlin/MavenSupport.kt
If a ProjectBuildingException occurs during building a project often the
project was partially built and is contained in the exception. Try to
continue in this case because the problems are often caused by build
extensions which might not be required for the dependency analysis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/618)
> analyzer: Continue if a Maven project could partially be built

- analyzer/src/main/kotlin/MavenSupport.kt
Similar to 5c7d98e continue if a ProjectBuildingException occurs while
building a project from a POM file, if the exception contains a
ProjectBuildingResult.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/622)
> analyzer: Also try to continue if building a Maven project from file fails

- analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/PhpComposer.kt
- model/src/main/kotlin/VcsInfo.kt
- scanner/src/main/kotlin/ScanResultsCache.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- utils/src/main/kotlin/SpdxUtils.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/626)
> Bundler homepage null

- analyzer/src/main/kotlin/Main.kt
- downloader/src/funTest/kotlin/GitRepoDownloadTest.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/627)
> Fixes for a VCS info regression for git-repo

- analyzer/src/main/kotlin/managers/Unmanaged.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/630)
> Fix VCS information for unmanaged projects, and GitRepo in particular

- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/631)
> utils: Properly normalize GitHub URLs without a protocol

- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/PhpComposer.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/635)
> NPE fixes for PIP and PhpComposer

- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/PIP.kt
There were a few missing cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/636)
> analyzer: Explain why "allowDynamicVersions" is sometimes hard-coded

- docs/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/637)
> Minor README improvements

- scanner/src/main/kotlin/scanners/Licensee.kt
See https://github.com/benbalter/licensee/releases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/640)
> Licensee: Upgrade the scanner to version 9.9.1

- reporter/src/web-app/js/src/App.js
- reporter/src/web-app/js/src/components/DependencyTable.js
- reporter/src/web-app/js/src/components/LicenseTag.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/641)
> Enable more filters

- reporter/src/web-app/js/package.json
- reporter/src/web-app/js/src/App.js
- reporter/src/web-app/js/src/index.js
- reporter/src/web-app/js/src/store/reducers.js
- reporter/src/web-app/js/src/store/setup.js
- reporter/src/web-app/js/yarn.lock
adding redux state management to have simple state manager
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/629)
> add redux state management

- .appveyor.yml
- .travis.yml
For a better overview.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/647)
> ci: Group installation into sections

- .appveyor.yml
- .gitmodules
- .travis.yml
- analyzer/build.gradle
- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml
- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml
- analyzer/src/funTest/kotlin/StackTest.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- analyzer/src/test/kotlin/PackageManagerTest.kt
- docs/README.md
- gradle.properties
/cc @stevana
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/644)
> Add Haskell support via Stack / Cabal

- .appveyor.yml
- .travis.yml
This bootstraps everything into a sandbox and thus takes a while.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/650)
> ci: Note that "stack setup" installs the whole Glasgow Haskell Compiler

- build.gradle
There is no official change log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/652)
> Gradle: Upgrade to detekt 1.0.0.RC7-3

- downloader/src/main/kotlin/Main.kt
- gradle.properties
- utils/build.gradle
- utils/src/main/kotlin/ArchiveUtils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/651)
> Improvements to the downloader's command line interface

- reporter/src/web-app/js/.eslintrc.json
- reporter/src/web-app/js/package.json
- reporter/src/web-app/js/src/App.js
- reporter/src/web-app/js/src/components/TreeView.js
- reporter/src/web-app/js/src/index.css
- reporter/src/web-app/js/src/store/reducers.js
- reporter/src/web-app/js/src/store/setup.js
- reporter/src/web-app/js/src/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/654)
> eslint and Tree view

- analyzer/src/main/kotlin/managers/PIP.kt
- downloader/src/test/kotlin/GitTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/655)
> Pipdeptree

- analyzer/build.gradle
- analyzer/src/main/kotlin/MavenSupport.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/653)
> Maven wagon support

- model/src/main/kotlin/Project.kt
This is a fixup for 0ce9c2e.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/656)
> Project: Ignore "aliases" from old data for backwards compatibility

- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- model/src/main/kotlin/OutputFormat.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
- scanner/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/658)
> Miscellaneous changes related to file format handling

- utils/src/main/kotlin/ProcessCapture.kt
Keeping the temporary files does not help if running ORT inside a
Docker container that is run with cleanup enabled. So instead log the
first lines as defined by DEBUG_LINES of both stdout and stderr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/659)
> ProcessCapture: Log stdout and stderr directly when debugging

- model/src/main/kotlin/Identifier.kt
/cc @zenogantner
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/660)
> Identifier: Sanitize against e.g. multi-line strings

- analyzer/src/main/kotlin/managers/Stack.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/661)
> Stack: Add some debug output

- build.gradle
See https://github.com/JetBrains/kotlin/releases/tag/v1.2.51.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/662)
> Gradle: Upgrade to Kotlin 1.2.51

- analyzer/src/main/kotlin/managers/Stack.kt
This is not the case e.g. on our CI. Instead get the project name from
the *.cabal file, which thus needs to be parsed first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/665)
> Stack: Do not rely on the workingDir name to match the project name

- analyzer/src/main/resources/init.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/666)
> init.gradle: Add a comment about "?.find { true }"

- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml
- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml
- analyzer/src/main/kotlin/managers/Stack.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/667)
> Miscellaneous improvements for Haskell / Stack

- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml
- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- analyzer/src/main/kotlin/managers/Unmanaged.kt
- model/src/main/kotlin/AnalyzerResult.kt
- model/src/main/kotlin/Identifier.kt
- model/src/main/kotlin/PackageReference.kt
- model/src/main/kotlin/Project.kt
- model/src/main/kotlin/ProjectAnalyzerResult.kt
- model/src/main/kotlin/Scope.kt
- model/src/main/kotlin/VcsInfo.kt
- model/src/test/kotlin/ProjectTest.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/670)
> More fixes for Haskell / Stack

- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml
- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml
- analyzer/src/funTest/kotlin/StackTest.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- downloader/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/674)
> Cabal parsing

- .codecov.yml
As suggested by Codecov support by email.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/679)
> Help Codecov to map Kotlin classes correctly to paths

- analyzer/src/main/kotlin/managers/Stack.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/683)
> Stack: Strip potential leading garbage from graph output

- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml
- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml
- analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-lockfile.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/php-composer-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/yarn-expected-output.yml
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PhpComposer.kt
- analyzer/src/main/kotlin/managers/Stack.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/680)
> Treat archived sources as source artifacts

- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- analyzer/src/funTest/kotlin/integration/VueJsIntegrationTest.kt
This is a fixup for 49767dd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/676)
> analyzer: Support expected errors in the integration tests

- utils/src/main/kotlin/ProcessCapture.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/682)
> ProcessCapture: Limit long error messages similar to debug logs

- .gitattributes
- detekt.yml
- docs/README.md
- model/src/main/kotlin/LicenseFinding.kt
- model/src/main/kotlin/ScanSummary.kt
- model/src/test/assets/deprecated-scan-results.yml
- model/src/test/kotlin/ScanResultContainerTest.kt
- reporter/src/main/kotlin/Main.kt
- reporter/src/main/kotlin/reporters/NoticeReporter.kt
- reporter/src/test/assets/NPM-is-windows-1.0.2-expected-NOTICE
- reporter/src/test/assets/NPM-is-windows-1.0.2-scan-record.json
- reporter/src/test/kotlin/reporters/NoticeReporterTest.kt
- scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
- scanner/src/funTest/kotlin/HttpCacheTest.kt
- scanner/src/funTest/kotlin/scanners/ScanPathTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/FileCounter.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/test/assets/oss-review-toolkit-license-and-readme_scancode-2.9.2.json
- scanner/src/test/kotlin/ScanCodeTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/594)
> Copyrights for licenses

- .appveyor.yml
- .travis.yml
- downloader/src/funTest/kotlin/GitRepoDownloadTest.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/688)
> Git repo windows

- .appveyor.yml
- analyzer/src/main/kotlin/managers/PhpComposer.kt
- utils/src/main/kotlin/ProcessCapture.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/689)
> Appveyor php composer

- analyzer/src/main/kotlin/managers/PhpComposer.kt
Inline the script constants which were only used in a single place, move
remaining constants as private to the companion object and slightly
rename them for readability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/691)
> PhpComposer: Refactor constants

- docs/README.md
- gradle/wrapper/gradle-wrapper.properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/692)
> Upgrade to Gradle 4.9, explain new application plugin usage

- analyzer/src/funTest/kotlin/PipTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/695)
> PipTest: Port code to use patchExpectedResult()

- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/696)
> Utils: Explain why we cannot use a function expression in showStackTrace()

- analyzer/src/funTest/assets/projects/external/grpc-bundler-expected-output.yml
- analyzer/src/funTest/kotlin/MainTest.kt
- analyzer/src/funTest/kotlin/PhpComposerTest.kt
- analyzer/src/funTest/kotlin/vcs/GitRepoTest.kt
- analyzer/src/main/kotlin/Main.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/PhpComposer.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- analyzer/src/main/kotlin/managers/Unmanaged.kt
- downloader/src/funTest/kotlin/GitRepoDownloadTest.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/GitBase.kt
- scanner/src/main/kotlin/Main.kt
- utils-test/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/697)
> Various GitRepo related improvements

- analyzer/src/main/kotlin/managers/PIP.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/700)
> PIP: Add debug output if requirements.txt restricts the Python version

- downloader/src/main/kotlin/VersionControlSystem.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/702)
> VCS caching

- build.gradle
No changelog available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/703)
> Gradle: Upgrade detekt to 1.0.0.RC8

- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/managers/Maven.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/710)
> Miscellaneous minor Maven-related improvements

- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/resources/META-INF/plexus/components.xml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/713)
> Improvements for handling Maven / SBT projects

- .gitmodules
- analyzer/src/funTest/assets/projects/external/directories-expected-output.yml
- analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
- analyzer/src/funTest/kotlin/SbtTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/715)
> Improve SBT tests

- scanner/src/main/kotlin/LocalScanner.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/720)
> Progress output

- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle/.ort.yml
- analyzer/src/main/kotlin/Analyzer.kt
- downloader/src/main/kotlin/Main.kt
- model/src/main/kotlin/OutputFormat.kt
- model/src/main/kotlin/config/Excludes.kt
- model/src/test/kotlin/ProjectTest.kt
- model/src/test/kotlin/ScanResultContainerTest.kt
- reporter/src/main/kotlin/Main.kt
- reporter/src/test/kotlin/reporters/NoticeReporterTest.kt
- scanner/src/main/kotlin/ArtifactoryCache.kt
- scanner/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/746)
> Parse ort yaml

- downloader/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/Main.kt
Since cbed5b1 if the scanner input file contains multiple projects for the
same repository only one of them was scanned. As a result no scan results
for the other projects from this repository were shown.
To fix this re-use the scan result for all projects from this repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/748)
> scanner: Add results for de-duplicated project packages to result

- analyzer/src/funTest/assets/projects/external/directories-expected-output.yml
- analyzer/src/funTest/assets/projects/external/grpc-bundler-expected-output.yml
- analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- model/src/main/kotlin/AnalyzerResult.kt
- model/src/main/kotlin/ScanRecord.kt
- scanner/src/funTest/assets/analyzer-result.yml
- scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/750)
> Analyzer has errors

- analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-babel/package-lock.json
- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm/node-modules/package-lock.json
- analyzer/src/funTest/assets/projects/synthetic/npm/package-lock/package-lock.json
- analyzer/src/funTest/assets/projects/synthetic/npm/shrinkwrap/npm-shrinkwrap.json
As reported by GitHub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/759)
> analyzer: Upgrade dependencies to account for a lodash security vulnerability

- downloader/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/760)
> Improve consolidate

- analyzer/src/funTest/assets/projects/synthetic/excludes-expected-result.yml
- analyzer/src/funTest/assets/projects/synthetic/excludes-with-remove-expected-result.yml
- analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/.ort.yml
- analyzer/src/main/kotlin/Analyzer.kt
- model/src/main/kotlin/PackageReference.kt
- model/src/main/kotlin/Scope.kt
- model/src/test/kotlin/PackageReferenceTest.kt
Implement exclusion of packages. Please see the commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/758)
> Exclude packages

- model/src/main/kotlin/PackageReference.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/761)
> PackageReference: Apply a trivial formatting fix for imports

- model/src/main/kotlin/AnalyzerResult.kt
- model/src/main/kotlin/PackageReference.kt
- model/src/main/kotlin/ScanRecord.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/762)
> Evaluate errors lazily

- analyzer/src/main/kotlin/managers/NPM.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/766)
> NPM: Add support for Subresource Integrity hashes

- analyzer/src/funTest/assets/projects/synthetic/excludes-expected-result.yml
- analyzer/src/funTest/assets/projects/synthetic/excludes-with-remove-expected-result.yml
- analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/.ort.yml
- analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/gradle/app1/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/gradle/app2/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/maven/broken1/pom.xml
- analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/maven/broken2/pom.xml
- analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/maven/broken3/pom.xml
- analyzer/src/funTest/kotlin/ExcludesTest.kt
- analyzer/src/main/kotlin/Analyzer.kt
- model/src/main/kotlin/Error.kt
- model/src/main/kotlin/Mappers.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/764)
> Exclude errors

- analyzer/src/main/kotlin/Analyzer.kt
- model/src/main/kotlin/AnalyzerResultPostProcessor.kt
- model/src/main/kotlin/ExcludesProcessor.kt
This improves the modularity of the code. Also the refactored
implementation has less duplication and is more readable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/767)
> analyzer: Move excludes logic from Analyzer to separate classes

- analyzer/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/Main.kt
- reporter/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/772)
> Use sets instead of lists where applicable

- scanner/src/funTest/kotlin/scanners/ScanPathTest.kt
- scanner/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/FileCounter.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/main/resources/META-INF/services/com.here.ort.scanner.Scanner
- scanner/src/test/kotlin/ScanCodeTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/780)
> Scanner loader

- scanner/src/funTest/kotlin/scanners/ScanPathTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/ScannerFactory.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/FileCounter.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/main/resources/META-INF/services/com.here.ort.scanner.Scanner
- scanner/src/main/resources/META-INF/services/com.here.ort.scanner.ScannerFactory
- scanner/src/test/kotlin/ScanCodeTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/785)
> Scanner factory

- reporter-web-app/src/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/787)
> reporter-web-app: Add missing spaces to error message

- model/src/main/kotlin/AnalyzerResult.kt
- reporter/src/main/kotlin/reporters/NoticeReporter.kt
- reporter/src/test/assets/npm-test-with-exclude-NOTICE
- reporter/src/test/assets/npm-test-with-exclude-scan-results.yml
- reporter/src/test/assets/npm-test-without-exclude-NOTICE
- reporter/src/test/assets/npm-test-without-exclude-scan-results.yml
- reporter/src/test/kotlin/reporters/NoticeReporterTest.kt
Only collect license notes for packages which are not excluded in the
repository configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/789)
> reporter: Respect excludes in notice reporter

- analyzer/src/main/kotlin/managers/NPM.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/793)
> NPM: Remove an unneeded detekt annotation

- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/Bower.kt
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/CocoaPods.kt
- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/PhpComposer.kt
- analyzer/src/main/kotlin/managers/SBT.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- analyzer/src/main/kotlin/managers/Unmanaged.kt
- analyzer/src/main/kotlin/managers/Yarn.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/794)
> analyzer: Override toString() only once in the PackageManger base class

- reporter-web-app/src/App.css
- reporter-web-app/src/components/PackagesTableErrors.js
- reporter-web-app/src/components/PackagesTablePaths.js
- reporter-web-app/src/components/PackagesTableScanSummary.js
- reporter-web-app/src/components/SummaryView.js
Series of small improvements  for the Reporter WebApp UI. See commits for details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/797)
> Reporter webapp improvements

- analyzer/src/funTest/assets/projects/external/godep-expected-output.yml
- analyzer/src/funTest/assets/projects/external/qmstr-expected-output.yml
- analyzer/src/funTest/assets/projects/external/sprig-expected-output.yml
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PhpComposer.kt
- model/src/main/kotlin/Package.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/795)
> More package manager cleanups

- analyzer/src/funTest/kotlin/GradleTest.kt
- analyzer/src/funTest/kotlin/SbtTest.kt
- analyzer/src/funTest/kotlin/vcs/GitRepoTest.kt
- downloader/src/funTest/kotlin/BeanUtilsTest.kt
- downloader/src/funTest/kotlin/CvsDownloadTest.kt
- downloader/src/funTest/kotlin/GitDownloadTest.kt
- downloader/src/funTest/kotlin/GitRepoDownloadTest.kt
- downloader/src/funTest/kotlin/MercurialDownloadTest.kt
- downloader/src/funTest/kotlin/SubversionDownloadTest.kt
- downloader/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- downloader/src/main/resources/META-INF/services/com.here.ort.downloader.VersionControlSystem
- downloader/src/test/kotlin/CvsTest.kt
- downloader/src/test/kotlin/GitTest.kt
- downloader/src/test/kotlin/MercurialTest.kt
- downloader/src/test/kotlin/SubversionTest.kt
- downloader/src/test/kotlin/VersionControlSystemTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/799)
> downloader: Port Version Control Systems to use ServiceLoader

- utils-test/src/main/kotlin/Utils.kt
- utils/src/main/kotlin/Utils.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/802)
> Utils: Trivially improve the comment for fileSystemEncode()

- build.gradle
These are already inherited from the test configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/803)
> Gradle: Remove duplicate funTest dependencies

- cli/src/main/kotlin/Main.kt
Note the order: If both --info and --debug are specified, --debug takes
precedence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/805)
> Main: Minor code simplification using "when"

- docs/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/807)
> README: Minor wording improvement as we have a single CLI now

- cli/src/funTest/kotlin/MainTest.kt
- cli/src/main/kotlin/Main.kt
- scanner/src/main/kotlin/Scanner.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/810)
> Distinct params

- analyzer/src/main/kotlin/Analyzer.kt
- cli/src/main/kotlin/Main.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/811)
> Ort yml parameter

- .appveyor.yml
- .travis.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-babel/package-lock.json
- analyzer/src/funTest/assets/projects/synthetic/npm/node-modules/package-lock.json
- analyzer/src/funTest/assets/projects/synthetic/npm/package-lock/package-lock.json
- analyzer/src/funTest/assets/projects/synthetic/npm/shrinkwrap/npm-shrinkwrap.json
- analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/npm/package-lock.json
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/Yarn.kt
- docs/GettingStarted.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/813)
> Yarn npm upgrade

- downloader/src/main/kotlin/Downloader.kt
- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
- reporter/src/main/kotlin/reporters/WebAppReporter.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/Scanner.kt
- utils/src/main/kotlin/ProcessCapture.kt
Libraries should not write unasked to the application's stdout. So
convert all remaining print(ln) statements in libarary code to log
statements that can be controlled by the application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/816)
> Do not write to stdout in libraries

- reporter/src/main/kotlin/reporters/NoticeReporter.kt
- utils/src/main/kotlin/SpdxUtils.kt
- utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/820)
> Spdx handle exceptions

- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/819)
> Improve artifact handling for local Maven projects

- analyzer/src/main/kotlin/Analyzer.kt
- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/SBT.kt
- cli/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/GitBase.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- model/src/main/kotlin/ExcludesProcessor.kt
- model/src/main/kotlin/Project.kt
- model/src/main/kotlin/ProjectAnalyzerResult.kt
- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
- scanner/src/main/kotlin/ArtifactoryCache.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/822)
> Misc cleanups

- reporter/src/main/kotlin/reporters/NoticeReporter.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/823)
> NoticeReporter: Align logging and variable naming with other reporters

- analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
This is a follow-up to 1e03907 as one more URL started to change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/827)
> analyzer: Update expected results with http URLs

- analyzer/src/main/kotlin/PackageManager.kt
- cli/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- reporter/src/main/kotlin/Reporter.kt
- reporter/src/main/kotlin/reporters/NoticeReporter.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
- reporter/src/main/kotlin/reporters/WebAppReporter.kt
- reporter/src/main/resources/META-INF/services/com.here.ort.reporter.Reporter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/828)
> Migrate reporter to use Service Loader

- reporter-web-app/config/webpack.config.dev.js
- reporter-web-app/config/webpack.config.prod.js
- reporter-web-app/src/components/SummaryView.js
- reporter-web-app/src/utils.js
As reported by eslint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/834)
> reporter-web-app: Trim trailing whitespace in JavaScript code

- analyzer/src/main/kotlin/MavenSupport.kt
- utils/src/main/kotlin/DiskCache.kt
Most importantly fixing broken disk cache size and doing several renames
to prevent analog problems and keep naming consistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/840)
> Diskcache fixes

- reporter-web-app/.eslintrc.json
- reporter-web-app/src/utils.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/835)
> Address some eslint issues in the web-app

- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/SBT.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- downloader/src/funTest/kotlin/CvsDownloadTest.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitBase.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- utils/src/main/kotlin/ProcessCapture.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/844)
> ProcessCapture-related cleanups

- downloader/src/main/kotlin/vcs/Subversion.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/847)
> Subversion: Minor code simplification

- utils/src/main/kotlin/Utils.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/849)
> Utils: Sort (extension) functions alphabetically

- analyzer/src/main/kotlin/managers/Maven.kt
- model/src/main/kotlin/AnalyzerResult.kt
- model/src/main/kotlin/OutputFormat.kt
- utils/src/main/kotlin/ArchiveUtils.kt
- utils/src/main/kotlin/ProcessCapture.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/850)
> Minor code simplifications

- .appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/853)
> AppVeyor: Simplify the installation of GoDep

- model/src/main/kotlin/config/ProjectExclude.kt
The @JsonInclude annotations were in the wrong place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/854)
> model: Fix formatting of ProjectExclude

- .appveyor.yml
- .travis.yml
- analyzer/src/funTest/assets/projects/synthetic/bower-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/bower/bower.json
- analyzer/src/funTest/kotlin/BowerTest.kt
- analyzer/src/funTest/kotlin/integration/PolymerIntegrationTest.kt
- analyzer/src/main/kotlin/managers/Bower.kt
- analyzer/src/main/resources/META-INF/services/com.here.ort.analyzer.PackageManagerFactory
- analyzer/src/test/kotlin/PackageManagerTest.kt
- utils/src/main/kotlin/Utils.kt
Resolving Bower dependencies involves the following steps:
- move `bower_components` folder to temp location if it exists
- install bower dependencies with `bower install`
- parse dependencies from `bower list --json` (for each level of
dependencies, value of `dependencies` key provide details of dependant
packages, that again hold details for it's own dependencies)
- remove `bower_components` that was created with `bower install`
- restore original `bower_components` from temporary folder (if exists)
Resolves #89.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/282)
> Analyzer: Implement support for the Bower package manager

- analyzer/src/main/resources/init.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/859)
> Handle Gradle version objects

- docs/GettingStarted.md
- docs/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/858)
> Miscellaneous follow-up improvements to adding Bower support

- .mailmap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/860)
> mailmap: Add mail addresses for Frank Viernau

- analyzer/src/main/kotlin/managers/SBT.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/863)
> SBT: Add more logging to debug empty analyzer results

- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- reporter/src/main/kotlin/reporters/NoticeReporter.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/864)
> Rewrite error summary

- analyzer/src/main/kotlin/managers/SBT.kt
- utils/src/test/kotlin/UtilsTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/866)
> UtilsTest: Add tests for redirecting output

- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/PhpComposer.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
- scanner/src/main/kotlin/LocalScanner.kt
- utils/src/main/kotlin/DiskCache.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/868)
> Make exception handling more consistent

- model/src/main/kotlin/config/Excludes.kt
- model/src/main/kotlin/config/ProjectExclude.kt
- model/src/main/kotlin/config/ScopeExclude.kt
- model/src/test/kotlin/config/ExcludesTest.kt
- model/src/test/kotlin/config/RepositoryConfigurationTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/873)
> Allow to exclude scopes using a regex

- build.gradle
- docs/README.md
- gradle.properties
- settings.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/881)
> Upgrade detekt to get proper UP-TO-DATE checks in Gradle

- model/src/main/kotlin/config/Excludes.kt
- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
Visualize excluded projects and scopes in the Excel report. See the commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/883)
> Show excludes in Excel report

- reporter/src/main/kotlin/reporters/ExcelReporter.kt
Move the `java.*` imports to the right location.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/884)
> ExcelReporter: Order imports alphabetically

- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- downloader/src/main/kotlin/Downloader.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/WorkingTree.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitBase.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- downloader/src/main/kotlin/vcs/GitWorkingTree.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- downloader/src/test/kotlin/CvsTest.kt
- downloader/src/test/kotlin/GitTest.kt
- downloader/src/test/kotlin/MercurialTest.kt
- downloader/src/test/kotlin/SubversionTest.kt
Minor non-functional changes in order to make it a bit easier working with the code as preparation for the JGit implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/879)
> Vcs minor clean ups

- analyzer/src/main/kotlin/managers/NPM.kt
If `npm install` creates a lock file that did not exist before, delete it
afterwards to not pollute the working directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/886)
> analyzer: Remove generated NPM lock files if they did not exist before

- gradle.properties
See https://arturbosch.github.io/detekt/changelog.html#rc92. In
particular this fixes https://github.com/arturbosch/detekt/issues/1141.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/890)
> Gradle: Upgrade to detekt 1.0.0.RC9.2

- analyzer/src/funTest/kotlin/integration/DrupalIntegrationTest.kt
- analyzer/src/funTest/kotlin/integration/PolymerIntegrationTest.kt
- analyzer/src/funTest/kotlin/integration/VueJsIntegrationTest.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/CocoaPods.kt
- analyzer/src/main/kotlin/managers/SBT.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/894)
> Integration test fixes and related improvements

- docs/Configuration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/898)
> docs: Fix escaping in a Regex configuration example

- downloader/src/main/kotlin/Downloader.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/test/kotlin/ExtensionsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/899)
> Fall back to stripping any user name from VCS URLs

- gradle.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/900)
> Gradle: Upgrade Kotlin to version 1.2.71

- downloader/src/main/kotlin/Downloader.kt
This is a fixup for ccd8256.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/902)
> Downloader: Fix logging the detected VCS type

- analyzer/src/main/kotlin/managers/Bower.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/912)
> Bower: Fix a minor typo in a variable name

- model/src/main/kotlin/Environment.kt
- scanner/src/main/kotlin/LocalScanner.kt
- utils/src/main/kotlin/OS.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/909)
> Fix some minor issues when directly scanning paths

- analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/915)
> StaticHtmlReporter: Display the number of errors in the errors summary title

- reporter/src/main/kotlin/reporters/ExcelReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/916)
> Improve accouting for the Excel cell length limit

- reporter-web-app/package.json
- reporter-web-app/src/App.css
- reporter-web-app/src/App.js
- reporter-web-app/src/components/LicenseChart.js
- reporter-web-app/src/components/LicenseSummaryCard.js
- reporter-web-app/src/components/LicenseTag.js
- reporter-web-app/src/components/PackagesTable.js
- reporter-web-app/src/components/PackagesTableDetails.js
- reporter-web-app/src/components/PackagesTableErrors.js
- reporter-web-app/src/components/PackagesTablePaths.js
- reporter-web-app/src/components/PackagesTableScanSummary.js
- reporter-web-app/src/components/SummaryView.js
- reporter-web-app/src/components/TableView.js
- reporter-web-app/src/components/TreeView.js
- reporter-web-app/src/config.js
- reporter-web-app/src/data/choosealicense/index.js
- reporter-web-app/src/data/licenses.js
- reporter-web-app/src/store/reducers.js
See individual commit message for details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/893)
> Reporter web app fixes

- reporter/src/funTest/kotlin/ReporterTest.kt
- reporter/src/main/kotlin/reporters/ExcelReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/918)
> Properly handle limiting of uninitialized RichTextStrings

- analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
- analyzer/src/main/kotlin/managers/NPM.kt
- cli/src/main/kotlin/Main.kt
- downloader/src/main/kotlin/Downloader.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/903)
> Misc minor fixes

- downloader/src/main/kotlin/Downloader.kt
- scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
If no VCS URL was defined, show a hint how to define it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/917)
> downloader: Add hints to the error message if no VCS URL was found

- README.md
- cli/src/main/kotlin/commands/RequirementsCommand.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/926)
> Requirements improvements

- analyzer/src/main/kotlin/Analyzer.kt
- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/YamlFilePackageCurationProvider.kt
- build.gradle
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- downloader/build.gradle
- downloader/src/main/kotlin/vcs/Subversion.kt
- model/src/main/kotlin/OutputFormat.kt
- model/src/test/kotlin/AnalyzerResultTest.kt
- model/src/test/kotlin/ProjectTest.kt
- model/src/test/kotlin/ScanResultContainerTest.kt
- model/src/test/kotlin/VcsInfoTest.kt
- model/src/test/kotlin/config/ArtifactoryCacheConfigurationTest.kt
- model/src/test/kotlin/config/RepositoryConfigurationTest.kt
- reporter/src/funTest/kotlin/ReporterTest.kt
- reporter/src/test/kotlin/reporters/NoticeReporterTest.kt
- scanner/src/main/kotlin/ArtifactoryCache.kt
- scanner/src/main/kotlin/Scanner.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/928)
> Improve type handling in usage of Jackson

- downloader/src/main/kotlin/WorkingTree.kt
Add a hint explaining how to fix the respective error
to each of the two touched cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/930)
> WorkingTree: Improve revision guessing failure messages

- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- docs/GettingStarted.md
- scanner/src/funTest/kotlin/scanners/FileCounterTest.kt
- scanner/src/main/kotlin/Scanner.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/931)
> Result file wording

- analyzer/src/main/kotlin/managers/NPM.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/test/kotlin/ExtensionsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/932)
> Add some basic support for tarball URLs as the NPM version

- analyzer/src/main/kotlin/MavenLogger.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- model/src/main/kotlin/AnalyzerResult.kt
- model/src/main/kotlin/Project.kt
- model/src/main/kotlin/Scope.kt
- model/src/main/kotlin/config/Excludes.kt
- scanner/src/main/kotlin/ScanResultsCache.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- utils/src/main/kotlin/Extensions.kt
If a single expression function does not fit in one line, the body should
be moved to the next line, see:
https://kotlinlang.org/docs/reference/coding-conventions.html#expression-body-formatting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/936)
> Align single expression functions with Kotlin coding conventions

- model/src/main/kotlin/AnalyzerResult.kt
- model/src/main/kotlin/config/Excludes.kt
- model/src/test/kotlin/config/ExcludesTest.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/933)
> Improve tests for `Excludes`

- model/src/main/kotlin/AnalyzerResult.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/944)
> AnalyzerResult: Correct the class documentation

- analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-version-urls/package.json
- analyzer/src/funTest/kotlin/NpmVersionUrlTest.kt
- analyzer/src/main/kotlin/managers/NPM.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/938)
> NPM version URLs

- model/src/main/kotlin/AnalyzerResult.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/946)
> AnalyzerResult: Improve the class documentation for "errors"

- .travis.yml
- analyzer/src/funTest/kotlin/NpmVersionUrlTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/948)
> Fix calling scripts in Travis

- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/945)
> TableReporter: Apply some minor code simplifications

- analyzer/src/main/kotlin/managers/SBT.kt
- analyzer/src/main/kotlin/managers/Yarn.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/953)
> Yarn cleanup

- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/test/kotlin/NpmTest.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/test/kotlin/VersionControlSystemTest.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/954)
> Support NPM source Git URLs

- analyzer/src/main/kotlin/Analyzer.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/SBT.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/952)
> Take mapping of definition files earlier into account

- analyzer/src/main/kotlin/MavenSupport.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/956)
> MavenSupport: Add a code comment with a link to the Maven SCM tag spec

- analyzer/src/main/kotlin/MavenSupport.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/957)
> MavenSupport: Log a message for invalid SCM URLs

- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/test/kotlin/MavenSupportTest.kt
- analyzer/src/test/kotlin/NpmTest.kt
- analyzer/src/test/kotlin/PackageManagerTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/958)
> Implement parsing git-repo URLs from POMs

- analyzer/src/main/kotlin/MavenSupport.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/959)
> MavenSupport: Minor improvements to filtering out local repos

- analyzer/src/main/kotlin/Analyzer.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/RequirementsCommand.kt
- model/src/main/kotlin/config/ErrorResolution.kt
- model/src/main/kotlin/config/ErrorResolutionReason.kt
- model/src/main/kotlin/config/RepositoryConfiguration.kt
- model/src/main/kotlin/config/Resolutions.kt
- model/src/test/kotlin/config/RepositoryConfigurationTest.kt
- reporter/src/funTest/kotlin/ReporterTest.kt
- reporter/src/main/kotlin/DefaultResolutionProvider.kt
- reporter/src/main/kotlin/Reporter.kt
- reporter/src/main/kotlin/ResolutionProvider.kt
- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- reporter/src/main/kotlin/reporters/NoticeReporter.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
- reporter/src/main/kotlin/reporters/WebAppReporter.kt
- reporter/src/test/kotlin/reporters/NoticeReporterTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- utils-test/src/main/kotlin/Utils.kt
Introduce error resolutions, a way to suppress errors by explaining why they can be ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/951)
> Error resolutions

- reporter/src/main/kotlin/reporters/TableReporter.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/961)
> TableReporter: Only print "Resolved by" if there is a resolution

- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/Yarn.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/960)
> Add support for Yarn workspaces

- docs/GettingStarted.md
So far we had this information only in "README.md".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/965)
> GettingStarted: Say also here to clone recursively

- analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml
- analyzer/src/main/kotlin/MavenSupport.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/968)
> Fix parsing SVN tags from Maven POMs

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/970)
> PipTest: Update the expected results

- cli/src/main/kotlin/commands/ReporterCommand.kt
- reporter/src/main/kotlin/Reporter.kt
- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- reporter/src/main/kotlin/reporters/NoticeReporter.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
- reporter/src/main/kotlin/reporters/WebAppReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/966)
> Print paths of generated reports

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/975)
> Update expected test results

- analyzer/src/main/kotlin/Analyzer.kt
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- build.gradle
- gradle.properties
- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- scanner/src/main/kotlin/LocalScanner.kt
- utils/src/main/kotlin/CommandLineTool.kt
- utils/src/main/kotlin/ProcessCapture.kt
- utils/src/main/kotlin/Utils.kt
See https://blog.jetbrains.com/kotlin/2018/10/kotlin-1-3/.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/977)
> Gradle: Upgrade to Kotlin 1.3

- downloader/src/main/kotlin/Downloader.kt
- utils/src/main/kotlin/ArchiveUtils.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/979)
> Apply some trivial improvements to "when" clauses

- analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/983)
> PipTest: Update expected results for spdx-tools

- scanner/src/main/kotlin/scanners/Askalono.kt
See https://github.com/amzn/askalono/releases/tag/0.3.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/981)
> Askalono: Upgrade to version 0.3.0

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/980)
> Gradle: Remove some unnecessary curly braces

- scanner/src/main/kotlin/scanners/Licensee.kt
See https://github.com/benbalter/licensee/releases/tag/v9.10.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/982)
> Licensee: Upgrade to version 9.10.1

- cli/src/main/kotlin/commands/ScannerCommand.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/987)
> Fix setting scanner

- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- utils/src/main/kotlin/ArchiveUtils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/991)
> Properly set executable bits when untar-ing ScanCode

- cli/src/main/kotlin/commands/DownloaderCommand.kt
This was still taking an AnalyzerResult. Closes #998.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/999)
> cli: Fix the DownloaderCommand to take an OrtResult

- gradle.properties
See https://arturbosch.github.io/detekt/changelog.html#rc10.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/996)
> Gradle: Upgrade detekt to version 1.0.0-RC10

- cli/build.gradle
- cli/src/main/kotlin/CommandWithHelp.kt
- cli/src/main/kotlin/Main.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/RequirementsCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- cli/src/main/resources/META-INF/services/javax.script.ScriptEngineFactory
- cli/src/main/resources/rules/no_gpl_declared.kts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1000)
> Add a proof-of-concept for an evaluator sub-command

- analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1005)
> analyzer: Update expected results for `NpmVersionUrlTest`

- analyzer/src/funTest/assets/projects/external/directories-expected-output.yml
- analyzer/src/funTest/assets/projects/external/grpc-bundler-expected-output.yml
- analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- cli/src/main/resources/rules/no_gpl_declared.kts
- model/src/main/kotlin/EvaluatorRun.kt
- model/src/main/kotlin/OrtResult.kt
- reporter/src/test/assets/npm-test-with-exclude-scan-results.yml
- reporter/src/test/assets/npm-test-without-exclude-scan-results.yml
- scanner/src/funTest/assets/analyzer-result.yml
- scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1006)
>  Allow the evaluator to add its results to an ORT file 

- .appveyor.yml
- .travis.yml
- analyzer/src/main/kotlin/managers/Yarn.kt
- reporter-web-app/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1009)
> Yarn: Upgrade to version 1.12.1

- cli/src/main/resources/rules/no_gpl_declared.kts
By using a destructing declaration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1012)
> no_gpl_declared: Further simplify the rule a bit

- analyzer/src/main/kotlin/managers/PackageJsonUtil.kt
- analyzer/src/test/kotlin/PackageJsonUtilTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1007)
> PackageJsonUtil cleanup

- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- model/src/main/kotlin/OrtResult.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1014)
> Evaluator syntax check

- CONTRIBUTING.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1016)
> CONTRIBUTING: Remove the mention of the CLA and replace it with the DCO

- scanner/src/funTest/kotlin/HttpCacheTest.kt
Just clear the map of requests between tests. This should help to reduce
the test time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1020)
> HttpCacheTest: Use a single HttpServer for all tests

- gradle.properties
See https://github.com/JetBrains/kotlin/releases/tag/v1.3.10.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1023)
> Upgrade to Kotlin 1.3.10

- downloader/src/main/kotlin/Downloader.kt
E.g. for some Android SDK components the source artifact URL actually
points to a file in the local Android / Google Maven repository. Support
"downloading" files from such locations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1025)
> Downloader: Support file:// URLs for source artifacts

- utils/build.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1026)
> utils: Also exclude the deprecated kotlin-stdlib from slf4k

- analyzer/src/main/kotlin/MavenSupport.kt
- downloader/src/main/kotlin/Downloader.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1027)
> Relax file URI checks and require only a single slash

- gradle.properties
See https://arturbosch.github.io/detekt/changelog.html#rc11.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1028)
> Gradle: Upgrade detekt to version 1.0.0-RC11

- model/src/main/kotlin/OrtResult.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1033)
> OrtResult: Add functions to get all declared / detected licenses

- cli/src/main/kotlin/commands/EvaluatorCommand.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1034)
> Minor fixes for evaluator

- reporter-web-app/public/index.html
- reporter-web-app/src/utils.js
- reporter/src/main/kotlin/reporters/TableReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1037)
> TableReporter: Account for renamed meta data fields

- model/src/main/kotlin/OrtResult.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1040)
> OrtResult: Allow to omit excluded projects / packages from collections

- cli/src/main/kotlin/commands/ReporterCommand.kt
- reporter/build.gradle
- reporter/src/main/kotlin/Reporter.kt
- reporter/src/main/kotlin/reporters/AbstractNoticeReporter.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
- reporter/src/main/kotlin/reporters/WebAppReporter.kt
- reporter/src/main/resources/META-INF/services/javax.script.ScriptEngineFactory
- reporter/src/test/assets/post-processed-NOTICE
- reporter/src/test/kotlin/reporters/NoticeReporterTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1047)
> Notice reporter post processor

- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1048)
> utils: Add a helper function to check for more than two disjoint collections

- utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1053)
> UtilsTest: Add a test for filterVersionNames() and SHA1 suffixes

- utils/src/test/kotlin/RedirectionTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1057)
> Redirection testing

- model/src/main/kotlin/PackageReference.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1056)
> PackageReference: Apply a minor code simplification

- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/test/kotlin/ExtensionsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1059)
> Fix hyperlinks in Excel report

- model/src/main/kotlin/LicenseFinding.kt
- model/src/main/kotlin/ScanSummary.kt
- reporter/src/main/kotlin/reporters/AbstractNoticeReporter.kt
- reporter/src/main/kotlin/reporters/NoticeOnlyDeclaredReporter.kt
- reporter/src/main/kotlin/reporters/NoticeReporter.kt
- reporter/src/test/kotlin/reporters/NoticeReporterTest.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1061)
> License findings fun

- model/src/main/kotlin/Scope.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1065)
> Minor Scope class fixups

- model/src/main/kotlin/config/Excludes.kt
- reporter/src/main/kotlin/reporters/NoticeOnlyDeclaredReporter.kt
- reporter/src/main/kotlin/reporters/NoticeReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1066)
> Notice reporter project excludes

- model/src/main/kotlin/PackageReference.kt
- model/src/main/kotlin/Project.kt
- model/src/main/kotlin/ProjectAnalyzerResult.kt
- model/src/main/kotlin/Scope.kt
- model/src/test/kotlin/ProjectTest.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1067)
> Refactor collecting of dependencies to be more flexbile

- model/src/main/kotlin/Identifier.kt
- model/src/main/kotlin/OrtResult.kt
- model/src/main/kotlin/PackageReference.kt
- model/src/main/kotlin/Project.kt
- model/src/main/kotlin/Scope.kt
- model/src/test/kotlin/OrtResultTest.kt
- model/src/test/kotlin/PackageReferenceTest.kt
- scanner/src/main/kotlin/Scanner.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1068)
> Clean-ups and addition of more utility functions for scripting

- gradle/wrapper/gradle-wrapper.properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1071)
> Gradle: Upgrade to version 5.0

- model/src/test/kotlin/OrtResultTest.kt
- model/src/test/kotlin/PackageReferenceTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1070)
> Improvements to recent changes regarding references

- model/src/main/kotlin/Mappers.kt
- model/src/main/kotlin/OrtIssue.kt
see individual commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1074)
> Ort issue name realign

- README.md
In particular, say how to fix an existing non-recursive clone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1076)
> README: Improve the cloning instructions

- analyzer/src/funTest/kotlin/BundlerTest.kt
- analyzer/src/funTest/kotlin/GoDepTest.kt
- analyzer/src/funTest/kotlin/PhpComposerTest.kt
- analyzer/src/funTest/kotlin/integration/VueJsIntegrationTest.kt
- model/src/main/kotlin/Identifier.kt
- model/src/main/kotlin/Mappers.kt
- model/src/test/kotlin/IdentifierTest.kt
- model/src/test/kotlin/OrtResultTest.kt
- model/src/test/kotlin/PackageReferenceTest.kt
- model/src/test/kotlin/ProjectAnalyzerResultTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1077)
> Identifier secondary constructor

- build.gradle
- gradle.properties
- model/build.gradle
By calling the :model:generateGrammarSource task after the IDE's sync
with the Gradle model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1082)
> Gradle: Fix compiling a fresh clone in IntelliJ

- cli/src/main/kotlin/commands/RequirementsCommand.kt
- utils/src/main/kotlin/CommandLineTool.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1083)
> Introduce the ANY_VERSION convenience requirement property

- model/src/main/kotlin/spdx/SpdxExpression.kt
- model/src/test/kotlin/spdx/SpdxExpressionParserTest.kt
- model/src/test/kotlin/spdx/SpdxExpressionTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1081)
> Spdx expression serialization

- analyzer/src/funTest/assets/projects/synthetic/bower-expected-output.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1086)
> bower-expected-output: Upgrade the shadycss dependency to version 1.7.0

- .travis.yml
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1087)
> Travis: Make MercurialTest pass again

- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- reporter/src/main/kotlin/reporters/ReportTableModel.kt
- reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
- reporter/src/main/kotlin/reporters/TableReporter.kt
Those are mainly preparations for further refactoring of the table reporter and addition of a new feature.
Please see individual commit messages for the details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1079)
> Refactor table reporter

- model/src/main/kotlin/config/ScannerConfiguration.kt
- scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/test/kotlin/ScanCodeTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1089)
> Scanner configuration

- .codecov.yml
- .travis.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1096)
> Upload coverage data only for cron builds

- model/src/main/kotlin/Provenance.kt
- scanner/src/main/kotlin/ArtifactoryCache.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1094)
> Compare provenance by source artifact hash

- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/PhpComposer.kt
- model/src/main/kotlin/HashAlgorithm.kt
- model/src/test/assets/expected-scan-results.yml
- model/src/test/kotlin/PackageTest.kt
- model/src/test/kotlin/ScanResultContainerTest.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/test/kotlin/ExtensionsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1098)
> Hash from string

- analyzer/src/main/kotlin/managers/SBT.kt
- utils/src/main/kotlin/Redirection.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1100)
> Sbt suppress input

- gradle.properties
See https://github.com/JetBrains/kotlin/releases/tag/v1.3.11.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1102)
> Gradle: Upgrade to Kotlin 1.3.11

- reporter/src/funTest/assets/NPM-is-windows-1.0.2-expected-NOTICE_UNPROCESSED
- reporter/src/funTest/kotlin/reporters/NoticeReporterTest.kt
- reporter/src/main/kotlin/reporters/AbstractNoticeReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1097)
> NoticeReporter: Do not clean up copyrights if post processing script is available

- build.gradle
- gradle.properties
See https://arturbosch.github.io/detekt/changelog.html#rc12.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1106)
> Gradle: Upgrade detekt to version 1.0.0-RC12

- evaluator/src/main/kotlin/Evaluator.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1108)
> evaluator: Add more wildcard imports for scripting convenience

- .appveyor.yml
- .travis.yml
- analyzer/src/funTest/kotlin/StackTest.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- utils/src/main/kotlin/CI.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1109)
> Only install Haskell Stack if we really need it (for running tests)

- model/src/main/kotlin/OrtIssue.kt
- model/src/main/kotlin/Severity.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1112)
> OrtIssue severity

- reporter/src/funTest/assets/file-counter-expected-scan-report.html
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1115)
> Improve html report

- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- reporter/src/main/kotlin/reporters/ReportTableModel.kt
And update the docs for `ExcelReporter`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1117)
> reporter: Add some missing imports for KDoc

- reporter/src/funTest/assets/file-counter-expected-scan-report.html
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
See individual commit message for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1119)
> Static HTML report: some more improvements

- scanner/src/main/kotlin/scanners/ScanCode.kt
> ScanCode: Fix a typo in the version number in a comment

- cli/build.gradle
- cli/docker/Dockerfile
- gradle.properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1123)
> Add code to create a Docker image based on Debian for running ORT

- model/src/main/kotlin/config/Resolutions.kt
- model/src/main/kotlin/config/RuleViolationResolution.kt
- model/src/main/kotlin/config/RuleViolationResolutionReason.kt
- model/src/test/kotlin/config/RepositoryConfigurationTest.kt
- reporter/src/funTest/assets/file-counter-expected-scan-report.html
- reporter/src/main/kotlin/DefaultResolutionProvider.kt
- reporter/src/main/kotlin/ResolutionProvider.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1124)
> Rename evaluator error

- model/src/main/kotlin/OrtResult.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1126)
> OrtResult: Add functions to get the concluded licenses of packages

- reporter-web-app/build.gradle
- reporter/build.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1128)
> Fix reporter tasks

- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- model/src/main/kotlin/OrtResult.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1129)
> Misc. fixups

- model/src/main/kotlin/OrtResult.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1134)
> OrtResult: Mark yet another scripting function as not unused

- reporter/src/funTest/assets/file-counter-expected-scan-report.html
- reporter/src/main/kotlin/reporters/ReportTableModel.kt
- reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1145)
> Merge License Columns

- .gitattributes
- reporter/src/funTest/assets/NPM-is-windows-1.0.2-expected-NOTICE
- reporter/src/funTest/assets/NPM-is-windows-1.0.2-expected-NOTICE_UNPROCESSED
- reporter/src/funTest/assets/post-processed-expected-NOTICE
- reporter/src/main/kotlin/reporters/NoticeReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1151)
> No trim license texts

- reporter/src/funTest/kotlin/reporters/StaticHtmlReporterTest.kt
Some code style improvements, see individual commits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1157)
> Static html reporter test minor improvements

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1160)
> CONTRIBUTING.md: Fix some minor issues

- reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
- reporter/src/funTest/assets/static-html-reporter-test-input.yml
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1164)
> Static html reporter fix section name

- reporter-web-app/package.json
- reporter-web-app/yarn.lock
See https://nvd.nist.gov/vuln/detail/CVE-2018-14732.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1167)
> reporter-web-app: Upgrade webpack-dev-server to address a vulnerability

- model/src/main/kotlin/OrtIssue.kt
- reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1165)
> OrtIssue fixups

- analyzer/src/funTest/assets/projects/synthetic/bower-expected-output.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1172)
> analyzer: Update expected BowerTest dependencies

- docs/Configuration.md
- model/src/main/kotlin/config/RuleViolationResolutionReason.kt
- model/src/test/kotlin/config/RepositoryConfigurationTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1171)
> Extend rule violation resolution reason

- reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
Undo the accidental change done by 3026cca4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1182)
> StaticHtmlReporter: Fix-up a CSS class reference

- .travis.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1192)
> Docker cron

- analyzer/build.gradle
- build.gradle
- cli/build.gradle
- downloader/build.gradle
- evaluator/build.gradle
- model/build.gradle
- reporter/build.gradle
- scanner/build.gradle
- spdx-utils/build.gradle
- test-utils/build.gradle
- utils/build.gradle
Except in the root project, where we want to load and apply separately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1198)
> Gradle: Consistently use the new syntax to apply plugins

- spdx-utils/src/main/kotlin/SpdxExpression.kt
- spdx-utils/src/test/kotlin/SpdxExpressionTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1199)
> Spdx expression improvements

- model/src/main/kotlin/LicenseFinding.kt
- model/src/main/kotlin/Mappers.kt
- model/src/main/kotlin/TextLocation.kt
- model/src/test/assets/expected-scan-results.yml
- model/src/test/kotlin/LicenseFindingTest.kt
- model/src/test/kotlin/ScanResultContainerTest.kt
- scanner/src/funTest/kotlin/HttpCacheTest.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/test/kotlin/ScanCodeTest.kt
- utils/src/main/kotlin/SortedSetComparator.kt
Store the locations of license findings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1158)
> License locations

- .travis.yml
This is a fixup for 1552962.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1201)
> Travis: Add a missing semicolon inside an if-block

- analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-lockfile.yml
- analyzer/src/funTest/assets/projects/synthetic/bundler/lockfile/Gemfile.lock
As reported by GitHub, see https://nvd.nist.gov/vuln/detail/CVE-2018-14404.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1205)
> BundlerTest: Upgrade nokogiri to address a potential security vulnerability

- reporter-web-app/README.md
Travis currently merges their ".org" to their ".com".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1212)
> reporter-web-app: Refer to travis-ci.com in the README

- spdx-utils/src/main/kotlin/SpdxExpression.kt
- spdx-utils/src/main/kotlin/SpdxExpressionDefaultVisitor.kt
- spdx-utils/src/test/kotlin/SpdxExpressionTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1211)
> SpdxExpression: Support validating against deprecated license identifiers

- analyzer/src/main/kotlin/managers/Gradle.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1213)
> Analyze kts

- analyzer/src/funTest/kotlin/integration/GradleIntegrationTest.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1220)
> Gradle integration test fixes for Kotlin script support

- README.md
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- scanner/src/funTest/kotlin/scanners/FileCounterTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/Scanner.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1223)
> Scanner cleanups

- gradle.properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1224)
> Upgrade to Kotlin 1.3.20

- docs/Configuration.md
- model/src/main/kotlin/config/RuleViolationResolutionReason.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1225)
> RuleViolationResolution: Add `cant_fix` as reason

- model/src/main/kotlin/config/ArtifactoryCacheConfiguration.kt
- model/src/test/kotlin/config/ArtifactoryCacheConfigurationTest.kt
- scanner/src/funTest/kotlin/HttpCacheTest.kt
- scanner/src/main/kotlin/ArtifactoryCache.kt
- scanner/src/main/kotlin/ScanResultsCache.kt
- scanner/src/test/kotlin/ScanResultsCacheTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1230)
> ScanResultsCache: List packages

- scanner/src/main/kotlin/LocalScanner.kt
For a better overview as these belong together.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1240)
> LocalScanner: Define scanPackage() directly after scanPackages()

- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- model/src/main/kotlin/Identifier.kt
- model/src/test/kotlin/IdentifierTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1242)
> Fix `Identifier.isFromOrg()`

- test-utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1244)
> Replacement logic cleanups

- analyzer/src/main/kotlin/managers/GoDep.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1243)
> Miscellaneous minor GoDep code improvements

- analyzer/src/funTest/assets/projects/external/directories-expected-output.yml
- analyzer/src/funTest/assets/projects/external/grpc-bundler-expected-output.yml
- analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- build.gradle
- cli/src/funTest/kotlin/MainTest.kt
- cli/src/main/kotlin/Main.kt
- gradle.properties
- model/.gitignore
- model/build.gradle
- model/src/main/kotlin/Environment.kt
- reporter/src/funTest/assets/npm-test-with-exclude-scan-results.yml
- reporter/src/funTest/assets/npm-test-without-exclude-scan-results.yml
- reporter/src/funTest/assets/static-html-reporter-test-input.yml
- scanner/src/funTest/assets/analyzer-result.yml
- scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
- spdx-utils/build.gradle
- test-utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1245)
> Add more environment info to runs

- .appveyor.yml
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- gradle.properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1246)
> Evaluator order

- analyzer/src/funTest/kotlin/MavenTest.kt
- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- downloader/src/test/kotlin/CvsTest.kt
- downloader/src/test/kotlin/GitTest.kt
- downloader/src/test/kotlin/MercurialTest.kt
- downloader/src/test/kotlin/SubversionTest.kt
- utils/src/main/kotlin/OkHttpClientHelper.kt
- utils/src/main/kotlin/Utils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1248)
> User directory funtions

- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1249)
> Git svn sparse check

- analyzer/src/main/kotlin/MavenSupport.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1250)
> MavenSupport: Make parseScm() private because we can

- analyzer/src/funTest/assets/projects/synthetic/bower-expected-output.yml
- docs/Configuration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1252)
> Edits for grammar and spelling, hopefully also improving readability

- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- downloader/src/main/kotlin/Downloader.kt
- model/src/main/kotlin/Hash.kt
- model/src/main/kotlin/HashAlgorithm.kt
- model/src/main/kotlin/RemoteArtifact.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1258)
> Hash utils

- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- analyzer/src/test/kotlin/PackageManagerTest.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- model/src/main/kotlin/ScannerDetails.kt
- reporter/src/funTest/assets/npm-test-with-exclude-scan-results.yml
- reporter/src/funTest/assets/npm-test-without-exclude-scan-results.yml
- reporter/src/funTest/assets/static-html-reporter-test-input.yml
- scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
- scanner/src/funTest/kotlin/scanners/FileCounterTest.kt
- scanner/src/funTest/kotlin/scanners/ScanPathTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/ScannerFactory.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/FileCounter.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/test/kotlin/ScanCodeTest.kt
- scanner/src/test/kotlin/ScannerDetailsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1255)
> Do not override toString() for the scanner name

- docs/Configuration.md
- model/src/main/kotlin/config/RuleViolationResolutionReason.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1259)
> RuleViolationResolution: Add `license acquired` as reason

- downloader/src/main/kotlin/vcs/Git.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1261)
> Git improve sparse checkout

- downloader/src/main/kotlin/Downloader.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- model/src/main/kotlin/AnalyzerResult.kt
- scanner/src/main/kotlin/ScanResultsStorage.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
URLs already stand out enough by themselves, and it usually just reads
better when not putting them in quotes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1260)
> Do not single-quote URLs in messages

- gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/5.2/release-notes.html.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1263)
> Gradle: Upgrade to version 5.2

- cli/docker/Dockerfile
- gradle.properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1264)
> Gradle docker plugin

- analyzer/src/funTest/assets/projects/synthetic/bower-expected-output.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1267)
> bower-expected-output: Upgrade the webcomponentsjs dependency to version 1.3.1

- downloader/src/funTest/kotlin/DownloaderTest.kt
This is a fixup for e410dd5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1271)
> DownloaderTest: Update an expected message string

- cli/docker/Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1257)
> Dockerfile: Add a source code offer for installed binaries

- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1273)
> VCS sparse check path

- gradle.properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1270)
> Kotlin 1.3.21

- analyzer/src/funTest/assets/projects/synthetic/bower-expected-output.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1275)
> bower-expected-output: Upgrade the webcomponentsjs dependency to version 1.3.2

- analyzer/src/funTest/assets/projects/synthetic/bower-expected-output.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1281)
> bower-expected-output: Upgrade the webcomponentsjs dependency to version 1.3.3

- .appveyor.yml
- .travis.yml
- analyzer/src/main/kotlin/managers/Bower.kt
- cli/docker/Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1278)
> Fixes and improvements to building the Docker image

- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/test/kotlin/ScanCodeTest.kt
- spdx-utils/src/main/kotlin/SpdxUtils.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1280)
> Introduce and use a list of non-license files excluded from scans

- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
See https://github.com/gradle/gradle/releases/tag/v5.2.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1283)
> Gradle: Upgrade to version 5.2.1

- analyzer/src/main/kotlin/PackageManager.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1277)
> Replace a few remaining simpleName calls with the respective name

- analyzer/src/main/kotlin/GradleSupport.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/resources/scripts/init.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1282)
> Gradle warnings

- model/src/main/kotlin/OrtResult.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1287)
> OrtResult: Add a convenience function to check if an Identifier is excluded

- analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml
- analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
- analyzer/src/main/kotlin/MavenSupport.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1286)
> Maven SCM fallback

- cli/src/main/kotlin/Main.kt
Also display the command name, if any, as part of the version header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1288)
> Main: Add a --version command line option

- cli/src/main/kotlin/Main.kt
- model/src/main/kotlin/Environment.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1291)
> Environment tuning

- analyzer/src/funTest/assets/projects/external/multi-kotlin-project-expected-output-cli.yml
- analyzer/src/funTest/assets/projects/external/multi-kotlin-project-expected-output-root.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-android-expected-output-app.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app-2.14.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app-3.4.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-library-expected-output-app.yml
- analyzer/src/main/kotlin/GradleSupport.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/resources/scripts/init.gradle
- model/src/main/kotlin/PackageLinkage.kt
- model/src/main/kotlin/ProjectAnalyzerResult.kt
- model/src/test/kotlin/ProjectTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1292)
> Gradle project deps

- analyzer/src/funTest/assets/projects/external/grpc-bundler-expected-output.yml
- downloader/src/main/kotlin/vcs/GitRepo.kt
- model/src/main/kotlin/VcsInfo.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1295)
> Some small VCS improvements

- analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml
- analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-app.yml
- analyzer/src/main/kotlin/MavenSupport.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/SBT.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1296)
> Maven multi module

- model/src/main/kotlin/OrtResult.kt
- model/src/test/kotlin/OrtResultTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1299)
> Scripting convenience

- model/src/main/kotlin/OrtResult.kt
- model/src/main/kotlin/Project.kt
- model/src/test/kotlin/OrtResultTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1300)
> OrtResult stuff

- analyzer/src/main/kotlin/PackageJsonUtils.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/PhpComposer.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/Scanner.kt
- test-utils/src/main/kotlin/Utils.kt
- utils/src/main/kotlin/CopyrightStatementsProcessor.kt
- utils/src/test/kotlin/RedirectionTest.kt
In preparation for a detekt upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1301)
> Trivially fix a few spacing issues that are reported by newer detekt versions

- analyzer/src/main/kotlin/MavenSupport.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1302)
> MavenSupport: If a POM's license comment is an SPDX id, prefer it

- analyzer/src/main/kotlin/managers/GoDep.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1307)
> Fix a GoDep GOPATH symlink issue

- utils/src/test/kotlin/ProcessCaptureTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1306)
> utils: Add a test for ProcessCapture

- model/src/main/kotlin/AnalyzerResult.kt
- model/src/main/kotlin/Package.kt
- model/src/main/kotlin/Project.kt
- model/src/test/kotlin/AnalyzerResultTest.kt
If the declared license of a project or package could not be processed
add an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1315)
> Unmapped license errors

- analyzer/src/main/kotlin/Analyzer.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1317)
> Config logging

- docs/GettingStarted.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1316)
> Docs updates

- utils/src/main/kotlin/Extensions.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1321)
> Percent encode

- analyzer/src/funTest/assets/projects/external/godep-expected-output.yml
- analyzer/src/funTest/assets/projects/external/grpc-bundler-expected-output.yml
- analyzer/src/funTest/assets/projects/external/qmstr-expected-output.yml
- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml
- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml
- analyzer/src/funTest/assets/projects/external/sprig-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output-no-lockfile.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/yarn-expected-output.yml
- model/src/main/kotlin/Identifier.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1319)
> Purl encode

- analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml
- analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-lockfile.yml
- reporter/src/funTest/assets/NPM-is-windows-1.0.2-expected-NOTICE
- reporter/src/funTest/assets/NPM-is-windows-1.0.2-expected-NOTICE_UNPROCESSED
- spdx-utils/build.gradle
- spdx-utils/src/main/kotlin/Extensions.kt
- spdx-utils/src/main/kotlin/SpdxExpression.kt
- spdx-utils/src/main/kotlin/SpdxExpressionDefaultVisitor.kt
- spdx-utils/src/main/kotlin/SpdxLicense.kt
- spdx-utils/src/main/kotlin/SpdxLicenseAliasMapping.kt
- spdx-utils/src/main/resources/licenses/HPND-sell-variant
- spdx-utils/src/test/kotlin/SpdxExpressionParserTest.kt
- spdx-utils/src/test/kotlin/SpdxExpressionTest.kt
- spdx-utils/src/test/kotlin/SpdxLicenseTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1323)
> Add support for normalizing deprecated SPDX IDs to current ones

- analyzer/src/main/resources/scripts/init.gradle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1330)
> Address some nits in init.gradle

- reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
- reporter/src/main/kotlin/reporters/ReportTableModel.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
Display the numbers of errors, warnings and hints separately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1331)
> StaticHtmlReporter: Break down the issue summary

- cli/src/main/kotlin/commands/EvaluatorCommand.kt
Print a summary how many issues are found by severity after running the
rules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1334)
> evaluator: Print a summary of found issues

- utils/src/main/kotlin/DirectoryStash.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/test/kotlin/DirectoryStashTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1335)
> Fix stashing non-existing directories

- analyzer/src/main/kotlin/PackageManager.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1336)
> PackageManager: Clarify the log message when ignoring directories

- analyzer/src/funTest/kotlin/GoDepTest.kt
- analyzer/src/funTest/kotlin/NpmVersionUrlTest.kt
- analyzer/src/main/kotlin/PackageManagerFactory.kt
- analyzer/src/main/kotlin/managers/PIP.kt
- cli/src/main/kotlin/commands/RequirementsCommand.kt
- downloader/src/main/kotlin/Downloader.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- model/src/main/kotlin/OrtResult.kt
- model/src/main/kotlin/OutputFormat.kt
- model/src/main/kotlin/PackageReference.kt
- model/src/main/kotlin/ScanResultContainer.kt
- model/src/main/kotlin/ScannerDetails.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/ScannerFactory.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- test-utils/src/main/kotlin/Utils.kt
- utils/src/main/kotlin/DirectoryStash.kt
Various Kotlin fixes, see the commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1339)
> Kotlin fixes

- build.gradle
- gradle.properties
See https://github.com/ben-manes/gradle-versions-plugin/releases/tag/v0.21.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1340)
> Gradle: Upgrade the versions plugin to version 0.21.0

- reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt
This puts the most important issues on top of the list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1342)
> reporter: Check severity prior to source when sorting rule violations

- analyzer/src/main/kotlin/managers/Bundler.kt
- utils/src/main/kotlin/OkHttpClientHelper.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1346)
> Refactor queryRubygems() to throw on unexpected errors

- model/src/main/kotlin/OutputFormat.kt
For completeness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1348)
> OutputFormat: Add the XML format mapper

- scanner/src/main/kotlin/Scanner.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1354)
> Scanner: Introduce a local variable for slightly better readabilty

- utils/src/main/kotlin/ProcessCapture.kt
Output heading and trailing lines, as mostly errors occur at the end of
the output. Also share the same limiting code between generation of the
error message, and the debug logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1353)
> ProcessCapture: Refactor limiting of log output lines

- analyzer/src/main/kotlin/managers/NPM.kt
- analyzer/src/test/kotlin/NpmTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1361)
> Support expanding explicit NPM "github" short URLs 

- reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
- reporter/src/main/kotlin/reporters/ReportTableModel.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
As that is what is relevant to the user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1364)
> StaticHtmlReporter: Limit the issue summary to unresolved issues

- downloader/src/main/kotlin/Downloader.kt
Previously, the connection was never closed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1368)
> downloader: Ensure the HTTP connection is closed in `downloadSourceArtifact`

- downloader/src/main/kotlin/vcs/GitRepo.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1370)
> Force repo sync by default to deal with broken project setups

- CONTRIBUTING.md
The sentence in CONTRIBUTING.md was confusing. It looks like there was an incomplete thought there. Removed unnecessary words.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1372)
> Fix sentence issue in CONTRIBUTING.md

- model/src/main/kotlin/AccessStatistics.kt
- scanner/src/funTest/kotlin/scanners/FileCounterTest.kt
- scanner/src/main/kotlin/ScanResultsStorage.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1374)
> Sync storage reads

- model/src/main/kotlin/OrtResult.kt
- model/src/main/kotlin/config/Excludes.kt
- model/src/test/kotlin/config/ExcludesTest.kt
- reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
- reporter/src/funTest/assets/static-html-reporter-test-input.yml
- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- reporter/src/main/kotlin/reporters/ReportTableModel.kt
- reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1369)
> Use path excludes to exclude detected licenses

- .travis.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1376)
> Travis: Only use curl instead of wget for consistency

- docs/Configuration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1378)
> docs: Document path excludes

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- analyzer/src/main/kotlin/managers/PIP.kt
- cli/src/funTest/kotlin/MainTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1383)
> Piptest upgrade

- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/test/kotlin/ExtensionsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1386)
> Expand tilde

- downloader/src/main/kotlin/Downloader.kt
Remove the fallback to download the Maven POM file if the source code
cannot be downloaded. The current implementation has two issues with the
scan results storage:
* Stored scan results of POM files are never retrieved from the cache.
* Scan results of POM files are added to the storage even if the same
scan result already exists.
Also, the reporter does not visualize if only the POM file was scanned,
giving the false impression that the source code was scanned.
Therefore remove the fallback, because the benefits of scanning the POM
file do not outweigh the costs of fixing above issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1387)
> downloader: Remove the Maven POM fallback

- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1389)
> Expand a tilde in paths from the command line

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1392)
> PipTest: Upgrade the expected Werkzeug version to 0.15.1

- gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/5.3/release-notes.html.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1391)
> Gradle: Upgrade to version 5.3

- model/src/main/kotlin/OrtResult.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1393)
> OrtResult: Trivially fix a typo in documentation

- downloader/src/funTest/kotlin/DownloaderTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1396)
> Download exception suppressed

- analyzer/src/main/kotlin/Analyzer.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- evaluator/src/test/kotlin/EvaluatorTest.kt
- model/src/main/kotlin/AnalyzerResult.kt
- model/src/main/kotlin/OrtResult.kt
- model/src/main/kotlin/Package.kt
- model/src/main/kotlin/Project.kt
- model/src/main/kotlin/RemoteArtifact.kt
- model/src/main/kotlin/Repository.kt
- model/src/main/kotlin/VcsInfo.kt
- model/src/test/kotlin/OrtResultTest.kt
- model/src/test/kotlin/ProjectAnalyzerResultTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- utils/src/main/kotlin/DeclaredLicenseProcessor.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1397)
> Cleanup EMPTY variables and default arguments

- model/src/main/kotlin/Identifier.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1398)
> Identifier: Return an empty Purl for an empty Identifier

- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/UtilsTest.kt
This helps to identify the common elements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1399)
> utils: Change disjoint() to return common elements

- analyzer/src/main/kotlin/managers/PIP.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1401)
> Disregard leading zeros when comparing package version numbers with Pip

- analyzer/src/main/kotlin/managers/PIP.kt
- analyzer/src/main/kotlin/managers/PhpComposer.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1403)
> Code improvements

- .appveyor.yml
To speed up pull request builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1411)
> AppVeyor: Run dokka only for scheduled builds

- .appveyor.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1415)
> AppVeyor: Extract package manager versions to variables
