oss-review-toolkit/ort

model/src/main/kotlin/config/PackageConfiguration.kt
model/src/test/kotlin/utils/LicenseResolverTest.kt

One has to compare against `resolvedRevision` as just `revision` may be
a moving target, e.g. reference a branch head.

PackageConfiguration: Fix-up VcsMatcher.matches()

---

helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
helper-cli/src/main/kotlin/common/Utils.kt
model/src/main/kotlin/utils/LicenseResolver.kt
model/src/test/kotlin/utils/LicenseResolverTest.kt
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/funTest/assets/static-html-reporter-test-input.yml
reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
reporter/src/main/kotlin/utils/StatisticsCalculator.kt
spdx-utils/src/main/kotlin/SpdxExpression.kt

The changes enable the use of the SPDX AND operator in detected licenses and thus most importantly also in license finding curations. The SPDX OR operator is not supported yet, but is now handle like the AND operator and thus the handling becomes fully consistent with that for declared and concluded licenses.

Somewhat support the SPDX operators AND and WITH for detected licenses

---

analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
analyzer/src/test/kotlin/managers/utils/NodeSupportTest.kt
model/src/test/kotlin/IdentifierTest.kt
scanner/src/funTest/kotlin/scanners/AbstractScannerTest.kt
utils/src/test/kotlin/DeclaredLicenseProcessorTest.kt
utils/src/test/kotlin/UtilsTest.kt

This leads to nicer output in case of assertion failures and ensures
that the loops are continued in case an assertion fails inside of the
loop.

tests: Turn forEach() into forAll() where applicable

---

model/src/main/kotlin/config/PackageConfiguration.kt

For some VCS types like Git it is not necessary to match the VCS path,
because the configuration entries are still valid if the VCS path was
changed. For Git-Repo the path denotes the Git-Repo manifest and thus
the path should be matched. Introduce an optional `path` property to
address that.

PackageConfiguration: Optionally match also the VCS path

---

reporter-web-app/src/components/SummaryView.js
reporter-web-app/src/models/WebAppOrtResult.js
reporter-web-app/src/models/WebAppPackage.js
reporter-web-app/src/reducers/index.js
reporter-web-app/src/reducers/selectors.js

Fix the Summary tab to only show processed/de-duplicated licenses names and numbers
instead of a mix of processed and unprocessed declared and detected licenses.
Prior to this change it could happen that the Summary license table
showed X number of licenses rows while the row count number showed Y.

reporter-web-app: Remove unprocessed licenses from Summary

---

cli/src/main/kotlin/commands/ClearlyDefinedUploadCommand.kt

As explained at [1] and visible in the code at [2], getting the
definitions already triggers the harvest of non-harvested components, so
omit requesting an explicit harvest again.
[1] https://github.com/oss-review-toolkit/ort/pull/2611#issuecomment-628744320
[2] https://github.com/clearlydefined/service/blob/4917725/business/definitionService.js#L212

ClearlyDefinedUploadCommand: Rely on components getting implicitly harvested

---

cli/src/main/kotlin/commands/ClearlyDefinedUploadCommand.kt

ClearlyDefinedUploadCommand: Remove the unused requestHarvest() function

---

analyzer/src/main/kotlin/managers/Gradle.kt

If the ORT Analyzer is run with "--debug", show standard output of the
analyzed Gradle project in ORT's debug log.
Show error output of the analyzed Gradle project in ORT's warning log.
This eases debugging of issues with the analysis of Gradle projects.

Gradle: Eventually show stdout and stderr of the analyzed build

---

analyzer/src/main/kotlin/managers/Gradle.kt

Gradle: Fix a typo in a code comment

---

analyzer/src/main/kotlin/managers/Pip.kt

Some developers use 'dev_requirements.txt' as name for the file defining Python dependencies used only for development.

Pip: Allow requirements.txt to be prefixed

---

analyzer/src/main/kotlin/managers/Pip.kt

As some libraries use the classifier 'License :: OSI Approved'.

Pip: Prevent returning 'OSI Approved' as declared license

---

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt

As declared in https://pypi.org/project/thrift/0.13.0/.

SpdxDeclaredLicenseMapping: Add 'Apache Software License, Version 2'

---

reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt

This at least fixes links to scanned Maven source artifacts with
existing VCS information but inaccessible VCS repositories.

StaticHtmlReporter: Add a work-around for missing scan provenance

---

cli/src/main/kotlin/commands/AnalyzerCommand.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
reporter/src/main/kotlin/Reporter.kt
reporter/src/main/kotlin/reporters/AbstractNoticeReporter.kt
reporter/src/main/kotlin/reporters/AmazonOssAttributionBuilderReporter.kt
reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
reporter/src/main/kotlin/reporters/EvaluatedModelReporter.kt
reporter/src/main/kotlin/reporters/ExcelReporter.kt
reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
reporter/src/main/kotlin/reporters/WebAppReporter.kt

This will become useful once a report format takes options, e.g. for
custom styling.

Add a way to pass report-format-specific options

---

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt

As found in https://repo.maven.apache.org/maven2/com/amazonaws/amazon-kinesis-client/1.7.5/amazon-kinesis-client-1.7.5.pom,
see also https://github.com/nexB/scancode-toolkit/blob/v3.0.2/src/licensedcode/data/licenses/amazon-sl.LICENSE.

SpdxDeclaredLicenseMapping: Add 'Amazon Software License'

---

clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceTest.kt

In order to run the tests nightly / non-blocking, as they have been
flaky in recent days.

ClearlyDefinedServiceTest: Add an expensive tag to all test cases

---

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt

As found in https://repo.maven.apache.org/maven2/com/github/vbmacher/java-cup-runtime/11b-20160615/java-cup-runtime-11b-20160615.pom,
whereas the URL in the license tag points to
http://www2.cs.tum.edu/projects/cup/install.php which contains the HPND
license. Note that there are several other `java-cup-*` packages using
that declared license.

SpdxDeclaredLicenseMapping: Add an entry for 'CUP Parser Generator'

---

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt

As found in [1], where the URL in the license tag points to [2], which
equals [3].
[1] https://repo.maven.apache.org/maven2/javax/cache/cache-api/1.0.0/cache-api-1.0.0.pom
[2] https://raw.github.com/jsr107/jsr107spec/master/LICENSE.txt
[3] https://github.com/nexB/scancode-toolkit/blob/v3.0.2/src/licensedcode/data/licenses/jsr-107-jcache-spec.LICENSE

SpdxDeclaredLicenseMapping: Add an entry for `jsr-107-jcache-spec`

---

reporter/src/main/kotlin/reporters/ExcelReporter.kt
reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
reporter/src/main/kotlin/utils/ReportTableModel.kt
reporter/src/main/kotlin/utils/ReportTableModelMapper.kt

As they are not reporters themselves.

reporter: Move report tabel model classes to the utils package

---

cli/build.gradle.kts

This is useful to get a single JAR file that bundles all dependencies
which an be directly run without any scripts that adjust the classpath:
$ java -jar cli/build/libs/ort-0.1.0-SNAPSHOT.jar

cli: Additionally build a "Fat JAR" for the CLI

---

model/src/main/kotlin/utils/DefaultResolutionProvider.kt
model/src/main/kotlin/utils/ResolutionProvider.kt

This is a follow-up to 681826f.

model: Improve class docs for (Default)ResolutionProvider, again

---

cli/src/main/kotlin/commands/RequirementsCommand.kt

To visually group different kinds of messages.

RequirementsCommand: Separate legend and error message by a blank line

---

spdx-utils/src/main/kotlin/SpdxExpression.kt
spdx-utils/src/test/kotlin/SpdxExpressionTest.kt

Various improvements of SPDX expressions as preparation for implementing license choices. The core of this is the implementation of a function to convert an SPDX expression to the disjunctive normal form, which allows to easily implement some other functions. See the commit messages for details.

SPDX expression improvements

---

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt

Found in
https://github.com/hamcrest/JavaHamcrest/blob/60454d3c3e2eac8f3049dfbef2900a989a8b8624/build.gradle#L73.

SpdxDeclaredLicenseMapping: Add 'BSD License 3'

---

helper-cli/src/main/kotlin/common/Utils.kt

The previous condition yielded false positive in some cases, e.g.
for `"ab/c".startWith("a")` while `"ab/c".startsWith("a/")` now properly
evaluates to `false`.

Utils: Fix determining whether a path is contained in another

---

reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/funTest/assets/static-html-reporter-test-input.yml
reporter/src/main/kotlin/model/EvaluatedModelMapper.kt

The licenses array contains entries for declared licenses and detected licenses while only the entries for the detected licenses were actually decomposed. Use `decompose()` instead of `licenses()` also for deriving the entries for the declared licenses.

EvaluatedModel: Properly decompose the declared license

---

.azure-pipelines/LinuxAnalyzerTest.yml

The existing Gradle cache is >5GB which causes builds to fail with "No
space left on device". Because there is no way to clear an existing
cache, change the cache key to ensure a new cache is used [1].
A prior change in 427f166 should make sure that the cache does not grow
too large in future.
[1] https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#can-i-clear-a-cache

Azure: Change the Gradle cache key for the Linux analyzer job

---

helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt

Instead of the revision, because this usually is the more interresting
value.

ListLicensesCommand: Output the resolved revision

---

analyzer/src/funTest/assets/projects/synthetic/godep/godeps/Godeps/Godeps.json

Add golang.org/x/sys to the Godeps.json file to avoid having to do
repeated updates of the expected results.

GoDepTest: Lock dependency versions of the godeps test project

---

cli/src/main/kotlin/commands/DownloaderCommand.kt
utils/src/main/kotlin/OrtAuthenticator.kt
utils/src/test/kotlin/OrtAuthenticatorTest.kt

This includes support for cloning private Git repos via HTTP(S). Please have a look at the individual commit messages for the details.

Support .netrc files as a way to authenticate HTTP(S) downloads

---

model/src/main/kotlin/utils/FindingsMatcher.kt

Add a new function to the `FindingsMatcher` that keeps the association of which specific license finding a copyright finding was associated to. This will later be used by #2667.

FindingsMatcher: Keep the association of matched locations

---

analyzer/src/main/kotlin/managers/Bower.kt
analyzer/src/main/kotlin/managers/Cargo.kt
analyzer/src/main/kotlin/managers/Conan.kt

There already is logging for this in the caller.

analyzer: Remove initial log statements when resolving dependencies

---

README.md

The resolutions.yml link in [configuration](https://github.com/oss-review-toolkit/ort#configuration) section of the main README.md is was incorrect and lead to a 404.

Fix resolutions.yml link in main README.md

---

helper-cli/src/main/kotlin/common/Utils.kt
model/src/main/kotlin/licenses/LicenseFindingCurationResult.kt
model/src/main/kotlin/utils/FindingCurationMatcher.kt
model/src/main/kotlin/utils/LicenseResolver.kt
model/src/test/kotlin/utils/FindingCurationMatcherTest.kt
reporter/src/main/kotlin/model/EvaluatedModelMapper.kt

Add a result class that is returned by the `FindingCurationMatcher`,
instead of only returning a list of resulting license findings. This
allows to track the original findings and the license finding curations
which resulted in the curated findings.
This is useful for visualizing applied license finding curations in the
reporters to help users to see the effect of license finding curations,
and to debug issues with license finding curations.
It will also be used by a new license resolver in a later commit.

model: Add a result class for applying license finding curations

---

.ort.yml

.ort.yml: Trivially trim trailing space

---

Jenkinsfile

This is a fixup for bd08a98 as the ORT Downloader does not do
incremental fetches but wants to do a fresh clone.

Jeninsfile: Remove the config directory before cloning to it

---

analyzer/src/main/kotlin/PackageManager.kt

This changes the output
[main] INFO  org.ossreviewtoolkit.analyzer.PackageManager$Companion$findManagedFiles$2 - Not analyzing directory
to
[main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory

PackageManager: Fix the logger instance being used from inside an object

---

model/src/main/kotlin/utils/FindingsMatcher.kt

The line for computing the unmatched findings was changed by 7b04388 to
subtract the `matchedFindings` rather than the `matchedFileFindings`.
This does not have any effect on the correctness of the result but it
renders matchFindings() very slow.
The time to compute the reports for some larger OrtResult was increased
from about 2 minutes to about an hour. This change fixes that problem.

FindingsMatcher: Fix-up a major performance regression

---

analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
analyzer/src/funTest/kotlin/managers/Extensions.kt
analyzer/src/funTest/kotlin/managers/MavenTest.kt
analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/managers/Bower.kt
analyzer/src/main/kotlin/managers/Bundler.kt
analyzer/src/main/kotlin/managers/Cargo.kt
analyzer/src/main/kotlin/managers/CocoaPods.kt
analyzer/src/main/kotlin/managers/Conan.kt
analyzer/src/main/kotlin/managers/DotNet.kt
analyzer/src/main/kotlin/managers/GoDep.kt
analyzer/src/main/kotlin/managers/GoMod.kt
analyzer/src/main/kotlin/managers/Gradle.kt
analyzer/src/main/kotlin/managers/Maven.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/NuGet.kt
analyzer/src/main/kotlin/managers/PhpComposer.kt
analyzer/src/main/kotlin/managers/Pip.kt
analyzer/src/main/kotlin/managers/Pipenv.kt
analyzer/src/main/kotlin/managers/Pub.kt
analyzer/src/main/kotlin/managers/Stack.kt
analyzer/src/main/kotlin/managers/Unmanaged.kt

Change the signature of `PackageManager.resolveDependencies` to allow
multiple projects per definition file. This is required for package
managers that allow defining multiple projects in a single definition
file, like Gradle or SBT.
This commit only changes the API, support for actually detekting
multiple projects in a single definition file will be added later.

analyzer: Allow multiple projects per definition file

---

README.md
cli/build.gradle.kts
gradle.properties
reporter/build.gradle.kts
reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt
reporter/src/main/kotlin/utils/AttributionDocumentPdfModel.kt
reporter/src/main/resources/META-INF/services/org.ossreviewtoolkit.reporter.Reporter

This PR adds a new reporter that creates attribution documents in PDF format by leveraging the Eclipse Antenna project, see https://github.com/eclipse/antenna. 
Resolves #2599.

Reporter: Initial implementation for AntennaAttributionDocumentReporter

---

reporter/src/main/kotlin/reporters/EvaluatedModelReporter.kt

EvaluatedModelReporter: Use the new Kotlin duration API

---

cli/src/funTest/kotlin/ExamplesTest.kt
docs/examples/go-dep.ort.yml
docs/examples/pip.ort.yml
docs/examples/sbt.ort.yml
spdx-utils/src/main/kotlin/SpdxSimpleLicenseMapping.kt

Add tests for the files in "docs/examples" to ensure that changes in ORT
do not break the examples. The test class is added to the "cli" module,
because this module depends on all other modules and therefore has
access to all required classes.

Add tests for the examples in the docs

---

reporter/src/main/kotlin/Reporter.kt
reporter/src/main/kotlin/reporters/AbstractNoticeReporter.kt
reporter/src/main/kotlin/reporters/AmazonOssAttributionBuilderReporter.kt
reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt
reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
reporter/src/main/kotlin/reporters/EvaluatedModelReporter.kt
reporter/src/main/kotlin/reporters/ExcelReporter.kt
reporter/src/main/kotlin/reporters/NoticeByPackageReporter.kt
reporter/src/main/kotlin/reporters/NoticeSummaryReporter.kt
reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
reporter/src/main/kotlin/reporters/WebAppReporter.kt

With possibly multiple files being created now, enforing this property
for all reporters does not make sense anymore.

reporter: Remove the defaultFilename from the interface

---

spdx-utils/src/main/resources/declared-license-mapping.yml

[1] https://repo1.maven.org/maven2/io/kotest/kotest-core/4.0.6/kotest-core-4.0.6.pom

Add a declared license mapping for "The Apache 2.0 License"

---

reporter/src/funTest/kotlin/reporters/AntennaAttributionDocumentReporterTest.kt
reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt

The AntennaAttributionDocumentReporterTest tests only the size of the
generated report and uses for this the scanners test result.

reporter: Add a test for the AntennaAttributionDocumentReporter

---

cli/src/main/kotlin/OrtMain.kt

OrtMain: Move the configFile fallback to an option default

---

README.md

README: Fix a typo in "Kotlin"

---

downloader/src/main/kotlin/WorkingTree.kt

As
No matching tag found for version ''. Please create a tag whose name contains the version.
reads a bit awkward, and the hint is also wrong.

WorkingTree: Use a dedicated message for a blank version in guessRevisionName()

---

analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/managers/Bundler.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/Stack.kt
cli/src/funTest/kotlin/ExamplesTest.kt
downloader/src/funTest/kotlin/vcs/GitRepoDownloadTest.kt
downloader/src/main/kotlin/vcs/Cvs.kt
reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt
spdx-utils/build.gradle.kts

To avoid "Unsafe use of a nullable receiver" inspection warnings, and to
reduce dependencies on the JVM.

Replace Java's listFiles() with Kotlin's walk()

---

spdx-utils/src/main/resources/declared-license-mapping.yml

The license of this library changed several times while the declared
license string remained constant. That is, any mapping entry for this
declared license string is incorrect, and thus remove the existing one.
This reverts ed84d8c.

declared-license-mapping: Remove an entry for the JCache library

---

.reuse/dep5
spdx-utils/build.gradle.kts
spdx-utils/src/main/kotlin/SpdxModelSerializer.kt
spdx-utils/src/main/kotlin/SpdxUtils.kt
spdx-utils/src/main/kotlin/model/SpdxAnnotation.kt
spdx-utils/src/main/kotlin/model/SpdxChecksum.kt
spdx-utils/src/main/kotlin/model/SpdxConstants.kt
spdx-utils/src/main/kotlin/model/SpdxCreationInfo.kt
spdx-utils/src/main/kotlin/model/SpdxDocument.kt
spdx-utils/src/main/kotlin/model/SpdxExternalDocumentReference.kt
spdx-utils/src/main/kotlin/model/SpdxExternalReference.kt
spdx-utils/src/main/kotlin/model/SpdxExtractedLicenseInfo.kt
spdx-utils/src/main/kotlin/model/SpdxFile.kt
spdx-utils/src/main/kotlin/model/SpdxPackage.kt
spdx-utils/src/main/kotlin/model/SpdxPackageVerificationCode.kt
spdx-utils/src/main/kotlin/model/SpdxRelationship.kt
spdx-utils/src/main/kotlin/model/SpdxSnippet.kt
spdx-utils/src/test/kotlin/SpdxDocumentModelTest.kt
spdx-utils/src/test/resources/spdx-spec-examples/SPDXJSONExample-v2.2-no-ranges.spdx.json
spdx-utils/src/test/resources/spdx-spec-examples/SPDXJSONExample-v2.2.spdx.json
spdx-utils/src/test/resources/spdx-spec-examples/SPDXYAMLExample-2.2-no-ranges.spdx.yaml
spdx-utils/src/test/resources/spdx-spec-examples/SPDXYAMLExample-2.2.spdx.yaml

This change adds the model classes for SPDX documents for SPDX version
2.2.1 and supports serialization and deserialization of JSON and YAML
SPDX document files. All properties are supported except for 'ranges'
which are not properly specified yet [1], and thus cannot be implemented yet.
There is some design flexibility regarding how strong the typing is for
the respective properties, e.g. a propery could use a String or a
dedicated type. This change does not implement the strongest possible
typing for both, fault tollerance and most importantly to limit the
scope of this first iteration. Adding a dedicated type for SPDX IDs or
references are good candidates for future improvements.
The SPDX specification [2] is targeting mainly RDF and thus does not
provide enough information to derive …

spdx-utils: Implement the SPDX 2.2.1 document model

---

analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt
model/src/test/kotlin/AnalyzerRunTest.kt
model/src/test/kotlin/EvaluatorRunTest.kt
model/src/test/kotlin/PackageTest.kt
model/src/test/kotlin/ScannerRunTest.kt
model/src/test/kotlin/config/RepositoryConfigurationTest.kt
spdx-utils/src/test/kotlin/SpdxExpressionLexerTest.kt
spdx-utils/src/test/kotlin/SpdxExpressionParserTest.kt

Reduce indentation in tests by passing init as a lambda

---

.reuse/dep5
spdx-utils/src/main/kotlin/SpdxModelSerializer.kt
spdx-utils/src/main/kotlin/model/SpdxAnnotation.kt
spdx-utils/src/main/kotlin/model/SpdxChecksum.kt
spdx-utils/src/main/kotlin/model/SpdxConstants.kt
spdx-utils/src/main/kotlin/model/SpdxCreationInfo.kt
spdx-utils/src/main/kotlin/model/SpdxDocument.kt
spdx-utils/src/main/kotlin/model/SpdxExternalDocumentReference.kt
spdx-utils/src/main/kotlin/model/SpdxExternalReference.kt
spdx-utils/src/main/kotlin/model/SpdxExtractedLicenseInfo.kt
spdx-utils/src/main/kotlin/model/SpdxFile.kt
spdx-utils/src/main/kotlin/model/SpdxPackage.kt
spdx-utils/src/main/kotlin/model/SpdxPackageVerificationCode.kt
spdx-utils/src/main/kotlin/model/SpdxRelationship.kt
spdx-utils/src/main/kotlin/model/SpdxSnippet.kt
spdx-utils/src/test/kotlin/SpdxDocumentModelTest.kt

Fix-up the copyright years of the SPDX document model implementation as well as several REUSE file entries.

spdx-utils: Copyright fixes

---

downloader/src/funTest/kotlin/vcs/GitRepoDownloadTest.kt
downloader/src/main/kotlin/vcs/Cvs.kt

As walk().maxDepth(1) includes the "." directory we need to explicitly
exclude it if we do not want to handle it. This is a fixup for a9451c6.

downloader: Fix a sub-directory walk to not contain the parent directory

---

model/src/main/kotlin/Identifier.kt

So that the rest of a string will become part of the version instead of
being silently dropped.

Identifier: Limit the split components to a maximum of 4

---

reporter/src/main/kotlin/reporters/WebAppReporter.kt

Based on the benchmark with a large project, the maximum compression
level reduces the file size by about 9%, while increasing the time to
generate the report by about 12%. There was no impact on the time to
load the report in the browser.

reporter: Increase the GZIP compression level to 9 for the web app

---

analyzer/src/funTest/kotlin/managers/NpmTest.kt
analyzer/src/funTest/kotlin/managers/PubTest.kt
analyzer/src/funTest/kotlin/managers/YarnTest.kt
reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
reporter/src/funTest/kotlin/reporters/SpdxDocumentReporterTest.kt
reporter/src/funTest/kotlin/reporters/StaticHtmlReporterTest.kt
reporter/src/main/kotlin/reporters/SpdxDocumentReporter.kt
reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt
reporter/src/main/resources/META-INF/services/org.ossreviewtoolkit.reporter.Reporter
test-utils/src/main/kotlin/Utils.kt

Add an initial SPDX document reporter which for now only creates the
document header. Logic for serializing additional data will be added
incrementally in following changes.

reporter: Add a very basic SpdxDocumentReporter

---

gradle/wrapper/gradle-wrapper.properties

See https://github.com/gradle/gradle/releases/tag/v6.5.1.

Upgrade Gradle to version 6.5.1

---

spdx-utils/src/main/kotlin/model/SpdxFile.kt
spdx-utils/src/main/kotlin/model/SpdxPackage.kt
spdx-utils/src/main/kotlin/model/SpdxSnippet.kt

spdx-utils: Fix all broken references from kDoc to SpdxConstants

---

reporter/src/funTest/kotlin/reporters/AntennaAttributionDocumentReporterTest.kt
reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt

By not scanning through the whole text for each replacement but using a
single pre-compiled regex.

AntennaAttributionDocumentReporter: Optimize glyph replacement for speed

---

model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt
model/src/main/kotlin/licenses/LicenseInfo.kt
model/src/main/kotlin/licenses/LicenseInfoProvider.kt
model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt

A new license API for ORT. The idea is to bundle the code that processes concluded, declared, and detected licenses in a single place, and to provide an API that will be used by all places in ORT working with those licenses, to make the license related code more consistent.

New license API

---

model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt

Filter out any copyright garbage before passing the copyrights to the
copyright statements processor. This avoids that garbage entries affect
the result of the processor.
To reflect this change in the model, add a map of all copyright garbage
findings mapped to their provenance to the `ResolvedLicenseInfo`, and
remove the `isGarbage` properties from `ResolvedCopyright` and
`ResolvedCopyrightFinding`.
This is a functional change compared to the existing code which cleans
copyright garbage before and after running the copyright statements
processor. The reason for the change is, that it is easier to understand
for the user that only actual copyright findings should be added to the
copyright garbage list, and it makes it independent of any changes in
the copyright statements processor.

LicenseInfoResolver: Filter copyright garbage before processing statements

---

reporter/src/funTest/kotlin/reporters/CycloneDxReporterTest.kt
reporter/src/main/kotlin/reporters/CycloneDxReporter.kt

CycloneDxReporter: Escape the component description if needed

---

model/src/main/kotlin/ScanSummary.kt
model/src/main/kotlin/config/LicenseFindingCuration.kt
spdx-utils/src/main/kotlin/SpdxExpression.kt
spdx-utils/src/main/kotlin/SpdxUtils.kt
spdx-utils/src/main/kotlin/model/SpdxCreationInfo.kt
utils/src/main/kotlin/DeclaredLicenseProcessor.kt

Now https://spdx.org/ forwards to https://spdx.dev/.

Replace all spdx.org links with spdx.dev

---

reporter/src/funTest/kotlin/reporters/AntennaAttributionDocumentReporterTest.kt

Do not read the whole file if we only want to get its size.

AntennaAttributionDocumentReporterTest: Improve getting the file size

---

reporter/src/funTest/kotlin/reporters/AntennaAttributionDocumentReporterTest.kt

As Antenna could now generate multiple report files, move the single()
check to the test itself as it depends on the test case whether a single
or multiple report files are expected.
Also simply name the variable "report" as there is no matching "expected
report".

AntennaAttributionDocumentReporterTest: Apply some minor code improvements

---

gradle.properties
reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt

In order to make the directory functionality work with own fonts, a
directory with fonts can be passed via the template.path option to the
report command. The directory must contain exactly 4 fonts with the
names regular.ttf, bold.ttf, italic.ttf and bold-italic.ttf.

AntennaAttributionDocumentReporter with fonts in directory

---

docs/config-file-ort-yml.md

ScopeExcludeReason was used instead of PathExcludeReason.

docs: Fix path exclude example

---

helper-cli/src/main/kotlin/commands/GenerateScopeExcludesCommand.kt

GenerateScopeExcludesCommand: Add several Gradle scopes

---

cli/src/main/kotlin/commands/AnalyzerCommand.kt
cli/src/main/kotlin/commands/ClearlyDefinedUploadCommand.kt
cli/src/main/kotlin/commands/DownloaderCommand.kt
cli/src/main/kotlin/commands/EvaluatorCommand.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
cli/src/main/kotlin/commands/ScannerCommand.kt

The general rules are:
- Throw a UsageError (with a default status code of 1) to indicate that
the user did something wrong.
- Throw a ProgramResult for errors or failures that are out of the
user's control.
- Use a status code of 1 with ProgramResult for errors that prevented the
program to execute correctly.
- Use a status code >= 2 with ProgramResult for failures found during
successful execution, like rule violations.

cli: Rework the returned status codes

---

test-utils/build.gradle.kts

Add a dependency to kotest-runner-console-jvm which is required for the
kotest IntelliJ plugin [1]. The plugin allows to execute individual
tests in IntelliJ which is otherwise impossible.
[1] https://github.com/kotest/kotest-intellij-plugin#getting-started

test-utils: Add a dependency required for the kotest IntelliJ plugin

---

analyzer/src/main/kotlin/managers/Pip.kt

Pip currently "enriches" the package meta data by querying PyPI. When using an additional repository, for example when
`--extra-index-url` is specified in `requirements.txt` then the enriching won't work for the packages obtained from that additonal repository. This change prepares for enriching the package meta-data also from other sources, namely
- querying also the other repository
- examining locally installed packages e.g. via `pip show`
Therefore the "query and enrich" functionality is split-up into "query" and "enrich" so that the latter can be re-used.

Pip: Prepare for obtaining package meta data from additional sources

---

model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt
model/src/main/kotlin/licenses/LicenseInfo.kt
model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/main/kotlin/utils/Extensions.kt
model/src/main/kotlin/utils/FindingCurationMatcher.kt
model/src/main/kotlin/utils/LicenseResolver.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt

Correctly handle license findings for projects in nested repositories. This was broken when applying path excludes and license finding curations, because the paths in the configuration are relative to the analyzer root, but the paths in the findings are relative to the root of the nested repository.

Correctly handle license findings in nested repositories

---

reporter/src/funTest/kotlin/reporters/CycloneDxReporterTest.kt
reporter/src/main/kotlin/reporters/CycloneDxReporter.kt

This reverts commit c918ff9 as [1] has been fixed in cyclonedx-core-java
3.0.0 which was taken into use in b953b98.
[1] https://github.com/CycloneDX/cyclonedx-core-java/issues/38

Revert "CycloneDxReporter: Escape the component description if needed"

---

evaluator/src/main/kotlin/PackageRule.kt
evaluator/src/test/kotlin/RuleSetTest.kt
model/src/main/kotlin/licenses/LicenseView.kt
model/src/test/kotlin/licenses/LicenseViewTest.kt
model/src/test/kotlin/licenses/TestData.kt

Apply several refactorings to prepare `LicenseView` and `LicenseViewTest` to be used with `ResolvedLicenseInfo`.

Prepare LicenseView for use with ResolvedLicenseInfo

---

reporter/src/main/kotlin/reporters/CycloneDxReporter.kt

Use the license view `CONCLUDED_OR_REST` for packages for consistency
with other reports.

CycloneDxReporter: Respect the concluded license of packages

---

Dockerfile

As version 0.42.0-0ubuntu1~18.04.1 is gone from the repository.

Dockerfile: Upgrade Cargo to version 0.44.1-0ubuntu1~18.04.1

---

docs/notice-pre-processor-kts.md

The "--pre-processing-script" option is now a report specific option, see [1].
[1]: https://github.com/oss-review-toolkit/ort/commit/5f17abbc70e5f153fe08f1f4a56ea289a8f91f93

docs: Update notice-pre-processor example

---

reporter/src/main/kotlin/gitlab/GitLabLicenseModelMapper.kt

If there is an issue during dependency resolution it can happen that
packages appear in the dependency tree of the analyzer result but have
no corresponding entry in the packages list.

GitLabLicenseModelMapper: Fix a NullPointerException

---

reporter/src/funTest/assets/gitlab-license-model-test-expected-output.json
reporter/src/funTest/assets/gitlab-license-model-test-skip-excluded-expected-output.json
reporter/src/main/kotlin/gitlab/GitLabLicenseModel.kt

The schema specification [1] requires gl-license-scanning-report.json
to include a version number so GitLab knows how to render it.
[1]: https://gitlab.com/gitlab-org/security-products/license-management/-/blob/e1bb260b43763a36536b7d3fa4d73108ffb604d4/spec/fixtures/schema/v2.1.json

GitLabLicenseModelReporter: Add schema version

---

analyzer/src/main/kotlin/managers/Maven.kt
analyzer/src/main/kotlin/managers/utils/MavenSupport.kt

Resolves #2905.
Maven seems to fully initialize repositories only when they are read
from settings.xml or from a project pom. In a scenario where no
repositories are specified, the default repository - Maven Central -
is not assigned a proxy, even if the repository system session has a
valid proxy configuration.
To make sure that proxy settings are correctly applied, when creating
a request to execute Maven, the proxy is now explicitly injected into
all the repositories used by the request.
More details about the exact constellation addressed by this PR can be found in the referenced ticket.

Make sure the current proxy is injected into repositories.

---

model/src/test/kotlin/VcsInfoTest.kt

StringSpec is not supposed to be used with nested tests.

VcsInfoTest: Fix test type to WordSpec

---

README.md

Make more clear that ORT is not only useful for Free / Open Source
Software dependencies and highlight that most of its tools can be seen
as an abstraction layer which may e.g. be introduced before a scanner
switch to hide that fact from the end-user for an uninterrupted
experience.

README: Reword the introduction

---

model/src/main/kotlin/licenses/LicenseView.kt

To hint that we do not expect and duplicates here.

LicenseView: Take sets of license sources instead of lists

---

.gitattributes
gradle.properties
model/src/main/kotlin/licenses/LicenseView.kt
model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
reporter/build.gradle.kts
reporter/src/funTest/assets/notice-template-reporter-expected-results
reporter/src/funTest/kotlin/reporters/NoticeTemplateReporterTest.kt
reporter/src/main/kotlin/reporters/NoticeByPackageReporter.kt
reporter/src/main/kotlin/reporters/NoticeTemplateReporter.kt
reporter/src/main/resources/META-INF/services/org.ossreviewtoolkit.reporter.Reporter
reporter/src/main/resources/template.notice/default.ftlh

Add a notice reporter that generates a notice file using Apache
Freemarker [1] templates. Templates can be provided by ORT or by the
user. This commit adds a default template that resembles the
`NoticeByPackageReporter` without handling of archived license files
which will be added in a later commit. Another template that resembles
the `NoticeSummaryReporter` will also be added in a later commit.
This notice reporter makes use of the `LicenseInfoResolver` which in
combination with the logic that can be implemented in the templates
makes the notice pre processing script obsolete. The reporter will
replace the other two notice reporters once the implementation is
complete.
Apache Freemarker was chosen because it has a large userbase, detailed
documentation, and good support for rendering …

Add a template based notice reporter

---

reporter/src/funTest/assets/gitlab-license-model-test-expected-output.json
reporter/src/funTest/assets/gitlab-license-model-test-skip-excluded-expected-output.json
reporter/src/main/kotlin/gitlab/GitLabLicenseModel.kt
reporter/src/main/kotlin/gitlab/GitLabLicenseModelMapper.kt

This change updates the key "package_manger" to "package_manager" in the GitLab license scanning report.

Fix typo in GitLab license_scanning report fixture.

---

utils/src/main/kotlin/ArchiveUtils.kt

This is not needed anymore as of 79377bc.

ArchiveUtils: Remove the POM "fake archive" type

---

model/src/main/kotlin/licenses/LicenseView.kt
model/src/main/kotlin/licenses/ResolvedLicenseFileInfo.kt
model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
reporter/src/funTest/assets/notice-template-reporter-expected-results-with-license-files
reporter/src/funTest/kotlin/reporters/NoticeTemplateReporterTest.kt
reporter/src/main/kotlin/reporters/NoticeTemplateReporter.kt
reporter/src/main/resources/template.notice/default.ftlh

NoticeTemplateReporter: Add license file handling to default template
Add the content of archived license files of packages to the default
template, similar to how they are used in the `NoticeByPackageReporter`.
Licenses that are contained in a license file are not listed again.
All copyright findings associated to licenses detected in a license file
are listed below the content of the file.

NoticeTemplateReporter: Handle license files

---

spdx-utils/src/main/resources/simple-license-mapping.yml

As found in
https://repo1.maven.org/maven2/com/sksamuel/exts/exts_2.13/1.61.1/exts_2.13-1.61.1.pom.

simple-license-mapping: Add an entry for "Apache2.0"

---

analyzer/src/main/kotlin/managers/Pip.kt

Pip: Add a work-around for projects that use classifiers as licenses

---

docs/config-file-curations-yml.md
downloader/src/main/kotlin/Downloader.kt
evaluator/src/main/kotlin/PackageRule.kt
examples/curations.yml
model/src/main/kotlin/Package.kt
model/src/main/kotlin/PackageCurationData.kt
model/src/test/kotlin/PackageCurationTest.kt
scanner/src/main/kotlin/LocalScanner.kt

Packages which are just meta data do not have any source code attached and thus nothing needs to be scanned or downloaded.
Also some evaluator rules may want to skip such packages. 
Thus introduce a corresponding flag and allow setting it via a package curation. Skip such packages in the downloader and scanner and provide a rule matcher to allow conditionally skipping such packages also in the evaluator rules.
A following PR will add logic for automatically set the flag for Maven BOM files.
#2897

Introduce meta data only packages

---

downloader/src/funTest/kotlin/vcs/MercurialWorkingTreeTest.kt
downloader/src/test/kotlin/VcsHostTest.kt

As Bitbucket stopped hosting Mercurial in favor of only Git, see
https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket.

VcsHostTest: Stop using Mercurial repos from Bitbucket

---

analyzer/src/main/kotlin/PackageManager.kt
build.gradle.kts
cli/src/main/kotlin/commands/ReporterCommand.kt
reporter/src/main/kotlin/reporters/EvaluatedModelReporter.kt
utils/src/main/kotlin/Utils.kt

On our infrastructure the analyzer currently fails consistently with the
below error for unknown reason. Switching to the non-experimental API
fixes that issue.
Exception in thread "main" java.lang.NoSuchMethodError: 'double kotlin.time.TimeMark.elapsedNow()'
at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:318)
at org.ossreviewtoolkit.analyzer.Analyzer$analyzeInParallel$$inlined$use$lambda$1$1$1.invokeSuspend(Analyzer.kt:143)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.jav …

PackageManager: Stop using the experimental time API

---

spdx-utils/src/main/resources/declared-license-mapping.yml

declared-license-mapping: Fix-up a broken license identifier

---

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-library-expected-output-app.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-library-expected-output-lib.yml
analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-app.yml
analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-lib.yml
analyzer/src/main/kotlin/managers/utils/MavenSupport.kt

To eliminate download and scan issues related to these packages (which
do not have any corresponding source code). Note that "pom" packaging
may be used e.g. for parent-, aggregation- or BOM packages.
Fixes #2897 .

MavenSupport: Treat packages with "pom" packaging as meta data only

---

analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/managers/Npm.kt
cli/src/main/kotlin/commands/DownloaderCommand.kt
downloader/src/main/kotlin/Downloader.kt
downloader/src/main/kotlin/VcsHost.kt
model/src/main/kotlin/VcsInfo.kt
model/src/main/kotlin/VcsType.kt
model/src/test/kotlin/PackageCurationTest.kt
model/src/test/kotlin/VcsInfoTest.kt

We actually use this to describe an unknown VCS, not necessarily only
URLs that point to no VCS at all.
Also compare to the HashAlgorithm semantics, where we have both NONE and
UNKNOWN.

Rename VcsType.NONE to VcsType.UNKNOWN

---

downloader/src/funTest/kotlin/vcs/MercurialDownloadTest.kt

As Bitbucket stopped hosting Mercurial. While at it, also fix expected
files to be just strings.

MercurialDownloadTest: Replace Bitbucket with another Mercurial host

---

cli/src/funTest/kotlin/ExamplesTest.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
docs/getting-started.md
docs/how-to-fix-text-provider-kts.md
examples/how-to-fix-text-provider.kts
reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/funTest/kotlin/reporters/StaticHtmlReporterTest.kt
reporter/src/main/kotlin/HowToFixTextProvider.kt
reporter/src/main/kotlin/ReporterInput.kt
reporter/src/main/kotlin/reporters/ExcelReporter.kt
reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
reporter/src/main/kotlin/utils/ReportTableModel.kt
reporter/src/main/kotlin/utils/ReportTableModelMapper.kt

Add a (reporter) command line option to inject custom how-to-fix Markdown texts for OrtIssues from within a Kotlin Script.
Display these injected how-to-fix texts in the `static HTML report` to show that it works.
The integration into the `WebApp` is going to be done in a following PR.
See also: #2347.

reporter: Implement custom how-to-fix texts for `OrtIssue`s

---

reporter-web-app/src/components/IssuesTable.js
reporter-web-app/src/models/WebAppOrtIssue.js
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
reporter/src/funTest/kotlin/reporters/EvaluatedModelReporterTest.kt
reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
reporter/src/main/kotlin/model/EvaluatedOrtIssue.kt

This PR follows up on #2966 by handling the `HowToFixTextProvider` in the `evaluated model` and in the `WebApp`.
Fixes #2347.

WebApp: Display the custom how-to-fix messages

---

downloader/src/test/kotlin/VcsHostTest.kt

GitHub is tolerant about "blob" vs. "tree" in the URL, but this is more
correct.

VcsHostTest: Use a proper "blob" GitHub URL for a file

---

reporter/src/main/kotlin/reporters/AmazonOssAttributionBuilderReporter.kt

AmazonOssAttributionBuilderReporter: Migrate to the new license API

---

helper-cli/src/main/kotlin/commands/GeneratePackageConfigurationsCommand.kt
model/src/main/kotlin/Identifier.kt
utils/src/main/kotlin/Extensions.kt

This supports organizing the files in a hierarchical directory structure
using each package identifier component as path element.

GeneratePackageConfigurationCommand: Create hierarchical dirs optionally

---

helper-cli/src/main/kotlin/commands/ExportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/commands/ExportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/ExtractRepositoryConfigurationCommand.kt
helper-cli/src/main/kotlin/commands/FormatRepositoryConfigurationCommand.kt
helper-cli/src/main/kotlin/commands/GenerateProjectExcludesCommand.kt
helper-cli/src/main/kotlin/commands/GenerateRuleViolationResolutionsCommand.kt
helper-cli/src/main/kotlin/commands/GenerateScopeExcludesCommand.kt
helper-cli/src/main/kotlin/commands/GenerateTimeoutErrorResolutionsCommand.kt
helper-cli/src/main/kotlin/commands/ImportCopyrightGarbageCommand.kt
helper-cli/src/main/kotlin/commands/ImportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/commands/ImportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/ListCopyrightsCommand.kt
helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
helper-cli/src/main/kotlin/commands/ListPackagesCommand.kt
helper-cli/src/main/kotlin/commands/ListStoredScanResultsCommand.kt
helper-cli/src/main/kotlin/commands/MapCopyrightsCommand.kt
helper-cli/src/main/kotlin/commands/MergeRepositoryConfigurationsCommand.kt
helper-cli/src/main/kotlin/commands/RemoveConfigurationEntriesCommand.kt
helper-cli/src/main/kotlin/commands/SortRepositoryConfigurationCommand.kt
helper-cli/src/main/kotlin/commands/VerifySourceArtifactCurationsCommand.kt

String.expandTilde() does not make the returned path absolute if it does
not contain a tilde. Ensure that all File options are absolute paths by
performing a conversion to absolute paths, and also a normalization while
at it.
See also f470815.

helper-cli: Fix using absolute paths for File options

---

cli/src/main/kotlin/OrtMain.kt
cli/src/main/kotlin/commands/UploadCurationsCommand.kt

ORT's sub-command aim to be / start with verbs, so rename the command
accordingly. Also generalize the name as curations might get uploaded to
other providers using the same sub-command in the future.

cli: Rename the command to upload curations to ClearlyDefined

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/SubtractScanResultsCommand.kt

Upgrading a scanner in ORT usually requires investigating the
effect of that upgrade on the scan results. Thus, provide a diff command
in order to reduce the manual efforts.

helper-cli: Add a command to subtract two scan results

---

analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml
analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt

"NuGet" is the official spelling, and it was already used as the
Identifier type for projects, so it makes sense to use that spelling
also for packages where the type describes the provider.
Note that the GitLabLicenseModelMapper prematurely already used the
"NuGet" spelling in toPackageManagerName(), which becomes correct with
this change.

Change the "nuget" package provider name to "NuGet"

---

cli/src/funTest/kotlin/ExamplesTest.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
reporter/src/main/kotlin/HowToFixTextProvider.kt

In order to allow the processing of that OrtResult.

HowToFixTextProvider: Pass the OrtResult to the Kotlin script

---

analyzer/src/funTest/assets/projects/synthetic/cargo-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/cargo-subcrate-client-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/cargo-subcrate-lib-expected-output.yml
analyzer/src/main/kotlin/managers/Cargo.kt

`cargo` supports arbitrary formats to specify multiple licenses, but `/` should be interpreted as `OR`.
It looks like the consensus is that crates.io should [only accept SPDX 2.1 license expressions](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields), but this is not the reality for all crates as it's not validated.
Related issue in cargo: https://github.com/rust-lang/cargo/issues/2039

Replace / by OR in the license field of Rust crates

---

README.md

It was merged in https://github.com/oss-review-toolkit/ort/pull/2838.

README: Add the SPDX document based analyzer

---

build.gradle.kts
gradle.properties

See https://github.com/Kotlin/dokka/releases/tag/1.4.0. Do not get
confused by the bogus "Alpha" in the title on that page.

Gradle: Upgrade dokka to version 1.4.0 (final)

---

analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml
analyzer/src/funTest/kotlin/managers/DotNetTest.kt
analyzer/src/funTest/kotlin/managers/NuGetTest.kt
analyzer/src/main/kotlin/managers/DotNet.kt
analyzer/src/main/kotlin/managers/NuGet.kt
analyzer/src/main/kotlin/managers/utils/NuGetAllPackageData.kt
analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
utils/build.gradle.kts
utils/src/main/kotlin/OkHttpClientHelper.kt

This rewrites NuGetSupport which an emphasis on speed and
maintainability:
- Use data classes for deserialization to increase readability.
- Use the service index to dynamically get the best registration base URL.
- Use URL types that support GZIP compression.
- Fix package names to always be lower-case to avoid unnecessary package
searches.
- Get independent URLs in parallel using coroutines.

analyzer: Rewrite NuGetSupport

---

spdx-utils/src/main/resources/declared-license-mapping.yml

Note that, as discussed [here](https://github.com/oss-review-toolkit/ort/pull/2938#discussion_r473835224), we should in future avoid adding non-version specific mapping to this file to avoid relicensings of a projects go unnoticed with version major changes.

Add several NuGet-realted mappings for declared licenses

---

reporter/src/main/kotlin/reporters/NoticeTemplateReporter.kt

Extract the part that merges a list of resolved licenses from the
existing `mergeLicenses()` function into a separate function, because
this function can also be useful in templates.

NoticeTemplateReporter: Add a helper function for merging licenses

---

docs/config-file-curations-yml.md
examples/curations.yml
model/src/main/kotlin/CuratedPackage.kt
model/src/main/kotlin/PackageCurationData.kt
model/src/test/kotlin/PackageCurationTest.kt
utils/src/main/kotlin/DeclaredLicenseProcessor.kt
utils/src/test/kotlin/DeclaredLicenseProcessorTest.kt

I decided for making the entries additive, so that multiple declared license mapping curations can be applied to
any packages, and the entries are added. They override only if the keys equal. This approach is a good basis for enabling the curation of declared license mappings on broader scopes, e.g. by introducing wildcards to the identifier matching of curations.
See the individual commits for the details.
Fixes #2898.

Allow defining custom declared license mappings via package curations

---

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt
spdx-utils/src/main/resources/declared-license-mapping.yml
utils/src/main/kotlin/DeclaredLicenseProcessor.kt
utils/src/test/kotlin/DeclaredLicenseProcessorTest.kt

Some declared license entries are just invalid, like e.g. if a copyright statement is used as declared license, and should be just discarded. This PR enables discarding such entries by mapping the declared license to (SPDX) "NONE", either
- via a declared license curation
- or via ORT's internal `declared license mapping` data
The entry for the `delcared_license_processed` contains e.g. "Copyright a,b,c" -> "NONE" in case a license was discarded with that new mechanism.
This improves on #2898 .

Allow discarding declared licenses

---

reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/funTest/assets/static-html-reporter-test-input.yml
reporter/src/main/kotlin/utils/ReportTableModelMapper.kt

The changes prepare for the removal of `OrtResult.data`. 
Please see the individual commit messages.

(StaticHtml|Excel)Reporter: Use `labels` instead of `data` for the metadata section

---

model/src/test/kotlin/PackageCurationTest.kt

PackageCurationTest: Align on using with() for grouping assertions

---

spdx-utils/src/main/resources/declared-license-mapping.yml

Found in [1].
[1]: https://github.com/jnr/jnr-posix/blob/jnr-posix-3.0.61/pom.xml#L32

Add a declared license mapping for "Eclipse Public License - v 2.0"

---

evaluator/src/test/kotlin/TestData.kt
model/src/main/kotlin/config/PathExcludeReason.kt
model/src/test/kotlin/licenses/TestData.kt

Since TEST_OF should be used instead.

PathExcludeReason: Deprecate TEST_TOOL_OF

---

spdx-utils/src/main/resources/declared-license-mapping.yml

Found in [1].
[1]: https://github.com/vy/flatbuffers/blob/600952fca1c5a7ca8c3c1ce4530116191f78530b/pom.xml#L17

Add a declared license mapping for "Apache License (v2.0)"

---

cli/src/main/kotlin/commands/EvaluatorCommand.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/utils/OrtResultExtensions.kt
reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/funTest/assets/static-html-reporter-test-input.yml
reporter/src/main/kotlin/reporters/ExcelReporter.kt
reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
reporter/src/main/kotlin/utils/ReportTableModel.kt
reporter/src/main/kotlin/utils/ReportTableModelMapper.kt
reporter/src/main/resources/static-html-reporter.css
scanner/src/main/kotlin/Scanner.kt

Remove the `data`  property from `OrtResult`, because the `labels` property should now be used for custom data.

Remove custom data

---

build.gradle.kts
gradle.properties

See https://github.com/detekt/detekt/releases/tag/v1.13.1.

Gradle: Upgrade detekt to version 1.13.1

---

.azure-pipelines/WindowsTest.yml

The "WindowsTest" job often fails with `OutOfMemoryError`s. Disable
parallel builds to reduce memory usage by running only one test task at
once.

Azure: Disable parallel builds for the Windows test job

---

model/src/main/kotlin/LicenseFindings.kt

The code using the typealias and the functions has been migrated to use
the `ResolvedLicenseInfo` instead.

model: Remove the LicenseFindingsMap typealias and related functions

---

downloader/src/main/kotlin/vcs/Git.kt
downloader/src/main/kotlin/vcs/Mercurial.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
reporter/src/funTest/kotlin/reporters/NoticeTemplateReporterTest.kt
utils/src/main/kotlin/FileMatcher.kt
utils/src/main/kotlin/LicenseFilenamePatterns.kt
utils/src/main/kotlin/Utils.kt
utils/src/main/kotlin/storage/FileArchiver.kt
utils/src/test/kotlin/LicenseFilenamePatternsTest.kt

In order to adjust the so called root license heuristic to consider also files which are not direct children of the root directory [1], the sparse checkout needs to checkout these files in the first place. This is what this PR is about.
[1] #3054

Broaden the license file matching for sparse checkouts

---

gradle.properties
utils/build.gradle.kts
utils/src/main/kotlin/FileMatcher.kt
utils/src/main/kotlin/storage/FileArchiver.kt
utils/src/test/kotlin/FileMatcherTest.kt

The `java.nio.file.PathMatcher` we used previously is incapable of
- matching `case-insensitive` (which is nice to have for matching license files)
- matching zero or many leading directories with `**/LICENSE` (which does not match `LICENSE`)
So use Springs' `AntPathMatcher` in order to eliminate these limitations, so that the patterns become compatible with
the patterns used for Git's and Mercurial's sparse checkouts.
As consequence the patterns can be shared between `FileArchiver` and the mentioned sparse checkouts in context of #3054.

FileMatcher: Use Springs' instead of Java's PathMatcher

---

Jenkinsfile

Since da9fcae all global configuration files have default locations, so
use them implicitly here instead of explicitly using example files.

Jenkinsfile: Use default instead of example evaluator configurations

---

utils/src/main/kotlin/FileMatcher.kt
utils/src/main/kotlin/LicenseFilenamePatterns.kt
utils/src/main/kotlin/storage/FileArchiver.kt
utils/src/test/kotlin/storage/FileArchiverTest.kt

To enable re-use of the archives, independent of any VCS path or project path.
This aligns with the planned nicely with the planned`scan by repository` / `sparse-checkout removal` refactoring, which aims at re-using cached scan results independently of the mentioned paths. Apart from that make the file matching case-insensitive to align with the broadened matching of the sparse-checkouts.
Note that the "readme*" files cannot be archived yet, since these would end-up in the notices.
This PR is done in the context of #3054, e.g. picking so called root license files from potentially any location.

FileArchiver: Archive all candidate license files, no matter of their file location

---

cli/src/main/kotlin/commands/ReporterCommand.kt
cli/src/main/kotlin/commands/UploadResultCommand.kt

Use the `GlobalOptions` in the `ReporterCommand` and
`UploadResultCommand`. Otherwise these command fail with a
`NullPointerException`.
This is a fixup for 5f7ebe5.

cli: Fix reading the configuration from GlobalOptions

---

gradle.properties

Note that, contrary to stated in 20729b0, all dokka version supporting
Kotlin 1.4 are still considered "alpha", also see
https://github.com/Kotlin/dokka/issues/1434#issuecomment-687050994

Gradle: Upgrade dokka to version 1.4.10

---

cli/src/main/kotlin/commands/ScannerCommand.kt

"config" is a better name, because the type is `OrtConfiguration`, not
`ScannerConfiguration`.

ScannerCommand: Rename a variable

---

README.md
analyzer/build.gradle.kts
analyzer/src/funTest/assets/projects/synthetic/carthage-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/carthage/Cartfile.resolved
analyzer/src/funTest/assets/projects/synthetic/carthage/binaryspec.json
analyzer/src/funTest/kotlin/managers/CarthageFunTest.kt
analyzer/src/main/kotlin/managers/Carthage.kt
analyzer/src/main/resources/META-INF/services/org.ossreviewtoolkit.analyzer.PackageManagerFactory
analyzer/src/test/assets/carthage/Cartfile-binary.resolved
analyzer/src/test/assets/carthage/Cartfile-faulty.resolved
analyzer/src/test/assets/carthage/Cartfile-generic-git.resolved
analyzer/src/test/assets/carthage/Cartfile-github.resolved
analyzer/src/test/assets/carthage/Cartfile-mixed.resolved
analyzer/src/test/assets/carthage/Carthage-binary-specification.json
analyzer/src/test/kotlin/PackageManagerTest.kt
analyzer/src/test/kotlin/managers/CarthageTest.kt
downloader/src/main/kotlin/VcsHost.kt
downloader/src/test/kotlin/VcsHostTest.kt

Carthage is a package manager for Cocoa applications.
See: https://github.com/Carthage/Carthage
The implementation supports 3 types of dependencies:
* github: Dependencies specified by the Github user and project name.
* git: Generic git dependencies from any git service.
* binary: Dependencies that are only available as compiled binaries.
See: https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-only-frameworks
Resolves #725
An example Cartfile can be found here: https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#example-cartfile

analyzer: Add Carthage package manager

---

analyzer/src/funTest/assets/projects/synthetic/carthage-expected-output.yml
analyzer/src/main/kotlin/managers/Carthage.kt

When using a VcsHost unknown to ORT the project name and revision are not set.
This PR fixes this by using the working dir's name as a fallback and not relying on the `resolvedRevision`

Carthage: Add missing project info for unknown VcsHost

---

model/src/main/kotlin/ScanResult.kt
model/src/main/kotlin/utils/RootLicenseMatcher.kt
model/src/test/kotlin/RootLicenseMatcherTest.kt
utils/src/main/kotlin/LicenseFilenamePatterns.kt
utils/src/main/kotlin/Utils.kt
utils/src/main/kotlin/storage/FileArchiver.kt
utils/src/test/kotlin/LicenseFilenamePatternsTest.kt
utils/src/test/kotlin/UtilsTest.kt

This PR implements a new hierarchical heuristic based on a two pass recursive search upwards the directory tree for finding files matching a given pattern. That new heuristic is taken into use for `ScanResult.filterPath()`.
The heuristic needs to be also integrated with the `FindingsMatcher`, which is left for a following PR.
See also #3054.

Add a hierarchical heuristic for determining the root license files

---

scanner/src/main/kotlin/scanners/ScanCode.kt

Let's get the big upgrade done now and then make the minor migration from this pre-release to the final release later on.

Upgrade ScanCode to version 3.2.1rc2

---

spdx-utils/src/main/resources/declared-license-mapping.yml

[1] https://github.com/python-trio/async_generator/blob/master/setup.py#L16

declared-license-mapping: Add 'MIT -or- Apache License 2.0'

---

scanner/src/main/kotlin/scanners/ScanCode.kt

Make ScanCode.bootstrap() return the correct directory again. Also
adjust ScanCode.getVersion() to make the Semver based requirements check
pass again.
This is a fix-up for fff03db.

ScanCode: Fix-up the broken bootstrapping

---

scanner/src/main/kotlin/LocalScanner.kt

Call the `getVersion()` implementation of the actual class as opposed to
the super class, so that an override of that function takes effect. In
particular call the implementation done in 7406b3a is now called.
The scanner version put into the scanner details were missing the hyphen
as of fff03db. When such scan result is read from the storage it causes
a Semver exception. This change fixes that problem.

LocalScanner: Put the proper ScanCode version into ScannerDetails

---

downloader/src/main/kotlin/Downloader.kt
model/src/main/kotlin/Provenance.kt

Trivially align the wording of using 'sourceArtifact' vs 'vcsInfo'

---

model/src/main/kotlin/utils/FindingsMatcher.kt
model/src/test/kotlin/RootLicenseMatcherTest.kt
model/src/test/kotlin/utils/FindingsMatcherTest.kt
utils/src/main/kotlin/FileMatcher.kt
utils/src/test/kotlin/FileMatcherTest.kt

To make use of the new hierarchical heuristic for determining which files are root license files, as we call them.
Fixes #3054.

FindingsMatcher: Migrate to the RootLicenseMatcher

---

spdx-utils/src/main/resources/declared-license-mapping.yml

When a license rule for 'edl-1.0' is triggered in ScanCode (3.2.1rc2), it
does not report 'edl-1.0' as detected license but 'bsd-new'. This is
because 'edl-1.0' is internally mapped due to the mapping entry defined
in [1]. Since 'bsd-new' has 'BSD-3-Clause' set as 'spdx_license_key' [2],
ORT uses that SPDX license ID. Furthermore ORT's license text import task
[3] won't generate a license text resource for 'bsd-new', and thus
mapping the entry to 'LicenseRef-scancode-bsd-new' is not an option.
Mapping "EDL 1.0" to "BSD-3-Clause" anyhow aligns best with ScanCode and
with how ORT integrates ScanCode.
[1] https://github.com/nexB/scancode-toolkit/blob/v3.2.1rc2/src/licensedcode/data/rules/edl-1.0.yml
[2] https://github.com/nexB/scancode-toolkit/blob/v3.2.1rc2/src/licensedcode/data/licenses/bsd …

declared-license-mapping: Adjust the entry for "EDL 1.0"

---

Dockerfile

Dockerfile: Configure ScanCode to use Python 3 even if Python 2 is installed

---

spdx-utils/src/main/resources/declared-license-mapping.yml

As found in [1], see also [2][3].
[1] https://repo.maven.apache.org/maven2/org/jdom/jdom/1.1.3/jdom-1.1.3.pom
[2] https://github.com/nexB/scancode-toolkit/blob/v3.2.1rc2/src/licensedcode/data/licenses/jdom.LICENSE
[3] https://github.com/nexB/scancode-toolkit/blob/v3.2.1rc2/src/licensedcode/data/licenses/jdom.yml

declared-license-mapping: Add an entry for the JDOM license

---

.travis.yml

Markdown files are not checked by our regular Gradle build, so there is
no value in triggering it. Instead, rely on the Markdown links check run
by GitHub actions.
If this works as expected we can apply the same logic to other CI runs,
like AppVeyor.

Travis: Skip CI runs if only Markdown files are modified

---

.appveyor.yml

Analog to Travis in 52f5e7a. Also see
https://www.appveyor.com/docs/how-to/filtering-commits/#commit-files-github-and-bitbucket-only

AppVeyor: Skip CI runs if only Markdown files are modified

---

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
cli/src/main/kotlin/commands/UploadCurationsCommand.kt
model/src/main/kotlin/utils/Extensions.kt
scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt

Stop requiring to be able to map any ORT Identifier to a ClearlyDefined
type and provider, as e.g. any Identifier originating from the
SpdxDocumentFile "package manager" simply is not mappable. Make
Identifier.toClearlyDefinedTypeAndProvider() nullable instead and handle
that case in the callers in the respective proper ways.

Rework mapping of Identifiers to ClearlyDefined

---

analyzer/src/main/kotlin/managers/Npm.kt

While it is correct that for *published* NPM packages the name and
version are required [1], a user may want to run the analyzer on local
source code of an unpublished NPM package, in which case both name and
version are optional, so simply use an empty string in that case.
[1] https://docs.npmjs.com/files/package.json#version

Npm: Do not throw a NullPointerException for missing name or version

---

analyzer/src/main/kotlin/managers/GoMod.kt
analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
cli/src/main/kotlin/commands/EvaluatorCommand.kt
cli/src/main/kotlin/commands/ScannerCommand.kt
helper-cli/src/main/kotlin/commands/GenerateTimeoutErrorResolutionsCommand.kt
helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
helper-cli/src/main/kotlin/common/Utils.kt
model/src/main/kotlin/ScanResult.kt
model/src/main/kotlin/licenses/LicenseView.kt
model/src/main/kotlin/utils/FindingsMatcher.kt
reporter/src/main/kotlin/reporters/SpdxDocumentReporter.kt
reporter/src/main/kotlin/utils/ReportTableModelMapper.kt
reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt
scanner/src/test/kotlin/scanners/ScanCodeResultParserTest.kt
utils/src/main/kotlin/DeclaredLicenseProcessor.kt

The `distinct` function converts a collection first to a set to
eliminate duplicate entries, and then to a list. Therefore use
`distinct` only if the `List` type is required, otherwise use `toSet` to
avoid the duplicate conversion. Note that both functions preserve the 
iteration order.

Use `distinct` only if a list is required

---

build.gradle.kts
cli/build.gradle.kts
test-utils/build.gradle.kts

Since Gradle version 6 the correct platform for multi-platform
dependencies will automatically be picked. Also see
https://github.com/kotest/kotest/issues/279#issuecomment-705213677

Gradle: Omit the "-jvm" suffix for kotest dependencies

---

.reuse/dep5
mlc_config.json

As https://source.android.com/setup/develop/repo continues to trigger
false positives.
Also see https://github.com/tcort/markdown-link-check#config-file-format.

Ignore android.com in Markdown link checks

---

analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/dotnet/nuget.config
analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/nuget/nuget.config
analyzer/src/main/kotlin/managers/DotNet.kt
analyzer/src/main/kotlin/managers/NuGet.kt
analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
analyzer/src/test/kotlin/managers/utils/NuGetSupportTest.kt
utils/src/main/kotlin/Extensions.kt
utils/src/test/kotlin/ExtensionsTest.kt

Use the NuGet.config file to get the configured indices for the analyzed
project and support package sources other than the default `api.nuget.org`.
Resolves #2189
This might not work for all service indices, as some do not provide valid catalogEntries.
e.g. [The service for windows terminal dependencies](https://pkgs.dev.azure.com/ms/terminal/_packaging/TerminalDependencies/nuget/v3/index.json) links to [this Package Data](https://pkgs.dev.azure.com/ms/20953fb4-d427-4ad6-b78c-13142d0c5462/_packaging/64e3bf16-3e04-41cd-b90f-60fdc9ccf494/nuget/v3/registrations2-semver2/terminal.themehelpers/0.2.200324001.json) which does not contain a valid catalogEntry URL

NuGet: Support multiple configured NuGet indices

---

Dockerfile

This PR upgrades Node.js to the latest LTS version 12.
Used the PPA installation method because adoptopenjdk:11-jre-hotspot-focal is not available, yet (and would only offer nodejs version 10 anyways)
Resolves #3189.

Docker: Upgrade Node.js to version 12

---

reporter-web-app/build.gradle.kts

This reverts commit ed604e3 because not our version of Kotlin counts,
but the version of Kotlin embedded into Gradle (or its kotlin-dsl
plugin), which still is Kotlin 1.3.72 for Gradle 6.6.1 (and 6.7).
Gradle will switch to Kotlin 1.4 only in version 6.8, see
https://github.com/gradle/gradle/issues/12660.

Revert "reporter-web-app: Make some Kotlin 1.4 related improvements"

---

README.md

With the support of multiple scan storage backends the format of the
ORT configuration file has changed. Update the documentation in
README.md to reflect these changes. Also list the new ClearlyDefined
storage.
Resolves #3194.
Signed-off-by: Oliver Heger <oliver.heger@bosch.io>

Update documentation for scanner storage backends

---

analyzer/src/funTest/assets/projects/synthetic/carthage-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/glide-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/godep-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/godeps-expected-output.yml
analyzer/src/funTest/kotlin/managers/CarthageFunTest.kt
analyzer/src/funTest/kotlin/managers/GoDepFunTest.kt

Otherwise a.g. Travis CI enabled on forks of ORT fails, see
https://travis-ci.com/github/bosch-io/oss-review-toolkit/builds/189639710#L1245
https://travis-ci.com/github/bosch-io/oss-review-toolkit/builds/189639710#L1598

analyzer: Make CarthageFunTest and GoDepFunTest pass on forks of ORT

---

README.md

Link ORT configuration file docs from storage docs

---

.appveyor.yml
.travis.yml

Fix skipping the AppVeyor build if only *.md files were modified

---

utils/src/main/kotlin/OrtProxySelector.kt

The authority contains the port, but a no_proxy entry might not, so also
compare by only the host.

OrtProxySelector: Support no_proxy entries without a port

---

downloader/src/main/kotlin/VersionControlSystem.kt

In Git repositories it is possible to have a git tag and a remote branch
sharing the same name, see e.g. the 'release-9.0' tag or branch in
https://github.com/apache/flink-shaded/.
In this case the Downloader is not able to determine a revision to
download in case the meta data of the package has the revision set to
the tag name and when moving revisions are not enabled. Fix this by
returning true in that case.

VersionControlSystem: Fix an issue with isFixedRevision()

---

cli/src/main/kotlin/commands/EvaluatorCommand.kt
evaluator/src/main/kotlin/Evaluator.kt
utils/src/main/kotlin/ScriptRunner.kt

Improve checking the syntax for evaluator scripts

---

Dockerfile

The Ubuntu base image sometimes removes older Pip versions in favor of
newer ones, which breaks our Docker image build. As we anyway install
our wanted version of Pip in a VirtualEnv [1], we can omit the version
requirement for the global Pip version. Also running "ort requirements"
confirms that ORT "Requires 'pip' in no specific version".
[1] https://github.com/oss-review-toolkit/ort/blob/199c0f495800e3b31cc1c44395e20f32d49f9ad0/analyzer/src/main/kotlin/managers/Pip.kt#L498-L509
Resolves #3232.

Dockerfile: Stop depending on a fixed Pip version

---

scanner/src/main/kotlin/LocalScanner.kt

In other similar output we use "of", and " of " is easier to search for
in logs than "/", so align on using "of".

LocalScanner: Align on using "of" instead of "/" in indices

---

README.md

As agreed in the TSC meeting from 2020-10-23 [1] that functionality will
be part of the reporter.
[1] https://github.com/oss-review-toolkit/ort-governance/pull/12

README: Remove the mention of a planned Documenter

---

analyzer/src/funTest/assets/projects/external/directories-expected-output.yml
analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
cli/src/main/kotlin/OrtMain.kt
model/src/main/kotlin/Environment.kt
model/src/test/kotlin/OrtResultTest.kt
reporter/src/funTest/assets/gradle-all-dependencies-result.yml
scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
test-utils/build.gradle.kts
test-utils/src/main/kotlin/Utils.kt

This is useful to debug memory issues and to learn how much CPUs a local
scanner like ScanCode would be using.

OrtMain: Show CPU and memory info in the header

---

cli/src/main/kotlin/OrtMain.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
cli/src/main/kotlin/commands/DownloaderCommand.kt
cli/src/main/kotlin/commands/EvaluatorCommand.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
cli/src/main/kotlin/commands/ScannerCommand.kt
cli/src/main/kotlin/commands/UploadResultCommand.kt
integrations/Jenkinsfile
scanner/src/main/kotlin/Scanner.kt
utils/src/main/kotlin/Extensions.kt
utils/src/main/kotlin/Logger.kt

Add a log level for performance logging and use it initially for logging (de-)serialization durations.

Introduce performance logging

---

utils/src/main/kotlin/Extensions.kt

This way also the 1024 constant does not explicitly need to be a double
as the number is already converted to double.

Extensions: Generalize bytesToMiB() to work an Numbers

---

README.md
utils/src/main/kotlin/OrtAuthenticator.kt

OrtAuthenticator: Support generic credentials passed as environment variables

---

model/src/main/kotlin/ScanResult.kt
scanner/src/main/kotlin/LocalScanner.kt

The filtering was accidentally applied only to projects.

Scanner: Filter out not applicable license files for packages

---

spdx-utils/src/main/resources/declared-license-mapping.yml

declared-license-mapping: Strip a trailing white space in a declared license
This entry was originally added in b3595cd for a Maven package, but since
a49dbba we strip declared licenses coming from Maven, so also strip the
lookup key in the mapping.
A future change will ensure that we consistently do trimming of declared
licenses for all package managers.

declared-license-mapping: Strip a trailing white space

---

cli/src/main/kotlin/OrtMain.kt

The help text of the -P command line option contains an example of a
configuration property that is overridden on the command line.
However, the path of this property is outdated. This fix corrects the
example by setting a valid property path.
Signed-off-by: Oliver Heger <oliver.heger@bosch.io>

Fix a wrong property reference in the help text of the -P option

---

README.md
model/src/test/kotlin/config/OrtConfigurationTest.kt

Issue #3242 is about supporting environment variables in configuration files.
Actually, the Hoplite configuration library already supports a way how to do this. This PR adds a test case to demonstrate this and updates the description of the main ORT configuration file in README.md. There are no functional changes.

ORT config: Documentation update about supporting environment variables

---

README.md
model/src/test/kotlin/config/OrtConfigurationTest.kt

As described in the  [hoplite ReadMe](https://github.com/sksamuel/hoplite#property-sources), environment variables are loaded by default. Furthermore, environment variables have the highest priority which is hard-coded at [at this place](https://github.com/sksamuel/hoplite/blob/7b43bf7eddbbb2f16fd6eeb2287e1035bce4db07/hoplite-core/src/main/kotlin/com/sksamuel/hoplite/PropertySource.kt#L52-L57) and I could not find a simple workaround. The documentation has been updated accordingly.

Update test coverage and documentation for usage of environment variables as OrtConfiguration parameters

---

utils/src/main/kotlin/Utils.kt

When a VCS Url with a leading white space is passed to that function, it
runs into so fallback handling implemented inside the catch block for
the URISyntaxException. The result of normalizing [1] is [2] whereas
${CWD} is the current working directory.
On the one hand the input was just wrong and thus it doesn't need to be
handled, but on the other hand finding the root cause of this issue was
quite time consuming. Thus, add this fault tolerance to avoid such time
consuming investigation in the future.
[1] " https://github.com/oss-review-toolkit/ort.git"
[2] "file:///${CWD}%20https:/github.com/oss-review-toolkit/ort.git

Utils: Add some fault tolerance to normalizeVcsUr()

---

scanner/src/main/kotlin/LocalScanner.kt
scanner/src/main/kotlin/Scanner.kt

Since this leads to empty scan results as the VCS path points to the manifest.

Stop filtering scan results by VCS path for Git Repo

---

Dockerfile

After moving the clearly-defined client to a new "clients" directory in this PR
we started getting error in docker build. Root cause seems to be
gradle/gradle#4823 that is not fixed yet. This change is a workaround that
suitable for docker build in clouds where no gradle files being cached.
Workaround for local development is build with disabled configure-on-demand
option once. For all further build it could be enabled back.
Fixes #3306
Signed-off-by: zhernovs <ext-andriy.zhernovskyi@here.com>

Gradle: Disable the configure-on-demand option for docker build

---

downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt
spdx-utils/src/main/resources/declared-license-mapping.yml

[1] https://github.com/mapado/haversine/blob/9fe596116a3d2f13208953f4a0f7bc7225ae0ac9/setup.py#L18

declared-license-mapping: Add an entry for `MIT`

---

downloader/src/main/kotlin/vcs/Subversion.kt

Esp. when converting to URL / URI objects, this avoids exceptions as
decoded literal spaces are illegal characters in URLs / URIs and need to
be percent-escaped.

Subversion: Consistently use the encoded string for URLs / URIs

---

Dockerfile

Dockerfile: Switch building to a base image with Java 11

---

README.md
cli/src/funTest/kotlin/ExamplesFunTest.kt
docs/config-file-curations-yml.md
docs/config-file-licenses-yml.md
docs/config-file-package-configuration-yml.md
docs/config-file-resolutions-yml.md
docs/file-rules-kts.md
docs/getting-started.md
examples/license-classifications.yml
examples/rules.kts
utils/src/main/kotlin/Constants.kt

Rename the file from licenses.yml to license-classifications.yml. The
new name expresses the intention of this file better: to give the user
a possibility to group licenses into a customizable set of categories.
I hope I spotted all references to the file name, including the ones in the documentation. At least IntelliJ's "find in path" feature did not find any hits any more.

Rename license configuration file

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/ListLicenseCategoriesCommand.kt

Which enables viewing licenses category and also allows to easily
determine the categories for a license, in particular because the
output is easier grep-able compared to the YAML file.
Note: Using the term `category` for the `sets` contained in the license
configuration as it is planned to use that terminology consistently.

helper-cli: Add a command to show the license categories

---

.jitpack.yml
README.md
build.gradle.kts
downloader/src/main/kotlin/vcs/Subversion.kt
gradle.properties
utils/src/main/kotlin/OrtAuthenticator.kt

And to be able to use the requestPasswordAuthenticationInstance() method
from the Java Authenticator.
Fixes #3322.

Raise the Java requirement to 11 from 1.8 to be able to simplify code

---

scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt
scanner/src/main/kotlin/LocalScanner.kt
scanner/src/main/kotlin/ScanResultsStorage.kt
scanner/src/main/kotlin/ScannerCriteria.kt
scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
scanner/src/main/kotlin/storages/CompositeStorage.kt
scanner/src/main/kotlin/storages/NoStorage.kt
scanner/src/main/kotlin/storages/PostgresStorage.kt
scanner/src/test/kotlin/LocalScannerTest.kt
scanner/src/test/kotlin/ScannerCriteriaTest.kt
scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
scanner/src/test/kotlin/storages/CompositeStorageTest.kt

This PR is a first step towards making queries for results from ScanResultsStorage more flexible. The basic idea is that storages are not queried in terms of a ScannerDetails object, but using a ScannerCriteria object. This object allows specifying more advanced matching criteria, for instance a range for the scanner version. ScannerCriteria are created by scanner implementations; per default, they match the properties of their scanner very strictly, but users can override their criteria via the scanner configuration. That way it can be stated for instance that scan results produced by an older scanner version can be reused.
The existing ScanResultsStorage implementations have been adapted to support all the criteria currently available. For PostgresStorage, this even happens in the query …

Oheger bosch/scanner/#3247 scanner details compatibility

---

analyzer/src/main/kotlin/managers/utils/NuGetAllPackageData.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
helper-cli/src/main/kotlin/commands/SubtractScanResultsCommand.kt
model/src/test/kotlin/RootLicenseMatcherTest.kt

Trailing commas have their benefits [1], but using them inconsistenly
might be confusing as it can make the code look incomplete. So remove
our few (probably accidental) usages manually until we can suppress them
[2].
[1] https://kotlinlang.org/docs/reference/coding-conventions.html#trailing-commas
[2] https://github.com/detekt/detekt/issues/2398

Remove optional trailing commas from the code base

---

Dockerfile
gradle.properties

This is a more general follow-up fix to [1] so that also users with a
custom Dockerfile benefit from it.
[1] https://github.com/oss-review-toolkit/ort/pull/3302

Gradle: Generally disable configure-on-demand

---

Dockerfile

Unfortunately no release notes are available for the commandlinetools
package. Note that the folder that contains the sdkmanager was changed
from `tools/` to `cmdline-tools/`.

Dockerfile: Update the Android SDK to the latest version

---

README.md

To align with the other config sections where the tables comes directly
after the introducing paragraphs.

README: Move the main config table to directly after the first paragraph

---

cli/src/funTest/assets/semver4j-analyzer-result.yml
cli/src/funTest/kotlin/ExamplesFunTest.kt
docs/config-file-licenses-yml.md
examples/license-classifications.yml
examples/rules.kts
helper-cli/src/main/kotlin/commands/ListLicenseCategoriesCommand.kt
model/src/main/kotlin/licenses/License.kt
model/src/main/kotlin/licenses/LicenseCategory.kt
model/src/main/kotlin/licenses/LicenseConfiguration.kt
model/src/test/kotlin/licenses/LicenseConfigurationTest.kt
reporter/src/funTest/assets/notice-template-reporter-expected-results
reporter/src/funTest/assets/notice-template-reporter-expected-results-summary
reporter/src/funTest/assets/notice-template-reporter-expected-results-with-license-files
reporter/src/funTest/kotlin/reporters/NoticeTemplateReporterFunTest.kt
reporter/src/main/kotlin/reporters/NoticeTemplateReporter.kt
reporter/src/main/resources/template.notice/default.ftl
reporter/src/main/resources/template.notice/summary.ftl

This PR reworks the sections of the license_classifications.yml file and introduces a generic mechanism to assign licenses to categories. Refer to the commit messages for detailed information.

Oheger bosch/licenses/#2624 rework license configuration

---

spdx-utils/src/main/resources/declared-license-mapping.yml

[1] https://repo.maven.apache.org/maven2/com/caucho/hessian/4.0.38/hessian-4.0.38.pom.

Add a declared license mapping for "The Apache Software License, Version 1.1"

---

reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt

While a provenance can only have either sourceArtifact or vcsInfo set,
rewrite the code without taking that convention into account, which
actually makes the code simpler to read. Also check vcsInfo first as we
prefer it, because a sourceArtifact permalink is only supported for
Maven Central.

StaticHtmlReporter: Rework ResolvedLicenseLocation.permalink()

---

analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml
spdx-utils/src/main/resources/declared-license-mapping.yml

The homepage lists being liensed under "MIT License" as a feature.
Also see the discussion at [1].
[1] https://github.com/oss-review-toolkit/ort/issues/3324#issuecomment-729163021

Add a declared license mapping for http://json.codeplex.com/license

---

scanner/src/main/kotlin/LocalScanner.kt

When using ORT programmatically it is useful to have access to this
function to scan a single package.

LocalScanner: Make `scanPackage` a public function

---

cli/build.gradle.kts
cli/src/main/kotlin/OrtMain.kt
cli/src/main/kotlin/commands/UploadResultToPostgresCommand.kt
cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
model/src/main/kotlin/config/ScanStorageConfiguration.kt
scanner/src/main/kotlin/ScanResultsStorage.kt

Resolves #3024 
This PR adds an experimental command to upload analyzer results to SW360. It creates releases in SW360 for the packages list from the analyzer result. 
Usage.
`ort  -c <ort.conf for SW360 configuration> --ort-file analyzer-result.yml`

Add a command to upload analyzer results to SW360

---

build.gradle.kts

Gradle: Make also dokka use JDK 11

---

spdx-utils/src/test/kotlin/SpdxDeclaredLicenseMappingTest.kt
spdx-utils/src/test/kotlin/SpdxSimpleLicenseMappingTest.kt

spdx-utils: Test that we do not map to deprecated SPDX licenses

---

build.gradle.kts
gradle.properties

This can be useful for debugging / optimizing builds. See
https://gitlab.com/barfuin/gradle-taskinfo.

Gradle: Add the taskinfo plugin for listing task dependencies

---

Dockerfile

Use it like
$ docker run --entrypoint /opt/ort/bin/orth ort
Resolves #3368.

Dockerfile: Add the helper-cli

---

analyzer/build.gradle.kts
analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/managers/Unmanaged.kt
spdx-utils/src/main/kotlin/SpdxUtils.kt

Analyzer improvements

---

utils/src/main/kotlin/LicenseFilenamePatterns.kt
utils/src/test/kotlin/LicenseFilenamePatternsTest.kt

As these globs are only used for Git and Mercurial sparse checkouts.
The globs for the current directory are not required, as these files are
already included in the sparse checkout as part of the subproject.
See: https://github.com/oss-review-toolkit/ort/pull/3079#issuecomment-730319812 and https://github.com/oss-review-toolkit/ort/pull/3079#issuecomment-730322531

LicenseFilenamePatterns: Remove superfluous entries from file patterns

---

reporter/src/main/kotlin/reporters/CycloneDxReporter.kt

The previous name "bom.xml" made it sound to users as if this was the one
and only BOM file format that ORT would create, which is not true.
Several other output formats could be regarded as BOMs, too, as "BOM" is
not a well-defined term.

CycloneDxReporter: Change the output name to "CycloneDX-BOM.xml"

---

build.gradle.kts
scripts/docker_build.sh

We usually do not quote version strings, so also do not do this here.
This is a fixup for b0e5263.

Gradle/Docker: Do not quote version strings

---

advisor/src/main/kotlin/advisors/NexusIq.kt
cli/src/main/kotlin/commands/AdvisorCommand.kt
model/src/main/kotlin/config/AdvisorConfiguration.kt
model/src/test/assets/reference.conf
model/src/test/kotlin/config/BasicAuthConfigurationTest.kt

This PR renames the NexusIqConfiguration to BasicAuthConfiguration as no NexusIq specifics are stored in this configuration.
Added an example configuration to reference.conf and wrote an test case for the (de-) serialization of the configuration

Rename NexusIqConfiguration & serialization test

---

analyzer/src/funTest/kotlin/GitRepoFunTest.kt

This reverts a change from 97561f6 and makes the test run again on
Windows.

GitRepoFunTest: Do like the comment says and keep the shortened path

---

model/src/main/kotlin/ScanResult.kt

If a non-empty path was passed to the `filterPath()` function it always
removed the raw scan result. As a result, scan results for packages with
a VCS path were never stored in the scan results storage, because the
storage only stores scan results which contain a raw result.

ScanResult: Keep the raw result in filterPath()

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/GeneratePackageConfigurationsCommand.kt
helper-cli/src/main/kotlin/commands/ImportScanResultsCommand.kt

To allow the (future) implementation of commands taking scan results from that storage as input.
Adjust a first command to do so already to illustrate the idea and to speed-up that command.

helper-cli: Start indexing scan results

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/ImportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/FindCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/FormatCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/ImportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/ImportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/PackageConfigurationCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/RemoveEntriesCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/SortCommand.kt
helper-cli/src/main/kotlin/common/Utils.kt
model/src/main/kotlin/utils/SimplePackageConfigurationProvider.kt

Provide commands analog (but with slight differences) to the ones for the repository configurations.
Therefore introduce a dedicated Kotline package and add one level of sub command nesting.
Note: A following PR will clean-up the package configuration command and move the repository config commands also into a separate package and sub commend.

helper-cli: Support working with package configurations

---

reporter/src/funTest/kotlin/reporters/AsciidocTemplateReporterFunTest.kt
reporter/src/main/kotlin/reporters/AmazonOssAttributionBuilderReporter.kt
reporter/src/main/kotlin/reporters/AntennaAttributionDocumentReporter.kt
reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
reporter/src/main/resources/templates/asciidoc/default.ftl

For those reporters that to dot display excluded license findings in a
special way, align on filtering them out, as that is what users usually
expect.
Fixes #3363.

reporter: Filter out excluded license findings by default

---

advisor/src/main/kotlin/advisors/NexusIq.kt
clients/nexus-iq/src/main/kotlin/NexusIqService.kt
model/src/main/kotlin/Identifier.kt
model/src/test/kotlin/IdentifierTest.kt

This PR fixes an issue with PIP that [uses PyPi](https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/main/kotlin/managers/Pip.kt#L553) as the type within `Identity` as opposed to Gradle that uses `gradle` instead of `maven`.
Also Security Vulnerability URLs need to be nullable within Nexus IQ security issues.

Change PURL fallback to package manager type

---

reporter/src/main/kotlin/gitlab/GitLabLicenseModelMapper.kt

GitLabLicenseModelMapper: Add a missing dot at the end of a log message

---

cli/src/main/kotlin/commands/AdvisorCommand.kt
model/src/main/kotlin/AdvisorRecord.kt

This PR fixes the issue that the advisor result does not contain the `has_issues` flag if there are any issues present.

Fix not persisted has_issues in AdvisorResult

---

utils/src/main/kotlin/ArchiveUtils.kt

ArchiveUtils: Gracefully unpack malicious Zip file entries
Normally all entries of a Zip file are associated with a relatve file
path. However, it is also possible to have entries with an absolute
path, see e.g. [1]. When the downloader unpacks such source artifact
archives it tries to create the respective absolute directories, which
fails in case of lacking file system privileges.
Skip all entries with absolute paths to fix that. Apply the same fix to
all other unpack functions for consistency.
[1] https://repo.maven.apache.org/maven2/org/liquibase/liquibase-core/3.8.9/liquibase-core-3.8.9-sources.jar

ArchiveUtils: Gracefully unpack malicious Zip file entries

---

helper-cli/src/main/kotlin/commands/ImportScanResultsCommand.kt
model/src/main/kotlin/ScanResult.kt
model/src/test/assets/expected-scan-results.yml
model/src/test/kotlin/ScanResultContainerTest.kt
scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt
scanner/src/main/kotlin/LocalScanner.kt
scanner/src/main/kotlin/ScanResultsStorage.kt
scanner/src/main/kotlin/scanners/Askalono.kt
scanner/src/main/kotlin/scanners/BoyterLc.kt
scanner/src/main/kotlin/scanners/FileCounter.kt
scanner/src/main/kotlin/scanners/Licensee.kt
scanner/src/main/kotlin/scanners/ScanCode.kt
scanner/src/main/kotlin/storages/PostgresStorage.kt
scanner/src/test/kotlin/storages/CompositeStorageTest.kt

Remove the `rawResult` field from the `ScanResult`. The property
contained the raw data from the license scanner. The idea behind this
property was that it might be useful to have the raw data, but in
practice it turned out it is very rarely used. The raw result could be
much larger than the `ScanSummary` which contains the extracted data
from the raw result. This significantly increased the space required for
storing scan results and also slowed down storing and reading scan
results from a storage, for no practical use. This change also reduces
the amount of memory used by the scanner, because raw results are kept
in memory for a shorter time when scanning packages, and not at all when
downloading scan results from the storage.
Fixes #3403: As part of this also an old workaround that …

ScanResult: Remove raw result

---

utils/src/main/kotlin/OkHttpClientHelper.kt

When the jars are in a Maven Artifactory protected by credentials, the downloader part of the Scanner cannot download them.
It does not know the settings.xml.
This commit adds the OrtAuthenticator to the http client of the Downloader to be able to, at least, pass the credentials through .netrc or environment.
Standard use case when there is no need for credentials has also been tested.

Support "reactive" authentication for OkHttpClientHelper

---

reporter/src/main/resources/templates/asciidoc/vulnerability_report.ftl

This PR fixes the issue with the vulnerability_report template when there are no vulnerability URLs and an external link can not be generated.

Fix null/empty vulnerability URLs in the vulnerability_report template

---

scanner/src/main/kotlin/RemoteScanner.kt

Fix this inspection hint by turning "details" into a lazy property, like
it is in LocalScanner.
This is a fixup for a2a2b71.

RemoteScanner: Fix a leaking "this" in constructor

---

utils/src/main/kotlin/ArchiveUtils.kt

ArchiveUtils: Reduce the number of file / path conversions in packZip

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt

MavenSupport.buildMavenProject() used to download all the artifacts
for the dependencies of the project to build, which is unnecessary for
the analysis. There is no official way in the Maven API to prevent
this.
Therefore, implement a custom WorkspaceReader that claims binary
artifacts to be present locally; they are then no longer downloaded.
Further details can be found in this ticket:
https://github.com/oss-review-toolkit/ort/issues/2115.
Resolves #2115.
Signed-off-by: Oliver Heger <oliver.heger@bosch.io>
Please ensure that your pull request adheres to our [contribution guidelines](../CONTRIBUTING.md). Thank you!

Prevent download of binaries when analyzing a Maven project

---

utils/src/main/kotlin/OrtAuthenticator.kt
utils/src/test/kotlin/OrtAuthenticatorTest.kt

When parsing the .netrc, the entry with the 'machine'
name has higher precedence than the 'default' one.
Current implementation always wrongly returns the first entry.
Also : the regex has been moved to a static field because compilation is expensive.
Maybe it would be worthwhile to make getNetrcAuthentication() an instance function
of OrtAuthenticator ? Thus we could make the regex private.

OrtAuthenticator : in .netrc, raise 'machine' precedence

---

docs/getting-started.md

As the repository is now called "ort", change the directory to change to
accordingly.

getting-started: Fix the directory to change to

---

scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt

ScanCodeResultParser: Fix a typo in a comment about LicenseRefs

---

model/src/main/kotlin/ScanResult.kt
model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/main/kotlin/utils/FindingsMatcher.kt
model/src/main/kotlin/utils/RootLicenseMatcher.kt
model/src/test/kotlin/RootLicenseMatcherTest.kt

The current implementation of the license info resolver considers any
file that has been archived and is matching the currently configured
archiver pattern as a root license file.
In recent month an improved heuristic for determining the root license
has been implemented, but it's not yet been take into use by this license
info resolver. That heuristic also considers the actual project / VCS path
and is no limited to matching only files residing in the root directory
anymore. For consistency it also should be applied here.
Doing so makes it possible to broaden the archiver patterns without
affecting the generated notices. Further, it eliminates the need to create
a separate archives per VCS path (for same revision and VCS URL). Finally
it simplifies the (planned) removal of sparse …

LicenseInfoResolver: Properly determine the root license files

---

.appveyor.yml
.travis.yml

This fortunately has no benefit anymore as of [1], and not archiving the
local Maven repository should speed up CI builds.
[1] https://github.com/oss-review-toolkit/ort/pull/3445

Stop archiving the local Maven repository in CI builds

---

cli/src/funTest/kotlin/ExamplesFunTest.kt
docs/reporters/AsciiDocTemplateReporter.md
reporter/src/funTest/kotlin/reporters/AsciiDocTemplateReporterFunTest.kt
reporter/src/main/kotlin/reporters/AsciiDocTemplateReporter.kt

To be able to refer to fonts without an absolute path in the
theme yaml, the attribute `pdf-fontsdir` was added.
As described in the [asciidoctor-pdf documentation][1]
In order to support both custom fonts and the location of
bundled fonts the [`GEM_FONTS_DIR` was added in the attribute
by default][1].
[1]: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#configuring-the-font-search-path

AsciiDocTemplateReporter: Add pdf-fontsdir option

---

analyzer/src/main/kotlin/managers/Bower.kt
analyzer/src/main/kotlin/managers/Conan.kt

Instead of requiring a strict version, use that version as the minimum
to avoid frequent updates for newer versions. An upper bound could quickly
be set if incompatibility with a newer version is reported that cannot
immediately be fixed.
Resolves #3440.

analyzer: Relax strict version requirements on external tools

---

analyzer/src/funTest/assets/projects/synthetic/bundler/gemspec/Gemfile.lock
analyzer/src/funTest/assets/projects/synthetic/bundler/lockfile/Gemfile.lock

This way the tests work with both Bundler 1 and Bundler 2. Also see
https://bundler.io/guides/bundler_2_upgrade.html#version-autoswitch.

analyzer: Remove the Bundler version from test lockfiles

---

cli/src/main/kotlin/commands/DownloaderCommand.kt

Even if historically ORT sometimes refers to projects as
(project-)packages, we should starting improving this and make the
distinction clearer.

DownloaderCommand: Better distinguish projects and packages

---

cli/src/main/kotlin/OrtMain.kt
cli/src/main/kotlin/commands/EvaluatorCommand.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
downloader/src/main/kotlin/VersionControlSystem.kt
model/src/main/kotlin/config/FileArchiverConfiguration.kt
model/src/main/kotlin/config/LicenseFilenamePatterns.kt
model/src/main/kotlin/config/OrtConfiguration.kt
model/src/main/kotlin/utils/RootLicenseMatcher.kt
model/src/test/assets/reference.conf
model/src/test/kotlin/config/OrtConfigurationTest.kt
model/src/test/kotlin/config/ScannerConfigurationTest.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
model/src/test/kotlin/licenses/LicenseViewTest.kt
reporter/src/funTest/kotlin/reporters/NoticeTemplateReporterFunTest.kt
reporter/src/main/kotlin/ReporterInput.kt
scanner/src/main/kotlin/LocalScanner.kt
test-utils/src/main/kotlin/Extensions.kt
utils/src/main/kotlin/LicenseFilenamePatterns.kt
utils/src/main/kotlin/storage/FileArchiver.kt
utils/src/test/kotlin/storage/FileArchiverTest.kt

There are several components depending on the license filename patterns, namely
- version control system's sparse checkout implementations
- file archiver
- root license matcher
- license info resolver
- ...
These patterns are currently hard-coded in the code, except for the file archiver which has a single configurable filename pattern
for determining which files to archive. That configuration however needs to be consistent with the hard-coded license filename patterns. Thus, the user can easily setup a wrong config causing inconsistencies and finally issues with the generated notice by package file.
All in all it makes sense to configure the license filename patterns globally and then use these globally configured patterns all over the place. The changes of this PR 
- remove the file …

Configurable license filename patterns

---

cli/src/main/kotlin/commands/EvaluatorCommand.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
downloader/src/main/kotlin/VersionControlSystem.kt
model/src/main/kotlin/ScanResult.kt
model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/main/kotlin/utils/OrtResultExtensions.kt
model/src/main/kotlin/utils/RootLicenseMatcher.kt
reporter/src/main/kotlin/ReporterInput.kt
reporter/src/main/kotlin/model/EvaluatedModelMapper.kt

This PR ensures that the configured license filename patterns are consistently used all over the place, except for the tests.
It is basically taking https://github.com/oss-review-toolkit/ort/pull/3462 into use and thus has to be merged after it.

Consistently use the configured license filename patterns

---

cli/src/funTest/kotlin/ExamplesFunTest.kt

ExamplesFunTest: Avoid a lateinit to be able to run tests individually

---

helper-cli/build.gradle.kts
scanner/build.gradle.kts
scanner/src/main/kotlin/ScanResultsStorage.kt
scanner/src/main/kotlin/storages/Sw360Storage.kt

Add a scan results storage for SW360 using the REST API. The scan
results are read/uploaded as a Scan Result Report attachment type in
SW360.
Resolves #2211.

scanner: Add a SW360 scan results storage

---

cli/build.gradle.kts
reporter/build.gradle.kts

From version 1.6.0 on, the json-schema artifact is primarily distributed
through JitPack [1], so prefer to get the it from there to avoid build
breakages. Fixes #3470.
[1] https://github.com/everit-org/json-schema#maven-installation
Signed-off-by: pctf <baranukis@gmail.com>

Gradle: Get the json-schema artifact from JitPack

---

scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt

With lateinit there is always the theoretical risk that the variable is
accessed before it is being initialized, so avoid lateinit where not
strictly needed.

ClearlyDefinedStorageTest: Avoid an unnecessary lateinit

---

scanner/src/main/kotlin/storages/Sw360Storage.kt

Omit return types in a few simple cases, partly to be able to improve
formatting.

Sw360Storage: Omit return types for function expressions

---

analyzer/src/main/kotlin/managers/Maven.kt

This is a fixup for 539d00a where only the commit messages was adjusted
to refer to a hint.

Maven: Fix the issue for auto-generated POMs to be a hint

---

reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
utils/src/main/kotlin/Extensions.kt

All other reporters also default to create a single file for all
projects, and for large multi-projects the number of files can become
confusing, so change the default to create a single file.

Create a single CycloneDX BOM by default

---

advisor/src/main/kotlin/Advisor.kt
cli/src/main/kotlin/commands/DownloaderCommand.kt
scanner/src/main/kotlin/Scanner.kt

Align on using canonicalPath for checking a provided ORT result file

---

evaluator/src/main/kotlin/RuleMatcher.kt

It can be used to make "Not(AnyOf(..))" constructs more readable.

RuleMatcher: Provide a NoneOf RuleMatcher

---

spdx-utils/src/main/kotlin/SpdxException.kt
spdx-utils/src/main/kotlin/SpdxExpression.kt
spdx-utils/src/test/kotlin/SpdxExpressionTest.kt

This is a draft how license choices should be applied.
The signature of the tested function looks like this:
`fun applyChoice(choice: SpdxExpression, subtreeMatcher: SpdxExpression = this): SpdxExpression`
See #3396 and #2610

Apply license choices to SPDX expressions

---

model/src/main/kotlin/config/PathExclude.kt
model/src/test/kotlin/config/PathExcludeTest.kt

When `.ort.yml `contains a exclude path pattern with leading "./" , the match is not done.
With this commit, the leading "./" is ignored for matching.

Ignore leading './' in path exclude patterns

---

analyzer/src/main/resources/scripts/init.gradle

This PR addresses #3321 on side of the Gradle plugin used to construct a dependency tree.
The plugin used to create a large number of duplicated Dependency objects. The PR applies a similar optimization than #3502; it caches the Dependency objects and reuses them throughout the dependency graph whenever possible.
Interestingly, this optimization also caused an unexpected speed improvement - probably because the dependency graph now is not traversed again and again for each scope. The time to analyse the [Focus Android](https://github.com/mozilla-mobile/focus-android.git) project on my machine went down from over 30 minutes to less than 4 minutes.

Optimize memory consumption of Gradle dependency tree plugin

---

analyzer/build.gradle.kts
analyzer/src/main/kotlin/curation/Sw360PackageCurationProvider.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
docs/getting-started.md
integrations/Jenkinsfile
model/src/main/kotlin/config/AnalyzerConfiguration.kt
model/src/main/kotlin/config/OrtConfiguration.kt
model/src/main/kotlin/config/ScanStorageConfiguration.kt
model/src/test/assets/reference.conf
model/src/test/kotlin/config/OrtConfigurationTest.kt
model/src/test/kotlin/config/Sw360StorageConfigurationTest.kt
reporter/src/funTest/kotlin/reporters/NoticeTemplateReporterFunTest.kt

This PR adds a package curation provider based on SW360. In order to use it set the flag `--sw360-curations` and add a config file with `-c <path-to-ort.conf>` in order to pass SW360 connection configurations like URLs, credentials and proxy. 
Resolves #2210.

analyzer: Add a package curation provider based on SW360

---

docs/getting-started.md
integrations/Jenkinsfile

Account for "ort.analyzer.allowDynamicVersions" now being a global option

---

model/src/main/kotlin/Vulnerability.kt
model/src/test/kotlin/VulnerabilityTest.kt

The rating attaches human-readable semantics to the score number.

Vulnerability: Add a function to get the rating based on the score

---

model/src/main/kotlin/ScanResult.kt
model/src/main/kotlin/config/ScannerConfiguration.kt
model/src/test/assets/reference.conf
model/src/test/kotlin/config/OrtConfigurationTest.kt
scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
scanner/src/main/kotlin/LocalScanner.kt
scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
scanner/src/test/kotlin/scanners/scancode/ScanCodeTest.kt
spdx-utils/src/main/kotlin/SpdxUtils.kt

Remove the filtering of 'non-license-files' from ScanCode in favor of a  configurable 'ignore file path' list which is applied consistently across all (local) scanner implementations. This makes things simpler and more general. Furthermore it allows for changing the configuration option in the future without invalidating the already existing scan cache entries - as the filtering is applied only after the scan results are stored.
**Migrating the Postgres scan results database**
This PR changes the scanner details which has the effect that entries stored in the scan results database do no match anymore.
This can be fixed by updating the `configuration` property of the scan results. Here's how this can be done in PostgreSQL
1. Determine the value(s) of the `scanner.configuration` property of …

Scanner: Generalize the ignore file list and make it configurable

---

model/src/main/kotlin/Vulnerability.kt
model/src/test/kotlin/VulnerabilityTest.kt

See e.g. [1] for the differences.
Also remove the "rating" variable from the Vulnerability class as it is
up to the Advisor implementation now to choose the correct mapping type.
[1] https://www.balbix.com/insights/cvss-v2-vs-cvss-v3/#CVSSv3-Scoring-Scale-vs-CVSSv2-6

Vulnerability: Distinguish between CVSS v2 and v3 score mapping

---

scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
scanner/src/test/kotlin/scanners/scancode/ScanCodeTest.kt

When the configuration options differ between debug and non-debug mode
the scan results cannot be re-used across these two modes. Align them
so that the scan storage entries do actually get re-used across modes.
Note that the option `--license-diag´ doesn't have any effect anymore
anyway as of [1].
[1] https://github.com/nexB/scancode-toolkit/commit/4087bba0eded214435e6e83297e7cb8fcc5415d3

ScanCode: Align the debug configuration options with non-debug ones

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt

When a Maven sources package cannot be downloaded, we should log with an "INFO" level instead of "WARN".

Adjust the log level to be "info" for Maven source packages

---

advisor/src/main/kotlin/advisors/NexusIq.kt
cli/src/main/kotlin/commands/UploadCurationsCommand.kt
clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
clients/nexus-iq/src/main/kotlin/NexusIqService.kt
model/src/main/kotlin/Vulnerability.kt
model/src/test/kotlin/AdvisorResultContainerTest.kt

No specific features of the URL class are used, but it brings in
some additional complexity (e.g. when doing equals checks). Other
parts of the model also use strings to represent URLs, e.g. VcsInfo.

Change type of Vulnerability.url from URL to String

---

integrations/azure/README.md
integrations/azure/credentials/write-config-netrc.yml
integrations/azure/credentials/write-downloader-netrc.yml
integrations/azure/docker/docker-build-image.yml
integrations/azure/docker/docker-ort-run.yml
integrations/azure/ort-pipeline.yml
integrations/azure/steps/complete-ort-run.yml

This adds a starter pipeline to try ORT on Azure. 
To test the pipeline, just select it from the Azure Pipelines GUI and run it with your choice of parameters.
There are several features we would like to contribute later on, but I cut it down to this to simplify reviewing. The pipeline was cut into several pieces to avoid duplication. The general organization will be used for future changes.
The following features are missing and will be contributed in future PRs:
- proper handling of using docker for shared runners: Cleanup output, allow pipeline to run as non-root (this is especially important for file permissions)
- use container registries to not build the pipeline every time
- split into stages to have a nicer view
- better customization

Add Azure Starter Pipeline for ORT run

---

cli/src/funTest/assets/semver4j-analyzer-result.yml
reporter-web-app/public/index.html
scanner/src/test/assets/mime-types-2.1.18_scancode-2.9.7.json
scanner/src/test/assets/mime-types-2.1.18_scancode-3.0.2.json
scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt

As a follow-up to 3410cff, remove this last bit of HERE-specific data
from the code base.
As the SPDX package verification code in simply calculated on the ScanCode
JSON output file for testing, the code needs to be adjusted as the
ScanCode output was modified.

Remove the mention of HERE_NOTICE from test data

---

scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
scanner/src/test/kotlin/scanners/scancode/ScanCodeTest.kt

The feature to pass additional options to the command line of ScanCode
when ORT is running in debug mode does not bring much benefit (the
same effect can be achieved manually by temporarily changing the ORT
configuration), but complicates the handling of scanner options and
checks for their compatibility.
While at it, fix some warnings about wrong references in KDoc comments
(which have been caused by changes of the 'configuration' property.

ScanCode: Drop support for debug command line options

---

cli/src/funTest/kotlin/ExamplesFunTest.kt
examples/rules.kts
model/src/main/kotlin/licenses/LicenseClassifications.kt
model/src/test/kotlin/licenses/LicenseClassificationsTest.kt
reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt

Instead of returning the LicenseCategorization, just return the licenses
contained in the category or the names of the categories, respectively,
as that is what is mostly needed. Adjust variable names, docs and tests
accordingly.

LicenseClassifications: Refactor the API a bit for usability

---

reporter/src/main/kotlin/model/EvaluatedModelMapper.kt

For "global" rule violations that are not triggered by a project or
package it makes sense to set the ID to Identifier.EMPTY. The WebApp
reporter so far failed to be generated for such rule violations as the
underlying mode mapper demanded the ID to by a valid project or package
ID. Relax this requirement to be able to display such "global" rule
violations in the WebApp reporter.

EvaluatedModelMapper: Support empty IDs for rule violations

---

advisor/src/main/kotlin/advisors/NexusIq.kt
clients/nexus-iq/src/main/kotlin/NexusIqService.kt

This PR is related #3553. It changes the service interface for NexusIQ to use the coroutines support provided by Retrofit.

Change NexusIqService to use suspend functions

---

cli/src/main/kotlin/commands/AdvisorCommand.kt

Stay unbiased here and do not set a default.

AdvisorCommand: Do not set a default advisor

---

reporter/src/funTest/kotlin/reporters/GitLabLicenseModelReporterFunTest.kt

ScanCode uses "public-domain-disclaimer".

GitLabLicenseModelReporterFunTest: Fix the LicenseRef for Public Domain

---

utils/src/main/kotlin/OkHttpClientHelper.kt
utils/src/test/kotlin/OkHttpClientHelperTest.kt

This way a common connection pool is shared across all clients.

OkHttpClientHelper: Base all clients on the same base client

---

analyzer/src/main/kotlin/managers/Sbt.kt

Starting from 1.4.2 Sbt adds some special characters to output regardless CI_MODE value. It brakes
mapDefinitionFiles that is based on parsing SBT output with regex. Disabling console colors explicitly
removes these characters.
Signed-off-by: zhernovs <ext-andriy.zhernovskyi@here.com>

Sbt: Disable console colors

---

model/src/main/kotlin/OrtResult.kt

These functionalities can be implemented using the LicenseView via the
LicenseRule. This ensures that the user's package configurations are
taken into account.
See discussion: https://github.com/oss-review-toolkit/ort/pull/3566#discussion_r567983170

OrtResult: Remove methods for accessing declared and concluded licenses

---

advisor/src/main/kotlin/Advisor.kt
advisor/src/main/kotlin/advisors/NexusIq.kt
advisor/src/main/kotlin/advisors/VulnerableCode.kt

This also fixes an issue with the Nexus IQ advisor using the wrong start
time in the summary.

advisor: Move common code for failed packages to the base class

---

.github/CODEOWNERS

Both have contributed significantly to the advisor and should be
consulted for future changes.

Add @MarcelBochtler and @oheger-bosch as advisor code owners

---

clients/oss-attribution-builder/src/main/kotlin/OssAttributionBuilderService.kt
reporter/build.gradle.kts
reporter/src/main/kotlin/reporters/AmazonOssAttributionBuilderReporter.kt

Use the built-in support for Coroutines in Retrofit rather than the
Call-based API.
Adapt the AmazonOssAttributionBuilderReporter accordingly.
This is part of the work done for #3553.

OssAttributionBuilderService: Use suspend functions in interface

---

reporter/src/main/kotlin/reporters/CycloneDxReporter.kt

One important aspect of the copyright statements processing is the
merging of multiple copyright statements into single ones. Thus, collect
all copyright statements to be included first and then pass them to the
processing.
Previously, the processing was called once per license which hinders the
merging from doing its job.
Note: In a following change the call to the copyright statements
processor will be moved into a function of the resolved licenses API.

CycloneDxReporter: Fix the processing of copyright statements

---

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
cli/build.gradle.kts
cli/src/main/kotlin/commands/UploadCurationsCommand.kt
clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt

Like in previous PRs, the interface is changed to use suspend functions rather than the Call API, and the call sites are changed accordingly.
I split the change into multiple commits because there were different clients for separate groups of functions in the interface; so they could be converted one by one.

Change ClearlyDefinedService interface to make use of Retrofit's support for coroutines

---

model/src/main/kotlin/OrtResult.kt

Previously, the private property advisorResultsById was unused and thus
could be removed. However, add a function to make use of that property
for consistency with getScanResultsForId().

OrtResult: Add getAdvisorResultsForId()

---

clients/fossid-webapp/src/main/kotlin/Extensions.kt
clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt

Use the built-in support for coroutines of Retrofit for this service.
This PR converts the last remaining Retrofit service to use the built-in coroutines support.

FossIdRestService: Change functions to use suspend

---

README.md

As Azur builds both, Linux and Windows, replace both badges with the
Azure build status badge.

README: Reorganize the badges

---

cli/src/main/kotlin/OrtMain.kt

Previously, the "* denotes required options." hint was only shown for
the help of the root command.

OrtMain: Show the help epilog also for subcommands

---

advisor/src/main/kotlin/Advisor.kt

Place blank lines where highlighting groups makes sense.

Advisor: Trivially improve formatting a bit

---

analyzer/src/main/kotlin/Analyzer.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt

There used to be an undocumented feature for analyzing a single project
file which got broken in the migration from JCommander to clikt. Restore
that feature and document it.

Restore the feature for analyzing a single project file

---

model/src/main/kotlin/licenses/LicenseInfoResolver.kt
reporter/src/main/kotlin/reporters/AsciiDocTemplateReporter.kt
reporter/src/main/kotlin/reporters/NoticeTemplateReporter.kt
reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
reporter/src/test/kotlin/utils/FreeMarkerTemplateProcessorTest.kt

ORT has two different notice reporter templates. The notice summary
template just lists all licenses in one large list. The default
template has one joint list for the licenses of all projects and
separate lists for the licenses of each package.
In some cases it makes sense to also list the licenses separetly for (some
of the) projects. In particular, listing the licenses for
SpdxDocumentFile projects separately is interresting, because this
allows to create a notice by package report also in cases where no
package manager is involved and the source code of the project dependencies
is just included in the source tree of the analyzed project.
In order to support that use case the scan results have to be
deduplicated for the projects which are to be reported separately in the
notices, …

NoticeTemplateReporter: Add an option for treating projects like packages

---

cli/src/main/kotlin/commands/DownloaderCommand.kt
downloader/src/main/kotlin/VersionControlSystem.kt
downloader/src/main/kotlin/vcs/Cvs.kt
downloader/src/main/kotlin/vcs/Git.kt
downloader/src/main/kotlin/vcs/GitRepo.kt
downloader/src/main/kotlin/vcs/Mercurial.kt
downloader/src/main/kotlin/vcs/Subversion.kt

In some VCS, like Git, the remote default branch can be configured. As Git
(and GitHub) recently changed the default name of the remote (and local)
default branch from "master" to "main", extend ORT's logic to dynamically
determine the remote default branch name per repository.
Resolves #3590.

Downloader: Support dynamic remote default branches

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
scanner/src/main/kotlin/LocalScanner.kt
utils/src/main/kotlin/Logger.kt
utils/src/test/kotlin/LoggerTest.kt

This helps to avoid logging accidentally being done on nested lambdas,
resulting in probably unexpected class names in the log.

Logger: Ensure logging is done on ORT classes

---

reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt

Show provenance information for detected licenses in the static HTML report

---

helper-cli/src/main/kotlin/common/Utils.kt
model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
reporter/src/main/kotlin/reporters/CycloneDxReporter.kt

Previously, `CopyrightStatements.process()` was called once per license finding file location by the `LicenseInfoResolver`.
This does not make sense and leads to poor performance as the `process()` function is not super fast (but fast enough if called only reasonably often). Once more, the license API was designed to hold the pre-processed copyright statements. This does not make any sense because the processing is different depending on the use case.
Do the processing properly, thereby reduce the number of calls to `process()` tremendously and change the design such that copyright statements are always processed on-the-fly. This fixes #3511.

Fix processing of copyrights along with its performance issues

---

model/src/main/kotlin/Project.kt
model/src/test/kotlin/ProjectTest.kt

Projects now support two different ways to store information about
their scopes and dependencies. This function makes sure that the
traditional format - the map with scopes - has been initialized, which
ensures compatibility with some use cases.

Add withResolvedScopes() function to Project class

---

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt

This makes the IDE highlight the second line properly.

ClearlyDefinedPackageCurationProvider: Fix indentation for a TODO

---

analyzer/src/funTest/assets/projects/external/directories-expected-output.yml
analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
analyzer/src/main/kotlin/managers/Sbt.kt

The Sbt implementation uses the command `sbt makePom` to generate POM
files and then analyzes the POM files using ORT's Maven support. These
generated POM files are not siblings of their original POM files, but
are always placed within some directory named 'target'.
Thus, `Sbt.mapDefinitionFiles()` changes the directory of the POM file
which leads to the following problems:
1. If the root directory of the repository contains a `build.sbt` but
no other definition file, then an Unmanaged project is added by the
package manager, because there is no mapped definition file in the
root directory.
2. The filtering of scan results done by `LocalScanner` via
`ScanResultContainer.filterByProject()` removes all license and
copyright findings from any generate POM project, because the
generated POM …

Sbt: Improve the mapping of definition files to fix related issues

---

analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt

ClearlyDefinedPackageCurationProviderTest: Add tests for non-existing packages

---

advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
clients/vulnerable-code/src/main/kotlin/VulnerableCodeService.kt

This reverts commit 04be50f. The work-around is not necessary anymore as
the issue has been fixed upstream in VulnerableCode, see
https://github.com/nexB/vulnerablecode/issues/284#issuecomment-778739208

Revert "VulnerableCodeService: Add slash character at bulk search URLs"

---

model/src/main/kotlin/config/ScannerConfiguration.kt
model/src/test/assets/reference.conf
scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
scanner/src/main/kotlin/LocalScanner.kt

The LocalScanner supports both an archive and a storage. So far, if
results of a package are present in the storage, they are skipped,
independent of the presence of results in the archive. Add an additional
check that, in case of absence, downloads the source code and applies the
archiving process.

LocalScanner: Check for archived files if scan results are present

---

reporter/src/funTest/kotlin/reporters/ExcelReporterFunTest.kt

Do not take the font index into account in test assertions as it might
change when just resaving the file without making real changes.

ExcelReporterFunTest: Disregard the font index as it is not stable

---

analyzer/src/funTest/assets/projects/synthetic/spdx/package/libs/curl/package.spdx.yml
analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml

Using the spdx-java-tool verify functionality [1]
these URIs were validated.
[1] https://github.com/spdx/tools-java.git
This commit is originally from https://github.com/oss-review-toolkit/ort/pull/3521, but was separated into a smaller PR.

Fix URLs of downloadLocation in SPDX example files

---

analyzer/src/main/kotlin/managers/Bower.kt
analyzer/src/main/kotlin/managers/Bundler.kt
analyzer/src/main/kotlin/managers/Cargo.kt
analyzer/src/main/kotlin/managers/Carthage.kt
analyzer/src/main/kotlin/managers/Composer.kt
analyzer/src/main/kotlin/managers/Conan.kt
analyzer/src/main/kotlin/managers/GoDep.kt
analyzer/src/main/kotlin/managers/GoMod.kt
analyzer/src/main/kotlin/managers/Gradle.kt
analyzer/src/main/kotlin/managers/Maven.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/Pip.kt
analyzer/src/main/kotlin/managers/Pub.kt
analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
analyzer/src/main/kotlin/managers/Stack.kt
analyzer/src/main/kotlin/managers/Unmanaged.kt
analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
model/src/main/kotlin/Package.kt
model/src/main/kotlin/PackageCurationData.kt
model/src/main/kotlin/Project.kt
model/src/test/kotlin/PackageCurationTest.kt
model/src/test/kotlin/PackageTest.kt

This is a preparation for solving #3400 and making copyright holder
curations possible. A new field declaredAuthors is added to
Package, PackageCuration and Project in order to be able to track
fields like authors from various package managers. These changes
don't include the adaptation of the package managers.

model: Add a new field for authors

---

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt
clients/clearly-defined/src/funTest/assets/gson.json
clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt

ClearlyDefined now returns HTTP 404 errors for non-existing curations,
see [1]. Lower the log level from "warn" to "debug" as not having a
curation is just fine with us if none is available.
Resolves #3559.
[1] https://github.com/clearlydefined/service/issues/795

ClearlyDefinedService: Support deserializing invalid curations

---

analyzer/src/main/kotlin/managers/GoDep.kt
analyzer/src/main/kotlin/managers/GoMod.kt

After studying the reference documentation about go modules and go dep, it turned out that both formats do not support standardized metadata for package authors. So, just remove the corresponding TODO comments.

(Lack of) author support for go package managers

---

docs/config-file-ort-yml.md

config-file-ort-yml: Fix formatting with backticks

---

scanner/src/main/kotlin/LocalScanner.kt

Previously, mapNotNullTo() added the mapped elements to the wrong set,
and thus `missingArchives` was guaranteed to always remain empty.
Trivially fix this by assigning the variable properly. This is a fix-up
of 90de765.

LocalScanner: Fix-up the creation of missing file archives

---

model/src/main/kotlin/config/FileArchiverConfiguration.kt
model/src/main/kotlin/config/ScannerConfiguration.kt
model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/main/kotlin/utils/FileArchiver.kt
model/src/main/kotlin/utils/OrtResultExtensions.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
model/src/test/kotlin/licenses/LicenseViewTest.kt
model/src/test/kotlin/utils/FileArchiverTest.kt
scanner/src/main/kotlin/LocalScanner.kt
test-utils/src/main/kotlin/Extensions.kt

The `FileArchiver` implementation is going to be extended to support a PostgreSQL storage in addition to / as alternative to the currently supported file storage in a following PR. Thus, the API of the file archiver must abstract from any storage specific details.
This is exactly what the changes are about. In particular, the `storagePath` API parameter is removed in favor of making the file archiver derive the archive file path internally from any given `id` and `provenance`.

FileArchiver: Encapsulate the file storage path

---

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm/README.md
analyzer/src/funTest/assets/projects/synthetic/npm/node-modules/package.json
analyzer/src/funTest/assets/projects/synthetic/npm/package-lock/package.json
analyzer/src/funTest/assets/projects/synthetic/npm/shrinkwrap/package.json
analyzer/src/funTest/assets/projects/synthetic/yarn-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/yarn-workspaces-expected-output.yml
analyzer/src/main/kotlin/managers/Npm.kt

Extract information about the author of a package from package.json
and make it available in the metadata of packages and projects.
Note: The major part of the changes is related to adapting the expected output of tests.

Npm: Add support for declared authors

---

analyzer/src/funTest/assets/projects/synthetic/npm/README.md

This makes the markdown link check pass again. Note that shrinkwrap
deliberately links to v6 of the docs, as using shrinkwrap is legacy.

analyzer: Update links in the README for synthetic NPM tests

---

analyzer/src/main/kotlin/managers/Npm.kt

As a trimmed string cannot be blank, it is enough to check for an empty
string here.

Npm: Trivially improve author string parsing

---

analyzer/src/funTest/assets/projects/external/dart-http-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pub-expected-output-any-version.yml
analyzer/src/funTest/assets/projects/synthetic/pub-expected-output-project-with-flutter.yml
analyzer/src/funTest/assets/projects/synthetic/pub/any-version/pubspec.yaml
analyzer/src/main/kotlin/managers/Pub.kt

Extract information about the authors of a package from the
pubspec.yaml definition file and make it available in the metadata of
packages and projects.

Pub: Add support for authors

---

Dockerfile

This is a basic requirement to be able to analyze Python projects that
have dependencies on native packages.

Dockerfile: Add Python development files

---

analyzer/src/funTest/assets/projects/synthetic/spdx-project-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml

This helps to have a higher coverage of tested code and ensures
that changes in the future aren't accidentally breaking anything.

SpdxDocumentFile: Add originator to example files

---

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pip-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pipenv-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pipenv-python3-expected-output.yml
analyzer/src/main/kotlin/managers/Pip.kt

Extract information about the author of a package from its setup.py
file or from the PyPi metadata, and make it available in the metadata
of packages and projects.

Pip: Add support for declared authors

---

analyzer/src/main/kotlin/managers/Gradle.kt

As is true for declared licenses, there is no support for authors in
gradle projects. Therefore, remove the TODO comment and just pass an
empty set for the authors field.

Gradle: Deal with missing support for authors field

---

analyzer/src/funTest/assets/projects/synthetic/cargo-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/cargo-subcrate-client-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/cargo-subcrate-integration-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/cargo-subcrate-lib-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/cargo-subcrate/Cargo.toml
analyzer/src/funTest/assets/projects/synthetic/cargo/Cargo.toml
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/managers/Cargo.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/Pub.kt

Extract information about the authors of a package from the Cargo.toml
definition file or from the metadata returned by cargo.

Cargo: Add support for declared authors

---

examples/asciidoctor-pdf-theme.yml
reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
reporter/src/main/resources/templates/asciidoc/disclosure_document.ftl
reporter/src/test/kotlin/utils/FreeMarkerTemplateProcessorTest.kt

In practice you probably do not want to use a disclosure document if there are unresolved issues in the reporter input.
To emphasize this, a check for unresolved issues is added that, if it is successful, adds a disclaimer to the disclosure document.

Add disclaimer in AsciidocTemplate disclosure document, if there are unresolved issues.

---

analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-py.yml
analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml
analyzer/src/funTest/assets/projects/synthetic/conan-py/conanfile.py
analyzer/src/main/kotlin/managers/Conan.kt

Extract information about the author of a package from the metadata
returned by an invocation of the "conan info" command.

Conan: Add support for declared authors

---

analyzer/src/funTest/assets/projects/synthetic/cargo-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/cargo-subcrate-client-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/cargo-subcrate-lib-expected-output.yml
analyzer/src/main/kotlin/managers/Cargo.kt

Do not include the OR-mapping as part of the declared license strings, but
apply it when processing the declared licenses. This way licenses are
sorted alphabetically in the result, and it becomes clear from the
whether the original metadata used a "/" to separate licenses.

Cargo: Improve the OR-mapping of licenses

---

analyzer/src/funTest/assets/projects/synthetic/bower-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/bower/bower.json
analyzer/src/main/kotlin/managers/Bower.kt

Extract information about the authors of a package from the bower.json
definition file and make it available in the metadata of packages and
project.

Bower: Add support for authors

---

downloader/src/main/kotlin/VersionControlSystem.kt

Support guessing revisions for Git tags of the form "@organization/component@1.2.3".

Support guessing revision some Lerna specific Git tag format

---

analyzer/src/funTest/assets/projects/synthetic/spdx-project-expected-output.yml
analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
analyzer/src/test/kotlin/managers/SpdxDocumentFileTest.kt

Previously, the downloadLocation was only considered if it was a file
URL, and it was not considered for determining the VCS location, which
is wrong. Address both issues by properly parsing the downloadLocation
and getting any artifact or VCS location from it.
Fixes #3700.

SpdxDocumentFile: Properly parse the downloadLocation

---

downloader/src/main/kotlin/Downloader.kt

I've got a exception :
```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <"> at index 22: ort5136863379338526039"logback-logger_2.12-1.0.14-sources.jar"; filename*=UTF-8''logback-logger_2.12-1.0.14-sources.jar
at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
at java.base/java.nio.file.TempFileHelper.generatePath(TempFileHelper.java:59)
at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:126)
at …
```

Downloader: Fix the reading of content-disposition

---

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pip-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pipenv-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pipenv-python3-expected-output.yml
analyzer/src/main/kotlin/managers/Pip.kt
examples/curations.yml

In Python package names are case-insensitive, and uses of hyphens and underscores are considered to be equivalent.
This may lead to cases where the same dependency appears twice in ORT scan results with different cased ids.
For example, this happens if say in transitive dependency on https://pypi.org/project/Flask has been declared as either
[Flask][1] or [flask][2].
[1]: https://github.com/corydolphin/flask-cors/blob/3.0.10/requirements.txt
[2]: https://github.com/rycus86/prometheus_flask_exporter/blob/0.18.1/requirements.txt
**This PR is a breaking change for all ORT users analyzing Python projects**
After this PR is merged Python packages may get a different package id assigned by ORT in the scan results. If you have Python packages defined in your …

Pip: Normalize package name

---

analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt
clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
test-utils/build.gradle.kts
test-utils/src/main/kotlin/ProjectConfig.kt

Initialize the proxy selector only once for all tests via the ProjectConfig

---

analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml
analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml
analyzer/src/main/kotlin/managers/Stack.kt

Extract information about the authors of a package from the cabal file
and make it available in the metadata of packages and projects.

Stack: Add support for authors

---

analyzer/src/funTest/assets/projects/synthetic/composer-expected-output-no-deps.yml
analyzer/src/funTest/assets/projects/synthetic/composer-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/composer/empty-deps/composer.json
analyzer/src/funTest/assets/projects/synthetic/composer/no-deps/composer.json
analyzer/src/main/kotlin/managers/Composer.kt

Extract information about the authors of a package from the
composer.json definition file and make it available in the metadata
of packages and projects.

Composer: Add support for authors

---

cli/src/main/kotlin/commands/UploadResultToSw360Command.kt

The UploadResultToSw360Command always evaluates the function in orElse
regardless if the Optional is present. To avoid the creation of
components/releases/projects every run, replace orElse with orElseGet.

cli: Replace orElse with orElseGet in UploadResultToSw360Command

---

analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output-with-nuspec.yml
analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/dotnet/subProjectTestWithNuspec/.nuspec
analyzer/src/funTest/assets/projects/synthetic/dotnet/subProjectTestWithNuspec/test.csproj
analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml
analyzer/src/funTest/kotlin/managers/DotNetFunTest.kt
analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt

Extract information about the authors of a package from the .nuspec
manifest.

NuGetSupport: Add support for declared authors

---

advisor/src/main/kotlin/Advisor.kt
advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
model/src/main/kotlin/AdvisorRecord.kt
model/src/main/kotlin/OrtResult.kt
model/src/test/kotlin/AdvisorRecordTest.kt
reporter/src/main/kotlin/reporters/AsciiDocTemplateReporter.kt
reporter/src/main/resources/templates/asciidoc/vulnerability_report.ftl

Use a map of instead of a list of `AdvisorResultContainer`s, because
this provides faster lookup by id and allows to simplify the code
working with the property.
The change adds a custom deserializer for the `advisorResults` property
to make sure that old ORT result files can still be read. When this
backward compatibility is not required anymore, the
`AdvisorResultContainer` class can be removed.
See also the related change for `ScanRecord`: #3720

AdvisorRecord: Change the type of advisorResults to a map

---

analyzer/src/main/resources/META-INF/plexus/components.xml

The packaging [1] says "hk2-jar", but the file extension is "jar".
[1] https://repo1.maven.org/maven2/org/glassfish/ha/ha-api/3.1.9/ha-api-3.1.9.pom

analyzer: Add a work-around for wrongly named High Availability artifacts

---

model/src/main/kotlin/config/OrtConfiguration.kt
model/src/test/kotlin/config/NexusIqConfigurationTest.kt
model/src/test/kotlin/config/OrtConfigurationTest.kt
model/src/test/kotlin/config/ScannerConfigurationTest.kt

The "config" context is clear here, and "args" also does not have that
prefix.

OrtConfiguration: Rename load()'s "configFile" to just "file"

---

README.md

The https://glide.sh/ homepage seems to be dead, so use the GitHub
project page instead.

README: Use the GitHub project page for Glide

---

scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt

The recently introduced replacement mechanism [1] does not adhere to
word boundaries. For example, if the expression variable holds the value
"LicenseRef-scancode-public-doman" prior to a replacement of
"public-domain" with "LicenseRef-scancode-public-doman", then in the
next iteration the expression variable has the value
"LicenseRef-scancode-LicenseRef-scancode-public-doman". Note that
multiple iterations may produce results like e.g. [2].
Adhere to word boundaries to fix that issue.
This is a fix-up for [1].
[1] c369766f018a88ae4c2ca9cfe46a52e71d387422
[2] LicenseRef-scancode-LicenseRef-scancode-LicenseRef-scancode-public-domain
Please ensure that your pull request adheres to our [contribution guidelines](../CONTRIBUTING.md). Thank …

ScanCodeResultParser: Fix-up the construction of the SPDX expressions

---

Dockerfile
docs/hints-for-use-with-docker.md
scripts/import_certificates.sh
scripts/import_proxy_certs.sh

Enable adding custom certificates via `--build-arg` to a Docker build. The certificates will be added to the Java keystore as well as the system keystore like the proxy-certificates. This is necessary for certain company repositories which provide their own certificate authority and trip up the analyzer. 
Tested internally with repository having certificate problems.

Enable adding custom certificates to the Docker image

---

analyzer/src/main/kotlin/managers/Carthage.kt

According to the documentation of Carthage [1, 2], there is no support
for project- or package-related metadata like license or author
information.
[1] https://github.com/Carthage/Carthage
[2] https://github.com/Carthage/Carthage/blob/84d068b/Documentation/Artifacts.md

Carthage.kt: Remove TODO comments related to retrieving authors

---

spdx-utils/src/main/kotlin/SpdxModelMapper.kt

This picks the change in b3db2cf for FileFormat.kt to this independent
module.

SpdxModelMapper: Fix forFile() to be case-insensitive

---

reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
reporter/src/main/resources/templates/asciidoc/disclosure_document.ftl

This is a follow-up to #3677.
The disclaimer should be shown for unresolved violations as well.

Show disclaimer in disclosure document if there are unresolved rule violations

---

analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml
analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-lockfile.yml
analyzer/src/main/kotlin/managers/Bundler.kt

Extract information about the author of a package from its .gemspec
file and make it available in the metadata of packages and projects.

Bundler: Add support for authors

---

spdx-utils/src/main/kotlin/SpdxExpression.kt
spdx-utils/src/test/kotlin/SpdxExpressionTest.kt

Valid choices for `a AND a` are only `a` and not `a AND a`.

SpdxExpression: Remove duplicated licenses from validChoices

---

analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml
analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt

Currently all packages in the project.spdx.ymls packages list
that are not the project package itself are added to the
ProjectAnalyzerResult packages list. They should only be listed
if there is also a relationship to the package project or one of
it's dependencies. These packages were previously identified and
put into their respective scope.
In the modified test SPDXRef-Saxon should not be in the result file even
though it is in the spdx.project.yml, since it has no relationship to any
other element in the file.

SpdxDocumentFile: Put only packages contained in the project's scopes in the result file

---

clients/fossid-webapp/src/main/kotlin/Extensions.kt
clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
scanner/build.gradle.kts
scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
scanner/src/main/resources/META-INF/services/org.ossreviewtoolkit.scanner.ScannerFactory

This scanner communicates with the FossID API client that
was previously contributed.
In this first implementation, the scanner creates a
project, a scan, runs the scan and fetches the scan
results.
- Add a parameter to FossIdRestService.createScan to be
able to configure scan name before scan's creation.
- Allow a scanner to modify its configuration before
putting the latter in the ScannerRun.
The FossId server configuration is passed through ort.conf :
```
options {
FossId {
serverUrl="https://xxx"
apiKey="xxx"
user="xxx"
}
}
```
[1]: https://fossid.com/

Add a wrapper for FossID scanner

---

reporter/src/main/resources/templates/asciidoc/disclosure_document.ftl

Due to wrong nesting of template tags, the content of license files
is only displayed if copyright statements are defined as well. Fix
the tag order, so that license files are always displayed (unless
they are explicitly excluded).

Disclosure document: Do not drop license files in the appendix

---

analyzer/src/main/kotlin/managers/Bundler.kt
analyzer/src/test/assets/bundler/rspec-3.7.0.json
analyzer/src/test/kotlin/managers/BundlerTest.kt

After obtaining a metadata from gemspec via Bundler, additional metadata
is queried from 'https://rubygems.org' as a json. The authors in this
json are provided as a single String with comma separated authors. Thus,
split this String to correctly obtain each author.
See, for instance, the [rspec  gem](https://rubygems.org/api/v2/rubygems/rspec/versions/3.7.0.json).

Bundler: Parse authors correctly from JSON

---

gradle.properties

This partly fixes a nasty memory leak issue, see
https://github.com/Kotlin/dokka/issues/1405#issuecomment-799666125

Gradle: Upgrade dokka to version 1.4.30

---

advisor/src/main/kotlin/Advisor.kt
advisor/src/main/kotlin/VulnerabilityProvider.kt
advisor/src/main/kotlin/VulnerabilityProviderFactory.kt
advisor/src/main/kotlin/advisors/NexusIq.kt
advisor/src/main/kotlin/advisors/VulnerableCode.kt
advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
cli/src/main/kotlin/commands/AdvisorCommand.kt

I think it is a good idea to split #3638 into multiple PRs.
This PR is a preparation of allowing multiple advisors during a single run.
I am following the idea of the analyzer: The `Analyzer` class has a single instance and is 
to call all the demanded `PackageManager`s. 
For the advisor, the `Advisor` class should also be a single instance that calls several providers of vulnerabilities.
Thus, a new class is created called `VulnerabilityProvider`, from which `NexusIq` and `VulnerablerCode` inherit.
The PR implements the basics of such a structure, but does not change the logic of calling only one `VulnerabilityProvider` so this should not be a breaking change. In a following PR, this should then be extended to multiple providers.

Prepare advisor module for supporting multiple advisors in one run

---

advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt

VulnerableCodeTest: Align on infix notations for assertions where possible

---

build.gradle.kts
cli/build.gradle.kts
downloader/build.gradle.kts
helper-cli/build.gradle.kts

The 5.11 release of JGit is available on Maven Central now.

Gradle: Remove the work-around to look for JGit directly on Eclipse servers

---

model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt
model/src/main/kotlin/licenses/LicenseInfo.kt
model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/test/kotlin/licenses/DefaultLicenseInfoProviderTest.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
model/src/test/kotlin/licenses/TestData.kt

Extend LicenseInfoResolver to generate copyright statements for declared
licenses based on author information.

model: Generate copyright statements from authors

---

reporter/build.gradle.kts
reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
reporter/src/main/resources/templates/asciidoc/disclosure_document.ftl
reporter/src/test/kotlin/utils/FreeMarkerTemplateProcessorTest.kt

Refer to the single commit messages for further details.

Disclosure document: Drop empty sections for NOASSERTION licenses in the appendix

---

reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt

The comment stating that the function is used by templates has been
removed by [1]. Afterwards the function has been made private by [2].
Make the function public again to re-enable calling it from within the
Freemarker template.
[1] 097410208d78243eff1bfe44efc44d626e1aa2f0
[2] 2a19381147aacc5297af7b25e303d18934514131

FreemarkerTemplateProcesser: Make mergeResolvedLicenses() public again

---

cli/src/main/kotlin/commands/AnalyzerCommand.kt
reporter/src/main/kotlin/reporters/CycloneDxReporter.kt

Omit the default separator in calls to joinToString()

---

.github/workflows/static-analysis.yml

This is required to get a baseline e.g. for detekt issues to show up in
the GitHub web UI.

github: Also trigger static analysis on pushes

---

docs/config-file-ort-yml.md
evaluator/src/main/kotlin/PackageRule.kt
evaluator/src/test/kotlin/RuleSetTest.kt
evaluator/src/test/kotlin/TestData.kt
model/build.gradle.kts
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/config/LicenseChoices.kt
model/src/main/kotlin/config/RepositoryConfiguration.kt
model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
model/src/test/kotlin/config/RepositoryConfigurationTest.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
model/src/test/kotlin/licenses/ResolvedLicenseInfoTest.kt
model/src/test/kotlin/licenses/TestUtils.kt
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/funTest/assets/static-html-reporter-test-input.yml
reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
reporter/src/main/kotlin/utils/ReportTableModel.kt
reporter/src/main/kotlin/utils/ReportTableModelMapper.kt
spdx-utils/src/main/kotlin/SpdxExpression.kt
spdx-utils/src/main/kotlin/model/LicenseChoice.kt
spdx-utils/src/test/kotlin/SpdxExpressionTest.kt

Apply license choices specified for a package defined in the repository configuration file.
The choices are used in the `licenseRule` and the `StaticHtmlReporter` and applied in the `effectiveLicense` function of `ResolveLicenseInfo`.
Related to #3396.
CC: @neubs-bsi

Apply license choices specified for a package defined in the repository configuration file

---

cli/src/main/kotlin/commands/UploadResultToSw360Command.kt

The upload-result-to-sw360 command was not able to create releases in
SW360 when using raw declared license data with e.g. whitespaces, which
is not allowed in SW360. Instead of declaredLicenses, the
declaredLicensesProcessed field is used to set the mainLicenseIds of a
release.

UploadResultToSw360Command: Use declaredLicensesProcessed for releases

---

advisor/src/main/kotlin/Advisor.kt
cli/src/main/kotlin/commands/AdvisorCommand.kt

This is a follow up PR to #3761.
Please look at the commit messages for details.

advisor: Allow multiple vulnerability providers in one run

---

evaluator/src/test/kotlin/TestData.kt

As the detected license is added in the OrtResult, no additional license should be contained in the package.

PackageRuleTest: Remove concluded license from only detected license pkg

---

model/src/main/kotlin/config/FileArchiverConfiguration.kt
model/src/main/resources/reference.conf
model/src/test/kotlin/config/OrtConfigurationTest.kt
model/src/test/kotlin/config/ScannerConfigurationTest.kt
reporter/src/funTest/kotlin/reporters/NoticeTemplateReporterFunTest.kt

The adjust the `FileArchiverConfiguration` so that either a file based storage or a PostgreSQL based storage can be configured for the file archiver.
Note: You may utilized the code on branch 'migrate-file-archive-to-postgres' for migrating your file archives from a file storage to postgres, see [1] [2].
[1] https://github.com/oss-review-toolkit/ort/blob/migrate-file-archive-to-postgres/scanner/src/main/kotlin/MigrateFileArchives.kt#L109 
[2] https://github.com/oss-review-toolkit/ort/blob/migrate-file-archive-to-postgres/scanner/src/main/kotlin/MigrateFileArchives.kt#L46-L55.

FileArchiver: Allow configuring the PostgreSQL based storage

---

reporter/src/main/kotlin/reporters/CycloneDxReporter.kt

In single.bom mode, we can expect to have the same behavior with 1 or more projects and therefore have the same filename in all cases.
This can be useful when using the CycloneDx result file in other processing/pipeline

CycloneDxReporter: In single.bom mode, use the default name even for a single project

---

analyzer/src/funTest/assets/projects/synthetic/spdx-project-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/spdx/package/libs/curl/package.spdx.yml
analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml
analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt

Introduce the integration of external document references that
refer to package spdx documents.
External references only get loaded when there is a relationship
referencing to the external document reference id, to avoid
unnecessary loading and parsing.
Resolves #3402.

Add support for external document reference to SPDX document

---

model/src/main/kotlin/config/FileArchiverConfiguration.kt

The `storage` property was renamed to `fileStorage` in 8e1350f. The
renaming was made backward compatible for parsing with hoplite. Make it
also backward compatible for parsing with Jackson, so that old ORT
result files can still be read.

FileArchiverConfiguration: Fix JSON deserialization of old results

---

scanner/src/main/kotlin/Scanner.kt

It can happen that the same identifier appears for a project and for a
package. Possible reasons for this are that the package manager
implementation does not detect that a dependency is also a project and
creates a package instance for it, or that the same identifier appears
for different package managers, for example NPM and Yarn.
If those duplicates are passed to the `PostgresStorage` it fails because
it expects identifiers to be unique.
To fix this make sure to not pass duplicate identifiers to the scanner.
If duplicates are found prefer the project over the package, because it
has likely more accurate metadata.
Other means to further improve this in future are:
- Change the `Scanner` and `ScanResultsStorage` API to take a set of
packages instead of a list.
- Add post-processing to …

Scanner: Do not try so scan projects and packages with the same id

---

reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt

The SPDX package verification code already is lower case, see e.g. the
assertions in ScanCodeResultParserTest.

SpdxDocumentModelMapper: Remove a superfluous toLowerCase() call

---

scanner/src/main/kotlin/storages/PostgresStorage.kt

The `PostgresStorage` splits the packages into chunks and requests the
scan results for each chunk of packages in parallel. If there are more
chunks than connections in the connection pool, it can happen that the
requests wait longer than the default timeout of 30 seconds for a free
connection.
As a quick fix, because this code is currently being rewritten anyway,
limit the number of chunks to be slighty smaller than the size of the
connection pool.
Fixes #3807.

PostgresStorage: Limit the number of chunks when reading results

---

analyzer/src/main/kotlin/managers/Npm.kt

As the issue message says, this *might* be fine, so creating an error is
probably too harsh.

Npm: Lower the issue about a not-installed package to a warning

---

cli/src/main/resources/log4j2.xml
test-utils/src/main/resources/log4j2.xml

The debug logs from this logger completely swamp ORT debug logs which
makes it hard to see through.

Disable the extremely chatty FileSnapshot logger from JGit

---

.github/pull_request_template.md

The relative link [1] is resolved to 'Not Found' page
as GitHub requires branch to be specified.
[1] https://github.com/oss-review-toolkit/ort/CONTRIBUTING.md

pull-request-template: Replace relative link

---

docs/config-file-ort-yml.md
evaluator/src/main/kotlin/PackageRule.kt
evaluator/src/test/kotlin/RuleSetTest.kt
evaluator/src/test/kotlin/TestData.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/config/LicenseChoices.kt
model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
model/src/test/kotlin/config/RepositoryConfigurationTest.kt
model/src/test/kotlin/licenses/ResolvedLicenseInfoTest.kt
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/funTest/assets/static-html-reporter-test-input.yml
reporter/src/main/kotlin/utils/ReportTableModelMapper.kt

Resolves #3396.
Introduce license choices that span the whole project scope and can be overwritten by package specific license choices.

LicenseChoices: Add repository license choices 

---

spdx-utils/src/main/resources/declared-license-mapping.yml
spdx-utils/src/main/resources/simple-license-mapping.yml
spdx-utils/src/test/kotlin/SpdxDeclaredLicenseMappingTest.kt
spdx-utils/src/test/kotlin/SpdxSimpleLicenseMappingTest.kt

@tsteenbe @mnonnenmacher what do you think about adding a test like this? I currently fails with
```
The following elements failed:
GPL=GPL_2_0_ONLY => "GPL" should contain at least one digit
agpl=AGPL_3_0_ONLY => "agpl" should contain at least one digit
fdl=GFDL_1_3_ONLY => "fdl" should contain at least one digit
gfdl=GFDL_1_3_ONLY => "gfdl" should contain at least one digit
gpl-license=GPL_2_0_ONLY => "gpl-license" should contain at least one digit
```
which indeed IMO are entries that should be fixed to *-or-later, as no version is indicated.

Verify that license mappings to *-only have a digit

---

.azure-pipelines.yml
.azure-pipelines/LinuxAnalyzerTest.yml
.azure-pipelines/WindowsAnalyzerTest.yml
Dockerfile
analyzer/src/main/kotlin/managers/Pub.kt
cli/src/main/kotlin/commands/RequirementsCommand.kt
utils/src/main/kotlin/Constants.kt
utils/src/main/kotlin/Utils.kt

Due to the big size (around 1.7Gb) and rare use it is more optimal to
bootstrap Flutter on demand instead of installing it in the Docker
container.
This commit implements the bootstrapping logic for Flutter (which
includes Pub) and removes Flutter from the Docker image and the CI
configurations.
With this change it is now possible to choose the Flutter version by
setting the `FLUTTER_VERSION` environment variable.
Co-authored-by: Martin Nonnenmacher <martin.nonnenmacher@here.com>
Signed-off-by: zhernovs <ext-andriy.zhernovskyi@here.com>

Flutter: Bootstrap Flutter/Pub/Dart

---

downloader/src/funTest/kotlin/vcs/SubversionWorkingTreeFunTest.kt
utils/src/main/kotlin/OkHttpClientHelper.kt

This allows to keep a User-Agent that was explicitly set in a request.

OkHttpClientHelper: Only set a User-Agent if none was set before

---

build.gradle.kts
spdx-utils/build.gradle.kts
utils/build.gradle.kts

Configuring a task is the default action.

Gradle: Omit superfluous configureEach calls

---

docs/config-file-ort-yml.md

Field name is plural not singular per [1].
[1]: https://github.com/oss-review-toolkit/ort/blob/master/model/src/main/kotlin/config/LicenseChoices.kt

docs: Fix incorrect field name in license choice examples

---

.github/workflows/static-analysis.yml

See https://github.com/actions/setup-java/blob/v2/docs/switching-to-v2.md.

GitHub: Upgrade the setup-java action to v2

---

spdx-utils/src/main/kotlin/SpdxException.kt
spdx-utils/src/main/kotlin/SpdxExpression.kt

These plain "retypes" are better kept together with SpdxException.

spdx-utils: Move license choice exceptions to SpdxException

---

scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt

The way the calculation of the package verification code was tested is
highly confusing and just wrong in this context. So just stop doing this
and use the generateSummary() function overload that directly gets a
package verification code. As the package verification code still cannot
be calculated given the input, just pass SpdxConstants.NONE for it even
if that is not explicitly allowed by the SPDX specification, but it
matches the semantics of the tests.

ScanCodeResultParserTest: Stop testing the package verification code

---

analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
analyzer/src/test/kotlin/managers/SpdxDocumentFileTest.kt

Since introducing external document references added the possibility
of just having one package (= the project package) and having the
other packages information be extracted to external document references,
the check for a project package needs to be enhanced.

SpdxDocumentFile: Enhance project package function

---

model/src/main/kotlin/config/ScannerConfiguration.kt
model/src/main/resources/reference.conf
scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
scanner/src/main/kotlin/LocalScanner.kt
scanner/src/main/kotlin/ScanResultsStorage.kt
scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/storages/CompositeStorage.kt
scanner/src/main/kotlin/storages/PostgresStorage.kt

If we already know the concluded license and have authors, we do not
necessarily need to detect licenses and copyrights anymore.

Scanner: Optionally skip scanning packages with a concluded license

---

advisor/src/main/kotlin/advisors/NexusIq.kt
advisor/src/main/kotlin/advisors/VulnerableCode.kt
advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
clients/nexus-iq/src/main/kotlin/NexusIqService.kt
clients/nexus-iq/src/test/kotlin/NexusIqServiceTest.kt
model/src/main/kotlin/Vulnerability.kt
model/src/main/kotlin/VulnerabilityReference.kt
model/src/test/assets/advisor-result-initial.yml
model/src/test/assets/advisor-result-vulnerability-refs.yml
model/src/test/kotlin/AdvisorResultContainerTest.kt
model/src/test/kotlin/VulnerabilityTest.kt

This PR prepares the full integration of VulnerableCode as an advisor.
VulnerableCode supports multiple sources of vulnerability information. Each vulnerability has a list of references to the sources from which information has been drawn. To represent this, the PR extends the data model accordingly.
Note that this is only a change of the data model, but the VulnerableCode advisor implementation is not yet updated to actually populate this data model.

Extend vulnerability model to support multiple sources

---

model/src/main/kotlin/config/PackageConfiguration.kt

Don't allow specifying a path for matching non-Git-Repo projects.
This eliminates an edge case which does not make sense to have in the first place.

PackageConfiguration: Increase the strictness of the VCS matcher

---

spdx-utils/src/main/resources/declared-license-mapping.yml

As seen in [1]. Also see [2].
[1] https://repo1.maven.org/maven2/com/google/re2j/re2j/1.1/re2j-1.1.pom
[2] https://golang.org/LICENSE

declared-license-mapping: Map "The Go license" to BSD-3-Clause

---

spdx-utils/src/main/resources/declared-license-mapping.yml

[1] https://repo1.maven.org/maven2/org/eclipse/emf/org.eclipse.emf.common/2.18.0/org.eclipse.emf.common-2.18.0.pom

declared-license-mapping: Add "The Eclipse Public License Version 2.0"

---

gradle.properties
helper-cli/build.gradle.kts
helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/ExportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/commands/ExportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/ExtractRepositoryConfigurationCommand.kt
helper-cli/src/main/kotlin/commands/GenerateProjectExcludesCommand.kt
helper-cli/src/main/kotlin/commands/GenerateRuleViolationResolutionsCommand.kt
helper-cli/src/main/kotlin/commands/GenerateScopeExcludesCommand.kt
helper-cli/src/main/kotlin/commands/GenerateTimeoutErrorResolutionsCommand.kt
helper-cli/src/main/kotlin/commands/ImportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/commands/ImportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/ImportScanResultsCommand.kt
helper-cli/src/main/kotlin/commands/ListCopyrightsCommand.kt
helper-cli/src/main/kotlin/commands/ListLicenseCategoriesCommand.kt
helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
helper-cli/src/main/kotlin/commands/ListPackagesCommand.kt
helper-cli/src/main/kotlin/commands/RemoveConfigurationEntriesCommand.kt
helper-cli/src/main/kotlin/commands/TransformResultCommand.kt

JSLT [1] supports powerful transformations on JSON data. Possible use cases would be the conversion of existing results to conform to breaking changes in ORT's data model or the manipulation of results to generate test data. I played around with JSLT when I changed the data format for vulnerabilities in the Advisor module. As I found it useful, I thought I could share it. If you think, this is out of scope, just close this PR.
There is one limitation, however: JSLT does not handle tags in YAML and simply drops them. This is a problem with ORT result files because Jackson uses such tags to deal with class hierarchies. Currently the configuration of scan result storages makes use of this mechanism; so a manual post-processing of result files is necessary.
As an example for a JSLT …

Proposal: Add a command to apply a JSLT transformation to an ORT result

---

helper-cli/src/main/kotlin/commands/packageconfig/ExportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/PackageConfigurationCommand.kt
helper-cli/src/main/kotlin/common/Utils.kt

This enables a workflow similar to what we already have for repository configurations.

helper-cli: Add a command to export path excludes from package configs

---

reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
spdx-utils/src/main/kotlin/model/SpdxExternalReference.kt

Seperator is a underscore not a hyphen see [1].
[1]: https://github.com/spdx/spdx-spec/blob/3dddfc34d7e770d4c17fc19f61be8554e3934c3d/schemas/spdx-schema.json#L273

spdx-utils: Fix referenceCategory enum values

---

reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt
spdx-utils/src/main/kotlin/model/SpdxCreationInfo.kt

SPDX reporter uses Instant as type for the creation data in CreatedInfo.
However Instant.toString() returns ISO-8601 string with macro seconds
whilst SPDX specification [1] only requires a precision in whole seconds.
[1]: https://github.com/spdx/spdx-spec/blob/development/v2.2.1/chapters/document-creation-information.md#691-description

spdx-reporter: Fix creation date to be 'YYYY-MM-DDThh:mm:ssZ'

---

helper-cli/src/main/kotlin/commands/packageconfig/ImportLicenseFindingCurationsCommand.kt

The code is implemented in such a way that it actually expects the file
to be present, so let clikt also enforce the existence.

ImportLicenseFindingCurationsCommand: Require the package config file to exist

---

analyzer/src/main/kotlin/managers/Pub.kt
downloader/src/main/kotlin/Downloader.kt
model/src/main/kotlin/config/AdvisorConfiguration.kt
model/src/main/kotlin/config/AnalyzerConfiguration.kt
model/src/main/kotlin/config/ScannerConfiguration.kt
scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml

This avoids null configs to be seralized to ORT result files.

model: Align tool configs to not serialize null values

---

build.gradle.kts

This fixes an IDEA inspection hint.

Gradle: Use HTTPS to link to the Apache-2.0 license

---

analyzer/src/main/kotlin/managers/Bower.kt

This is a quick work-around for #3764 and should be reverted once a
proper fix is in place.

Bower: Allow to run as root, for use in Docker

---

reporter/src/main/resources/templates/asciidoc/vulnerability_report.ftl

Recent changes on the model of vulnerabilities broke this template, as
it now references fields that no longer exist. Change the generation
of vulnerabilities to include all vulnerability references.

vulnerability_report.ftl: Adapt to changes in vulnerability model

---

model/src/main/kotlin/Provenance.kt
model/src/test/kotlin/ProvenanceTest.kt

Deserialization of the `Provenance` class failed if the target type was
`KnownProvenance`, because the `BeanDeserializer` configured for this
class does not have a default constructor.
Remove the annoation that configured `BeanDeserializer` for
`KnownProvenance`, because it was a left-over from testing and not
required anyway.
Also add a test case to make sure that provenance objects can properly
be serialized and deserialized.

Provenance: Fix deserialization

---

helper-cli/src/main/kotlin/commands/ExportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/commands/ExportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/ExportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/ExportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/PackageConfigurationCommand.kt
helper-cli/src/main/kotlin/common/Utils.kt

This enables a workflow similar to what we already have for repository configurations.

helper-cli: Add a command to export curations from package configs

---

model/src/main/kotlin/AdvisorRecord.kt
model/src/test/kotlin/AdvisorRecordTest.kt

AdvisorRecord: Add a getVulnerabilities() function
The function allows obtaining all the vulnerabilities for a specific
package independent on the advisor that produced the result. If the
same vulnerabilities have been retrieved from different advisors (with
potentially different metadata), their references are merged.
This can be useful for rules that operate on advisor results.

Improve the API to access vulnerabilities

---

model/src/main/kotlin/licenses/LicenseInfoResolver.kt

Take the author as-is if it already contains a copyright, e.g. because of
a curation that sets the author with a copyright incl. year.

LicenseInfoResolver: Improve the mapping of authors to copyrights

---

analyzer/src/main/kotlin/managers/Bundler.kt
analyzer/src/main/kotlin/managers/Npm.kt
utils/src/main/kotlin/OkHttpClientHelper.kt

Also handle an IOException thrown by execute() itself.

OkHttpClientHelper: Improve exception handling in downloadText()

---

helper-cli/src/main/kotlin/common/Utils.kt

Use only the "matcher" attributes for determining whether an existing entry shall be replaced.

helper-cli: Improve curation import and export

---

analyzer/src/main/kotlin/managers/GradleDependencyHandler.kt
analyzer/src/test/kotlin/managers/GradleDependencyHandlerTest.kt

Change the exception handling when resolving packages to not create a
dummy package for a failed resolution. That way the affected package
is still listed in the dependency graph, but is no longer contained in
the project's list of packages.
The new behavior is in-line with the Maven package manager
implementation.

GradleDependencyHandler: Remove the creation of a dummy package

---

spdx-utils/src/main/resources/declared-license-mapping.yml

[1]: https://repo.maven.apache.org/maven2/org/sangria-graphql/macro-visit_2.13/0.1.3/macro-visit_2.13-0.1.3.pom

declared-license-mapping: Add "Apache License, ASL Version 2.0"

---

advisor/src/main/kotlin/Advisor.kt
cli/src/main/kotlin/commands/DownloaderCommand.kt
reporter/src/main/kotlin/utils/ReportTableModelMapper.kt
scanner/src/main/kotlin/Scanner.kt

Pragmatically, when being asked to operate on empty input, then doing
nothing is the right thing to do, esp. in library code where the caller
should implement custom error handling.
However, as it is rather unusual to not even have an analyzer result in a
ORT result, still emit a warning in that case.

Do not fail hard if an ORT result contains no analyzer result

---

spdx-utils/src/main/resources/declared-license-mapping.yml

As seen e.g. in
https://repo1.maven.org/maven2/com/solacesystems/solsuite/10.8.1/solsuite-10.8.1.pom
Use the "ort" LicensRef namespace for now as also ScanCode does not
recognize the license yet, see
https://github.com/nexB/scancode-toolkit/issues/2498

declared-license-mapping: Add the Solace Software EULA

---

analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
model/src/main/kotlin/PackageCurationData.kt
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml

The comment is different than the other fields in this class as it is
not patch data, but metadata about the patch. So make it stand out by
moving it to the top. As a wanted side effect, this also makes the comment
go first when rewriting curation files to normalize formatting. And having
the comments first in a file's entry is also good practice, to first
explain why a curation is needed, and then define it, similar to Git
commit messages that explain what the patch is doing.

PackageCurationData: Make the comment go first

---

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml
analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pip-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pipenv-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pipenv-python3-expected-output.yml
spdx-utils/src/main/resources/declared-license-mapping.yml

It does not make sense to map "BSD License" and "The BSD License"
differently. In fact, the version cannot be told in either case. So simply
remove both mappings.
As an example why the version cannot be assumed, take [1] where "The BSD
License" is supposed to mean BSD-3-Clause instead of BSD-2-Clause.
[1] https://repo1.maven.org/maven2/org/antlr/antlr4-master/4.7.1/antlr4-master-4.7.1.pom

declared-license-mapping: Remove conflicting BSD license mappings

---

docs/config-file-ort-yml.md

Add license choices to TOC of `.ort.yml` documentation.

Add license choices to TOC

---

analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
analyzer/src/funTest/assets/projects/synthetic/gradle/curations.yml
analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
analyzer/src/main/kotlin/curation/Sw360PackageCurationProvider.kt
analyzer/src/test/assets/package-curations.yml
analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt
cli/src/funTest/assets/semver4j-analyzer-result.yml
cli/src/main/kotlin/commands/UploadCurationsCommand.kt
model/src/main/kotlin/Package.kt
model/src/main/kotlin/PackageCurationData.kt
model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt
model/src/test/assets/advisor-result-initial.yml
model/src/test/assets/advisor-result-vulnerability-refs.yml
model/src/test/kotlin/PackageCurationTest.kt
model/src/test/kotlin/PackageTest.kt

Removing or fixing broken declared licenses coming from the package meta data is supported by using a "declared license mapping" curation. Adding a declared license which wasn't declared in the original packages' meta data does not make sense,
because the curated package wouldn't reflect reality anymore. Therefore the overwriting is not needed as all valid declared license fixes can be achieved using the mapping approach. Since using a mapping is also superior in any regard remove the means to overwrite a declared license.

Stop supporting overwriting declared licenses

---

reporter/src/funTest/kotlin/reporters/AsciiDocTemplateReporterFunTest.kt

The "kotlin" package is in the list of default imports, see
https://kotlinlang.org/docs/packages.html#default-imports

Remove a superfluous import of kotlin.IllegalArgumentException

---

docs/sw360-integration.md

This is a fixup for 097d88a where the behavior was changed.

sw360-integration: Fix curated fields to include `concludedLicenses`

---

downloader/src/main/kotlin/vcs/Git.kt

Git: Install JGit's .netrc credential provider in addition to ORT's

---

model/src/test/kotlin/config/NexusIqConfigurationTest.kt
model/src/test/kotlin/config/ScannerConfigurationTest.kt

Rename variables etc. to make the tests better comparable.

model: Align the {NexusIq,Scanner}ConfigurationTests

---

Dockerfile

See the updated instructions at [1]. This fixes the Docker image build.
[1] https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html#Ubuntu+and+other+Debian-based+distributions

Dockerfile: Update the sbt Debian repository

---

reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
reporter/src/main/resources/templates/asciidoc/disclosure_document.ftl
reporter/src/main/resources/templates/notice/default.ftl
reporter/src/main/resources/templates/notice/summary.ftl

Instead of searching for it by name.

FreemarkerTemplateProcessor: Use LicenseView constants directly

---

helper-cli/src/main/kotlin/commands/GeneratePackageConfigurationsCommand.kt

The VCS path must be null for all VCS types except for "Git-Repo".
This is a fix-up for 4d94d93e89240977024deaf80d9af3620c1a4dd0.

GeneratePackageConfigurationsCommand: Fix VCS path generation

---

helper-cli/src/main/kotlin/commands/GeneratePackageConfigurationsCommand.kt

Please refer to the commit messages for details.

GeneratePackageConfigurationsCommand: Prevent overwriting output results

---

model/src/main/kotlin/FileFormat.kt

If pretty-printing is enabled, writeValue() needs to be called on the
ObjectWriter, not on the ObjectMapper. This got broken in 3269e2e.
Fixes #3948.

FileFormat: Fix pretty-printing of (JSON) files

---

analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt

SpdxDocumentFile: Remove superfluous parentheses in an expression

---

scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt

The "find all scan results for compatible scanners" tests seem to be
flaky, so provide a clue when failing to help with finding the root
cause.

AbstractStorageFunTest: Give a clue for apparently flaky tests

---

model/src/main/kotlin/Severity.kt
reporter/src/main/kotlin/utils/ReportTableModelMapper.kt

This way a more natural comparison like "severity > Severity.HINT" can
be done.

Severity: Swap ordering of enum members

---

cli/src/main/kotlin/commands/ScannerCommand.kt

Following the discussion on Slack, this commit aligns the return codes of `ScannerCommand` with the recent changes made to the Evaluator (see https://github.com/oss-review-toolkit/ort/pull/3767).
Only return code '2' if there are some issues with severity higher than 'HINT'.

scanner: Align the return code of the ScannerCommand

---

model/src/main/kotlin/Vulnerability.kt
model/src/main/kotlin/VulnerabilityReference.kt
model/src/test/kotlin/VulnerabilityTest.kt
reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt

Add a helper method to generate human-readable string based on the
given score and scoring system of a vulnerability. This method can
be used in the template files in order to provide further information
about the vulnerabilities in the report.

TemplateHelper: Generate human-readable string for vulnerability scores

---

.azure-pipelines/LinuxAnalyzerTest.yml
.azure-pipelines/LinuxTest.yml
.azure-pipelines/WindowsAnalyzerTest.yml
.azure-pipelines/WindowsTest.yml
analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-lockfile.yml

Invalidate the Azure cache for Gradle, as the Gradle build cache seems
to be corrupt due to Kotlin compiler backend changes.

Invalidate Azure build caches

---

reporter/src/main/kotlin/HowToFixTextProvider.kt

Add more default imports to the `HowToFixTextProvider` scripts so that
they can use the same model classes and utility functions as evaluator
scripts.

HowToFixTextProvider: Add more packages to the default imports

---

Dockerfile

Adding the `-y` flag prevents the `add-apt-repository` command from requesting
user input for conformation for adding the git-core repository. This request for
user input was blocking the Docker build as it kept waiting.
The issue of user input occured when building with `podman` version 1.6.2 on
Ubuntu 20.04.2 LTS.
Closes #3969
Signed-off-by: Nico Rikken <nico.rikken@alliander.com>

Dockerfile: Prevent user input for add-apt-repository

---

spdx-utils/src/main/kotlin/model/SpdxDocument.kt
spdx-utils/src/test/kotlin/SpdxDocumentModelTest.kt
spdx-utils/src/test/resources/spdx-spec-examples/SPDXYAMLExample-2.2-no-relationship-describes-or-document-describes.spdx.yaml

After trying to create a valid spdx file with external references and basing them on the existing example files in the functional tests, I discovered that the inital spdx file from the functional tests do not pass validation with the spdx-java cli tool [2]. Only after adding a relaltionship of the type `DESCRIBES` did the files pass validation. 
In order for an spdx document to be valid it needs at least
one relationship of type DESCRIBES, as can be seen in the
implementation of the SPDX java library of spdx in the
verify method of the SpdxDocument [1].
The changes are tested and the funTest spdx files were
changed accordingly. Validation of the file  was done
with spdx-java-tool[2]. A cli tool that can be used to
verify spdx files with SPDX version 2.2
[1] …

Make SPDX document require either DESCRIBES relationship or a documentDescribes

---

utils/src/main/kotlin/OrtAuthenticator.kt
utils/src/test/kotlin/OrtAuthenticatorTest.kt

This reverts commit c5c5c4f. As it turns out, the original
implementation to always use the first matching entry is exactly how the
Git CLI behaves. ORT aims to be compatible to the Git CLI to avoid confusion
when it is being used as a fallback for the JGit implementation.
But more importantly, after careful rereading of [1] and esp. [2], the
behavior seems to also be in line with the documentation: When saying "It
must be the last entry (after all machine entries); otherwise, entries
that follow it will be ignored" it is not supposed to mean that not
having the default entry last would be a syntax error, but that it
simply does not make sense, because all entries after a default entry
are irrelevant.
[1] https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html
[2] …

Revert "OrtAuthenticator : In .netrc, raise 'machine' precedence"

---

analyzer/src/funTest/assets/projects/synthetic/cargo-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/cargo/Cargo.toml
analyzer/src/main/kotlin/managers/Cargo.kt

Cargo allows to declare non-SPDX licenses only by referencing a license
file. If the `license-file` property is used, map the value to
`LicenseRef-ort-unknown-license-reference` to indiciate that some
license is declared, instead of ignoring the property. This
implementation is similar to how the "SEE LICENSE IN ..." values are
handled in NPM.

Cargo: Map the license-file property to an unknown license

---

downloader/src/main/kotlin/vcs/GitRepo.kt

For all 2.14 releases of repo until the current stable release 2.14.2
running sync with the `--fetch-submodules` option fails, for example for
the project used in `GitRepoFunTest` with these errors:
```
$ repo sync -c --force-sync --fetch-submodules
Fetching: 100% (2/2), done in 4.304s
Garbage collecting: 100% (2/2), done in 0.004s
Fetching: 100% (2/2), done in 0.010s
Garbage collecting: 100% (2/2), done in 0.004s
error: submodules/commons-text/: Cannot checkout oss-review-toolkit/ort-test-data-git-submodules/commons-text due to missing network sync; Run `repo sync -n oss-review-toolkit/ort-test-data-git-submodules/commons-text` first.
error: Cannot checkout oss-review-toolkit/ort-test-data-git-submodules/commons-text
error: submodules/test-data-npm/: Cannot checkout …
```

GitRepo: Downgrade repo to 2.13.8

---

reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt

This is useful to eventually ignore hints only.

FreemarkerTemplateProcessor: Make hasUnresolved*() take a threshold

---

scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt

The main goal of this PR is to prepare for the removal of `RepositoryProvenance.originalVcsInfo`.
Therefore two setups of two test cases which deal with that `originalVcsInfo` are improved.
These preparations can be found in the top-most two commits.
All other commits below are miscellaneous improvements to the code.

AbstractStorageFunTest Improvements

---

scanner/src/main/kotlin/LocalScanner.kt

Esp. when having reconfigured the sourceCodeOrigins, it can happen that
the stored scan results contain multiple results for the same package
with different provenance. If also createMissingArchives is enabled,
this could have led to name clashes in the created temporary
directories. Solve that by adding another directory level that is named
after the provenance.

LocalScanner: Name temporary directories also after the provenance

---

cli/src/main/kotlin/commands/DownloaderCommand.kt
cli/src/main/kotlin/commands/EvaluatorCommand.kt
downloader/src/funTest/kotlin/DownloaderFunTest.kt
model/src/main/kotlin/config/DownloaderConfiguration.kt
model/src/main/resources/reference.conf
model/src/test/kotlin/config/OrtConfigurationTest.kt

This PR adds a configuration to `ort.conf` that enables the user to limit the packages that are bundled in the source code bundle.
If no categories are configured, the implementation falls back to archive all packaged. This has the the benefit of providing backwards compatibility to the current archive functionality and it doesn't force the user to add a configuration to use the archive functionality.

Downloader: Limit archiving source code to configured categories

---

analyzer/src/main/kotlin/managers/GoMod.kt
analyzer/src/test/kotlin/managers/GoModTest.kt

See https://golang.org/ref/mod#pseudo-versions.

GoMod: Extract the revision from versions in "pseudo version" format

---

analyzer/src/main/kotlin/managers/GoMod.kt
analyzer/src/test/kotlin/managers/GoModTest.kt

Properly determine VCS URL and path if the package resides in a subdirectory of the Git repository.

GoMod: Fix determining the VCS info for packages from mono repos

---

model/src/main/kotlin/utils/DatabaseUtils.kt
model/src/main/kotlin/utils/PostgresFileArchiverStorage.kt
scanner/src/main/kotlin/storages/PostgresStorage.kt

This PR fixes #4009 by explicitly referring to the correct database connection when starting a new transaction.

Use correct database connection when starting transactions

---

model/src/main/resources/reference.conf

To maintain consistency with the other configurations.

reference: Remove unnecessary comma from downloader configuration

---

model/src/main/kotlin/utils/DatabaseUtils.kt

The tableExists() extension function uses TransactionManager.current()
to access the database connection. This is causing a warning because
the receiver of the extension function is not used. Fix this by
implicitly referencing this transaction, which also seems more natural
and makes sure that actually the correct database connection is used.

DatabaseUtils: Use this transaction in tableExists()

---

analyzer/src/main/kotlin/managers/GoMod.kt
analyzer/src/test/kotlin/managers/GoModTest.kt

GoMod: Handle the version suffix '+incompatible'
The '+incompatible' suffix is just an indication about compatibility for
the package manager. In particular there won't be any Git tags which
contain that suffix in their name. Just drop the suffix to make the
version guessing / matching to remote tags work. See also [1].
[1] https://golang.org/ref/mod#incompatible-versions

GoMod: Handle the version suffix '+incompatible'

---

README.md
model/src/main/kotlin/config/ScanStorageConfiguration.kt
model/src/main/resources/reference.conf
model/src/test/kotlin/config/OrtConfigurationTest.kt

schema now is not required and always fallback on postgresql default
public schema.
Custom schemas need to be created and granted previously on database
Signed-off-by: Helio Chissini de Castro <helio@kde.org>

postgresql: Use default schema if not defined

---

downloader/src/main/kotlin/VersionControlSystem.kt

When a GoMod package originates from a monorepo, the Git tag must
contain the module path as prefix [1]. For example, the Git tag for
package `GoMod::github.com/Azure/go-autorest/autorest/date:v0.1.0` is
`autorest/date/v0.1.0`.
Executing filterVersionNames() for above package throws an IOException
for above package, because it finds multiple matching tags. Add a
fallback to "${pkg.vcsProcessed.path}/${pkg.id.version}/" to fix that
problem.
The handling differes a bit compared the one for Lerna directly above, so that it works also in case one module is in a parent directory of another. In this case the Git tags share a common prefix, so addGuessedRevision() would not work.
Note: Mapping symbolic names to versions in GoMod is complex [1,2,3].
So, it would be better to let the original code …

Support some GoMod style Git tag format for guessing revisions

---

analyzer/src/main/kotlin/managers/utils/NodeSupport.kt

NodeSupport: Avoid invalid logging on non-ORT classes

---

analyzer/src/funTest/kotlin/GitRepoFunTest.kt
analyzer/src/funTest/kotlin/managers/Extensions.kt
analyzer/src/funTest/kotlin/managers/MavenFunTest.kt
analyzer/src/funTest/kotlin/managers/SbtFunTest.kt
analyzer/src/main/kotlin/managers/Maven.kt
analyzer/src/main/kotlin/managers/MavenDependencyHandler.kt
analyzer/src/test/kotlin/managers/MavenDependencyHandlerTest.kt

This PR is related to #3825. It converts the package manager implementation for Maven to the dependency graph format.

Maven: Switch to the dependency graph format

---

.github/workflows/automatic-rebase.yml

This is to align with the other used actions. As a side note, version
1.5 includes the fix for https://github.com/cirrus-actions/rebase/pull/78.

automatic-rebase: Refer to the action by repository and tag

---

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm-expected-output-no-lockfile.yml
analyzer/src/main/kotlin/PackageManager.kt

Make some log and issue messages unambiguous, to enable better resolutions and for debugging.
Note: the change may break the matching of existing issue resolutions.

PackageManager: Improve log and issue messages

---

analyzer/src/main/kotlin/managers/GradleDependencyHandler.kt
analyzer/src/main/kotlin/managers/MavenDependencyHandler.kt

This aligns the implementation with MavenDependencyHandler.linkageFor()
for easier comparison.

GradleDependencyHandler: Inline Dependency.linkage()

---

analyzer/src/main/kotlin/managers/GradleDependencyHandler.kt
analyzer/src/main/kotlin/managers/MavenDependencyHandler.kt
analyzer/src/main/kotlin/managers/utils/DependencyGraphBuilder.kt
analyzer/src/main/kotlin/managers/utils/DependencyHandler.kt
analyzer/src/test/kotlin/managers/MavenDependencyHandlerTest.kt

The dependency graph representation uses `String` as type for the
package identifiers. The package managers Maven and Gradle which use this
dependency graph representation do not parse the identifiers of the
packages into `Identifier` instances until right after the analyzer
result creation. Actually, that parsing happens when
`ortResult.getProjects()` is called by the analyzer command, see [1].
As consequence, the pre-condition checks implemented in the constructor
of `Identifier` are executed after the analyzer result is created. When
that check fails the analyzer command exits with an exception, e.g.
without any result.
Change the return type of `GradleDependencyHandler.identifierFor()` to
`Identifier` to execute these checks as early as possible. This in fact
turns that uncaught …

analyzer: Fail gracefully when dependency graph contains invalid IDs

---

analyzer/src/main/kotlin/managers/GradleDependencyHandler.kt
analyzer/src/main/kotlin/managers/MavenDependencyHandler.kt
analyzer/src/main/kotlin/managers/utils/DependencyGraphBuilder.kt
analyzer/src/main/kotlin/managers/utils/DependencyHandler.kt
analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
analyzer/src/test/kotlin/managers/GradleDependencyHandlerTest.kt
analyzer/src/test/kotlin/managers/MavenDependencyHandlerTest.kt
model/src/main/kotlin/DependencyGraph.kt
model/src/test/kotlin/DependencyGraphTest.kt
model/src/test/kotlin/ProjectTest.kt

Change the Identifier type from String to Identifier in several classes related to the dependency graph and rename a few variables. See the individual commit messages.

DependencyGraph: Consistently use Identifier as type for IDs

---

downloader/src/main/kotlin/VersionControlSystem.kt
downloader/src/main/kotlin/vcs/Cvs.kt
downloader/src/main/kotlin/vcs/Git.kt
downloader/src/main/kotlin/vcs/GitRepo.kt
downloader/src/main/kotlin/vcs/Mercurial.kt
downloader/src/main/kotlin/vcs/Subversion.kt

Instead of just a Boolean, return a Result object encapsulating the
originally requested revsion for convenience, or any occurred exception.
This eases the debugging of download failures.
Resolves #3952.

downloader: Return a Result object from updateWorkingTree()

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/SetLabelsCommand.kt

Add a command to set labels in an ORT result file and optionally remove
existing labels.

helper-cli: Add a command to set the labels in an ORT result

---

.azure-pipelines/LinuxAnalyzerTest.yml
.azure-pipelines/LinuxTest.yml

Do not unnecessarily export PATH, but just prepend to it in the end
using the dedicated Azure logging command. Ensure that directories being
downloaded to exist. Prefer $HOME over ~ as the latter does not get
expanded in all scenarios.

azure-pipelines: Make prepending to PATH on Linux more robust

---

.github/dependabot.yml

We do not want dependabot to update the dependencies of test projects.
As there is no option to disable dependabot for a directory, enable it
only for the projects where we want it to run.
Note that we do not enable dependabot for Gradle because it does not
support defining versios in gradle.propertes [1] and we manually check
for Gradle dependency updates using the `dependencyUpdates` Gradle task
on a regular basis.
[1] https://github.com/dependabot/dependabot-core/issues/1618

Enable dependabot only for github-actions and reporter-web-app

---

spdx-utils/src/main/kotlin/SpdxLicense.kt
spdx-utils/src/main/resources/licenses/BSD-3-Clause-No-Military-License
spdx-utils/src/main/resources/licenses/CDL-1.0

Done by running "./gradlew :spdx-utils:generateSpdxEnums". For details
see https://github.com/spdx/license-list-XML/releases/tag/v3.13.

spdx-utils: Regenerate SPDX enums to update to license list version 3.13

---

cli/build.gradle.kts
gradle.properties

The custom "fatJar" code causes Kotlin 1.5 to hang with Gradle 7 [1].
Work around that by using the anyway more powerful "shadow" plugin [2].
[1] https://youtrack.jetbrains.com/issue/KT-46559#focus=Comments-27-4909120.0-0
[2] https://github.com/johnrengelman/shadow

Gradle: Replace custom "fatJar" code with the "shadow" plugin

---

cli/src/funTest/assets/semver4j-analyzer-result.yml
downloader/src/funTest/kotlin/BeanUtilsFunTest.kt
downloader/src/main/kotlin/Downloader.kt
model/src/main/kotlin/Provenance.kt
model/src/main/kotlin/ScanResult.kt
model/src/test/assets/advisor-result-initial.yml
model/src/test/assets/advisor-result-vulnerability-refs.yml
model/src/test/kotlin/ProvenanceTest.kt
reporter-web-app/public/index.html
reporter-web-app/src/models/Provenance.js
scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt

The purpose of the provenance is to point to some code location. That
location is either a source artifact, a VCS location / revision or
an unknown location.
The main use case in ORT for provenance is to describe what has been
downloaded or scanned. For that purpose the original VCS information is
irrelevant. Remove it to make provenance be usable for that single
purpose. If it should become necessary to also have the original
provenance a separate attribute can be added elsewhere.
Note that finding a scan result for a given package does not involve the
`originalVcsInfo`, in fact all its attribute values are contained also
in `vcsInfo` except for the `resolvedRevision`.
Note: The change is marked as breaking, because "old" scan result storage entries for packages without a revision in …

RepositoryProvenance: Remove the `originalVcsInfo` property

---

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
analyzer/src/funTest/assets/projects/external/multi-kotlin-project-expected-output-cli.yml
analyzer/src/funTest/assets/projects/external/multi-kotlin-project-expected-output-core.yml
analyzer/src/funTest/assets/projects/external/multi-kotlin-project-expected-output-root.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-android-expected-output-app.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-android-expected-output-lib.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app-2.14.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app-3.4.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-library-expected-output-app.yml
analyzer/src/funTest/assets/projects/synthetic/gradle-library-expected-output-lib.yml
analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/yarn-workspaces-expected-output.yml
analyzer/src/main/kotlin/managers/Gradle.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/utils/DependencyGraphBuilder.kt
analyzer/src/test/kotlin/managers/GradleDependencyHandlerTest.kt

Slightly simplify the code of affected package managers to construct the dependency graph. Adapt the expected test results accordingly.

Drop scopes with no dependencies from results

---

analyzer/src/funTest/kotlin/managers/Extensions.kt
analyzer/src/main/kotlin/PackageManagerResult.kt
analyzer/src/main/kotlin/managers/Gradle.kt
analyzer/src/main/kotlin/managers/Maven.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/Pub.kt

This is a minor simplification/optimization for package managers using the dependency graph format. Refer to the commit messages for further details.

Don't use a sorted set for shared packages in PackageManagerResult

---

clients/fossid-webapp/src/main/kotlin/Extensions.kt
clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt

The FossID server is not consistent. It usually returns a List or a Map,
but if there is no entry, it returns data:false.
Hence this commit wires a custom Jackson deserializer that abstracts
this behavior.
It also removes the previous toList() function who attempted at doing
this abstraction.

fossid-webapp: use custom Jackson deserializer

---

downloader/src/main/kotlin/VcsHost.kt

See: https://kotlinlang.org/docs/whatsnew15.html#stable-locale-agnostic-api-for-upper-lowercasing-text.

VcsHost: Replace usage of deprecated `toLowerCase()` with `lowercase()`

---

build.gradle.kts
scripts/import_proxy_certs.sh

Note that the test projects partly still refer to JCenter, but that probably is even a good idea, to verify that we can deal with projects that still refer to JCenter.

Remove (some) references to JCenter

---

clients/fossid-webapp/src/main/kotlin/EntityResponseBody.kt
clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
clients/fossid-webapp/src/test/assets/return-type/mappings/apiphp-list_scan_for_project_exaclty_one.json
clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt

This bug addresses a regression introduced by https://github.com/oss-review-toolkit/ort/pull/4045.
The FossID `get_all_scans` operation has a bug and returns an array if only one scan is returned, otherwise a map.
We have to handle this case, plus the one the other PR was dealing with i.e. handling `data:false` when there is no result.
The result is a new Jackson serializer that handles all these cases.
This commit also contains a new test exhibiting the bug.

fossid-webapp: Fix regression in response deserialization

---

analyzer/src/funTest/assets/projects/synthetic/gomod-expected-output.yml
analyzer/src/main/kotlin/managers/GoMod.kt

Using the source artifact URL pointing to a GO proxy is more fragile
compared to using the VCS info. So, avoid using / scanning that source
artifact URL by setting it only in case the VCS info is not available.

GoMod: Use the source artifact URL only as fallback

---

analyzer/src/main/kotlin/managers/GoMod.kt

Previously, VcsHost was only used for "github.com". Make use of the host
detection in VcsHost instead to support more hosts.
This way the fallback to proxy artifacts, for which we have only limited
support according to the code comments, might be triggered less often.

GoMod: Support all hosts known to VcsHost

---

analyzer/src/main/kotlin/managers/Composer.kt

The --ignore-platform-reqs option allows to avoid install failures due to PHP version mismatch or absent PHP extensions (e.g. gd, dom, etc.) cf . https://getcomposer.org/doc/03-cli.md#install-i Fix issue #4109
Signed-off-by: Camille Moulin <cmoulin@inno3.fr>

Composer : ignore platform specific requirements

---

reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/main/kotlin/utils/ReportTableModelMapper.kt
spdx-utils/src/main/kotlin/SpdxExpression.kt
spdx-utils/src/test/kotlin/SpdxExpressionTest.kt

Add a function to sort SPDX expressions lexicographically and use it for the effective license in the Static HTML reporter for a start.

SpdxExpression: Add a function to sort expressions lexicographically

---

model/src/main/kotlin/AnalyzerResult.kt
model/src/main/kotlin/DependencyGraph.kt

Add a function to collect issues from a `DependencyGraph` and use it in
the `AnalyzerResult` to collect issues also from graphs without having
to resolve them first.
Fixes #4105.

AnalyzerResult: Collect issues from dependency graphs

---

model/src/main/kotlin/AnalyzerResult.kt

The map returned by DependencyGraph.collectIssues() associates only
those packages to issues that actually have issues, so this check is
unnecessary here. This is a fixup for 71b8949.

AnalyzerResult: Remove a superfluous isNotEmpty() check

---

cli/src/main/kotlin/OrtMain.kt

Not the count comparison, but the threshold comparison should have been
changed in 6b08f15. Fix this, and also adapt the printed message
accordingly.

OrtMain: Fixup getting the severity count

---

downloader/src/main/kotlin/Downloader.kt
helper-cli/src/main/kotlin/common/Utils.kt
model/src/main/kotlin/config/PackageConfiguration.kt
reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt
utils/src/main/kotlin/Extensions.kt
utils/src/test/kotlin/ExtensionsTest.kt

The usual way of dealyíng with repositories requiring authentication
in FossID is by adding the public key of the FossID instance in the
repository and using the SSH protocol.
Unfortunately, in several environments, SSH is not available or
forbidden and FossID has no mechanisms of managing HTTP credentials.
The usual workaround is to use a netrc file but this requires admin
access to the system running the FossID instance.
This commit is an alternative: it extracts credentials from the system
running ORT and prepends them to the repository URL, before giving it
to FossID.
Please note that doing so is highly insecure because the credentials
will be visible in FossID logs. Therefore this behavior is an opt-in
option that must be enabled with the scanner option
"credentialsFromNetrc".
Please …

fossid-webapp: add credentials from netrc file to repo URL

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/SplitCurations.kt

The command creates a directory structure in the format
type/namespace/package.yml.
If no namespace is available the structure is type/package.yml.
This directory structure is intended to be used with the
`--package-curations-dir` command.
Related to #4128.

helper-cli: Add a command to split the curations.yml

---

utils/src/test/kotlin/ExtensionsTest.kt

This is a fixup for a recent refactoring in 9a0b5f6.

ExtensionsTest: Improve replaceCredentialsInUri() tests

---

helper-cli/src/main/kotlin/commands/SplitCurations.kt

This is a fixup for 503842005511772b695ce23bdbd520cad0b9e658.
Curations also need to be persisted as a list, which is the required
format for the `--package-curations-dir` option.

SplitCurations: Ensure curations for one package are persisted into a single file

---

gradle.properties

This fixes a race condition in the Kotlin compiler in conjunction with
Gradle [1][2] that we occasionally run into [3].
[1] https://github.com/JetBrains/kotlin/releases/tag/v1.5.20-RC
[2] https://youtrack.jetbrains.com/issue/KT-46820
[3] https://dev.azure.com/oss-review-toolkit/ort/_build/results?buildId=4660&view=logs&j=fa363831-c637-5773-1163-373ecf422174&t=7d0e4a4e-4b6c-5bd7-aae6-5d2ee8f765e2&l=189

Gradle: Upgrade to Kotlin 1.5.20-RC

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/SplitCurationsCommand.kt
helper-cli/src/main/kotlin/commands/packagecuration/CreateCommand.kt
helper-cli/src/main/kotlin/commands/packagecuration/PackageCurationCommand.kt
helper-cli/src/main/kotlin/commands/packagecuration/SplitCommand.kt
helper-cli/src/main/kotlin/common/Utils.kt

The directory structure from split-curations is reused.

Add ORT helper command to create a new curation in the correct directory structure

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/packagecuration/PackageCurationsCommand.kt
helper-cli/src/main/kotlin/common/Utils.kt

Helper: Use underscore for package-curations if no namespace exists

---

helper-cli/build.gradle.kts

To be able to build a fat JAR analogical to the cli.

Gradle: Apply shadow plugin for helper-cli

---

Dockerfile

This does not seem to be required anymore with recent Docker versions,
and removing it simplifies upcoming Copyright header checking logic.

Dockerfile: Remove the experimental syntax header

---

Dockerfile

This is a fixup for 8b07e14 which dropped this header completely, but
Azure DevOps seems to run a version of Docker that defaults to a
different frontend syntax version, so explicitly specify it again.
Also see [1].
[1] https://github.com/moby/buildkit/blob/fa632c5/frontend/dockerfile/docs/syntax.md#build-mounts-run---mount

Dockerfile: Be explicit about the required frontend syntax version

---

helper-cli/src/main/kotlin/commands/packagecuration/CreateCommand.kt
helper-cli/src/main/kotlin/commands/packagecuration/SplitCommand.kt
helper-cli/src/main/kotlin/common/Utils.kt

Ensure that curations created via `helper-cli` use a block comment.

Helper curations commands: Use block comments

---

analyzer/src/funTest/kotlin/GitRepoFunTest.kt
analyzer/src/funTest/kotlin/managers/SbtFunTest.kt
analyzer/src/main/kotlin/managers/Gradle.kt
analyzer/src/main/kotlin/managers/GradleDependencyHandler.kt
analyzer/src/main/kotlin/managers/Maven.kt
analyzer/src/main/kotlin/managers/MavenDependencyHandler.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/NpmDependencyHandler.kt
analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
analyzer/src/test/kotlin/managers/GradleDependencyHandlerTest.kt
cli/src/funTest/kotlin/OrtMainFunTest.kt
model/src/main/kotlin/AnalyzerResult.kt
model/src/main/kotlin/utils/DependencyGraphBuilder.kt
model/src/main/kotlin/utils/DependencyGraphConverter.kt
model/src/main/kotlin/utils/DependencyHandler.kt
model/src/test/kotlin/utils/DependencyGraphConverterTest.kt
scanner/src/funTest/kotlin/scanners/FileCounterScannerFunTest.kt
test-utils/src/main/kotlin/Utils.kt

This PR is part of #4069. It adds a generic converter for analyzer results that generates dependency graphs if necessary. It also adds a custom serializer that triggers this conversion automatically before writing the analyzer result.
Adding the custom serializer was a bit problematic because the conversion logic is part of the `analyzer` module; so the serializer cannot be placed in `model` where the standard object mappers are created. I therefore introduced a mechanism via Java's `ServiceLoader` that allows customization of these mappers from other modules. If you have better suggestions, please let me know.
Note that there are still some quirks until #4069 is completely solved. Currently, there are format conversions when loading and saving ORT results in single steps. (These …

Write the dependency graph format for all package managers

---

README.md

This is a fix up for 52edab04ac297e3ef394a7b7271eae3e068d0958.

README.md: Fix a broken link

---

README.md
analyzer/src/main/kotlin/managers/GoMod.kt

Meanwhile VCS detection capababilities have been added which are not
identical to / using the originial (GoMod) tool, but are good enough to
remove the experimental state.

analyzer: Remove the obsolete "experimental" state from GoMod

---

cli/src/main/kotlin/commands/DownloaderCommand.kt
cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
utils/src/main/kotlin/Utils.kt

Add a new command line option --attach-sources in order to attach sources
of packages if they exist. The Downloader is used to download the sources of
the package and it's packed as a ZIP file in a temporary directory.
Resolves #3998.

UploadResultToSw360Command: Add a new command line option to attach sources

---

analyzer/src/main/kotlin/managers/Pub.kt

Newer releases of Flutter are only available from the updated URL. Note
that older releases can be downloaded from the updated URL as well.

Pub: Update the Flutter download URL

---

helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt

When calling
./gradlew :helper-cli:run --args="list-licenses --help"
clikt already displays these as
--offending-severity [HINT|WARNING|ERROR]

ListLicensesCommand: Drop hard-coded allowed enum values

---

analyzer/build.gradle.kts
cli/build.gradle.kts
helper-cli/build.gradle.kts

The URL seems to have changed as part of migrating away from JCenter.

Gradle: Update the URL to the repo hosting the API tooling

---

.azure-pipelines/LinuxAnalyzerTest.yml
Dockerfile

Download the archive instead of cloning the repository to reduce
execution time.

Docker/Azure: Avoid cloning the CocoaPods Git repository

---

reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
reporter/src/test/kotlin/utils/FreeMarkerTemplateProcessorTest.kt

This is part of resolving #4096. Note that this implicitly changes the
default value used for hasUnresolvedIssues() and
hasUnresolvedRuleViolations() from Severity.HINT to Severity.WARNING.

reporter: Make the TemplateHelper adhere to severeIssueThreshold by default

---

helper-cli/src/main/kotlin/commands/packagecuration/PackageCurationsCommand.kt
helper-cli/src/main/kotlin/commands/packagecuration/SetCommand.kt

One use case for this is removing organizatinon internal (curation)
data from a given ORT file prior to sharing it externally.

helper-cli: Add a command to set the package curations for a ORT file

---

analyzer/src/main/kotlin/PackageManager.kt

Use the more general term as done throughout the code base.

PackageManager: Rename "error" variables to be "issues"

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/SetDependencyRepresentationCommand.kt

In future, all ORT results will use the dependency graph format. It
can therefore be useful to have a command that does a corresponding
conversion on existing result files.
The command supports different types of result files. It is also
intended to be used to convert the expected test results to the new
format.

Helper-cli: Add a command to convert results to the graph format

---

model/src/main/kotlin/AnalyzerResult.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/ScanRecord.kt

These annotation do not seem to be required anymore.

model: Remove a few unneeded @Suppress("UNUSED") annotations

---

analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
model/src/main/kotlin/AnalyzerResult.kt

This fixes a regression introduced in d76ec51 with the custom
serializer for AnalyzerResult; the property was overlooked then.

AnalyzerResult: Take hasIssues property into account on serialization

---

analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt

Change the test assertions to accept results that either use a
dependency graph or the classic tree format. Otherwise, tests for
package managers that produce a dependency graph fail.
Note: Some test classes derived from this base class must have been
failing for a while now. This has not yet been noticed because these
tests are not executed by the default CI pipeline.

AbstractIntegrationSpec: Support results with dependency graphs

---

cli/src/main/kotlin/OrtMain.kt

This is a fixup for 17085cb. While at it, remove a not strictly
necessary check for the count to be greater than 0.

OrtMain: Fix adding up the count of severe issues

---

analyzer/src/main/kotlin/managers/CocoaPods.kt

The mentioned command is not used.

CocoaPods: Remove an obsolete comment

---

analyzer/src/main/kotlin/managers/CocoaPods.kt

Don't throw a NPE in case a Podspec cannot be found in the default Specs
repository. Use an empty package instead. This is particularly important
in case the Podfile uses non-default Specs repositories, which are not
yet supported in ORT.

CocoaPods: Gracefully handle absent Podspecs

---

scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt

As a preparation for removing the fileCount, test other properties of a
ScanSummary.

ScanCodeResultParserTest: Test other properties than the fileCount

---

advisor/src/main/kotlin/advisors/VulnerableCode.kt

Check for the scores to be empty already before the mapping to clarify
the intention.

VulnerableCode: Simplify VulnerabilityReference.toModel()

---

model/src/main/kotlin/VulnerabilityReference.kt

A VulnerabilityReference has a nullable severity, so also handle that in
in getSeverityString(), and generalize the scoring system matching to be
able to handle more cases.

VulnerabilityReference: Rewrite getSeverityString() to match more systems

---

helper-cli/build.gradle.kts
helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/packageconfig/PackageConfigurationCommand.kt
helper-cli/src/main/kotlin/commands/packagecuration/PackageCurationsCommand.kt
helper-cli/src/main/kotlin/commands/repoconfig/RepositoryConfigurationCommand.kt
helper-cli/src/main/kotlin/commands/scanstorage/DeleteCommand.kt
helper-cli/src/main/kotlin/commands/scanstorage/ScanStorageCommand.kt

While this is quite a specific command, it is required for https://github.com/oss-review-toolkit/ort/issues/2848.
Inconsistencies in the scan storage caused by switching the prefered source can be cleaned up using this `helper-cli` command.

helper-cli: Add command to delete entries from postgres scan storage

---

README.md

This way statements are not merged into a single line.

README: Fix formatting of Copyright statements

---

scanner/src/main/kotlin/scanners/fossid/FossId.kt

When the 'noWait' parameter is set, ORT doesn't wait for repositories
to be downloaded nor scans to be completed.
Scan results are then only available in the FossID instance.

fossid-webapp: Add an asynchronous mode to the scanner

---

model/src/main/kotlin/utils/DependencyGraphConverter.kt
model/src/test/kotlin/utils/DependencyGraphConverterTest.kt

DependencyGraphConverter missed the issues stored at PackageReferences
when constructing a DependencyGraph. By overriding the
issuesForDependency() function in the private ScopesDependencyHandler
class, they are now preserved.

DependencyGraphConverter: Take issues of dependencies into account

---

helper-cli/src/main/kotlin/commands/SetDependencyRepresentationCommand.kt

One use case for SetDependencyRepresentationCommand is to convert the
YAML files with expected results of ORT's functional tests. This is
currently not possible, however, because most of these files contain
special placeholders that are dynamically replaced during test
execution and that cause the deserialization to result objects to
fail.
Therefore, add logic to handle such placeholders. If enabled via a new
command line flag, critical placeholders are replaced by allowed
values before deserialization. When writing the result of the
conversion they are restored again.

helper-cli: Support placeholders when changing the dependency format

---

.azure-pipelines/LinuxAnalyzerTest.yml
.azure-pipelines/WindowsAnalyzerTest.yml

For running the analyzer tests we do not need to build the
reporter-web-app, so explicitly exclude the task.

Azure: Do not build the reporter-web-app in analyzer tests

---

model/src/main/kotlin/AnalyzerResult.kt
model/src/main/kotlin/CuratedPackage.kt
reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
reporter/src/main/kotlin/utils/ReportTableModelMapper.kt

Treating unmapped licenses as issues has caused confusion in the past as
these issues are not serialized into the ORT result despite "has_issues"
being "true" in that case. Moreover, unmapped licenses are not a
technical problem, but a metadata problem, which in many workflows will be
handled by different people than technical issues.
So do not dynamically create issues for unmapped licenses anymore;
instead the recommendation is to use the example code from [1] to report
unmapped licenses as policy violations.
Resolves #3324.
[1] https://github.com/oss-review-toolkit/ort/blob/2e8f08e/examples/rules.kts#L123-L135

Stop dynamically creating issues for unmapped licenses

---

model/src/main/resources/reference.conf
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/fossid/FossIdNamingProvider.kt

These patterns allow to control the name when a scan or project is created.
When a pattern is omitted, a default naming convention is used.

fossid-webapp: Introduce pattern options for naming projects and scans

---

evaluator/src/main/kotlin/DependencyRule.kt
examples/rules.kts

Avoid the term "root", as the root of a dependency tree usually is the
project itself. However, here "level 0" refers to the direct
dependencies of a project.

DependencyRule: Improve level-related documentation

---

model/src/main/kotlin/utils/DependencyGraphConverter.kt
model/src/test/kotlin/utils/DependencyGraphConverterTest.kt

Such projects are created as fall-back by PackageManager if resolving
of dependencies fails. They can cause problems if there is already a
dependency graph for their package manager type; then this graph is
overridden by an empty one.

DependencyGraphConverter: filter out empty projects

---

utils/src/main/kotlin/OkHttpClientHelper.kt

In case of a request that failed because of an exception, log some
information about the current request. This is especially useful when
requests are executed asynchronously, as it is then sometimes hard to
say, which request caused the failure.

OkHttpClientHelper: Improve error logging

---

analyzer/src/main/kotlin/managers/Npm.kt

Also suppress the IDE hint about HTTP usage as it is intentional here.

Npm: Simplify the logic to replace insecure HTTP registry URLs

---

reporter/src/main/kotlin/reporters/AsciiDocTemplateReporter.kt

It's not required to delete each Asciidoc file individually in the loop,
because the parent temp directory will be deleted afterwards. Additionally,
the Asciidoc files can depend on each other, which requires them to exist
within the loop.

AsciiDocTemplateReporter: Remove not required deleting of files

---

model/src/main/kotlin/ScanSummary.kt

The `fileCount` property was removed in 3cfda8c. Ignore it during
deserialization to allow deserialization of old scan summaries.

ScanSummary: Ignore the file_count property on deserialization

---

analyzer/src/funTest/assets/projects/synthetic/gradle-android/build.gradle
analyzer/src/funTest/assets/projects/synthetic/gradle-library/app/build.gradle
analyzer/src/funTest/assets/projects/synthetic/gradle-library/lib/build.gradle
analyzer/src/funTest/assets/projects/synthetic/gradle/app/build.gradle
analyzer/src/funTest/assets/projects/synthetic/gradle/lib/build.gradle

Replace `jcenter()` with `mavenCentral()` in all synthetic test
projects, because JCenter is goin to be shutdown [1]. The external test
project will be addressed separately.
[1] https://blog.gradle.org/jcenter-shutdown

analyzer: Replace jcenter with mavenCentral in test projects

---

scanner/src/funTest/kotlin/experimental/DefaultNestedProvenanceResolverFunTest.kt
scanner/src/main/kotlin/experimental/NestedProvenance.kt
scanner/src/main/kotlin/experimental/NestedProvenanceResolver.kt

The `ProvenanceTreeResolver` is used to resolve nested repositories in a
`RepositoryProvenance`. It will be used by a new experimental scanner
implementation in a later commit, therefore it is also located in the
"experimental" package for now.

scanner: Add a NestedProvenanceResolver

---

analyzer/build.gradle.kts
analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderMockTest.kt

In a concrete scenario, ClearlyDefined did not send a response within
the configured timeout, causing a SocketTimeoutException to be thrown.
This exception was not handled and eventually caused the analyzer to
crash. To avoid this, add a catch block for all exceptions.
Add a test case using a mock server to verify that timeout exceptions
are now handled properly.

ClearlyDefinedPackageCurationProvider: Handle all exceptions

---

scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/fossid/FossIdNamingProvider.kt

When set, ORT will create delta scans. When only changes in a repository
need to be scanned, delta scans reuse the identifications of latest scan
on the same repository to reduce the amount of findings.
If deltaScans is set and no scan exist yet, an initial scan called
"origin" scan will be created.

fossid-webapp: Delta scans

---

scanner/src/main/kotlin/scanners/fossid/FossId.kt

Tweak the logic when reusing existing scans: If the scan is not finished, wait for it to complete.

fossid-webapp: Refine the "reuse identification" behavior

---

analyzer/src/funTest/assets/projects/synthetic/spdx-project-expected-output.yml
analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt

If the `packageFilename` is defined, the code is already present, thus, need
not be downloaded again. Additionally, this ensures that the code is scanned
that is actually used by the project, which could include minor changes.
Resolves #4276.
This was discussed in [this thread](https://ort-talk.slack.com/archives/C9NNJ54B1/p1625841198374400) in Slack.

SpdxDocumentFile: Use packageFilename before downloadLocation for VcsInfo

---

analyzer/src/funTest/assets/projects/synthetic/spdx-packages-expected-output.yml
analyzer/src/funTest/kotlin/managers/SpdxDocumentFileFunTest.kt
analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
spdx-utils/src/main/kotlin/model/SpdxDocument.kt

Resolves #4251. 
Previously, `package.spdx.yml` were discarded in favor of `project.spdx.yml`s. This was a breaking change.
In order to avoid duplicate packages, the `package.spdx.yml` is only used when no `project.spdx.yml` is amongst the definition files of the `SpdxDocumentFile` manager.

SpdxDocumentFile: Use package.spdx.yml if no project file is provided.

---

examples/notifications.kts
notifier/src/main/kotlin/Notifier.kt
notifier/src/main/kotlin/modules/MailNotifier.kt

This is a fixup for cbb5c9641accdec4b679059d9947d3fec71bd6c2 to use the
same naming scheme as the corresponding `SendMailConfiguration`.

Notifier: Rename emailClient to mailClient

---

model/src/main/kotlin/HashAlgorithm.kt
model/src/test/kotlin/HashAlgorithmTest.kt
reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt

Add links to licenses in the table of the `StaticHtmlReporter`. 
Once for Strings of licenses and once for SpdxExpressions. 
In order to have a consistent link, the software heritage links to licenses was used. 
Using the files from ORT might be less consistent across forks and blobs.

StaticHtmlReporter: Add Software Heritage links to licenses

---

downloader/src/main/kotlin/vcs/Git.kt

The overridden function already has an empty body.

Git: Remove a superfluous function override

---

downloader/build.gradle.kts
downloader/src/main/kotlin/vcs/Git.kt
downloader/src/test/kotlin/vcs/GitTest.kt

There seem to be discrepancies in the way the .netrc is interpreted by
JGit and ORT. This can cause JGit commands to fail while direc git
command line invocations are successful.
To prevent this, install a special JGit CredentialsProvider that
delegates to the Authenticator (managed by ORT). This makes sure that
always the same credentials are used.
Resolves #4311.

Git: Synchronize authentication with JGit

---

downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt

There is obviously a new remote tag in a project used by the test.
Therefore, adapt the expectations accordingly.

GitWorkingTreeFunTest: Fix a failing test case

---

cli/src/main/resources/log4j2.xml
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/fossid/FossIdConfig.kt
scanner/src/test/kotlin/scanners/fossid/FossIdConfigTest.kt

This PR is a minor refactoring of FossId with the aim to make this class easier to test. The idea is to extract the various parameters into a dedicated configuration class, which also supports the creation of helper objects. By passing a mock configuration, it is then possible to inject mocks for these helpers.

Extract a configuration for FossId

---

cli/build.gradle.kts
gradle.properties
model/src/main/kotlin/config/JiraConfiguration.kt
model/src/main/resources/reference.conf
model/src/test/kotlin/config/OrtConfigurationTest.kt
notifier/build.gradle.kts
notifier/src/main/kotlin/Notifier.kt
notifier/src/main/kotlin/modules/JiraNotifier.kt
notifier/src/test/assets/__files/response_create_issue.json
notifier/src/test/assets/__files/response_get_project.json
notifier/src/test/assets/__files/response_search_jql.json
notifier/src/test/kotlin/modules/JiraNotifierTest.kt

This introduces the Jira notifier, which uses the Java REST client of
Jira in order to make the CRUD operations. Currently, the JiraNotifier
only provides a wrapper function to create new issues in Jira.

Add a new JiraNotifier

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt

This happens quite often, and most of the time the user is not in the
position to fix it. Also ORT can transparently handle this metadata
problem, so lower the log level to "info" to not clutter the log by
default. That is also more in line with the log statement a few lines
below.

MavenSupport: Lower the log level for a missing SCM prefix to "info"

---

analyzer/src/main/kotlin/managers/Pub.kt
evaluator/build.gradle.kts
evaluator/src/main/kotlin/DependencyRule.kt
evaluator/src/main/kotlin/RuleSet.kt
evaluator/src/test/kotlin/DependencyRuleTest.kt
evaluator/src/test/kotlin/RuleSetTest.kt
evaluator/src/test/kotlin/TestData.kt
model/src/main/kotlin/DependencyNode.kt
model/src/main/kotlin/ProjectAnalyzerResult.kt
model/src/main/kotlin/config/Excludes.kt
model/src/test/kotlin/DependencyTreeNavigatorTest.kt
model/src/test/kotlin/config/ExcludesTest.kt

This is a follow-up PR to #4166. It addresses further consumers of dependency information in an `OrtResult`.

Adapt more clients to the dependency navigator API

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/GetPackageLicensesCommand.kt

The command allows querying the detected license as well as the root
license from the configured scan result storage, given any package
identifier.
This allows to determine the detected license given a package
identifier relatively quickly compared to determining the detected
license by locating, downloading and parsing an ORT result file
containing a scan result for a given package identifier. In particular
for large ORT result file the latter is much slower.

helper-cli: Add a command which shows the licenses of a package

---

.github/dependabot.yml

As there are no tests for the reporter-web-app dependency updates need
to be verified manually. Therefore updating dependencies individually
would be too much effort and dependencies are updated manually in bulk
instead.

Disable dependabot for reporter-web-app

---

analyzer/src/main/kotlin/PackageManager.kt

PackageManager: Align on logging the relative path of the definiton file

---

analyzer/src/main/kotlin/managers/Conan.kt

While at it, add docs explaining why stashing the storage path is needed
in the first place.

Conan: Simplify stashing the storage path

---

analyzer/src/test/kotlin/PackageManagerTest.kt

Some directories were named after the wrong package manager due to copy
& paste mistakes. This is a fixup for 32e8bff.
Resolves #4350.

PackageManagerTest: Fix temporary parent directory names

---

notifier/build.gradle.kts

ORT uses Log4j 2 as the logger abstraction framework, which also
provides an implementation for the SLF4J logger abstraction framework.
As a result, the conflicting SLF4J implementation for Log4j 1 has to be
excluded to avoid the runtime warning that the "Class path contains
multiple SLF4J bindings".

notifier: Exclude the conflicting log4j12 implementation for slf4j

---

Dockerfile

The old package has been removed and there is a new one: https://packages.ubuntu.com/search?keywords=cargo&searchon=names&suite=bionic&section=all

Dockerfile: Update Cargo to the available upstream version

---

scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/fossid/FossIdConfig.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt

The class contains non-trivial logic and therefore should be tested.
The new test should cover the major part of the functionality
available.
Minor changes have been applied to FossId to simplify testing.

fossid-webapp: Add a unit test for FossId

---

helper-cli/src/main/kotlin/commands/packagecuration/SetCommand.kt

To make sure that scopes are resolved properly use the helper function
that is also used in all other commands.

SetCommand: Fix loading the ORT result

---

analyzer/src/main/kotlin/managers/Conan.kt

This applies configuration stored to a conventional "conan_config"
directory before the dependency resolution. This is needed in order to
support custom remotes besides the default ConanCenter.
Resolves #4312.

Conan: Take local configuration (like remotes) into account

---

analyzer/src/main/kotlin/managers/Gradle.kt

Gradle: Respect the GRADLE_USER_HOME environment variable

---

README.md

Readme: Fix wrong uppercase in advisor documentation

---

analyzer/src/test/kotlin/managers/GradleDependencyHandlerTest.kt
model/src/main/kotlin/DependencyGraph.kt
model/src/main/kotlin/DependencyGraphNavigator.kt
model/src/main/kotlin/DependencyNavigator.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/utils/DependencyGraphBuilder.kt
model/src/test/assets/result-with-issues-graph-old.yml
model/src/test/assets/result-with-issues-graph.yml
model/src/test/assets/result-with-issues-scopes.yml
model/src/test/assets/sbt-multi-project-example-graph-old.yml
model/src/test/assets/sbt-multi-project-example-graph.yml
model/src/test/kotlin/AbstractDependencyNavigatorTest.kt
model/src/test/kotlin/DependencyGraphNavigatorLegacyTest.kt
model/src/test/kotlin/DependencyGraphNavigatorTest.kt
model/src/test/kotlin/DependencyGraphTest.kt
model/src/test/kotlin/DependencyTreeNavigatorTest.kt
model/src/test/kotlin/OrtResultTest.kt
model/src/test/kotlin/utils/DependencyGraphBuilderTest.kt
model/src/test/kotlin/utils/DependencyGraphConverterTest.kt

This is going to become the default implementation of the `DependencyNavigator` interface. It allows access to dependency information in ORT results that completely use the dependency graph format.
This PR also reworks the representation of dependency graphs in ORT result files again. The new format has the following advantages:
* It is more compact, especially for complex graphs referencing dependency sub trees multiple times. (To give you an impression: for a bigger JavaScript project, the size of the analyzer result could be reduced from 25 MB to ~900 KB.)
* No duplication of objects happens during serialization or deserialization.
* The serialized form may be easier to understand, as it is based on a typical graph representation with nodes and edges.
The code can handle the original …

Add a DependencyNavigator implementation for dependency graphs

---

Dockerfile
analyzer/src/main/kotlin/managers/Npm.kt

Upgrading Node from version 12 to version 16 also leads to an upgrade of
Npm. So, pin the Npm version accordingly to the latest release. See also
[1] and [2].
This change fixes [3] for unknown reason.
[1] https://github.com/nodejs/node/blob/7ca38f05a023666274569343f128c5aed81599f3/doc/changelogs/CHANGELOG_V16.md
[2] https://github.com/npm/cli/blob/59b9851d1649b8f78203cae187b1337f2441219d/CHANGELOG.md#v7206-2021-08-12
[3] https://stackoverflow.com/questions/68021121/fsevents-not-accessible-from-jest-haste-map.

Dockerfile: Upgrade Node to version 16

---

analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
model/src/main/kotlin/DependencyGraph.kt

acd4aa8 added the @JsonInclude(JsonInclude.Include.NON_DEFAULT)
annotation to DependencyGraph. This caused a rather aggressive
optimization when serializing an empty DependencyGraph object: the
fields for packages and scopes were dropped completely. Such an
instance could then no longer be deserialized, because these fields
are not nullable and do not define a default value.
(Note: This problem was actually encountered in practice with a DotNet
project, which produced a dependency graph for NuGet and an empty one
for DotNet.)
Fix this by assigning empty default values to the problematic fields.
This is in-line with the other fields in this class, which have a
default value, too.

DependencyGraph: Fix a deserialization problem with empty graphs

---

model/src/main/kotlin/Vulnerability.kt
model/src/test/kotlin/VulnerabilityTest.kt

When using the VulnerableCode advisor implementation, results have
been encountered that actually contain only an ID, but no references.
Therefore, to represent such results in ORT's vulnerability model,
remove the check for an empty list of references from the
Vulnerability class. (It is probably safer to store such results -
even if they contain limited information - than to drop them.)

Vulnerability: Allow instances without references

---

analyzer/src/main/kotlin/curation/SimplePackageCurationProvider.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
docs/config-file-ort-yml.md
helper-cli/src/main/kotlin/common/Utils.kt
model/src/main/kotlin/config/Curations.kt
model/src/main/kotlin/config/RepositoryConfiguration.kt

Enable package curations from the project's repository configuration file in order to enable project-specific curations.

Project-specific package curations

---

docs/config-file-ort-yml.md

This is a fixup for f4a0ea166372635fe0bf0651dabc6928611118e4.

config-file-ort-yml: Fix example for project-local curations

---

.github/workflows/static-analysis.yml

See https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/.

workflows: Enable Java dependency caching

---

README.md
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
analyzer/src/main/kotlin/curation/Sw360PackageCurationProvider.kt
analyzer/src/main/kotlin/managers/Bundler.kt
analyzer/src/main/kotlin/managers/CocoaPods.kt
analyzer/src/main/kotlin/managers/Composer.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/Pip.kt
analyzer/src/main/kotlin/managers/Stack.kt
clients/clearly-defined/src/main/kotlin/Enums.kt
docs/getting-started.md
docs/sw360-integration.md
downloader/src/main/kotlin/VersionControlSystem.kt
evaluator/src/main/kotlin/PackageRule.kt
evaluator/src/test/kotlin/PackageRuleTest.kt
evaluator/src/test/kotlin/TestData.kt
examples/curations.yml
model/src/main/kotlin/Package.kt
model/src/main/kotlin/PackageCurationData.kt
model/src/main/kotlin/Project.kt
model/src/main/kotlin/licenses/LicenseCategorization.kt
model/src/main/kotlin/licenses/LicenseClassifications.kt
reporter-web-app/public/index.html
reporter/src/main/kotlin/model/MetaData.kt
reporter/src/main/kotlin/reporters/SpdxDocumentReporter.kt
scanner/src/main/kotlin/LocalScanner.kt
spdx-utils/src/main/kotlin/model/SpdxCreationInfo.kt
spdx-utils/src/main/kotlin/model/SpdxFile.kt

The "metadata" spelling seems to be way more common than "meta data" or
"meta-data".

Consistently spell it like "metadata" throughout the code base

---

Dockerfile

In some environments using a symlink to `$HOME/.gradle` won't work.
Instead, change the location by setting `GRADLE_HOME`.
For our Azure environment gradle is not able to create a lock file when symlinking the `.gradle` directory:
```
#15 [build 5/5] RUN --mount=type=cache,target=/tmp/.gradle/     ln -s /tmp/....
#15 1.381 Skipping the import of certificates as no HTTPS proxy is set.
#15 1.790 Exception in thread "main" java.lang.RuntimeException: Could not create parent directory for lock file /root/.gradle/wrapper/dists/gradle-7.2-bin/2dnblmf4td7x66yl1d74lt32g/gradle-7.2-bin.zip.lck
#15 1.791   at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:43)
#15 1.792   at org.gradle.wrapper.Install.createDist(Install.java:48)
#15 1.792   at …
```

Dockerfile: Set `GRADLE_USER_HOME` instead of using a symlink to the default location

---

cli/src/main/kotlin/commands/ScannerCommand.kt
scanner/src/main/kotlin/Scanner.kt

Allow to use a different scanner for projects than for packages

---

model/src/main/kotlin/utils/DependencyGraphBuilder.kt
model/src/test/kotlin/utils/DependencyGraphBuilderTest.kt

When `DependencyGraphBuilder.toGraph()` looks-up the node index of the "to node" of an edge, the look-up may fail since it happens that the map entry hasn't been created before. Fix that issue (crash) by making sure that the map entry is properly created.
The false logic which exhibited that bug also skipped edges which may mean actually eliminating circles. 
In fact when fixing the logic, ORT runs into a subsequent issue because several consumers of the graph assume the absence of any cycle. 
While in the long run it makes sense to allow cycle in the graph, implement a temporary solution to just break all cycle. 
Allowing circles is a bigger topic and needs proper planning and involvement of all relevant people. The goal of this PR is to fix the crash in the short term.
Fixes #4405.

DependencyGraph: Fix a crash and a couple of subsequent issues

---

reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
reporter/src/main/kotlin/reporters/SpdxDocumentReporter.kt

These days it's all about (S)BOMs, so align the names of these commonly
used BOM formats to appear next to each other when sorted
alphabetically, for a better overview.

reporter: Align the default output names of CycloneDX and SPDX files

---

docs/config-file-package-configuration-yml.md

Package configurations have been around for about 1.5 years already,
are actively being used and the implementation has remained stable. So,
they are not experimental anymore.

 docs: Drop the "experimental" state from package configurations

---

analyzer/src/main/kotlin/managers/GoMod.kt

Only the named "sha1" group is used. This fixes an inspection hint.

GoMod: Remove an unnecessary capturing group in a regex

---

spdx-utils/src/main/resources/declared-license-mapping.yml

Found in [1].
[1]: https://github.com/eclipse/paho.mqtt.java/blob/v1.2.4/pom.xml#L50.

declared-license-mapping: Add mapping for "Eclipse Public License - Version 2.0"

---

scanner/src/main/kotlin/scanners/fossid/FossId.kt

This prevent an exception "Logging is only allowed on ORT classes, but
'java.util.Arrays.ArrayList' is used."
```
Exception in thread "main" java.lang.IllegalArgumentException: Logging is only allowed on ORT classes, but 'java.util.Arrays.ArrayList' is used.
at org.ossreviewtoolkit.scanner.scanners.fossid.FossId.findLatestPendingOrFinishedScan(FossId.kt:1092)
at org.ossreviewtoolkit.scanner.scanners.fossid.FossId.access$findLatestPendingOrFinishedScan(FossId.kt:76)
at org.ossreviewtoolkit.scanner.scanners.fossid.FossId$findLatestPendingOrFinishedScan$1.invokeSuspend(FossId.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
```

fossid-webapp: Fix logging in FossId scanner

---

scanner/src/main/kotlin/scanners/fossid/FossIdConfig.kt

toBooleanStrictOrNull() parses case-sensitively while toBoolean() is
case-insensitive. Align on the latter for more lenient parsing.

FossIdConfig: Align parsing of booleans for clarity and case-insensitivity

---

spdx-utils/src/main/resources/declared-license-mapping.yml

Found in [1].
[1] https://jcenter.bintray.com/io/objectbox/objectbox-android/2.8.1/objectbox-android-2.8.1.pom

declared-license-mapping: Add an entry for OLDAP-2.8

---

cli/src/funTest/kotlin/ExamplesFunTest.kt
examples/notifications.kts
notifier/src/main/kotlin/modules/MailNotifier.kt

Enable the mail notifier to be able to send HTML mails.

MailNotifier: Provide the possibility to send HTML emails

---

analyzer/src/main/kotlin/managers/CocoaPods.kt

There a two code locations running the `pod` executable. One of these
two locations accidentally lacks passing the `--allow-root` argument.
As result this package manager integration can be run only as non-root
users.
Remove that limitation by adding that missing argument.

CocoaPods: Enable running this package manager as root user

---

analyzer/src/main/kotlin/PackageManager.kt
model/src/test/kotlin/CompatibilityDependencyNavigatorTest.kt

PackageMangaer: Fix a broken assumption
The evaluator calls `CompatibilityDependencyNavigator.create()` in order
to construct a dependency navigator. That function creates an instance
of DependencyGraphNavigator if `Project.scopeNames` is not null [2].
The constructor of DependencyGraphNavigator in turn requires a
dependency graph to exist [3].
That requires check [3] fails if the project has an empty set as
`scopeNames` and at the same time there is no dependency graph available
for the type of the project. This happens e.g. if a source tree with
only one definition file is analyzed, whereas `resolvedDependencies()`
fails with an exception, see [4]. The failed requires check results in
a crash of the evaluator.
Guarantee that in case `project.usesTree() == false` a dependency graph
for …

PackageManager: Fix a broken assumption

---

README.md

This is for a better overview for development teams that work with a
specific programming language. This also allows to document any
limitation more prominently with a short summary.

README: Group supported package managers by primary programming language

---

cli/src/main/kotlin/commands/NotifierCommand.kt

In contrast to other labels the Notifier labels are not persisted in a
resulting ort-result.yml, as the Notifier itself does not create an
ort-result.yml. However, this option is still useful if specific options
for any of the Notifier implementations are required, e.g. E-Mail
addresses or Jira Ticket numbers.

NotifierCommand: Add the label option to the Notifier

---

docs/dir-custom-license-texts.md

Fix a small typo in documentation for custom license text directory.

docs: Fix a typo

---

model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt

The resolver accidentally associates all detected licenses to each "resolved license" instance, which is fixed by this PR.

LicenseInfoResolver: Fix resolving original expressions for detected licenses

---

reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/main/kotlin/utils/ReportTableModelMapper.kt

The HTML report shows an effective license which does not adhere to path
excludes for detected licenses. So, if there is no concluded license the
effective license always includes all detected licenses. Fix that by
using filterExcluded().

StaticHtmlReport: Respect the path excludes for the effective license

---

evaluator/src/main/kotlin/OrtResultRule.kt
evaluator/src/main/kotlin/Rule.kt
evaluator/src/main/kotlin/RuleSet.kt
model/src/main/kotlin/RuleViolation.kt
reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
reporter/src/main/kotlin/model/EvaluatedRuleViolation.kt
reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt

Having a generic rule which is executed once per ORT result helps with use
cases for which the more specific rules aren't a good fit. As a pre-requisite the field
`RuleViolation.pkgId` is made nullable, which eliminates the assumption that a rule violation always corresponds to a package.
NOTE: The PR has to be amended to properly handle the now nullable attribute in the `web-app`.

evaluator: Add the new rule type `OrtResultRule`

---

model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt

The previous implementation was using raw licenses for original expressions and curated licenses for resolved locations which is inconsistent. As original expressions are the basis for applying license choices these have to be curated.
The PR illustrates and fixes a bug where the resolved license info lacks original expressions.

LicenseInfoResolver: Make original expression curated instead of raw

---

docs/getting-started.md

As of 48f2b96fbffbd2f6038e3d1dba4904302dac06ab Java 11 is required to
build ORT.

getting-started: Raise Java requirement to 11

---

analyzer/src/main/kotlin/managers/Pub.kt

The default implementation uses the `run` method. In Pub's case this
uses `dart pub`, which does not offer the `--version` flag. Therefore,
using the `dart`'s version information.

Pub: Override the getVersion command

---

advisor/src/main/kotlin/Advisor.kt
analyzer/src/main/kotlin/PackageManager.kt
reporter/src/main/kotlin/Reporter.kt
scanner/src/main/kotlin/Scanner.kt

This way also e.g. package managers added via external plugins show up
sorted in the CLI output for activated package managers.

Sort service loader factories by name if not sorted otherwise

---

model/src/main/resources/reference.conf

This is to align a bit with YAML configuration files.

reference.conf: Use hash-chars for comments in HOCON

---

detekt-rules/build.gradle.kts

Also see [[1]].
[1]: https://detekt.github.io/detekt/extensions.html#pitfalls

detekt-rules: Show a colored info if the Gradle plugin needs to reload

---

cli/src/funTest/assets/semver4j-analyzer-result.yml
cli/src/funTest/kotlin/ExamplesFunTest.kt
evaluator/src/main/kotlin/OrtResultRule.kt
examples/rules.kts

Recently the rule type `OrtResultRule` has been added [1].
This PR adds an example.
[1] #4349

examples/rules: Illustrate the OrtResultRule

---

analyzer/src/main/kotlin/curation/FilePackageCurationProvider.kt
analyzer/src/test/assets/package-curations-not-deserializable.yml
analyzer/src/test/kotlin/curation/FilePackageCurationProviderTest.kt

Fail if any curation file does not exist or cannot be deserialized.
Previously, it could easily go unnoticed if curations have not been
applied, because the only hint was a warning in the logs.

FilePackageCurationProvider: Fail if curations file cannot be read

---

advisor/src/main/kotlin/AdviceProvider.kt
advisor/src/main/kotlin/AdviceProviderFactory.kt
advisor/src/main/kotlin/Advisor.kt
advisor/src/main/kotlin/advisors/NexusIq.kt
advisor/src/main/kotlin/advisors/OssIndex.kt
advisor/src/main/kotlin/advisors/VulnerableCode.kt
advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
cli/src/main/kotlin/commands/AdvisorCommand.kt
evaluator/src/test/kotlin/TestData.kt
model/src/main/kotlin/AdvisorRecord.kt
model/src/main/kotlin/AdvisorResult.kt
model/src/main/kotlin/Defect.kt
model/src/test/kotlin/AdvisorRecordTest.kt
model/src/test/kotlin/AdvisorResultContainerTest.kt
model/src/test/kotlin/DefectTest.kt

This PR adds a `Defect` class to the data model that can be used in a similar way as the existing `Vulnerability` class. The goal is to support advisor implementations that can retrieve information about known defects for the packages involved. To make this possible, the result classes used by advisors have been extended to store defects as well.
To reflect this broader scope advisors can now have, some classes have been renamed to no longer refer to *vulnerabilities* exclusively.

Add support for defects to ORT's data model

---

reporter/src/main/resources/templates/asciidoc/disclosure_document.ftl
reporter/src/main/resources/templates/notice/default.ftl

Improve the handling of license files in the Freemarker templates, see the commit messages for details.

reporter: Fix license file handling

---

cli/src/main/kotlin/commands/ScannerCommand.kt
downloader/src/main/kotlin/Downloader.kt
scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
scanner/src/main/kotlin/experimental/NestedProvenance.kt
scanner/src/main/kotlin/experimental/NestedProvenanceScanResult.kt
scanner/src/main/kotlin/experimental/ProvenanceDownloader.kt
scanner/src/main/kotlin/experimental/ScanStorage.kt
scanner/src/main/kotlin/experimental/ScannerWrapper.kt
scanner/src/main/kotlin/scanners/Askalono.kt
scanner/src/main/kotlin/scanners/BoyterLc.kt
scanner/src/main/kotlin/scanners/Licensee.kt
scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
scanner/src/main/resources/META-INF/services/org.ossreviewtoolkit.scanner.ScannerWrapperFactory
scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt

Add a new experimental scanner implementation that aims to scan each provenance (meaning source code repository or source artifact) only once. This provides better performance and uses less storage for scan results. The new implementation can be tried by providing the `--experimental` switch to the `scan` command.
Simplified, the algorithm of the new scanner is:
* Resolve the provenance of all packages, including sub-repositories, to determine if there are any overlaps.
* Check if any stored scan results are available for the provenances.
* Scan the remaining provenances.
* Associate the scan results back to the packages.
The implementation is not yet feature complete, missing functionality will be added in later PRs. Please see the commit messages for details.

Add an experimental provenance based scanner implementation

---

helper-cli/src/main/kotlin/commands/repoconfig/RemoveEntriesCommand.kt

The previous way of accessing scopes always lead to a runtime exception
thrown from [1]. Fix that by accessing the scopes for any project via
the property`Project.scopes`. This works fine because the ORT result is
obtained via `readOrtResult()` which ensures that scopes are resolved.
[1] https://github.com/oss-review-toolkit/ort/blob/6a7e2855129c4c35d1b058aaeff5f4e2fece2c79/model/src/main/kotlin/DependencyGraphNavigator.kt#L29-L31

RemoveEntriesCommand: Don't crash when accessing scopes

---

cli/src/funTest/assets/semver4j-analyzer-result.yml
cli/src/funTest/kotlin/ExamplesFunTest.kt
examples/rules.kts
model/src/main/kotlin/config/PathExcludeReason.kt

Undo a deprecation which should not have been done in the first place according to [1] and refactor an example policy rule accordingly.
[1] https://github.com/spdx/spdx-spec/blob/development/v2.2.2/chapters/relationships-between-SPDX-elements.md

Un-deprecate a path exclude reason

---

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
analyzer/src/main/kotlin/managers/Pip.kt

See [1] and [2] for some background information.
[1] https://pip.pypa.io/en/stable/news/#v18-1
[2] https://github.com/pypa/pipenv/issues/3058

Pip: Raise PIP_VERSION to 18.1 to support PEP 508 URL requirements

---

model/src/main/kotlin/CompatibilityDependencyNavigator.kt
model/src/test/kotlin/CompatibilityDependencyNavigatorTest.kt

CompatibilityDependencyNavigator.create() could fail with an exception
for an OrtResult that contains projects with an empty set of scope
names, but no dependency graph. This is a corner case that could
appear if a package manager had issues when constructing projects. To
prevent this exception, check first whether the result contains a
dependency graph, and if not, return the DependencyTreeNavigator.

DependencyNavigator: Handle results with empty dependency graphs

---

scanner/src/main/kotlin/Scanner.kt

If one wants to implement a scanner working on binary artifacts, LocalScanner cannot be inherited because it operates exclusively on source artifacts.
The solution is then to inherit directly Scanner but, for that, the function must be public to be able to do the implementation in a plugin.

Scanner: Increase the visibility of scanPackages

---

analyzer/src/funTest/assets/projects/synthetic/spdx-project-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml
analyzer/src/funTest/kotlin/managers/SpdxDocumentFileFunTest.kt
analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
spdx-utils/src/main/kotlin/SpdxConstants.kt

SpdxDocumentFiles: Use `originator` as the author

---

scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt

This fixes the regex for the extraction of the repository name from
a Git URL, because the old regex could not omit the .git suffix from
the Git URL. Additionally, it adds a new test case for testing the
function convertGitUrlToProjectName with several Git URLs.

FossId: Fix the extraction of a repository name from a Git URL

---

analyzer/src/main/kotlin/managers/Pip.kt

There are Pip packages that use the full license text here instead of a
short string. Only use the first line in that case, and warn about the
rest. Also see [1].
[1]: https://github.com/scanny/python-pptx/issues/748

Pip: Do not fail hard on non-short-string / multi-string licenses

---

analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-py.yml
analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml
analyzer/src/funTest/assets/projects/synthetic/conan-py/conanfile.py
analyzer/src/funTest/assets/projects/synthetic/conan-txt/.gitignore
analyzer/src/funTest/assets/projects/synthetic/conan-txt/conanfile.txt

The previously used dependencies were not available on Conan Center
anymore, probably because the Bintray default repository was removed in
Conan 1.40.0 [1].
While at it, use dependencies which have transitive dependencies, to
show how these are handled.
[1] https://docs.conan.io/en/1.40/changelog.html#id12

ConanFunTest: Replace the dependencies

---

cli/src/main/kotlin/commands/ScannerCommand.kt
model/src/main/kotlin/config/ScanStorageConfiguration.kt
scanner/src/funTest/kotlin/experimental/AbstractProvenanceBasedStorageFunTest.kt
scanner/src/funTest/kotlin/experimental/ProvenanceBasedFileStorageFunTest.kt
scanner/src/funTest/kotlin/experimental/ProvenanceBasedPostgresStorageFunTest.kt
scanner/src/main/kotlin/ScanResultsStorage.kt
scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
scanner/src/main/kotlin/experimental/ProvenanceBasedFileStorage.kt
scanner/src/main/kotlin/experimental/ProvenanceBasedPostgresStorage.kt
scanner/src/main/kotlin/experimental/ScanStorage.kt
scanner/src/main/kotlin/experimental/ScanStorageException.kt
scanner/src/main/kotlin/experimental/Utils.kt
scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt

Adapt the existing storages for the experimental scanner and add new provenance based storages. For details see the commit messages.

Experimental scanner: Add storage implementations

---

clients/oss-index/src/main/kotlin/OssIndexService.kt

OssIndexService: Make a ComponentReport's description optional

---

scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt

AbstractStorageFunTest: Fix a compilation error

---

.reuse/dep5
examples/curations.ort.yml
examples/package-configurations.ort.yml
examples/resolutions.ort.yml
gradle.properties
integrations/schemas/repository-configuration-schema.json
model/build.gradle.kts
model/src/test/kotlin/JsonSchemaTest.kt

A JSON schema [1] is a description of a JSON document, which can also be
used for YAML files. This schema can be used to enable auto-completion
in multiple editors for the .ort.yml file [2]. E.g. IntelliJ IDEA has build-in support
for it [3]:
As a next step, the URL to this schema can be contributed to https://github.com/schemastore/schemastore/ and many editors will then have autocompletion for .ort.yml out of the box.
It would be nice to autogenerate this file, however I didn't find a convenient way to do this.
Adding the test coverage to avoid regressions in the schema should be good enough for now.
Missing as of now is the documentation from the model classes. It would be nice to also get this documentation during auto completion.
I opted to use the JSON format instead of a YAML …

Add JSON schema for .ort.yml configuration

---

model/src/main/kotlin/config/IssueResolution.kt
model/src/main/kotlin/config/RuleViolationResolution.kt
model/src/main/kotlin/utils/Extensions.kt
model/src/test/kotlin/config/RuleViolationResolutionTest.kt
model/src/test/kotlin/utils/ExtensionsTest.kt

In the StaticHtml and WebApp reports the message is being rendered
without any additional whitespaces and new lines. However, when writing
resolutions for these messages the user needs to know that the message
contains these characters, otherwise the Regex will not work.

Rule: Ignore invisible characters in the matching of the resolution

---

reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
utils/core/src/main/kotlin/Utils.kt
utils/core/src/test/kotlin/UtilsTest.kt

This is to prepare for upcoming reuse.

Move the code to detect Maven Central URLs to a utility function

---

scanner/src/main/kotlin/scanners/scanoss/ScanOssResultParser.kt
scanner/src/test/assets/pigz-c-scanoss.json
scanner/src/test/kotlin/scanners/scanoss/ScanOssResultParserTest.kt

SCANNOSS [1] is a snippet scanner whose engine [2], mining tool [3] and
some other parts are Open Source. It also provides a public database of
"fingerprints" for Open Source packages [4]. As such it is a good fit
for being added to ORT as a supported scanner. This commit prepares for
that by adding a parser for SCANOSS results. More changes that trigger
the actualy scans and extensions to the ORT data model to capture
snippet findings [5] will follow later.
The license name is an SPDX ID, or "NOASSERTION" when there is an
exceptional situation.
[1]: https://scanoss.com/
[2]: https://github.com/scanoss/engine
[3]: https://github.com/scanoss/minr
[4]: https://osskb.org/
[5]: https://github.com/oss-review-toolkit/ort/issues/3265
Signed-off-by: Juan M Salamanca <juan.m.salamanca@scanoss.com> …

scanner: Add a parser for SCANOSS results

---

analyzer/src/main/kotlin/managers/Pub.kt

Instead of throwing an IllegalArgumentException as the yamlMapper does
not handle nullable files.

Pub: Create ORT issue if pubspec.yaml is missing for a package

---

utils/core/src/main/kotlin/Extensions.kt

Use `let` to make the function an expression function.

utils-core: Make showStackTrace() an expression function

---

docs/config-file-curations-yml.md
model/src/main/kotlin/PackageCurationData.kt
model/src/test/kotlin/PackageCurationTest.kt

For some packages the default value for the package URL generated by
ORT is invalid. That generated default value also does not cover some
of the parameters e.g. qualifiers or subpaths, see [1].
Allow curating the package URLs to enable fixing invalid or improving
valid default values.
[1] https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst
Fixes #4565.

Allow curating the package URL

---

downloader/src/main/kotlin/vcs/GitRepo.kt

The command does not actually clone the referenced Git repositories yet.

GitRepo: Improve the code comment for running "repo init"

---

analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
analyzer/src/funTest/kotlin/managers/Extensions.kt
analyzer/src/funTest/kotlin/managers/MavenFunTest.kt
analyzer/src/funTest/kotlin/managers/SpdxDocumentFileFunTest.kt
analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/managers/Bower.kt
analyzer/src/main/kotlin/managers/Bundler.kt
analyzer/src/main/kotlin/managers/Cargo.kt
analyzer/src/main/kotlin/managers/Carthage.kt
analyzer/src/main/kotlin/managers/CocoaPods.kt
analyzer/src/main/kotlin/managers/Composer.kt
analyzer/src/main/kotlin/managers/Conan.kt
analyzer/src/main/kotlin/managers/DotNet.kt
analyzer/src/main/kotlin/managers/GoDep.kt
analyzer/src/main/kotlin/managers/GoMod.kt
analyzer/src/main/kotlin/managers/Gradle.kt
analyzer/src/main/kotlin/managers/Maven.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/NuGet.kt
analyzer/src/main/kotlin/managers/Pip.kt
analyzer/src/main/kotlin/managers/Pipenv.kt
analyzer/src/main/kotlin/managers/Pub.kt
analyzer/src/main/kotlin/managers/Sbt.kt
analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
analyzer/src/main/kotlin/managers/Stack.kt
analyzer/src/main/kotlin/managers/Unmanaged.kt
analyzer/src/test/kotlin/managers/CarthageTest.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt

This allows implementing a dependency resolution logic depending on the
labels given as parameters to the AnalyzerCommand. This is useful, for
instance, for custom analyzer plugins.

Analyzer: Pass the labels to the `resolveDependencies` functions

---

analyzer/src/funTest/assets/projects/synthetic/npm/no-lockfile/package.json
analyzer/src/funTest/assets/projects/synthetic/npm/node-modules/package.json
analyzer/src/funTest/assets/projects/synthetic/npm/package-lock/package.json
analyzer/src/funTest/assets/projects/synthetic/npm/shrinkwrap/package.json
analyzer/src/funTest/assets/projects/synthetic/yarn/package.json

ORT does not support `peerDependencies` yet [1]. That is mostly because
handling of peer dependencies varies with NPM versions: Some versions do
install them by default, some do not [2]. This results in ORT's functional
tests to fail depending on the NPM version, and as it turns out, they
would fail with the NPM version 7 currently used in ORT's `Dockerfile`.
However, tests succeed on Azure CI which uses NPM 6.  Avoid that
inconsistency by simply not using peer dependencies at all for testing for
now.
[1]: https://github.com/oss-review-toolkit/ort/issues/95
[2]: https://nodejs.org/en/blog/npm/peer-dependencies#using-peer-dependencies

analyzer: Remove `peerDependencies` from NPM / Yarn test assets

---

model/src/main/kotlin/Package.kt
model/src/main/kotlin/PackageCurationData.kt
model/src/test/kotlin/PackageCurationTest.kt
model/src/test/kotlin/PackageTest.kt

When a package lacks VCS meta-data several of ORT's package manager
integrations use fallback URLs to guess the VCS location. The result of
that guess ends up in `Package.vcsProcess` but not in `Package.vcs`.
Applying a VCS package curation works by patching `Package.vcs` and
setting `Package.vcsProcessed` to `Package.vcs.normalize()`. So, the
result of the above mentioned guess based on the fallback URLs gets
discarded.
For example, applying a VCS path curation to a package with empty `vcs`
but non-empty `vcsProcessed` yields a package wich has empty VCS info
(besides the path) for both, `vcs` and `vcsProcessed`.
Avoid loosing the guessed VCS by applying the curation to `vcsProcessed`
instead of to `vcs`. Note that only the former is considered by the
downloader or scanner respectively. …

Apply VCS curation to `vcsProcessed` instead of to `vcs`

---

detekt-rules/src/main/kotlin/OrtPackageNaming.kt
utils/core/src/main/kotlin/Logger.kt
utils/core/src/test/kotlin/LoggerTest.kt
utils/core/src/test/kotlin/test/other/OrtLogTestExtension.kt

ORT's logging mechanism currently checks whether the current class
belongs to a package in ORT's namespace; otherwise, an exception is
thrown. This check can fail for external classes that extend ORT
functionality, e.g. plugins - even if the logging code is in a base
class.
As a work-around, make the check more lenient to accept classes that
extend a class or interface from the ORT namespace.
To prevent a detekt failure with the corresponding test case (that
uses a class in a different namespace), the OrtPackageNaming rule
class had to be tweaked.

Utils: Support logging from classes that extend ORT base classes

---

advisor/src/main/kotlin/Advisor.kt
analyzer/src/main/kotlin/Analyzer.kt
downloader/src/main/kotlin/Downloader.kt
scanner/src/main/kotlin/Scanner.kt

This allows to benefit from default arguments also when ORT in called
from Java.

Add JVM overloads for main API functions with default arguments

---

model/src/main/kotlin/Provenance.kt
scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt

The downloader uses only `Package.vcsProcessed`, not `Package.vcs`, for
downloading the sources of any package from a VCS. The scan results
storages match a scan result, if that scan result's provenance equals
either of `Package.vcs` and `Package.vcsProcessed`. This is inconsistent
with the downloader and does lead to the following issue:
If `vcs` and `vcsProcessed` of a package differ,
`ScanResultsStorage.read()` may return multiple scan results with
different provenance. For example, when a package's VCS path is set via
a curation, the OrtResult may contain (as of [1]) two scan results for
that package, one with- and the other without a VCS path.
Stop matching `Package.vcs` for consistency with the downloader and to
fix above issue.
Fixes #4679.
[1] #4653
Signed-off-by: Frank Viernau …

ScanResulsStorage(s): Fix an issue with VCS info based matching

---

.reuse/dep5
README.md
reporter/src/funTest/assets/sample.fossinfo.json
reporter/src/funTest/kotlin/reporters/ctrlx/CtrlXAutomationReporterFunTest.kt
reporter/src/main/kotlin/reporters/ctrlx/CtrlXAutomationModel.kt
reporter/src/main/kotlin/reporters/ctrlx/CtrlXAutomationReporter.kt
reporter/src/main/resources/META-INF/services/org.ossreviewtoolkit.reporter.Reporter

"ctrlX AUTOMATION" is a suite of tools developed by Bosch Rexroth to
automate various processes in engineering. The "ctrlX CORE" tool defines
a JSON schema to document FOSS information [2]. This new reporter
exports to that format.
[1] https://ctrlx-automation.com/
[2] https://github.com/boschrexroth/json-schema/tree/master/ctrlx-automation/ctrlx-core/apps/fossinfo

reporter: Add a reporter for the CtrlX Automation framework

---

build.gradle.kts

The concept of conventions is deprecated.

Gradle: Use extensions to configure source sets

---

utils/spdx/src/test/kotlin/model/SpdxDocumentTest.kt

To match the package (and name) of the class under test.

spdx-utils: Move `SpdxDocumentTest` to the `model` package

---

cli/src/main/kotlin/commands/ScannerCommand.kt
scanner/src/funTest/kotlin/experimental/DefaultNestedProvenanceResolverFunTest.kt
scanner/src/funTest/kotlin/experimental/DefaultPackageProvenanceResolverFunTest.kt
scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
scanner/src/main/kotlin/experimental/NestedProvenanceResolver.kt
scanner/src/main/kotlin/experimental/PackageProvenanceResolver.kt
scanner/src/main/kotlin/experimental/ProvenanceDownloader.kt
scanner/src/main/kotlin/experimental/WorkingTreeCache.kt
scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt

Add a working tree cache to avoid downloading the same sources multiple times. See the commit messages for details.

scanner: Add a working tree cache for the experimental scanner

---

reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
reporter/src/main/kotlin/reporters/evaluatedmodel/Statistics.kt
reporter/src/main/kotlin/reporters/evaluatedmodel/StatisticsCalculator.kt

Can be useful as an overview and as input for a simple heuristic
which guesses whether there was a significant change in-between two
revisions of a repository configuration.

 EvaluatedModel: Add some statistics about the repository configuration

---

cli/src/main/kotlin/commands/AnalyzerCommand.kt
cli/src/main/kotlin/commands/EvaluatorCommand.kt
docs/config-file-ort-yml.md
model/src/main/kotlin/config/OrtConfiguration.kt
model/src/main/resources/reference.conf
model/src/test/kotlin/config/OrtConfigurationTest.kt

This disables the project-local package-configuration and curations by default, as it was discussed in the [developer meeting](https://github.com/oss-review-toolkit/ort/wiki/Developer-Meeting#2021-09-02).

Configuration for project-local package-configurations and curations

---

scanner/src/main/kotlin/LocalScanner.kt

Do not require that the installed version of a scanner matches the
expected version. Instead print a message if the installed version is
not the expected version, but continue using it for scanning.

LocalScanner: Remove the version requirement for scanners

---

docs/hints-for-use-with-docker.md

An alternative for .netrc is gitconfig to access private repos.
Signed-off-by: martencassel <marten.cassel@gmail.com>

doc-hints-for-docker: gitconfig for private repos. Fixes #4539

---

advisor/src/main/kotlin/advisors/VulnerableCode.kt
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
cli/src/main/kotlin/commands/RequirementsCommand.kt
scanner/src/main/kotlin/storages/FileBasedStorage.kt
scanner/src/main/kotlin/storages/PostgresStorage.kt
utils/core/src/main/kotlin/OkHttpClientHelper.kt

Consistently use `runCatching` when catching the generic `Exception`
class to avoid having to use `@Suppress("TooGenericExceptionCaught")`.

Use runCatching for catching generic exceptions

---

.lift.toml

Detekt is already run separately, and this way detekt's "SpreadOperator"
rule does not need to be disabled via Lift.

Disable running detekt as part of Lift

---

.azure-pipelines/WindowsAnalyzerTest.yml
build.gradle.kts

This makes `PipenvFunTest` on Azure pass again, which (for whatever
reason) recently started to use a very long temporary directory path
with a duplicated user home directory, like
'C:\\\\Users\\\\VssAdministrator\\\\AppData\\\\Local\\\\Temp\\\\pip-uninstall-539z9bgr\\\\users\\\\vssadministrator\\\\appdata\\\\local\\\\temp\\\\ort-pipenv-python3-virtualenv16189861807346217886\\\\lib\\\\\site-packages\\\\pip\\\\_vendor\\\\urllib3\\\\packages\\\\ssl_match_hostname\\\\__pycache__\\\\__init__.cpython-39.pyc'
The shortending is achieved by setting the JVM's `java.io.tmpdir` system
property to some short path, and ensuring the property to be passed on
to the separate JVM that runs the tests.

WindowsAnalyzerTest: Shorten the temporary directory paths (fixes `PipenvFunTest`)

---

analyzer/src/main/kotlin/managers/Npm.kt

PR attempts to use `--ignore-scripts` parameter also in `npm ci` cases, not only for `npm install`.
(cmp. #4699 for respective issue description)

#4699: analyzer/npm :: Add usage of --ignore-scripts parameter to "npm ci" in order to prevent unnecessary and risky script execution

---

model/src/main/kotlin/config/AnalyzerConfiguration.kt

Allow de-serializing analyzer results created prior to the removal of
that property, see also 97eca89064f6e82ee9e605e242c0a7b556e24ff9.

AnalyzerConfiguration: Fix-up the removal of 'ignore_tool_versions'

---

helper-cli/src/main/kotlin/commands/repoconfig/ImportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/commands/repoconfig/ImportPathExcludesCommand.kt
helper-cli/src/main/kotlin/common/Utils.kt

Cloning for some projects is time consuming. So, match the path excludes
against the finding locations within the given ORT file in order to
speed-up that workflow.
Note: Excludes which don't match any finding won't get imported anymore.
That's not critical because such path excludes anyway don't have any
effect. Since ORT files will likely be extended to contain a full
listing of all scanned files in the future, it will be possible to
implement the same behavior as before this change.

 ImportPathExcludesCommand: Avoid requiring the source code directory

---

model/src/main/resources/reference.conf
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/fossid/FossIdConfig.kt
scanner/src/test/kotlin/scanners/fossid/FossIdConfigTest.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt

When ORT waits for FossID scan to complete, the current timeout is
hardcoded and is set to one hour.
We have some FossID scans lasting for longer therefore the timeout needs
to be configurable.

fossid-webapp: Make the timeout for FossID connections configurable

---

settings.gradle.kts

Gradle: Explicitly add Maven Central as a repository for the Dokka plugin

---

Dockerfile

This is only quick fix before an upcoming general overhaul of the Docker file.

Expose the ScanCode version as a Docker build argument

---

analyzer/src/main/kotlin/PackageManager.kt
reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
utils/common/src/main/kotlin/Os.kt

`find` is an alias for `firstOrNull`. Since `find` is already used far
mor often in the codebase, align on using `find`.

Align on using find instead of firstOrNull

---

cli/src/main/kotlin/OrtMain.kt

This reads better than a comma-separated list while still highlighting
the individual arguments vs. a single argument with spaces.

OrtMain: Print the original command line arguments as a list

---

reporter-web-app/build.gradle.kts

By default, the extension uses node version 14.17.0, which is not
available for ARM64 machines, see [1]. Update to version 16.13.0 to be
able to build ORT on these machines.
[1]: https://youtrack.jetbrains.com/issue/KT-49109.

Gradle: Set NodeJsRootExtension's node version to 16.13.0

---

advisor/src/main/kotlin/AdviceProvider.kt
advisor/src/main/kotlin/advisors/GitHubDefects.kt
advisor/src/main/kotlin/advisors/NexusIq.kt
advisor/src/main/kotlin/advisors/OssIndex.kt
advisor/src/main/kotlin/advisors/VulnerableCode.kt
advisor/src/test/kotlin/advisors/GitHubDefectsTest.kt
advisor/src/test/kotlin/advisors/OssIndexTest.kt
advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
model/src/main/kotlin/AdvisorCapability.kt
model/src/main/kotlin/AdvisorDetails.kt
reporter/src/main/kotlin/reporters/freemarker/FreemarkerTemplateProcessor.kt
reporter/src/main/resources/templates/asciidoc/vulnerability_report.ftl
reporter/src/test/kotlin/reporters/freemarker/FreeMarkerTemplateProcessorTest.kt

If no vulnerabilities can be retrieved due to errors, the vulnerability report is currently misleading, since it only lists packages without further information. ORT issues are not shown, so there can be the false impression that no vulnerabilities have been found.
This PR changes the template for the vulnerability report to show a prominent warning if there were errors during the advisor run, so that it is obvious that the report is incomplete. Also, the issues assigned to the single packages are now shown.
When deciding whether or not to display this warning, there is the problem that there are now advisor implementations retrieving different findings, e.g. defects. The warning is, however, relevant only if an advisor for vulnerabilities is affected. To handle this, the PR extends the …

Vulnerability report: Improve error handling

---

README.md
cli/src/main/kotlin/OrtMain.kt
helper-cli/src/main/kotlin/commands/GetPackageLicensesCommand.kt
helper-cli/src/main/kotlin/commands/ListStoredScanResultsCommand.kt
helper-cli/src/main/kotlin/commands/scanstorage/DeleteCommand.kt

This is a fix-up for b70e3f4366d1401bc0f22493ff81a674060bc16e.

Fix the examples for overriding a postgres storage config property

---

cli/src/main/kotlin/commands/ScannerCommand.kt
model/build.gradle.kts
model/src/test/kotlin/utils/PostgresFileArchiverStorageTest.kt
scanner/build.gradle.kts
scanner/src/funTest/kotlin/experimental/AbstractNestedProvenanceStorageFunTest.kt
scanner/src/funTest/kotlin/experimental/AbstractPackageProvenanceStorageFunTest.kt
scanner/src/funTest/kotlin/experimental/DefaultNestedProvenanceResolverFunTest.kt
scanner/src/funTest/kotlin/experimental/DefaultPackageProvenanceResolverFunTest.kt
scanner/src/funTest/kotlin/experimental/FileBasedNestedProvenanceStorageFunTest.kt
scanner/src/funTest/kotlin/experimental/FileBasedPackageProvenanceStorageFunTest.kt
scanner/src/funTest/kotlin/experimental/PostgresNestedProvenanceStorageFunTest.kt
scanner/src/funTest/kotlin/experimental/PostgresPackageProvenanceStorageFunTest.kt
scanner/src/funTest/kotlin/experimental/ProvenanceBasedPostgresStorageFunTest.kt
scanner/src/funTest/kotlin/storages/PostgresStorageFunTest.kt
scanner/src/main/kotlin/experimental/FileBasedNestedProvenanceStorage.kt
scanner/src/main/kotlin/experimental/FileBasedPackageProvenanceStorage.kt
scanner/src/main/kotlin/experimental/NestedProvenance.kt
scanner/src/main/kotlin/experimental/NestedProvenanceResolver.kt
scanner/src/main/kotlin/experimental/NestedProvenanceStorage.kt
scanner/src/main/kotlin/experimental/PackageProvenanceResolver.kt
scanner/src/main/kotlin/experimental/PackageProvenanceStorage.kt
scanner/src/main/kotlin/experimental/PostgresNestedProvenanceStorage.kt
scanner/src/main/kotlin/experimental/PostgresPackageProvenanceStorage.kt
utils/test/build.gradle.kts
utils/test/src/main/kotlin/PostgresListener.kt

Add storages for resolved provenances, used by the experimental scanner. This provides a massive performance improvement by reducing the amount of required VCS operations. This PR adds the storages and configures a default local file storage for the experimental scanner. Configuration options will be added in another PR.

Experimental scanner: Add provenance storages

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt

The command matches the given packages IDs against the database entries
of the 'scan_results' table, which belongs to the postgres storage, to
determine the provenance. Only the most recent provenance per id and
provenance type is used in case there are many matches, like it happens
e.g. for snapshot artifacts.
The command can be used to trigger scans for arbitrary sets of package
IDs by just passing the file to ORT's `scan` CLI command. That can be
useful for re-scanning with a different ScanCode or for any development
task which requires a synthetic analyzer result for any specific
package ID.

helper-cli: Add a command to generate a synthetic analyzer result

---

scanner/src/main/kotlin/experimental/PostgresNestedProvenanceStorage.kt

This is a follow-up to f70ac03.

Align on using find instead of firstOrNull, continued

---

.github/workflows/static-analysis.yml

See [1].
[1]: https://github.blog/changelog/2021-11-23-github-actions-setup-python-now-supports-dependency-caching/

github: Enable caching of pip dependencies

---

downloader/src/main/kotlin/VcsHost.kt

This is a fixup for b39e446, which caused a NPE triggered by 13b70a7.

VcsHost: Also exit early in case of a blank `projectUrl`

---

docs/reporters/AsciiDocTemplateReporter.md

The generic AsciiDocTemplateReporter was replaced in
04388b847473c8fe587b46b1879559977ffeacd4 with more specific reporters.

AsciiDocTemplateReporter: Fix outdated documentation

---

.github/workflows/gradle-wrapper-validation.yml
.github/workflows/static-analysis.yml

The branch protection settings in GitHub show job names without their
belonging workflow names, so improve names a bit for readability.

github-workflows: Give some jobs more speaking names

---

Dockerfile

As the Gradle distribution to use is changed, the checksum is not
applicable anymore. This is a fixup for 91f071f.

Dockerfile: Delete the Gradle wrapper's `distributionSha256Sum`

---

downloader/src/main/kotlin/VcsHost.kt
downloader/src/test/kotlin/VcsHostTest.kt

This is (another) fixup for 13b70a7.

VcsHost: Fix an NPE if there is no query in a TFS URL

---

build.gradle.kts
utils/core/build.gradle.kts

This also fixes the ORT version to be available inside the shadow JAR
for the `cli` module.

Gradle: Set the ORT version on each subproject

---

analyzer/src/main/kotlin/PackageManager.kt

Inside a JAR, the "META-INF/maven" directory usually contains the
"pom.xml" file that was used to build the JAR [1]. Ignore such POMs if for
whatever reason they are committed to the repository being analyzed.
[1]: https://maven.apache.org/guides/mini/guide-archive-configuration.html

PackageManager: Ignore "META-INF/maven" directories

---

.github/workflows/build-and-test.yml

These still require some tools to be installed.

github-workflows: Disable running functional tests jobs for now

---

reporter/src/main/kotlin/reporters/ctrlx/CtrlXAutomationReporter.kt

CtrlXAutomationReporter: Ensure to always have at least one component license

---

reporter/src/main/kotlin/reporters/ctrlx/CtrlXAutomationReporter.kt

CtrlXAutomationReporter: Extract the `NOASSERTION` `License` to a constant

---

analyzer/src/main/kotlin/managers/Pub.kt

This partially solves https://github.com/oss-review-toolkit/ort/issues/4651.
However, it is important that `flutter pub get` is run before the `Gradle` project is analyzed this might still cause concurrency issues.

Pub: Run flutter pub get to install dependencies in flutter projects

---

analyzer/src/funTest/kotlin/GitRepoFunTest.kt
analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
analyzer/src/main/kotlin/managers/GoDep.kt
analyzer/src/main/kotlin/managers/Gradle.kt
analyzer/src/main/kotlin/managers/Pip.kt
downloader/src/funTest/kotlin/vcs/GitRepoDownloadFunTest.kt
downloader/src/main/kotlin/Downloader.kt
model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/main/kotlin/utils/FileArchiver.kt
model/src/main/kotlin/utils/FileArchiverFileStorage.kt
model/src/main/kotlin/utils/PostgresFileArchiverStorage.kt
model/src/test/kotlin/utils/PostgresFileArchiverStorageTest.kt
reporter/src/funTest/kotlin/reporters/ExcelReporterFunTest.kt
reporter/src/main/kotlin/reporters/freemarker/asciidoc/AsciiDocTemplateReporter.kt
scanner/src/main/kotlin/storages/Sw360Storage.kt

Consistently use ORT's own function for temporary files 

---

utils/spdx/src/main/kotlin/SpdxConstants.kt
utils/spdx/src/test/kotlin/UtilsTest.kt

This is useful as a "real looking" code that in fact describes no input.

spdx-utils: Add a constant for an empty package verification code

---

cli/src/main/kotlin/commands/ScannerCommand.kt
model/src/main/kotlin/config/ProvenanceStorageConfiguration.kt
model/src/main/kotlin/config/ScannerConfiguration.kt
model/src/main/resources/reference.conf
model/src/test/kotlin/config/OrtConfigurationTest.kt

Add configuration options to configure either a file storage or a
PostgreSQL storage to store provenance information. This is used only by
the experimental scanner.
By default a local file storage is used as prior to this commit.

Make the provenance storage configurable

---

analyzer/src/funTest/assets/projects/synthetic/spdx-project-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/spdx/package/libs/curl/package.spdx.yml
analyzer/src/funTest/assets/projects/synthetic/spdx/package/libs/zlib/package.spdx.yml
analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml
analyzer/src/funTest/kotlin/managers/SpdxDocumentFileFunTest.kt
analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
analyzer/src/test/kotlin/managers/SpdxDocumentFileTest.kt
model/src/main/kotlin/Package.kt
model/src/main/kotlin/PackageCurationData.kt
model/src/main/kotlin/Project.kt
model/src/test/kotlin/PackageCurationTest.kt

CPEs are an alternative mechanism to identify software components, and
in some areas, e.g. databases for security vulnerabilities, they are
in widespread use. To support use cases in these domains, enable ORT
to store these identifiers if they are available.
This PR is related to #4755.

Model: Add support for CPE identifiers
