- advisor/src/main/kotlin/advisors/NexusIq.kt
- model/src/main/kotlin/AdvisorRecord.kt
- model/src/main/kotlin/AdvisorResult.kt
- model/src/main/kotlin/Vulnerability.kt
- model/src/test/kotlin/AdvisorResultContainerTest.kt
> Correct advisor deserialization of vulnerabilities.

- model/src/main/kotlin/OrtResult.kt
- reporter/src/main/resources/templates/asciidoc/vulnerabilities.ftl
> Expand the AsciidocTemplateReporter to support reports for vulnerabilities.

- clients/nexus-iq/src/main/kotlin/NexusIqService.kt
Nexus IQ Server requires the X-CSRF-TOKEN header and the corresponding
CLM-CSRF-TOKEN cookie, when the server authentication is handled by a
reverse proxy server, see [1].
Servers without reverse proxy server authentication are not affected by
this additional header and cookie.
[1] https://books.sonatype.com/sonatype-clm-book/1.32/html/book/api-rut-auth-and-csrf.html
> NexusIqService: Add CSRF header and cookie

- analyzer/src/test/kotlin/managers/utils/NodeSupportTest.kt
- test-utils/src/main/kotlin/Extensions.kt
- test-utils/src/main/kotlin/Utils.kt
- utils/src/main/kotlin/OrtProxySelector.kt
- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/OrtProxySelectorTest.kt
> Support defining proxies only for specific hosts

- analyzer/src/main/kotlin/managers/Carthage.kt
> Carthage: Document that also Objective-C is supported

- analyzer/src/main/kotlin/managers/Carthage.kt
- evaluator/src/main/kotlin/PackageRule.kt
- model/src/main/kotlin/Project.kt
> Fix formatting for a few expression functions

- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- model/src/main/kotlin/config/OrtConfiguration.kt
> Better output for config path information

- model/src/main/kotlin/PackageCuration.kt
- model/src/test/kotlin/PackageCurationTest.kt
> Ivy curation improvements

- advisor/src/main/kotlin/advisors/NexusIq.kt
To avoid server overload and timeouts the request to retrieve security vulnerabilities is now chunked into 100 packages at a time and requested sequentially.
Resolves #3414.
> NexusIq: Retrieve vulnerabilities from Nexus IQ in chunks

- reporter/src/main/kotlin/reporters/AsciiDocTemplateReporter.kt
- reporter/src/main/kotlin/reporters/NoticeTemplateReporter.kt
- reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
> Freemarker defaults

- model/src/main/kotlin/Vulnerability.kt
> Vulnerability: Give a clue about the CVSS range

- reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
> CycloneDX improvements

- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
> Cli safe mkdirs

- analyzer/src/main/kotlin/managers/utils/NuGetAllPackageData.kt
- analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
> NuGet improvements

- cli/src/main/kotlin/commands/ScannerCommand.kt
- evaluator/src/test/kotlin/TestData.kt
- model/src/main/kotlin/TextLocation.kt
- model/src/test/kotlin/RootLicenseMatcherTest.kt
- model/src/test/kotlin/ScanResultContainerTest.kt
- model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
- model/src/test/kotlin/licenses/TestData.kt
- model/src/test/kotlin/utils/FindingCurationMatcherTest.kt
- reporter/src/funTest/kotlin/TestData.kt
- reporter/src/funTest/kotlin/reporters/SpdxDocumentReporterFunTest.kt
- scanner/src/funTest/kotlin/scanners/scancode/ScanCodeScannerFunTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/RemoteScanner.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/FileCounter.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/ScanCode.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
- scanner/src/main/resources/META-INF/services/org.ossreviewtoolkit.scanner.ScannerFactory
- scanner/src/test/kotlin/LocalScannerTest.kt
- scanner/src/test/kotlin/ScanCodeTest.kt
- scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt
- scanner/src/test/kotlin/scanners/scancode/ScanCodeTest.kt
> Remote scanner base

- model/src/main/kotlin/OrtResult.kt
- model/src/test/kotlin/config/ExcludesTest.kt
- reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
Rewrite the functions to fix some issues and clean up the code. See the commit messages for details.
> OrtResult: Rewrite the isExcluded functions

- model/src/main/kotlin/OrtResult.kt
This is exactly what the "perf" level is for. Add the duration while at
it.
> OrtResult: Use "perf" log level for excludes calculation

- cli/src/main/kotlin/commands/DownloaderCommand.kt
- utils/src/main/kotlin/ArchiveUtils.kt
- utils/src/main/kotlin/storage/FileArchiver.kt
> Archiving improvements

- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/ScanResultsStorage.kt
> scanner: Introduce and use a constant for the number of dispatcher theads

- cli/src/main/kotlin/commands/DownloaderCommand.kt
- downloader/src/main/kotlin/Downloader.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/main/kotlin/storage/FileArchiver.kt
> Download archive improvements

- .azure-pipelines/LinuxAnalyzerTest.yml
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/Pip.kt
> Analyzer relax upper bound

- analyzer/src/main/kotlin/managers/Npm.kt
> Npm: Fix a potential NPE if no "version" field is present at all

- README.md
> README: Update instructions that still referred to "Main.kt"

- reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
> Show the scanned repository and revision in the static HTML report

- analyzer/src/main/kotlin/managers/Maven.kt
> Warn about auto-generated POMs

- model/src/main/kotlin/licenses/LicenseClassifications.kt
> LicenseClassifications helpers

- gradle/wrapper/gradle-wrapper.properties
- reporter-web-app/build.gradle.kts
> Upgrade to Gradle 6.8

- advisor/src/main/kotlin/advisors/NexusIq.kt
- cli/src/main/kotlin/commands/AdvisorCommand.kt
- model/src/main/kotlin/config/AdvisorConfiguration.kt
- model/src/test/assets/reference.conf
- model/src/test/kotlin/config/NexusIqConfigurationTest.kt
> Link Sonatype vulnerabilities

- clients/nexus-iq/src/main/kotlin/NexusIqService.kt
- detekt-rules/src/main/kotlin/OrtImportOrder.kt
- model/src/test/kotlin/SimplePackageConfigurationProviderTest.kt
- reporter/src/main/kotlin/reporters/AsciiDocTemplateReporter.kt
- scanner/src/main/kotlin/storages/PostgresStorage.kt
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
- scanner/src/test/kotlin/storages/CompositeStorageTest.kt
- utils/src/main/kotlin/OkHttpClientHelper.kt
Please refer to the commit messages for details.
> Update detekt rule to check for line breaks between top-level packages in the imports.

- examples/rules.kts
- model/src/main/kotlin/licenses/LicenseClassifications.kt
- model/src/test/kotlin/licenses/LicenseClassificationsTest.kt
- utils/src/main/kotlin/Extensions.kt
> LicenseClassifications improvements

- spdx-utils/src/main/kotlin/model/SpdxPackage.kt
See https://spdx.github.io/spdx-spec/3-package-information/#311-package-home-page.
> SpdxPackage: Fix the homepage to be optional

- examples/rules.kts
- model/src/main/kotlin/licenses/LicenseView.kt
- model/src/test/kotlin/licenses/LicenseViewTest.kt
- reporter/src/main/resources/templates/asciidoc/disclosure_document.ftl
- reporter/src/main/resources/templates/notice/default.ftl
- reporter/src/main/resources/templates/notice/summary.ftl
> LicenseView improvements

- analyzer/src/test/kotlin/PackageManagerTest.kt
> PackageManagerTest: Make a check insensitive to key order changes

- reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
> FreemarkerTemplateProcessor: Fix-up an error message

- downloader/src/main/kotlin/Downloader.kt
- model/src/main/kotlin/Environment.kt
> Extract the HTTP User Agent to a dedicated variable for convenience

- gradle/wrapper/gradle-wrapper.properties
See https://github.com/gradle/gradle/releases/tag/v6.8.1.
> Upgrade Gradle to version 6.8.1

- model/src/main/kotlin/config/FileStorageConfiguration.kt
- model/src/main/kotlin/config/HttpFileStorageConfiguration.kt
- model/src/test/assets/reference.conf
- model/src/test/kotlin/config/HttpFileStorageConfigurationTest.kt
- scanner/src/test/kotlin/ScanResultsStorageTest.kt
- utils/src/main/kotlin/storage/HttpFileStorage.kt
> Add postfix field to HttpFileStorage

- analyzer/src/funTest/assets/projects/synthetic/maven-wagon-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/maven-wagon/pom.xml
- analyzer/src/funTest/kotlin/managers/MavenFunTest.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
Fix loading Maven build extensions, see the commit messages for details.
> Maven support build extensions

- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/test/kotlin/ExtensionsTest.kt
> Remove the String.isValidUrl() extension function

- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
> Avoid the term "packageUrl" in the  ClearlyDefinedStorage

- integrations/azure/README.md
- integrations/azure/credentials/write-config-netrc.yml
- integrations/azure/credentials/write-downloader-netrc.yml
- integrations/azure/ort-pipeline.yml
- integrations/azure/steps/complete-ort-run.yml
> Improve Azure pipeline display names

- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- cli/src/funTest/kotlin/OrtMainFunTest.kt
- clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
- clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
- detekt-rules/src/main/kotlin/OrtImportOrder.kt
- downloader/src/funTest/kotlin/BabelFunTest.kt
- downloader/src/funTest/kotlin/BeanUtilsFunTest.kt
- downloader/src/funTest/kotlin/DownloaderFunTest.kt
- downloader/src/test/kotlin/VcsHostTest.kt
- model/src/test/kotlin/PackageTest.kt
- model/src/test/kotlin/config/OrtConfigurationTest.kt
- model/src/test/kotlin/config/ScannerConfigurationTest.kt
- model/src/test/kotlin/utils/FindingCurationMatcherTest.kt
- reporter/src/test/kotlin/reporters/ExcelReporterTest.kt
- scanner/src/funTest/kotlin/scanners/AbstractScannerFunTest.kt
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
- spdx-utils/src/test/kotlin/SpdxDeclaredLicenseMappingTest.kt
- spdx-utils/src/test/kotlin/SpdxLicenseTest.kt
- spdx-utils/src/test/kotlin/SpdxSimpleLicenseMappingTest.kt
- spdx-utils/src/test/kotlin/SpdxUtilsTest.kt
- utils/src/test/kotlin/DeclaredLicenseProcessorTest.kt
- utils/src/test/kotlin/ExtensionsTest.kt
- utils/src/test/kotlin/OrtAuthenticatorTest.kt
- utils/src/test/kotlin/UtilsTest.kt
> Infix syntax for tests

- model/src/main/kotlin/config/LicenseFindingCuration.kt
> LicenseFindingCuration improvements

- utils/src/main/kotlin/CommandLineTool.kt
- utils/src/main/kotlin/Utils.kt
> CommandLineTool clean-ups

- README.md
As discussed in TSC meeting of January 28, 2021.
> README: Add CII best practices badge

- cli/src/funTest/kotlin/ExamplesFunTest.kt
- examples/README.md
> examples: Add a README about consulting your legal counsel

- analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
> PipFunTest: Update the expected pytz version to be 2021.1

- Dockerfile
> Dockerfile: Update Cargo to the available upstream version

- integrations/azure/README.md
- integrations/azure/ort-pipeline.yml
In particular, get rid of the term "starter" which sounds a bit like
"for starters", i.e. for beginners.
> azure: Apply various small wording improvements and typo fixes

- scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
- spdx-utils/src/main/kotlin/SpdxConstants.kt
- spdx-utils/src/main/kotlin/SpdxExpression.kt
- spdx-utils/src/main/kotlin/SpdxUtils.kt
> Add and use SPDX constants for license and document references

- utils/src/test/kotlin/DeclaredLicenseProcessorTest.kt
> Add a test for processing a compound expression

- utils/src/main/kotlin/CopyrightStatementsProcessor.kt
During investigating the issue described in #3511 I found that these tweaks do make sense. Even though they do not address the "real big issue" (for which I'll file another PR) they improve on the performance problem in #3511 a bit.
> Copyright statements processing performance tweaks

- reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
> CycloneDxReporter: Extract a constant for visibility

- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/RequirementsCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
> cli: Improve the help wording of some subcommands

- analyzer/build.gradle.kts
- analyzer/src/main/kotlin/curation/Sw360PackageCurationProvider.kt
- cli/build.gradle.kts
- cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
- gradle.properties
- helper-cli/build.gradle.kts
- model/src/main/kotlin/config/ScanStorageConfiguration.kt
- model/src/test/assets/reference.conf
- model/src/test/kotlin/config/OrtConfigurationTest.kt
- model/src/test/kotlin/config/Sw360StorageConfigurationTest.kt
- scanner/build.gradle.kts
- scanner/src/main/kotlin/storages/Sw360Storage.kt
The SW360 client is only released as a snapshot for now, but this way we
can keep track of its releases, and avoid getting bogus update
notifications about weekly Antenna builds.
Please ensure that your pull request adheres to our [contribution guidelines](../CONTRIBUTING.md). Thank you!
> Switch from Antenna to the official SW360 client

- clients/fossid-webapp/src/main/kotlin/Extensions.kt
- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- clients/fossid-webapp/src/test/assets/new-project/mappings/apiphp-list_pending_files.json
- clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
> Add function 'get_pending_files' to FossID API service

- gradle/wrapper/gradle-wrapper.properties
See https://github.com/gradle/gradle/releases/tag/v6.8.2.
> Upgrade Gradle to version 6.8.2

- cli/src/main/kotlin/commands/ReporterCommand.kt
Note that while async() is documented to use Dispatchers.Default, an
inherited coroutine context takes precedence [1]. Here, that is the
context of runBlocking(), which by default uses "an internal
implementation of [an] event loop that processes continuations in this
blocked thread" [2], so it blocks the main thread. Explicitly use
Dispatchers.Default to avoid that and to benefit from parallelism.
[1] https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html
[2] https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/run-blocking.html
> ReporterCommand: Generate reports in parallel to improve performance

- cli/src/main/kotlin/commands/UploadCurationsCommand.kt
- reporter/src/main/kotlin/reporters/AmazonOssAttributionBuilderReporter.kt
> Generalize Retrofit service calls to align and simplify code

- build.gradle.kts
> Gradle: Explain why Git output needs to match exactly

- clients/fossid-webapp/src/main/kotlin/Extensions.kt
This PR is a follow-up of this [comment](https://github.com/oss-review-toolkit/ort/pull/3593#discussion_r570904445).
> Rewrite FossID extensions documentation in KDoc style

- scanner/src/main/kotlin/storages/PostgresStorage.kt
> PostgresStorage: Change nested log statements to log on the outer class

- analyzer/src/main/kotlin/Analyzer.kt
Using the default IO dispatcher [1] instead of a custom thread pool
simplifies the code.
[1] https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/-i-o.html
> Analyzer: Run analyzers with the default IO dispatcher

- model/src/test/assets/reference.conf
- model/src/test/kotlin/config/OrtConfigurationTest.kt
> reference.conf: Add SW360 scan results storage

- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
- scanner/src/test/assets/h2database-1.4.200_scancode-3.2.1.json
- scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt
Please refer to the commit message for details.
> Parse license choice from ScanCode results

- model/src/test/assets/reference.conf
> reference.conf: Add an example for configuring the ScanCode command line

- analyzer/src/main/kotlin/managers/Bower.kt
- helper-cli/src/main/kotlin/commands/ImportLicenseFindingCurationsCommand.kt
- helper-cli/src/main/kotlin/common/Utils.kt
- model/src/main/kotlin/licenses/LicenseInfoResolver.kt
- model/src/main/kotlin/utils/FindingsMatcher.kt
- reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
- scanner/src/main/kotlin/storages/CompositeStorage.kt
- utils/src/main/kotlin/CopyrightStatementsProcessor.kt
> Prefer the more readable += operator over the .add(All) function

- model/src/main/kotlin/licenses/LicenseClassifications.kt
- spdx-utils/src/main/kotlin/Extensions.kt
- spdx-utils/src/main/kotlin/SpdxUtils.kt
- spdx-utils/src/main/kotlin/model/SpdxDocument.kt
- utils/src/main/kotlin/Extensions.kt
> Add sanity checks to guard against duplicate SPDX IDs

- advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
- clients/vulnerable-code/src/main/kotlin/VulnerableCodeService.kt
See the commit message for more details.
> VulnerableCodeService: Add slash character at bulk search URLs

- analyzer/src/main/kotlin/managers/Pip.kt
- utils/src/main/kotlin/Utils.kt
> Resolve Windows executables

- cli/src/main/kotlin/commands/UploadResultToPostgresCommand.kt
- model/src/main/kotlin/OrtResult.kt
- model/src/main/kotlin/Project.kt
> Convert scopes on upload

- analyzer/src/main/kotlin/managers/Pip.kt
- detekt-rules/src/main/kotlin/OrtImportOrder.kt
- model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
- scanner/src/main/kotlin/LocalScanner.kt
- utils/src/main/kotlin/DirectoryStash.kt
- utils/src/main/kotlin/Logger.kt
Fixes for issues highlighted by the code inspector of the IntelliJ IDE.
> Miscellaneous code inspection fixes

- gradle.properties
- scanner/build.gradle.kts
- scanner/src/funTest/kotlin/storages/PostgresStorageFunTest.kt
- scanner/src/main/kotlin/ScanResultsStorage.kt
- scanner/src/main/kotlin/storages/PostgresStorage.kt
- scanner/src/main/kotlin/storages/utils/ExposedUtils.kt
- scanner/src/main/kotlin/storages/utils/JsonbSupport.kt
- scanner/src/main/kotlin/storages/utils/ScanResultDao.kt
Use Exposed for database access, see the commit messages for details. I still need to test this implementation with a real database, but reviews are welcome already.
> Use Exposed for database access

- advisor/src/main/kotlin/Advisor.kt
- analyzer/src/main/kotlin/Analyzer.kt
- cli/src/main/kotlin/OrtMain.kt
- clients/nexus-iq/src/main/kotlin/NexusIqService.kt
- downloader/src/main/kotlin/Downloader.kt
- evaluator/src/test/kotlin/TestData.kt
- model/build.gradle.kts
- model/src/main/kotlin/AdvisorRun.kt
- model/src/main/kotlin/AnalyzerRun.kt
- model/src/main/kotlin/ScannerRun.kt
- model/src/test/kotlin/OrtResultTest.kt
- model/src/test/kotlin/config/ExcludesTest.kt
- model/src/test/kotlin/licenses/TestData.kt
- reporter/src/funTest/kotlin/TestData.kt
- reporter/src/funTest/kotlin/reporters/GitLabLicenseModelReporterFunTest.kt
- reporter/src/funTest/kotlin/reporters/SpdxDocumentReporterFunTest.kt
- reporter/src/funTest/kotlin/reporters/StaticHtmlReporterFunTest.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
- reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt
- reporter/src/test/kotlin/utils/FreeMarkerTemplateProcessorTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/Scanner.kt
- utils/build.gradle.kts
- utils/src/main/kotlin/Environment.kt
- utils/src/main/kotlin/OkHttpClientHelper.kt
> Set a default HTTP agent for all ORT requests

- analyzer/src/main/kotlin/managers/Pub.kt
Please have a look at the commit messages.
> Improvements for Pub

- advisor/src/main/kotlin/advisors/NexusIq.kt
- advisor/src/main/kotlin/advisors/VulnerableCode.kt
- analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
- reporter/src/main/kotlin/reporters/AmazonOssAttributionBuilderReporter.kt
- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
- utils/src/main/kotlin/OkHttpClientHelper.kt
> OkHttp client lazy initialization

- gradle/wrapper/gradle-wrapper.properties
See https://github.com/gradle/gradle/releases/tag/v6.8.3.
> Upgrade Gradle to version 6.8.3

- model/src/main/kotlin/utils/FileArchiver.kt
> FileArchiver improvements

- analyzer/src/main/resources/scripts/python_compatibility.py
- analyzer/src/main/resources/scripts/python_interpreter.py
- spdx-utils/src/main/resources/simple-license-mapping.yml
- utils/src/main/kotlin/Utils.kt
> Python fixes

- scanner/src/funTest/kotlin/storages/PostgresStorageFunTest.kt
- scanner/src/main/kotlin/ScanResultsStorage.kt
- scanner/src/main/kotlin/storages/PostgresStorage.kt
> PostgresStorage: Fix schema issue

- analyzer/src/main/kotlin/managers/Npm.kt
- analyzer/src/main/kotlin/managers/utils/NodeSupport.kt
- analyzer/src/test/kotlin/managers/utils/NodeSupportTest.kt
Please ensure that your pull request adheres to our [contribution guidelines](../CONTRIBUTING.md). Thank you!
> Private npm registry management

- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
> MavenSupport: Apply some trivial code style improvements

- model/src/main/kotlin/utils/FileArchiver.kt
> FileArchiver: Guard against empty provenance

- analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
- analyzer/src/funTest/kotlin/integration/DrupalIntegrationFunTest.kt
- analyzer/src/funTest/kotlin/integration/GradleIntegrationFunTest.kt
- analyzer/src/funTest/kotlin/integration/PolymerIntegrationFunTest.kt
- analyzer/src/funTest/kotlin/integration/SimpleFormIntegrationFunTest.kt
- analyzer/src/funTest/kotlin/integration/VueJsIntegrationFunTest.kt
- downloader/src/funTest/kotlin/BabelFunTest.kt
- downloader/src/funTest/kotlin/BeanUtilsFunTest.kt
- downloader/src/funTest/kotlin/DownloaderFunTest.kt
- downloader/src/main/kotlin/Downloader.kt
- helper-cli/src/main/kotlin/common/Utils.kt
- scanner/src/main/kotlin/LocalScanner.kt
> Consolidate the DownloadResult into the Provenance

- scanner/src/main/kotlin/ScanResultsStorage.kt
- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
- scanner/src/main/kotlin/storages/CompositeStorage.kt
- scanner/src/main/kotlin/storages/FileBasedStorage.kt
- scanner/src/main/kotlin/storages/NoStorage.kt
- scanner/src/main/kotlin/storages/PostgresStorage.kt
- scanner/src/main/kotlin/storages/Sw360Storage.kt
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
Several improvements of the ScanResultsStorage, please see the commit messages for details.
> ScanResultsStorage improvements

- model/src/main/kotlin/ScanResult.kt
- model/src/main/kotlin/ScanSummary.kt
- model/src/main/kotlin/utils/FileArchiver.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/FileCounter.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- utils/src/main/kotlin/FileMatcher.kt
> Scan summary for local scanners

- clients/fossid-webapp/src/main/kotlin/model/status/ScanState.kt
> Add missing entry to FossID scan state enum

- analyzer/src/main/kotlin/managers/Cargo.kt
> Cargo: Add a comment about license operators based on previous commit messages

- scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
Most importantly, get rid of a lengthy and rather confusing comment in
favor of shorter comments in a few places.
> ScanCodeResultParser: Rewrite getLicenseId() for clarity

- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- downloader/src/main/kotlin/Downloader.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- helper-cli/src/main/kotlin/common/Utils.kt
- utils/src/main/kotlin/Extensions.kt
> String without prefix

- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/.gitignore
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/build.sbt
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/native-image-readme.md
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/project/build.properties
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/project/plugins.sbt
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/src/main/resources/META-INF/native-image/com/example/http4stemplate/reflect-config.json
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/src/main/resources/logback.xml
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/src/main/scala/com/example/http4stemplate/HelloWorld.scala
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/src/main/scala/com/example/http4stemplate/Http4stemplateRoutes.scala
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/src/main/scala/com/example/http4stemplate/Http4stemplateServer.scala
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/src/main/scala/com/example/http4stemplate/Jokes.scala
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/src/main/scala/com/example/http4stemplate/Main.scala
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/src/test/scala/com/example/http4stemplate/HelloWorldSpec.scala
- analyzer/src/funTest/kotlin/managers/SbtFunTest.kt
We should have at least one *synthetic* test per package manager. So far we did not have one for Sbt, so add one.
> Add a synthetic Sbt test

- utils/src/main/kotlin/DeclaredLicenseProcessor.kt
- utils/src/test/kotlin/DeclaredLicenseProcessorTest.kt
> DeclaredLicenseProcessor improvements

- cli/src/main/kotlin/OrtMain.kt
This is sometimes useful to search for common options across subcommands
by piping through "grep".
> OrtMain: Add an option to display the help for all subcommands

- analyzer/src/funTest/assets/projects/synthetic/spdx-project-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
> Miscellaneous small SPDX improvements

- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt
> More small SPDX-related improvements

- .azure-pipelines/DockerBuild.yml
- .azure-pipelines/StaticAnalysis.yml
> Azure pipeline improvements

- build.gradle.kts
- gradle.properties
> Idea ext runner config improvements

- analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
- analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml
- analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template-expected-output.yml
- analyzer/src/main/kotlin/managers/Maven.kt
- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
> Fix licenses from Maven projects to be combined with "OR"

- .gitattributes
- helper-cli/src/main/kotlin/commands/VerifySourceArtifactCurationsCommand.kt
- model/src/main/kotlin/Hash.kt
- model/src/main/kotlin/HashAlgorithm.kt
- model/src/test/kotlin/HashAlgorithmTest.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/test/kotlin/ExtensionsTest.kt
> Add support for SHA-1 for Git "blob" objects

- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- clients/fossid-webapp/src/main/kotlin/model/result/MatchType.kt
This PR is a collection of minor fixes to FossID scanner
> Several minor fixes to FossID scanner

- spdx-utils/src/main/kotlin/SpdxModelMapper.kt
> SpdxModelMapper: Add grouping code comments for readability

- scanner/src/main/kotlin/storages/PostgresStorage.kt
Use a function from the Exposed API to check if the table exists,
because this requires less code than the custom query.
> PostgresStorage: Use the Exposed API to check if the table exists

- docs/config-file-ort-yml.md
- examples/resolutions.yml
- helper-cli/src/main/kotlin/common/Utils.kt
- model/src/main/kotlin/config/RepositoryConfiguration.kt
- model/src/main/kotlin/config/Resolutions.kt
- model/src/main/kotlin/config/VulnerabilityResolution.kt
- model/src/main/kotlin/config/VulnerabilityResolutionReason.kt
- model/src/main/kotlin/utils/DefaultResolutionProvider.kt
- model/src/main/kotlin/utils/ResolutionProvider.kt
- model/src/test/kotlin/config/RepositoryConfigurationTest.kt
- reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
- reporter/src/main/resources/templates/asciidoc/vulnerability_report.ftl
Please refer to the commit messages for details.
> Allow vulnerabilities to be resolved

- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/utils/NodeSupport.kt
- analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
- build.gradle.kts
- cli/src/funTest/kotlin/OrtMainFunTest.kt
- cli/src/main/kotlin/commands/RequirementsCommand.kt
- downloader/src/main/kotlin/VcsHost.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- gradle.properties
- helper-cli/src/main/kotlin/commands/SubtractScanResultsCommand.kt
- scanner/src/main/kotlin/storages/FileBasedStorage.kt
- scanner/src/main/kotlin/storages/Sw360Storage.kt
- spdx-utils/build.gradle.kts
- spdx-utils/src/main/kotlin/Extensions.kt
- spdx-utils/src/main/kotlin/SpdxExpressionDefaultVisitor.kt
- spdx-utils/src/main/kotlin/model/SpdxExternalReference.kt
- spdx-utils/src/test/kotlin/SpdxDeclaredLicenseMappingTest.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/ExtensionsTest.kt
> Upgrade detekt

- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/utils/NodeSupport.kt
- downloader/src/main/kotlin/VcsHost.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/main/kotlin/Utils.kt
> Introduce and use helper functions for common String to URI conversion

- clients/fossid-webapp/src/main/kotlin/model/identification/common/LicenseMatchType.kt
- clients/fossid-webapp/src/main/kotlin/model/result/MatchType.kt
- clients/fossid-webapp/src/main/kotlin/model/status/DownloadStatus.kt
- clients/fossid-webapp/src/main/kotlin/model/status/ScanState.kt
- clients/fossid-webapp/src/main/kotlin/model/status/ScanStatusType.kt
> FossID: Add missing match type to the enum

- advisor/src/main/kotlin/advisors/NexusIq.kt
- advisor/src/main/kotlin/advisors/VulnerableCode.kt
- advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
- cli/src/main/kotlin/commands/AdvisorCommand.kt
- model/src/main/kotlin/config/AdvisorConfiguration.kt
- model/src/main/kotlin/config/OrtConfiguration.kt
- model/src/main/resources/reference.conf
- model/src/test/kotlin/config/NexusIqConfigurationTest.kt
See the commit message and [hoplite](https://github.com/sksamuel/hoplite#sealed-classes) why this ambiguity is a problem.
This solution might not be the most satisfying, but it requires only a few code changes and the VulnerableCode extension is an experiment in the moment anyway.
> AdvisorConfiguration: Resolve ambiguity between configurations

- model/src/main/kotlin/utils/FileArchiver.kt
- model/src/main/kotlin/utils/FileArchiverFileStorage.kt
- model/src/main/kotlin/utils/FileArchiverStorage.kt
Factor out an interface for the file archive storage so that a second, PostgreSQl based, implementation can be added in a following PR.
> FileArchiver: Factor out an interface for the storage

- clients/fossid-webapp/src/main/kotlin/Extensions.kt
- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- clients/fossid-webapp/src/test/assets/new-project/mappings/apiphp-delete_scan.json
- clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
> fossid-webapp: Add 'delete scan' function

- analyzer/src/main/kotlin/managers/Carthage.kt
- analyzer/src/main/kotlin/managers/Composer.kt
- analyzer/src/main/kotlin/managers/GoMod.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Pip.kt
- analyzer/src/main/kotlin/managers/Pub.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- evaluator/src/main/kotlin/Rule.kt
- helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
- model/src/main/kotlin/config/LicenseFindingCuration.kt
- reporter/src/main/kotlin/reporters/EvaluatedModelReporter.kt
- reporter/src/main/kotlin/reporters/ExcelReporter.kt
- reporter/src/main/kotlin/reporters/SpdxDocumentReporter.kt
- reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
> cli: Align the handling of case-insensitive list options

- advisor/src/main/kotlin/VulnerabilityProviderFactory.kt
- advisor/src/main/kotlin/advisors/NexusIq.kt
- advisor/src/main/kotlin/advisors/VulnerableCode.kt
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- reporter/src/funTest/kotlin/reporters/SpdxDocumentReporterFunTest.kt
- spdx-utils/src/main/kotlin/SpdxModelMapper.kt
- spdx-utils/src/test/kotlin/SpdxDocumentModelTest.kt
- test-utils/src/main/kotlin/Extensions.kt
> Minor code improvements regarding generics

- spdx-utils/src/main/kotlin/SpdxExpression.kt
> SpdxExpression: Clarify the difference between decompose() and licenses()

- model/src/main/kotlin/utils/FileArchiverFileStorage.kt
This aligns with `Provenance.storageKey()` in `PostgresFileArchiverStorage.kt`.
> FileArchiverFileStorage: Fix the storage key for Git-Repo file archives

- cli/src/main/kotlin/commands/EvaluatorCommand.kt
This PR changes the return code of evaluator runs when only hint-severity violations are found.
The reasoning is in short: Hints should only be "hints", not real violations, so the return code should signal "success" (exit code 0) instead of "failure" (exit code 2) which would break the build.
See also the commit message.
> Signal success for evaluator if only HINT-level violations exist

- cli/build.gradle.kts
- cli/src/main/kotlin/commands/UploadResultToPostgresCommand.kt
Use exposed for database access and add an option to create the database table.
> Improve UploadResultToPostgresCommand

- reporter/src/main/resources/templates/asciidoc/disclosure_document.ftl
> Minor AsciiDoc report layout improvements

- clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- clients/nexus-iq/src/main/kotlin/NexusIqService.kt
- clients/oss-attribution-builder/src/main/kotlin/OssAttributionBuilderService.kt
- clients/vulnerable-code/src/main/kotlin/VulnerableCodeService.kt
> Add more API endpoints to the Nexus IQ service

- scanner/src/main/kotlin/ScanResultsStorage.kt
So far only for the file based storage configuration details were logged
to the console, add logs for the most important configuration values for
the other storage types as well.
> ScanResultsStorage: Log details for all storage types

- clients/vulnerable-code/src/main/kotlin/VulnerableCodeService.kt
That is what Retrofit itself does, see https://square.github.io/retrofit/.
> VulnerableCodeService: Align on using relative paths with Retrofit

- examples/rules.kts
- spdx-utils/src/main/kotlin/Extensions.kt
> Simplify the default way of getting duplicates

- scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
> ScanCodeResultParser: Apply miscellaneous small code improvements

- analyzer/src/main/kotlin/managers/Composer.kt
- analyzer/src/main/kotlin/managers/Npm.kt
- model/src/main/kotlin/Mappers.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/FileCounter.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
- scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt
> Introduce and use a generic readJsonFile() helper function

- docs/sw360-integration.md
Initial documentation for the usage of the SW360 integration.
> docs: Add documentation for all SW360 integration options

- cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
Create the release in SW360 with the concatenation of namespace, "/" and
name in order to find the releases in further steps again.
> UploadResultToSw360Command: Use namespace and name to create a release

- downloader/src/main/kotlin/WorkingTree.kt
- model/src/main/kotlin/config/LicenseFindingCurationReason.kt
> Fix formatting by removing blank lines after class declarations

- utils/src/main/kotlin/Extensions.kt
> Extensions: Trivially reduce some code duplication in String.toUri()

- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- spdx-utils/src/main/kotlin/model/SpdxDocument.kt
> Miscellaneous SPDX-related fixes and improvements

- .github/CODEOWNERS
> CODEOWNERS improvements

- analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml
- analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template-expected-output.yml
- spdx-utils/src/main/resources/declared-license-mapping.yml
> declared-license-mapping: Relax LGPL mapping if no version is specified

- cli/src/main/resources/log4j2.xml
- test-utils/src/main/resources/log4j2.xml
This is a follow-up to f195c5e.
> Also disable the "org.apache.http.{headers,wire}" loggers

- spdx-utils/src/main/resources/declared-license-mapping.yml
[1] https://github.com/locationtech/jts/blob/jts-1.17.1/pom.xml
> Add a declared license mapping for "Eclipse Public License, Version 2.0"

- spdx-utils/src/main/kotlin/model/SpdxDocument.kt
> SpdxDocument: Trivially improve some documentation

- reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
- spdx-utils/src/main/kotlin/SpdxExpression.kt
This helps to compare different SPDX expressions.
> SpdxExpression: Sort the DNF representation

- model/src/main/kotlin/HashAlgorithm.kt
- model/src/test/kotlin/HashAlgorithmTest.kt
> HashAlgorithm: Support calculation on InputStreams and Resources

- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
The Maven-internal HttpTransporter calls newOutputStream() on the
GetTask as needed, so the complexity can be reduced here a bit.
> MavenSupport: Avoid creating temporary files for checksum downloads

- spdx-utils/src/main/resources/declared-license-mapping.yml
Found in [1].
[1]: https://repo.maven.apache.org/maven2/net/sf/jpf/jpf/1.5/jpf-1.5.pom
> Add a declared license LGPL mapping

- reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
- reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
- reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt
- spdx-utils/src/main/kotlin/model/SpdxExternalReference.kt
> SpdxDocumentReporter: Add purl as SPDX externalRefs

- .detekt.license.template
- .github/workflows/static-analysis.yml
> Fix reuse check

- model/src/main/kotlin/utils/Extensions.kt
> Extensions: Reformat Identifier.toPurl() to be more readable

- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
Actually, the analyzer should not directly look for / handle SPDX
documents that describe a package instead of a project. Instead, only
projects should be handled, and packages are implicitly handled when
they are referred to from the project.
Resolves #3833.
> SpdxDocumentFile: Properly handle multiple package.spdx.xml files

- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- spdx-utils/src/main/kotlin/model/SpdxPackage.kt
See:
https://spdx.github.io/spdx-spec/3-package-information/#35-package-supplier
https://spdx.github.io/spdx-spec/3-package-information/#36-package-originator
> SpdxPackage: Fix the originator and supplier to take NOASSERTION

- model/src/main/kotlin/OrtResult.kt
> OrtResult: Add isPackage()

- analyzer/src/funTest/kotlin/managers/SpdxDocumentFileFunTest.kt
Added a test to the changes made in #3846
> SpdxDocumentFile: Test removing package.spdx.yml in mapDefinitionFiles

- advisor/src/main/kotlin/Advisor.kt
- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- helper-cli/src/main/kotlin/commands/ExportLicenseFindingCurationsCommand.kt
- helper-cli/src/main/kotlin/commands/ExportPathExcludesCommand.kt
- helper-cli/src/main/kotlin/commands/ExtractRepositoryConfigurationCommand.kt
- helper-cli/src/main/kotlin/commands/GenerateProjectExcludesCommand.kt
- helper-cli/src/main/kotlin/commands/GenerateRuleViolationResolutionsCommand.kt
- helper-cli/src/main/kotlin/commands/GenerateScopeExcludesCommand.kt
- helper-cli/src/main/kotlin/commands/GenerateTimeoutErrorResolutionsCommand.kt
- helper-cli/src/main/kotlin/commands/ImportLicenseFindingCurationsCommand.kt
- helper-cli/src/main/kotlin/commands/ImportScanResultsCommand.kt
- helper-cli/src/main/kotlin/commands/ListCopyrightsCommand.kt
- helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
- helper-cli/src/main/kotlin/commands/ListPackagesCommand.kt
- helper-cli/src/main/kotlin/commands/MapCopyrightsCommand.kt
- helper-cli/src/main/kotlin/commands/RemoveConfigurationEntriesCommand.kt
- helper-cli/src/main/kotlin/commands/SubtractScanResultsCommand.kt
- helper-cli/src/main/kotlin/commands/TransformResultCommand.kt
- helper-cli/src/main/kotlin/commands/packageconfig/ImportLicenseFindingCurationsCommand.kt
- helper-cli/src/main/kotlin/commands/packageconfig/RemoveEntriesCommand.kt
- reporter/src/funTest/kotlin/reporters/CycloneDxReporterFunTest.kt
- scanner/src/main/kotlin/Scanner.kt
> ORT result file consistency changes

- gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/7.0/release-notes.html.
> Upgrade Gradle to version 7.0

- helper-cli/src/main/kotlin/commands/GeneratePackageConfigurationsCommand.kt
- helper-cli/src/main/kotlin/commands/GenerateTimeoutErrorResolutionsCommand.kt
- helper-cli/src/main/kotlin/commands/ImportCopyrightGarbageCommand.kt
- helper-cli/src/main/kotlin/commands/ImportLicenseFindingCurationsCommand.kt
- helper-cli/src/main/kotlin/commands/ListCopyrightsCommand.kt
- helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
- helper-cli/src/main/kotlin/commands/MapCopyrightsCommand.kt
- helper-cli/src/main/kotlin/commands/MergeRepositoryConfigurationsCommand.kt
- helper-cli/src/main/kotlin/commands/RemoveConfigurationEntriesCommand.kt
> Miscellaneous helper-cli improvements

- docs/sw360-integration.md
> sw360-integration: Add the missing "storages" level to the config

- clients/fossid-webapp/src/main/kotlin/model/identification/identifiedFiles/IdentifiedFile.kt
- clients/fossid-webapp/src/main/kotlin/model/identification/markedAsIdentified/MarkedAsIdentifiedFile.kt
- clients/fossid-webapp/src/main/kotlin/model/summary/Summarizable.kt
- scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
- scanner/src/test/kotlin/storages/CompositeStorageTest.kt
- spdx-utils/build.gradle.kts
> Miscellaneous small improvements

- advisor/src/main/kotlin/advisors/NexusIq.kt
> Some small Nexus IQ improvements

- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/Npm.kt
- analyzer/src/main/kotlin/managers/Pip.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- utils/src/main/kotlin/OkHttpClientHelper.kt
- utils/src/main/kotlin/storage/HttpFileStorage.kt
> Download helpers

- evaluator/src/main/kotlin/PackageRule.kt
- model/src/main/kotlin/OrtResult.kt
- model/src/main/kotlin/licenses/LicenseView.kt
- model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
- reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
- reporter/src/main/kotlin/utils/ReportTableModelMapper.kt
- reporter/src/main/resources/templates/asciidoc/disclosure_document.ftl
- reporter/src/test/kotlin/utils/FreeMarkerTemplateProcessorTest.kt
Warning: This changes the output of the disclosure document as license choices are now applied, without actually changing the template.
> Add apply license choices for AsciiDocTemplateReporter

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
This PR contains two fixes. Please refer to individual commit messages for description.
> FossId: Fix Git repo URL match pattern

- analyzer/src/main/kotlin/managers/utils/NodeSupport.kt
> NodeSupport: Simplify the code to lookup workspaces a bit

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
> FossId: Check if project exists before trying to create it

- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
> CLI wording improvements

- clients/fossid-webapp/src/main/kotlin/Extensions.kt
- clients/fossid-webapp/src/main/kotlin/ReponseBody.kt
- clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
> FossID improvements

- clients/fossid-webapp/src/main/kotlin/EntityResponseBody.kt
- clients/fossid-webapp/src/main/kotlin/Extensions.kt
- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- clients/fossid-webapp/src/main/kotlin/ReponseBody.kt
> More FossId improvements

- cli/src/main/kotlin/commands/ScannerCommand.kt
- downloader/src/main/kotlin/Downloader.kt
- model/src/main/kotlin/config/ScannerConfiguration.kt
- scanner/src/funTest/kotlin/scanners/FileCounterScannerFunTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/test/kotlin/LocalScannerTest.kt
> Remove the feature to explicitly set the download directory when scanning

- cli/src/funTest/assets/semver4j-analyzer-result.yml
- downloader/src/main/kotlin/Downloader.kt
- model/src/main/kotlin/Provenance.kt
- model/src/test/assets/advisor-result-initial.yml
- model/src/test/assets/advisor-result-vulnerability-refs.yml
- model/src/test/assets/expected-scan-results.yml
- model/src/test/kotlin/ProvenanceTest.kt
- model/src/test/kotlin/ScanRecordTest.kt
- model/src/test/kotlin/ScanResultContainerTest.kt
- reporter-web-app/public/index.html
- reporter-web-app/src/models/Provenance.js
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
- reporter/src/funTest/assets/static-html-reporter-test-input.yml
- scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
- scanner/src/funTest/kotlin/scanners/FileCounterScannerFunTest.kt
- scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt
- test-utils/src/main/kotlin/Utils.kt
The property is not needed and make life a bit more difficult.
> Remove the provenances' download time

- docs/config-file-curations-yml.md
- docs/config-file-ort-yml.md
This introduces `is_modified` to the curation yml documentation. 
+ some minor grammar fixes.
> Documentation: add is_modified and small fixes

- downloader/src/main/kotlin/WorkingTree.kt
> Some small downloader improvements

- analyzer/src/main/kotlin/managers/Pipenv.kt
- cli/src/funTest/kotlin/ExamplesFunTest.kt
- model/src/test/kotlin/ProjectTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- test-utils/src/main/kotlin/Extensions.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/main/kotlin/Redirection.kt
> Introduce and start using utility functions for creating temporary files / directories

- model/src/test/kotlin/config/ScannerConfigurationTest.kt
> ScannerConfigurationTest: Minor fixes

- analyzer/src/main/kotlin/managers/Npm.kt
Support comments in package.json files, see the commit messages for details.
> Yarn comments

- build.gradle.kts
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
> Scanner fixes

- analyzer/src/funTest/assets/projects/synthetic/spdx/project/libs/zlib/README.md
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
> Various small SpdxDocumentFile improvements

- build.gradle.kts
- cli/build.gradle.kts
- helper-cli/build.gradle.kts
- reporter-web-app/build.gradle.kts
- spdx-utils/build.gradle.kts
- utils/build.gradle.kts
> Deterministic builds

- .azure-pipelines/LinuxAnalyzerTest.yml
- .azure-pipelines/LinuxTest.yml
- .azure-pipelines/WindowsAnalyzerTest.yml
- .azure-pipelines/WindowsTest.yml
- analyzer/src/funTest/kotlin/managers/SbtFunTest.kt
- cli/src/funTest/kotlin/OrtMainFunTest.kt
- scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt
> Disable running Sbt tests on Azure on Windows for now

- analyzer/src/funTest/assets/projects/synthetic/spdx-project-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- analyzer/src/test/kotlin/managers/SpdxDocumentFileTest.kt
- spdx-utils/src/main/kotlin/model/SpdxExternalReference.kt
> SpdxDocumentFile: Use a PURL from the input instead of generating one

- cli/src/main/kotlin/commands/ReporterCommand.kt
> ReporterCommand: Slightly improve printing the list of generated files

- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt
- spdx-utils/src/main/kotlin/model/SpdxExternalReference.kt
> SpdxExternalReference: Make the type safer to use

- model/src/main/kotlin/Package.kt
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
> Also deserialize PURLs from the model

- advisor/src/main/kotlin/Advisor.kt
- cli/src/main/kotlin/OrtMain.kt
- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- cli/src/main/kotlin/commands/UploadResultToPostgresCommand.kt
- cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
- scanner/src/funTest/kotlin/scanners/FileCounterScannerFunTest.kt
- scanner/src/main/kotlin/Scanner.kt
> Improve debug logging in CLI commands

- gradle/wrapper/gradle-wrapper.properties
See https://github.com/gradle/gradle/releases/tag/v7.0.1.
> Upgrade Gradle to version 7.0.1

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- analyzer/src/funTest/kotlin/managers/PipFunTest.kt
> PipFunTest: Update the expected test results

- reporter-web-app/public/index.html
- reporter-web-app/src/components/AboutModal.js
- reporter-web-app/src/models/MetaData.js
- reporter-web-app/src/models/WebAppOrtResult.js
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
- reporter/src/main/kotlin/model/EvaluatedModel.kt
- reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
- reporter/src/main/kotlin/model/MetaData.kt
- reporter/src/main/kotlin/utils/MetaDataCalculator.kt
> WebAppReporter: Add Analyzer start time to about dialog

- analyzer/src/main/kotlin/managers/GoMod.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/main/kotlin/Utils.kt
> Make use of a withoutSuffix() utility function

- model/src/test/kotlin/utils/PostgresFileArchiverStorageTest.kt
- scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt
- scanner/src/funTest/kotlin/storages/PostgresStorageFunTest.kt
- utils/src/funTest/kotlin/storage/HttpFileStorageFunTest.kt
> Embedded Postgres improvements

- gradle/wrapper/gradle-wrapper.properties
See https://github.com/gradle/gradle/releases/tag/v7.0.2.
> Upgrade Gradle to 7.0.2

- gradle.properties
See https://github.com/detekt/detekt/releases/tag/v1.17.0.
> Gradle: Upgrade the detekt plugin to version 1.17.0

- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
> Minor Git improvements

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
> PipFunTest: Update the expected "werkzeug" version

- analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
- analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml
- analyzer/src/funTest/assets/projects/external/multi-kotlin-project-expected-output-cli.yml
- analyzer/src/funTest/assets/projects/external/multi-kotlin-project-expected-output-core.yml
- analyzer/src/funTest/assets/projects/external/multi-kotlin-project-expected-output-root.yml
- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml
- analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml
- analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml
- analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-lockfile.yml
- analyzer/src/funTest/assets/projects/synthetic/cargo-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/pub-expected-output-project-with-flutter.yml
- analyzer/src/funTest/assets/projects/synthetic/yarn-expected-output.yml
- analyzer/src/funTest/kotlin/managers/PubFunTest.kt
- model/src/main/kotlin/Identifier.kt
- model/src/test/kotlin/IdentifierTest.kt
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
- reporter/src/funTest/assets/notice-template-reporter-expected-results
- reporter/src/funTest/assets/notice-template-reporter-expected-results-with-license-files
- reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
> Fix sorting of Identifiers

- analyzer/src/main/kotlin/managers/Npm.kt
- analyzer/src/main/kotlin/managers/utils/NodeSupport.kt
- analyzer/src/test/kotlin/managers/utils/NodeSupportTest.kt
> Small NPM shortcut improvements

- analyzer/src/funTest/kotlin/managers/BabelFunTest.kt
- analyzer/src/funTest/kotlin/managers/Extensions.kt
- analyzer/src/funTest/kotlin/managers/NpmFunTest.kt
- analyzer/src/funTest/kotlin/managers/NpmVersionUrlFunTest.kt
- analyzer/src/funTest/kotlin/managers/YarnFunTest.kt
- analyzer/src/main/kotlin/managers/Npm.kt
- analyzer/src/main/kotlin/managers/NpmDependencyHandler.kt
- analyzer/src/main/kotlin/managers/utils/DependencyGraphBuilder.kt
- analyzer/src/test/assets/test-package.json
- analyzer/src/test/kotlin/managers/GradleDependencyHandlerTest.kt
- analyzer/src/test/kotlin/managers/NpmDependencyHandlerTest.kt
This PR changes the NPM implementation to use the dependency graph format.
> NPM: Switch to dependency graph format

- cli/src/funTest/assets/analyzer-result-with-dependency-graph.yml
- model/src/test/assets/analyzer-result-with-dependency-graph.yml
Align the indentation with how Jackson would serialize those files.
> Fix formatting of some test assets

- model/src/main/resources/reference.conf
- model/src/test/kotlin/config/OrtConfigurationTest.kt
> Minor improvements for reference.conf

- helper-cli/src/main/kotlin/commands/ExtractRepositoryConfigurationCommand.kt
- helper-cli/src/main/kotlin/commands/GenerateTimeoutErrorResolutionsCommand.kt
- helper-cli/src/main/kotlin/commands/ImportScanResultsCommand.kt
- helper-cli/src/main/kotlin/commands/ListCopyrightsCommand.kt
- helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
- helper-cli/src/main/kotlin/commands/ListPackagesCommand.kt
- helper-cli/src/main/kotlin/commands/MapCopyrightsCommand.kt
- helper-cli/src/main/kotlin/commands/SetLabelsCommand.kt
- helper-cli/src/main/kotlin/commands/SubtractScanResultsCommand.kt
- helper-cli/src/main/kotlin/commands/packageconfig/ImportLicenseFindingCurationsCommand.kt
- helper-cli/src/main/kotlin/commands/packageconfig/RemoveEntriesCommand.kt
- helper-cli/src/main/kotlin/commands/repoconfig/ExportLicenseFindingCurationsCommand.kt
- helper-cli/src/main/kotlin/commands/repoconfig/ExportPathExcludesCommand.kt
- helper-cli/src/main/kotlin/commands/repoconfig/GenerateProjectExcludesCommand.kt
- helper-cli/src/main/kotlin/commands/repoconfig/GenerateRuleViolationResolutionsCommand.kt
- helper-cli/src/main/kotlin/commands/repoconfig/GenerateScopeExcludesCommand.kt
- helper-cli/src/main/kotlin/commands/repoconfig/ImportLicenseFindingCurationsCommand.kt
- helper-cli/src/main/kotlin/commands/repoconfig/RemoveEntriesCommand.kt
- helper-cli/src/main/kotlin/common/Utils.kt
> helper-cli: Make sure that `withResolvedScopes()` is called

- analyzer/src/main/kotlin/managers/Pip.kt
- analyzer/src/main/kotlin/managers/utils/DependencyGraphBuilder.kt
- model/src/main/kotlin/utils/DatabaseUtils.kt
- model/src/main/kotlin/utils/PostgresFileArchiverStorage.kt
- scanner/src/main/kotlin/storages/PostgresStorage.kt
> Some code inspection fixes

- gradle.properties
See https://github.com/detekt/detekt/releases/tag/v1.17.1.
> Gradle: Upgrade the detekt plugin to version 1.17.1

- spdx-utils/src/main/resources/declared-license-mapping.yml
Found in [1].
[1]: https://repo.maven.apache.org/maven2/org/graalvm/sdk/graal-sdk/20.2.0/graal-sdk-20.2.0.pom
> declared-license-mapping: Add 'Universal Permissive License v1.0'

- analyzer/src/main/kotlin/managers/utils/NodeSupport.kt
- analyzer/src/test/kotlin/managers/utils/NodeSupportTest.kt
- downloader/src/main/kotlin/VcsHost.kt
- utils/src/main/kotlin/Extensions.kt
> Improve NPM project URL parsing

- gradle.properties
See https://github.com/ben-manes/gradle-versions-plugin/releases/tag/v0.39.0.
> Gradle: Upgrade the versions plugin to version 0.39.0

- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm/node-modules/package-lock.json
- analyzer/src/funTest/assets/projects/synthetic/npm/node-modules/package.json
- analyzer/src/funTest/assets/projects/synthetic/npm/package-lock/package-lock.json
- analyzer/src/funTest/assets/projects/synthetic/npm/package-lock/package.json
- analyzer/src/funTest/assets/projects/synthetic/npm/shrinkwrap/npm-shrinkwrap.json
- analyzer/src/funTest/assets/projects/synthetic/npm/shrinkwrap/package.json
- analyzer/src/main/kotlin/managers/Npm.kt
- downloader/src/main/kotlin/VcsHost.kt
- downloader/src/test/kotlin/VcsHostTest.kt
> Support NPM dependencies that point to VCS hosts (like GitHub)

- reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
- spdx-utils/src/main/kotlin/SpdxExpression.kt
- spdx-utils/src/test/kotlin/SpdxExpressionTest.kt
> SpdxExpression: Revert sorting expressions when computing the DNF

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
> fossid-webapp: Display the version of FossID server

- analyzer/src/main/kotlin/managers/Npm.kt
> Npm: Explicitly declare the type of `graphBuilder`

- cli/src/main/kotlin/commands/DownloaderCommand.kt
This is a preparation for making wider use of this helper function.
> DownloaderCommand: Generalize archive() to work without a surrounding class

- .detekt.yml
- cli/build.gradle.kts
- cli/src/funTest/kotlin/ExamplesFunTest.kt
- cli/src/funTest/kotlin/OrtMainFunTest.kt
- cli/src/main/kotlin/OrtMain.kt
- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/ConfigCommand.kt
- cli/src/main/kotlin/commands/Constants.kt
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/Extensions.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/RequirementsCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- cli/src/main/kotlin/commands/UploadCurationsCommand.kt
- cli/src/main/kotlin/commands/UploadResultToPostgresCommand.kt
- cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
- cli/src/main/kotlin/utils/Constants.kt
- cli/src/main/kotlin/utils/Extensions.kt
- cli/src/main/kotlin/utils/PackageConfigurationOption.kt
- detekt-rules/src/main/kotlin/OrtPackageNaming.kt
> cli: Move Constants and Extensions to the utils package

- README.md
> README: Update the instructions to create a run configuration

- cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
- scanner/src/main/kotlin/storages/Sw360Storage.kt
> Reduce SW360 code duplication

- cli/src/funTest/kotlin/OrtMainFunTest.kt
- cli/src/main/kotlin/OrtMain.kt
- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- cli/src/main/kotlin/commands/UploadResultToPostgresCommand.kt
- cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
- cli/src/main/kotlin/utils/Extensions.kt
> Align severity handling for CLI exit codes

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
The logic of the scanner has been changed. Now we search for existing
scans of a given package before creating a new scan. If such an existing
scan is found, the scanner will check if repository data has been
downloaded and if this scan has completed. If some of these conditions is
not fulfilled, the scanner will wait until it has.
> fossid-webapp: Search and reuse existing scans

- analyzer/src/main/kotlin/Analyzer.kt
- analyzer/src/main/kotlin/curation/FilePackageCurationProvider.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/UploadCurationsCommand.kt
- model/src/main/kotlin/FileFormat.kt
> Handle user-facing empty configuration files leniently

- cli/src/main/kotlin/OrtMain.kt
- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- model/src/main/kotlin/config/OrtConfiguration.kt
- model/src/main/resources/reference.conf
This is yet another step towards resolving https://github.com/oss-review-toolkit/ort/issues/4096. The last missing bit is the required changes to the web app reporter.
> Configurable severity threshold

- clients/fossid-webapp/src/main/kotlin/Extensions.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
Please refer to individual commit messages for detail about the changes.
> fossid-webapp: Various improvements

- helper-cli/src/main/kotlin/commands/packageconfig/FindCommand.kt
- model/src/main/kotlin/FileFormat.kt
- model/src/main/kotlin/utils/SimplePackageConfigurationProvider.kt
> model: Introduce and use a generic findFilesWithKnownExtensions() function

- README.md
Also see issues #3671 and #3873.
> README: Make the current limitations in Python support more explicit

- analyzer/src/main/kotlin/Analyzer.kt
- reporter/src/funTest/kotlin/reporters/SpdxDocumentReporterFunTest.kt
- reporter/src/funTest/kotlin/reporters/StaticHtmlReporterFunTest.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
- reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt
- test-utils/src/main/kotlin/Utils.kt
> Environment class improvements

- reporter-web-app/package.json
- reporter-web-app/yarn.lock
Update dependencies to latest available versions to benefit from
upstream improvements.
> reporter-web-app: Update versions of dependencies

- downloader/src/main/kotlin/vcs/Git.kt
As parsing human-readable output is generally fragile, instead check
whether the revision is a remote tag in order to conditionally create a
matching local tag.
Also, as right now (before the scan-by-repository topic is implemented)
there could be race conditions with multiple paths from a single Git
repository being downloaded in parallel, force to create the local tag
in case it already exists.
> Git: Make the logic to create a missing local tag more robust

- helper-cli/src/main/kotlin/commands/packagecuration/PackageCurationsCommand.kt
This is a fix-up for 3d4d80334778e7bd969f10478e9c31382fe2d507.
> PackageCurationsCommand: Add help text

- analyzer/src/main/kotlin/curation/FilePackageCurationProvider.kt
- analyzer/src/test/kotlin/curation/FilePackageCurationProviderTest.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- model/src/main/kotlin/OrtResult.kt
> Evaluator: Add option to provide multiple curation files

- reporter-web-app/package.json
- reporter-web-app/yarn.lock
Forgot to remove these in a recent refactor of the WebApp.
> reporter-web-app: Remove no longer used dependencies

- downloader/src/main/kotlin/vcs/GitWorkingTree.kt
> Git single file mode

- analyzer/src/main/kotlin/managers/Npm.kt
> Npm: Omit blank declared licenses 

- .reuse/dep5
- README.md
- model/src/test/kotlin/licenses/TestUtils.kt
> Additions to Bosch's Copyright statements

- cli/src/main/kotlin/OrtMain.kt
While at it, generalize the wording to match for both single and
multiple issues.
> OrtMain: Also print the actual count of severe issues

- helper-cli/src/main/kotlin/commands/packagecuration/SplitCommand.kt
See: https://github.com/oss-review-toolkit/ort/pull/4201#discussion_r656071644
> SplitCommand: Sort curations within the files

- gradle.properties
> Upgrade to Kotlin 1.5.20 final

- analyzer/src/main/kotlin/managers/CocoaPods.kt
> CocoaPods: Remove a superfluous let call

- gradle/wrapper/gradle-wrapper.properties
See https://github.com/gradle/gradle/releases/tag/v7.1.1.
> Upgrade to Gradle version 7.1.1

- advisor/src/main/kotlin/advisors/NexusIq.kt
- clients/nexus-iq/src/main/kotlin/NexusIqService.kt
- clients/nexus-iq/src/test/kotlin/NexusIqServiceTest.kt
> NexusIq advisor improvements

- downloader/src/main/kotlin/VersionControlSystem.kt
- scanner/src/funTest/kotlin/experimental/DefaultPackageProvenanceResolverFunTest.kt
- scanner/src/main/kotlin/experimental/PackageProvenanceResolver.kt
The first component for a new experimental scanner, see the commit messages for details.
> Package provenance resolver

- gradle.properties
See https://github.com/Kotlin/dokka/releases/tag/v1.5.0.
> Gradle: Upgrade the dokka plugin to version 1.5.0

- gradle.properties
See https://github.com/JetBrains/kotlin/releases/tag/v1.5.21.
> Gradle: Upgrade to Kotlin 1.5.21

- spdx-utils/src/main/resources/simple-license-mapping.yml
Found in [1].
[1]: https://github.com/skeeto/rng-js/blob/master/package.json#L23
> simple-license-mapping: Add 'Unlicence'

- docs/config-file-curations-yml.md
- examples/curations.yml
> Improve docs examples

- clients/fossid-webapp/src/main/kotlin/Extensions.kt
- clients/fossid-webapp/src/main/kotlin/model/Scan.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
See individual commit messages for detail about the changes.
> fossid-webapp: Improvements to target_path handling

- build.gradle.kts
> Gradle: Only inherit non-null test system properties

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
Adapt the expected analyzer result.
> PythonFunTest: Fix failing test case

- downloader/src/funTest/kotlin/vcs/CvsWorkingTreeFunTest.kt
- downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt
- downloader/src/funTest/kotlin/vcs/MercurialWorkingTreeFunTest.kt
- downloader/src/funTest/kotlin/vcs/SubversionWorkingTreeFunTest.kt
- model/src/test/kotlin/utils/PostgresFileArchiverStorageTest.kt
> Slightly rewrite some test classes for less indentation

- analyzer/src/main/resources/META-INF/plexus/components.xml
> Support more Maven packagings

- helper-cli/src/main/kotlin/commands/repoconfig/RemoveEntriesCommand.kt
Remove all license finding curations which do not match any license
finding.
> RemoveEntriesCommand: Also remove non-matching license finding curations

- cli/src/main/kotlin/commands/AnalyzerCommand.kt
Print out the actually used repository configuration file already in the
beginning to get rid of the conditional logging further below.
> AnalyzerCommand: Improve informing about the repository configuration file

- analyzer/src/main/kotlin/managers/Maven.kt
> Maven: Fix a typo in an issue message

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
> PipFunTest: Update the expected test result

- Dockerfile
> Apply some hadolint recommendation to the Dockerfile

- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
> Spdx document file handling improvements

- .github/CODEOWNERS
> Add @nnobelis as a code owner for the fossid-webapp client

- model/src/main/resources/reference.conf
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/main/kotlin/scanners/fossid/FossIdConfig.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdConfigTest.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
Please refer to the single commits for further details.
> FossID: Limit the number of delta scans

- analyzer/src/main/kotlin/Analyzer.kt
- analyzer/src/main/kotlin/managers/Sbt.kt
> Trivially improve some log messages

- .gitattributes
- analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- analyzer/src/test/kotlin/managers/SpdxDocumentFileTest.kt
> Miscellaneous SPDX document file handling improvements

- cli/build.gradle.kts
- helper-cli/build.gradle.kts
> Add a plugin classpath to start scripts

- build.gradle.kts
- gradle.properties
> Upgrade to Kotlin 1.5.30

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
> Miscellaneous improvements to FossID logging and issue handling

- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- downloader/src/test/kotlin/vcs/GitTest.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
> Improvements to requesting authentication passwords

- analyzer/src/main/kotlin/managers/Conan.kt
Conan does not support parsing .netrc for credentials to authenticate
against remotes, see [1]. So forward any credentials for remote hosts
provided by the Java authenticator, which in this case is an instance of
OrtAuthenticator that supports getting credentails from a .netrc file.
[1] https://github.com/conan-io/conan/issues/3046#issuecomment-904516572
> Conan: Forward Java authenticator credentials

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- analyzer/src/main/kotlin/managers/Cargo.kt
- model/src/main/kotlin/Identifier.kt
> Cargo: Add a code comment about Rust / Cargo package (non-)namespaces

- gradle.properties
See https://github.com/detekt/detekt/releases/tag/v1.18.1.
> Gradle: Upgrade the detekt plugin to version 1.18.1

- Dockerfile
> Do not hard-code the user's home to /root

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
> PipFunTest: Update expected test output

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
> More fixes for filtering empty paths in FossID scans

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
As FossID interprets queued scans as error, check for this and wait for
the completion without checking for further errors.
> FossId: Explicitly check if a scan was added to scan queue

- model/src/main/kotlin/OrtResult.kt
- reporter/src/main/kotlin/utils/ReportTableModel.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/test/kotlin/ExtensionsTest.kt
> Introduce and use a zipWithCollections() utility function

- cli/src/main/kotlin/commands/AnalyzerCommand.kt
> AnalyzerCommand: Output details about found project types

- reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
- reporter/src/main/resources/templates/freemarker_implicit.ftl
For details see:
https://www.jetbrains.com/help/idea/template-data-languages.html#fcfc279c
> reporter: Support resolving class names from FreeMarker templates

- reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
> Improve FreemarkerTemplateProcessor docs

- model/src/main/kotlin/OrtIssue.kt
> OrtIssue: Do not assume the severity's default value in createAndLogIssue()

- model/src/main/kotlin/OrtResult.kt
- model/src/test/kotlin/OrtResultTest.kt
Provide the possibility to remove resolved violations and violations
below a specified threshold.
This is not used in the ORT code, but is intended to be used in the
`rules.kts` and `notifications.kts` scripts.
Signed-off-by: Marcel Bochtler <marcel.bochtler@bosch.io>
> OrtResult: Enhance getRuleViolations to omit resolved violations

- build.gradle.kts
> Gradle: Add docs to the "allDependencies" task

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
> fossid-webapp: Allow first delta scan to be asynchronous

- gradle.properties
See https://github.com/Kotlin/dokka/releases/tag/v1.5.30.
> Gradle: Upgrade the dokka plugin to version 1.5.30

- utils/src/main/kotlin/Utils.kt
> Minor improvements to the filterVersionNames() function

- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/fossid/FossIdNamingProvider.kt
> Miscellaneous small scanner improvements

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
> FossId: Set file name of pending identification as message

- analyzer/src/funTest/kotlin/GitRepoFunTest.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Maven.kt
- cli/src/funTest/kotlin/OrtMainFunTest.kt
- model/src/main/kotlin/utils/DependencyGraphBuilder.kt
- model/src/test/kotlin/utils/DependencyGraphBuilderTest.kt
- scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
- test-utils/src/main/kotlin/Utils.kt
Refer to the individual commit messages for more details.
> Some dependency graph improvements and clean-up

- README.md
- advisor/src/main/kotlin/advisors/NexusIq.kt
- advisor/src/main/kotlin/advisors/OssIndex.kt
- advisor/src/main/resources/META-INF/services/org.ossreviewtoolkit.advisor.VulnerabilityProviderFactory
- clients/nexus-iq/src/main/kotlin/NexusIqService.kt
- clients/oss-index/build.gradle.kts
- clients/oss-index/src/main/kotlin/OssIndexService.kt
- detekt-rules/src/main/kotlin/OrtPackageNaming.kt
- model/src/main/kotlin/VulnerabilityReference.kt
- settings.gradle.kts
> Support OSS Index as a vulnerability provider

- analyzer/src/funTest/kotlin/managers/Extensions.kt
- helper-cli/src/main/kotlin/common/Utils.kt
- model/src/main/kotlin/DependencyNavigator.kt
- model/src/main/kotlin/OrtResult.kt
- reporter/src/main/kotlin/utils/StatisticsCalculator.kt
> Replace calls to getProjectAndPackageIds() with collectProjectsAndPackages()

- advisor/src/main/kotlin/advisors/OssIndex.kt
- advisor/src/main/kotlin/advisors/VulnerableCode.kt
- advisor/src/test/assets/__files/oss-index/response_components.json
- advisor/src/test/kotlin/advisors/OssIndexTest.kt
- advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
> Add a test for the OSS Index vulnerability provider

- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- helper-cli/src/main/kotlin/common/Utils.kt
- model/src/main/kotlin/config/OrtConfiguration.kt
- model/src/main/kotlin/licenses/LicenseInfoResolver.kt
- model/src/main/kotlin/utils/OrtResultExtensions.kt
- model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
- model/src/test/kotlin/licenses/LicenseViewTest.kt
- reporter/src/main/kotlin/ReporterInput.kt
- reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
> Make the mapping of authors to copyrights configurable

- downloader/src/main/kotlin/Downloader.kt
> Downloader: Fix the docs for `handle{Vcs,SourceArtifact}Download()`

- cli/src/main/kotlin/commands/DownloaderCommand.kt
> Improve the download failure summary wording

- analyzer/src/main/kotlin/managers/Bower.kt
- analyzer/src/main/kotlin/managers/Composer.kt
- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/Npm.kt
- analyzer/src/main/kotlin/managers/Pip.kt
- analyzer/src/main/kotlin/managers/Pub.kt
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- clients/fossid-webapp/src/main/kotlin/Extensions.kt
- downloader/src/main/kotlin/VcsHost.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- helper-cli/src/main/kotlin/commands/ListLicenseCategoriesCommand.kt
- helper-cli/src/main/kotlin/common/Utils.kt
- model/src/main/kotlin/VcsInfo.kt
- model/src/test/kotlin/utils/FileArchiverTest.kt
- scanner/src/main/kotlin/ScannerCriteria.kt
- utils/src/main/kotlin/ArchiveUtils.kt
- utils/src/main/kotlin/Extensions.kt
- utils/src/test/kotlin/ArchiveUtilsTest.kt
- utils/src/test/kotlin/ExtensionsTest.kt
> Miscellaneous minor improvements

- .azure-pipelines.yml
- .azure-pipelines/LinuxAnalyzerTest.yml
- .azure-pipelines/LinuxTest.yml
- Dockerfile
See https://github.com/conan-io/conan/issues/9695.
> Upgrade Conan to fix a certificate issue

- README.md
> README: Also document the PIP version projects need to be compatible with

- analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
- analyzer/src/main/kotlin/managers/Pip.kt
> Better Pip errors

- gradle.properties
See [1].
[1]: https://github.com/Kotlin/dokka/releases/tag/v1.5.31
> Dokka: Upgrade the Dokka Plugin to version 1.5.31

- cli/src/main/kotlin/commands/EvaluatorCommand.kt
Improve the rule violation summary printed by the evaluator command. See the commit messages for details.
> EvaluatorCommand: Summary improvements

- utils/src/main/kotlin/Utils.kt
- utils/src/test/kotlin/RedirectionTest.kt
> Java 17 support

- analyzer/src/funTest/kotlin/GitRepoFunTest.kt
- analyzer/src/funTest/kotlin/managers/SbtFunTest.kt
- analyzer/src/main/kotlin/Analyzer.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- helper-cli/src/main/kotlin/common/Utils.kt
> Separate finding files from analysis

- scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt
- scanner/src/main/kotlin/LocalScanner.kt
- scanner/src/main/kotlin/storages/FileBasedStorage.kt
- scanner/src/main/kotlin/storages/PostgresStorage.kt
> scanner: Prevent storing the same scan result twice

- reporter/src/main/kotlin/reporters/spdx/SpdxDocumentModelMapper.kt
- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
> Some trivial scanner-related improvements

- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- cli/src/main/kotlin/utils/SeverityStats.kt
> Improvements to printing severity statistics

- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
> Detect modified Maven artifacts

- .lift.toml
Start off with a few things that should be configured for ORT. Probably
more tuning will be needed in the future.
> Create a configuration file for Sonatype Lift

- README.md
> README: Add a note about the Sonatype OSS Index Terms of Service

- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- model/src/main/kotlin/config/OrtConfiguration.kt
- model/src/main/resources/reference.conf
- reporter/src/main/kotlin/reporters/freemarker/FreemarkerTemplateProcessor.kt
This is now analogous to the severity of issues. Fixes #4642.
> model: Add separate severity configuration for rule violations

- utils/common/src/main/kotlin/Extensions.kt
- utils/common/src/test/kotlin/ExtensionsTest.kt
> Make `zipWithCollections()` work for Sets 

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
Make PipFunTest succeed again.
> PipFunTest: Update expected output for example-python-flask

- gradle/wrapper/gradle-wrapper.properties
See [1].
[1]: https://docs.gradle.org/7.3/release-notes.html
> Upgrade Gradle to version 7.3

- README.md
- mlc_config.json
> Update the Pipenv homepage link

- cli/src/main/kotlin/commands/ScannerCommand.kt
- scanner/src/main/kotlin/Scanner.kt
> Add the possibility to limit scanning to project or packages only

- analyzer/src/funTest/assets/projects/synthetic/gradle-android/app/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle-android/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle-android/lib/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle-bom/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle-library/app/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle-library/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle-library/lib/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle-unsupported-version/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle/app/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle/lib-without-repo/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle/lib/build.gradle
- analyzer/src/funTest/kotlin/managers/GradleFunTest.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
> Miscellaneous Gradle analyzer improvements

- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/GoMod.kt
- analyzer/src/main/kotlin/managers/Pip.kt
- analyzer/src/main/kotlin/managers/Pub.kt
- analyzer/src/main/kotlin/managers/Sbt.kt
- analyzer/src/main/kotlin/managers/utils/NodeSupport.kt
- analyzer/src/test/kotlin/managers/CarthageTest.kt
- detekt-rules/src/main/kotlin/OrtImportOrder.kt
- detekt-rules/src/main/kotlin/OrtPackageNaming.kt
- downloader/src/main/kotlin/VcsHost.kt
- evaluator/src/main/resources/rules/no_gpl_declared.kts
- examples/rules.kts
- helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
- model/src/test/kotlin/AbstractDependencyNavigatorTest.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
- reporter/src/main/kotlin/reporters/freemarker/NoticeTemplateReporter.kt
- reporter/src/main/kotlin/reporters/freemarker/asciidoc/AsciiDocTemplateReporter.kt
- scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
- utils/core/src/main/kotlin/OrtProxySelector.kt
- utils/core/src/main/kotlin/Utils.kt
- utils/spdx/src/main/kotlin/SpdxExpression.kt
> Consistently prefer Kotlin's `in` over Java's `contains`

- README.md
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Yarn.kt
> Miscellanous trivial improvements

- analyzer/src/main/kotlin/managers/Gradle.kt
> Improvements to Gradle's system properties handling

- README.md
> README: Improve the ctrlX AUTOMATION reporter entry

- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm/node-modules/package-lock.json
- analyzer/src/funTest/assets/projects/synthetic/npm/node-modules/package.json
- analyzer/src/funTest/assets/projects/synthetic/npm/package-lock/package-lock.json
- analyzer/src/funTest/assets/projects/synthetic/npm/package-lock/package.json
- analyzer/src/funTest/assets/projects/synthetic/npm/shrinkwrap/npm-shrinkwrap.json
- analyzer/src/funTest/assets/projects/synthetic/npm/shrinkwrap/package.json
- analyzer/src/main/kotlin/managers/Npm.kt
> NpmFunTest fixes

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
> FossId: Change the `wait()` function to take `Duration`s for readability

- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
- scanner/src/main/kotlin/experimental/ProvenanceBasedFileStorage.kt
- utils/core/src/main/kotlin/storage/XZCompressedLocalFileStorage.kt
> Some trivial improvements

- scanner/src/main/kotlin/scanners/Askalono.kt
See [1].
[1]: https://github.com/jpeddicord/askalono/releases/tag/0.4.4
> Askalono: Upgrade to version 0.4.4

- downloader/src/main/kotlin/vcs/Git.kt
- utils/common/src/main/kotlin/Extensions.kt
- utils/core/src/main/kotlin/OrtAuthenticator.kt
> Add more JGit / netrc related debugging

- model/src/main/kotlin/OrtResult.kt
- model/src/test/kotlin/OrtResultTest.kt
- reporter/src/main/kotlin/reporters/evaluatedmodel/StatisticsCalculator.kt
This helper is mainly required for rules and notifications.
> OrtResult: Add helper function to get all open issues 

- cli/src/main/kotlin/commands/DownloaderCommand.kt
> DownloaderCommand: Print download provenance

- clients/fossid-webapp/src/main/kotlin/model/summary/Summarizable.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/main/kotlin/scanners/fossid/FossIdConfig.kt
- scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
> FossID spelling fixes

- gradle.properties
- settings.gradle.kts
> Upgrade Dokka

- downloader/src/funTest/kotlin/vcs/SubversionWorkingTreeFunTest.kt
- downloader/src/main/kotlin/vcs/Git.kt
> Git: Align on using the simple class name for credential items

- build.gradle.kts
- gradle.properties
- utils/test/src/main/kotlin/ProjectConfig.kt
> Re-introduce the idea-ext plugin to configure IDEA runs

- downloader/src/main/kotlin/VcsHost.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/test/kotlin/VcsHostTest.kt
> VersionControlSystem: Try to determine the VCS type statically first 

- scanner/src/funTest/kotlin/scanners/AbstractScannerFunTest.kt
- scanner/src/funTest/kotlin/scanners/scancode/ScanCodeScannerFunTest.kt
- utils/spdx/src/main/kotlin/Utils.kt
- utils/spdx/src/test/kotlin/UtilsTest.kt
> Move ScanCode license tests

- .github/workflows/build-and-test.yml
- .github/workflows/static-analysis.yml
- gradle/wrapper/gradle-wrapper.properties
> Introduce a GitHub workflow to build and test ORT

- analyzer/src/main/kotlin/managers/Pub.kt
- gradle.properties
- scanner/build.gradle.kts
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- utils/core/src/main/kotlin/OkHttpClientHelper.kt
> Bootstrapping improvements

- helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
Allow to narrow down the matching of scan result entries in the postgres
storage to a given ScanCode version.
This enables the use case to re-scan a given set of package IDs which
have been scanned before with the specified ScanCode version.
> CreateAnalyzerResultCommand: Add the parameter `--scancode-version`

- advisor/src/test/kotlin/advisors/OssIndexTest.kt
- advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
- analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderMockTest.kt
- clients/fossid-webapp/src/test/kotlin/FossId2021dot2Test.kt
- clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
- clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
- clients/github-graphql/src/test/kotlin/GitHubServiceTest.kt
- notifier/src/test/kotlin/modules/JiraNotifierTest.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdConfigTest.kt
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
> Clean up Wiremock tests

- Dockerfile
See [1].
[1]: https://github.com/nexB/scancode-toolkit/issues/2762
> Dockerfile: Work around a ScanCode configuration issue

- model/src/main/kotlin/utils/Extensions.kt
> Purl type fixes

- model/src/main/kotlin/HashAlgorithm.kt
- utils/common/src/main/kotlin/Utils.kt
- utils/spdx/src/main/kotlin/Utils.kt
> Reduce code duplication for hashing functions

- gradle/wrapper/gradle-wrapper.properties
See [1].
[1]: https://github.com/gradle/gradle/releases/tag/v7.3.1
> Upgrade Gradle to version 7.3.1

- cli/src/main/kotlin/commands/ScannerCommand.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
- scanner/src/main/kotlin/experimental/NestedProvenanceScanResult.kt
- scanner/src/main/kotlin/experimental/ScanContext.kt
- scanner/src/main/kotlin/experimental/ScannerWrapper.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt
Some improvements for the experimental scanner, please see the commit messages for details.
> Experimental scanner improvements

- docs/config-file-curations-yml.md
- integrations/schemas/repository-configuration-schema.json
Refer to the individual commits for further details.
> Documentation updates for curations related to new cpe property

- analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
- utils/common/src/main/kotlin/Os.kt
- utils/core/src/main/kotlin/EnvVarAuthenticator.kt
- utils/core/src/main/kotlin/NetRcAuthenticator.kt
- utils/core/src/main/kotlin/OkHttpClientHelper.kt
- utils/core/src/main/kotlin/OrtAuthenticator.kt
- utils/core/src/test/kotlin/EnvVarAuthenticatorTest.kt
- utils/core/src/test/kotlin/NetRcAuthenticatorTest.kt
- utils/core/src/test/kotlin/test/other/OrtLogTestExtension.kt
> Authenticator refactoring

- utils/core/src/main/kotlin/OkHttpClientHelper.kt
> OkHttpClientHelper refactoring

- helper-cli/src/main/kotlin/commands/repoconfig/ImportPathExcludesCommand.kt
- helper-cli/src/main/kotlin/common/Utils.kt
See individual commit messages.
> helper-cli: Avoid importing too many path excludes

- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
> SpdxDocumentFile improvements

- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
> ScanCode: Fix creating the directory when bootstrapping

- .mailmap
> Update .mailmap to consolidate contributors

- reporter/src/main/kotlin/reporters/OpossumReporter.kt
> Trivial Opossum improvements

- cli/src/main/kotlin/commands/UploadCurationsCommand.kt
- utils/common/build.gradle.kts
- utils/common/src/main/kotlin/Extensions.kt
> Reduce reflection

- utils/spdx/src/main/kotlin/SpdxExpression.kt
- utils/spdx/src/test/kotlin/SpdxExpressionTest.kt
> SpdxExpression: Add a new ALLOW_LICENSEREF_EXCEPTIONS strictness level

- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
Rename the function to `hasDefaultScopeLinkage()` as a result of moving
out the `DEPENDS_ON` check to the caller, which makes the code more
readable due to the resulting symmetry with the `dependencyOfRelation`
case at the call site.
> SpdxDocumentFile: Slightly refactor `hasDependsOnRelationship()`

- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
Create file archives in a way compatible with the way they are created
in the `LocalScanner`. This allows to keep using the existing file
archives without changing the logic used to read those file archives in
the reporter.
> ExperimentalScanner: Support the creation of file archives

- utils/spdx/src/main/kotlin/model/SpdxPackageVerificationCode.kt
> SpdxPackageVerificationCode: Improve an exception message

- analyzer/src/main/kotlin/managers/Gradle.kt
The Gradle cache might contain the "same" artifact multiple times, that
is, different files for the same Maven coordinates, deduplicated by the
cache path which contains the file hash. This can happen if an artifact
was silently updated on a Maven server, or if different Maven servers
serve different files for the same artifact coordinates and servers were
switched in a Gradle project. Instead of choosing the first artifact the
directory walk comes across, deterministically use the file with the
most recent modification date.
> Gradle: Use the most recent file in case of multiple cache matches

- gradle/wrapper/gradle-wrapper.properties
See [1].
[1]: https://github.com/gradle/gradle/releases/tag/v7.3.2
> Upgrade Gradle to version 7.3.2

- scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
- scanner/src/main/kotlin/PathScanner.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- scanner/src/test/kotlin/PathScannerTest.kt
> PathScanner simplifications

- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
- scanner/src/main/kotlin/experimental/ScannerWrapper.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt
> ScannerWrapper renaming

- scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
- scanner/src/main/kotlin/CommandLineScanner.kt
- scanner/src/main/kotlin/PathScanner.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- scanner/src/test/kotlin/PathScannerTest.kt
> Introduce a `CommandLineScanner`

- analyzer/src/funTest/assets/projects/synthetic/spdx/libs/my-lib/package.spdx.yml
- analyzer/src/funTest/assets/projects/synthetic/spdx/project-xyz-with-transitive-dependencies.spdx.yml
- analyzer/src/funTest/kotlin/managers/SpdxDocumentFileFunTest.kt
- analyzer/src/main/kotlin/managers/SpdxDocumentCache.kt
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- analyzer/src/main/kotlin/managers/SpdxResolvedDocument.kt
- analyzer/src/test/kotlin/managers/SpdxDocumentCacheTest.kt
- analyzer/src/test/kotlin/managers/SpdxDocumentFileTest.kt
- analyzer/src/test/kotlin/managers/SpdxResolvedDocumentTest.kt
> SpdxDocumentFile: Support transitive dependencies

- integrations/schemas/repository-configuration-schema.json
Change the type to array, as multiple path excludes are allowed.
Resolves: #4874
> repository-configuration-schema: Fix schema for path_excludes

- README.md
- gradle.properties
- scanner/build.gradle.kts
- scanner/src/main/kotlin/scanners/scanoss/ScanOss.kt
- scanner/src/main/resources/META-INF/services/org.ossreviewtoolkit.scanner.ScannerFactory
Resolves #2908.
Co-authored-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>
Signed-off-by: Juan M Salamanca <juan.m.salamanca@scanoss.com>
> scanner: Add basic SCANOSS integration

- reporter/src/funTest/kotlin/reporters/CycloneDxReporterFunTest.kt
- reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
> Write out CycloneDX 1.3 by default

- gradle/wrapper/gradle-wrapper.properties
See [1].
[1]: https://github.com/gradle/gradle/releases/tag/v7.3.3
> Upgrade Gradle to version 7.3.3

- model/src/main/kotlin/HashAlgorithm.kt
- utils/common/src/main/kotlin/Utils.kt
> Hash cleanups

- build.gradle.kts
> Internal funTest visibility

- README.md
> README: Just briefly document the Notifier until we have a logo

- analyzer/src/main/kotlin/AnalyzerResultBuilder.kt
> AnalyzerResultBuilder: Log the duration for getting package curations

- clients/nexus-iq/build.gradle.kts
- clients/nexus-iq/src/main/kotlin/NexusIqService.kt
Add required code that was accidentally not committed. This is a fixup for
e8a896b.
> nexus-iq: Fixup the port to kotlinx.serialization

- advisor/src/main/kotlin/advisors/NexusIq.kt
- advisor/src/main/kotlin/advisors/OssIndex.kt
- advisor/src/main/kotlin/advisors/VulnerableCode.kt
- analyzer/src/main/kotlin/AnalyzerResultBuilder.kt
- analyzer/src/main/kotlin/PackageCurationProvider.kt
- analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
- analyzer/src/main/kotlin/curation/FallbackPackageCurationProvider.kt
- analyzer/src/main/kotlin/curation/FilePackageCurationProvider.kt
- analyzer/src/main/kotlin/curation/SimplePackageCurationProvider.kt
- analyzer/src/main/kotlin/curation/Sw360PackageCurationProvider.kt
- analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderMockTest.kt
- analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt
- analyzer/src/test/kotlin/curation/FilePackageCurationProviderTest.kt
- clients/clearly-defined/src/main/kotlin/Enums.kt
- helper-cli/src/main/kotlin/common/Utils.kt
- model/src/main/kotlin/utils/Extensions.kt
~*Edit:* I'll rebase this once more when https://github.com/oss-review-toolkit/ort/pull/4911 is merged.~ Done.
> Implement bulk requests for curation providers

- model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
- model/src/test/kotlin/licenses/LicenseViewTest.kt
- model/src/test/kotlin/licenses/TestUtils.kt
- scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt
- utils/spdx/src/test/kotlin/SpdxExpressionTest.kt
- utils/test/src/main/kotlin/Utils.kt
> Simplify custom Kotest matchers

- clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
> Improve `ClearlyDefinedService` docs

- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
- reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModel.kt
- reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModelMapper.kt
The WebApp UI will be enhanced to adhere to these thresholds in an
upcoming change, see also #4453.
> EvaluatedModel: Add the severity thresholds for issues and violations

- README.md
- scripts/docker_build.sh
> Docker BuildKit related improvements

- model/src/main/kotlin/PackageCuration.kt
- model/src/main/kotlin/PackageCurationData.kt
> Minor `PackageCuration(Data)` improvements

- Dockerfile
> Use JDK 17 LTS in the `Dockerfile`

- notifier/src/main/kotlin/modules/JiraNotifier.kt
> JiraNotifier improvements

- cli/src/main/kotlin/commands/UploadCurationsCommand.kt
- model/src/main/kotlin/PackageCurationData.kt
- model/src/main/kotlin/VcsInfoCurationData.kt
- model/src/test/kotlin/PackageCurationDataTest.kt
> Merge curations before uploading to ClearlyDefined

- model/src/main/kotlin/AdvisorRecord.kt
- model/src/main/kotlin/OrtResult.kt
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
- reporter/src/main/kotlin/reporters/evaluatedmodel/Statistics.kt
- reporter/src/main/kotlin/reporters/evaluatedmodel/StatisticsCalculator.kt
> Statistics: Add the number of open vulnerabilities

- scanner/src/main/kotlin/PathScanner.kt
> PathScanner: Slightly improve log messages in `scanPackages()`

- analyzer/src/main/kotlin/managers/GoDep.kt
> GoDep: Avoid unnecessary path conversions

- Dockerfile
> Dockerfile: Use a JDK even for running ORT 

- cli/src/main/kotlin/commands/AnalyzerCommand.kt
> AnalyzerCommand: Fix calculating the total project count

- analyzer/src/main/kotlin/managers/GoDep.kt
Please have a look at the commit messages for more details.
> GoDep: Fix retrieval of VCS metadata

- evaluator/src/main/kotlin/Evaluator.kt
- evaluator/src/main/kotlin/RulesScriptTemplate.kt
- notifier/src/main/kotlin/NotificationsScriptTemplate.kt
- notifier/src/main/kotlin/Notifier.kt
- utils/scripting/src/main/kotlin/OrtScriptCompilationConfiguration.kt
> Fix custom scripts highlighting

- cli/src/funTest/kotlin/ExamplesFunTest.kt
- evaluator/src/main/kotlin/Evaluator.kt
- evaluator/src/test/kotlin/EvaluatorTest.kt
- utils/scripting/src/main/kotlin/OrtScriptCompilationConfiguration.kt
- utils/scripting/src/main/kotlin/ScriptRunner.kt
> Miscellaneous evaluator improvements

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
FossID offers the possibility to exclude files from the scan. To do so,
the user has to write 'ignore rules' in FossID UI.
This commit adapts the integration to takes these rules in account: when
a new delta scan is created, all 'ignore rules' from the previous latest
scan are carried to the new scan.
> fossid-webapp: Carry existing ignore rules to the new delta scan

- .gitignore
- .reuse/dep5
- batect
- batect.cmd
- batect.yml
> Introduce Batect as an easy way to run ORT functional test inside a Docker container

- analyzer/src/main/kotlin/curation/FilePackageCurationProvider.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- model/src/main/kotlin/licenses/LicenseClassifications.kt
- utils/common/src/main/kotlin/Extensions.kt
- utils/spdx/src/main/kotlin/model/SpdxDocument.kt
> Miscellaneous configuration-related improvements

- analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
- helper-cli/src/main/kotlin/commands/SetDependencyRepresentationCommand.kt
- utils/common/src/main/kotlin/Os.kt
- utils/core/src/main/kotlin/OkHttpClientHelper.kt
- utils/spdx/src/main/kotlin/Utils.kt
This is a new function since Kotlin 1.5, see [1].
[1]: https://kotlinlang.org/docs/whatsnew15.html#new-collections-function-firstnotnullof
> Simplify code with `firstNotNullOfOrNull`

- scanner/src/main/kotlin/PathScanner.kt
- scanner/src/main/kotlin/Scanner.kt
> Filter by ignore patterns for all scanners

- downloader/src/main/kotlin/vcs/GitRepo.kt
Just omit the manifest revision and path options in case they are blank
to rely on the repo tool's built-in defaults instead of repeating them
here. This allows the repo tool to figure out the remote default branch
itself when the provided revision is empty, resolving download errors
for repositories that use "main" as the default branch name.
> GitRepo: Do not hard-code the default manifest revision and path

- analyzer/src/main/kotlin/managers/utils/SpdxResolvedDocument.kt
- utils/spdx/src/main/kotlin/model/SpdxExternalDocumentReference.kt
> Small SPDX document resolution improvements

- reporter/src/main/kotlin/reporters/ExcelReporter.kt
> ExcelReporter: Initialize all colors lazily at once

- analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output-with-nuspec.yml
- analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/dotnet/subProjectTest/test.csproj
- analyzer/src/funTest/assets/projects/synthetic/dotnet/subProjectTestWithNuspec/test.csproj
- analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/nuget/packages.config
- analyzer/src/funTest/kotlin/managers/DotNetFunTest.kt
- analyzer/src/funTest/kotlin/managers/NuGetFunTest.kt
- analyzer/src/main/kotlin/managers/DotNet.kt
- analyzer/src/main/kotlin/managers/NuGet.kt
- analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
Parse more information from DotNet and NuGet definition files, as a preparation for improving the NuGet dependency resolution. See the commit messages for details.
> NuGet: Parse more information

- build.gradle.kts
- detekt-rules/src/main/kotlin/OrtPackageNaming.kt
> Detekt configuration improvements

- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- scanner/src/test/assets/scancode-with-issues.json
- scanner/src/test/kotlin/scanners/scancode/ScanCodeTest.kt
See the single commits for further details.
> ScanCode: Improve error handling

- cli/build.gradle.kts
See [1] for some background information.
[1]: https://github.com/oracle/graal/issues/4265
> Gradle: Add more Graal options to work-around native image build issues

- docs/config-file-resolutions-yml.md
> Document vulnerability resolutions

- utils/spdx/src/main/resources/declared-license-mapping.yml
Add "GNU Lesser General Public License, Version 3"
Found in [1].
[1]: https://github.com/haifengl/smile/blob/v2.3.0/build.sbt#L34
Co-authored-by: Thomas Steenbergen <thomas.steenbergen@here.com>
Signed-off-by: Sankalpa Menon <sankalpa.menon@here.com>
> declared-license-mapping: Add "GNU Lesser General Public License"

- utils/spdx/src/main/resources/declared-license-mapping.yml
Found in [1].
[1]: https://github.com/dpaukov/combinatoricslib/blob/release21/pom.xml#L10
Signed-off-by: Sachin Bhakar <sachin.bhakar@here.com>
> declared-license-mapping: Add "LGPL v3.0"

- analyzer/src/main/kotlin/managers/utils/SpdxDocumentCache.kt
- analyzer/src/main/kotlin/managers/utils/SpdxResolvedDocument.kt
- docs/notice-templates.md
- model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
Fix a couple of issues reported by IntelliJ's code analyzer.
> Code inspection fixes

- Dockerfile
> Avoid referring to `$HOME` in the Dockerfile

- .github/workflows/build-and-test.yml
- reporter-web-app/build.gradle.kts
> Miscellaneous GitHub action / reporter related stuff

- Dockerfile
- scripts/docker_run.sh
> Furher fixes for running Go as non-root in Docker

- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
> cli: Clarify that configuration being looked for is tool-specific

- analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml
- analyzer/src/main/kotlin/managers/Conan.kt
> Conan improvements and updates

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
> PipFunTest: Update the expected dependencies

- analyzer/src/main/kotlin/managers/Conan.kt
> More Conan improvements

- .github/workflows/build-and-test.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/static-analysis.yml
- analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
- analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
> Some ClearlyDefined / curation improvements

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- analyzer/src/funTest/kotlin/managers/PipFunTest.kt
> Python 3.8 fixes

- .azure-pipelines/LinuxAnalyzerTest.yml
- .azure-pipelines/LinuxTest.yml
- .azure-pipelines/WindowsAnalyzerTest.yml
- .azure-pipelines/WindowsTest.yml
- build.gradle.kts
See [1].
[1]: https://kotest.io/docs/framework/tags.html
> Update to the new Kotest syntax for test tags

- .github/workflows/build-and-test.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/static-analysis.yml
- README.md
- cli/src/main/kotlin/commands/UploadCurationsCommand.kt
- docs/config-file-package-configuration-yml.md
- examples/evaluator-rules/src/main/resources/example.rules.kts
- examples/resolutions.yml
- integrations/schemas/repository-configuration-schema.json
> Add GitHub workflow badges

- clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
- clients/fossid-webapp/src/test/kotlin/FossId2021dot2Test.kt
- clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
- clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
- clients/fossid-webapp/src/test/kotlin/FossIdRulesTest.kt
> Ensure client libraries are independent of ORT core code

- analyzer/src/main/kotlin/managers/Pub.kt
- analyzer/src/main/kotlin/managers/utils/PubCacheReader.kt
Reduce the file size a bit and apply a minor simplification.
> Pub: Extract PubCacheReader to a separate file

- cli/src/main/kotlin/commands/AnalyzerCommand.kt
> Definition files vs projects

- utils/scripting/build.gradle.kts
- utils/scripting/src/main/kotlin/ScriptRunner.kt
> Small scripting improvements

- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
> Properly apply local package configurations in the `ReporterCommand`

- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- scanner/src/main/kotlin/storages/CompositeStorage.kt
> Miscellaneous improvements and fixes

- cli/src/main/kotlin/commands/UploadResultToPostgresCommand.kt
- helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
- helper-cli/src/main/kotlin/commands/DownloadResultsFromPostgresCommand.kt
- helper-cli/src/main/kotlin/commands/scanstorage/DeleteCommand.kt
- model/src/main/kotlin/utils/DatabaseUtils.kt
- model/src/main/kotlin/utils/PostgresFileArchiverStorage.kt
- scanner/src/main/kotlin/experimental/PostgresNestedProvenanceStorage.kt
- scanner/src/main/kotlin/experimental/PostgresPackageProvenanceStorage.kt
- scanner/src/main/kotlin/experimental/ProvenanceBasedPostgresStorage.kt
- scanner/src/main/kotlin/storages/PostgresStorage.kt
- utils/test/src/main/kotlin/PostgresListener.kt
> Initialize `DataSource`s lazily 

- scanner/src/main/kotlin/PathScanner.kt
> Scan dupe logging

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
> FossId license mapping improvements

- analyzer/src/main/kotlin/PackageManager.kt
> PackageManager: Improve logging of relative paths in `resolveDependencies`

- analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output-no-lockfile.yml
> analyzer: Correct expected issue messages

- utils/spdx/src/main/resources/declared-license-mapping.yml
Add a few declared license mappings, see the commit messages for details.
> Add declared license mapping for "Apache-2.0 license"

- scanner/src/funTest/kotlin/scanners/AbstractScannerFunTest.kt
- scanner/src/funTest/kotlin/scanners/AskalonoScannerFunTest.kt
- scanner/src/funTest/kotlin/scanners/BoyterLcScannerFunTest.kt
- scanner/src/funTest/kotlin/scanners/LicenseeScannerFunTest.kt
- scanner/src/funTest/kotlin/scanners/scancode/ScanCodeScannerFunTest.kt
> AbstractScannerFunTest: Cover full LicenseFindings incl. score

- utils/spdx/src/main/kotlin/model/SpdxRelationship.kt
- utils/spdx/src/main/kotlin/model/SpdxSnippet.kt
According to [1], annotation are available on snippets, too.
[1]: https://spdx.github.io/spdx-spec/annotations/
> Add some missing SPDX properties

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- gradle/wrapper/gradle-wrapper.properties
See [1].
[1]: https://docs.gradle.org/7.4.1/release-notes.html
> Upgrade Gradle to version 7.4.1

- clients/scanoss/src/main/kotlin/model/BooleanSerializer.kt
- clients/scanoss/src/main/kotlin/model/Model.kt
- clients/scanoss/src/main/kotlin/model/ScanResponse.kt
- clients/scanoss/src/test/assets/details/mappings/scan_details.json
- clients/scanoss/src/test/kotlin/ScanOssDetailsTest.kt
- clients/scanoss/src/test/kotlin/ScanOssServiceTest.kt
This PR improves the model for SCANOSS response in ORT based on some non-public documentation.
Please refer to individual commits for details.
> Several improvements to SCANOSS model

- utils/common/src/test/kotlin/FileMatcherTest.kt
> `FileMatcherTest` improvements

- utils/common/src/test/kotlin/FileMatcherTest.kt
> FileMatcherTest: Add another test that combines glob and globstar

- evaluator/src/main/kotlin/PackageRule.kt
- evaluator/src/test/kotlin/PackageRuleTest.kt
- examples/evaluator-rules/src/main/resources/example.rules.kts
> Simplify vulnerability rules

- analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml
> ConanFunTest: Update an expected homepage URL

- cli/src/main/kotlin/commands/DownloaderCommand.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- utils/common/src/main/kotlin/Extensions.kt
> DownloaderCommand: Add an option to filter by package ids

- notifier/src/main/kotlin/modules/JiraNotifier.kt
- notifier/src/test/kotlin/modules/JiraNotifierTest.kt
Add a function to change the assignee of an issue.
> JiraNotifier: Add function to change the assignee

- utils/core/src/main/kotlin/OkHttpClientHelper.kt
- utils/core/src/test/kotlin/OkHttpClientHelperTest.kt
Currently, an exception thrown when writing the file to disk is not
handled and can break clients. Prevent this by writing the file in a
mapCatching() block.
> OkHttpClientHelper: Handle exceptions when downloading files

- utils/common/src/test/kotlin/ExtensionsTest.kt
> ExtensionsTest: Sort outer tests alphabetically

- analyzer/src/funTest/kotlin/managers/NpmFunTest.kt
- analyzer/src/funTest/kotlin/managers/NpmVersionUrlFunTest.kt
- analyzer/src/funTest/kotlin/managers/PipFunTest.kt
- analyzer/src/main/kotlin/managers/Npm.kt
- analyzer/src/main/kotlin/managers/Yarn.kt
- analyzer/src/main/kotlin/managers/utils/NpmDependencyHandler.kt
- analyzer/src/test/kotlin/managers/utils/NpmDependencyHandlerTest.kt
> Npm vs Yarn fixes

- reporter/src/funTest/kotlin/reporters/WebAppReporterFunTest.kt
> WebAppReporterFunTest: Narrow down the expected file size

- analyzer/src/main/kotlin/managers/Pub.kt
Unfortunately, no changelog is available.
> Pub: Upgrade bootstrapped flutter version to 2.10.4

- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
- scanner/src/main/kotlin/experimental/NestedProvenanceScanResult.kt
- scanner/src/main/kotlin/experimental/ScanController.kt
Some improvements for the exeperimental scanner, see the commit messages for details.
> `ExperimentalScanner` fixes

- analyzer/src/main/kotlin/managers/Cargo.kt
- analyzer/src/main/kotlin/managers/Pip.kt
- analyzer/src/main/kotlin/managers/Pipenv.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
> Cargo: Remove a possible suffix from the version string

- model/src/main/kotlin/TextLocation.kt
- model/src/main/kotlin/utils/FindingsMatcher.kt
- model/src/test/kotlin/utils/FindingsMatcherTest.kt
> FindingsMatcher: Omit contained exceptions

- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
- scanner/src/main/kotlin/experimental/ScanController.kt
- scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt
> `ExperimentalScanner`: Handle provenance resolution issues

- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- helper-cli/src/main/kotlin/HelperMain.kt
- helper-cli/src/main/kotlin/commands/ListPackagesCommand.kt
> (helper-)cli: Remove redundant mentions of available / default values 

- analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-py.yml
- analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml
- gradle/wrapper/gradle-wrapper.properties
See [1].
[1]: https://docs.gradle.org/7.4.2/release-notes.html
> Upgrade Gradle to version 7.4.2

- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/test/kotlin/vcs/GitTest.kt
> GitTest improvements

- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
> Add a root `.ort.yml` to sparse checkouts

- helper-cli/src/main/kotlin/commands/repoconfig/GenerateScopeExcludesCommand.kt
> Add scope exclude for spotbugs

- downloader/src/main/kotlin/vcs/Git.kt
> Git: Also clone submodules shallowly for performance reasons

- analyzer/src/main/kotlin/managers/Npm.kt
> Parse NPM packages in parallel

- analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-py.yml
- analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml
- analyzer/src/main/kotlin/managers/Conan.kt
> Conan: Detect whether packages are modified based on patches 

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-py.yml
- analyzer/src/main/kotlin/managers/Pip.kt
> Pip updates and refactorings

- .reuse/dep5
- integrations/tekton/mime-types.yaml
- integrations/tekton/ort-pipeline.yaml
- integrations/tekton/simple-maven.yaml
> Miscellaneous minor formatting stuff

- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
- scanner/src/main/kotlin/experimental/NestedProvenance.kt
- scanner/src/main/kotlin/experimental/NestedProvenanceScanResult.kt
- scanner/src/test/kotlin/experimental/NestedProvenanceScanResultTest.kt
Some fixes for the experimental scanner, see the commit messages for details.
> ExperimentalScanner fixes

- scanner/src/main/kotlin/PathScanner.kt
> PathScanner: Trivially improve package ID quoting in logs

- .gitattributes
- .github/workflows/build-and-test.yml
- batect
- batect.cmd
> Upgrade Batect

- analyzer/src/main/kotlin/managers/Carthage.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- utils/common/src/main/kotlin/Extensions.kt
- utils/common/src/test/kotlin/ExtensionsTest.kt
- utils/core/src/main/kotlin/DeclaredLicenseProcessor.kt
- utils/core/src/main/kotlin/OkHttpClientHelper.kt
- utils/core/src/test/kotlin/DeclaredLicenseProcessorTest.kt
- utils/spdx/src/main/kotlin/SpdxConstants.kt
> Improve mapping of declared licenses

- scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
- utils/spdx/src/main/kotlin/SpdxExpression.kt
> SPDX / FossID improvements

- downloader/src/main/kotlin/VcsHost.kt
> VcsHost: Trivially simplify some code by using `nextOrNull()`

- clients/scanoss/src/main/kotlin/model/BooleanSerializer.kt
- clients/scanoss/src/main/kotlin/model/Model.kt
> scanoss: Simplify the `BooleanSerializer` a bit

- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- analyzer/src/test/kotlin/managers/utils/MavenSupportTest.kt
- model/src/main/kotlin/Hash.kt
- model/src/test/kotlin/HashTest.kt
> Improve maven checksum handling

- build.gradle.kts
> Gradle: Apply some syntactic sugar for test suite registration

- analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml
> ConanFunTests: Update expected test results

- downloader/src/main/kotlin/vcs/GitRepo.kt
> Upgrade the used GitRepo version

- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/Composer.kt
- analyzer/src/main/kotlin/managers/Npm.kt
- analyzer/src/main/kotlin/managers/utils/NodeSupport.kt
- model/src/main/kotlin/FileFormat.kt
- model/src/main/kotlin/Mappers.kt
- model/src/test/kotlin/FileFormatTest.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt
> Allow empty definition files again

- downloader/src/main/kotlin/Downloader.kt
- utils/common/src/main/kotlin/ArchiveUtils.kt
- utils/common/src/test/kotlin/ArchiveUtilsTest.kt
This PR fixes #5329. Refer to the single commits for more information.
> Support unpacking unknown archives

- analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-py.yml
- analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml
> ConanFunTest: Update expected test results

- analyzer/src/funTest/assets/projects/synthetic/gomod-expected-output.yml
- model/src/main/kotlin/Identifier.kt
- model/src/test/kotlin/IdentifierTest.kt
- utils/common/src/main/kotlin/AlphaNumericComparator.kt
- utils/common/src/test/kotlin/AlphaNumericComparatorTest.kt
> Use a natural number comparator for versions

- cli/src/main/kotlin/OrtMain.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- cli/src/main/kotlin/utils/PackageConfigurationOption.kt
- helper-cli/src/main/kotlin/common/PackageConfigurationOption.kt
- model/src/main/kotlin/Provenance.kt
- model/src/main/kotlin/config/ScanStorageConfiguration.kt
- model/src/main/kotlin/utils/DependencyGraphBuilder.kt
- scanner/src/main/kotlin/experimental/PackageProvenanceStorage.kt
Sealed interface are more flexible and allow for a slightly simpler
implementation syntax. For more details see [1].
[1]: https://stackoverflow.com/a/69103695/1127485
> Prefer sealed interfaces over sealed classes where possible

- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
- utils/common/src/main/kotlin/ArchiveUtils.kt
> Replace `archive()` with `packZip()`

- model/src/main/kotlin/ScanResult.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
Check commit messages for details.
> FossId: Store the scan code of a scan in the ScanSummary

- model/src/main/kotlin/config/FileArchiverConfiguration.kt
- model/src/main/resources/reference.conf
- scanner/src/funTest/kotlin/scanners/AbstractScannerFunTest.kt
- scanner/src/main/kotlin/PathScanner.kt
- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
- scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt
> Allow to disable the file archiver

- analyzer/src/main/kotlin/managers/Pub.kt
- analyzer/src/main/kotlin/managers/utils/PubCacheReader.kt
- analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt
> Pub: Add support for path dependencies

- clients/clearly-defined/build.gradle.kts
- clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
- clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
- clients/clearly-defined/src/main/kotlin/Curation.kt
- clients/clearly-defined/src/main/kotlin/Definition.kt
- clients/clearly-defined/src/main/kotlin/Enums.kt
- clients/clearly-defined/src/main/kotlin/Serializers.kt
- clients/clearly-defined/src/test/kotlin/ClearlyDefinedServiceTest.kt
- scanner/src/funTest/kotlin/storages/ClearlyDefinedStorageFunTest.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
> clearly-defined: Port from Jackson to kotlinx.serialization

- analyzer/src/main/kotlin/managers/Yarn.kt
> Raise a warning if 'yarn --info' returns empty data

- model/src/main/kotlin/DependencyGraphNavigator.kt
- model/src/main/kotlin/utils/DependencyGraphBuilder.kt
- model/src/test/kotlin/utils/DependencyGraphBuilderTest.kt
> Improvements of the dependency graph

- analyzer/src/main/kotlin/managers/CocoaPods.kt
> CocoaPods: Simplify a regex

- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
> ExperimentalScanner: Slightly improve various log messages

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
- analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/pip-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/pipenv-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/pipenv-python3-expected-output.yml
- analyzer/src/main/kotlin/managers/Pip.kt
> Pip: Allow to map a generic BSD license in some cases

- .ort.yml
Update file paths for files which have been moved and remove entries for
deleted files.
> .ort.yml: Update moved and deleted files

- advisor/src/main/kotlin/advisors/OssIndex.kt
- clients/oss-index/src/main/kotlin/OssIndexService.kt
> OssIndex(Service): Make the displayName optional

- utils/common/src/main/kotlin/ArchiveUtils.kt
> ArchiveUtils beautifications

- analyzer/src/main/kotlin/AnalyzerResultBuilder.kt
- analyzer/src/main/kotlin/managers/Bundler.kt
- cli/src/main/kotlin/OrtMain.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/utils/Extensions.kt
- downloader/src/main/kotlin/Downloader.kt
- model/src/main/kotlin/OrtResult.kt
- model/src/main/kotlin/utils/FileArchiver.kt
- reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModelReporter.kt
- scanner/src/main/kotlin/CommandLineScanner.kt
- scanner/src/main/kotlin/PathScanner.kt
- scanner/src/main/kotlin/ScanResultsStorage.kt
- utils/ort/src/main/kotlin/Logger.kt
- utils/scripting/src/main/kotlin/ScriptRunner.kt
> Stop using the custom "perf" log level

- integrations/schemas/repository-configuration-schema.json
Use a reference to the resolutions schema to avoid duplication.
> Schemas: Reference resolutions schema

- model/src/main/kotlin/utils/FileArchiver.kt
- model/src/test/kotlin/utils/FileArchiverTest.kt
- utils/common/src/main/kotlin/ArchiveUtils.kt
> `FileArchiver` improvements

- analyzer/src/main/kotlin/managers/Conan.kt
- analyzer/src/main/kotlin/managers/utils/SpdxResolvedDocument.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- downloader/src/test/kotlin/vcs/GitTest.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- utils/ort/src/main/kotlin/Utils.kt
- utils/ort/src/test/kotlin/UtilsTest.kt
Refer to the single commits for further information.
> Add helper functions to request password authentication

- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- model/src/main/kotlin/Package.kt
- model/src/main/kotlin/Project.kt
- model/src/main/kotlin/licenses/LicenseInfoResolver.kt
> Miscellaneous clean-ups and fixes for inspection hints

- analyzer/src/funTest/kotlin/managers/Yarn2FunTest.kt
- analyzer/src/main/kotlin/managers/Composer.kt
- analyzer/src/main/kotlin/managers/Yarn2.kt
- analyzer/src/main/kotlin/managers/utils/NodeSupport.kt
- utils/common/src/main/kotlin/CommandLineTool.kt
> Some minor Yarn2 improvements

- analyzer/src/main/kotlin/managers/utils/MavenDependencyHandler.kt
- analyzer/src/test/kotlin/managers/utils/GradleDependencyHandlerTest.kt
- reporter/src/main/kotlin/reporters/fossid/FossIdReporter.kt
- scanner/src/main/kotlin/ScanResultsStorage.kt
> Fix all broken KDoc references

- analyzer/src/main/kotlin/managers/utils/SpdxResolvedDocument.kt
> SpdxResolvedDocument: Minor improvements

- helper-cli/src/main/kotlin/commands/scanstorage/DeleteCommand.kt
- helper-cli/src/main/kotlin/common/Utils.kt
The `--license` option can be used to delete stored scan results, if the
specified license is contained in the detected licenses.
This can be useful if the `detectedLicenseMapping` is changed and the
user wants to ensure that the stored scan results no longer returns the
old mapping.
> DeleteCommand: Add option to delete scan results with a specific license

- model/src/main/resources/reference.conf
- model/src/test/kotlin/config/OrtConfigurationTest.kt
Please see individual commits for details.
> Reference.conf consistency improvements

- scanner/src/main/kotlin/Scanner.kt
> Scanner: Fix config check

- README.md
- analyzer/src/main/kotlin/managers/Poetry.kt
> Poetry: Minor improvements

- examples/go-mod.ort.yml
See [1], [2] and also [3].
[1] https://github.com/oss-review-toolkit/ort/pull/5454
[2] https://github.com/oss-review-toolkit/ort/pull/5459
[3] 64b64670b6e8c26b97c2548f4d52c7e0643e4618
> examples/go-mod.ort.yml: Align with recent changes in GoMod

- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- model/src/main/kotlin/config/AnalyzerConfiguration.kt
- model/src/main/kotlin/config/PackageManagerConfiguration.kt
- model/src/main/kotlin/config/RepositoryConfiguration.kt
- model/src/test/kotlin/config/AnalyzerConfigurationTest.kt
- model/src/test/kotlin/config/PackageManagerConfigurationTest.kt
- model/src/test/kotlin/config/RepositoryConfigurationTest.kt
Make it possible to configure the analyzer in the .ort.yml file, see the commit messages for details.
> RepositoryConfiguration: Add AnalyzerConfiguration

- helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
> CreateAnalyzerResultCommand: Tolerate blank ScanCode versions

- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
- utils/ort/src/main/kotlin/CopyrightStatementsProcessor.kt
- utils/spdx/src/main/kotlin/Utils.kt
> Miscellanous minor improvement / fixes

- analyzer/src/funTest/assets/projects/synthetic/spdx/project-xyz-with-sub-project-dependencies.spdx.yml
- analyzer/src/funTest/assets/projects/synthetic/spdx/projects/sub-project-xyz-with-inline-packages.spdx.yml
- analyzer/src/funTest/kotlin/managers/SpdxDocumentFileFunTest.kt
- analyzer/src/main/kotlin/AnalyzerResultBuilder.kt
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
> SPDX: Prevent duplicate packages for projects

- analyzer/src/main/kotlin/managers/Pub.kt
> Pub: Log improvements

- advisor/src/main/kotlin/advisors/VulnerableCode.kt
- analyzer/src/main/kotlin/managers/Npm.kt
- model/src/main/kotlin/CuratedPackage.kt
- model/src/main/kotlin/PackageCurationData.kt
Simplify code in several places by using collection builders.
> Use collection builders to simplify code

- analyzer/src/main/kotlin/managers/Npm.kt
Since NPM 7 conflicts in peer dependencies lead to an error during `npm
install`, unless the `--legacy-peer-deps` flag is provided [1][2].
Add an option to `Npm` to enable this flag on demand, so that NPM 6
projects with peer dependency conflicts can be analyzed.
[1]: https://docs.npmjs.com/cli/v8/commands/npm-install#strict-peer-deps
[2]: https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major
> Npm: Add an option to enable legacy peer dependencies

- README.md
- advisor/build.gradle.kts
- advisor/src/funTest/assets/retrieve-package-findings-expected-result.json
- advisor/src/funTest/kotlin/OsvFunTest.kt
- advisor/src/main/kotlin/Advisor.kt
- advisor/src/main/kotlin/advisors/Osv.kt
- advisor/src/main/resources/META-INF/services/org.ossreviewtoolkit.advisor.AdviceProviderFactory
- advisor/src/test/kotlin/AdvisorTest.kt
- clients/osv/src/main/kotlin/Model.kt
- model/src/main/kotlin/config/AdvisorConfiguration.kt
- model/src/main/resources/reference.conf
A first iteration for #3599 with a couple of things left as TODO.
> Integrate OSV.dev as advisor

- analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
- analyzer/src/main/kotlin/AnalyzerResultBuilder.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Pub.kt
- analyzer/src/main/kotlin/managers/utils/PackageManagerDependencyHandler.kt
- analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
- model/src/main/kotlin/DependencyGraphNavigator.kt
- model/src/main/kotlin/utils/DependencyGraphConverter.kt
Introduce a mechanism for dependencies between package managers. Please see the commit messages for details.
> Implement mechanism for dependencies between package managers

- README.md
- advisor/src/funTest/assets/retrieve-package-findings-expected-result.json
- advisor/src/funTest/kotlin/OsvFunTest.kt
- advisor/src/main/kotlin/advisors/NexusIq.kt
- advisor/src/main/kotlin/advisors/OssIndex.kt
- advisor/src/main/kotlin/advisors/Osv.kt
- cli/src/funTest/assets/semver4j-analyzer-result.yml
- model/src/test/assets/advisor-result-initial.yml
- model/src/test/assets/advisor-result-vulnerability-refs.yml
> Capitalize the OSV acronym in free text

- advisor/src/main/kotlin/advisors/NexusIq.kt
- advisor/src/main/kotlin/advisors/OssIndex.kt
- cli/src/funTest/assets/semver4j-analyzer-result.yml
- model/src/test/assets/advisor-result-initial.yml
- model/src/test/assets/advisor-result-vulnerability-refs.yml
See individual commit messages for details.
> Revert advisors name change

- integrations/jenkins/Jenkinsfile
- integrations/jenkins/README.md
- integrations/tekton/README.md
- integrations/tekton/ort-pipeline.yaml
> Add a dedicated `README.md` for Jenkins integration

- advisor/src/funTest/assets/retrieve-package-findings-expected-result.json
- clients/osv/src/main/kotlin/OsvApiClient.kt
- integrations/jenkins/Jenkinsfile
> Jenkinsfile: Add an advisor stage, using OSV

- .detekt.yml
- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- gradle/libs.versions.toml
- model/src/main/kotlin/DependencyGraph.kt
- scanner/src/main/kotlin/experimental/WorkingTreeCache.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
> Upgrade to a new Detekt version

- advisor/src/main/kotlin/advisors/Osv.kt
> Osv: Add fault tolerance for invalid URIs

- advisor/src/funTest/assets/retrieve-package-findings-expected-result.json
> OsvFunTest: Update expected results for `NPM::glob-parent:5.1.1`

- advisor/src/funTest/kotlin/OsvFunTest.kt
- advisor/src/main/kotlin/advisors/Osv.kt
- analyzer/src/main/kotlin/managers/Conan.kt
- clients/osv/src/main/kotlin/Model.kt
- helper-cli/src/main/kotlin/commands/DownloadResultsFromPostgresCommand.kt
- reporter/src/main/kotlin/ReportTableModelMapper.kt
- reporter/src/main/kotlin/reporters/fossid/FossIdReporter.kt
- utils/spdx/src/main/kotlin/model/SpdxFile.kt
- utils/spdx/src/main/kotlin/model/SpdxSnippet.kt
> Miscellaneous small OSV improvements

- advisor/src/funTest/assets/retrieve-package-findings-expected-result.json
Add more references and reorder results as expected.
> OsvFunTest: Update expected test results

- analyzer/src/main/kotlin/managers/utils/MavenDependencyHandler.kt
- analyzer/src/test/kotlin/managers/utils/MavenDependencyHandlerTest.kt
Under certain circumstances, the Maven analyzer could create a package
with the same identifier as a local project. This caused a sanity
check in AnalyzerResultBuilder to fail. To prevent this, improve the
tests whether a package corresponds to a local project in
MavenDependencyHandler. Also make sure that for the affected package
the correct linkage is returned.
Resolves #5581.
> MavenDependencyHandler: Improve the checks for project dependencies

- advisor/src/funTest/kotlin/OsvFunTest.kt
- advisor/src/main/kotlin/advisors/Osv.kt
> OSV: Enable ruby gems

- advisor/src/funTest/assets/retrieve-package-findings-expected-result.json
- advisor/src/funTest/kotlin/OsvFunTest.kt
> OSV: Improve the functional test

- integrations/jenkins/README.md
- scanner/src/main/kotlin/scanners/fossid/FossIdConfig.kt
> Fix a couple of typos

- advisor/src/main/kotlin/advisors/Osv.kt
- clients/osv/src/main/kotlin/Model.kt
> Osv: Clarify the mapping of the severity

- analyzer/src/funTest/assets/projects/synthetic/spdx-project-xyz-expected-output-subproject-conan.yml
- analyzer/src/funTest/assets/projects/synthetic/spdx/README.md
- analyzer/src/funTest/assets/projects/synthetic/spdx/subproject-conan/project-xyz.spdx.yml
- analyzer/src/funTest/assets/projects/synthetic/spdx/subproject-conan/subproject/conanfile.py
- analyzer/src/funTest/assets/projects/synthetic/spdx/subproject-conan/subproject/subproject-with-conan-reference.spdx.yml
- analyzer/src/funTest/assets/projects/synthetic/spdx/subproject-dependencies/project-xyz.spdx.yml
- analyzer/src/funTest/assets/projects/synthetic/spdx/subproject-dependencies/subproject/subproject-xyz.spdx.yml
- analyzer/src/funTest/kotlin/managers/SpdxDocumentFileFunTest.kt
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- analyzer/src/test/kotlin/managers/SpdxDocumentFileTest.kt
Please see the commit messages for details. This PR depends on #5551 to be merged first.
> SPDX: Definition file references

- scanner/src/main/kotlin/experimental/PackageProvenanceResolver.kt
Some registries, for instance artifact feeds in Azure DevOps, do not
support the HEAD method when checking for the existence of artifacts.
To deal with those, handle "405 Bad method" errors by falling back to
regular GET requests.
> PackageProvenanceResolver: Handle 405 errors in resolveSourceArtifact

- analyzer/src/main/kotlin/managers/CocoaPods.kt
- clients/osv/src/funTest/kotlin/OsvServiceFunTest.kt
- clients/osv/src/main/kotlin/OsvApiClient.kt
- downloader/src/main/kotlin/vcs/GitRepo.kt
- model/src/main/kotlin/AdvisorRecord.kt
- model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt
- model/src/main/kotlin/utils/FindingsMatcher.kt
- scanner/src/main/kotlin/PathScanner.kt
- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
> A couple of code inspection fixes

- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
- model/src/main/kotlin/OrtIssue.kt
- utils/ort/src/main/kotlin/Logger.kt
- utils/ort/src/main/kotlin/OrtAuthenticator.kt
- utils/ort/src/main/kotlin/OrtProxySelector.kt
- utils/ort/src/test/kotlin/LoggerTest.kt
> Logging clean-ups

- utils/spdx/src/main/resources/declared-license-mapping.yml
> Add various declared license mapping

- gradle/wrapper/gradle-wrapper.properties
See: https://docs.gradle.org/7.5.1/release-notes.html
> Gradle: Upgrade to version 7.5.1

- .github/workflows/batect-wrapper-validation.yml
- .github/workflows/build-and-test.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/static-analysis.yml
- Dockerfile
- batect.yml
Update to the most recent LTS release Ubuntu 22.04 "Jammy Jellyfish".
This is mostly to get Composer 2 directly from upstream, also see [1].
[1]: https://github.com/oss-review-toolkit/ort/pull/5497#issuecomment-1195058103
> Dockerfile: Update to Ubuntu 22.04 base images

- clients/osv/src/funTest/assets/vulnerabilities-by-name-and-version-expected-result.json
- clients/osv/src/funTest/kotlin/OsvServiceFunTest.kt
> OsvServiceFunTest updates

- analyzer/src/main/kotlin/managers/utils/NodeSupport.kt
> NodeSupport: Improve wording of a PNPM related code comment

- README.md
> README: Update wrapper validation badge

- reporter-web-app/build.gradle.kts
> Web app build improvements

- downloader/src/main/kotlin/VersionControlSystem.kt
> VersionControlSystem: Quote a revision when logging for consistency

- reporter/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
- reporter/src/funTest/assets/static-html-reporter-test-input.yml
- reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModelMapper.kt
- reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedOrtIssueType.kt
> reporter: Add advisor issues to evaluated model

- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
> scanner: Add hints to results for scanners that cannot detect copyrights

- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
Run the provenance resolution in parallel to improve performance.
> Scanner: Parallelize provenance resolution

- analyzer/src/main/kotlin/managers/Npm.kt
- analyzer/src/main/kotlin/managers/Yarn2.kt
- analyzer/src/main/kotlin/managers/utils/NpmSupport.kt
- analyzer/src/test/kotlin/managers/utils/NpmSupportTest.kt
> Minor NodeSupport clean-ups

- model/src/main/kotlin/CuratedPackage.kt
- model/src/main/kotlin/Package.kt
- model/src/test/kotlin/PackageTest.kt
> Package.diff() fixes

- README.md
- cli/src/main/kotlin/commands/ScannerCommand.kt
- model/src/main/kotlin/config/PostgresConnection.kt
- model/src/main/kotlin/config/ScanStorageConfiguration.kt
> Add documentation for the experimental scanner

- helper-cli/src/main/kotlin/commands/packageconfig/CreateCommand.kt
> helper-cli: CreateCommand improvements

- analyzer/src/main/kotlin/managers/Pip.kt
Some improvements for the python-inspector integration, see the commit messages for details. A follow-up PR will address some issues with regards to selecting the correct Python version.
> Pip: Improve python inspector integration

- advisor/build.gradle.kts
> advisor: Remove unused `funTest` dependencies on Jackson

- build.gradle.kts
> Gradle: Apply a small JGit-related code beautification

- model/src/main/kotlin/Package.kt
- model/src/main/kotlin/PackageCurationData.kt
- model/src/main/kotlin/Project.kt
> Improve license field docs

- analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
- analyzer/src/main/kotlin/managers/Pip.kt
> Pip improvements

- analyzer/src/funTest/kotlin/curation/OrtConfigPackageCurationProviderFunTest.kt
- evaluator/src/test/kotlin/EvaluatorTest.kt
- model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
> Reduce nesting in tests for readability

- Dockerfile
- analyzer/src/funTest/kotlin/managers/PipFunTest.kt
- analyzer/src/main/kotlin/managers/Pip.kt
> Upgrade python-inspector

- utils/common/src/main/kotlin/FileMatcher.kt
Create only instance of `AntPathMatcher` for case-sensitive and
case-insensitive matching each. For convenience, also create static
matcher functions for cases where the patterns are not reused and
creating an instance of `FileMatcher` would be overhead.
> FileMatcher: Reuse instances of `AntPathMatcher`

- .lift.toml
> Update Lift links

- evaluator/src/test/kotlin/RuleSetTest.kt
> RuleSetTest: Reduce nesting for readability

- model/src/test/kotlin/utils/DependencyGraphConverterTest.kt
> DependencyGraphConverterTest: Optimize mapping of projects / packages

- advisor/src/main/kotlin/advisors/GitHubDefects.kt
This avoids the ugly `pkg.pkg` construct.
> GitHubDefects: Rename the original package property

- analyzer/src/funTest/assets/projects/synthetic/pub-expected-output-with-flutter-android-and-cocoapods.yml
- analyzer/src/main/kotlin/managers/Pub.kt
See: https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.3.0
> Pub: Upgrade bootstrapped Flutter version to 3.3.0

- helper-cli/build.gradle.kts
- helper-cli/src/main/kotlin/utils/PathExcludeGenerator.kt
- helper-cli/src/main/kotlin/utils/Utils.kt
- helper-cli/src/test/kotlin/PathExcludeGeneratorTest.kt
- helper-cli/src/test/kotlin/UtilsTest.kt
Fix an issue, add some tests and handle further directories.
> Improve the generation of path excludes

- .github/workflows/static-analysis.yml
See [1] and [2]. This complements detekt with the inspection hints known
from IntelliJ IDEA and resolves #4051.
[1]: https://github.com/JetBrains/qodana-action
[2]: https://www.jetbrains.com/help/qodana/
> github/workflows: Add a Qodana scan job

- downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt
> GitWorkingTreeFunTest: Account for `master` being renamed to `main`

- downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt
> GitWorkingTreeFunTest: Update the list of expected remote tags

- downloader/src/main/kotlin/vcs/GitWorkingTree.kt
Previously, the `Repository` instance remained open during the lifetime
of the `GitWorkingTree`. That is a problem if some clean-up code (like
in tests) wants to delete a cloned Git repository while there is still
a GitWorkingTree instance.
To avoid that, provide a getter for the `repo` property which allows the
caller to auto-close the `Repository` instance after use as on the next
access of the `repo` property it will be re-evaluated. The added runtime
overhead due to this should be neglible compared to the duration of the
Git operation.
> GitWorkingTree: Properly close the repository after each operation

- reporter-web-app/src/components/PackageLicenses.js
- reporter-web-app/src/components/TableView.js
- reporter-web-app/src/models/WebAppOrtResult.js
- reporter-web-app/src/models/WebAppPackage.js
- reporter/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
- reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModelMapper.kt
- reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedPackage.kt
> Add the effective license to the web app reporter

- README.md
- model/src/main/kotlin/config/PostgresConnection.kt
> Update links to the PostgreSQL client SSL configuration

- clients/osv/src/funTest/assets/vulnerabilities-by-name-and-version-expected-result.json
Account for changed query results.
> OsvServiceFunTest: Update an expected output

- scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
- scanner/src/main/kotlin/experimental/ScanController.kt
The `ExperimentalScanner` downloads missing archives for packages and whenever,
the `Downloader` fails and throws a `DownloadException` the scanner stopped
the execution. This commit moves the downloader call in a runCatching block
and creates an `OrtIssue` on failure.
> ExperimentalScanner: Catch `DownloadException` when creating archives

- analyzer/src/funTest/assets/projects/synthetic/pub-expected-output-with-flutter-android-and-cocoapods.yml
- analyzer/src/main/kotlin/managers/Pub.kt
See: https://groups.google.com/g/flutter-announce/c/q_l6jOBUCzY
> Pub: Upgrade bootstrapped Flutter version to 3.3.1

- docs/license-handling.md
> docs: Explain handling of licenses in ORT

- gradle/libs.versions.toml
- utils/spdx/build.gradle.kts
> Speed up the download of SPDX license texts

- evaluator/src/main/kotlin/OrtResultRule.kt
- evaluator/src/main/kotlin/ProjectSourceRule.kt
> Some fixups for recent changes

- downloader/src/funTest/kotlin/DownloaderFunTest.kt
- downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt
> DownloaderFunTest improvements

- integrations/schemas/ort-configuration-schema.json
- integrations/schemas/package-manager-configuration-schema.json
This is a fixup of 13091d75a58066b6e20cbf02056f94007e2d949f.
> Schemas: Fix wrong reference URLs

- downloader/src/main/kotlin/vcs/Git.kt
> Git simplifications

- docs/license-handling.md
> License handling doc improvements

- clients/osv/src/funTest/assets/vulnerabilities-by-name-and-version-expected-result.json
> OsvServiceFunTest: Update expected test results

- model/src/test/kotlin/JsonSchemaTest.kt
> Schema test improvements

- analyzer/src/main/kotlin/managers/Sbt.kt
> Fixup the `user.home` passed to SBT

- scanner/src/main/kotlin/scanners/scanoss/ScanOssConfig.kt
- scanner/src/test/kotlin/scanners/scanoss/ScanOssConfigTest.kt
> ScanOss config improvements

- integrations/schemas/ort-configuration-schema.json
- integrations/schemas/repository-configuration-schema.json
In order to pass the `JsonSchemaTest` https://github.com/oss-review-toolkit/ort/pull/5788 has to be merged.
> Schemas: Reference analyzer configuration schema

- analyzer/src/main/kotlin/curation/FilePackageCurationProvider.kt
- analyzer/src/main/kotlin/curation/OrtConfigPackageCurationProvider.kt
> Curation provider alignments

- gradle/libs.versions.toml
- utils/spdx/build.gradle.kts
> Further optimize the download of SPDX license texts

- .github/workflows/static-analysis.yml
- .reuse/dep5
- build.gradle.kts
- qodana.yml
> Fix running static analysis checks in GitHub actions

- advisor/src/funTest/kotlin/OsvFunTest.kt
- clients/osv/build.gradle.kts
- clients/osv/src/funTest/kotlin/OsvServiceFunTest.kt
- clients/osv/src/main/kotlin/Model.kt
- clients/osv/src/test/kotlin/ModelTest.kt
- reporter/src/funTest/kotlin/reporters/spdx/SpdxDocumentReporterFunTest.kt
- reporter/src/test/kotlin/reporters/OpossumReporterTest.kt
> OSV: Disregard the `modified` field

- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml
- cli/src/funTest/kotlin/OrtMainFunTest.kt
> OrtMainFunTest fixes

- model/src/test/kotlin/AdvisorRecordTest.kt
Reduce some test setup, reduce some repetition and eliminate some magic values.
> AdvisorRecord: Some test improvements

- .github/workflows/build-and-test.yml
- .github/workflows/static-analysis.yml
- batect.yml
> Speed up the Batect build by restoring Gradle caches on the host

- reporter-web-app/build.gradle.kts
> Rescripts not found fix

- cli/src/funTest/kotlin/ExamplesFunTest.kt
- model/src/main/kotlin/AdvisorRecord.kt
- model/src/main/kotlin/AnalyzerRun.kt
- model/src/main/kotlin/ScanRecord.kt
- model/src/test/kotlin/AdvisorRecordTest.kt
> Fix `OrtResult.collectIssues()`

- clients/clearly-defined/src/main/kotlin/Serializers.kt
> Minor `ToStringSerializer` improvements

- scripts/docker_run.sh
> docker_run: Trivially trim a trailing space

- scripts/docker_build.sh
> Docker build script improvements

- advisor/src/main/kotlin/advisors/Osv.kt
- analyzer/src/main/kotlin/managers/Npm.kt
- analyzer/src/main/kotlin/managers/Pip.kt
- analyzer/src/main/kotlin/managers/Yarn2.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- evaluator/src/main/kotlin/RuleSet.kt
- helper-cli/src/main/kotlin/commands/VerifySourceArtifactCurationsCommand.kt
- helper-cli/src/main/kotlin/commands/packagecuration/CreateCommand.kt
- model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
- reporter/src/main/kotlin/reporters/gitlab/GitLabLicenseModelMapper.kt
- scanner/src/main/kotlin/experimental/PackageProvenanceResolver.kt
- scanner/src/main/kotlin/storages/PostgresStorage.kt
- scanner/src/main/kotlin/storages/Sw360Storage.kt
- scanner/src/test/kotlin/scanners/scanoss/ScanOssScannerDirectoryTest.kt
- scanner/src/test/kotlin/scanners/scanoss/ScanOssScannerFileTest.kt
- utils/common/src/main/kotlin/Extensions.kt
- utils/test/src/main/kotlin/Extensions.kt
> Miscellaneous small fixes

- analyzer/src/main/kotlin/managers/CocoaPods.kt
`run` throws on failure so the return statement was never reached.
> CocoaPods: Fix `getPodspec()` to return null if `run` fails

- README.md
See [1].
[1]: https://github.com/oss-review-toolkit/ort-governance/issues/6#issuecomment-1173522852
> README: Replace individual copyrights with a `NOTICE` reference

- helper-cli/src/main/kotlin/utils/PathExcludeGenerator.kt
- helper-cli/src/test/kotlin/PathExcludeGeneratorTest.kt
> PathExcludeGenerator: Enable filename specific excludes

- analyzer/src/main/kotlin/managers/Sbt.kt
- helper-cli/src/main/kotlin/utils/PathExcludeGenerator.kt
- helper-cli/src/test/kotlin/PathExcludeGeneratorTest.kt
- utils/common/src/main/kotlin/Utils.kt
- utils/common/src/test/kotlin/UtilsTest.kt
> Apply some minor `PathExcludeGenerator` improvements

- .gitattributes
- scanner/src/main/kotlin/scanners/scanoss/ScanOss.kt
- scanner/src/test/kotlin/scanners/scanoss/ScanOssScannerDirectoryTest.kt
- scanner/src/test/kotlin/scanners/scanoss/ScanOssScannerFileTest.kt
> SCANOSS test fixes

- .github/workflows/build-and-test.yml
- Dockerfile
- batect.yml
- docker/00-add_local_path.sh
- docker/android.sh
- docker/legacy/Dockerfile
- docker/ort-wrapper.sh
- docker/python.sh
- docker/ruby.sh
> Docker tool components

- evaluator/src/main/kotlin/PackageRule.kt
> PackageRule: Fix a KDoc parameter reference

- batect
- batect.cmd
- gradle/libs.versions.toml
> Upgrade Batect and MockK

- model/src/main/kotlin/PackageCurationData.kt
> PackageCurationData: Improve the documentation a bit

- analyzer/src/main/kotlin/managers/Conan.kt
Please refer to the single commits for further information.
> Some improvements to Conan

- .github/workflows/build-and-test.yml
- batect.yml
> Enable Gradle build scans also for functional test run inside Docker via Batect

- downloader/src/funTest/kotlin/vcs/CvsDownloadFunTest.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/CvsWorkingTree.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/main/kotlin/vcs/MercurialWorkingTree.kt
- downloader/src/main/kotlin/vcs/Subversion.kt
- downloader/src/main/kotlin/vcs/SubversionWorkingTree.kt
> Minor refactoring of CLI-based VCS classes

- ADOPTERS.md
We are currently in the process of adopting ORT for our open-source cloud stack project and are happy to add us to this list.
Signed-off-by: Eduard Itrich <eduard@itrich.net>
> Add Sovereign Cloud Stack as an adopter of ORT

- gradle/libs.versions.toml
- utils/spdx/build.gradle.kts
> Upgrade Kotlin and other dependencies

- Dockerfile
- analyzer/src/main/kotlin/managers/Cargo.kt
- docker/legacy/Dockerfile
> Dockerfile: Upgrade the Cargo version available in Ubuntu Jammy

- NOTICE
- build.gradle.kts
- cli/src/main/resources/logback.xml
- helper-cli/src/main/resources/logback.xml
- qodana.yml
- utils/test/src/main/resources/logback.xml
> Introduce a `NOTICE` file check

- integrations/tekton/mime-types.yaml
- integrations/tekton/ort-pipeline.yaml
- integrations/tekton/simple-maven.yaml
- utils/spdx/build.gradle.kts
- utils/spdx/src/main/kotlin/SpdxLicense.kt
- utils/spdx/src/main/kotlin/SpdxLicenseException.kt
> More license and copyright fixes

- helper-cli/src/main/kotlin/utils/PathExcludeGenerator.kt
> PathExcludeGenerator: Misc minor improvements

- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitWorkingTree.kt
Several VCS hosts including GitHub have disabled the use of the
unauthenticated Git protocol, see e.g. [1]. So,
`Git.updateSubmodules()` fails when run with `recursive=true` if at
least one submodule uses the Git protocol blocked by the respective
VCS host.
As result, the experimental scanner fails cloning recursively and
crashes, see [2]. Also the downloader is not capable of cloning
repositories recursively if any of its submodules exhibits that issue.
Work around that by instructing git to re-write the submodule
repository URLs to use `https` instead of `git` as protocol.
[1] https://github.com/heroku/heroku-buildpack-nodejs/issues/959
[2] https://github.com/oss-review-toolkit/ort/issues/5899
Fixes #5899.
> Git: Work around an issue with downloading submodules via Git protocol

- analyzer/src/funTest/assets/projects/synthetic/pub-expected-output-with-flutter-android-and-cocoapods.yml
- analyzer/src/main/kotlin/managers/Pub.kt
See: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#334-oct-05-2022
> Pub: Upgrade bootstrapped Flutter version to 3.3.4

- gradle/libs.versions.toml
- scanner/src/main/kotlin/provenance/PostgresNestedProvenanceStorage.kt
- scanner/src/main/kotlin/provenance/PostgresPackageProvenanceStorage.kt
See: https://github.com/JetBrains/Exposed/blob/master/docs/ChangeLog.md#0401
> Gradle: Upgrade Exposed to version 0.40.1

- model/src/test/kotlin/CompatibilityDependencyNavigatorTest.kt
> CompatibilityDependencyNavigator: Minor improvements

- model/src/main/kotlin/AdvisorRun.kt
- model/src/main/kotlin/AnalyzerRun.kt
- model/src/main/kotlin/ScannerRun.kt
In context of https://github.com/oss-review-toolkit/ort/issues/5681.
> model: Make the KDoc of the `*Run` classes consistent

- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/GitWorkingTree.kt
> Migrate more Git code to JGit

- analyzer/src/funTest/kotlin/managers/PubFunTest.kt
Code redundancy, readability and formatting improvements.
> PubFunTest improvements

- .dockerignore
- integrations/jenkins/Jenkinsfile
> Jenkinsfile: Continue using the legacy Dockerfile for now 

- gradle/libs.versions.toml
See: https://github.com/qos-ch/logback/compare/v_1.4.3...v_1.4.4
> Gradle: Upgrade logback-classic to version 1.4.4

- analyzer/src/main/kotlin/managers/Bundler.kt
> Minor Bundler analyzer improvements

- analyzer/src/main/kotlin/managers/Bundler.kt
> Allow to configure the Bundler version to use

- analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
- analyzer/src/funTest/kotlin/managers/utils/PythonInspectorFunTest.kt
- analyzer/src/main/kotlin/managers/Pip.kt
- analyzer/src/main/kotlin/managers/utils/PythonInspector.kt
> Pip: Get project metadata from python-inspector

- analyzer/src/main/kotlin/managers/Bundler.kt
Most importantly, document the newly added option.
> Bundler: Improve the class docs

- reporter-web-app/src/components/PackageDetails.js
- reporter-web-app/src/models/WebAppPackage.js
> reporter-web-app: Display the authors as part of package details

- downloader/src/main/kotlin/vcs/GitRepo.kt
> Git repo stuff

- model/src/test/kotlin/PackageCurationTest.kt
> Test curations with empty name / version

- scanner/src/main/kotlin/Scanner.kt
> Add some scanning progress information

- clients/scanoss/src/main/kotlin/model/ScanResponse.kt
- scanner/src/main/kotlin/scanners/scanoss/ScanOss.kt
- scanner/src/main/kotlin/scanners/scanoss/ScanOssResultParser.kt
> ScanOSS fixes

- integrations/jenkins/Jenkinsfile
> Expose project and package scanners as Jenkins job parameters

- build.gradle.kts
- clients/clearly-defined/build.gradle.kts
- clients/github-graphql/build.gradle.kts
- clients/nexus-iq/build.gradle.kts
- clients/oss-index/build.gradle.kts
- clients/osv/build.gradle.kts
- clients/scanoss/build.gradle.kts
- clients/vulnerable-code/build.gradle.kts
- utils/spdx/build.gradle.kts
This silences false-positive error messages in IntellJ [1].
[1]: https://youtrack.jetbrains.com/issue/KTIJ-19369
> Gradle: Suppress DSL_SCOPE_VIOLATION

- advisor/src/funTest/kotlin/OsvFunTest.kt
- advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
- analyzer/src/funTest/kotlin/managers/PubFunTest.kt
- helper-cli/src/test/kotlin/PathExcludeGeneratorTest.kt
- utils/test/src/main/kotlin/Utils.kt
> Simplify resolving `File`s in a few places

- analyzer/src/main/kotlin/managers/Sbt.kt
- helper-cli/src/main/kotlin/HelperMain.kt
> Miscellaneous CLI fixes

- helper-cli/src/main/kotlin/commands/packageconfig/CreateCommand.kt
The command already allows specifying non-offending license categories. Allow specifying license IDs in addition to support further use cases. This unlocks new use cases as the user can now specify uncategorized licenses or the SPDX constant NOASSERTION.
> CreateCommand: Allow for specifying non-offending license IDs

- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- model/src/main/kotlin/config/IssueResolution.kt
- model/src/main/kotlin/config/RuleViolationResolution.kt
- model/src/main/kotlin/utils/Extensions.kt
- model/src/test/kotlin/utils/ExtensionsTest.kt
- utils/common/src/main/kotlin/Extensions.kt
- utils/common/src/test/kotlin/ExtensionsTest.kt
- utils/ort/src/main/kotlin/CopyrightStatementsProcessor.kt
> Generalize a function to collapse whitespace

- helper-cli/src/main/kotlin/utils/Extensions.kt
- model/src/main/kotlin/licenses/ResolvedLicense.kt
- model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
- utils/ort/src/main/kotlin/CopyrightStatementsProcessor.kt
- utils/ort/src/test/kotlin/CopyrightStatementsProcessorTest.kt
> Improvements to Copyright handling

- utils/ort/src/main/kotlin/CopyrightStatementsProcessor.kt
> More `CopyrightStatementsProcessor` improvements

- cli/src/funTest/kotlin/OrtMainFunTest.kt
> `OrtMainFunTest` improvements

- downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt
> GitWorkingTreeFunTest: Update expected test results

- utils/ort/src/main/kotlin/CopyrightStatementsProcessor.kt
> CopyrightStatementsProcessor: Further organize code into local functions
