analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-lib-without-repo.yml, analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-lib.yml, analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-root.yml, analyzer/src/funTest/assets/projects/synthetic/project-npm-expected-output.yml, analyzer/src/main/kotlin/Main.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/PIP.kt, model/src/main/kotlin/Package.kt, model/src/main/kotlin/Project.kt, model/src/test/kotlin/PackageTest.kt, scanner/src/funTest/kotlin/HttpCacheTest.kt
We need to track the declared licenses, too. While at it, always
construct projects and packages using named arguments to guards against
introduction / reordering of fields. This also actually fixes occurances
in PIP.kt, Project.kt and PackageTest.kt where the package description and
version fields were swapped.
Change-Id: I880c9df0bce51fac0568e05e256691e77697bd19
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/4)
=> OSS-344: Add a field for declared licenses to projects and packages

downloader/src/main/kotlin/Main.kt
This is already done in download().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/8)
=> downloader: Only call safeMkdirs() on the output directory once

analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/PIP.kt
Instead let the method return AnalyzerResult? and let the PackageManager
class take care of adding it to the result map. This provides better
encapsulation of the result map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/7)
=> PackageManager: Do not pass resolution result to resolveDependencies

downloader/src/main/kotlin/vcs/Git.kt
rev-parse actually returns exit code 128 when run outside of a working
tree. It only returns "false" when run from below the ".git" directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/9)
=> Git: Fix the isApplicableDirectory() check

scanner/src/main/kotlin/Scanner.kt
Even for projects that do not use a package manager we want to be able to
cache scan result files by a unique key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/10)
=> scanner: Fall back to the package hash if the version is empty

.gitmodules, scanner/build.gradle
We really only use this in scanner funcional tests, and do not plan to
use it for analyzer tests anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/14)
=> Move the scancode submodule to the scanner project

scanner/src/main/kotlin/Main.kt, util/src/main/kotlin/ProcessCapture.kt, util/src/main/kotlin/Utils.kt, util/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/18)
=> Add a utility function to split a VCS URL into the base repo and a path 

build.gradle
See https://blog.jetbrains.com/kotlin/2017/11/kotlin-1-1-60-is-out/.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/22)
=> Gradle: Upgrade to Kotlin 1.1.60

README.md, scanner/src/main/kotlin/Main.kt, scanner/src/main/kotlin/Scanner.kt
Add a parameter to set a download-directory to separate downloaded source
code from scan results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/33)
=> scanner: Add parameter --download-directory

appveyor.yml
Esp. in case of test failures we are interested in the results, but
after_test is only called on success, so use on_finish instead. Also see
http://help.appveyor.com/discussions/questions/1479-after_test-not-invoked-when-test-fails
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/39)
=> AppVeyor: Upload test results also in case of test failures

scanner/src/main/kotlin/Scanner.kt
While at it, remove a superfluous call to safeMkdirs() as that is done
inside download() anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/38)
=> Scanner: Do not shadow the downloadDirectory variable

.travis.yml
Still do not run expensive tests when triggered via PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/40)
=> Travis: Run expensive tests when triggered via cron

.travis.yml, appveyor.yml
This speeds up the Maven tests for the price that we will not test if the
implementation works with an empty local repository anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/42)
=> CI: Also cache the local Maven repository

analyzer/src/main/kotlin/managers/Maven.kt
Do not override the function from LocalRepositoryManager. It is not
required for the implementation to work, because it is only used when
adding new artifacts to the repository.
Also the implementation of the function was wrong, it is supposed to return
the path to the artifact relative to the root of the local repository, not
an absolute path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/43)
=> Maven: Do not override getPathForLocalArtifact()

analyzer/src/funTest/kotlin/GradleTest.kt, analyzer/src/funTest/kotlin/MavenTest.kt, analyzer/src/funTest/kotlin/NpmTest.kt, analyzer/src/main/kotlin/Main.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/PIP.kt, downloader/build.gradle, downloader/src/main/kotlin/Main.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/GitRepo.kt, downloader/src/test/kotlin/VersionControlSystemTest.kt
Previously, the call to fromDirectory() and e.g. to a succeeding call to
getRemoteUrl() both needed to get the workingDir passed. With the
intermediate WorkingDirectory class this is not needed anymore as it
stores the workingDir internally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/44)
=> Introduce a class to represent a local VCS working directory

scanner/src/main/kotlin/ArtifactoryCache.kt
Otherwise we might continue using scan results from the local cache
although they have already been deleted from Artifactory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/47)
=> Set a max-age of 0 to have Artifactory validate cached responses

scanner/src/funTest/kotlin/ScanPathTest.kt, scanner/src/main/kotlin/Main.kt, scanner/src/main/kotlin/Scanner.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanCodeTest.kt
Add errors to an extended scan result class so we can parse the errors
at the same time as the licenses to not call readTree() twice on the
native JSON result file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/50)
=> scanner: Do not read the native result file format twice

analyzer/src/funTest/assets/projects/external/directories-expected-output.yml, analyzer/src/main/kotlin/managers/SBT.kt, util/src/main/kotlin/ProcessCapture.kt
Extend getCommandVersion() to be able to receive multiple
space-separated arguments to we can additionally pass
"-Dsbt.log.noformat=true" to sbt. At least for Windows, this argument
needs to be quoted currently because of
https://github.com/sbt/sbt/issues/2695
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/57)
=> Ensure sbt does not produce ANSI output so matching works corrently

analyzer/src/main/kotlin/managers/SBT.kt
This breaks on Linux otherwise, which went unnoticed by CI due to
another problem with calling System.exit() as part of MainTest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/59)
=> SBT: Only quote sbt.log.noformat on Windows

analyzer/src/main/kotlin/managers/Gradle.kt
Change matcher for gradle projects, so it matches custom build files names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/53)
=> Gradle: add settings.gradle to glob patterns of definition files

analyzer/src/funTest/kotlin/MainTest.kt, analyzer/src/main/kotlin/Main.kt, analyzer/src/main/kotlin/PackageManagerFactory.kt
Add a test to only enable "Gradle" to ensure it is not called "GRADLE"
in the console output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/60)
=> analyzer: Only convert the package manager name to upper case for comparison

downloader/src/main/kotlin/vcs/Git.kt
This avoid an IOException during the real check in case the working
directory does not exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/66)
=> Git: Exit early in isValid() if the working directory does not exist

util/src/main/kotlin/Utils.kt, util/src/test/kotlin/UtilsTest.kt
SSH URLs, which are always authenticated, must not be turned into HTTPS
URLs as that avoids private GitHub repositories to be scanned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/68)
=> util: Correctly handle GitHub SSH URLs

detekt.yml
Add exceptions for the valid use cases, because it is not possible to
annotate import statements with @Suppress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/73)
=> Detekt: Enable WildcardImport rule

util/src/main/kotlin/ProcessCapture.kt
`File.createTempFile` fun requires prefix with minimum length of 3. 
Current implementation fails for shorter commands (ex. Mercurial's `hg`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/77)
=> ProcessCapture: use min 3 chars length prefix when creating tmp files

analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-lib-without-repo.yml, analyzer/src/main/resources/init.gradle
Collect the messages from all exception causes for resolution errors. This
simplifies debugging as usually the most helpful message is in the root
cause.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/108)
=> Gradle: Also show exception causes in error messages

util/src/test/kotlin/UtilsTest.kt
This is the drive letter separator on Windows and must not be used
literally in a file name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/123)
=> UtilsTest: Also test to encode ":" properly

analyzer/src/main/resources/init.gradle
Project dependencies in Gradle can be circular which caused a stack overflow
in the recursive parseDependency method. To fix it do not continue building
the dependency tree when a dependency was already seen on the same branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/124)
=> Gradle: Guard against circular dependencies

analyzer/src/main/kotlin/MavenSupport.kt, gradle.properties, util/build.gradle, util/src/main/kotlin/DiskCache.kt
Store remote artifact information in a disk cache backed by
DiskLruCache [1]. This brings a big performance boost for Gradle, Maven
and SBT dependency resolution.
The cached metadata contains the URLs and checksums of Maven artifacts which
is retrieved without actually downloading the remote artifacts. This is
information which is not available from the local Maven repository,
especially without downloading the remote artifacts.
Currently the max cache size is hardcoded to 1GB and expiry to six hours,
this will be made configurable in a later commit.
[1] https://github.com/JakeWharton/DiskLruCache
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/122)
=> MavenSupport: Add cache for remote artifacts

.travis.yml
If functional tests execute a code path which calls exitProcess() the
JVM running the tests is terminated, shadowing any upcoming failing
tests. Fail CI builds if such a case is detected by checking that the
line following
[...] > GradleLoggingSubprojectTest.analyzer produces ABCD files
for all .gradle files STARTED
does not start wirh ":" like in
:analyzer:testPicked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/131)
=> Travis: Add a crude check for aborted tests

analyzer/src/funTest/assets/projects/external/directories-expected-output.yml, analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml, analyzer/src/funTest/assets/projects/external/gradle-submodules/logging/expected-logging-integration-test-build-src-dependencies.yml, analyzer/src/funTest/assets/projects/external/gradle-submodules/logging/expected-logging-integration-test-dependencies.yml, analyzer/src/funTest/assets/projects/external/gradle-submodules/logging/expected-logging-integration-test-multi-threaded-dependencies.yml, analyzer/src/funTest/assets/projects/external/gradle-submodules/logging/expected-logging-integration-test-nested-build-build-src-dependencies.yml, analyzer/src/funTest/assets/projects/external/gradle-submodules/logging/expected-logging-integration-test-nested-build-dependencies.yml, analyzer/src/funTest/assets/projects/external/gradle-submodules/logging/expected-logging-integration-test-project1-dependencies.yml, analyzer/src/funTest/assets/projects/external/gradle-submodules/logging/expected-logging-integration-test-project2-dependencies.yml, analyzer/src/funTest/assets/projects/external/gradle-submodules/wrapper/expected-wrapper-gradle-dependencies.yml, analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-expected-output.yml, analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-root.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-lib.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-root.yml, analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml, analyzer/src/funTest/kotlin/GradleTest.kt, analyzer/src/funTest/kotlin/MavenTest.kt, analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt, downloader/src/main/kotlin/Main.kt, model/src/main/kotlin/Package.kt, model/src/main/kotlin/Project.kt
Extend Projects and Packages to contain all processed VcsInfo, not just
the normalizedVcsUrl.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/132)
=> Store all processed VcsInfo instead of only a normalizedVcsUrl

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/133)
=> Travis: Enable pipefail to avoid tee shadowing gradlew's exit code

analyzer/src/main/kotlin/Main.kt, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/test/kotlin/PackageManagerTest.kt
This reduces the complexity of the main method and makes it possible to
test the code in isolation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/134)
=> analyzer: Move code to discover package manager files to PackageManager

utils/src/main/kotlin/ProcessCapture.kt
Resolves an issue where if a tool's version doesn't include a patch then then OSS Review Toolkit is unable to determine if there tool version requirement has been met.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/130)
=> Fix issue #129

Dockerfile
This adds a Dockerfile that allows the ORT scripts to be run inside a container (to avoid having to install dependencies such as a JDK) on the host.
Ideally, the oss-review-toolkit team would build the image and publish it to DockerHub so consumers don't need to clone the repository and build the image themselves. Let me know if you'd like me to help this out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/141)
=> Enable running ORT in a Docker container

appveyor.yml
We are already uploading the XML files, which should be enough to track
down test failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/149)
=> AppVeyor: To safe some time and storage, do not archive the build reports

analyzer/src/main/kotlin/MavenSupport.kt
To not clutter stdout, do not print the stack trace (not even with
--stacktrace) if an artifact failed to download from a single
repository, because running into such exceptions is completely fine if
the artifacts succeeds to download from a repository further down the
list.
So only put any exception's message into the debug log, and only warn if
the artifact failed to download from all repositories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/148)
=> MavenSupport: Do print the stack trace if an artifact failed to download

analyzer/build.gradle, gradle.properties
Turns out they do come in pairs (unlike assumed in 5c0744d), but the
tooling API artifact is (now) published at repo.gradle.org, not at
JCenter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/151)
=> Gradle: Sync the tooling API version with the main version again

utils/src/main/resources/logback.xml
We currently only use a single "main" thread and a single logger, so
this information is all the same. Remove it to get shorter logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/153)
=> logback: Remove the thread and logger names from the pattern

analyzer/src/main/kotlin/MavenSupport.kt
Otherwise the log gets too cluttered the the repo's id, content type,
policy etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/152)
=> MavenSupport: Only print the repo URLs if an artifact could not be found

downloader/src/main/kotlin/vcs/Git.kt
To also match e.g.
git version 2.15.1-271-g1a4e40aa5dc
or
git version 2.4.9 (Apple Git-60)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/164)
=> Git: Relax the version pattern

analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
To benefit from URL normalization. This fixes a breakage in expensive
tests run by Travis CRON.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/167)
=> AbstractIntegrationSpec: Use processed VCS information as the actual data

build.gradle
This fixes an annoying warning on Windows:
https://github.com/arturbosch/detekt/issues/630
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/174)
=> Upgrade detekt to version 1.0.0.RC6-1

analyzer/src/funTest/kotlin/MainTest.kt, analyzer/src/funTest/kotlin/NpmTest.kt, analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt, analyzer/src/main/kotlin/MavenSupport.kt, analyzer/src/main/kotlin/managers/PIP.kt, downloader/src/funTest/kotlin/DirectoryTest.kt, downloader/src/funTest/kotlin/DownloaderTest.kt, downloader/src/funTest/kotlin/MercurialTest.kt, downloader/src/funTest/kotlin/SubversionTest.kt, downloader/src/main/kotlin/Main.kt, downloader/src/test/kotlin/ArchiveUtilsTest.kt, downloader/src/test/kotlin/GitTest.kt, downloader/src/test/kotlin/MercurialTest.kt, downloader/src/test/kotlin/SubversionTest.kt, scanner/src/funTest/kotlin/HttpCacheTest.kt, scanner/src/funTest/kotlin/ScanPathTest.kt, utils/src/test/kotlin/UtilsTest.kt
Warn if files could not be deleted, except for NPM where an IOException
is thrown if our node_modules directory could not be deleted, and except
test which do not depend on the logger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/182)
=> Alignments about creating / deleting temporary files / directories

analyzer/src/main/kotlin/managers/NPM.kt
When the remote package information does not contain an entry for the
specific version of the package, fall back to using the information from
the local package.json. Before this resulted in a NullPointerException.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/184)
=> NPM: Fall back to package.json when no remote version info is available

downloader/src/main/kotlin/vcs/Git.kt
Otherwise only tags reachable from branches are fetched.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/191)
=> Git: When fetching everything, also fetch all tags

analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/PackageManagerFactory.kt
This handles cases like in https://github.com/wireservice/csvkit.
/cc @haikoschol 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/190)
=> PackageManager: Support multiple matches of a single glob in a directory

analyzer/src/main/kotlin/Main.kt
Do not fail writing results if the output directory cannot be created
because it already exists due to previously generated results. This can
happen as we now support multiple definition files of the same package
manager in a single directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/194)
=> analyzer: Do not fail when writing multiple results per directory

analyzer/src/main/kotlin/managers/PIP.kt
To check here for "requirements.txt"-like, simply check for not being
a "setup.py". That works as that is (currently) the only other supported
PIP definition file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/195)
=> PIP: Do not hard-code "requirements.txt" in conditional

downloader/src/funTest/kotlin/GitTest.kt, downloader/src/funTest/kotlin/MercurialTest.kt
This is a follow-up to aa01230. As the implementation of
File.compareTo() is OS-specific, ensure to always sort by the path
string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/196)
=> downloader: Fix sorting of files in tests, again

downloader/src/funTest/kotlin/MercurialTest.kt, downloader/src/main/kotlin/vcs/Mercurial.kt
The extension for sparse checkouts is only available starting with
Mercurial 4.3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/197)
=> MercurialTest: Disable sparse checkout tests on versions below 4.3

analyzer/src/main/kotlin/managers/PIP.kt
The underlying createTempFile() requires at least 3 chars. Otherwise the
call would fail e.g. for a directory called "ci".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/201)
=> PIP: Ensure the temporary virtualenv directory name prefix length

downloader/src/funTest/kotlin/DownloaderTest.kt, downloader/src/main/kotlin/Main.kt
Some VCS implementations create files/directories in the target directory (i.e. `.git`) which probably should be cleaned up in this case, since they contain inaccurate information that might otherwise be picked up elsewhere.
IMHO this should be done either in subclasses' implementation of `VersionControlSystem.download()` or in a separate `cleanup` method that has an empty implementation in the base class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/204)
=> Fall back to source package when VCS download fails

analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/npm-babel/package-lock.json, analyzer/src/funTest/assets/projects/synthetic/npm-babel/package.json, analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml, analyzer/src/funTest/kotlin/BabelTest.kt, analyzer/src/funTest/kotlin/NpmTest.kt, analyzer/src/main/kotlin/managers/NPM.kt, model/src/main/kotlin/VcsInfo.kt, model/src/test/kotlin/VcsInfoTest.kt
Merging VCS information is implemented for NPM first to demonstrate the idea. When this PR is merged, I'll add merging of VCS information also for the other package managers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/206)
=> Merge VCS information, esp. after calling splitUrl(), to support Babel-like projects

analyzer/src/funTest/kotlin/BabelTest.kt, analyzer/src/funTest/kotlin/NpmTest.kt
Instead of catching and re-throwing the exception.
=> analyzer: Clean up "node_modules" in tests in "finally"

utils/src/main/kotlin/Utils.kt
To make more clear that the trailing dot does not belong to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/209)
=> Utils: Quote the path in File.safeMkdirs()

appveyor.yml
"assemble" is doing too much, like building docs, which is cluttering
the CI log output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/212)
=> AppVeyor: Execute the "classes" task instead of "assemble"

model/src/main/kotlin/VcsInfo.kt, model/src/test/kotlin/VcsInfoTest.kt
Assign empty strings to fields of VcsInfo if they are missing in the
serialized form.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/221)
=> VcsInfo: Support deserialization from incomplete data

README.md, analyzer/src/main/kotlin/Main.kt, downloader/src/main/kotlin/Main.kt, graph/src/main/kotlin/Main.kt, scanner/src/main/kotlin/Main.kt, utils/src/main/kotlin/Utils.kt
Sort the parameters in this order for all tools:
1) Mandatory parameters
2) Optional parameters
3) Logging related parameters
4) Help parameters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/226)
=> Improve ordering of command line parameters

analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/NPM.kt
This makes the logic reusable by other package managers. The logic
itself it still the same, only a redundant let() call was removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/228)
=> analyzer: Move logic to process VcsInfo from NPM to PackageManager

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml, analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-root.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-lib.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-root.yml, analyzer/src/funTest/kotlin/GradleTest.kt, analyzer/src/funTest/kotlin/MavenTest.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/PIP.kt
Unprocessed VCS information should not fall back to using the working
tree as there might be local / unpublished changes, or the clone might
have happened from a fork.
Instead of removing the code to patch expected results completely, just
deactivate it by using a pattern that is not yet matched. This way we can
make use of the code again in a follow-up commit that aligns merging of
package VCS information to how it is already done for NPM also for the
remaining package managers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/229)
=> analyzer: Consistently take project VCS information only from the package

analyzer/src/funTest/assets/projects/external/directories-expected-output.yml, analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-expected-output.yml, analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-root.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-lib.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-root.yml, analyzer/src/funTest/kotlin/MavenTest.kt, analyzer/src/main/kotlin/Main.kt, analyzer/src/main/kotlin/MavenSupport.kt, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/PIP.kt
Use the functions from PackageManager to process VcsInfo when creating
projects and packages in all package managers. Also consistently only
assign raw data coming from the package manager to the "vcs" field, and all
deduced data to the "vcsProcessed" field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/231)
=> analyzer: Align processing of VcsInfo for all package managers

analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml, analyzer/src/main/kotlin/managers/NPM.kt
/cc @jeffmcaffer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/242)
=>  Add a work-around for getting the source code of TypeScript definitions

analyzer/src/main/kotlin/Main.kt, analyzer/src/main/kotlin/MavenSupport.kt, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/NPM.kt, downloader/src/main/kotlin/Main.kt, downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/GitRepo.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, downloader/src/main/kotlin/vcs/Subversion.kt, graph/src/main/kotlin/Main.kt, scanner/src/main/kotlin/Main.kt, scanner/src/main/kotlin/Scanner.kt, utils/src/main/kotlin/Utils.kt
Previously, if the scanner command line tool was calling the downloader
library programatically, a --stacktrace parameter to the scanner was not
passed to the downloader, and the downloader library code would not have
printed any stack traces as its own "Main.stacktrace" variable was still
the default of "false". Solve that by introducing a globally shared
"printStackTrace" variable that gets toggled by each of the Main entry
points.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/244)
=> Make the --stacktrace parameter globally available

.travis.yml, scanner/src/funTest/kotlin/ScanPathTest.kt, utils-test/src/main/kotlin/TestTags.kt
Because it is used to specifically disable the ScanCode test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/247)
=> Rename ScanPathTag to ScanCodeTag

analyzer/src/main/resources/init.gradle
Currently dependencies in flat dir repositories [1] cannot be handled.
Add an error message to the analyzer result if a project uses a flat dir
repository.
[1] https://docs.gradle.org/4.4.1/userguide/dependency_management.html#sec:flat_dir_resolver
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/251)
=> Gradle: Add an error message when a project uses a flat dir repository

downloader/src/main/kotlin/VersionControlSystem.kt
When guessing the tag for a version allow suffixes to version names in tag
names, similar to how prefixes were already allowed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/266)
=> VCS: Allow suffixes to version names in tag names when guessing tags

utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/269)
=> Fixup scp-like Git URLs that do not use a ':' after the server part

analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml, analyzer/src/main/kotlin/MavenSupport.kt, utils/src/main/kotlin/Utils.kt
The SCM plugin returns bogus VCS URLs that do not start with ":" as ":"
is also used as the delimiter in SCM connection strings, see
https://maven.apache.org/scm/cvs.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/270)
=> Fixup CVS URLs returned by the Maven SCM plugin

utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/UtilsTest.kt
This reverts commit b741dd3 as it breaks SSH URLs with ports. Add a test
on top of the revert.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/271)
=> Revert "normalizeVcsUrl: Simplify the regex to fixup scp-like URLs bit"

utils/src/test/kotlin/UtilsTest.kt
This is a fixup for 47a3c50.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/272)
=> UtilsTest: Add a user name to the Gerrit URL to really make it authenticated

analyzer/src/main/kotlin/managers/NPM.kt
Run "npm/yarn install" with the "--ignore-scripts" option [1][2]. This
prevents the execution of any build scripts of the node.js project or its
dependencies. Execution arbitrary scripts is a security issue and also has
a high risk of failing, e.g. because the scripts could try to compile
native code.
[1] https://docs.npmjs.com/cli/install#description
[2] https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-scripts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/273)
=> NPM: Add --ignore-scripts option to install

Dockerfile
ScanCode bundles an old version of libmagic that has crashed in some of our scans. This is a workaround until https://github.com/nexB/scancode-toolkit/issues/907 has been fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/274)
=> Docker: Install libmagic and the associated database file

analyzer/src/funTest/assets/projects/external/directories-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml, analyzer/src/funTest/kotlin/BabelTest.kt, analyzer/src/funTest/kotlin/NpmTest.kt, analyzer/src/main/kotlin/PackageManager.kt
Prefer the VCS info from the project directory over VCS info parsed from the
projects metadata. The metadata could be different to the actually cloned
project which would lead to unexpected results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/275)
=> analyzer: Prefer VCS info from directory for projects

analyzer/src/funTest/assets/projects/external/directories-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-lib.yml, analyzer/src/main/kotlin/MavenSupport.kt
If "tag" is unspecified Maven uses "HEAD" by default, no matter whether
"HEAD" actually is understood by the referred SCM, if any. To be
SCM-agnostic use an empty string here instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/287)
=> MavenSupport: Never return "HEAD" for "tag"

.travis.yml, appveyor.yml, scanner/src/funTest/kotlin/ScanPathTest.kt
While running Licensee is much faster than running ScanCode, installing
Licensee takes at least a minute due to building the native extension
dependencies. So only install and run Licensee if we enable expensive
tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/290)
=> Also make the Licensee ScanPathTest expensive

downloader/src/funTest/kotlin/CvsDownloadTest.kt, downloader/src/funTest/kotlin/GitDownloadTest.kt, downloader/src/funTest/kotlin/MercurialDownloadTest.kt, downloader/src/funTest/kotlin/SubversionDownloadTest.kt, downloader/src/main/kotlin/Main.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Cvs.kt, downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/GitRepo.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, downloader/src/main/kotlin/vcs/Subversion.kt, utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/UtilsTest.kt
Some repositories contain the source code to e.g. multiple NPM packages.
Individual package releases are then typically marked with tags whose
names are prefixed with the package name. Support finding such tags by
passing along the package name to VersionControlSystem.download().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/292)
=> Support guessing revisions in multi-project repos based on project tags

downloader/src/main/kotlin/Main.kt
Otherwise there is no way to tell if the download was successful if the
downloader was start programmatically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/296)
=> downloader: Exit with code 1 if the download failed

scanner/src/main/kotlin/Scanner.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt
There are cases, like for ScanCode, where we point to directories to
keep.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/316)
=> scanner: Do not automatically delete the bootstrap directory

model/src/main/kotlin/PackageReference.kt
The property was never used to create directories which was the main reason
to have a normalized name. The only usage was to build the identifier
string. This broke PackageReference.dependsOn(pkg: Package) because the
package identifer does not use a normalized name. As a result packages
were often not assigend to the correct scopes in the scan summary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/320)
=> PackageReference: Remove property normalizedName

downloader/src/test/kotlin/CvsTest.kt
SourceForge seems to have some permission problems that read-only locks
cannot be created on the server side.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/325)
=> downloader: Temporarily disable CVS tests that require online access

analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml, analyzer/src/main/kotlin/managers/NPM.kt
Some old NPM packages use deprecated ways to declare their license [1].
[1] https://docs.npmjs.com/files/package.json#license
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/324)
=> NPM: Support deprecated license declaration syntaxes

analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/maven-parent-expected-output-root.yml, analyzer/src/funTest/assets/projects/synthetic/maven-parent/pom.xml, analyzer/src/funTest/kotlin/MavenTest.kt, analyzer/src/main/kotlin/MavenSupport.kt, analyzer/src/main/kotlin/managers/Maven.kt
Populate all ProjectBuildingRequests with the Maven default values by using
the MavenExecutionRequestPopulator. This better aligns the tool with the
behavior of Maven.
The main reason for this is that it adds the default Maven central
repository to the remote repositories of the request. This is important for
projects that use a parent POM from the central repository because it could
otherwise not be resolved. Usually the remote repository for a parent POM
would have to be defined in the POM itself, the only exception is if the
parent POM comes from Maven central, because this repository is always used
by Maven.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/3 …
=> Maven: Use the Maven defaults when building a project

utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/UtilsTest.kt
The SVN client actually requires the prefix; it cannot clone from "pure"
ssh URLs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/332)
=> utils: Do not strip svn+ prefix from Subversion URLs

analyzer/src/main/kotlin/managers/SBT.kt
The name of the generated POM might be different from the Scala project
directory name as the project name might have been set programatically.
So just check if any POM was generated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/333)
=> SBT: Relax the existence check for generated POMs

analyzer/src/main/kotlin/managers/SBT.kt
Allow the POM to be in any sub-directory of the "target" directory. This
is because there might by intermediate directories that denote the used
Scala version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/334)
=> SBT: Relax the POM existence check even further

analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt, analyzer/src/funTest/kotlin/integration/GradleIntegrationTest.kt, analyzer/src/funTest/kotlin/integration/VueJsIntegrationTest.kt, downloader/src/funTest/kotlin/BabelTest.kt, downloader/src/funTest/kotlin/BeanUtilsTest.kt, downloader/src/funTest/kotlin/DownloaderTest.kt, downloader/src/main/kotlin/Main.kt, scanner/src/main/kotlin/Scanner.kt
Instead of only returning the download directory let the download function
also return information about what was downloaded. This is described by
either the VcsInfo if the source was downloaded from a VCS or the
RemoteArtifact if a source artifact was downloaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/342)
=> downloader: Return DownloadResult from download function

analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml
The Maven repository http://jasperreports.sourceforge.net/maven2 is not
available anymore, so revert this change.
This reverts commit 16d200aaac756785f8c5fdc581eb1ea8fec69870.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/347)
=> Revert "Maven: Fix expected results for jgnash-core"

scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/Main.kt, scanner/src/main/kotlin/Scanner.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt
Move all code that is only required for local scanners to the new
LocalScanner class. Also change the scan() method in Scanner to take a list
of packages. This allows the Scanner implementation to decide if they are
process in serial order or in parallel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/345)
=> scanner: Prepare for integrating remote scanners

downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Cvs.kt, downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/GitRepo.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, downloader/src/main/kotlin/vcs/Subversion.kt
Add a new property "aliases" which is a list of strings and use it to
generalize the implementation of isApplicableType, because they all work
basically the same way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/350)
=> VersionControlSystem: Generalize isApplicableType

scanner/src/main/kotlin/Main.kt
Instead of merging the lists of declared and detected licenses add separate
entries for each of them to the SummaryEntry class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/351)
=> scanner: Add separate fields for declared and detected licenses

analyzer/src/main/kotlin/MavenSupport.kt
This avoids duplicates as visible in warning logs like
WARN  - Unable to find 'artifact' in any of [https://repo.maven.apache.org/maven2, ..., https://repo.maven.apache.org/maven2].
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/361)
=> MavenSupport: De-duplicate the list of all repositories

analyzer/src/funTest/assets/projects/external/directories-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml, analyzer/src/main/kotlin/MavenSupport.kt
When asking Maven for the SCM URL of a POM that does not itself define an SCM URL, Maven returns the SCM URL of the parent POM (if any) and appends the child POM's artifactId to it. This behavior is fundamentally broken because it invalidates the URL for many SCMs that cannot clone / checkout a specific path from a repository. Also, the assumption that the source code for a child artifact is stored in a top-level directory named like the artifactId inside the parent artifact's repository is often not correct.
To fix this, determine the SCM URL of the root parent (if there are parents) and use that as the child's SCM URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review- …
=> Maven: Remove paths appended to SCM URLs by Maven

analyzer/src/main/resources/META-INF/plexus/components.xml
This enables parsing of POM files that use "zip" packaging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/366)
=> Maven: Add an empty lifecycle mapping for "zip" packaging

build.gradle
See https://blog.jetbrains.com/kotlin/2018/03/kotlin-1-2-30-is-out/.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/373)
=> Gradle: Upgrade Kotlin to version 1.2.30

analyzer/src/main/resources/init.gradle
This should avoid the
IllegalArgumentException: java.lang.String is not an interface
error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/375)
=> analyzer: Convert GStrings to plain Strings in two more missing places

analyzer/src/main/resources/init.gradle
Ivy repositories are not yet supported by the analyzer. Print a more
specific error message if they are used in a Gradle project. Also improve
the error message for flat dir repositories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/376)
=> Gradle: Improve the error message for Ivy repositories

downloader/src/funTest/kotlin/SubversionDownloadTest.kt
Because SourceForge still has connectivity problems due to its data
center migration.
This is a follow-up for 4a9b185.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/377)
=> downloader: Temporarily disable tests that depend on SourceForge

analyzer/src/main/kotlin/managers/NPM.kt
Circular dependencies are common in NPM, so instead of printing a warning
for them make it a debug message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/383)
=> NPM: Make the warning about circular dependencies a debug message

utils/src/main/kotlin/DiskCache.kt
On Windows, where open files cannot be deleted, this had caused many
errors about "unreadable" cache entries being logged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/387)
=> DiskCache: Do not try to remove keys before closing the snapshot

scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanCodeTest.kt
This allows for a more compact display of timeout errors in the scan
summary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/390)
=> scanner: Map ScanCode timeout errors simiarly to memory errors

scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanCodeTest.kt
Otherwise results retrieved from the cache do not get mapped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/392)
=> scanner: Map ScanCode error messages as part of getResult()

downloader/src/funTest/kotlin/CvsDownloadTest.kt, downloader/src/test/kotlin/CvsTest.kt
According to
https://sourceforge.net/p/forge/site-support/16554/
CVS repositories should be up again. SVN repositories do not seem to be
(yet).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/396)
=> downloader: Enable CVS tests again that were disabled due to SF's outage

scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanCodeTest.kt
The first line with the scanner name seems to be optional. So remove the
scanner name from the mapped error message altogether, which also avoids
duplicate errors if e.g. both the license and the copyright scanner timed
out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/397)
=> scanner: Remove the scanner name from mapped ScanCode error messages

analyzer/src/main/kotlin/managers/Gradle.kt
The exception will be catched in PackageManager.resolveDependencies() which
also creates a valid AnalyzerResult. Also catching it in the Gradle class
is duplicated code which in this case also was less functional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/411)
=> Gradle: Do not catch BuildException in parseDependencies()

scanner/src/main/kotlin/scanners/ScanCode.kt
Otherwise, if only files with findings are included, and we have a
"files_count" of "0", we do not know whether really no files have been
scanned (e.g. due to a bug) or simply no files contained any findings.
Note that our internal Scanner Results will still only contain files
with findings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/410)
=> ScanCode: Include all scanned files in the native output file

downloader/src/funTest/kotlin/SubversionDownloadTest.kt, downloader/src/main/kotlin/vcs/Subversion.kt
As in Subversion tags are not symbolic names for revisions but paths
inside the repository, we must not specify tags as revisions but as
paths. Add this special path handling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/412)
=> downloader: Fix downloading of Subversion tags

analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app-3.3.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app-3.4.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml, analyzer/src/main/resources/init.gradle
Ignore configurations ending on "Classpath" because these represent the
classpaths for their respective configurations, e.g. "compileClasspath" is
the classpath for the "compile" configuration [1].
This removes a lot of duplication from the results and especially helps
with Android projects where the classpath configurations often cannot be
resolved when they contain dependencies to Android library projects which
have multiple variants. This leads to errors like this:
"ResolveException: Could not resolve all dependencies for configuration
':lib:...Classpath'. Caused by: AmbiguousVariantSelectionException: More
than one variant of project :lib matches the consumer attributes."
[1] https://discuss.gradle.org/t/sourcesets-main-compileclasspath-vs-configurations-compile/6782
---
This change …
=> Gradle: Ignore classpath configurations

analyzer/src/main/resources/init.gradle
Replace "project :" with "project _" in project dependencies, otherwise the
colon messes up the identifier of the dependency because it uses the colon
as a separator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/418)
=> Gradle: Always replace the colon in the display name of project dependencies

downloader/src/main/kotlin/Main.kt
Previously if a package had a blank version the source was downloaded to
the directory "outputDir/packageName" while packages with a version were
downloaded to the directory "outputDir/packageName/version". To remove this
inconsistency use "unknown" as the version if the package version is blank.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/421)
=> downloader: Use "unknown" for the version if a package has a blank version

downloader/src/main/kotlin/Main.kt
Catch the IllegalArgumentException that occurs if the target ZIP file for a
package already exists. This can happen if there are a project and a
package with the same identifier in the dependencies file, or if the
output directory was not cleaned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/428)
=> downloader: Do not abort if a package cannot be archived

analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-root.yml, analyzer/src/main/resources/init.gradle
If a project does not define a version Gradle returns the default value
"unspecified". Replace this with the empty string to not have to handle
"unspecified" in the rest of the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/434)
=> Gradle: Replace "unspecified" version with empty string

downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Cvs.kt, downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, downloader/src/main/kotlin/vcs/Subversion.kt
If multiple matching tags are found for a version fail instead of taking
the first one. This helps preventing false positives for example if a
repository contains multiple projects where each project has its own set of
release tags (like "project-a-1.0" and "project-b-1.0").
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/436)
=> VCS: Fail if multiple matching tags for a version are found

.travis.yml, appveyor.yml, scanner/src/funTest/kotlin/ScanPathTest.kt, scanner/src/main/kotlin/scanners/Licensee.kt
This way we do not need to hard-code installation for scheduled CI
builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/439)
=> Bootstrap Licensee

model/src/main/kotlin/MergedAnalyzerResult.kt
Without this the MergedAnalyzerResult cannot be deserialized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/449)
=> MergedAnalyzerResult: Add missing key deserializer for the errors map

analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml, analyzer/src/main/kotlin/managers/PIP.kt
This change requires a modified version of pydep, which includes the
fields "license" and "classifiers" from setup.py files in its output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/451)
=> PIP: Read "declared licenses" from Python packages

downloader/src/main/kotlin/Main.kt, scanner/src/main/kotlin/LocalScanner.kt, utils/src/main/kotlin/Utils.kt
This change extracts `String.encodeOrUnknown()` from the downloader to utils and calls it in the scanner as well, when constructing the path to result files.
The issue this fixes came up when testing the toolkit with Go projects, where import paths are used as package names (e.g. `k8s.io/apiserver`). The scanner would then expect a directory `scanResults/k8s.io` to exist and fail to write the result file there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/456)
=> scanner: Encode paths to scan result files

settings.gradle
The issue with the broken POM has been resolved with dokka 0.9.16 which
is what we are using now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/457)
=> Gradle: Remove the customized plugin repository order

analyzer/src/main/kotlin/managers/PIP.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/464)
=> Fix running pipdeptree by pinning the pip version

docs/README.md
This is a fixup for 57eb2b8.
Resolves #463.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/465)
=> README: Fix relative links now that the README lives in "docs"

scanner/src/main/kotlin/LocalScanner.kt
It is a bit weird to first use wrong values in order to map them
immediately. Instead, associate to the right values from the start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/462)
=> LocalScanner: Improve readability of scan()

scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt
As of 6d49505 local scanner implementations need to implement the
"scannerExe" property instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/466)
=> scanner: Remove the unused "executable" argument from getVersion()

analyzer/src/main/resources/init.gradle
As Groovy has no "firstOrNull()", use "?.find { true }" instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/470)
=> Gradle: Guard against resolvedComponents being empty

analyzer/src/main/kotlin/MavenSupport.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/473)
=> MavenSupport: Avoid the repo URL being used as part of the metadata file name

model/src/main/kotlin/ScannerDetails.kt, scanner/src/funTest/kotlin/HttpCacheTest.kt, scanner/src/main/kotlin/ArtifactoryCache.kt, scanner/src/main/kotlin/ScanResultsCache.kt
When looking up results from the cache allow the version of the scanner to
differ in the patch, suffix, and build parts, but not in the major or
minor parts. This way the scan results can be reused if there are no
significant changes between the used scanner versions, assuming the scanner
uses semantic versioning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/472)
=> scanner: Allow small versions diffs when looking up results from the cache

.gitattributes, analyzer/src/funTest/assets/.gitattributes
Previously, the newly added file at
model/src/test/assets/expected-scan-results.yml
was not matched. Also remove the entry for "txt" files as there are none
anymore.
This fixes a potential test failure in "ScanResults should serialize as
expected" on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/478)
=> Ensure LF line endings for all expected results files

analyzer/src/main/resources/init.gradle
Provide default values for properties of DependencyImpl that are expected
to be non-null in the Kotlin code.
This fixes a regression introduced in 5f8dee7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/481)
=> Gradle: Provide default values for properties of DependencyImpl

build.gradle, gradle.properties
See https://blog.jetbrains.com/kotlin/2018/04/kotlin-1-2-40-is-out/
Note that kotlin-stdlib-jre* were deprecated in favor of
kotlin-stdlib-jdk*.
Also upgrade a few dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/483)
=> Gradle: Upgrade Kotlin and other dependencies

model/src/main/kotlin/Provenance.kt, scanner/src/funTest/kotlin/HttpCacheTest.kt, scanner/src/main/kotlin/ArtifactoryCache.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/ScanResultsCache.kt
When reading the scan results for a package also verify that the provenance
of the scan result matches the sourceArtifact, vcs, or vcsProcessed fields
of the package. Otherwise wrong scan results could be returned if different
revisions of a package using the same version name were scanned.
If the vcs info of a package only contains symbolic names the scanned
revision could be wrong if the symbolic name is changed to point to another
commit. This could be improved by resolving the symbolic name already in
the analyzer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/474)
=> scanner: Also check the provenance of a cached scan result

model/src/main/kotlin/Provenance.kt
Otherwise e.g. "git" and "Git" would not be recognized as equal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/496)
=> model: Ignore case when comparing the VCS type in Provenance.matches()

downloader/src/main/kotlin/Main.kt, model/src/main/kotlin/Provenance.kt, scanner/src/funTest/kotlin/HttpCacheTest.kt, scanner/src/main/kotlin/LocalScanner.kt
Record the original VCS info in the Provenance class. This is important if
the original VCS info does not have a revision or the revision cannot be
downloaded, and the downloader detects the revision for example by
searching for a tag matching the version of the package. Without storing
the original VCS info there would be no way to find out that the Provenance
matches the package without downloading the source code and detecting the
revision again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/497)
=> Record original VCS info in Provenance

analyzer/src/funTest/assets/projects/external/directories-expected-output.yml, analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml, analyzer/src/funTest/assets/projects/external/godep-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-expected-output.yml, analyzer/src/funTest/assets/projects/external/qmstr-expected-output.yml, analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml, analyzer/src/funTest/assets/projects/external/sprig-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app-2.14.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app-3.4.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-root.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-expected-output-unsupported-version.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-app.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-lib.yml, analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-root.yml, analyzer/src/funTest/assets/projects/synthetic/maven-parent-expected-output-root.yml, analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml, downloader/src/funTest/kotlin/BabelTest.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/test/kotlin/VersionControlSystemTest.kt, model/src/main/kotlin/VcsInfo.kt
To have more consistent VCS types. Also adapt the default value for type in
VersionControlSystem.splitUrl() accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/498)
=> model: Convert the VCS type to lower case in VcsInfo.normalize()

analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml, analyzer/src/funTest/assets/projects/synthetic/gradle/curations.yml, analyzer/src/funTest/kotlin/MainTest.kt
Compare the full analyzer results file in "Package curation data file is
applied correctly" because it requires less code and makes it easier to
view the diff if the test fails.
Also align the test code with "Merging into single results file creates
correct output".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/506)
=> analyzer: Improve testing of curations in MainTest

analyzer/src/funTest/assets/projects/synthetic/pip-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/pip/requirements.txt, analyzer/src/funTest/assets/projects/synthetic/pip/setup.py, analyzer/src/funTest/kotlin/PipTest.kt, analyzer/src/main/kotlin/managers/PIP.kt
So far only one "definition file" per package manager is considered. So if there is a requirements.txt, setup.py is ignored. With this change pydep is always run to read the metadata from setup.py, even when the package manager was invoked with requirements.txt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/510)
=> PIP: Run pydep if setup.py exists (#480)

scanner/src/main/kotlin/Scanner.kt, scanner/src/main/kotlin/scanners/FileCounter.kt
The FileCounter scanner counts the files in the scan path. Because it is
much faster than the other scanners it is useful for testing the scanner
tool, for example during development or when integrating it with other
tools.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/512)
=> scanner: Add a simple FileCounter scanner for testing

scanner/src/funTest/kotlin/ScanPathTest.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/Main.kt
Name both "scanPath" as both scan a single path. Also improve the
documentation accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/513)
=> scanner: Align the two implementations that scan a path

model/src/main/kotlin/AnalyzerResult.kt, model/src/test/kotlin/AnalyzerResultTest.kt
This saves code when calling the addResult function multiple times in a
row.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/523)
=> model: Make AnalyzerResultBuilder.addResult fluent

docs/README.md
We have migrated from .org to .com, see
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/532)
=> README: Update links to Travis CI

analyzer/src/main/kotlin/managers/GoDep.kt
It seems the wording of the "no Go files" error message changed
somewhere between Go version 1.8 and 1.10, so include the new wording
here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/533)
=> GoDep: Extend the list of errors messages to ignore

analyzer/src/main/kotlin/PackageManager.kt
Previously, only the URL was normalized and the VCS information from the
URL was merged with the original / non-normalized package VCS information.
Normalizing the VCS information only partly is somewhat arbitrary. Also,
we should be agnostic about what VcsInfo.normalize() actually does at this
point. Finally, we should be consistent about only merging normalized
information with other normalized information here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/534)
=> PackageManager: Normalize the whole package VCS when processing it

model/src/main/kotlin/VcsInfo.kt, model/src/test/kotlin/VcsInfoTest.kt
There is no real point in preferring a specific spelling of the type as
in most places we deal with normalized VcsInfo with lower-cased type
anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/535)
=> VcsInfo: Remove awkward "type" merging logic

analyzer/src/funTest/kotlin/integration/SimpleFormIntegrationTest.kt
The previous version depends on a version of nokogiri that requires Ruby
version < 2.4. Upgrade simple_form (and thus nokogiri) to support Ruby
2.4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/540)
=> SimpleFormIntegrationTest: Upgrade simple_form to version 4.0.0

.appveyor.yml
With our limited cache size of 1 GiB we never managed to upload
gradle-4.7-all to the cache anyway, and we should get rid of old
distributions in favor of making space for regular dependency
artifacts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/541)
=> AppVeyor: Stop caching the Gradle distribution

analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/test/kotlin/NpmTest.kt
These URLs will be handled by normalizeVcsUrl(). This fixes the analyzer
to handle the "git@github.com/cisco/node-jose.git" NPM URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/545)
=> NPM: Teach expandShortcutURL() to leave crazy URLs untouched

analyzer/src/main/kotlin/MavenSupport.kt
Instead of overwriting the default remote repositories, keep them at the
end of the list of repositories to search in. This ensures that Maven
Central is always searched as a fall-back, which resembles standard
Maven behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/546)
=> MavenSupport: Maintain the default list of remote repositories

analyzer/src/funTest/assets/projects/external/godep-expected-output.yml, analyzer/src/funTest/assets/projects/external/qmstr-expected-output.yml, analyzer/src/funTest/assets/projects/external/sprig-expected-output.yml, analyzer/src/main/kotlin/managers/GoDep.kt
Otherwise the package references cannot be matched with the packages where
"GoDep" is already used as provider.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/551)
=> analyzer: Use "GoDep" as provider for package references

downloader/src/test/kotlin/CvsTest.kt
Temporarily disable the CVS tests that require the SourceForge repository
because it is currently down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/554)
=> downloader: Disable CVS tests that use SourceForge

scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/FileCounter.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt
Perform some minor refactoring to reduce the number of times getDetails()
is called. It in turn calls getVersion() which, depending on the
scanner, might take a few seconds. So doing this call for each package
to scan might sum up to a significant amount of time for projects with
several hundrets or even thousands of packages. Assuming that the
scanner executable is not changed while scanning packages, only call
getDetails() once when starting to scan a list of packages.
While at it, also call Instant.now() only once in specific places. This
is not to improve performance, but to have exactly matching time stamps
in those places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss …
=> LocalScanner: Reduce the number of calls to getDetails() and friends

analyzer/src/main/kotlin/managers/GoDep.kt
This fixes a regression introduced by 2022201. The commit went in
unnoticed due to an issue with the test being skipped, see
https://ci.appveyor.com/project/heremaps/oss-review-toolkit/build/1.0.2569/tests
This yet needs to be investigated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/564)
=> GoDep: Fix the revision to be the one from Gopkg.lock again

analyzer/src/funTest/kotlin/BabelTest.kt, analyzer/src/funTest/kotlin/BundlerTest.kt, analyzer/src/funTest/kotlin/GoDepTest.kt, analyzer/src/funTest/kotlin/GradleTest.kt, analyzer/src/funTest/kotlin/MainTest.kt, analyzer/src/funTest/kotlin/MavenTest.kt, analyzer/src/funTest/kotlin/NpmTest.kt, analyzer/src/funTest/kotlin/PhpComposerTest.kt, analyzer/src/funTest/kotlin/PipTest.kt, analyzer/src/funTest/kotlin/SbtTest.kt, analyzer/src/test/kotlin/PackageManagerTest.kt, analyzer/src/test/kotlin/YamlFilePackageCurationProviderTest.kt, downloader/src/test/kotlin/CvsTest.kt, downloader/src/test/kotlin/GitTest.kt, downloader/src/test/kotlin/MercurialTest.kt, downloader/src/test/kotlin/SubversionTest.kt, model/src/test/kotlin/ProjectTest.kt, model/src/test/kotlin/ScanResultContainerTest.kt, scanner/src/funTest/kotlin/ScanPathTest.kt, utils/src/test/kotlin/ArchiveUtilsTest.kt, utils/src/test/kotlin/UtilsTest.kt
This has been fixed in IntelliJ IDEA 2018.1.4, see
https://youtrack.jetbrains.com/issue/IDEA-190100
Perform some minor renaming of variables along the way to avoid name
clashes / use more speaking names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/566)
=> Remove code that works around the wrong IntelliJ IDEA working directory

analyzer/src/funTest/assets/projects/synthetic/npm-expected-output-multiple-lockfiles.yml, analyzer/src/funTest/assets/projects/synthetic/npm-expected-output-no-lockfile.yml, analyzer/src/funTest/kotlin/NpmTest.kt, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/CocoaPods.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/PIP.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/SBT.kt, analyzer/src/main/kotlin/managers/Unmanaged.kt
Using empty projects is a problem if the dependency resolution fails for
multiple projects, in this case they would overwrite each other in the
analyzer result. Also it is hard to fix the issue if there is no
information about which project failed.
Instead use the relative path of the definition file as the project name
and also set the VCS info if available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/559)
=> analyzer: Do not create empty projects when the dependency resolution fails

analyzer/src/main/kotlin/Main.kt
Remove the feature to write individual analyzer result files per project, instead always create the merged analyzer result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/570)
=> Remove single-project analyzer results

scanner/src/main/kotlin/Main.kt
This is a fixup for 0579bcf.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/573)
=> scanner: Correctly print the detected licenses

downloader/src/main/kotlin/vcs/GitRepo.kt
As a follow-up to 8a757c7, remove the optimization completely. It turns out
that it happens too often that Git wants to fetch unadvertized objects
(objects not at the tip of a ref), like merge commits generated by
Gerrit, which is not supported by Gerrit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/577)
=> GitRepo: Remove the shallow clone optimization

analyzer/src/funTest/kotlin/BundlerTest.kt
These tests should run for all PRs, otherwise it is too risky that the
Bundler implementation breaks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/582)
=> analyzer: Remove the ExpensiveTag from the Bundler tests

analyzer/src/main/kotlin/managers/Maven.kt
Otherwise this can cause a NullPointerException.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/583)
=> analyzer: Handle null values of MavenProject.getUrl()

scanner/src/funTest/kotlin/scanners/FileCounterTest.kt
To avoid a deprecation warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/584)
=> FileCounterTest: Use matchers from the new kotlintest 3 package

analyzer/src/main/kotlin/MavenSupport.kt
If no connector for a repository can be created catch the exception and continue with the next repository instead of crashing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/585)
=> MavenSupport: Handle the NoRepositoryConnectorException

scanner/src/main/kotlin/scanners/ScanCode.kt
Until [1] is fully fixed the matched text included in the output is not
the full / unmodified license text, so drop it to avoid confusion.
Instead, the plan is to get the vanilla license text from the SPDX
license database [2] which also would work with all scanners.
[1] https://github.com/nexB/scancode-toolkit/issues/504
[2] https://github.com/spdx/license-list-data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/592)
=> ScanCode: Remove matched license text from native output

analyzer/src/funTest/kotlin/integration/DrupalIntegrationTest.kt
This is a fixup for a391d9e.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/598)
=> DrupalIntegrationTest: Add "yarn.lock" as an expected definition file

downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, downloader/src/main/kotlin/vcs/Subversion.kt
Calling an external process might be expensive and is not necessary for
blank URLs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/599)
=> downloader: Improve isApplicableUrl() for pathological cases

scanner/src/main/kotlin/scanners/ScanCode.kt
This is a fixup for 6dba67c that enables caching of scan results again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/607)
=> ScanCode: Fix passing the raw scan result

scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml, scanner/src/funTest/kotlin/scanners/FileCounterTest.kt
This way the expected output file can actually be parsed e.g. by the
reporter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/616)
=> scanner: Use a real timestamp in the file counter test

analyzer/src/main/kotlin/managers/PIP.kt
Turns out this is completely valid in case the project does not declare
any dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/619)
=> PIP: Do not throw an exception if pipdeptree output lacks the project

model/src/test/kotlin/AnalyzerResultTest.kt, model/src/test/kotlin/ScanResultContainerTest.kt
Before, the resolvedRevision was assigned the value "path". That did not
make the test fail, but was confusing to read in the output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/621)
=> AnalyzerResultTest: Properly pass a "resolvedRevision"

build.gradle
See https://blog.jetbrains.com/kotlin/2018/06/kotlin-1-2-50-is-out/.
The stdlib by default resolves to the version of the plugin, so simply
omit that version number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/624)
=> Gradle: Upgrade Kotlin to version 1.2.50

scanner/src/main/kotlin/Main.kt
These can get long and clutter regular output, so only show them in debug
mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/628)
=> scanner: Print declared / detected licenses only in debug mode

analyzer/src/main/resources/META-INF/plexus/components.xml
This enables parsing of POM files that use "hpi" packaging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/632)
=> Maven: Add an empty lifecycle mapping for "hpi" packaging

analyzer/src/main/kotlin/Main.kt
Otherwise passing "." as the inputDir would make resolving a path relative to it fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/639)
=> analyzer: Pass an absolute path to resolveDependencies()

scanner/src/main/kotlin/scanners/Licensee.kt
As of [1] the "matched_license" already is the SPDX ID instead of an
internal key name. This is a fixup for 924eb69.
[1] https://github.com/benbalter/licensee/pull/283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/646)
=> Licensee: Fix getting the SPDX ID for a license match

.appveyor.yml, .travis.yml, analyzer/src/main/kotlin/MavenSupport.kt
The function only determines information about the package itself, not
about the dependencies, so it makes no sense to resolve the dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/648)
=> analyzer: Disable dependency resolution in MavenSupport.parsePackage()

.travis.yml
sudo was implicitly required already as we use "sudo apt install -y cvs"
in the "install" section, but removing that line would make Travis
silently switch to "sudo: false", i.e. the container-based EC2
infrastructure. As we are planning to move to Docker-based builds which
also require sudo, make that requirement explicit already now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/649)
=> Travis: Explicitly state that sudo is required

downloader/src/main/kotlin/Main.kt
This prevents a crash when an IOException occurs, because the surrounding
code only expects DownloadExceptions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/657)
=> downloader: Wrap IOExceptions when downloading source artifact

analyzer/src/main/kotlin/MavenSupport.kt
This is important because system properties and environment variables can
be used to activate Maven profiles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/664)
=> analyzer: Use all system properties and environment variables in Maven

model/src/main/kotlin/ScanSummary.kt, model/src/test/kotlin/ScanResultContainerTest.kt, scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml, scanner/src/funTest/kotlin/HttpCacheTest.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/Main.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/FileCounter.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanCodeTest.kt
The order of errors, like the messages from a chain of exceptions, is
important. So make this a list instead of a set of errors, like we also
already have it in other places. The original idea was to, in case of
multiple separate errors, to not show duplicates in the summary. But in
reality we do not use this field to store multiple errors, but multiple
messages for the same root error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/672)
=> model: Make the scan error summary a list

analyzer/src/main/kotlin/managers/PIP.kt
For example, this one does not have these:
https://github.com/syoyo/tinyobjloader/blob/f750f3faebb688a0c7f3d918fb29a96c2ec652e4/python/setup.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/684)
=> PIP: Do not require "url" or "download_url" to be present in setup.py

utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/UtilsTest.kt
This fixes the issue that e.g. "1.11.6" was regarded to be ambigious to
"1.11.60" etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/686)
=> Utils: Return early from filterVersionNames() for full matches

downloader/src/main/kotlin/Main.kt
Without this change, depending on the configuration of the webserver from which
source artifacts are downloaded, OkHTTP will decompress gzip transparently.
That leads to problems when calculating hash digests and unpacking archives,
since the file extension still indicates that the archive is compressed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/687)
=> downloader: Disable transparent gzip in OkHTTP

utils/src/main/kotlin/ProcessCapture.kt
To avoid the hint about wrong property naming.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/698)
=> ProcessCapture: Make DEBUG_* variables compile time constants

analyzer/src/funTest/kotlin/PhpComposerTest.kt, analyzer/src/funTest/kotlin/vcs/GitRepoTest.kt, analyzer/src/main/kotlin/Main.kt, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/PIP.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/Unmanaged.kt, downloader/src/main/kotlin/VersionControlSystem.kt, scanner/src/main/kotlin/Main.kt
We must not use "getInfo(path)" in these cases as that call resolves the
path relative to the VCS root, but in case of GitRepo we need the path to
the manifest.
This is a fixup for f492022.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/701)
=> analyzer: Fix getting provenance information for analysis of GitRepos

.gitmodules, .travis.yml, analyzer/src/funTest/assets/projects/external/directories-expected-output.yml
That fixes issues with Java 9. Also note that "directories" moved to
"directories-jvm" on GitHub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/708)
=> gitmodules: Update "directories" to version 10

analyzer/src/main/kotlin/managers/SBT.kt
This (semantically) reverts commit 4352907 (while keeping the introduced
runSBT function) as there are several issues with passing the log level to
various versions of sbt:
https://github.com/sbt/sbt/issues/4285
https://github.com/sbt/sbt/issues/4088
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/712)
=> Revert "SBT: Be explicit about running SBT with "--info""

downloader/src/main/kotlin/Main.kt
Download (and scan) projects within the same VCS working tree only once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/717)
=> downloader: De-duplicate projects by VcsInfo

downloader/src/main/kotlin/Main.kt, scanner/src/main/kotlin/Main.kt
For GitRepo we must not de-duplicate based on VcsInfo without taking the
path into account. Also, the first entry in projectsWithSameVcs is not
necessarily the one which origtinally had the empty path, if any, so
actually search for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/719)
=> downloader: Fix chosing the "root" project with the empty path

build.gradle
See https://blog.jetbrains.com/kotlin/2018/08/kotlin-1-2-60-is-out/.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/742)
=> Gradle: Upgrade to Kotlin 1.2.60

utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/UtilsTest.kt
Some setups have issues when "%2F" as part of an URL, e.g. when using
Apache Redirect. Double encode "%2F" to "%252F" to work around this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/743)
=> utils: Double encode "%2F" in fileSystemEncode()

utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/UtilsTest.kt
This reverts commit ae9bd5eb7c149e1f081ce7d5bfd1a26dcfa608b4.
The double encoding of "/" causes similar issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/744)
=> Revert "utils: Double encode "%2F" in fileSystemEncode()"

model/src/main/kotlin/AnalyzerResult.kt
The function checked if the errors map is not empty instead of checking if
any of the lists contained in the map is not empty. This always returned
true, because the map contains one entry for each project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/745)
=> model: Fix AnalyzerResult.hasErrors()

model/src/main/kotlin/config/ArtifactoryCacheConfiguration.kt, model/src/test/kotlin/config/ArtifactoryCacheConfigurationTest.kt
Otherwise credentials could leak into the results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/749)
=> model: Make sure the Artifactory ApiToken is not serialized

scanner/src/main/kotlin/scanners/ScanCode.kt
When mapping unknown errors only the error message is relevant, not the
other properties of the error object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/769)
=> ScanCode: Only use the error message to get distinct errors

scanner/src/main/kotlin/Main.kt
If at all a function, it should probably be part of OrtResult or an
extension function for File. Neither is really fitting here, also
because of the println(). So just inline this small function which is
only called once. This also helps for the upcoming CLI refactoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/771)
=> scanner: Inline the writeResult() function

scanner/src/main/kotlin/Main.kt
We are not using these files anymore in favor of the OrtResult.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/770)
=> scanner: Do not write out the individual ScanResultContainers anymore

analyzer/src/main/kotlin/Main.kt, downloader/src/main/kotlin/Main.kt, reporter/src/main/kotlin/Main.kt, scanner/src/main/kotlin/Main.kt
This reverts commit 7ee6438c3d1d0db6a73e57988d778539cffe36e2.
JCommander does not support sets by default. It only has a
DefaultListConverter. As a result it fails to parse the set parameters with
the correct type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/776)
=> Revert "Use sets where lists are supposed to contain unordered entries only once"

docs/README.md
Updating README.md to point to our roadmap on GitHub instead of communicating a release date that by now has been moved
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/775)
=> Update README to link to project roadmap

analyzer/src/funTest/kotlin/BabelTest.kt, analyzer/src/funTest/kotlin/BundlerTest.kt, analyzer/src/funTest/kotlin/GoDepTest.kt, analyzer/src/funTest/kotlin/GradleAndroidTest.kt, analyzer/src/funTest/kotlin/GradleLibraryTest.kt, analyzer/src/funTest/kotlin/GradleTest.kt, analyzer/src/funTest/kotlin/MavenTest.kt, analyzer/src/funTest/kotlin/NpmTest.kt, analyzer/src/funTest/kotlin/PhpComposerTest.kt, analyzer/src/funTest/kotlin/PipTest.kt, analyzer/src/funTest/kotlin/StackTest.kt, analyzer/src/funTest/kotlin/YarnTest.kt, analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt, analyzer/src/main/kotlin/Analyzer.kt, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/PackageManagerFactory.kt, analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/CocoaPods.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/PIP.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/SBT.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/Unmanaged.kt, analyzer/src/main/kotlin/managers/Yarn.kt, utils-test/src/main/kotlin/Utils.kt
This is done in preparation of implementing BitBake support (#722), which requires a mechanism to pass a list of recipes to analyze.
Since this list is specific to the repository being analyzed, it makes sense to add this information to .ort.yml and give package manager instances access to it, analogous to the command line parameters via AnalyzerConfiguration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/777)
=> analyzer: Pass config from .ort.yml to package managers

analyzer/src/main/kotlin/managers/PhpComposer.kt
The "composer-plugin-api" is a special package, which does not actually
exist. It's used by composer plugins internally and should be ignored
during dependency resolution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/781)
=> PhpComposer: Ignore special "composer-plugin-api" dependency

analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt, analyzer/src/funTest/kotlin/integration/DrupalIntegrationTest.kt, analyzer/src/funTest/kotlin/integration/GradleIntegrationTest.kt, analyzer/src/funTest/kotlin/integration/SimpleFormIntegrationTest.kt, analyzer/src/funTest/kotlin/integration/VueJsIntegrationTest.kt, analyzer/src/main/kotlin/Analyzer.kt
Call maps of managers to definiton files "managed files" to distinguish
from lists of definition files and to align with function names like e.g.
findManagedFiles(). Also improve a related code comment along the way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/792)
=> analyzer: Minor renaming of variables

reporter-web-app/src/utils.js
Undefined error was thrown as no default values were set for
several package attributes related to detected package licenses
Had asssumed that each package found by the Analyzer
would be scanned by the Scanner
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/796)
=> Fix undefined detected licenses error if no scan was made

analyzer/src/main/kotlin/PackageManager.kt, scanner/src/main/kotlin/Scanner.kt
Not the loader, but the list of discovered classes should be initialized
lazily.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/798)
=> Initialize the list of all classes discovered by ServiceLoader lazily

scanner/src/funTest/kotlin/scanners/FileCounterTest.kt
Do not go through hoops by calling main() including command line
parsing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/800)
=> FileCounterTest: Call scanDependenciesFile() directly

reporter-web-app/src/components/SummaryView.js, reporter-web-app/src/utils.js
Refactored code to fix a bug in the code that creates a list
of errors from walking package tree. Previous code did not
collect all package errors as the code had not been updated
to align with a recent report data format change e.g.
scanResult.errors => scanResult.summary.errors
This bug resulted in some reviews to be displayed as
'Completed scan successfully' whilst in reality there
were errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/808)
=> reporter-web-app: Fix incorrect summarization of package errors

cli/src/main/kotlin/Main.kt
If generating a report fails with an exception, catch it and continue
creating the other reports, instead of aborting the program.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/817)
=> cli: Handle exceptions thrown in report generation

scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/Scanner.kt
Before the raw scan results for each package were kept in memory until the
scan of all packages finished. This could easily lead to OutOfMemoryErrors,
especially for scanners with large results files, like ScanCode.
To fix this remove the raw results from memory directly after the scan of a
package finished.
Note that raw results are still written to the scan results cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/818)
=> scanner: Do not keep all raw results in memory

analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/yarn-expected-output.yml
For some reason the NPM registry started to return non-https URLs for
these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/821)
=> analyzer: Update expected results with http URLs

docs/README.md
Added a link to our Slack to README.md. If someone has a suggestion for a pretty Slack badge I'm happy to take it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/814)
=> Add link to ort-talk Slack to README.md

cli/src/main/kotlin/Main.kt, docs/GettingStarted.md
Previously, the sub-commands did not support --help, i.e. "ort analyze
--help" did not work. Add support for that, only showing the relevant
sub-command parameters. "ort --help" still shows all sub-commands
including all their parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/830)
=> Main: Support --help also per (sub-)command

docs/GettingStarted.md
The parameter for specifying the dependencies has been
renamed by 1f428664, now it is consistent again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/836)
=> GettingStarted: fix-up scanner example

model/src/main/kotlin/AnalyzerResult.kt, model/src/main/kotlin/Model.kt, model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/Package.kt, model/src/main/kotlin/PackageCurationData.kt, model/src/main/kotlin/PackageReference.kt, model/src/main/kotlin/Project.kt, model/src/main/kotlin/Provenance.kt, model/src/main/kotlin/RemoteArtifact.kt, model/src/main/kotlin/ScanRecord.kt, model/src/main/kotlin/ScanResult.kt, model/src/main/kotlin/ScanResultContainer.kt, model/src/main/kotlin/ScannerDetails.kt, model/src/main/kotlin/Scope.kt, model/src/main/kotlin/VcsInfo.kt
Introduce a typealias for the data maps. This ensures that all data maps
use the same data type, and allows for changing it in a central place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/839)
=> model: Introduce a CustomData typealias

reporter-web-app/src/data/choosealicense/index.js, reporter-web-app/src/data/colors/index.js
The "* as" syntax is intended for use with modules, not JSON files. So do
not use it for JSON files, otherwise the "default" entry will be also
iterated over.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/833)
=> reporter-web-app: Avoid a "default" entry being created upon JSON import

reporter-web-app/src/utils.js
These changes from 1d3f2d9 broke the report. A difference to using
forEach is that it does not enumerates properties in the prototype
chain, which probably caused the breakage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/841)
=> reporter-web-app: Revert changes to for-loops

analyzer/src/funTest/kotlin/GradleTest.kt, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/CocoaPods.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/PIP.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/SBT.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/Unmanaged.kt, analyzer/src/main/kotlin/managers/Yarn.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Cvs.kt, downloader/src/main/kotlin/vcs/GitBase.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, downloader/src/main/kotlin/vcs/Subversion.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/FileCounter.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, utils/src/main/kotlin/CommandLineTool.kt, utils/src/main/kotlin/ProcessCapture.kt
Add an interface to implement by all classes that are backed by a command
line tool. This makes it easier to identify our external dependencies on
command line tools and reduces code duplication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/848)
=> Introduce the concept of a CommandLineTool

downloader/src/main/kotlin/DownloadException.kt, scanner/src/main/kotlin/ScanException.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, utils/src/main/kotlin/CommandLineTool.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/856)
=> Work around a regression to call tools with absolute paths

model/src/main/kotlin/config/Excludes.kt, reporter/src/main/kotlin/reporters/NoticeReporter.kt, reporter/src/test/assets/npm-test-with-exclude-NOTICE, reporter/src/test/assets/npm-test-with-exclude-scan-results.yml, reporter/src/test/kotlin/reporters/NoticeReporterTest.kt
Do not add licenses and copyright for packages that only appear in excluded
projects or scopes to the generated LICENSE file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/852)
=> reporter: Re-implement exclusion of projects and scopes in notice reporter

analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml, build.gradle
See https://blog.jetbrains.com/kotlin/2018/09/kotlin-1-2-70-is-out/.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/865)
=> Gradle: Upgrade to Kotlin 1.2.70

.appveyor.yml, .travis.yml
This avoids potential file locking issues on Windows. Using the daemon
does not pay off anyway as we only launch Gradle once now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/869)
=> Do not use the Gradle daemon in CI

reporter-web-app/build.gradle
NPM needs to be installed in order to bootstrap Yarn
since the Gradle Node plugin install Yarn via NPM. For
this installation to work the download flag needs to
be set.
Also for not nefatively affecting reproducibility of
build setting a fixed NPM version.
See also the related issue [2] and open pull request [1].
[1] srs/gradle-node-plugin#186
[2] srs/gradle-node-plugin#175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/862)
=> reporter-web-app: Support bootstrapping NPM and Yarn

.appveyor.yml, .travis.yml, analyzer/build.gradle, analyzer/src/main/kotlin/managers/SBT.kt, gradle.properties, utils/src/main/kotlin/Utils.kt
For the same reason as in ProcessCapture, see 839bcdb, use a temporary
file to redirect output to work around the 64k pipe buffer limit on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/871)
=> Utils: Use a temporary file for redirecting output

analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
The dependency on "pyparsing" was updated from 2.2.0 to 2.2.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/878)
=> analyzer: Update expected results for spdx-tools-python in `PipTest`

analyzer/src/main/kotlin/PackageManager.kt
This came up when analyzing our own reporter-web-app. While we temporarily
move away any existing "node_modules" directory before resolving NPM
dependencies, it is confusing to list found definition files in there in
the first place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/875)
=> PackageManager: Ignore intermediate build system directories

analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, utils/src/main/kotlin/Utils.kt
The logic for moving directories to temporary directories and back was redundantly implement accross several package managers. That redundancy is eliminated by extracting the logic from Bower and re-using it all over the place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/882)
=> Stash dir utility

analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/Yarn.kt, analyzer/src/test/kotlin/PackageManagerTest.kt
Previously, NPM was run in addition to Yarn in case only "yarn.lock"
(besides a "package.json", of course) was present, as it could be
interpreted as an NPM project without a lock file, *and* as a Yarn project
with a lock file. However, running both NPM and Yarn was a source of
confusion, esp. for projects that intend to be used with Yarn only, as a
single project appeared twice in the results.
Therefore, change the behavior so that always either NPM or Yarn is
used depending on the presence of "yarn.lock": If no "yarn.lock" is
present, use NPM, and if it is, use Yarn. If both "yarn.lock" and
"package-lock.json" are present an IOException is thrown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> analyzer: Do not run NPM and Yarn for the same project

cli/src/main/kotlin/Main.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/892)
=> cli: Add missing space in description of `--repository-configuration-file`

docs/Configuration.md
Add documentation for how to mark parts of a repository as excluded using
the `.ort.yml` file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/891)
=> docs: Add documentation for excludes using `.ort.yml`

docs/Configuration.md, model/src/main/kotlin/config/Excludes.kt, model/src/main/kotlin/config/ProjectExclude.kt, model/src/test/kotlin/config/RepositoryConfigurationTest.kt
This allows for excluding multiple projects with a single `ProjectExclude`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/897)
=> model: Make the `path` in `ProjectExclude` a regular expression

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml, analyzer/src/main/kotlin/Analyzer.kt, model/src/main/kotlin/AnalyzerResult.kt, model/src/test/kotlin/AnalyzerResultTest.kt
The `AnalyzerResultBuilder` requires the root path of the analyzed
project to be able to calculate the file hashes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/910)
=> analyzer: Fix reporting duplicate project identifiers

analyzer/src/main/kotlin/managers/Bower.kt
If the dependency tree contains multiple nodes representing a single
specific package, that is the version and the target do match
exactly, bower may leave out the dependency information of the
child dependencies for such nodes while keeping at least
one node with the full dependency information for all the children.
This change adds handling for that case: when the parsing logic
arrives at a node with lacking dependency information it tries to
parse a similar node (with full dependency information) instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/904)
=> Bower: properly handle nodes with lacking dependency data

downloader/src/main/kotlin/vcs/GitRepo.kt
The default group to clone is called "default", but if groups are in use
this likely only is a subset of all projects. Until we properly support
the groups feature, be conservative and clone all projects instead of only
projects in the default group.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/913)
=> GitRepo: Clone all groups by default

analyzer/src/funTest/assets/projects/synthetic/pip-expected-output.yml, analyzer/src/main/kotlin/managers/PIP.kt
In case a "setup.py" was present in addition to multiple
"requirements*.txt" files the project name was only constructed from
"setup.py" for all "requirements*.txt" files, leading to duplicate
project names. Fix this by always considering "setup.py" and
"requirements*.txt", if any, to get project meta-data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/922)
=> PIP: Fix the logic to determine the project name from requirements.txt

utils/src/main/kotlin/DirectoryStash.kt, utils/src/test/kotlin/DirectoryStashTest.kt
Amongst others add two tests which throw an IOException due
to a bug and thus are disabled for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/921)
=> DirectoryStash: Add unit tests

cli/src/main/kotlin/commands/ScannerCommand.kt
The check for LocalScanner needs to go now as the compiler otherwise
correctly warns that the check is superfluous as we only have
LocalScanners currently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/927)
=> cli: Reflect in the help that ScanCode actually is the default scanner

downloader/src/main/kotlin/Downloader.kt
Avoid the need to escape HTML tags in this case by simply using prose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/929)
=> Downloader: Fix printing the Maven hint for HTML reports

analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/SBT.kt, model/src/main/kotlin/Package.kt, model/src/main/kotlin/Project.kt, scanner/src/main/kotlin/ScanResultsCache.kt
The only exception are constructors which should be close to the default
constructor, and enum constants which have to come before any other
content.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/937)
=> Move all companion objects to the top of the class for consistency

.travis.yml
This never really worked as expected due to [1] and would again require
rotating of S3 credentials, so simply disable it for now.
[1] https://github.com/travis-ci/travis-ci/issues/9025
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/947)
=> Travis: Stop uploading of test artifacts

downloader/src/main/kotlin/VersionControlSystem.kt
Esp. for Subversion with its varing directory layout for branches / tags
(globally or per project) it could be that we are guessing the wrong
layout. In such a case we should not fail completely, but just fail this
check to give a later curation the chance to succeed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/949)
=> VersionControlSystem: Catch IOExceptions when listing remote branches

downloader/src/main/kotlin/vcs/Git.kt
This ensures our sparse checkout actually matches the path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/969)
=> Git: Throw an error if a requested VCS path does not exist

analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/yarn-expected-output.yml
Again, the download URLs for some packages have changed from HTTPS to HTTP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/972)
=> analyzer: Update expected NPM results with HTTP URLs

analyzer/src/main/kotlin/managers/NPM.kt
Given a list of definition files 'mapDefinitionFiles' needs to decide which
of those files shall be handled by this package manager. In case of NPM all
definition files that are not handled by a Yarn workspace need to be filtered
out as of the recent introduction of basic Yarn workspace support, see dcf44b7.
The implemented logic which is based on computing a common file prefix does not
work in all possible cases. In context of this bug the computed project root
path does not have any child file called 'package.json'. This is the typical
case for Git Repo based projects resulting in an IOException.
Checking whether that file exists fixes this issue quickly. This change
intentionally doesn't fix the Yarn workspace detection for all possible cases
since this requires more effort and is left …
=> NPM:fix uncaught IOException

model/build.gradle, model/src/main/kotlin/config/LicenseMapping.kt, model/src/main/kotlin/config/SpdxLicense.kt, reporter/src/main/kotlin/reporters/AbstractNoticeReporter.kt, reporter/src/main/kotlin/reporters/NoticeOnlyDeclaredReporter.kt, reporter/src/main/kotlin/reporters/NoticeReporter.kt, reporter/src/main/kotlin/reporters/TableReporter.kt, reporter/src/main/resources/META-INF/services/com.here.ort.reporter.Reporter, reporter/src/test/assets/NPM-is-windows-1.0.2-expected-NOTICE_ONLY_DECLARED, reporter/src/test/kotlin/reporters/NoticeOnlyDeclaredReporterTest.kt, scanner/src/main/kotlin/Scanner.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/974)
=> Add license note generator for only declared licenses

.gitmodules, scanner/src/main/kotlin/scanners/ScanCode.kt
The Git submodule is not available when running ORT from a (future)
binary distribution. Hence we need to really bootstrap ScanCode instead
of "fake-bootstrapping" it by directly using it from the checked out
submodule. This aligns with the other scanners which are bootstrapped
properly already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/988)
=> scanner: Really bootstrap ScanCode instead of using it from a submodule

utils/src/main/kotlin/OkHttpClientHelper.kt
The previous 10 MiB were too little to cache e.g. the ScanCode
distribution which has about 110 MiB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/992)
=> OkHttpClientHelper: Increase the HTTP cache size to 1 GiB

build.gradle, cli/build.gradle
Now that we only have one application project, move application
dependencies directly to there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/994)
=> Gradle: Move application dependencies to the only "cli" application

scanner/src/main/kotlin/scanners/ScanCode.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/997)
=> ScanCode: Enable caching of the ScanCode distribution when boostrapping

analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/PackageJsonUtil.kt, analyzer/src/main/kotlin/managers/Yarn.kt, analyzer/src/test/kotlin/PackageJsonUtilTest.kt, utils/src/main/kotlin/Utils.kt
Fix several issues related to Yarn workspaces
The existing logic for deciding between Yarn and NPM for a given list of
packages was intentionally designed to be very basic, but it also exhibits
several issues. As an incremental refactoring for fixing those seems to be
much more effort this change re-writes that logic for mapping the definition
files - that is the decision whether Yarn, Npm or none of them should handle
a given 'package.json'.
As of this change a definition file is handled by Yarn if and only if at
least one of the folowing conditions is fulfilled:
(1) it belongs to a Yarn workspace, e.g. either it is the root or a submodule
(2) it has a yarn lockfile as sibling
The logic for computing the root project directory was not working in some
cases, e.g. given '/ab/package.json' …
=> Improve Yarn workspaces handling

.github/dco.yml
See https://github.com/probot/dco#skipping-sign-off-for-organization-members.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1008)
=> Do not require organization members to signoff the DCO

.mention-bot
This was not working for a long time already as the upstream project is
archived, see
https://github.com/facebookarchive/mention-bot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1010)
=> Remove the .mention-bot configuration file

analyzer/src/main/kotlin/Analyzer.kt, docs/Configuration.md
If the input directory of the analyzer is a Git-Repo project the root
directory cannot by default contain an `.ort.yml` file that is associated
to the manifest. Instead look for the file in the manifest repository,
using the pattern `[manifest-file-name].ort.yml`, e.g.
`manifest.xml.ort.yml`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1003)
=> analyzer: Add a default location for the `.ort.yml` file for Git-Repo

settings.gradle
This will be needed to centrally define the version number via
properties for plugin IDs like "com.bmuschko.docker-java-application".
For this example, the deduced version property name would be
"dockerJavaApplicationPluginVersion".
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1011)
=> Gradle: Make version property name deduction work for plugin names with dashes

cli/src/main/kotlin/commands/EvaluatorCommand.kt, model/src/main/kotlin/Identifier.kt, model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/ScanResultContainer.kt, reporter/src/main/kotlin/reporters/TableReporter.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1013)
=> Scripting convenience

analyzer/src/main/kotlin/managers/PackageJsonUtil.kt, analyzer/src/test/kotlin/PackageJsonUtilTest.kt, build.gradle, reporter-web-app/build.gradle, scanner/src/funTest/kotlin/HttpCacheTest.kt
Partly revert 5e4ab2c to work around an issue on AppVeyor. While it was
nice to align with the analyzer on version 1.12.1, it is not strictly
required for this project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1018)
=> reporter-web-app: Go back to using Yarn 1.9.4 again

utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/UtilsTest.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1024)
=> Improve filtering of version names

analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml, analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-lockfile.yml, analyzer/src/funTest/assets/projects/synthetic/bundler/gemspec/Gemfile.lock, analyzer/src/funTest/assets/projects/synthetic/bundler/lockfile/Gemfile.lock
To address a security vulnerability as reported by GitHub. The upgrade
was performed by running
bundle lock --update=rack
in the respective directories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1031)
=> analyzer: Upgrade "rack" in synthetic test projects

downloader/src/main/kotlin/vcs/Git.kt
GitHub recently added server-side support for this, so enable it for
speedier clones from GitHub. Also see
https://blog.github.com/changelog/2018-11-08-git-protocol-v2-support/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1032)
=> Git: Enable the more efficient Git Wire Protocol version 2, if possible

analyzer/src/funTest/assets/projects/synthetic/bower-expected-output.yml
`shadycss` was upgraded to 1.6.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1035)
=> analyzer: Fix expected results for `BowerTest`

cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/DownloaderCommand.kt, cli/src/main/kotlin/commands/EvaluatorCommand.kt
This is to distinguish from e.g. Gradle exit codes which returns 1 for
failed builds, see https://stackoverflow.com/a/26814641/1127485.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1039)
=> cli: Use exit code 2 in case of command failures

evaluator/src/main/kotlin/Evaluator.kt
To avoid strange errors when java.lang.Package is implicitly used instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1043)
=> Evaluator: Import com.here.ort.model.Package by default

reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, reporter/src/main/kotlin/reporters/TableReporter.kt
If an evaluator result is available show the errors in a new table on top
of the report.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1044)
=> reporter: Show the evaluator errors in the static HTML report

.gitattributes
Our code is mainly Kotlin, not HTML.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1052)
=> Fix GitHub language statistics by excluding generated HTML code

docs/Configuration.md, model/src/test/kotlin/config/RepositoryConfigurationTest.kt
Fix a wrong configuration example along the way.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1041)
=> model: Add a test for deserializing a repo config with escaped dots in the path

analyzer/src/main/kotlin/PackageJsonUtils.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/Yarn.kt, analyzer/src/test/kotlin/PackageJsonUtilsTest.kt
As it is not a package manager itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1058)
=> analyzer: Move PackageJsonUtils out of managers

utils/src/test/kotlin/ExtensionsTest.kt
It is already mentioned by the parent scope part of the test case name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1060)
=> ExtensionsTest: Remove redundant 'should' from test case names

evaluator/src/main/kotlin/Evaluator.kt
Rule scripts themselves cannot contain imports as they would come after
the variable declarations in the preface, which is not allowed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1062)
=> Evaluator: Simplify writing rules by wildcard-importing some packages

gradle.properties, model/build.gradle, model/src/main/antlr/com/here/ort/model/spdx/SpdxExpression.g4, model/src/main/kotlin/spdx/SpdxException.kt, model/src/main/kotlin/spdx/SpdxExpression.kt, model/src/main/kotlin/spdx/SpdxExpressionDefaultVisitor.kt, model/src/test/kotlin/spdx/SpdxExpressionLexerTest.kt, model/src/test/kotlin/spdx/SpdxExpressionParserTest.kt
Implement a parser for SPDX expressions as specified in [1] using ANTLR
[2]. This is a prerequisite for implementing the evaluation of SPDX
expressions which will be used by upcoming features like evaluating the
compatibility of a license choice with an SPDX expression.
[1] https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60
[2] https://www.antlr.org/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1072)
=> model: Add a parser for SPDX expressions

settings.gradle
To avoid warnings like
No version specified for plugin 'antlr' and property 'antlrPluginVersion' does not exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1078)
=> Gradle: Skip looking for plugin version properties for core plugins

model/src/main/kotlin/spdx/SpdxLicenseMapping.kt, reporter/src/main/kotlin/reporters/AbstractNoticeReporter.kt, reporter/src/main/kotlin/reporters/NoticeOnlyDeclaredReporter.kt
This allows to shorten the script by not using fully-qualified names in
several places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1084)
=> AbstractNoticeReporter: Add SpdxLicense to the PostProcessor imports

docs/Configuration.md, model/src/main/kotlin/Package.kt, model/src/main/kotlin/PackageCurationData.kt, model/src/test/kotlin/PackageCurationTest.kt
The concluded license can be used to define the license of a package in
case the license declared in the metadata or the license detected by the
scanner do not match reality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1085)
=> model: Add a `concludedLicense` field to `Package`

model/src/main/kotlin/config/EvaluatorErrorResolution.kt, model/src/main/kotlin/config/EvaluatorErrorResolutionReason.kt, model/src/main/kotlin/config/Resolutions.kt, model/src/test/kotlin/config/RepositoryConfigurationTest.kt, reporter/src/funTest/assets/file-counter-expected-scan-report.html, reporter/src/main/kotlin/DefaultResolutionProvider.kt, reporter/src/main/kotlin/ResolutionProvider.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/ReportTableModel.kt, reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
Extend the model to allows specifying resolations for evaluator rule violations for local and global config.
Adjust the HTML reporter to display resolved error in green.
Refactor the HTML and CSS to improve it before touching it.
Note: this PR is based on https://github.com/heremaps/oss-review-toolkit/pull/1079 and has to be merged afterwards. Also the commit " Fix-up building the error description" will be merged as part of another PR where this one will depend on.
The PR now also depends on: https://github.com/heremaps/oss-review-toolkit/pull/1095
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1090)
=> License policy violations resolutions

.travis.yml
Running without "sudo" stopped working today (which actually makes
sense) by giving
$ rm -f $JAVA_HOME/lib/security/cacerts
rm: cannot remove '/usr/local/lib/jvm/openjdk10/lib/security/cacerts': Permission denied
The command "rm -f $JAVA_HOME/lib/security/cacerts" failed and exited with 1 during .
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1101)
=> Travis: Re-link cacerts as root

reporter/src/funTest/assets/NPM-is-windows-1.0.2-expected-NOTICE, utils/src/main/kotlin/CopyrightStatementsProcessor.kt, utils/src/test/assets/copyright-statements-expected-output.yml, utils/src/test/assets/copyright-statements.txt
Further improve the copyright statements processing by improving copyright prefix matchers and
adding a workaround for prefixed years. See individual commits for details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1103)
=> More pretty copyright statements

reporter-web-app/src/components/TableView.js
Passed incorrect parameter which fixed pageSize to 100 and resulted in any change in page size being ignored
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1114)
=> reporter-web-app: Fix page size changer in TableView

utils/src/main/kotlin/Extensions.kt
As it turns out, File().delete() also just deletes / unlinks the
junction without touching the directory the junction points to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1116)
=> safeDeleteRecursively: Remove the Windows-specific call to ProcessCapture()

docs/GettingStarted.md, reporter-web-app/build.gradle
The custom code properly caches e.g. "yarn install" already on the
Gradle-level instead of leaving it to Yarn. On the downside, the new
implemenation does not bootstrap Node, NPM or Yarn anymore, but we have
these already installed for the Analyzer anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1113)
=> reporter-web-app: Replace the unmaintained gradle-node-plugin with custom code

analyzer/src/main/kotlin/managers/Bower.kt
The toString() override introduced in e30f74f does nothing different than
the implementation inherited from PackageManager (see 50f03e9). Also
inline the single last remaining use of "PACKAGE_TYPE" now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1118)
=> Bower: Remove the toString() override

cli/src/main/kotlin/commands/EvaluatorCommand.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, model/src/main/kotlin/OrtResult.kt
Allow running `evaluation` and `report` with a changed repository configuration without needing to run the `analyzer` and `scanner` again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1127)
=> Override repository config

downloader/src/funTest/kotlin/GitRepoDownloadTest.kt
The Java comparator used for File objects on Windows is case-insensitve,
just like Windows file systems. To avoid differences to Linux'
case-sensitive sorting, sort on String objects instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1133)
=> GitRepoDownloadTest: Sort on String instead of File objects

cli/src/main/kotlin/commands/ReporterCommand.kt
If an exception is thrown while creating a report still try to create the
other reports, but return exit code 1 to indicate that something went
wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1138)
=> reporter: Return exit code 1 if any report could not be created

analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/yarn-expected-output.yml, analyzer/src/main/kotlin/managers/NPM.kt
To prevent NPM from modifying existing lock files, use `npm ci` [1] if a
lock file is found.
[1] https://docs.npmjs.com/cli/ci
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/877)
=> analyzer: Use `npm ci` if a lock file exists

.gitattributes
Avoid SPDX license / exception texts to be detected as Roff files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1144)
=> Fixup GitHub detected language statistics once more

analyzer/src/main/kotlin/managers/PIP.kt
This should help to avoid compiling packages with native code from
source, which usually requires several C / C++ development tools to be
installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1150)
=> PIP: Prefer binary wheels over sdist packages

model/src/main/kotlin/LicenseFinding.kt, scanner/src/test/kotlin/ScanCodeTest.kt
The `compareTo` function of a comparable class should be consistent with
`equals`, otherwise using the class in a sorted set or as a key in a sorted
map can result in unexpected behaviour [1][2]. Fix the `compareTo` function
of `LicenseFinding` accordingly. This also unveiled an issue in one of the
ScanCode tests.
Note that there are several other model classes with the same issue which
also need to be fixed.
[1] https://docs.oracle.com/javase/8/docs/api/java/util/SortedSet.html
[2] https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit …
=> LicenseFinding: Fix the `compareTo` function

reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
Instead of using `unsafe` to be able to replace linebreaks with `<br>` use
a loop in combination with the `br` DSL function. This makes sure that
error strings are properly escaped. Otherwise HTML special characters like
`&` in the error message could cause a `SAXParseException`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1161)
=> reporter: Do not use `unsafe` for error descriptions

README.md
Adding instructions how to build the Docker Image to make this  option more visible to ORT users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1159)
=> README: Add install instructions for Docker image

README.md
Yarn need to be installed on the system in order to
build ORT from source else Gradle wil throw an exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1156)
=> README: Update installation prerequisites

reporter/src/funTest/assets/static-html-reporter-test-expected-output.html, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
There is no such class, and it also should not be "ort-error" (singular)
as not all issues in the table are actually errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1174)
=> StaticHtmlReporter: Remove the invalid "ort-errors" class

reporter/src/funTest/assets/static-html-reporter-test-expected-output.html, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
Add row indexes to all the tables of the HTML report to increase readablity.
Moreover add anchors to the rows of the error and rule violation summary table to enable
linking to a specific issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1173)
=> HTML report: Add row indexes and anchors

model/src/main/kotlin/Identifier.kt, model/src/test/kotlin/IdentifierTest.kt
Also add some tests along the way. Use kotlintest's "assertSoftly" [1]
as these checks are too small for tests on their own, but we still want
to see all possible failures, if any, at once.
[1] https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#soft-assertions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1175)
=> Identifier: Extend isFromVendor() to also check .net and .org "domains"

model/src/main/kotlin/Identifier.kt, model/src/main/kotlin/OrtResult.kt, model/src/test/kotlin/IdentifierTest.kt
A single vendor, like HERE, can in fact claim multiple package
namespaces, like "com.here" and "com.traffic" for Maven.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1177)
=> model: Refactor isFromVendor to isFromOrg which can take multiple names

reporter/src/funTest/assets/NPM-is-windows-1.0.2-expected-NOTICE, reporter/src/funTest/assets/NPM-is-windows-1.0.2-expected-NOTICE_UNPROCESSED, reporter/src/funTest/assets/post-processed-expected-NOTICE, reporter/src/main/kotlin/reporters/NoticeReporter.kt
This is possible now as of d307aab.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1180)
=> reporter: Get license texts also for non-SPDX licenses

downloader/src/main/kotlin/Downloader.kt
Un-nest the fallback code to try them sequentially for a better
overview, and add a new final fallback to try downloading and scanning
the Maven POM to detect licenses added as XML comments in there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1181)
=> downloader: Add a final fallback to scan the Maven POM itself

reporter-web-app/public/index.html, reporter-web-app/src/App.js, reporter-web-app/src/components/ExpandablePanel.js, reporter-web-app/src/components/ExpandablePanelContent.js, reporter-web-app/src/components/ExpandablePanelTitle.js, reporter-web-app/src/components/LicenseChart.js, reporter-web-app/src/components/LicenseSummaryCard.js, reporter-web-app/src/components/LicenseTag.js, reporter-web-app/src/components/PackageDetails.js, reporter-web-app/src/components/PackageErrors.js, reporter-web-app/src/components/PackageLicenses.js, reporter-web-app/src/components/PackagePaths.js, reporter-web-app/src/components/PackageScansSummary.js, reporter-web-app/src/components/SummaryViewLicenses.js, reporter-web-app/src/components/SummaryViewTableIssues.js, reporter-web-app/src/components/SummaryViewTableMetadata.js, reporter-web-app/src/components/SummaryViewTimeline.js, reporter-web-app/src/components/TreeView.js, reporter-web-app/src/data/choosealicense/index.js, reporter-web-app/src/data/colors/index.js, reporter-web-app/src/index.js, reporter-web-app/src/reducers/index.js, reporter-web-app/src/reducers/selectors.js, reporter-web-app/src/sagas/convertReportData.js, reporter-web-app/src/sagas/index.js, reporter-web-app/src/store/index.js, reporter-web-app/src/utils/index.js
So we do not miss them when updating copyright headers next time like in
ff0645e.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1184)
=> reporter-web-app: Align copyright headers to those in Kotlin code

cli/docker/Dockerfile
This PR updates the npm and python-pip version for the Docker image build, because with the current `openjdk:11-jre-slim-sid` image I get the following error:
```
E: Version '5.8.0+ds6-2' for 'npm' was not found
E: Version '18.1-2' for 'python-pip' was not found
```
The newer versions of npm (5.8.0+ds6-3) and python-pip (18.1-4) solve this problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1190)
=> Docker: Update npm and python-pip versions

build.gradle
By default detekt only uses 'src/main/kotlin' (and 'src/main/java') as
the input [1]. Extend the input to also check the source code for tests.
[1] https://arturbosch.github.io/detekt/groovydsl.html#available-plugin-tasks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1196)
=> Gradle: Let detekt also check test code

cli/build.gradle, gradle.properties
See https://bmuschko.github.io/gradle-docker-plugin/#v4_3_0_january_12_2019.
Note that "inputDir" defaults to "$buildDir/docker" now. As "$buildDir"
is not under version control, explicitly specify our "cli/docker"
directory now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1203)
=> Gradle: Upgrade Docker plugins to version 4.3.0

spdx-utils/src/main/antlr/com/here/ort/spdx/SpdxExpression.g4, spdx-utils/src/main/kotlin/SpdxExpression.kt, spdx-utils/src/main/kotlin/SpdxExpressionDefaultVisitor.kt, spdx-utils/src/test/kotlin/SpdxExpressionParserTest.kt
DocumentRefs are a special kind of LicenseRefs, and both DocumentRefs and
LicenseRefs are license references. Clarify that also in variable names
and comments by not referring to license references as (only) LicenseRefs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1202)
=> SpdxExpression: Fix the support for DocumentRefs

model/build.gradle, model/src/main/kotlin/Mappers.kt, model/src/main/kotlin/VcsInfo.kt, model/src/test/kotlin/VcsInfoTest.kt
This is especially useful on deserializing manually created curations which
might contain typos in the property names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1204)
=> VcsInfo: Fail deserialization on unknown property

analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml, analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml, cli/src/funTest/kotlin/MainTest.kt, cli/src/main/kotlin/Main.kt
The `MainTest` was skipped since 546cda0 because `Main.main()` called
`exitProcess`. Fix this by moving the logic to a `run` function and calling
this function from the tests.
Because the test were skipped the expected result files need to be updated
to make it pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1214)
=> cli: Fix `MainTest`

analyzer/src/main/kotlin/Analyzer.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanCodeTest.kt, utils/src/main/kotlin/Utils.kt
While at it, extract the file name to a global constant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1209)
=> ScanCode: Do not scan the ORT configuration file

cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/EvaluatorCommand.kt, downloader/src/main/kotlin/Downloader.kt
Relax the existing check by not requiring anymore that the whole output
directory does not yet exist, but only require the individual output files
to not exist so they do not get overwritten.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1218)
=> AnalyzerCommand: Only require the individual output files to not exist

cli/src/main/kotlin/commands/ReporterCommand.kt, reporter/src/funTest/kotlin/reporters/ExcelReporterTest.kt, reporter/src/funTest/kotlin/reporters/NoticeReporterTest.kt, reporter/src/funTest/kotlin/reporters/StaticHtmlReporterTest.kt, reporter/src/funTest/kotlin/reporters/WebAppReporterTest.kt, reporter/src/main/kotlin/Reporter.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/NoticeReporter.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, reporter/src/main/kotlin/reporters/WebAppReporter.kt
This required some refactoring to not determine the report names
internally so their existence can be checked beforehand.
"generateReport()" now takes an "OutputStream" instead of a "File" which
also has the advantage that fewer temporary files neeed to be created in
the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1219)
=> ReporterCommand: Only require the individual report files to not exist

model/src/main/kotlin/CopyrightFinding.kt, model/src/main/kotlin/LicenseFinding.kt, model/src/main/kotlin/Mappers.kt, model/src/main/kotlin/ScanSummary.kt, model/src/main/kotlin/TextLocation.kt, model/src/test/assets/expected-scan-results.yml, model/src/test/kotlin/LicenseFindingTest.kt, model/src/test/kotlin/ScanResultContainerTest.kt, reporter-web-app/src/components/PackageScansSummary.js, reporter/src/main/kotlin/reporters/NoticeReporter.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanCodeTest.kt, utils/src/main/kotlin/Extensions.kt
Storing the file and line numbers where the copyrights associated to a
license were detected is a precondition for implementing file based
excludes. Otherwise it would not be possible to remove only the copyrights
found in a certain file.
Note that some refactorings in `ScanCode` and `ScanCodeTest` will happen in a separate PR to not make this one bigger as necessary. Also `LicenseFindingsMap` will be removed in another PR as it is not required anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1221)
=> LicenseFinding: Store locations of detected copyrights

gradle.properties
This reverts commit 5ec3169 as it seems to be causing
Caused by: java.lang.OutOfMemoryError: Metaspace
on AppVeyor CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1228)
=> Revert "Gradle: Enable parallel compilation of independent source sets"

.appveyor.yml, gradle.properties
This is a new feature in Kotlin 1.3.20. Do not enable that feature on
AppVeyor CI, though, as we otherwise get
Caused by: java.lang.OutOfMemoryError: Metaspace
over there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1229)
=> Gradle: Enable parallel compilation of independent source sets

cli/src/main/kotlin/commands/AnalyzerCommand.kt, cli/src/main/kotlin/commands/EvaluatorCommand.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, cli/src/main/kotlin/commands/ScannerCommand.kt
Using an absolute path is not enough to get rid of e.g. the trailing "."
in
/Users/d029788/src/go/src/github.com/gardener/gardener/.
so normalize, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1234)
=> cli: Normalize paths in potentially user-facing output

model/src/main/kotlin/Provenance.kt, scanner/src/main/kotlin/LocalScanner.kt
To signal an unknown download time. Use this in places where the
download time actually is unknown and previously was simply set to the
start time if the scan.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1238)
=> model: Allow an empty downloadTime for Provenance

scanner/src/funTest/kotlin/scanners/FileCounterTest.kt, test-utils/src/main/kotlin/Utils.kt
This way we can also use it in FileCounterTest and get rid of its custom
patch function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1237)
=> Allow patchActualResult() to also patch the download time

analyzer/src/main/kotlin/managers/GoDep.kt, utils/src/main/kotlin/Extensions.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1235)
=> Safe copy recursively

README.md, cli/src/main/kotlin/commands/ScannerCommand.kt, model/src/main/kotlin/AccessStatistics.kt, model/src/main/kotlin/ScanRecord.kt, model/src/main/kotlin/config/ArtifactoryStorageConfiguration.kt, model/src/main/kotlin/config/ScannerConfiguration.kt, model/src/test/kotlin/ScannerRunTest.kt, model/src/test/kotlin/config/ArtifactoryStorageConfigurationTest.kt, reporter/src/funTest/assets/NPM-is-windows-1.0.2-scan-result.json, reporter/src/funTest/assets/npm-test-with-exclude-scan-results.yml, reporter/src/funTest/assets/npm-test-without-exclude-scan-results.yml, reporter/src/funTest/assets/static-html-reporter-test-input.yml, scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml, scanner/src/funTest/kotlin/HttpStorageTest.kt, scanner/src/funTest/kotlin/scanners/FileCounterTest.kt, scanner/src/main/kotlin/ArtifactoryStorage.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/ScanResultsStorage.kt, scanner/src/main/kotlin/Scanner.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanResultsStorageTest.kt
The interface is not intended to be used as a temporary cache but as a
permanent storage for scan results.
Along the way rename `CacheStatistics` to `AccessStatistics` as the class
could be used also in other places than the storage and fix the README
section about storages which was not updated in 2307b72.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1247)
=> Rename `ScanResultsCache` to `ScanResultsStorage`

analyzer/src/funTest/kotlin/BabelTest.kt, analyzer/src/funTest/kotlin/BowerTest.kt, analyzer/src/funTest/kotlin/BundlerTest.kt, analyzer/src/funTest/kotlin/GoDepTest.kt, analyzer/src/funTest/kotlin/GradleAndroidTest.kt, analyzer/src/funTest/kotlin/GradleKotlinScriptTest.kt, analyzer/src/funTest/kotlin/GradleLibraryTest.kt, analyzer/src/funTest/kotlin/GradleTest.kt, analyzer/src/funTest/kotlin/MavenTest.kt, analyzer/src/funTest/kotlin/NpmTest.kt, analyzer/src/funTest/kotlin/NpmVersionUrlTest.kt, analyzer/src/funTest/kotlin/PhpComposerTest.kt, analyzer/src/funTest/kotlin/PipTest.kt, analyzer/src/funTest/kotlin/StackTest.kt, analyzer/src/funTest/kotlin/YarnTest.kt, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/PackageManagerFactory.kt, analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/CocoaPods.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/PIP.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/SBT.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/Unmanaged.kt, analyzer/src/main/kotlin/managers/Yarn.kt
Overriding toString() often is a bad idea to due hard-to-track
side-effects. Instead, use a dedicated "managerName" property and
explicitly define each package manager name only once for both package
manager and package manager factory classes, avoiding the name to be
deduced multiple times from the class name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1251)
=> analyzer: Do not override toString() for the package manager name

analyzer/src/main/kotlin/PackageManager.kt
An individual file cannot be null here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1256)
=> PackageManager: Simpify code a bit when filtering files

cli/src/main/kotlin/commands/ReporterCommand.kt, reporter/src/main/kotlin/Reporter.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/NoticeReporter.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, reporter/src/main/kotlin/reporters/WebAppReporter.kt
Similar to like we did for the package managers and scanners before.
The implementation is slightly simpler in this case as for the reporter
no factory class is required because the base class already has a
constructor with no arguments that can be used directly with
ServiceLoader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1262)
=> reporter: Do not override toString() for the reporter name

cli/src/main/kotlin/commands/RequirementsCommand.kt
This makes the command work again for package managers and scanners.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1265)
=> RequirementsCommand: Account for changed constructor signatures

cli/src/main/kotlin/Main.kt
Because a member of the team has a demoscene background ;-)
Generated with:
http://patorjk.com/software/taag/#p=display&f=Graffiti&t=ORT
Note that the tool versions are now not shown anymore, but so far that
map is not populated anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1269)
=> Main: Add an ASCII logo for ORT

.appveyor.yml, .travis.yml, analyzer/src/main/kotlin/managers/Yarn.kt, cli/docker/Dockerfile
This seems to fix an issue on AppVeyor / Windows where a link to the
jsesc binary could not be created, see
https://ci.appveyor.com/project/heremaps/oss-review-toolkit/builds/22167822#L2031
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1274)
=> Upgrade Yarn to version 1.13.0

analyzer/src/main/kotlin/Analyzer.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/PIP.kt, analyzer/src/main/kotlin/managers/Stack.kt, cli/src/main/kotlin/commands/DownloaderCommand.kt, downloader/src/main/kotlin/Downloader.kt, model/src/main/kotlin/AnalyzerResult.kt, model/src/main/kotlin/Identifier.kt, model/src/main/kotlin/Mappers.kt, model/src/main/kotlin/Package.kt, model/src/main/kotlin/PackageCuration.kt, model/src/test/kotlin/IdentifierTest.kt, model/src/test/kotlin/OrtResultTest.kt, model/src/test/kotlin/PackageCurationTest.kt, model/src/test/kotlin/ProjectTest.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, scanner/src/main/kotlin/ArtifactoryStorage.kt, scanner/src/main/kotlin/LocalScanner.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1266)
=> Do not override toString() for the Identifier anymore

reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, spdx-utils/src/main/kotlin/SpdxExpression.kt
Add a function to get all license IDs from an `SpdxExpression`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1285)
=> Spdx all licenses

reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
Unfortunately, we display multiple issues with potentially different
severities in a single row, so there is no single correct color.
However, hard-coding the error color is not the best we can do. Instead,
use the color for the worst severity, and also take resolutions into
account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1294)
=> StaticHtmlReporter: Do not hard-code issue rows to error color

analyzer/src/main/kotlin/managers/Maven.kt
In SBT mode, i.e. if the Maven class was instanciated by the SBT class,
"managerName" is already set to "SBT", so this condition can be removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1297)
=> Maven: Minor code simplification regarding SBT mode

reporter/src/main/kotlin/reporters/NoticeReporter.kt
Public domain licenses do not require attribution. Also improve the
check to include "public-domain-disclaimer" which is used by ScanCode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1313)
=> NoticeReporter: Do not try to add the texts for public domain licenses

spdx-utils/src/main/kotlin/Extensions.kt, spdx-utils/src/test/kotlin/ExtensionsTest.kt
Allow only infixes which we know to be namespaces. This prevents e.g.
"LicenseRef-no-public-domain" to be regarded as "public domain" in the
"no" namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1314)
=> Extensions: Make isLicenseRefTo() stricter

downloader/src/main/kotlin/vcs/GitRepo.kt
Running "sync" itself already creates an info log entry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1322)
=> GitRepo: Remove a superfluous info log statement

downloader/src/main/kotlin/Downloader.kt
`URL.readBytes()` can throw an `IOException`, so instead of catching the
specific `FileNotFoundExceptoin` and `MalformedURLException` catch their
parent `IOException`. Also check if the POM URL is empty before trying
to download it to use a more precise exception message in this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1320)
=> downloader: Improve exception handling in `downloadPomArtifact()`

downloader/src/main/kotlin/Downloader.kt
The calling code catches the `DownloadException` and initializes its
cause which fails if the exception already has a cause.
This is a fixup for 4d01427.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1324)
=> downloader: Do not set the exception cause in `downloadPomArtifact`

.appveyor.yml, .travis.yml, build.gradle
See https://guides.gradle.org/creating-build-scans/.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1325)
=> Gradle: Enable the build scan plugin for (non-scheduled) CI builds

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
The MarkupSafe dependency was upgraded to version 1.1.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1329)
=> PipTest: Update expected flask test results

analyzer/src/funTest/assets/projects/external/grpc-bundler-expected-output.yml, analyzer/src/funTest/kotlin/vcs/GitRepoTest.kt, analyzer/src/main/kotlin/Analyzer.kt, downloader/src/main/kotlin/WorkingTree.kt, downloader/src/main/kotlin/vcs/GitRepo.kt, downloader/src/main/kotlin/vcs/GitWorkingTree.kt, downloader/src/test/kotlin/GitTest.kt, evaluator/src/test/kotlin/EvaluatorTest.kt, model/src/main/kotlin/Repository.kt, scanner/src/main/kotlin/LocalScanner.kt
Nested repositories are submodules for Git and projects for Git-Repo.
Capture those nested repositories and add them to the ORT result file.
This is a prerequisite to fix the issue that definition file paths of
different projects can be identical and therefore ambiguous, because
they are always relative to the nested repository, not the root
repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1332)
=> Capture nested repositories for Git and Git-Repo

.appveyor.yml, downloader/src/main/kotlin/vcs/GitRepo.kt
The current stable release 1.13.2 of git-repo now has all Windows patches
included [1], so use that one instead of latest master.
[1] https://groups.google.com/d/topic/repo-discuss/0V4RSOD3QCc/discussion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1341)
=> GitRepo: Do not use latest master on Windows anymore

analyzer/src/main/resources/META-INF/services/com.here.ort.analyzer.PackageManagerFactory, downloader/src/main/resources/META-INF/services/com.here.ort.downloader.VersionControlSystem
While the order in these files determines the order in which classes are
instantiated, we do not really care about the order of instantiation and
having a defined order makes maintenance easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1347)
=> Sort contents of services files alphabetically

analyzer/src/main/kotlin/managers/NPM.kt, analyzer/src/main/kotlin/managers/Yarn.kt
As ORT does not actually run the Yarn package we should not fail if a
dependency is not compatible with the installed node version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1352)
=> analyzer: Add `--ignore-engines` option to `yarn install`

analyzer/src/main/kotlin/managers/Bundler.kt
While OkHttp as a built-in retry mechanism [1] it does not kick in on
"bad gateway" responses.
[1] https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#retryOnConnectionFailure-boolean-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1355)
=> Bundler: Retry when RubyGems reports "bad gateway"

gradle.properties, scanner/build.gradle, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/Scanner.kt
To make better use of the resources use Kotlin coroutines to make the
local scanner multithreaded. Use separate fixed size thread pools for
scanning source code and for downloading results from the cache.
As scanning itself already uses multiple threads, at least with
ScanCode, limit the thread pool for scanning to a single thread.
Downloading cached results mainly uses network bandwidth for
transferring the results and the CPU for deserialization. To improve
throughput use a thread pool size of 5.
As this change makes it harder to read the log output add a few lines
and add the index of the package to all log statements in
`LocalScanner`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> scanner: Use multiple threads in `LocalScanner`

model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/Repository.kt, model/src/test/kotlin/OrtResultTest.kt, reporter/src/funTest/assets/static-html-reporter-test-expected-output.html, reporter/src/funTest/assets/static-html-reporter-test-input.yml, reporter/src/main/kotlin/reporters/ReportTableModel.kt, reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
Use the recently added information about nested VCS in the OrtResult to
determine the full path to the definition file of a project. This is
different to `Project.definitionFilePath` if the project is located
inside a nested VCS, because the definition file path is always relative
to the VCS that contains the file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1350)
=> reporter: Show full path to definition file in static HTML report

downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/GitRepo.kt, downloader/src/main/kotlin/vcs/Mercurial.kt, downloader/src/main/kotlin/vcs/Subversion.kt
For VCS, 35af37f was wrong saying we would "not really care about the
order of instantiation", because probing a VCS (e.g. from a URL) might
take a few seconds, so we want to probe more likely VCS first. Instead
of relying on the declaration order in the services file, which is
error-prone at the latest when loading VCS plugins provided by
third-parties on the classpath, introduce a dedicated priority.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1358)
=> VCS: Introduce a priority for probing

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml, analyzer/src/main/kotlin/managers/NPM.kt
See https://docs.npmjs.com/files/package.json#repository and
https://github.com/npm/cli/releases/tag/v6.8.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1356)
=> NPM: Add support for the new "directory" field for a repository

analyzer/src/main/kotlin/managers/SBT.kt, utils/src/main/kotlin/Utils.kt
If the files passed to this function share a common prefix in the
filename part this was part of the returned prefix. For example, passing
"/dir/file-1" and "/dir/file-2" returned "/dir/file-". This was wrong
because the result is expected to be an existing directory. To fix this
ensure that the returned value is a directory and if not return the
parent file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1359)
=> utils: Ensure that `getCommonFilePrefix` returns a directory

scanner/src/main/kotlin/LocalScanner.kt
Otherwise a sentence like "Scanning [...] in thread scan" reads a bit
odd as "thread scan" sounds like a composite noun.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1362)
=> LocalScanner: Quote thread names for clarity

downloader/src/main/kotlin/Downloader.kt
If a source artifact has no hash to verify, skip the verification and
print a warning instead of aborting the downloader with an exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1366)
=> downloader: Skip verification if a source artifact has no hash

analyzer/src/main/kotlin/PackageJsonUtils.kt
If a package.json cannot be parsed, log the exception and continue with
a reasonable default value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1363)
=> PackageJsonUtils: Handle exceptions caused by invalid package.json files

model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/Repository.kt, model/src/main/kotlin/config/Excludes.kt, model/src/main/kotlin/config/PathExclude.kt, model/src/main/kotlin/config/PathExcludeReason.kt, model/src/test/kotlin/config/ExcludesTest.kt, reporter/src/funTest/assets/static-html-reporter-test-expected-output.html, reporter/src/funTest/assets/static-html-reporter-test-input.yml, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/NoticeReporter.kt, reporter/src/main/kotlin/reporters/ReportTableModel.kt, reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
Add path excludes and use them to exclude projects. Using path excludes for excluding files from the license scan results ẃill be implemented in a separate PR. See the commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1360)
=> Path excludes projects

model/src/main/kotlin/Package.kt, model/src/main/kotlin/PackageCurationData.kt, model/src/main/kotlin/VcsInfo.kt, model/src/main/kotlin/VcsInfoCuration.kt, model/src/test/kotlin/PackageCurationTest.kt, model/src/test/kotlin/PackageTest.kt
Sometimes we need to enforce the use of a source artifact even if VCS
information is present. A convenient way to do this is to clear the VCS
URL which previously was not possible as a blank curated VCS URL triggered
the use of original VCS URL. Support blank VCS URLs in curation by
introducing a dedicated VcsInfoCuration class with nullable properties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1367)
=> model: Allow to curate VCS information with empty properties

reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt
If a project is excluded using a path exclude, do not add analyzer or
scanner issues of the project to the error summary, like it is already
done for projects excluded by project excludes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1379)
=> reporter: Respect path excludes in error summary

cli/docker/Dockerfile
To enable building the Docker image again as the previous version is not
available anymore in Debian Sid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1382)
=> Dockerfile: Upgrade Bundler to version 1.17.3-3

model/src/main/kotlin/Provenance.kt, scanner/src/funTest/kotlin/HttpStorageTest.kt
If the (non-empty) hashes match, the source code is the same. This
added earlier check supports the case where the source artifact URLs
differ (e.g. because the artifact was retrieved from a cache) although
the artifacts are in fact the same.
Also add some more code comments along the way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1395)
=> Provenance: Allow only source artifact hashes to match

downloader/src/main/kotlin/vcs/Git.kt, downloader/src/test/kotlin/GitTest.kt
The changes are confirmed to work as expected on Linux. However, while
doing no harm on Windows compared to before, the test hangs on Windows,
so only enable it on non-Windows for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1402)
=> Git: Suppress interactive prompts for credentials

.travis.yml
Travis from time to time seems to silently do patch-level upgrades to
PHP, resulting in an exact version like 7.1.19 to not be found anymore.
Effectively revert 2dbe831 to again allow patch-level version changes as
Travis by now seems to have fixed the issue with the "7.1" alias from back
then.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1408)
=> Travis: Accept patch-level PHP version changes

.appveyor.yml
E.g. after clearing the build cache the directory may not exist yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1414)
=> AppVeyor: Ensure  %HOME%\.gradle exists

model/src/main/kotlin/AnalyzerResult.kt, model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/Package.kt, model/src/main/kotlin/PackageCurationData.kt, model/src/main/kotlin/PackageCurationResult.kt, model/src/main/kotlin/PackageReference.kt, model/src/main/kotlin/Project.kt, model/src/main/kotlin/Provenance.kt, model/src/main/kotlin/RemoteArtifact.kt, model/src/main/kotlin/ScanRecord.kt, model/src/main/kotlin/ScanResult.kt, model/src/main/kotlin/ScanResultContainer.kt, model/src/main/kotlin/ScannerDetails.kt, model/src/main/kotlin/Scope.kt, model/src/main/kotlin/VcsInfo.kt, model/src/test/kotlin/VcsInfoTest.kt, reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt
I'm proposing to move custom data out of the primary constructor of data classes so that the auto-generated `equals()` does not take custom data into account.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1394)
=> Custom data no equals

cli/src/main/kotlin/commands/EvaluatorCommand.kt, model/src/main/kotlin/Model.kt, scanner/src/main/kotlin/Scanner.kt
This was broken as of d824a74 because copy() does not include "data"
anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1417)
=> Fix passing on OrtResult meta-data when amending results

analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/dotnet/subProjectTest/test.csproj, analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/nuget/packages.config, analyzer/src/funTest/kotlin/DotNetSupportTest.kt, analyzer/src/funTest/kotlin/DotNetTest.kt, analyzer/src/funTest/kotlin/NugetTest.kt, analyzer/src/main/kotlin/DotNetSupport.kt, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/Nuget.kt, analyzer/src/main/resources/META-INF/services/com.here.ort.analyzer.PackageManagerFactory, analyzer/src/test/kotlin/PackageManagerTest.kt
This pull request introduces two new managers (dotnet and Nuget) that handle .NET dependency management. 
Added:
- Two Managers:
- DotNet: dotnet manager analyses files ending with ".csproj"
- Nuget: nuget manager analyses files "package.config"
- DotNetSupport: is responsible for mapping the dependencies on the model. The information is retrieved from the Nuget API and dependencies are crawled
- Tests:
- DotNetSupportTest: tests special cases for dependency resolution 
- coverage is at  96% for the classes and 88% of lines
- NugetTest: tests a test nuget file included in funTests/assets//projects/synthetics 
- coverage is at  75% for the classes and 91% of lines
- DotNetTest: tests a test dotnet file included in funTests/assets/projects/synthetics 
- coverage is at  75% for the classes …
=> DotNet: added dotnet and nuget managers including tests

spdx-utils/src/main/kotlin/SpdxErrorListener.kt, spdx-utils/src/main/kotlin/SpdxExpression.kt, spdx-utils/src/test/kotlin/SpdxExpressionLexerTest.kt
Ensure that always only our custom error listener is set to avoid errors
being written to the console. This e.g. avoids
line 1:4 token recognition error at: ':'
being written to stderr when parsing the URL
http://jquery.org/license
as an SpdxExpression.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1429)
=> SpdxExpression: Remove the default ConsoleErrorListener

.travis.yml
This basically cherry-picks 6c32a72 as Travis silently changed its
behavior again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1446)
=> Travis: Accept patch-level PHP version changes, again

analyzer/src/main/kotlin/PackageCurationProvider.kt, analyzer/src/main/kotlin/YamlFilePackageCurationProvider.kt, analyzer/src/test/assets/package-curations.yml, analyzer/src/test/kotlin/YamlFilePackageCurationProviderTest.kt, docs/Configuration.md, model/src/main/kotlin/Identifier.kt, model/src/main/kotlin/PackageCuration.kt, model/src/test/kotlin/IdentifierTest.kt
This allows to create a single curation that matches multiple versions
of the same package. For Ivy version specifiers see
http://ant.apache.org/ivy/history/2.4.0/settings/version-matchers.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1445)
=> Support Ivy version patterns in curation data

downloader/src/funTest/kotlin/BeanUtilsTest.kt, downloader/src/funTest/kotlin/CvsDownloadTest.kt, downloader/src/funTest/kotlin/MercurialDownloadTest.kt, downloader/src/funTest/kotlin/SubversionDownloadTest.kt, downloader/src/test/kotlin/CvsTest.kt, downloader/src/test/kotlin/MercurialTest.kt, downloader/src/test/kotlin/SubversionTest.kt, downloader/src/test/kotlin/VersionControlSystemTest.kt
This potentially shadows test breakages if a developer / CI has not the
required tool installed. Better fail hard to force installation of the
respective tool to verify the test passes afterwards.
Disabling tests if a tool is not installed was an experiment based on
the discussions in issues #398 and #416, but we decided that not
shadowing any potential test breakages outweights nice looking reports
for seemingly passing test suites with skipped test cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1453)
=> downloader: Do not enable tests depending on whether tools are installed

analyzer/src/main/kotlin/Analyzer.kt, analyzer/src/main/kotlin/FilePackageCurationProvider.kt, analyzer/src/test/kotlin/FilePackageCurationProviderTest.kt
Rename `YamlFilePackageCurationProvider` to `FilePackageCurationProvider`,
because the provider can also read JSON and XML files, so the old name was
giving the false impression that only YAML files are supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1454)
=> analyzer: Remove `Yaml` from `YamlFilePackageCurationProvider`

analyzer/src/main/kotlin/PackageManager.kt
Because Martin likes that better than "= Unit" :-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1458)
=> PackageManager: Use {} for an empty function body

evaluator/src/main/kotlin/DependencyRule.kt, evaluator/src/main/kotlin/LicenseSource.kt, evaluator/src/main/kotlin/LicenseView.kt, evaluator/src/main/kotlin/PackageRule.kt, evaluator/src/main/kotlin/Rule.kt, evaluator/src/main/kotlin/RuleMatcher.kt, evaluator/src/main/kotlin/RuleSet.kt
Add a DSL for describing evaluator rules. This is the first iteration
that likely needs more refactoring in the near future. Documentation
will be added later, once it reaches a stable state.
This is just the API, integration with the evaluator will happen separately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1452)
=> evaluator: Add a DSL for writing rules

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml, analyzer/src/funTest/kotlin/vcs/GitRepoTest.kt, downloader/src/main/kotlin/vcs/GitRepo.kt
This argument was accidentally removed in 8191aa8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1469)
=> GitRepo: Re-introduce "--no-repo-verify" to avoid the dependency on GPG

model/src/main/kotlin/OrtResult.kt
The auto-generated copy function does not adhere to the data attribute
as it is not declared via the primary constructor.
Manually copy that data in order to ensure that replaceConfig() does
nothing in addition to just replacing the config.
This fixes up d824a743.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1479)
=> OrtResult: Make sure replaceConfig() keeps the custom data

model/src/main/kotlin/Mappers.kt
That is better than creating our own ones using the factories as they
add format-specific utility methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1481)
=> Mappers: Use Jackson's dedicated mapper sub-classes

analyzer/src/funTest/kotlin/DotNetTest.kt, analyzer/src/funTest/kotlin/NuGetTest.kt, analyzer/src/main/kotlin/DotNetSupport.kt, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/NuGet.kt, model/src/main/kotlin/OutputFormat.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1482)
=> Miscellaneous improvements to DotNet / NuGet code

analyzer/src/funTest/kotlin/NuGetTest.kt, analyzer/src/main/kotlin/managers/DotNet.kt, analyzer/src/main/kotlin/managers/NuGet.kt
Because they do not have to be, which simplifies the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1485)
=> DotNet/NuGet: Make some types non-nullable

downloader/src/test/kotlin/CvsTest.kt
And comment for the others why they are disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1492)
=> CvsTest: Enable a test again that does not actually call the CVS CLI

evaluator/src/main/kotlin/RuleSet.kt
Use the already collected license findings for better performance. This
finishes 4d96777.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1493)
=> evaluator: Use the collected license findings instead of collecting again

analyzer/src/funTest/assets/projects/synthetic/dotnet/subProjectTest/test.csproj, analyzer/src/funTest/assets/projects/synthetic/nuget/packages.config, analyzer/src/funTest/kotlin/DotNetSupportTest.kt
DotNet/NuGet: Fix test projects to use an existing jQuery version
If a non-existing version is used, NuGet falls back to using the most
recent version. Using such non-existing versions in test is undesirable
as it requires to update the tests whenever a new version is released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1504)
=> DotNet/NuGet: Fix test projects to use an existing jQuery version

reporter/src/funTest/assets/static-html-reporter-test-expected-output.html, reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt
Do not repeat the source of the violation in the description field and
remove the timestamp, because it is not relevant for rule violations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1506)
=> StaticHtmlReporter: Improve presentation of rule violations

model/src/main/kotlin/CuratedPackage.kt, model/src/main/kotlin/OrtResult.kt
Sometimes it makes sense to work on not curated representations
of a package rather than on curated ones. The implementation of
policies enforcing rules on package meta data would ideally consume
not curated packages.
Add a function to support such use cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1497)
=> OrtResult: Add a function to lookup `uncurated` packages

analyzer/src/main/kotlin/managers/Stack.kt, cli/src/main/kotlin/commands/DownloaderCommand.kt, model/src/main/kotlin/Hash.kt, model/src/main/kotlin/HashAlgorithm.kt, model/src/main/kotlin/Provenance.kt, model/src/main/kotlin/RemoteArtifact.kt, model/src/test/assets/deprecated-errors-scan-results.yml, model/src/test/assets/deprecated-licenses-scan-results.yml, model/src/test/assets/expected-scan-results.yml
Previously, UNKNOWN was used for two cases:
1) An existing hash value of an unknown hash algorithm.
2) A non-existing hash value of no hash algorithm.
However, for case 1) we can still compare actual and expected hash
values by string even without knowing the algorithm. Because of this it
makes sense to distinguish these two cases by introducing NONE for case
2) and keeping UNKNOWN for case 1).
Also fix test data accordingly so that only empty hash values use NONE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1509)
=> Introduce a NONE hash to distinguish from UNKNOWN

analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml, analyzer/src/main/kotlin/DotNetSupport.kt
The NuGet hashes are in fact SRI-style hashes that are Base64-encoded,
so decode them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1516)
=> DotNet/NuGet: Decode SRI hashes

model/src/main/kotlin/OrtResult.kt, reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt
Fix the matching of path excludes and license findings. See the commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1522)
=> Fix path excludes

spdx-utils/src/main/antlr/com/here/ort/spdx/SpdxExpression.g4, spdx-utils/src/test/kotlin/SpdxExpressionParserTest.kt
Scancode also uses license references for detected exceptions. These
references could not be used, because the lexer turns them into a
`LICENSEREFERENCE` token, which is not a valid input for the
`licenseExceptionExpression` rule.
To fix this, move the "LicenseRef-" part of `LICENSEREFERENCE`, which is
a valid subset of `IDSTRING`, to a separate rule, and allow this in the
`licenseExceptionExpression` rule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1524)
=> spdx-utils: Allow parsing license references as exceptions

spdx-utils/src/main/antlr/com/here/ort/spdx/SpdxExpression.g4, spdx-utils/src/test/kotlin/SpdxExpressionParserTest.kt
This is a fixup for 91056e1 which did not acutally fix the issue.
The problem was that the first part of the `REFERENCE` rule was
optional, as a result any license reference was always put in a
`REFERENCE` token, but never in a `LICENSEREFERENCE` token by the lexer.
Fix this by making two separate rule for license references and document
references, to prevent overlap in the rules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1529)
=> spdx-utils: Fix parsing license references as exceptions

downloader/src/main/kotlin/Downloader.kt
This changes the error message to like it was before eeea7ec so it again
contains the name of the hash algorithm to make the DownloaderTest pass
again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1528)
=> Downloader: Fix an error message to make DownloaderTest pass again

model/src/main/kotlin/CopyrightFinding.kt, model/src/main/kotlin/Hash.kt, model/src/main/kotlin/LicenseFinding.kt, model/src/main/kotlin/Mappers.kt, model/src/main/kotlin/OrtIssue.kt, model/src/main/kotlin/VcsInfo.kt, model/src/main/kotlin/config/AnalyzerConfiguration.kt
This keeps all (de-)serialization code alongside the class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1527)
=> model: Use annotations to add custom (de-)serializers

README.md
Linking to another point in the README makes more sense than linking to
the source code here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1533)
=> README: Link to the anchor of supported package managers

analyzer/build.gradle.kts, cli/build.gradle.kts, downloader/build.gradle.kts, evaluator/build.gradle.kts, model/build.gradle.kts, reporter/build.gradle.kts, scanner/build.gradle.kts, spdx-utils/build.gradle.kts, test-utils/build.gradle.kts, utils/build.gradle.kts
Core plugins can be directly added by their name. If their name does not
only consist of letters, it must be enclosed in backticks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1536)
=> Gradle: Use Kotlin syntactic sugar to add plugins

settings.gradle.kts
It seems that the Kotlin DSL behavior has changed at some point and core
plugins now report "org.gradle" instead of null as their namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1538)
=> Gradle: Update the namespace check for plugins

model/src/main/kotlin/ScanResult.kt, scanner/src/main/kotlin/Scanner.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, spdx-utils/src/main/kotlin/SpdxUtils.kt
Filter the scan results for projects to only contain relevant license and copyright findings. See the commit messages for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1537)
=> Filter project scan results by definition file paths

gradle.properties
See https://bmuschko.github.io/gradle-docker-plugin/#change_log. Despite
version 4.9.0 being marked as "TBA" on that page, it was actually
already released. Also see
https://github.com/bmuschko/gradle-docker-plugin/issues/822
about that issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1540)
=> Gradle: Upgrade Docker plugins to version 4.9.0

model/src/main/kotlin/ScanResult.kt
The intention of the code was to not filter out any license findings in any
LICENSE file(s) which makes sense. It was broken as the wrong parameter was
passed to the matcher.
This is a fix-up for 987a541c.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1545)
=> ScanResult: Fix-up the filtering of license findings

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
The SHA1 of the v2.1.15 tag in the spdx/tools repository has changed.
Probably the history of the repository was rewritten [1].
[1] https://github.com/spdx/tools/issues/193#issuecomment-501356678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1553)
=> analyzer: Fix expected results for GitRepoTest

scanner/src/main/kotlin/Scanner.kt
If the definition file of a project is in the root of the repository,
all license findings which were not in the definition file itself or in
a license file were removed by `filterProjectScanResults`, because
`substringBeforeLast("/")` returns the definition file path itself
instead of an empty string.
To fix this, do not filter at all if the definition file is in the root
of the repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1551)
=> scanner: Fix filtering of project scan results

analyzer/src/main/kotlin/managers/Npm.kt, utils/src/main/kotlin/OkHttpClientHelper.kt
Note that if we agree this change to be merged, we should do something similar for other packages managers where we call the respective CLI but also directly access the registry via HTTP, like for Python / PIP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1568)
=> Npm: Read proxy settings from .npmrc for directly querying the registry

cli/src/main/kotlin/commands/ReporterCommand.kt
As of 0ff8c21 it is not necessary to contain a scan result anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1587)
=> ReporterCommand: Correct command line help aout the ORT result file

evaluator/src/main/kotlin/RuleSet.kt, model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/config/Excludes.kt, model/src/test/kotlin/config/ExcludesTest.kt
With a huge amount of projects the evaluator is still slow.
This PR first fixes two low hanging fruits by using lookup instead of loops.
Moreover it fixes several severe bottlenecks of the evaluator and the reporter.
Overall for the large project I used to investigate the evaluator now runs in 1:48min instead of 2.5h.
The HTML reporter takes about 4 minutes instead of 20. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1585)
=> Ort result performance tweaks

downloader/src/main/kotlin/VersionControlSystem.kt
As they each access a shared map resource for caching.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1605)
=> VersionControlSystem: Make forUrl and forDirectory thread safe

analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml, analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml, analyzer/src/main/kotlin/PackageManager.kt
Even if created from a normalized URL, the "type" in vcsFromUrl is
still unnormalized, so normalize the whole VcsInfo afterwards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1606)
=> PackageManager: Normalize (esp. the "type" in) vcsFromUrl

analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml, analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-lockfile.yml, downloader/src/funTest/kotlin/BabelTest.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/test/kotlin/VersionControlSystemTest.kt
To not create the impression it was ever normalized to lower-case like
VcsInfo.normalize() would do it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1608)
=> VersionControlSystem: Consistently use an unnormalized type in splitUrl()

.appveyor.yml, .travis.yml, analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml, analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml, analyzer/src/funTest/kotlin/StackTest.kt, analyzer/src/main/kotlin/managers/Stack.kt
See https://github.com/commercialhaskell/stack/releases/tag/v2.1.1 for
details about the new flag. Due to the nature of its implementation, GHC
and the runtime system (and their dependencies) are no longer listed as
explicit dependencies.
This partly reverts cbe8aae as "stack" is again always installed, but the
huge part of installing GHC via "stack setup" can now be omitted.
In order to make the "stack.yaml" work with Stack 2.1.1, the
"quickcheck-state-machine" project had to be updated to latest master,
which does not anymore come with the example project, see
advancedtelematic/quickcheck-state-machine@c2e0682
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Stack: Use the "--global-hints" flag to bypass the need for an installed GHC

evaluator/src/main/resources/rules/no_gpl_declared.kts
Add the second parameter to the `error` function call. This is a fixup
for e559b3e. The issue was not detected by the `EvalutorTest` because
Kotlin's own `error` function was called instead, so the script could
still be compiled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1609)
=> evaluator: Fix the no_gpl_declared.kts script

downloader/src/main/kotlin/vcs/Git.kt, downloader/src/main/kotlin/vcs/GitWorkingTree.kt, downloader/src/test/kotlin/GitTest.kt
As it turns out, using an empty string does not work reliably on all
platforms. Instead, use "echo" as a universal dummy command which seems
to work well on Linux and Windows so we can avoid suppressing any
prompt for input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1622)
=> Git: Do not set core.askpass to an empty string to suppress prompts

model/src/main/kotlin/Repository.kt
The intention of the mentioned commit obviously was to compare the
`type` of both instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1627)
=> Repository: Fix-up 74b6a60e

utils/src/main/kotlin/ArchiveUtils.kt
Only 7-Zip files cannot be unpacked from an InputStream as the underlying
API requires a File.
Add / improve documentation along the way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1626)
=> ArchiveUtils: Support unpacking from an InputStream

docker/build.sh, docker/run.sh, docker/run/Dockerfile, docker/test.sh
Instead of checking for the existence of the "ort-build" Docker image,
check for the existence of the required "ort.tar". With the recent change
in 5e82e01 to properly set the Gradle project version, the "ort.tar"
contains the version string which is also taken into account here.
Fixes #1637.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1638)
=> docker: Fix the check whether running build.sh is required

analyzer/src/funTest/assets/projects/external/godep-expected-output.yml, analyzer/src/funTest/assets/projects/external/qmstr-expected-output.yml, analyzer/src/funTest/assets/projects/external/sprig-expected-output.yml, analyzer/src/main/kotlin/managers/GoDep.kt, downloader/src/test/kotlin/SubversionTest.kt
The Gopkg.toml seems to provide no means to declare a name for
the project but the dependencies are actually referred to by names
constructed from the host and path of the repository URL. As
this would still be ambigious for multi-project repositories use
also the path to the directory containing the definition file.
While not really sure about whether appending the path inside the
repository is correct it seems to be an improvement compared to
using always empty strings as name as was done so before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1646)
=> GoDep: Set the project name based on the definition file URL

analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
This reverts commit 9d01ec7aa7b29e5a1c385a50c9ea697876fda257.
pyparsing 2.4.1 was unpublished, see:
https://github.com/pyparsing/pyparsing/blob/master/CHANGES
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1651)
=> Revert "PipTest: Upgrade the expected pyparsing version to 2.4.1"

.travis.yml
This is a fixup for ef9923a where the task was removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1656)
=> Travis: Do not execute the `cli:dockerBuildImage` task

build.gradle.kts
To not report versions like "2.10.0.pr1" or "1.3.0-RC-1.3.50-eap-5" as
updates. While at it, move the list to a separate variable and sort it
alphabetically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1663)
=> Gradle: Add "eap" and "pr" to the list of non-final version qualifiers

analyzer/src/main/kotlin/managers/Npm.kt
The message is mainly printed in projects using Yarn workspaces and for
projects with many dependencies this can easily generate more than 100M
of logs, so make the message debug instead of info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1671)
=> NPM: Change the log level of a message from info to debug

model/src/main/kotlin/Provenance.kt
Not comparing the hash value in some cases adds an execution
branch and thus makes testing harder. It is not needed as the
performance gains likely are neglectible and thus removed now.
=> Provenance: Simplify the matches() function a bit

scanner/src/main/kotlin/scanners/ScanCode.kt
See https://github.com/nexB/scancode-toolkit/releases/tag/v3.0.2
The ScanCode result JSON format was changed a bit: a json array
named `headers` has been added and the `files_count` node has been
moved underneath it. Adding a fallback to compute that value based
on the distinct paths keeps backwards compatibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1467)
=> Upgrade ScanCode to version 3.0.2

evaluator/src/main/kotlin/LicenseView.kt, evaluator/src/test/kotlin/LicenseViewTest.kt
Adding new license view to enable writing evaluator rules only on concluded or detected licenses
=> evaluator: Add a LicenseView for concluded or detected licenses

cli/src/main/kotlin/Main.kt
The option allows reading parameters from a file, see [1]. The option is
enabled by default, as a result parameters cannot start with "@",
because JCommander then interprets the following characters as a file
path to read parameters from.
As the option is unused and there is no workaround like escaping the
parameter that starts with "@", disable the option.
[1] http://jcommander.org/#__syntax
=> cli: Disable "ExpandAtSign" JCommander option

.detekt.yml
Clear the default value [1] to check test sources, too.
[1] https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml#L548
=> detekt: Clear wildcard excludes

.github/CODEOWNERS
See https://help.github.com/en/articles/about-code-owners.
=> GitHub: Add an initial CODEOWNERS file to auto-assign reviewers

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/python3-django-expected-output.yml, analyzer/src/main/kotlin/managers/Pip.kt
`setup.py` files do provide means for declaring a package name while
`requirements.txt` files don't. Thus in case there is only a `requirements.txt`
but no `setup.py` present in a project's base directory there is no way to
derive a non-ambigious name for the project identifier just from the meta-data
provided in the definition file(s). In fact in that case the name was previously
set to the name of the parent directory of the definition file which is not
very unique and thus leads to duplicate project IDs resulting in an analyzer
error.
As of this change the path to the definition file relavtive to the analyzer root
directory as project name which should be highly likely unique. The path relative
to the VCS root could be used alternatively which I decided against having Git
Repo based …
=> Pip: Assign less ambigious project IDs for `requirements.txt`

analyzer/src/main/kotlin/managers/Pip.kt
**to be merged after https://github.com/heremaps/oss-review-toolkit/pull/1704**
When running pip (freeze) using virtualenv on Ubuntu the package
`pkg-resources` version 0.0.0 incorrectly gets added to the dependency
tree. Strip that package from the result in order to have more consistent
behavior accross platforms. Also the tests (PipTest.kt) now successfully
run on Ubuntu. See also:
https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1635463
=> Pip: Work around an issue with virtualenv on Ubuntu

cli/src/main/kotlin/commands/EvaluatorCommand.kt, model/src/main/kotlin/OrtResult.kt
In order to apply package curations without re-running the analyzer or the
scanner add a parameter which allows overriding the set of applicable
package curations.
Note that this can lead to an inconsistent ORT-file in case the curations take
effect on the input of analyzer or scanner.
=> EvaluatorCommand: Add a parameter for overriding the pkg curations

helper-cli/src/main/kotlin/Main.kt, helper-cli/src/main/resources/log4j2.xml
Some of the commands in helper-cli are calling code that uses the
logger, so allow to set the log level and to enable printing
stacktraces.
=> helper-cli: Add same logging options as used in cli

scanner/src/main/kotlin/storages/FileBasedStorage.kt, scanner/src/test/kotlin/ScanResultsStorageTest.kt
The mechanism was put in place for backwards compatibility with old
cache entries which do not have the later introduced prefix for
ScanCode licenseRefs.
=> FileBasedStorage: Remove the patching of ScanCode LicenseRefs

scanner/src/main/kotlin/scanners/ScanCode.kt
ScanCode 3 has more keys for unknown licenses than ScanCode 2 for which
the mapping was implemented. Map those keys to NOASSERTION as well for
consistency.
=> ScanCode: Map more license keys to NOASSERTION

model/src/main/kotlin/ScanSummary.kt
The function is analog to getSingleLicenseFindings, in fact the code was
copied and incorrectly adjusted, see 67abf886.
=> ScanSummary: Fix-up getSingleCopyrightFindings()

helper-cli/src/main/kotlin/common/Utils.kt
This fixes a nulll pointer exception with the parentFile property.
=> Utils: Expand the tilde for the parent directory

settings.gradle.kts
This way no separate property has to be introduced e.g. for the
"org.jetbrains.kotlin.js" plugin, but the same version as for the main
Kotlin plugin will be used.
=> Gradle: Improve the plugin version property check

downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/test/kotlin/VersionControlSystemTest.kt
Add handling for URLs ending with ".git" to the `splitUrl()` function.
Previously, the `VcsType` of such URLs could not be detected.
=> VCS: Support URLs ending with ".git" in `splitUrl()`

reporter-web-app/src/components/ScanFindingsTable.js
WebApp report crashed in the browser as a variable was undefined after underlying model was refactored.
=> reporter-web-app: Fix app crash after model refactoring

gradle/wrapper/gradle-wrapper.properties
See https://github.com/gradle/gradle/releases/tag/v5.6.2.
=> Upgrade Gradle to version 5.6.2

analyzer/src/main/kotlin/managers/utils/MavenLogger.kt, cli/src/main/resources/log4j2.xml, test-utils/src/main/resources/log4j2.xml, utils/src/main/kotlin/CommandLineTool.kt, utils/src/main/kotlin/Logger.kt, utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/LoggerTest.kt
Improve logging by using one logger per class so the source of logging
can be more easily identified. Consequently, include the logger name and
thread name into the log pattern, so that the pattern now matches the
"configuration equivalent to the default" mentioned at [1].
As the "log" extension property now is only available in the context of
an object (there is no more top-level "log"), simply hard-code the
logger name for MavenLogger.
[1] https://logging.apache.org/log4j/2.x/manual/configuration.html
=> Use separate loggers per class (with individual names)

CONTRIBUTING.md
As several new contributors have asked how to sign the DCO.
=> docs: Update CONTRIBUTING.md to explain signing DCO

analyzer/src/funTest/kotlin/managers/PhpComposerTest.kt, analyzer/src/funTest/kotlin/managers/PubTest.kt, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/Cargo.kt, analyzer/src/main/kotlin/managers/GoDep.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/Pub.kt
Align the lockfile check in all package managers that support a lockfile
to use the same error message.
=> analyzer: Align the lockfile check in package managers

spdx-utils/src/main/kotlin/SpdxLicenseAliasMapping.kt, spdx-utils/src/test/kotlin/SpdxDeclaredLicenseMappingTest.kt, spdx-utils/src/test/kotlin/SpdxLicenseAliasMappingTest.kt
To not accidentally mix up values for SpdxDeclaredLicenseMapping vs.
SpdxLicenseAliasMapping.
=> spdx-utils: Add sanity checks for values of the mapping objects

spdx-utils/src/test/kotlin/SpdxDeclaredLicenseMappingTest.kt, spdx-utils/src/test/kotlin/SpdxLicenseAliasMappingTest.kt
=> spdx-utils: Also test against plain SPDX license ids in mappings

helper-cli/src/main/kotlin/Main.kt, helper-cli/src/main/kotlin/commands/ListPackagesCommand.kt
It seems to be helpful to be able to list all packages matching a given
predicate in order to use that list as input for further processing.
=> helper-cli: Add a command for listing packages

helper-cli/src/main/kotlin/commands/ImportPathExcludesCommand.kt, helper-cli/src/main/kotlin/common/Utils.kt
Add a parameter which allows toggling between either importing all
entries or only updating entries with a matching pattern.
=> ImportPathExcludesCommand: Add an update mode

model/src/main/kotlin/util/FindingsMatcher.kt, model/src/test/kotlin/utils/FindingsMatcherTest.kt
getRootLicense() returns an empty string in case more than one of the
given license findings are matched by the LicenseFileMatcher. In that
case all copyright statements found in files without a license are
being discarded which seems wrong. The existing code and code comments
suggest that the intention of the author was to return any license
found in any of the root license files. Adjust the code to do so in
order to fix the issue.
=> FindingsMatcher: Fix a bug in getRootLicense()

model/src/main/kotlin/util/FindingsMatcher.kt, model/src/test/kotlin/utils/FindingsMatcherTest.kt
In case there are multiple root licenses, no matter if found in a
single or in multiple files, all copyright findings found in files
without licenses are associated with single arbitrary root license.
Thus the links to all other root licenses are missing which results in
underreporting of copyrights in the generated NOTICE files.
Fix this issue by associating the copyrights to all root licenses in
that particular case.
=> FindingsMatcher: Handle mutliple root licenses

downloader/build.gradle.kts, gradle.properties, spdx-utils/build.gradle.kts, utils/build.gradle.kts
The last dependency on commons-codec was removed in 8366286.
=> Gradle: Remove left-over properties for commons-codec

helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
Return null instead of throwing in case the baseDir or the target
file does not exist.
=> ListLicensesCommand: Gracefully handle text location resolution

.github/workflows/rebase.yml
YML-based actions, in contrast to the legacy HCL-based ones, do not
support the neutral exit code 78 from Docker images anymore. This
resulted in bogus failures due to non-zero exit codes for non-"/rebase"
comments.
To avoid this, filter comments early before even running the rebase
action. As unfortunately GitHub Actions do not currently support
conditionals at the job level [1], repeat the condition for every step.
Also, the YML-based actions do not provide a workspace by default
anymore, so use GitHub's "checkout" action to explicitly provide one.
Finally, white at it, also give the workflow, the job, and the steps
proper names.
[1] https://github.community/t5/GitHub-Actions/Github-Actions-CI-CD-Need-optional-jobs/m-p/29696
Signed-off-by: Sebastian Schuberth …
=> GitHub: Fix the automatic rebase workflow

analyzer/src/main/kotlin/Analyzer.kt, scanner/src/main/kotlin/LocalScanner.kt, utils/src/main/kotlin/NamedThreadFactory.kt
The default thread factory used in the thread pool factory methods of
`Executors` uses the naming pattern "pool-$i-thread-$j". Instead we
would like to use more telling names for the analyzer and scanner
threads.
To allow this add a `NamedThreadFactory` class based on the default
thread factory used by `Executors`, that allows to manually set a prefix
for the created threads.
=> Add a `NamedThreadFactory` for naming coroutine threads

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt, spdx-utils/src/main/kotlin/SpdxLicenseAliasMapping.kt, spdx-utils/src/test/kotlin/SpdxDeclaredLicenseMappingTest.kt, spdx-utils/src/test/kotlin/SpdxLicenseAliasMappingTest.kt
This allows to again remove some mappings that only differ in case. The
check itself is not implemented as a unit test this time as that would
require to keep both the case-sensitive map and the case-insensitive map
in the classes.
=> spdx-utils: Make the key lookup for license mappings case-insensitive

spdx-utils/src/test/kotlin/SpdxExpressionTest.kt
=> SpdxExpressionTest: Fix a typo in a test name

model/src/main/kotlin/util/FindingsMatcher.kt
Mainly switch from ```mutable``` to ```immutable``` collections and stop using ```sorted collections``` without need.
=> Minor findings matcher improvements

scanner/src/main/kotlin/ScanResultsStorage.kt
And slightly improve the logging to show the real directory being used.
=> ScanResultsStorage: Support a tilde in the directory for a local file storage

model/src/main/kotlin/Mappers.kt
=> Mappers: Use Jackson's built-in MissingNode as our empty node

model/src/main/kotlin/OrtResult.kt, model/src/main/kotlin/ScanResultContainer.kt, model/src/main/kotlin/ScanSummary.kt, reporter/src/main/kotlin/reporters/NoticeReporter.kt
Looking at the call hierarchy of the ```ScanSummary.licenseFindings``` shows a call tree with not so much shared code. In order to not duplicate the code for
1. applying path excludes
2. matching license to copyright findings
3. applying license finding curation (implementation is unmerged, work in progress)
The goal of this PR is to change the call tree such that all calls to ```ScanSummary.licenseFindings``` go through a single place where 1,2,3 can be done.
For this I have choosen ```OrtResult.collectLicenseFindings()``` thus detected licenses are now accessed always through that function.
Performance wise it seems likely that this implementation is slower, I'm doing some performance testing now and will comment below. If performance change is acceptable then I'd say let's optimize it …
=> Get detected licenses

model/src/main/kotlin/OrtResult.kt
Previously, it was a bit unclear why subprojects were only determined if
they should be excluded. Rewrite the code to make it more obvious (and
performant) that subprojects are removed from the set of all projects.
=> OrtResult: Make the code to exclude subprojects more readable

docs/Configuration.md
Add required keys for LicenseFindingCuration so ORT users are can simply copy-paste the example into their .ort.yml.
=> Configuration.md: Fix-up LicenseFindingCuration example

.ort.yml
Correct license findings with curations so correct ORT report
is generated.
=> .ort.yml: Add license findings curations

README.md
Thanks to @maxhbr for pointing this out.
=> README: Replace the expired Slack link with one that does not expire

utils/src/main/kotlin/Extensions.kt
On Windows the path separator is "\" so we cannot include "/" into the
pattern anymore. Instead of the presence of "/", use the "SHELL"
environment variable as the indicator whether the replacement should
happen, as "SHELL" is also set in Git for Windows' Bash and "Bash on
Ubuntu on Windows".
=> Extensions: Make expandTilde() work in Bash on Windows

scanner/src/main/kotlin/Scanner.kt
This is not a configuration file, but an ORT result file. Also use the
canonical path instead of just the absolute path to resolve e.g.
intermediate "..".
=> Scanner: Fix the message if an ORT result file cannot be found

.ort.yml
Conclude licenses for findings with curations so correct ORT report is generated.
=> .ort.yml: Add more license findings curations

helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt, helper-cli/src/main/kotlin/common/Utils.kt, model/src/main/kotlin/OrtResult.kt
Extend the list licenses command of the helper-cli by parameters for:
- specifying a repository configuration
- optionally applying license finding curations
=> Helper-CLI: Additional params for listing licenses

.github/CODEOWNERS
Ownership is not additive, the last matching one takes precedence, so
all wanted reviewers must be repeated for a specific pattern.
=> CODEOWNERS: Fix adding @tsteenbe

spdx-utils/src/main/kotlin/SpdxException.kt
Derive SpdxException from RuntimeException to make it an unchecked
exception. This makes parse() more convenient to use from Java code as
SpdxException then does not need to be catched or declared as part of a
a method signature, e.g. because some preprocessing already ensured a
correct syntax of the expression.
=> spdx-utils: Make SpdxException an unchecked exception

analyzer/src/main/kotlin/managers/Gradle.kt
The Gradle Tooling API always uses the Gradle Daemon. The default idle
timeout for the Gradle Daemon is 3 hours [1]. Set it to 10 seconds
instead to make sure the Daemon is stopped shortly after the analyzer
has finished analyzing Gradle projects to make sure the runtime is
completely isolated from previous builds [2].
[1] https://docs.gradle.org/current/userguide/build_environment.html
[2] https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:disabling_the_daemon
=> Gradle: Set the idle timout for the Gradle Daemon to 10 seconds

utils/src/main/kotlin/storage/HttpFileStorage.kt
Java's InputStream.readAllBytes() is only available since Java 9, see
https://docs.oracle.com/javase/9/docs/api/java/io/InputStream.html#readAllBytes--
=> HttpFileStorage: Use Kotlin's readBytes() instead of Java's readAllBytes()

utils/src/main/kotlin/storage/FileSaver.kt, utils/src/test/kotlin/storage/FileSaverTest.kt
Add a class to archive files matching configurable patterns in a
`FileStorage`. The archiver will be used by the scanner to archive part
of the scanned files in a future commit.
=> utils: Add the `FileArchiver` class

evaluator/src/test/kotlin/TestData.kt, model/src/main/kotlin/ProjectScanScopes.kt, model/src/main/kotlin/ScanRecord.kt, model/src/test/kotlin/ScannerRunTest.kt, reporter-web-app/public/index.html, reporter-web-app/src/models/ProjectScanScopes.js, reporter-web-app/src/models/ScanRecord.js, reporter/src/funTest/assets/NPM-is-windows-1.0.2-scan-result.json, reporter/src/funTest/assets/npm-test-with-exclude-scan-results.yml, reporter/src/funTest/assets/npm-test-without-exclude-scan-results.yml, reporter/src/funTest/assets/static-html-reporter-test-input.yml, scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
Previously, the YAML output looked like
scanned_scopes:
- id: "Gradle:com.here.ort.gradle.example:lib:1.0.0"
scanned_scopes:
- "compile"
- "testCompile"
ignored_scopes: []
which is confusing due to its nested duplicate "scanned_scopes" field.
Simplify the structure to be
scopes:
- id: "Gradle:com.here.ort.gradle.example:lib:1.0.0"
scanned:
- "compile"
- "testCompile"
ignored: []
but maintain backwards-compatibility through aliases.
=> model: Improve the naming of the fields for scanned / ignored scopes

analyzer/src/main/kotlin/Analyzer.kt
In case `absoluteProjectPath` is a subdirectory of a Git Repo project the
analyzer fails with a NoSuchFileException thrown when it accesses the
`manifest.xml`.
Fix this by executing the Git Repo specific logic only in case the root
path of that Git Repo project is being analyzed.
=> Analyzer: Fix an issue with locateRepositoryConfigurationFile()

spdx-utils/src/main/kotlin/SpdxUtils.kt
Change 1c89ed77 accidentally duplicated those variables instead of
moving them.
=> SpdxUtils: Remove two unused variables

helper-cli/src/main/kotlin/Main.kt, helper-cli/src/main/kotlin/commands/ExportLicenseFindingCurationsCommand.kt, helper-cli/src/main/kotlin/commands/ExportPathExcludesCommand.kt, helper-cli/src/main/kotlin/commands/ImportLicenseFindingCurationsCommand.kt, helper-cli/src/main/kotlin/commands/ImportPathExcludesCommand.kt, helper-cli/src/main/kotlin/common/Utils.kt, model/src/main/kotlin/config/Curations.kt
Curations can now be exported to a file mapping repository URLs to curations.
This can be helpful for managing a global curations file with commonly used entries.
=> helper-cli: Commands for the import / export of curations

helper-cli/src/main/kotlin/commands/ImportLicenseFindingCurationsCommand.kt
The package renaming done by 5eab6e706ef was not reflected in that import
statement and thus broke the compilation. For not yet known reason this
slipped through CI.
=> helper-cli: Fix compile error

model/src/test/kotlin/utils/FindingCurationMatcherTest.kt, model/src/test/kotlin/utils/FindingsMatcherTest.kt
Note, as these specs have no code in non-leaf tests, using
InstancePerLeaf instead of InstancePerTest should be enough.
Also see:
https://github.com/kotlintest/kotlintest/blob/master/doc/isolation_mode.md
=> model: Use isolationMode() instead of the deprecated isInstancePerTest()

.travis.yml
This is a fixup for b9ba83b. Coverage reporting was broken since then.
=> Travis: Add a missing colon to fix coverage reporting

scanner/src/main/kotlin/LocalScanner.kt
This way it is clearer that this huge try block is actually the last
statement in the function.
=> LocalScanner: Move a return out of "try"

analyzer/src/main/kotlin/managers/Pip.kt
Signed-off-by: Craig Barnes <craig.barnes@here.com>
When analyzer is run using the Pip module there is the following error
> Traceback (most recent call last):
>   File "/tmp/ort3241966459477721899generated-virtualenv/lib/python3.7/site-packages/pipdeptree.py", line 17, in <module>
>     from pip._internal import get_installed_distributions
> ImportError: cannot import name 'get_installed_distributions' from 'pip._internal' (/tmp/ort3241966459477721899generated-virtualenv/lib/python3.7/site-packages/pip/_internal/__init__.py)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/tmp/ort3241966459477721899generated-virtualenv/bin/pipdeptree", line 7, in <module>
>     from pipdeptree import main
>   File …
=> updated pipdeptree version from 0.13.0 to 0.13.2

model/build.gradle.kts
E.g. ProcessedDeclaredLicense from "utils" is part of the model API, so
it has to be an API dependency.
=> model: Fix the "utils" project to be an API dependency

model/src/main/kotlin/utils/FindingCurationMatcher.kt, model/src/test/kotlin/utils/FindingCurationMatcherTest.kt
When a single finding actually points to a text location containing
multiple licenses it was not possible before to express those multiple
licenses with a single or with multiple curations as SPDX
expressions are not supported with detected licenses yet and as only the
first matching curation is applied to any license finding.
Implementing support for SPDX expression would allow setting multiple
licenses to a single finding via a curation but doing the implementation
is a bigger task. Until then address this by applying all curations to
have a solution available quickly. That behavior may make sense to keep
even when SPDX expression are supported.
=> FindingCurationMatcher: Apply all matching curations

helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
This is to use a non-negative value to comply with POSIX and
to align with the `cli` module, see be2a4b02 and also
https://stackoverflow.com/questions/47265667/return-code-on-failure-positive-or-negative/47266617#47266617
=> helper-cli: Use exit code 2 in case of command failures

model/src/main/kotlin/licenses/License.kt
The check intentionally does not involve SpdxExpression.validate() in
order to allow using the SPDX's WITH operator allong with custom defined
Ids for exceptions.
=> License: Make the precondition check more strict

analyzer/src/main/kotlin/managers/Pip.kt
We mostly want to check that we have at least version 15.1 here. In order
to support current version 16.7.7 and also future releases, relax the
version check accordingly.
=> Pip: Relax the version check for virtualenv

cli/build.gradle.kts, helper-cli/build.gradle.kts
Our classpath of dependencies got too long to be passed to Java on the
command line on Windows. Work around the issue by using a wildcard
instead of listing all JARs individually as suggested at
https://github.com/gradle/gradle/issues/1989#issuecomment-395001392
=> Work around a classpath issue when running ORT on Windows

analyzer/src/main/kotlin/managers/Gradle.kt, analyzer/src/main/kotlin/managers/Pub.kt, gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/6.0/release-notes.html.
Flutter by default uses the Gradle version that runs the build, which in
this case is the Gradle Tooling API and as of now Gradle 6. However, as
Flutter / the Android Gradle plugin version used by Flutter does not
support Gradle 6 yet, we need a way to downgrade the Gradle version used
for analysis. Introduce a constructor parameter to the Gradle package
manager to explicitly specify the Gradle version to use to solve exactly
that issue.
=> Upgrade Gradle to version 6.0

scanner/src/main/kotlin/scanners/ScanCode.kt
generateSummary() and therefore getFileCount() is called even if ScanCode
did not create a result file because it failed to run for some reason.
To avoid a NullPointerException in this case, fall back to a file count
of 0.
=> ScanCode: Fix getting the file count from empty results

model/src/main/kotlin/config/PathExcludeReason.kt
In some cases no path exclude reason really matches. Introduce `other`
as additional reason which is supposed to be used mainly for not so
common reasons or edge cases.
=> PathExcludeReason: Add `other` as reason

docs/Configuration.md
The project excludes feature has been removed a while ago while this
sentence was left over, see 9b595404.
=> Configuration.md: Remove some left overs

model/src/main/kotlin/ScanSummary.kt, model/src/test/assets/expected-scan-results.yml, model/src/test/kotlin/ScanResultContainerTest.kt, scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml, scanner/src/funTest/kotlin/storages/AbstractStorageTest.kt, scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/scanners/Askalono.kt, scanner/src/main/kotlin/scanners/BoyterLc.kt, scanner/src/main/kotlin/scanners/FileCounter.kt, scanner/src/main/kotlin/scanners/Licensee.kt, scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanCodeTest.kt, spdx-utils/src/main/kotlin/SpdxUtils.kt, spdx-utils/src/test/kotlin/SpdxUtilsTest.kt
Calculate the SPDX package verification code [1] in all scanners and add
it to the `ScanSummary`.
Also fix some broken links in `SpdxUtils` along the way.
[1] https://spdx.org/spdx_specification_2_0_html#h.2p2csry
=> ScanSummary: Add a field for the SPDX package verification code

reporter/src/main/kotlin/reporters/ReportTableModelMapper.kt
Do not fail if the uncurated package for an identifier cannot be found
and use an empty `VcsInfo` instead. The package can be missing if there
was an issue in the analyzer.
This is a fixup for 6747eae.
=> ReportTableModelMapper: Fix a null pointer exception

spdx-utils/src/main/kotlin/SpdxExpression.kt
The left-hand side operand of the `WITH` operator must be a license
identifier. Reflect that in validate().
=> SpdxCompoundExpression: Validate also the lhs operand of WITH

buildSrc/build.gradle.kts, cli/build.gradle.kts, helper-cli/build.gradle.kts
The "compile" configuration has been generally deprecated in Gradle 6.0,
so use the "implementation" configuration instead.
=> Gradle: Use the "implementation" instead of "compile" configuration

build.gradle.kts
Because for some reason calling "./gradlew dependencies" does not work
as a task selector to execute all "dependencies" tasks in all projects,
but it executes only in the root project.
Ensure deterministic output by requiring to run tasks after each other
in always the same order.
=> Gradle: Add a task to list all dependencies of all projects

README.md, build.gradle.kts, docker/build/Dockerfile, reporter-web-app/build.gradle.kts
This allows to remove Node.js and Yarn from the list of prerequisites
to build ORT, which means now nothing except for a JDK is required.
Unfortunately, the Yarn plugin always installs itself to the root project
(even if applied in a subproject) [1], and it also creates a "check" task
in the root project which clashes with our existing "check" task. As for
some reason the "check" task created by the Yarn plugin cannot be further
configured to depend on our "checkCopyright" task, simply remove our
"check" task which is not used anymore as of 6d994fd anyway.
Finally, as the Node.js binary installed by Gradle depend on glibc, but
our Alpine-based Dockerfile uses musl, switch to a Alpine base image
that comes with glic (and Java 8).
[1] …
=> reporter-web-app: Use Kotlin's Yarn plugin to bootstrap Node.js and Yarn

scanner/src/main/kotlin/Scanner.kt
In case the IDs of the given project and result container differ
and the definition file of that project is in the root directory,
filterProjectScanResults() returns a scan result container whose ID
does not match the ID of the given project. As consequence the scan
result lacks all license and copyright findings for that project.
Even worse the whole ORT result may lack those findings as the
unfiltered scan result container may get ditched in line 152.
Fix this by setting the ID of the returned container properly.
=> Scanner: Stop accidentally dropping scan results

analyzer/src/funTest/assets/projects/external/directories-expected-output.yml, analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml, analyzer/src/main/kotlin/Analyzer.kt
The scanner module associates each copyright or license finding to the
project in whoose subtree it resides whereas the project directories are
derived from the definition file locations. Thus having a definition file
at the root of the repository guarantees that each finding gets associated
with a project.
In order to provide that mentioned guarantee the analyzer adds an
`unmanaged` project to the root directory in case it does not already
contain a definition file for an enabled package manager.
The problem is that the condition for the creation of the `unmanaged`
manager is based on the locations of the definitions files while the
logic for the association of findings uses the locations of the `mapped`
definition files. In particular when the root directory contains a
definition file …
=> Analyzer: Fix the `Unmanaged` approach

reporter/src/main/kotlin/reporters/NoticeReporter.kt
Do not call `reduce` on an empty map to prevent it from throwing an
exception.
=> NoticeReporter: Prevent calling `reduce` on an empty map

reporter/src/funTest/assets/static-html-reporter-test-expected-output.html, reporter/src/funTest/assets/static-html-reporter-test-input.yml, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
Make sure that in the dependency table the project itself is always the
first entry.
=> StaticHtmlReporter: Make sure projects are listed first

analyzer/src/main/kotlin/Analyzer.kt, docs/Configuration.md
The fact that ORT uses the manifests repository as default location for
repository configuration files can be interpreted as ORT is encouraging
to place the ort.yml files there which could put some users in the wrong
direction. Remove this to make ORT neutral about the location for Git
Repo based projects and to remove the need to maintain an additional
code path.
Note that it is still possible to use any `*.ort.yml` residing within
the `.repo/manifest` directory by just specifying it via the
`repositoryConfigurationFile` parameter.
=> Analyzer: Remove the default repository config file location for Git Repo projects

scanner/src/main/kotlin/Scanner.kt
As this avoids unwanted inconsistencies as seen in the bug which just
got fixed at that same code location.
=> Scanner: Use the same code path for setting the container ID

downloader/src/main/kotlin/vcs/Git.kt
Because the Git command called is "update", and initialization is just a
special case of updating.
=> Git: Rename "initSubmodules" to "updateSubmodules"

downloader/build.gradle.kts, downloader/src/main/kotlin/vcs/Subversion.kt, gradle.properties
This is a step towards getting rid of the "svn" CLI dependency
completely.
=> Subversion: Use SVNKit instead of the "svn" CLI for working tree information

spdx-utils/src/main/kotlin/SpdxUtils.kt
The previous implementation can cause even out of memory exception when processing large files.
=> sha1sum(): Reduce to O(1) memory consumption

evaluator/src/main/kotlin/LicenseView.kt, evaluator/src/main/resources/rules/no_gpl_declared.kts, evaluator/src/test/kotlin/LicenseViewTest.kt, evaluator/src/test/kotlin/RuleSetTest.kt
In order to re-align with the naming commonly used in ORT. This follows
up on 53734d4.
=> LicenseView: Use upper case for static constants

analyzer/src/main/kotlin/managers/Cargo.kt
Checking whether the given dependencyName is a string prefix of the
actual dependency name is a to broad condition for finding the right
JSON node. In particular when the dependency tree contains two packages
where one packages' name is a prefix of the others', then the condition
is evaluated to true while it should yield false.
Adjusting the condition to check for equality which fixes that issue.
=> Cargo: Fix the buggy getResolvedVersion() function

build.gradle.kts, gradle.properties
This now automatically provides the "detekt" extension. For details see
https://arturbosch.github.io/detekt/changelog.html#121.
=> Gradle: Upgrade the detekt plugin to version 1.2.1

downloader/src/main/kotlin/VersionControlSystem.kt, utils/src/main/kotlin/Utils.kt
These functions are somewhat similar, so highlight the differences.
=> Improve / align docs to the splitUrl() and normalizeVcsUrl() functions

downloader/src/main/kotlin/vcs/Subversion.kt
This removes one more direct use of ProcessCapture and the "svn" CLI.
=> Subversion: Implement isApplicableUrlInternal() via SVNKit

downloader/src/main/kotlin/vcs/Subversion.kt
So this gets properly handled by the caller.
=> Subversion: Wrap any SVNException when listing refs into a DownloadException

helper-cli/src/main/kotlin/common/Utils.kt
As we decided to keep them, see the related discussion in
https://github.com/heremaps/oss-review-toolkit/pull/2029.
=> Utils: Use explicit underscores in a destructing declaration

README.md
As the VCS locations returned by that package manager often times do not
contain the actual source code for the respective package but just a
receipe to build the conan package, see #2037.
=> README.md: Make the Conan integration experimental

downloader/src/funTest/kotlin/CvsWorkingTreeTest.kt
The tyrex repository seems to have a server-side read-lock file which does
not get removed by the CVS server for some reason and thus blocks any read
operation. So simply use another CVS repository for testing, and enable
the tests again.
=> CvsWorkingTreeTest: Fix the test by using another CVS repository

helper-cli/src/main/kotlin/HelperMain.kt, helper-cli/src/main/kotlin/commands/ImportCopyrightGarbageCommand.kt
This command reads copyright garbage entries from a text file and merges
them into a copyright garbage YAML file. Use a custom collator to sort
the entries independent from the machine specific environment in the
same order as the sort command [1].
[1] https://www.gnu.org/software/coreutils/
=> helper-cli: Add a command to import copyright garbage

reporter/src/main/kotlin/reporters/NoticeByPackageReporter.kt, reporter/src/main/kotlin/reporters/NoticeSummaryReporter.kt
This needs to be merged after the notice reporter refactoring and the list copyrights commits so that this PR contains only 2 commits.
=> NoticeReporter: remove more garbage

utils/src/main/kotlin/Utils.kt
Add *.licence for consistency, as for the other patterns also both
AE and BE spellings are in the list.
=> utils: Add *.licence to the list of license file patterns

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml, docker/run/Dockerfile, downloader/src/funTest/kotlin/BeanUtilsTest.kt, downloader/src/funTest/kotlin/SubversionDownloadTest.kt, downloader/src/funTest/kotlin/SubversionWorkingTreeTest.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/main/kotlin/vcs/Subversion.kt, downloader/src/test/kotlin/VersionControlSystemTest.kt
This also changes the (so far broken) semantics of the Subversion
implementation. Previously, when downloading a Subversion branch / tag,
it had to be specified as the path. However, the fact that Subversion
organizes branches / tags as paths is an implementation detail that the
user should not need to care about when using the ORT downloader.
The new implementation treats branch / tag names as symbolic revisions.
That is, if the user wants to download a branch, the VCS revision should
be set to "branches/<branch name>", or "tags/<tag name>" for a tag. A
branch / tag name requires the "branches/" / "tags/" prefix in order to
distinguish branches and tags with the same name.
Note that this changes requires any existing VCS curations for
Subversion branches / tags to be updated by moving …
=> Subversion: Reimplement all remaining operations using SVNKit

helper-cli/src/main/kotlin/commands/MapCopyrightsCommand.kt
Which was a copy & paste mistake previously.
=> MapCopyrightsCommand: Fix-up the command name

downloader/src/main/kotlin/Downloader.kt
Git creates its pack files with read-onyl attribute set on Windows,
which requires to apply force when deleting them.
Also see e.g. the discussion at
https://github.com/libgit2/libgit2sharp/issues/1354#issuecomment-277968633.
Fixes #2072.
=> Downloader: Force deletion of VCS left-overs

downloader/src/main/kotlin/vcs/Cvs.kt, downloader/src/main/kotlin/vcs/Subversion.kt, utils/src/main/kotlin/Extensions.kt, utils/src/main/kotlin/Utils.kt
In favor of using Kotlin's runCatching / isSuccess instead.
=> Remove our custom "succeeds" extension function

downloader/src/main/kotlin/Downloader.kt
This code is run after a failed downloadFromVcs(), so it also has to
deal with Git repositories in the same way as 2060060.
=> Downloader: Force deletion of VCS left-overs, again

downloader/build.gradle.kts, downloader/src/funTest/kotlin/GitWorkingTreeTest.kt, downloader/src/main/kotlin/vcs/Git.kt, gradle.properties
This is the first step towards fully migrating to JGit to reduce external
dependencies, and it allows to again enable the test for non-existing
repositories on Windows.
Fixes #2077.
=> Git: Rewrite testing for applicable URLs to use JGit

spdx-utils/src/main/kotlin/SpdxLicenseAliasMapping.kt, spdx-utils/src/test/kotlin/SpdxLicenseAliasMappingTest.kt
For of all, the keys in these maps are not (full) license names in
SPDX-speak, but string representations of license ids (also see [1]). So
use the term "ids" instead of "names".
Secondly, for deprecated entries not the license / exception itself is
deprecated but only its "id", so rename variables accordingly.
Finally, also adjust the docs for consistency.
[1] https://spdx.org/licenses/
=> SpdxLicenseAliasMapping: Rename variables for clarity

.reuse/dep5, .travis.yml, LICENSES/Apache-2.0.txt, LICENSES/CC-BY-3.0.txt, LICENSES/CC0-1.0.txt, analyzer/src/funTest/assets/projects/synthetic/pip/setup.py, gradle.properties
See https://reuse.software/.
Use at least reuse-tool 0.6.0 [1] which excludes Git submodules by
default and execute "reuse lint".
[1] https://github.com/fsfe/reuse-tool/blob/master/CHANGELOG.md#060---2019-11-19
=> Make ORT REUSE-compliant

.mailmap
=> mailmap: Account for Sebastian's new email address at Bosch

analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml, analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
Several Maven repositories have disabled HTTP access for security
reasons, see [1] and [2]. To be able to still analyze old Maven projects
that use the HTTP URLs automatically create mirrors for those
repositories pointing to the HTTPS URLs. Otherwise Maven would abort
with an exception as soon as it tries to download an artifact from any
of those repositories.
[1] https://github.com/github/security-lab/issues/21
[2] https://medium.com/p/d069d253fe23
=> analyzer: Automatically create HTTPS mirrors for disabled HTTP URLs

docs/config-file-ort-yml.md
The `resolutions` was missing in one of the explanation for resolutions in the .ort.yml which resulted in confusion for ORT users.
=> docs: Add `resolutions`  in .ort.yml explanation

gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/6.1/release-notes.html.
=> Gradle: Upgrade to version 6.1

model/src/main/kotlin/OrtResult.kt
In order to adhere to the exclude state of the license and copyright
findings.
=> OrtResult: Add param to getDetectedLicensesWithCopyrights()

model/src/main/kotlin/Scope.kt, model/src/test/kotlin/ScopeTest.kt, reporter/src/funTest/assets/evaluated-model-test-expected-statistics.yml, reporter/src/funTest/kotlin/reporters/EvaluatedModelYamlReporterTest.kt, reporter/src/main/kotlin/StatisticsCalculator.kt, reporter/src/main/kotlin/model/Statistics.kt, reporter/src/main/kotlin/reporters/EvaluatedModelReporter.kt, reporter/src/main/resources/META-INF/services/com.here.ort.reporter.Reporter
Which for now just contains summary stats and is supposed to be extended so that a data model is shared across reporters.
Note: doing the stats first was only due to urgent needs.
=> reporter: Start reporting the reporter data model itself

.appveyor.yml
This is a work-around for GPG failing to connect to its agent in
GitRepoTest [1]. A better work-around in the repo tool is pending review
at [2].
[1] https://ci.appveyor.com/project/heremaps/oss-review-toolkit/builds/30228453#L3030
[2] https://gerrit-review.googlesource.com/c/git-repo/+/251108
=> AppVeyor: Temporarily move GPG executables away

model/src/main/kotlin/AnalyzerResult.kt, model/src/main/kotlin/ScanRecord.kt
In a recent PR `error` has been renamed to `issue` accross the code
based. Deserializing OrtResults created before that rename now fails
as the 'has_errors' property is not ignored anymore, see 99152a1 and
addb4ab.
Re-add 'has_errors' to the set of ignored properties fixes the
deserialization again.
=> OrtResult: Fix-up the deserialization after a rename

cli/src/main/kotlin/OrtMain.kt
This allows for more flexibility in upcoming changes.
=> Main: Generate the header as a string instead of printing it immediately

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
=> ClearlyDefinedPackageCurationProvider: Add missing provider mappings

reporter/src/main/kotlin/reporters/NoticeByPackageReporter.kt
Not the one of the class the extension function operates on.
=> NoticeByPackageReporter: Use the class' logger

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
Remove the trailing slash from "http://repo.spring.io/" for consistency
and check if the repository starts with any of the configured URLs
instead of checking for equality to ignore trailing slashes.
Fixes #2138.
=> MavenSupport: Improve Maven HTTPS mirror matching

model/src/main/kotlin/ScanSummary.kt
For consistency with a similar comment in `AnalyzerResult` and
`ProjectAnalyzerResult`, and because it is useful to have this comment
also in the generated docs.
=> ScanSummary: Move a code comment to KDoc

cli/src/main/kotlin/commands/ReporterCommand.kt
The call to "file.outputStream()" already creates the file, which is
then still kept if the reporter later fails with an exception. Avoid
that by writing to a byte array frist.
=> ReporterCommand: Do not write an empty output file on error

analyzer/src/funTest/assets/projects/synthetic/yarn-workspaces-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/yarn-workspaces/packages/pkg1/package.json, analyzer/src/main/kotlin/managers/Npm.kt, utils/src/main/kotlin/Extensions.kt
The logic for finding workspace submodules did not find submodules with a scope / namespace, which is the issue this PR addresses. See also the individual commit messages.
=> Yarn workspaces: Handle also scoped submodules

downloader/build.gradle.kts, downloader/src/main/kotlin/vcs/Git.kt, gradle.properties
Configure JGit to use the SSH-Agent if available and disable strict host key checking for JGit.
=> JGit SSH-Agent

cli/src/main/kotlin/commands/DownloaderCommand.kt
The default value has recently been changed to an empty list which made
the behavior inconsistent with the parameter description, see bb5e2b6.
Fix this by reverting to the previous default value.
=> DownloaderCommand: Fix-up the entity parameter handling

cli/src/main/kotlin/commands/DownloaderCommand.kt
As the log can be potentially quite long it seems convenient to have the
errors summarized at the very end of the logs.
=> DownloaderCommand: Log an error summary

cli/src/main/kotlin/commands/DownloaderCommand.kt, utils/src/main/kotlin/ArchiveUtils.kt
This makes the code more readable.
Note that there is a minor change in behavior involved in
DownloaderCommand: Before, the condition
if (ARCHIVE_EXTENSIONS.any { projectFile.name.endsWith(it) })
was not taken for POM files, that is, in vase of an URL pointing to a
POM file, that POM file was not used as the source artifact, which is
actually wrong.
The new condition
ArchiveType.getType(projectFile.name) != ArchiveType.NONE
distinguishes POM artifacts from other NONE archive types, and thus the
condition it now taken for POM files, and POM files are used as source
artifacts.
=> downloader: Refactor the archive types from constants into an enum

Dockerfile
=> Dockerfile: Always get a stacktrace if Gradle fails

downloader/src/main/kotlin/vcs/GitWorkingTree.kt
A SubModuleWalk by index iterates over all Git submodules no matter whether
they have been initialized, however for all non-intialized submodules
getRepository() returns null.
Handle that gracefully in order to avoid crashing with a null pointer
exception.
=> GitWorkingTree: Fix a NPE with listSubmodulePath()

cli/src/main/kotlin/OrtMain.kt
As of the migration from `JCommander` to `clikt` the exit codes from the
ORT commands are propagated via exceptions to clikt which then calls
exitProcess(). In case no such exception has been thrown exitProcess()
is not called anymore as of bb5e2b6. As a consequence the process keeps
alive in case threads (other than the main thread) are still running.
The problem indeed happens e.g. with the analyzer command.
Adding this missing call as a fix-up for bb5e2b6.
=> OrtMain: Exit the process before returning from main()

downloader/src/main/kotlin/vcs/GitRepo.kt
ORT started using the master branch instead of the (default) stable
branch as master contained some fixes which had not been integrated into
stable back then, see c0eb030. As both fixes mentioned in that commit
meanwhile got integrated into stable there is no need anymore to use the
master branch.
Installing the repo launcher command via [1], as we do on Travis CI,
actually installs the released launcher command which comes from the
stable branch. As of the recent bump of the major version [2] of that
launcher command on the master branch, calling [3] refuses to work and
asks to update the launcher command to version 2.x first.
Revert back to using the stable branch in order to fix that issue and
thus make ORTs git-repo integration work again.
[1] curl …
=> GitRepo: Use the default branch of git-repo again

downloader/src/main/kotlin/vcs/GitRepo.kt
This has been removed by f61b87b but it turned out that there is a
preferrence to keep it, see also:
https://github.com/heremaps/oss-review-toolkit/pull/2186#issuecomment-582905816
This partially reverts commit f61b87b.
=> GitRepo: Re-introduce the switch for the git-repo branch

.appveyor.yml, .travis.yml, downloader/src/main/kotlin/vcs/GitRepo.kt
Yesterday version 2 became the new `stable` version of git-repo and
thus ORT started using it. As result GitRepoTest started failing due to
the below issue which can be reproduced by installing the latest
(stable) git-repo launcher and then running a `repo-sync` with the
`--fetch-submodules` option.
Work around that issue by switching back to version 1 temporarily, so
that finding the proper solution can be done outside the critical path
of fixing the failing CI.
[1] .repo/repo/project.py", line 2076, in parse_gitmodules
os.write(fd, p.stdout)
=> git-repo: Temporarily switch back to version 1

.jitpack.yml
=> JitPack: Exclude dokkaJavadoc tasks to save build time

model/src/main/kotlin/OrtResult.kt
This is efficient as the execution performance is determined solely by
a TreeSet look-up.
=> OrtResult: Add a isProject() function

docs/getting-started.md
Add to the getting-started guide sections on how to pass curations
to the Analyzer and user-defined license classifications to
the Evaluator using example files.
This change will help guide new users other documentation that they
can use to workaround common scan issues.
Resolves #2185.
=> docs: Reference `curations.yml` and `licenses.yml`

Jenkinsfile, README.md
E.g. to further process scan results with some user-specific logic. It
is the downstream job's responsibility to copy the artifacts it needs
from the upstream job, e.g. by accessing the Cause instance via Groovy
DSL.
=> Jenkinsfile: Allow to trigger an optional downstream job afterwards

docs/getting-started.md
Section 6 of the Getting Started document contained a wrong link,
possibly a copy and paste error. The link to the curations.yml pointed
to 'examples/licenses.yml'.
Signed-off-by: Sander, Uwe <uwe.sander@zeiss.com>
=> docs: Fix link to curations.yml

scanner/src/main/kotlin/scanners/ScanCode.kt
=> ScanCode: Guard against "spdx_license_key" being null in ScanCode 3.11

analyzer/src/main/kotlin/managers/Bundler.kt
As Bundler 2.1.4 is now what Travis uses.
=> Bundler: Whitelist Bundler 2.1.x

analyzer/build.gradle.kts, buildSrc/build.gradle.kts, cli/build.gradle.kts, helper-cli/build.gradle.kts, reporter/build.gradle.kts
This feature was introduced in Gradle 6.2, see
https://docs.gradle.org/6.2/release-notes.html#declaring-exclusive-repository-content
=> Gradle: Use exclusive repository content to speed up artifact lookup

README.md, model/src/main/kotlin/config/FileStorageConfiguration.kt, model/src/main/kotlin/config/LocalFileStorageConfiguration.kt, model/src/main/resources/reference.conf, reporter/src/funTest/kotlin/reporters/NoticeByPackageReporterTest.kt, scanner/src/main/kotlin/ScanResultsStorage.kt, scanner/src/main/kotlin/storages/FileBasedStorage.kt
As this is more specific and distinguishes e.g. LocalFileStorage from
XZCompressedLocalFileStorage.
=> scanner: Use the backend storage name in case of a FileBasedStorage

model/src/main/kotlin/utils/FindingsMatcher.kt, model/src/test/kotlin/utils/FindingsMatcherTest.kt
This PR is intended to consist of only non-functional changes which prepare changing the actual matching algorithm. In order to no break things accidentally it seems to be good to have a green test run at this point.
=> FindingsMatcher: Prepare for changing the algorithm

model/src/main/kotlin/config/PathExcludeReason.kt
In SPDX 2.2 [1] the `TEST_OF` relationship was
introduced for cases where it's clear something is used
for testing but unclear whether it's code or tools.
Adding `TEST_OF` in addition to `TEST_TOOL_OF` so ORT users
have a generic reason for test directories
which may besides tools also contain code.
[1] https://github.com/spdx/spdx-spec/issues/173.
=> PathExcludeReason: Add `TEST_OF`

docs/config-file-ort-yml.md, docs/examples/bower.ort.yml, docs/examples/bundler.ort.yml, docs/examples/cargo.ort.yml, docs/examples/go-mod.ort.yml, docs/examples/gradle-android.ort.yml, docs/examples/gradle.ort.yml, docs/examples/maven.ort.yml, docs/examples/npm.ort.yml, docs/examples/php-composer.ort.yml, docs/examples/sbt.ort.yml, docs/examples/stack.ort.yml, docs/examples/yarn.ort.yml
Update comments for scope excludes examples so they are aligned with
those in the helper-cli's .ort.yml generation, see 9c6b442.
=> docs: Align scope exclude examples with helper-cli

helper-cli/src/main/kotlin/commands/GenerateScopeExcludesCommand.kt
Change includes:
- Aligning reasons and comments for generated .ort.yml with docs/examples/*.ort.yml.
- Improve reasons to better match what the scope contains.
=> helper-cli: Improve .ort.yml generation

utils/src/main/kotlin/storage/XZCompressedLocalFileStorage.kt, utils/src/test/kotlin/storage/XZCompressedLocalFileStorageTest.kt
This way any existing uncompressed files, like scan results, are reused
instead of being recreated.
=> XZCompressedLocalFileStorage: Fall back to reading an uncompressed file

reporter/src/main/kotlin/utils/StatisticsCalculator.kt
`ErrorResolution` was renamed to `IssueResolution`. While at it import
the classes instead of using the canonical name as it is done in most
other classes.
=> StatisticsCalculator: Fix the KDoc

downloader/src/main/kotlin/VersionControlSystem.kt
To reduce code duplication, and because it is a useful function.
=> VersionControlSystem: Add function to check if the VCS is available

analyzer/src/main/kotlin/managers/Gradle.kt
This better separates the properties from the rest of the log output.
=> Gradle: Add indentation to logged system properties

gradle.properties
Unfortunately, no release notes are available. Note that the currently
latest version 0.7 does not work without significant code changes on
our side.
=> Gradle: Upgrade the idea-ext plugin to version 0.6.1

scripts/set_gradle_proxy.sh
=> set_gradle_proxy: Fix setting a proxy without authentication info

model/src/main/kotlin/ScanRecord.kt
This is a fix-up for 09dfd2d which missed to also add the JSON alias
corresponding to the `scopes` property.
=> ScanRecord: Fix-up broken de-serialization backwards compatibility

utils/src/main/kotlin/ArchiveUtils.kt
=> ArchiveUtils: Add comments about why we call safeMkdirs() for each file

model/src/main/kotlin/OrtResult.kt, reporter/src/funTest/assets/notice-by-package-reporter-expected-results, reporter/src/funTest/assets/notice-by-package-reporter-expected-results-with-license-files
Invert the logic for applying PathExcludes to the locations of
copyright statements so that excluded locations get filtered out.
The issue was observed in the generated copyright notices which lacked
the copyright statements which were detected in not excluded locations.
This is a fix-up of d4e577c.
=> OrtResult: Fix a severe issue with collectLicenseFindings()

model/src/main/kotlin/config/ScannerConfiguration.kt, model/src/main/resources/reference.conf, model/src/test/kotlin/config/OrtConfigurationTest.kt, scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml, scanner/src/main/kotlin/scanners/ScanCode.kt, scanner/src/test/kotlin/ScanCodeTest.kt
The ScannerConfiguration itself is included via a "scanner" field in the
"OrtConfiguration", leading to two nested "scanner" fields, which is not
so nice. So rename this field to "options" which is a more fitting name
anyway, also see the docs for the field.
=> ScannerConfiguration: Rename the "scanner" field to "options"

model/src/main/kotlin/utils/FindingsMatcher.kt, model/src/test/kotlin/utils/FindingsMatcherTest.kt
The previous algorithm for matching a license finding against copyright
findings had a hard-coded limit on the number of copyrights it could
match to a license finding. The default was to match at most 5 copyright
statements above and 5 below the start line of the license.
Let's remove this threshold by extending the above range upwards
recursively if there is a copyright within expandToleranceLines
distance to the topmost copyright statement in that range.
Further the previous algorithm did adhere only to the start but not to
the end line of the license. Since ScanCode sometimes detects license
locations ranging accross copyrights that can lead to non-matched and
thus discarded copyright statements. Let's avoid that by extending the
previously use range until the end line of the license. …
=> FindingsMatcher: Improve the matching algorithm

docs/getting-started.md
Recently `scope` parameter was removed from `scanner`, but docs were not updated. See #2276 #2226 
Since Getting Started docs have old version, it seems quite crucial to update it for those who are exploring the toolkit. I spent several hours myself, trying to find, why skipping is not working. 
This is my first PR here, will be happy to update my PR if it doesn't meet certain criteria
Signed-off-by: Askar Absemetov <askar.absemetov@zeiss.com>
=> GettingStarted: Update docs to reflect changes of 'scope' and '--skip-excluded'

gradle.properties
See https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-3-70-released/.
=> Gradle: Upgrade Kotlin to version 1.3.70

analyzer/src/main/kotlin/managers/Yarn.kt
Support for Yarn 2.x is pending, see
https://github.com/heremaps/oss-review-toolkit/issues/2283.
=> Yarn: Bump the supported version to the latest stable 1.x release

README.md, model/src/main/kotlin/config/PostgresStorageConfiguration.kt, model/src/main/resources/reference.conf, model/src/test/kotlin/config/OrtConfigurationTest.kt, scanner/src/main/kotlin/ScanResultsStorage.kt
Allow to enable and configure SSL mode when connecting to the database
server. For details see:
https://jdbc.postgresql.org/documentation/head/connect.html
https://jdbc.postgresql.org/documentation/head/ssl-client.html
=> PostgresStorage: Allow to connect using SSL

gradle/wrapper/gradle-wrapper.properties
See https://github.com/gradle/gradle/releases/tag/v6.2.2.
=> Upgrade Gradle to version 6.2.2

analyzer/src/main/kotlin/PackageManager.kt
Reflect that definition files are always files but never directories.
This avoids exiting with a FileNotFoundException when analyzing a
directory containing a descendant directory named e.g. `package.json`.
=> PackageManager: Stop matching definition file globs against directories

docs/getting-started.md
And link to the README.md instead of just mentioning it.
=> getting-started: Say "storage" instead of "cache"

scanner/src/main/kotlin/storages/FileBasedStorage.kt
Use `readFromStorage(id)` in `readFromStorage(pkg, scannerDetails)`
instead of the `read(id)` function. Otherwise the storage stats are
incremented twice when calling
`ScanResultsStorage.read(pkg, scannerDetails)` with a
`FileBasedStorage`.
=> scanner: Fix storage stats when using FileBasedStorage

model/src/main/kotlin/Package.kt, model/src/main/kotlin/Project.kt, model/src/test/kotlin/AnalyzerResultTest.kt
Reduce the severity for unmapped declared licenses from `ERROR` to
`WARNING`. The decision if an unmapped license is an error should be
made in the evaluator rules. Further improvements to simplify this will
be implemented in separate commits.
=> model: Reduce the severity for unmapped declared licenses

README.md
After trying to use the Readme parameters to downloader and scanner, saw that both now use ```-i``` and not ```-a```
<sub> Basem Vaseghi <basem.vaseghi@daimler.com>, Daimler TSS GmbH, [Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
=> Fixed wrong parameters in Readme

cli/build.gradle.kts, helper-cli/build.gradle.kts
As of 655bb22 JCenter is declared for all projects.
=> Remove JCenter from repository declarations in CLI projects

README.md
So readers can easily navigate to the issue.
=> README: Make the text about issue 2037 a relative link

spdx-utils/src/main/kotlin/SpdxUtils.kt, spdx-utils/src/test/kotlin/SpdxUtilsTest.kt
This way not the whole list of files is held in memory at once.
=> spdx-utils: Try to reduce memory consumption by using sequences

analyzer/src/main/kotlin/managers/Bundler.kt
The former calls the latter and covers more cases.
=> Bundler: Prefer VersionControlSystem.splitUrl() over VcsHost.toVcsInfo()

analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/Cargo.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/utils/MavenSupport.kt, downloader/src/funTest/kotlin/BabelTest.kt, downloader/src/main/kotlin/VcsHost.kt, downloader/src/main/kotlin/VersionControlSystem.kt, downloader/src/test/kotlin/VcsHostTest.kt, downloader/src/test/kotlin/VersionControlSystemTest.kt
It was confusing to have both very similar functions, so merge the former
into the latter. This bundles all static VCS URL parsing in VcsHost.
=> Merge VersionControlSystem.splitUrl() into VcsHost.toVcsInfo()

downloader/src/main/kotlin/vcs/GitWorkingTree.kt
Previously, the first remote from the alphabetically sorted list of
remotes was used when determining the remote URL and no remote for the
current branch was set.
As "origin" is the default remote name in Git and the alphabetical order
of remotes has no inherent meaning, prefer "origin" if it exists.
=> GitWorkingTree: Give "origin" preference over other remotes

scanner/src/main/kotlin/scanners/ScanCode.kt
On the first run of ScanCode `removePrefix` is not sufficient, because
ScanCode prints an additional line before the version string:
* Configuring ScanCode for first use...
ScanCode version 3.0.2
This is a fixup for 6b83f55.
=> ScanCode: Revert to `substringAfter` in `transformVersion`

analyzer/src/funTest/assets/projects/external/directories-expected-output.yml, analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/Cargo.kt, analyzer/src/main/kotlin/managers/Conan.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/Pip.kt, analyzer/src/main/kotlin/managers/Pub.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
Also use the SCM URL as fallback when determining the VCS info for Maven projects and packages.
=> Maven fallback URLs

scanner/src/main/kotlin/scanners/ScanCode.kt
=> ScanCode: Fix a typo in the expected version string

Dockerfile
The problem with Debian Sid is that it continuously unpublishes
previously existing packages, which breaks building the Docker image
until we update those packages manually. So switch to Ubuntu 18.04 which
is an LTS release.
Fixes #2384.
=> Dockerfile: Switch to Ubuntu 18.04 as a base image

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
If the checksum cannot be retrieved from the server the function falls
back to using an empty string instead. This was broken since eeea7ec,
because calling `Hash.create()` with an empty string will fail to verify
the checksum with a message like this:
java.lang.IllegalArgumentException: '' is not a SHA-1 hash.
Instead, check if the checksum is blank and use `Hash.NONE` in this
case.
=> MavenSupport: Do not fail on missing checksum

Jenkinsfile
Sometimes just having the analyzer result is enough, e.g. if only
declared licenses of dependencies are required for further processing in
other tools
=> Jenkinsfile: Make running the scanner and reporter tools optional

model/src/main/kotlin/AnalyzerResult.kt
Sometimes the `hasIssues` property was `false' even though the analyzer
result contained issues. Fix this by checking if  `collectIssues()`
returns an empty result, instead of re-implementing the logic to search
for issues.
=> AnalyzerResult: Fix wrong value of `hasIssues`

.github/workflows/rebase.yml
See https://github.com/cirrus-actions/rebase#installation, otherwise the
base to rebase onto is wrong (the root commit).
=> rebase: Add the missing fetch-depth of 0

.appveyor.yml, README.md, analyzer/src/funTest/kotlin/managers/GoModTest.kt
Looks like the migration implicitly made use use newer / different AppVeyor base images.
=> Fix AppVeyor builds after migration to new org

Dockerfile
This is again needed for corporate proxy support to be able to install
sbt from Bintray.
=> Dockerfile: Allow proxies to tamper with Bintray's SSL certificate

Dockerfile
This is a fixup for commit f192d99.
=> Dockerfile: Fix alphabetical sorting of libraries

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml, analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/pip-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/pipenv-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/python3-django-expected-output.yml, analyzer/src/funTest/assets/projects/synthetic/python3-django-pipenv-expected-output.yml, analyzer/src/main/kotlin/managers/Pip.kt
Often the " License" suffix is part of the name of the license. Also, we
do not do this in any of the other package manager implementations, and
it is ORT's philosophy to capture the original metadata without
manipulating it.
=> Pip: Stop removing the " License" suffix from license identifiers

.travis.yml, README.md
Java 11 is both the default for the Bionic image and also the version we
use for the Windows build on AppVeyor.
This also requires to update the Android SDK command line tools which
finally support Java 11 [1].
[1] https://issuetracker.google.com/issues/122210344#comment10
=> Travis: Use Java 11 which is an LTS release

.gitattributes
Otherwise the ScanCodeTest can fail on Windows, because the calculated
package verification code depnds on the line endings.
=> gitattributes: Checkout ScanCode samples with Unix line endings

utils/src/main/kotlin/Utils.kt
Paths that point to sub-directories contained in the repository (but
that do not contain ".git/" in between) should not get ".git" appended.
For example, previously
https://github.com/hamcrest/JavaHamcrest/hamcrest-core
was turned into
https://github.com/hamcrest/JavaHamcrest/hamcrest-core.git
which is wrong.
=> Utils: Let normalizeVcsUrl() append ".git" only for repository paths

downloader/build.gradle.kts
While we are using jsch.agentproxy.jsch 0.0.7, even the currently latest
version 0.0.9 still depends on jsch 0.1.49. However, JGit requires jsch
version 0.1.55, which is what Gradle resolves to.
The generated POM only declares jsch.agentproxy.jsch 0.0.7, and Maven's
version conflict resolution (take the version that is closest to the
root) does *not* upgrade jsch 0.1.49 to version 0.1.55, which causes
problems with JGit on the consumer side. So manually stick the version
to 0.1.55 here.
Ideally, the dependency version could be customized in the Maven Publish
Plugin as described at [1], but doing so did not have any effect on the
generated POM when tested.
[1] https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies
Signed-off-by: Sebastian …
=> downloader: Fix a jsch dependency issue in the generated Maven POM

model/src/main/kotlin/config/LocalFileStorageConfiguration.kt
Providing a default value for the compression allows to configure the
local file storage by only setting the directory.
=> LocalFileStorageConfiguration: Enable compression by default

model/src/main/kotlin/utils/SimplePackageConfigurationProvider.kt
Trying to read a PackageConfiguration from a directory does not make
sense and results in an uncaught exception, thus adjust the filter
condition accordingly.
This is a fix-up of 596aebb.
=> SimplePackageConfigurationProvider: Fix-up a filter condition

analyzer/src/test/kotlin/PackageManagerTest.kt
To match the location of the tested PackageManager class.
=> PackageManagerTest: Move the class one package level up

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml, analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml, downloader/src/main/kotlin/VcsHost.kt
Similar to like already done for Subversion URLs to branches or tags,
also handle trunk URLs and split out "trunk" as the symbolic revision
name.
=> VcsHost: Handle Subversion trunk URLs in toVcsInfo()

.appveyor.yml
This fixes the AppVeyor build which fails because the tests require at least PHP 7.2.5. This also allows to remove the OpenSSL specific configuration for AppVeyor and requires the Composer installer to be upgraded to 5.1.0.
=> Upgrade AppVeyor to use PHP 7.4.3

analyzer/src/funTest/kotlin/integration/GradleIntegrationTest.kt
The Gradle wrapper of the previously used version 4.4.0 is not
compatible with Java 11. The new version now has a directory which
contains both a "build.gradle" and a "build.gradle.kts", adjust the
logic to get the `expectedManagedFiles` accordingly.
=> GradleIntegrationTest: Upgrade Gradle to 6.2.0

reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
Previously Package.collectIssues() was never called by this model mapper
class. Thus only analyzer issues linked to PackageReferences were included
in the result while the ones linked to Packages were missing.
Include Package.collectIssues() into the result computation so that
the issues show-up in the WebApp report.
=> EvaluatedModelMapper: Map all analyzer issues for packages

analyzer/src/funTest/assets/projects/synthetic/yarn-workspaces-expected-output.yml, analyzer/src/funTest/kotlin/managers/YarnTest.kt
Before, the normalized VCS URL was used for the unprocessed and the
processed VCS URL of the workspace packages in the expected results.
This was wrong, because the URL is not normalized in the unprocessed VCS
info.
=> YarnTest: Fix the expected VCS URL in workspace packages

model/src/main/kotlin/OrtResult.kt, model/src/test/kotlin/OrtResultTest.kt
When the OrtResult contains a large number of nested VCSes
Repository.getRelativePath() executes relatively slowly. In combination
with a large number of projects and packages in which case this function
gets called quite often this leads to terrible execution time.
For my real world example the evaluator took about 30 minutes while
computing the reports took around 3 hours. With this change it executes
altogether in less than two minutes again.
=> OrtResult: Speed-up getFilePathRelativeToAnalyzerRoot()

analyzer/src/funTest/assets/projects/external/jgnash-core-expected-output.yml, analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
=> MavenSupport: Treat Subversion tag names as revisions

downloader/src/funTest/kotlin/vcs/GitWorkingTreeTest.kt, evaluator/src/test/kotlin/LicenseViewTest.kt, model/src/test/kotlin/OrtResultTest.kt, model/src/test/kotlin/ProjectTest.kt, model/src/test/kotlin/utils/FindingCurationMatcherTest.kt, model/src/test/kotlin/utils/FindingsMatcherTest.kt, scanner/src/test/kotlin/ScanCodeTest.kt, spdx-utils/src/test/kotlin/SpdxExpressionTest.kt
Note: If this PR should get accepted a similar change for `shouldContainExactly` should be implemented.
=> Tests: Improve shouldContainExactlyInAnyOrder assertions

model/src/test/kotlin/OrtResultTest.kt, model/src/test/kotlin/ScanResultContainerTest.kt
Consistently use `should containExactly` instead of
`shouldContainExactly` if applicable as it saves the manual construction
of the expected collection, e.g. the listOf() call.
Note: The new syntax is unfortunately not applicable for maps and sets
with the current matchers API of kotest. At least for maps it seems
possible to extend the API upstream.
=> Tests: Improve shouldContainExactly assertions

analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output-win32.yml, analyzer/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml, analyzer/src/main/kotlin/PackageManager.kt, analyzer/src/main/kotlin/managers/Bower.kt, analyzer/src/main/kotlin/managers/Bundler.kt, analyzer/src/main/kotlin/managers/Cargo.kt, analyzer/src/main/kotlin/managers/Conan.kt, analyzer/src/main/kotlin/managers/Maven.kt, analyzer/src/main/kotlin/managers/Npm.kt, analyzer/src/main/kotlin/managers/PhpComposer.kt, analyzer/src/main/kotlin/managers/Pip.kt, analyzer/src/main/kotlin/managers/Pub.kt, analyzer/src/main/kotlin/managers/Stack.kt, analyzer/src/main/kotlin/managers/utils/MavenSupport.kt, analyzer/src/test/kotlin/PackageManagerTest.kt
Previously, VersionControlSystem.forUrl() was called before splitting
the URL into any contained VCS information via VcsHost.toVcsInfo(). That
did not really make sense, as URLs like e.g.
https://github.com/fpco/unliftio/tree/master/unliftio
only become valid after they have been split. So change the function to
first split, and then check whether the URL is applicable for any
supported VCS implementation.
=> PackageManager: Make processPackageVcs() validate URLs after splitting

model/src/main/kotlin/utils/LicenseResolver.kt
The comment has been made obsolete by eb0b346.
=> LicenseResolver: Remove an obsolete code comment

reporter/src/main/kotlin/model/EvaluatedModel.kt
To potentially save some memory.
=> EvaluatedModel: Avoid an intermediate toList() conversion

cli/src/main/kotlin/commands/EvaluatorCommand.kt, cli/src/main/kotlin/commands/ReporterCommand.kt, cli/src/main/kotlin/utils/PackageConfigurationOption.kt, model/src/main/kotlin/config/PackageConfiguration.kt, model/src/main/kotlin/utils/SimplePackageConfigurationProvider.kt, model/src/test/kotlin/SimplePackageConfigurationProviderTest.kt
There is already an option to specify a package configuration directory
which is supposed to contain files each holding the configuration for a
single package.
This option allows specifying a single file holding a list of all package
configurations, and thus only a new representation is added to give some
flexibility to the user.
=> commands: Add an option to specifiy a single package configuration file

reporter/src/main/kotlin/reporters/NoticeByPackageReporter.kt
Use the license file patterns configured in the file archiver when
generating the notices. Otherwise license texts from archived files are
ignored if they do not match the default `LICENSE_FILENAMES`.
Fixes #2452.
=> NoticeByPackageReporter: Use the configured license file patterns

utils/src/main/kotlin/Utils.kt, utils/src/test/kotlin/UtilsTest.kt
This used to be used in "rules.kts" but got replaced by a neat
"groupBy { it }" trick by now.
=> utils: Remove the now unused disjoint() function

docs/examples/rules.kts
Presence of 'HERE' in rule name was a left-over from HERE's rules.kts
which was the base for ORT's example rules.kts.
=> rules.kts: Remove 'HERE' in rule name

analyzer/src/funTest/assets/projects/synthetic/pub/no-lockfile/pubspec.yaml
=> analyzer: Fix a typo in a synthetic test project definition file

gradle.properties
See https://github.com/arturbosch/detekt/releases/tag/v1.8.0.
=> Gradle: Upgrade the detekt plugin to version 1.8.0

reporter/src/main/kotlin/reporters/AbstractNoticeReporter.kt, reporter/src/main/kotlin/reporters/AmazonOssAttributionBuilderReporter.kt, reporter/src/main/kotlin/reporters/CycloneDxReporter.kt
Recently 614feb1 added a command line option for providing package
confgurations. That change implemented the handling of the provided
configurations only for the static HTML report.
This change enables package configurations for all remaining reporters,
except for the evaluated model and thus the WebApp report. The
underlying features package configuration needs, namely license
finding curations and path excludes for license findings, are not
implemented yet in the evaluated model and should be added first.
=> Reporters: Add package configuration handling to further reporters

.detekt.yml
In favor of detekt's built-in UnusedImports rule.
=> detekt: Disable ktlint's NoUnusedImports rule

helper-cli/src/main/kotlin/commands/ListCopyrightsCommand.kt, helper-cli/src/main/kotlin/common/Utils.kt
This command does not show excluded copyright findings for projects, and as
of this change also for packages the excluded copyright findings are
omit.
=> ListCopyrightsCommand: Add an option for providing package configurations

.azure-pipelines.yml, analyzer/src/funTest/assets/projects/synthetic/pipenv/Pipfile, analyzer/src/funTest/assets/projects/synthetic/pipenv/Pipfile.lock, analyzer/src/funTest/assets/projects/synthetic/python3-django-pipenv/Pipfile, analyzer/src/funTest/assets/projects/synthetic/python3-django-pipenv/Pipfile.lock, analyzer/src/funTest/kotlin/GitRepoTest.kt, analyzer/src/funTest/kotlin/managers/CargoSubcrateTest.kt, analyzer/src/funTest/kotlin/managers/GoDepTest.kt, analyzer/src/funTest/kotlin/managers/SbtTest.kt, build.gradle.kts, downloader/src/funTest/kotlin/vcs/CvsWorkingTreeTest.kt, scanner/src/funTest/kotlin/storages/PostgresStorageTest.kt, utils/src/main/kotlin/Ci.kt
Create the configuration for Linux and Windows builds Azure Pipelines. The plan is to enable them as non-mandatory checks during a transition period. If builds on Azure Pipelines are proven to be stable and fast enough they will replace Travis and AppVeyor.
The configuration still contains several TODOs that will be addressed in later PRs.
=> Configure Azure Pipelines

README.md, docs/config-file-package-configuration.yml.md, docs/getting-started.md
Classify the feature as experimental mainly to allow making adjustments to
the model if needed, without `suprising` any ORT user and also to let
the feature mature a bit as it hasn't been used yet.
=> docs: Document the new package configuration feature

scanner/src/funTest/kotlin/storages/PostgresStorageTest.kt
The "Embedded postgres works" test case was intended to test if the
embedded database works, before it was integrated with the other storage
tests. This is now implicitly tested by the other test cases. Removing
the test also improves test performance, because the embedded database
is started only once.
Fixes #2529.
=> PostgresStorageTest: Remove an unnecessary test

.appveyor.yml, .travis.yml
Set `-Dkotest.assertions.multi-line-diff=simple` when running tests on
CI, because the condensed diffs often do not show the required
information to find out why a test failed. Printing the full diffs at
least allows to copy the output and do a local diff.
=> CI: Enable simple multi-line-diffs

.appveyor.yml, .travis.yml
The utils module does not create a cache folder during the tests. This
leads to a warning on AppVeyor [1].
[1] https://ci.appveyor.com/project/oss-review-toolkit/ort/builds/32408723?fullLog=true#L4391
=> CI: Do not cache .ort/utils/cache

helper-cli/src/main/kotlin/commands/FormatRepositoryConfigurationCommand.kt
The double hyphen prefix are commonly used for options but not for
arguments.
=> FormatRepositoryConfigurationCommand: Fix-up an argument name

helper-cli/src/main/kotlin/commands/GenerateScopeExcludesCommand.kt
=> GenerateScopeExcludesCommand: Fix-up the reason for `kapt*` scopes

reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json, reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml, reporter/src/main/kotlin/model/EvaluatedFinding.kt, reporter/src/main/kotlin/model/EvaluatedModelMapper.kt, reporter/src/main/kotlin/model/EvaluatedPackage.kt
The changes adjust the `evaluated model` so that path excludes handling for license and copyright findings can be implemented in the `Web App`. In particular the only `first matching` path exclude is added  to each `EvaluatedFinding`, e.g. not adding all matching excludes to keep the size small and for simplicity in the code using this model.
=> EvaluatedModel: Apply path excludes to license and copyright findings

cli/src/main/kotlin/commands/AnalyzerCommand.kt
=> AnalyzerCommand: Support reading package curations from the config directory

cli/src/main/kotlin/OrtMain.kt, helper-cli/src/main/kotlin/commands/ListStoredScanResultsCommand.kt
Change both implementation so that the `-P` option can now be provided
multiple times each time along with a key-value pair separated by a '=',
for example: `-P a=b -P c=d`.
Using a POSIX style short option, like `-Pa=b -Pc=d`, was the ultimate
goal which wasn't easily achievable as Clikt seems not to allow that in
case the parameter contains '='.
=> (helper-)cli: Make the -P option consistent across commands

Jenkinsfile, README.md
To quickly see e.g. in the build history which project was analyzed in
which build.
=> JenkinsFile: Amend the build's display name with the root project's id

spdx-utils/src/main/kotlin/SpdxDeclaredLicenseMapping.kt
As found in https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc6/11.2.0.4/ojdbc6-11.2.0.4.pom.
ScanCode does not seem to know this license, so use ORT's own namespace
for the LicenseRef.
=> SpdxDeclaredLicenseMapping: Add the "Oracle Free Use Terms and Conditions"

README.md
Now that tickgit supports Kotlin, see
https://github.com/augmentable-dev/tickgit/issues/45.
=> README: Add a badge for TODOs

Jenkinsfile
This makes using the id of the first project for the build description
(see 0366b45) more meaningful.
=> Jenkinsfile: Sort projects to make the root project the first

docs/config-file-ort-yml.md, model/src/main/kotlin/config/PathExclude.kt, model/src/main/kotlin/config/ScopeExclude.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt, utils/src/main/kotlin/Utils.kt
Path and scope excludes can now be de-serialized also if no comment is
provided, which improves usability for cases in which no comment is
needed. Empty comments are not serialized anymore.
=> (Path|Scope)Exclude: Make the comment optional

model/src/main/kotlin/utils/SimplePackageConfigurationProvider.kt
Not all IOExceptions thrown by readValue() do reveal the file for which
the reading failed. Log an error with the absolute file path to provide an
indication where to look for the issue.
=> PackageConfigurationProvider: Log an error if readValue() fails

docs/config-file-curations-yml.md, docs/config-file-licenses-yml.md, docs/config-file-package-configuration-yml.md, docs/file-rules-kts.md
=> docs: Fix evaluator output to point to a directory, not to a file

reporter/src/main/kotlin/Reporter.kt, reporter/src/main/kotlin/reporters/ExcelReporter.kt, reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
Move the functions to the Reporter interface and thus de-duplicate one of
them.
=> Reporter: Factor out the exclude description extension properties

scanner/src/main/kotlin/LocalScanner.kt, scanner/src/main/kotlin/storages/FileBasedStorage.kt, scanner/src/main/kotlin/storages/PostgresStorage.kt
Remove log statements of little value, improve the wording of log
messages, prefer to log only once in the caller, and adjust log levels
where sensible.
=> scanner: Improve logging when reading scan results

Jenkinsfile
See https://wiki.jenkins.io/display/JENKINS/Pipeline+CPS+method+mismatches#PipelineCPSmethodmismatches-Callingnon-CPS-transformedmethodswithCPS-transformedarguments.
=> Jenkinsfile: Work around a sandboxing issue with custom comparators
