analyzer/src/main/kotlin/managers/utils/MavenSupport.kt

Starters are a set of convenient dependency descriptors that you can
include in your application, see [1].
Starters usually have no sources published at all (see e.g. [2]), and if
sources are published, they only contain metadata file in the `META-INF`
directory that can also be retrieved from the POM.
[1]: https://github.com/spring-projects/spring-boot#spring-boot-starters
[2]: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-undertow/2.0.8.RELEASE/
[3]: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-security/2.6.0/

MavenSupport: Handle Sprint Boot Starters as metadata-only packages

---

model/src/main/kotlin/utils/Extensions.kt
model/src/test/kotlin/IdentifierTest.kt

This allows to customize the creation of purls in plugins i.e. create
[Package] instances with a special purl.
The extracted function offers also the possible to pass additional
query parameters to the purls that the previous implementation didn't.

purls: Extract 'toPurl' function's content

---

.azure-pipelines.yml
.azure-pipelines/LinuxAnalyzerTest.yml
.azure-pipelines/WindowsAnalyzerTest.yml
reporter-web-app/build.gradle.kts

Use the same version of NPM as in the Dockerfile as Azure's new default
version 8.1.0 causes problems with the lockfiles committed as part of the
test assets.

azure-pipelines: Pin the NPM version to 7.20.6

---

Dockerfile

Add ORT binary directory to the path variable to enable the shell to
find the ORT tool.
This is useful if the container is used with its entry point overridden
and to run multiple ORT commands sequentially without restarting the
container.
Signed-off-by: Jens Erdmann <jens.erdmann@web.de>

Dockerfile: Extend PATH

---

analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
model/src/main/kotlin/utils/Extensions.kt
reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
reporter/src/main/kotlin/reporters/spdx/SpdxDocumentModelMapper.kt

Sanitize creating an `Identifier` from SPDX

---

Dockerfile

This is to benefit from layer caching for different SCANCODE_VERSION
build arguments.

Dockerfile: Move installing ScanCode to its own layer

---

cli/src/main/kotlin/commands/DownloaderCommand.kt
cli/src/main/kotlin/commands/ScannerCommand.kt
helper-cli/src/main/kotlin/commands/ListPackagesCommand.kt
model/src/main/kotlin/PackageType.kt
scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
scanner/src/main/kotlin/experimental/ScanContext.kt
scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt

`DataEntity` is a very generic name, replace it with a more specific
name that better describes the purpose of the enum. While at it, also
improve the documentation of the enum and rename the command line
parameters accordingly.

Rename `DataEntity` to `PackageType`

---

analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm-babel/package-lock.json

This should fix the error with NPM trying to install the optional
fsevents package on a non-darwin platform. Also see [1].
[1]: https://github.com/npm/cli/issues/2291

BabelFunTest: Recreate the lockfile in v2 using NPM 7.20.6

---

.azure-pipelines/LinuxTest.yml
reporter-web-app/src/App.css
reporter-web-app/src/components/SummaryView.js
reporter-web-app/src/components/VulnerabilitiesTable.js
reporter-web-app/src/models/Statistics.js
reporter-web-app/src/models/VulnerabilityReference.js
reporter-web-app/src/models/WebAppOrtResult.js
reporter-web-app/src/models/WebAppRuleViolation.js
reporter-web-app/src/models/WebAppVulnerability.js
reporter-web-app/src/reducers/index.js
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModel.kt
reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModelMapper.kt
reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedVulnerabilityReference.kt

Initial implementation to show vulnerabilities in the WebApp report.
Closes #4630

Show vulnerabilities WebApp report

---

gradle.properties

See [1].
[1]: https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/5.3.0

Gradle: Upgrade GraphQL dependencies to version 5.3.0

---

.github/workflows/build-and-test.yml

This job suffers from [1].
[1]: https://github.com/burrunan/gradle-cache-action/issues/40

github-workflows: Disable the reporter-web-app build for now

---

model/src/main/kotlin/AdvisorRecord.kt
model/src/test/kotlin/AdvisorRecordTest.kt
reporter/src/funTest/kotlin/TestData.kt
reporter/src/funTest/kotlin/reporters/freemarker/asciidoc/PdfTemplateReporterFunTest.kt
reporter/src/main/kotlin/reporters/freemarker/FreemarkerTemplateProcessor.kt
reporter/src/main/kotlin/reporters/freemarker/asciidoc/AsciiDocTemplateReporter.kt
reporter/src/main/resources/templates/asciidoc/defect_report.ftl
reporter/src/main/resources/templates/asciidoc/vulnerability_report.ftl
reporter/src/test/kotlin/reporters/freemarker/FreeMarkerTemplateProcessorTest.kt

Analogously to the vulnerability report, a report for defects is now be generated if the ORT result contains corresponding information. For this purpose, a new template was added.
This PR also adapts the existing template for vulnerabilities to make sure that information and issues from the different advisors do not interfere with each other.

Add a defect report

---

helper-cli/src/main/kotlin/common/Utils.kt

The import path excludes command makes the assumption that each
nested repository is contained in
`OrtResult.repsitory.nestedRepositories`. This assumtpion does not
always hold for Git submodules of Git repositories cloned via Git-Repo
for unknown reason. Work around that creating additional entries from
the VCS info of the projects.
The (broken) assumption has been introduced by [1].
[1] 23dfaca4cc287b88c83ea438839924b7657b27ff

helper-cli: Fix a potential NPE with the path exclude import

---

helper-cli/src/main/kotlin/commands/packageconfig/ExportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/ImportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/repoconfig/ExportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/repoconfig/ImportPathExcludesCommand.kt
helper-cli/src/main/kotlin/common/Utils.kt
helper-cli/src/main/kotlin/common/VcsUrlMapping.kt

Some VCSes are hosted on multiple hosts, e.g. a original repository and a mirror repository.
Allow for mapping the `host` part of the VCS URL so that redundant entries can be avoided as well as the
inconvenience which that'd brings.

helper-cli: Allow for mapping VCS URLs when importing / exporting path excludes

---

analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
utils/core/src/main/kotlin/OkHttpClientHelper.kt

Support preemptive authentication when resolving remote SPDX documents
via HTTP. This is required to download e.g. from Bitbucket which does
not trigger reactive authentication via a 401 "Not Authorized" response,
but forwards to a login page.

SpdxDocumentFile: Support preemptive HTTP authentication

---

reporter/src/main/kotlin/reporters/freemarker/FreemarkerTemplateProcessor.kt
reporter/src/test/kotlin/reporters/freemarker/FreeMarkerTemplateProcessorTest.kt

Templates rendering advisor results currently operate on package
identifiers only, since the results do not contain the packages
themselves. There is no direct way to obtain the referenced package.
As this is useful, e.g. to display additional metadata of a package,
provide a function in TemplateHelper that resolves a package for a
given ID.

TemplateHelper: Allow access to packages by their identifiers

---

analyzer/src/funTest/assets/projects/synthetic/spdx-project-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/spdx/package/libs/zlib/package.spdx.yml
analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml
analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
analyzer/src/test/kotlin/managers/SpdxDocumentFileTest.kt

Use `GENERATED_FROM` SPDX relations to distinguish between source and binary artifacts

---

helper-cli/src/main/kotlin/commands/packageconfig/ExportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/ExportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/ImportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/commands/repoconfig/ExportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/commands/repoconfig/ExportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/repoconfig/ImportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/common/Utils.kt

The implementation is analog to the existing one for path excludes.

helper-cli: Allow mapping VCS URLs for the import / export of license finding curations

---

utils/core/src/main/kotlin/OkHttpClientHelper.kt

Include building the request (and converting the String to a URL) into
`runCatching` to also catch any `IllegalArgumentException` due to invalid
URL schemes.

OkHttpClientHelper: Catch exceptions due to illegal URLs

---

.github/workflows/build-and-test.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/static-analysis.yml

Save some build minutes by not also running on `master` after the merge.

github-workflows: Trigger only on the "virtual merge" with `master`

---

analyzer/src/main/kotlin/managers/Sbt.kt
utils/common/src/main/kotlin/DirectoryStash.kt

Prefer Kotlin's `moveTo()` extension function over `Files.move()`

---

analyzer/src/main/kotlin/managers/Npm.kt

Some `debug` log statements may trash the analysis execution performance as they are to frequent. So, reduce the level to `trace`. Apart from that save I/Os by a factor of about 1000 and add some alternative debug logging so that there is at least some status output on the `debug` log level.

Npm: Performance and debug logging

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt

Use the proxies configured in the `settings.xml` when requesting remote
artifacts.
The proxies were already configured in the `RepositorySystemSession` but
are not automatically used for repositories which are parsed from
arbitrary POM files, so this has to be done manually.

MavenSupport: Use proxies when requesting remote artifacts

---

utils/spdx/src/main/resources/declared-license-mapping.yml

Found "European Union Public Licence (EUPL v.1.1)" in [1].
[1]: https://github.com/felleslosninger/efm-commons-libs/blob/master/commons-bdx/pom.xml#L41

declared-license-mapping: Add EUPL-1-1 mapping

---

analyzer/src/main/kotlin/managers/GoMod.kt

The analysis result may contain packages which are not referenced from the dependency tree.
Remove these package as they are not needed and find the rationale for it in the commit.

Gomod: Reduce over-reporting of packages

---

clients/fossid-webapp/src/main/kotlin/model/Scan.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt

Historically in ORT, the id was always a free nullable String even if
the FossID server in fact always returned the id as a non-nullable
integer.
This led to a subtle bug: when creating new delta scan,
FossID.recentScansForRepository was listing all the scans and sorting
them with .sortedByDescending { scan.id }, i.e. alphanumerically.
We didn't notice this behaviour because our scan ids were between 1000
and 9999 for a long time. As soon as the server went over 10000, the
lexicographic sorting order was wrong and led to cases where older scans
were used for delta scans basis, and also newer scans were automatically
deleted by ORT scanner.

fossid-webapp: Make Scan.id an integer

---

.github/workflows/static-analysis.yml
build.gradle.kts

detekt 1.19.0 creates the merged SARIF report by itself, so just use
that.

Gradle: Use the merged report created by detekt itself

---

utils/spdx/src/main/resources/declared-license-mapping.yml

Found in [1].
[1] https://github.com/wdtinc/mapbox-vector-tile-java/blob/81d2ea92fe255eab5c1005ec86c8a9160fdf44dd/pom.xml#L18

declared-license-mapping: Add "Apache Licence 2.0"

---

reporter/src/main/kotlin/reporters/spdx/SpdxDocumentModelMapper.kt

The package verification code is not always available in scan results.
This is currently the case for the `FossId` scanner and for the
`ExperimentalScanner`. As a result the `SdpxDocumentModelMapper` can
fail because it requires a package verification code if a scan result
for a package is available.
From the SPDX specification is not totally clear if a package
verification code [1] is always required if the `FilesAnalyzer` property
[2] is set to `true`, but the SPDX validation tool [3] rejects such
files.
Therefore only set `FilesAnalyzed` to `true` if we can provide a package
verification code, to make sure that the generated documents pass the
SPDX validation.
[1]: https://spdx.github.io/spdx-spec/package-information/#7.9
[2]: https://spdx.github.io/spdx-spec/package-information/#7.8 …

SpdxDocumentModelMapper: Add verification code only if available

---

advisor/src/main/kotlin/Advisor.kt
advisor/src/test/kotlin/AdvisorTest.kt

It does not make sense to invoke the advice providers if there are no
packages they can operate on. Therefore, return early in this case.

Advisor: Skip execution if there are no packages in the ORT result

---

downloader/src/funTest/kotlin/BabelDownloaderFunTest.kt

To deduplicate from "analyzer/src/funTest/kotlin/managers/BabelFunTest.kt".

Rename the downloader's `BabelFunTest` to `BabelDownloaderFunTest`

---

scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt

The inner `Factory` class is unused in this case.

ScannerIntegrationFunTest: Remove the `DummyScanner`s `Factory` class

---

cli/src/main/kotlin/commands/ScannerCommand.kt
scanner/src/main/kotlin/experimental/ExperimentalScanner.kt

Support the optional skipping of excluded packages and packages with concluded license.

ExperimentalScanner: Support skip options

---

cli/src/main/kotlin/commands/ScannerCommand.kt
scanner/src/funTest/kotlin/scanners/AbstractScannerFunTest.kt
scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
scanner/src/funTest/kotlin/scanners/scancode/ScanCodeScannerFunTest.kt
scanner/src/main/kotlin/PathScanner.kt
scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/scanners/Askalono.kt
scanner/src/main/kotlin/scanners/BoyterLc.kt
scanner/src/main/kotlin/scanners/Licensee.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
scanner/src/test/kotlin/PathScannerTest.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt

The idea of collecting a scanner's native scan result files in addition
to ORT's scan result file had only `PathScanner`s in mind. But by now,
there are scanners that operate remotely, and which do not actually have
a native scan result file format.
So simplify the code by removing support for the "native-scan-results"
directory, and let individual scanners create temporary output
directories where needed.
This also allows to get rid of the `PathScanner`'s `resultFileExt`
property.

scanner: Do not create a "native-scan-results" directory anymore

---

scanner/src/main/kotlin/experimental/ExperimentalScanner.kt

Do not scan packages which provide only metadata and no source code.

ExperimentalScanner: Skip packages which are metadata only

---

analyzer/src/main/kotlin/managers/Pub.kt

The flutter binary might be a symlink to another location which is
problematic because the resolved parent directories might look different
as expected.

Pub: Resolve symlinks for flutterHome

---

scanner/src/main/kotlin/experimental/ExperimentalScanner.kt

Call the `log` helper on the `ExperimentalScanner` class in extension
functions.

ExperimentalScanner: Fix logging issue

---

build.gradle.kts

See the naming pattern at [1].
[1]: https://gradle.org/nightly/

Ignore Gradle nightly versions when checking for dependency updates

---

model/src/main/kotlin/Identifier.kt
model/src/test/kotlin/IdentifierTest.kt

While it is a good practice to use the dot notation in the Maven
groupId, it is not required [1]. See [2] for a popular example.
[1]: https://maven.apache.org/pom.html#maven-coordinates
[2]: https://github.com/junit-team/junit4/blob/main/pom.xml

Identifier: Allow Maven namespaces without TLD

---

scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/experimental/ScannerWrapper.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt

This is to match the `ScannerWrapper`s function name so both can be
implemented by the same code. While at it, also align function docs.
This also requires to remove the `ScannerWrapper`s default
implementation in the interface, as otherwise it would clash with the
`Scanner`s default implementation.

Scanner: Rename `filterOptionsForResult()` to `filterSecretOptions()`

---

helper-cli/src/main/kotlin/common/Utils.kt

Only consider scan results associated to the package, otherwise a scan
result that belongs to another package from the same repository could
accidentally be matched.
Fixes #4849.

helper-cli: Fix getting the scan result provenance of a package

---

scanner/src/main/kotlin/CommandLineScanner.kt

Do not override `getVersionRequirement()` and instead use the default
implementation which allows any version.
Since 9af81d8 any version of the command line scanners is accepted, the
expected version is only used to bootstrap a scanner if it is not found
on the path. Therefore returning the expected version as a requirement
was wrong.

CommandLineScanner: Do not require the expected version

---

build.gradle.kts

Esp. setting `useJUnitPlatform()` not only when the task graph is ready
avoids the bogus "Test framework is changing" message [1] from Gradle.
[1]: https://github.com/oss-review-toolkit/ort/runs/4658469363?check_suite_focus=true#step:4:74

Gradle: Configure all test properties but JaCoCo early

---

gradle.properties

See [1].
[1]: https://github.com/ben-manes/gradle-versions-plugin/releases/tag/v0.40.0

Gradle: Upgrade the "versions" plugin to version 0.40.0

---

model/src/main/kotlin/config/ScannerConfiguration.kt
scanner/src/funTest/assets/dummy-expected-output-for-analyzer-result.yml

SPDX files declare metadata and might contain license identifiers and
license texts. As these are already picked up by the `SpdxDocumentFile`
analyzer, they should not be picked up by scanners again to generate
detected findings.
At the example of ScanCode, ORT runs ScanCode without `-p` /
`--package`, so ScanCode does not scan / interpret "package manifests and
build scripts". Thus ignoring SPDX project / package files is in line
with that.

ScannerConfiguration: Ignore SPDX files by default

---

clients/nexus-iq/build.gradle.kts
clients/nexus-iq/src/main/kotlin/NexusIqService.kt

This is for portability and to align with the OSS Index implementation.

nexus-iq: Port from Jackson to kotlinx.serialization

---

build.gradle.kts

To benefit from bytecode optimizations, always use the latest supported
JVM target. Note that at a minimum still Java 11 is required.

Gradle: Target the latest version supported by the current JVM

---

README.md
cli/src/funTest/kotlin/ExamplesFunTest.kt
cli/src/main/kotlin/commands/EvaluatorCommand.kt
docs/config-file-curations-yml.md
docs/config-file-license-classifications-yml.md
docs/config-file-package-configuration-yml.md
docs/file-rules-kts.md
docs/getting-started.md
evaluator/build.gradle.kts
evaluator/src/main/kotlin/Evaluator.kt
evaluator/src/main/resources/rules/no_gpl.rules.kts
evaluator/src/test/kotlin/EvaluatorTest.kt
examples/example.rules.kts
settings.gradle.kts
utils/core/src/main/kotlin/Constants.kt
utils/scripting/build.gradle.kts
utils/scripting/src/main/kotlin/RulesScriptConfiguration.kt
utils/scripting/src/main/kotlin/ScriptRunner.kt

Rules scripting

---

scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt

Add custom matchers to reduce the boilerplate code required to assert
license and copyright findings.

ScanCodeResultParserTest: Add custom matchers to reduce boilerplate code

---

utils/spdx/src/main/resources/declared-license-mapping.yml
utils/spdx/src/main/resources/licenserefs/LicenseRef-ort-oracle-futc
utils/spdx/src/test/kotlin/UtilsTest.kt

Start addressing the missing license texts for LicenseRef-ort licenses from the declared license mapping (#3909). See the commit messages for details.

Handle part of the LicenseRef-ort license texts

---

notifier/src/main/kotlin/modules/JiraNotifier.kt
notifier/src/test/kotlin/modules/JiraNotifierTest.kt

Use Kotlin built-in functionality wherever possible.
Note that there seems to be a nullability issue with Kotest's
`shouldBeSuccess` / `shouldBeFailure` matchers, see [1].
[1]: https://github.com/kotest/kotest/issues/2759

JiraNotifier: Port from ORT's `Result` to Kotlin's `Result`

---

utils/spdx/src/main/resources/licenserefs/LicenseRef-ort-google-maps-tos

Taken from [1] but omitted the date as packages that use this license do
not mention a specific version, e.g. [2].
[1] https://cloud.google.com/maps-platform/terms/
[2]
https://maven.google.com/com/google/android/libraries/places/places/2.3.0/places-2.3.0.pom
Resolves #3909.

LicenseRef: Add Google Maps Terms of Service LicenseRef

---

.github/workflows/automatic-rebase.yml

See [1]. This hopefully fixes the "unable to find version `1`" error
[2].
[1]: https://github.com/cirrus-actions/rebase#installation
[2]: https://github.com/oss-review-toolkit/ort/actions/runs/1678809665

github: Use latest installation instructions for the rebase action

---

Dockerfile

This bumps the base image from `adoptopenjdk:11-jre-hotspot-bionic` to `adoptopenjdk:11-jre-hotspot-focal`. With just minor version changes. 
The only complication is potentially, that the package `python-pip` is no longer available.

docker base image 11-jre-hotspot-bionic -> 11-jre-hotspot-focal

---

utils/spdx/src/main/kotlin/SpdxExpression.kt
utils/spdx/src/test/kotlin/SpdxExpressionTest.kt

In contrast to the argumentation in fe1f1ff, this should not cause any
severe performance issues with large expressions as "equals()" does not
call `toString()`.

SpdxExpression: Simplify the DNF for compound expressions with equal operands

---

analyzer/src/main/kotlin/managers/GradleDependencyHandler.kt

If a package cannot be created because of a `RepositoryException` which
occurs during downloading the metadata of the package, handle this
gracefully instead of failing the whole dependency resolution for the
package.

GradleDependencyHandler: Also catch RepositoryException

---

utils/spdx/src/main/kotlin/SpdxExpression.kt
utils/spdx/src/test/kotlin/SpdxExpressionTest.kt

This reverts commit c1f60d0. For once, simplification of expressions
should not be part of canonization via the DNF. Secondly, "a AND b"
needs to stay a valid choice in the test, as the first occurrence of "a
OR b" and the second occurrence of "a OR b" might be located in different
packages, for which independent choices can be made.

Revert "SpdxExpression: Simplify the DNF for compound expressions with equal operands"

---

Dockerfile

This reverts commit 80d0d3e. Projects that use the Gradle wrapper to
bootstrap a version of Gradle prior to 7.3 cannot be analyzed with Java
17 as the version of Groovy / ASM used in those Gradle versions cannot
handle Java 17 bytecode, see [1].
[1]: https://github.com/gradle/gradle/issues/16857

Revert "Dockerfile: Build and run ORT with Java 17 LTS"

---

cli/src/main/kotlin/commands/ScannerCommand.kt

This is good for double-checking that the expected version is being used.

ScannerCommand: Also print the version of used scanners

---

analyzer/src/main/kotlin/managers/Pip.kt

When the classifier format is accidentally used in the `license` property, it happens that just "OSI Approved :: " is used accidentally as the prefix instead of "License :: OSI Approved :: ". Add a work-around so this gets properly parsed.

Pip: Extend the work-around for declared license parsing

---

evaluator/src/main/kotlin/Evaluator.kt
utils/scripting/src/main/kotlin/RulesScriptConfiguration.kt

Policy rules may require the current date and time as input, such as
e.g. checks for copyright year ranges. Constructor inject the date and
time into the script to avoid a direct dependency on the system time in
order not to sacrifice testability.

Evaluator: Pass the current time to the policy rules script

---

analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
helper-cli/src/main/kotlin/commands/SetDependencyRepresentationCommand.kt
model/src/main/kotlin/AnalyzerResult.kt
model/src/main/kotlin/OrtResult.kt
model/src/test/kotlin/utils/DependencyGraphConverterTest.kt
reporter/src/main/kotlin/reporters/OpossumReporter.kt

SetDependencyRepresentationCommand currently only supports conversions
to the dependency graph format. Conversions to the tree format are
useful as well, as this format is more readable and is better suited
to analyze dependencies. So, extend the command to support conversions
in this direction, too.

helper-cli: Support conversions to the dependency tree format

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt

See e.g. [1], whose JAR is empty besides some META-INF entries.
[1]: https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-starter-stream-rabbit/3.1.3/

MavenSupport: Also treat Spring Cloud Starter projects as `isMetaDataOnly`

---

README.md
advisor/src/main/kotlin/Advisor.kt
analyzer/src/funTest/kotlin/managers/SbtFunTest.kt
analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/managers/Pub.kt
analyzer/src/main/kotlin/managers/Unmanaged.kt
analyzer/src/main/resources/META-INF/services/org.ossreviewtoolkit.analyzer.PackageManagerFactory
analyzer/src/test/kotlin/PackageManagerTest.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
downloader/src/main/kotlin/VersionControlSystem.kt
reporter/src/main/kotlin/Reporter.kt
scanner/src/main/kotlin/Scanner.kt

Allow to deactivate package managers

---

gradle.properties

Gradle: Add a code comment why adding the Kotlin stdlib is disabled

---

analyzer/src/main/kotlin/curation/OrtConfigPackageCurationProvider.kt

Return only curations which are applicable to the provided package id.
This is required because the curation files can contain curations for
multiple versions.

OrtConfigPackageCurationProvider: Filter applicable curations

---

analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt

Use the homepage URL of a project as fallback URL for the VCS URL like
it is already done for other package managers.

NuGetSupport: Use the homepage URL as fallback for the VCS URL

---

analyzer/src/main/kotlin/PackageManager.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
model/src/main/kotlin/OrtResult.kt
reporter/src/main/kotlin/reporters/ctrlx/CtrlXAutomationModel.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt

Otherwise writing the report for such scan results would fail.

CtrlXAutomationModel: Relax the SPDX check to allow LicenseRef exceptions

---

cli/build.gradle.kts
gradle.properties

Run it like `./gradlew :cli:nativeImage`. While this does not succeed yet,
there seem to only be a few blockers to get it running, so still make
this publicly available for people to play with.

Gradle: Apply the `gradle-graal` plugin to experiment with native images

---

gradle.properties
scanner/src/main/kotlin/scanners/Licensee.kt

See [1].
[1]: https://github.com/licensee/licensee/releases/tag/v9.15.1

Upgrade the Licensee version to bootstrap to 9.15.1

---

analyzer/src/main/kotlin/managers/GoMod.kt

Improve guessing the VCS information from package IDs like
GoMod::github.com/lithammer/shortuuid/v3:v3.0.4
by stripping the "/v3" suffix from the path before passing the URL to
`VcsHost.toVcsInfo()`.

GoMod: Strip a major version suffix from host path URLs

---

scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
utils/spdx/src/main/kotlin/Utils.kt

ScanCode has one SPDX license key containing an underscore characters
which is not allwed, see [1]. This results in ORT's scanner crashing
due to an SpdxException when it tries to parse the SPDX license key.
This issue has first occured in 2020 and been fixed by [2]. It got
re-introduced recently by [3].
Deliberatly don't fix the general problem with underscores in
`getLicenseTextFile()` in favor of a license ID specific work around,
because this can be implemented efficiently without doing a refactoring
first.
[1] nexB/scancode-toolkit#2813
[2] fb0370f
[3] #4523

ScanCode: Work around an underscore in a SPDX license key

---

analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
analyzer/src/main/kotlin/managers/utils/SpdxDocumentCache.kt
analyzer/src/main/kotlin/managers/utils/SpdxResolvedDocument.kt
analyzer/src/test/kotlin/managers/utils/SpdxDocumentCacheTest.kt
analyzer/src/test/kotlin/managers/utils/SpdxResolvedDocumentTest.kt
utils/spdx/src/main/kotlin/model/SpdxDocument.kt
utils/spdx/src/main/kotlin/model/SpdxExternalDocumentReference.kt
utils/spdx/src/main/kotlin/model/SpdxExtractedLicenseInfo.kt
utils/spdx/src/main/kotlin/model/SpdxRelationship.kt

Resolving a path against a URI drops the original query string. However,
the query string might be required to get the right file, so copy an
existing query string over on resolution.

SpdxResolvedDocument: Copy over query strings when resolving URIs

---

cli/build.gradle.kts
helper-cli/build.gradle.kts

(helper-)cli: Stop using the deprecated `mainClassName`

---

reporter/src/main/kotlin/reporters/ExcelReporter.kt
reporter/src/main/kotlin/reporters/freemarker/asciidoc/AsciiDocTemplateReporter.kt

Reduce the duration of running `ort --help` from ~13s to ~2s, see the commit messages for details.

Improve startup performance

---

.detekt.yml
detekt-rules/src/main/kotlin/OrtImportOrder.kt
detekt-rules/src/main/kotlin/OrtPackageNaming.kt
detekt-rules/src/main/kotlin/OrtRuleSet.kt

If no config object is passed to a rule it is always active. If a config
object is passed the rule is inactive by default, but can be activated
in the configuration.
Pass the config to both rules to allow to enable them selectively when
reusing them in another project.

detekt-rules: Pass the config to the rules

---

Dockerfile

The previously used version 1.3.8 contains a vulnerable version of
log4j-core [1]. Upgrade to the latest available version [2].
[1]: https://www.scala-lang.org/blog-detail/2021/12/16/state-of-log4j-in-scala-ecosystem.html
[2]: https://github.com/sbt/sbt/releases/tag/v1.6.1

Dockerfile: Upgrade sbt to version 1.6.1

---

scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt

Parenthesis are not allowed in license expressions, resulting in an
exception when trying to parse these with `toSpdx()`.

FossIdScanResults: Replace problematic FossID licenses with valid expressions

---

.lift.toml

ESLint is already run as part of ORT's build and Lift is returning tens of
false-positives in pull requests see for example [1].
[1]: https://github.com/oss-review-toolkit/ort/pull/5012

Disable Sonatype Lift's JavaScript checks

---

scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt

FossIdScanResults: Reduce the number of `toSpdx()` calls

---

utils/core/src/main/kotlin/OkHttpClientHelper.kt

This allows to see where leaked connections were allocated.

OkHttpClientHelper: Set OkHttp's logging to "fine" in ORT's "debug" log level

---

.github/workflows/build-and-test.yml

Try whether the caching issue from [1] has "disappeared".
[1]: https://github.com/burrunan/gradle-cache-action/issues/40

github-workflows: Enable the build-reporter-web-app job again

---

gradle.properties
reporter/build.gradle.kts
reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/funTest/kotlin/reporters/StaticHtmlReporterFunTest.kt

The latest Apache Xalan 2.7.2 is 8 years old and does not support the
`accessExternalDTD` attribute that Apache POI requires, so switch to
the actively maintained Saxon TransformerFactory instead. Fixes #4830.

reporter: Replace the Xalan TransformerFactory with Saxon

---

utils/spdx/src/main/kotlin/Utils.kt
utils/spdx/src/test/kotlin/UtilsTest.kt

Ignore the '+' operator when getting the license text of an SPDX license.
For example, for the id 'Apache-2.0+' return the license text for
'Apache-2.0'. This is valid, because in the example 'Apache-2.0' is a
valid license for the expression.
Choosing a later version of the license should be implemented as an
extension of the license choice feature.
Fixes #5004.

spdx-utils: Ignore the '+' operator for SPDX license texts

---

.github/pull_request_template.md

See [1].
[1]: https://github.com/oss-review-toolkit/.github/pull/1

Remove the pull-request template in favor of a shared one

---

analyzer/src/funTest/kotlin/integration/DrupalIntegrationFunTest.kt

See [1]. Since https://github.com/oss-review-toolkit/ort/commit/a8bf05debf8f59a49b1f99eeb80dbfcf44e46cc3 empty definition files are skipped. This went
unnoticed until now as expensive functional tests are currently not run.
[1]: https://github.com/drupal/drupal/blob/4a76549/core/modules/system/tests/fixtures/HtaccessTest/composer.json

DrupalIntegrationFunTest: Remove an empty `composer.json` from expected results

---

helper-cli/build.gradle.kts
helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
helper-cli/src/main/kotlin/commands/DownloadResultsFromPostgresCommand.kt

The `cli` module provides the UploadResultToPostgresCommand. Add a
command to retrieve the previously uploaded commands. This can be useful
to synchronize a local directory with the database incrementally, in
order to play around with the latest data on the local machine.
Use md5sums to detect broken files, so that the download is gracefully
resumed after a hard exit or a connectivity issue. The need for md5sums
prevented the re-use of the LocalFileStorage class.

helper-cli: Add a command to download results from Postgres

---

.github/workflows/build-and-test.yml
.github/workflows/static-analysis.yml
Dockerfile
batect.yml

The former is deprecated in favor of the latter, see [1].
[1]: https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/

Consistenly switch from AdoptOpenJDK to Eclipse Temurin

---

utils/spdx/src/main/kotlin/SpdxExpression.kt
utils/spdx/src/test/kotlin/SpdxExpressionTest.kt

Add parenthesis to the string representation and fix an issue with applying license choices. See the commit messages for details.

SpdxExpression: Add parentheses in string representation

---

utils/spdx/src/main/resources/declared-license-mapping.yml

Found in [1].
[1]: https://repo.maven.apache.org/maven2/com/google/re2j/re2j/1.3/re2j-1.3.pom
Signed-off-by: Shruti Dadoo <shruti.dadoo@here.com>

declared-license-mapping: Add "Go License"

---

.codecov.yml

See [1].
[1]: https://docs.codecov.com/docs/pull-request-comments#after_n_builds

Avoid Codecov to comment on pull-requests before all reports are uploaded

---

analyzer/src/main/kotlin/managers/Gradle.kt

Remove a redundant and inconsistent code path for finding the files
managed by Pub by calling the dedicated `findManagedFiles()`. This
removes the assumption that `Pub.Factory.globsForDefinitionFiles` only
contains filenames and properly applies IGNORED_DIRECTORY_MATCHERS, see
`findManagedFiles()`.

Gradle: Fix some potential issues with the filtering of definition files

---

analyzer/src/main/kotlin/managers/Gradle.kt
analyzer/src/main/kotlin/managers/Maven.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/utils/GradleDependencyHandler.kt
analyzer/src/main/kotlin/managers/utils/MavenDependencyHandler.kt
analyzer/src/main/kotlin/managers/utils/NpmDependencyHandler.kt
analyzer/src/test/kotlin/managers/utils/GradleDependencyHandlerTest.kt
analyzer/src/test/kotlin/managers/utils/MavenDependencyHandlerTest.kt
analyzer/src/test/kotlin/managers/utils/NpmDependencyHandlerTest.kt

The top-level `managers` package should only contain the core package
manager implementations themselves for a better overview.

analyzer: Move dependency handlers to the `utils` package

---

cli/src/main/kotlin/commands/AnalyzerCommand.kt

AnalyzerCommand: Fix typos in console output

---

cli/build.gradle.kts
cli/src/main/kotlin/commands/RequirementsCommand.kt
utils/spdx/src/main/kotlin/Utils.kt

As of 9946f7e, ScanCode gets installed via `pip` in the `Dockerfile`,
resulting the ScanCode binary to be placed in
/usr/local/bin/scancode
and the licenses in
/usr/local/lib/python3.8/dist-packages/licensedcode/data/licenses
This causes non-SPDX license texts to not be found anymore as the
"dist-packages" sub-directory is no search candidate. Instead of adding
it as a candidate, generalize the lookup logic to avoid such issues in
the future.

spdx-utils: Generalize the `scanCodeLicenseTextDir` logic

---

.codecov.yml

Add a threshold to not report a failure when adding small amounts of
code without coverage. For reference see [1].
[1]: https://docs.codecov.com/docs/commit-status

Codecov: Allow the coverage to drop by up to 0.1%

---

model/src/test/kotlin/utils/FindingsMatcherTest.kt

FindingsMatcherTest: Add a test for non-belonging licenses / exceptions

---

model/src/test/kotlin/utils/FindingsMatcherTest.kt

FindingsMatcherTest: Fix a typo in a test name

---

model/src/main/kotlin/utils/FileArchiver.kt
scanner/src/main/kotlin/PathScanner.kt

Only log (the performance) in the downstream `archive()` function. The
package coordinates are still visible from the logged directory name.

Improve logging when archiving files

---

analyzer/src/main/kotlin/managers/Pub.kt

The existing implementation exhibits several issues in case there is more than one Pub definition file under the `analysis root` directory. Fix a couple of them, see individual commits.
See also #5100.

Pub: Fix several issues with the analysis of Gradle projects

---

scanner/src/funTest/kotlin/experimental/DefaultPackageProvenanceResolverFunTest.kt
scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
scanner/src/main/kotlin/experimental/PackageProvenanceResolver.kt
scanner/src/main/kotlin/experimental/ScanController.kt
scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt

Several refactorings of the experimental scanner code, see the commit messages for details. This is only the first part of the refactoring, another refactoring will follow which will add handling of issues during provenance resolution and might also include a cleaner implementation of #5047.

ExperimentalScanner refactoring

---

.github/workflows/build-and-test.yml

This is a try to solve the issue described in [1].
[1]: https://github.com/burrunan/gradle-cache-action/issues/40

github/workflows: Split Gradle caches for jobs that run in parallel

---

analyzer/src/funTest/assets/projects/synthetic/dotnet-direct-dependencies-only-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output-with-nuspec.yml
analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/nuget-direct-dependencies-only-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml
analyzer/src/funTest/kotlin/managers/DotNetFunTest.kt
analyzer/src/funTest/kotlin/managers/NuGetFunTest.kt
analyzer/src/main/kotlin/managers/DotNet.kt
analyzer/src/main/kotlin/managers/NuGet.kt
analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
model/src/main/kotlin/config/AnalyzerConfiguration.kt
model/src/main/resources/reference.conf

Add support for separate scopes and an option to resolve only direct dependencies to NuGet based package managers. See the commit messages for details.

NuGet: Scopes and direct dependencies

---

clients/fossid-webapp/src/main/kotlin/model/status/ScanDescription2021dot2.kt

It seems that, when triggering a scan and requesting its status
straightaway, FossID server answers with a `null` value for the
property `percentageDone` of a `ScanDescription`.
This seems to be a regression introduced in FossID 21.2.4.
This fixes forllowing exception
```
01:21:13.998 [main] INFO  org.ossreviewtoolkit.scanner.scanners.fossid.FossId - Waiting for scan 'IO_OSM_Standard_snippet_scanners-example-projects-csharp_20220304_012102_delta' to complete.
Exception in thread "main" com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class org.ossreviewtoolkit.clients.fossid.model.status.ScanDescription2021dot2] value failed for JSON property percentage_done due to missing (therefore NULL) value for creator parameter percentageDone which …
```

fossid-webapp: Make `ScanDescription.percentagedone` nullable

---

model/src/main/kotlin/LicenseFinding.kt
scanner/src/main/kotlin/scanners/Askalono.kt
scanner/src/main/kotlin/scanners/BoyterLc.kt
scanner/src/main/kotlin/scanners/Licensee.kt
scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
scanner/src/main/kotlin/scanners/scanoss/ScanOssResultParser.kt
scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt

Introduce a license finding score

---

Dockerfile

For the release notes see [1].
[1]: https://github.com/bower/bower/releases

Dockerfile: Upgrade Bower to 1.8.12

---

Dockerfile

Without exporting, the variable is not passed to the Gradle process at
all.

Dockerfile: Properly set the GRADLE_USER_HOME variable

---

examples/evaluator-rules/src/main/resources/example.rules.kts

examples: Ignore deprecation of `TEST_TOOL_OF` in a deprecation check

---

analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
analyzer/src/test/kotlin/managers/utils/NodeSupportTest.kt
model/src/test/kotlin/AbstractDependencyNavigatorTest.kt
model/src/test/kotlin/DependencyTreeNavigatorTest.kt
model/src/test/kotlin/IdentifierTest.kt
model/src/test/kotlin/config/OrtConfigurationTest.kt
scanner/src/funTest/kotlin/experimental/DefaultNestedProvenanceResolverFunTest.kt
scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt
utils/common/src/test/kotlin/ExtensionsTest.kt
utils/core/src/test/kotlin/DeclaredLicenseProcessorTest.kt
utils/test/src/main/kotlin/Utils.kt

Use Kotest's new upstream version of `containExactly` for map entries

---

downloader/src/funTest/kotlin/DownloaderFunTest.kt
model/src/test/kotlin/utils/FileArchiverTest.kt
utils/common/src/test/kotlin/ExtensionsTest.kt
utils/core/src/funTest/kotlin/storage/LocalFileStorageFunTest.kt

These matchers provide better messages on failures.

Improve file assertions in tests

---

scripts/import_proxy_certs.sh
scripts/set_gradle_proxy.sh

In https://github.com/oss-review-toolkit/ort/commit/c6b2818af7ed7b960ed8977449314eb4fc6ed783 the docker file was fixed to properly export the gradle
home variable for the gradle application to use.
The set_gradle_proxy.sh script needs to be modified to follow this
change. Up until now it was expecting gradle properties to reside in
$HOME while gradle is now expecting it at GRADLE_USER_HOME.
Whithout this adaptation gradle will fail with a
java.net.UnknownHostException error.
Complete error:
```
#17 1.561 Setting HTTP proxy http://proxy.example.com:3128 for Gradle in file '/root/.gradle/gradle.properties'...
#17 1.564 Setting HTTPS proxy http://proxy.example.com:3128 for Gradle in file '/root/.gradle/gradle.properties'...
#17 1.693 Downloading …
```

Set Gradle Proxy Script: Fix Home Variable and Add no_proxy

---

utils/spdx/src/main/resources/declared-license-mapping.yml

The 'CDDL+GPL' commonly refers to a license choice between these licenses
and not an 'AND' given by Sun/Oracle, see for example [1] and [2].
That the '+' is an 'OR' is also supported by the fact that many in the
community have argued that these licenses incompatible with each other, see
[3],[4] and [5].
[1]: https://repo.maven.apache.org/maven2/org/glassfish/gmbal/gmbal-api-only/3.0.0-b023/gmbal-api-only-3.0.0-b023.pom
[2]: https://web.archive.org/web/20150923052903/https://glassfish.java.net/public/faq/GF_FAQ_2.html#terms
[3]: https://lwn.net/Articles/687550/
[4]: https://www.whitesourcesoftware.com/resources/blog/top-10-cddl-questions-answered/#5_What_is_the_difference_between_the_CDDL_and_the_GNU_GPL_and_is_it_compatible_with_them
[5]: …

declared-license-mapping: Map 'CDDL+GPL' entries with 'OR'

---

analyzer/src/funTest/assets/projects/synthetic/yarn-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/yarn-workspaces/yarn.lock
analyzer/src/funTest/assets/projects/synthetic/yarn/yarn.lock

At some point, probably due to an NPM version change in ORT's
Dockerfile, the resolution logic seems to have changed, and NPM started
to consolidate domutils versions 1.5.1 and 1.7.0 in the tree to just
version 1.5.1. As the NPM version is not an input property to the tasks
task, this change went unnoticed so far.

YarnFunTest: Update expected results

---

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
analyzer/src/funTest/kotlin/GitRepoFunTest.kt
analyzer/src/main/kotlin/managers/Unmanaged.kt
analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
analyzer/src/test/kotlin/managers/utils/MavenSupportTest.kt
downloader/src/funTest/kotlin/vcs/GitRepoDownloadFunTest.kt
downloader/src/main/kotlin/vcs/GitRepo.kt
helper-cli/src/main/kotlin/commands/packageconfig/CreateCommand.kt
model/src/main/kotlin/ScanResult.kt
model/src/main/kotlin/VcsInfo.kt
model/src/main/kotlin/config/PackageConfiguration.kt
model/src/main/kotlin/utils/Extensions.kt
model/src/main/kotlin/utils/FileArchiverFileStorage.kt
model/src/main/kotlin/utils/PostgresFileArchiverStorage.kt
model/src/test/kotlin/utils/ExtensionsTest.kt
reporter/src/main/kotlin/reporters/freemarker/FreemarkerTemplateProcessor.kt
reporter/src/test/kotlin/reporters/freemarker/FreeMarkerTemplateProcessorTest.kt
scanner/src/funTest/kotlin/experimental/DefaultNestedProvenanceResolverFunTest.kt
scanner/src/main/kotlin/PathScanner.kt
utils/core/src/main/kotlin/Utils.kt
utils/core/src/test/kotlin/UtilsTest.kt

Store the git-repo manifest path in the VCS URL instead of the VCS path to remove the requirement to handle the path different in case the VCS type is git-repo.
This is breaking change because existing curations and package configurations need to be adapted. It does also invalidate stored scan results for git-repo projects because their provenance is changed.

git-repo: Store the manifest path in the VCS URL instead of the VCS path

---

reporter/src/main/kotlin/reporters/gitlab/GitLabLicenseModelMapper.kt
utils/core/src/main/kotlin/Utils.kt

Use the speaking `orEmpty()` in more places

---

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/yarn-expected-output.yml
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/Yarn.kt
analyzer/src/main/kotlin/managers/utils/NodeSupport.kt
analyzer/src/main/kotlin/managers/utils/NpmDependencyHandler.kt
analyzer/src/test/kotlin/managers/utils/NodeSupportTest.kt
analyzer/src/test/kotlin/managers/utils/NpmDependencyHandlerTest.kt

Npm: Fix querying of package details from private / scoped registries 

---

README.md

The default value is always empty, so there is no point in documenting
it in addition to the default location.

README: Remove the "Default value" column from configuration tables

---

scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
scanner/src/main/kotlin/experimental/NestedProvenanceScanResult.kt
scanner/src/main/kotlin/experimental/ScanController.kt
scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt

Always scan the full repository, even if a VCS path is set. This makes
the initial scan slower if a VCS path is set, because more files are
scanned, but it also has several advantages:
* There is exactly one scan result in the storage for each repository
and revision, not multiple for different VCS paths.
* Changing the VCS path via a curation does not require a new scan,
instead the existing result can be reused and filtered appropriately.
* Only one scan of a repository revision is required, no matter how many
packages where published from it.

ExperimentalScanner: Always scan the full repository

---

analyzer/src/main/kotlin/managers/CocoaPods.kt

CocoaPods: Do not take empty declared licenses for packages

---

utils/spdx/src/main/resources/declared-license-mapping.yml

[1]: https://repo1.maven.org/maven2/org/eclipse/californium/parent/2.7.0/parent-2.7.0.pom

utils: Add another Eclipse Distribution License mapping

---

analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/Yarn.kt

This way `npm` / `yarn` should take a project's `.npmrc` / `.yarnrc`
into account.

Npm/Yarn: Run `view`/ `info` in the package directory

---

clients/scanoss/src/main/kotlin/ScanOssService.kt
clients/scanoss/src/test/kotlin/ScanOssDetailsTest.kt
clients/scanoss/src/test/kotlin/ScanOssServiceTest.kt
scanner/build.gradle.kts
scanner/src/main/kotlin/scanners/Askalono.kt
scanner/src/main/kotlin/scanners/BoyterLc.kt
scanner/src/main/kotlin/scanners/Licensee.kt
scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
scanner/src/main/kotlin/scanners/scanoss/ScanOss.kt
scanner/src/main/kotlin/scanners/scanoss/ScanOssConfig.kt
scanner/src/test/assets/scanoss/filesToScan/ArchiveUtils.kt
scanner/src/test/assets/scanoss/filesToScan/ScannerFactory.kt
scanner/src/test/assets/scanoss/scanMulti/mappings/scanoss-multi-response.json
scanner/src/test/assets/scanoss/scanSingle/mappings/scanoss-response.json
scanner/src/test/kotlin/scanners/scanoss/ScanOssScannerDirectoryTest.kt
scanner/src/test/kotlin/scanners/scanoss/ScanOssScannerFileTest.kt

Please refer to individual commit messages for details.
The two sample Java classes are coming from https://github.com/vdurmont/semver4j.

scanoss: Use the new Retrofit-based client

---

analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/utils/NpmDependencyHandler.kt
analyzer/src/test/kotlin/managers/utils/NpmDependencyHandlerTest.kt

In order to apply a project local `.npmrc`/`.yarnrc`, when calling
`view`/`info` the call has to be made in the directory containing this
configuration file.

Npm/Yarn: Use project root directory for `npm view` call

---

Dockerfile
analyzer/src/main/kotlin/managers/Npm.kt

To support projects that require a newer NPM version. NPM 8.5.0 is the
version used by the latest Node.js LTS version [1].
[1]: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#nodejs-16-changelog

NPM: Upgrade to 8.5.0

---

helper-cli/src/main/kotlin/commands/scanstorage/DeleteCommand.kt

Improvements to the `helper-cli`'s scan storage "delete" subcommand

---

clients/fossid-webapp/src/main/kotlin/model/status/DownloadStatus.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt

This fixes the following exception:
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.ossreviewtoolkit.clients.fossid.model.status.DownloadStatus` from String "FAILED": not one of the values accepted for Enum class: [FINISHED, NOT STARTED, NOT FINISHED]
at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 81] (through reference chain: org.ossreviewtoolkit.clients.fossid.EntityResponseBody["data"])
at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1991)
at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationC …
```

fossid-webapp: Handle the case when the download fails

---

helper-cli/src/main/kotlin/commands/scanstorage/DeleteCommand.kt
model/src/main/kotlin/Identifier.kt
model/src/main/kotlin/utils/FindingsMatcher.kt

DeleteCommand: Fix the `slice` command to be executed in a transaction

---

scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt
utils/spdx/src/main/kotlin/Extensions.kt
utils/spdx/src/test/kotlin/ExtensionsTest.kt

ScanCodeResultParser: Fix the license mapping to NOASSERTION

---

cli/src/main/kotlin/commands/ScannerCommand.kt
scanner/src/main/kotlin/experimental/ScannerWrapper.kt
scanner/src/main/kotlin/experimental/ScannerWrapperFactory.kt
scanner/src/main/kotlin/scanners/Askalono.kt
scanner/src/main/kotlin/scanners/BoyterLc.kt
scanner/src/main/kotlin/scanners/Licensee.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
scanner/src/main/kotlin/scanners/scanoss/ScanOss.kt
scanner/src/main/resources/META-INF/services/org.ossreviewtoolkit.scanner.ScannerWrapperFactory
scanner/src/main/resources/META-INF/services/org.ossreviewtoolkit.scanner.experimental.ScannerWrapperFactory

Add support for plugins for the experimental scanner, and for using multiple scanners at once. See the commit messages for details.

`ExperimentalScanner`: Plugin support

---

reporter-web-app/build.gradle.kts

Kotlin 1.6.20 contains node version 16.13.0 [1], therefore the manual
declaration is no longer required.
[1]: https://youtrack.jetbrains.com/issue/KT-49109

Gradle: Remove manual definition of node version

---

model/src/main/kotlin/OrtResult.kt
model/src/test/kotlin/OrtResultTest.kt

The filtering for sub-projects should already happen in `getProjects()`
itself as that is more fitting.

OrtResult: Refactor the `includeSubProjects` parameter to `getProjects()`

---

analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml
analyzer/src/funTest/assets/projects/synthetic/conan-txt/conanfile.txt

This resolves the following error that started to appear:
ERROR: Conflict in libxml2/2.9.12:
'libxml2/2.9.12' requires 'zlib/1.2.12' while 'libcurl/7.80.0'
requires 'zlib/1.2.11'.
To fix this conflict you need to override the package 'zlib' in your
root package.
Note that aligning on the older version 1.2.11 did not make the error go
away, and the new version 1.2.12 lacks source artifact metadata.

ConanFunTest: Make the version of "zlib" explicit

---

clients/fossid-webapp/src/main/kotlin/model/Project.kt

It is not guaranteed that FossId always returns these values. To prevent
a crash due to a deserialization error, specify the properties as
nullable.

fossid-webapp: Make multiple FossId model properties nullable

---

scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt

ScanCodeResultParser: Also map "generic" licenses to `NOASSERTION`

---

clients/nexus-iq/build.gradle.kts
clients/scanoss/build.gradle.kts

This aligns with the majority of existing code.

clients: Use imports instead of fully qualified Gradle task names

---

evaluator/src/main/kotlin/PackageRule.kt
evaluator/src/test/kotlin/PackageRuleTest.kt
evaluator/src/test/kotlin/RuleSetTest.kt
evaluator/src/test/kotlin/TestData.kt
utils/spdx/src/main/kotlin/SpdxConstants.kt
utils/spdx/src/main/kotlin/SpdxExpression.kt

Fix the evaluator's `hasLicense()` for "not present" values 

---

scanner/src/main/kotlin/scanners/fossid/FossId.kt

When a download has status `FAILED`, the logs are not located in the
`error` property, they are in the `message` property.

fossid-webapp: Use the correct property for download failure logging

---

reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
reporter/src/main/kotlin/reporters/spdx/SpdxDocumentModelMapper.kt

Being able to predict the SPDX "idstring" for a given package is a
prerequisite for upcoming changes that will maintain the transitive
package relationships.
The SPDX ID is now derived from the coordinate representation of a
project's / package's `Identifier`. As the `Identifier` is unique within
an `OrtResult`, the derived SPDX ID is very likely unique, too, except
for cases where coordinate representations differ only in special
characters that get mapped to the same valid character for an SPDX ID.

SpdxDocumentModelMapper: Make SPDX "idstring" generation predictable

---

docs/config-file-package-configuration-yml.md
model/src/main/kotlin/config/PackageConfiguration.kt

PackageConfiguration: Support matching any `revision`

---

analyzer/src/main/kotlin/managers/utils/SpdxDocumentCache.kt

If a project contains multiple SPDX files and one of these is invalid
(so that it cannot be loaded), there is no indication in the log,
which file is affected. Therefore, add a log statement allowing to
keep track on the files that are processed.

SpdxDocumentCache: Log the file name before loading it

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt

MavenSupport: Close the `RepositoryConnector` after use

---

analyzer/src/main/kotlin/managers/Npm.kt

Work around Artifactory returning API URLs instead of download URLs for NPM

---

README.md
analyzer/src/main/kotlin/managers/Pip.kt

Pip: Get rid of the `pydep` dependency 

---

analyzer/src/main/kotlin/managers/Cargo.kt
analyzer/src/main/kotlin/managers/Npm.kt

Consistently map references to unknown licenses to NOASSERTION

---

analyzer/src/funTest/assets/projects/synthetic/cargo-expected-output.yml

CargoFunTest: Fixup expected test data with respect to `NOASSERTION`

---

.github/workflows/build-and-test.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/static-analysis.yml

This fixes the issue with Git's new `safe.directory` setting, see [1].
[1]: https://github.com/actions/checkout/blob/main/CHANGELOG.md#v301

github/workflows: Upgrade to checkout action v3

---

README.md
mlc_config.json

Simply let GitHub determine the default branch.

README: Remove the explicit default branch names from status badge URLs

---

analyzer/src/funTest/assets/projects/synthetic/dotnet-direct-dependencies-only-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output-with-nuspec.yml
analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/nuget-direct-dependencies-only-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml
utils/spdx/src/main/resources/declared-license-mapping.yml

The mappings were determined by downloading the linked HTML pages and
scanning them with ScanCode 30.1.0.

declared-license-mapping: Fix mappings for .NET licenses

---

.github/workflows/static-analysis.yml

This reverts commit 7b20661 as the upstream issue has been fixed, see
[1].
[1]: https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/132#issuecomment-1103553643

Revert "github/workflows: Use ORT's fork of github-action-markdown-link-check"

---

cli/src/main/kotlin/commands/AnalyzerCommand.kt

Combine curations from the ORT configuration repository [1] with local
curations by default, where the latter override the former if in
conflict.
[1]: https://github.com/oss-review-toolkit/ort-config

AnalyzerCommand: Use the ORT curation provider together with local providers

---

model/src/main/kotlin/config/ScannerConfiguration.kt
scanner/src/funTest/assets/dummy-expected-output-for-analyzer-result.yml

`NOTICE` files are the Apache Foundation's convention "to collect
copyright notices and required attributions" [1] for which Maven has
built-in support [2]. As ORT collects this information on its own by
scanning the project's and dependencies' source code, scanning the
`NOTICE` file is deceptive as it is likely to contain information that
belongs to the dependencies, not to the project itself.
[1]: https://www.apache.org/legal/src-headers.html
[2]: https://maven.apache.org/apache-resource-bundles/

ScannerConfiguration: Exclude `META-INF/NOTICE` files by default

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
analyzer/src/test/kotlin/managers/utils/MavenSupportTest.kt

MavenSupport: Fixup VCS paths that contain the project name as a prefix

---

scanner/src/main/kotlin/experimental/NestedProvenanceScanResult.kt

If the merged scan results come from a package based storage, they can
contain the identical issues, because it is not possible to associate
scanner issues with files when splitting the package based result by
provenance. Therefore deduplicate issues when merging them for the ORT
result file, otherwise it can happen that the identical issue appears
multiple times in the ORT result and therefore also in the reports.

NestedProvenanceScanResult: Deduplicate issues when merging results

---

analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt

NuGetSupport: Refactor `parseLicenses()` for readability

---

gradle.properties

Repeat the default JVM arguments [1] and add `-Dfile.encoding=UTF-8`.
Fixes #5278.
[1]: https://docs.gradle.org/current/userguide/build_environment.html#sec:configuring_jvm_memory

Gradle: Enforce the JVM running Gradle to use UTF-8 encoding for reading files

---

utils/core/src/main/kotlin/Utils.kt
utils/core/src/test/kotlin/UtilsTest.kt

Utils: Allow `filterVersionNames()` to strip some prefix and suffix strings

---

gradle.properties

See [1].
[1]: https://github.com/Kotlin/dokka/releases/tag/v1.6.21

Gradle: Upgrade the Dokka plugin to version 1.6.21

---

analyzer/src/main/kotlin/managers/utils/PubCacheReader.kt
analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt

The `packageInfo` for Pub's Git dependencies contain different
information as for hosted dependencies. Fix the path construction for
dependency resolution from Pub's cache.
Resolves #5196.

PubCacheReader: Fix handling of Git dependencies

---

README.md

The related issue has been fixed in #4541.

README: Remove a link to a closed Conan issue

---

model/src/main/kotlin/config/ScannerConfiguration.kt
scanner/src/funTest/assets/dummy-expected-output-for-analyzer-result.yml

Sometimes these text files come with an explicit extension, so ignore
these, too.

ScannerConfiguration: Also ignore `{DEPENDENCIES,NOTICE}.txt` files

---

README.md

Make it easier to find ORT's contribution guidance and clearer
what is the fastest way for users to get answers to their questions.

README: Add section pointing to CONTRIBUTING.md and Slack

---

advisor/src/test/kotlin/advisors/OssIndexTest.kt
clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt

Avoid fully qualified matcher names in tests for readability

---

analyzer/src/main/kotlin/Analyzer.kt

Improve unmanaged file checks

---

utils/spdx/src/main/resources/simple-license-mapping.yml

declared-license-mapping: Map "LGPLv3+" to `LGPL-3.0-or-later`

---

downloader/src/main/kotlin/VcsHost.kt
downloader/src/test/kotlin/VcsHostTest.kt

This is a fixup for 99a1ffc93e954343c0fc09a6e27085cc18474df9.

VcsHost: Fix permalinks to Azure DevOps

---

downloader/src/main/kotlin/VcsHost.kt
downloader/src/test/kotlin/VcsHostTest.kt

When selecting line 1-10 in Azure DevOps the generated link actually
points to line 1-11. Adapt this behavior in the VcsHost implementation.

VcsHost: Fix end line for Azure DevOps permalink

---

analyzer/src/main/kotlin/managers/Pip.kt

Pip: Add a few sanity checks when parsing license information

---

analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/yarn-workspaces-expected-output.yml
model/src/main/kotlin/Identifier.kt
model/src/test/kotlin/IdentifierTest.kt

This way e.g. version "5.11.0" will come after "5.6.0" instead of now
before it.

Identifier: Sort versions numerically, if possible

---

cli/src/main/kotlin/commands/EvaluatorCommand.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
cli/src/main/kotlin/utils/PackageConfigurationOption.kt
helper-cli/src/main/kotlin/commands/GetPackageLicensesCommand.kt
helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
helper-cli/src/main/kotlin/common/PackageConfigurationOption.kt
helper-cli/src/main/kotlin/common/Utils.kt
model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt
model/src/main/kotlin/utils/CompositePackageConfigurationProvider.kt
model/src/main/kotlin/utils/OrtResultExtensions.kt
model/src/main/kotlin/utils/PackageConfigurationProvider.kt
model/src/main/kotlin/utils/SimplePackageConfigurationProvider.kt
model/src/test/kotlin/licenses/DefaultLicenseInfoProviderTest.kt
model/src/test/kotlin/licenses/LicenseViewTest.kt
reporter/src/main/kotlin/ReporterInput.kt
reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModelMapper.kt

Several refactorings to prepare the implementation of a `PackageConfigurationProvider` for the ort-config repository, see the commit messages for details.

Prepare ort-config PackageConfigurationProvider

---

analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/Pipenv.kt
analyzer/src/main/kotlin/managers/Yarn.kt
scanner/src/main/kotlin/scanners/Askalono.kt
scanner/src/main/kotlin/scanners/Licensee.kt
utils/common/src/main/kotlin/ProcessCapture.kt

The fact that `ProcessCapture` uses temporary files to work around the
64k buffering limit is an implementation detail that should not be
exposed to ease switching to another process builder alternative
eventually. Also see [1].
[1]: https://github.com/oss-review-toolkit/ort/issues/4668

ProcessCapture: Make `{stdout,stderr}File` private

---

scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt

These licenses cannot be mapped to valid SPDX expressions, resulting in
ORT issues.

FossIdScanResults: Add u_* license mappings

---

analyzer/src/main/kotlin/managers/Pub.kt

See: https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0

Pub: Upgrade bootstrapped Flutter to version 3.0.0

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt

MavenSupport: Extend the Spring `isMetaDataOnly` logic to contract specs

---

model/src/main/kotlin/utils/DependencyGraphBuilder.kt
model/src/test/kotlin/utils/DependencyGraphBuilderTest.kt

If a dependency to a package was added to the builder which contains
another reference to this package in its dependencies, the builder
created multiple DependencyReference objects with the same index and
fragment. This caused a corrupted dependency graph which could not be
deserialized. Fix this by checking the fragment again before creating
a new DependencyReference.
Note that this issue was encountered with a real Gradle project where
the analyzer actually produced such cyclic dependencies.

DependencyGraphBuilder: Handle cyclic dependencies

---

utils/core/src/main/kotlin/OkHttpClientHelper.kt

A Resource leak was partially fixed in
https://github.com/oss-review-toolkit/ort/issues/5240.
However the Response would still not be closed if unsuccessful, and the same warnings as in #5240 would appear if so.
By also closing (as recommended by OKHttp) before throwing the exception, it will not show the warn messages.
(and the potential resource leak).
Note: It can be argued it could be solved in less imperative ways by some overall refactoring,
but for a first PR I would like it to be as simple and straightforward as possible.
Signed-off-by: Josef Andersson <josef.andersson@gmail.com>

Analyzer: Close Response Body on failure

---

.github/workflows/static-analysis.yml

See [1].
[1]: https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

github/workflows: Upgrade deprecated upload-sarif action v1 to v2

---

scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
scanner/src/test/kotlin/scanners/scancode/ScanCodeTest.kt

The version output of ScanCode 31.x adds a colon to the version
output, see [1]. Support the parsing of this new format.
[1]: https://github.com/nexB/scancode-toolkit/commit/b78b49f7d57d03938f973f0542a08417c84bb77e

ScanCode: Support version parsing for ScanCode 31.0.0b4

---

analyzer/src/main/kotlin/managers/Pip.kt

For example the license of package kiwisolver contains `-` characters
https://github.com/nucleic/kiwi/blob/main/LICENSE

Pip: Fix license detection for license containing separators

---

analyzer/src/main/kotlin/managers/Npm.kt

According to the documentation ([1] and [2]), NPM submits by default a
dependency description to the configured registry and asks for a report
of known vulnerabilities.
Since:
* ORT does not use this information (security analysis is done
separately by the Advisor)
* this auditing should be done regularly and not only at install time
this commit deactivates this option for now.
[1]: https://docs.npmjs.com/cli/v8/commands/npm-ci
[2]: https://docs.npmjs.com/cli/v8/commands/npm-audit

Npm: Disable audit submission during `npm ci` or `npm install`

---

analyzer/src/main/kotlin/managers/Pub.kt

No release notes are published for this minor update.

Pub: Upgrade bootstrapped Flutter version to 3.0.1

---

utils/common/src/main/kotlin/ArchiveUtils.kt

This is a fixup for fe53333. Resolves #5376.

ArchiveUtils: Do not follow links in `packZip()`

---

utils/common/src/main/kotlin/ArchiveUtils.kt
utils/common/src/test/kotlin/ArchiveUtilsTest.kt

The fix in 3342e50 was incomplete in that only symbolic links to files
were not followed. Extend this to symbolic links to directories.
Resolves #5376, again.

ArchiveUtils: Also do not follow symbolic links to directories

---

integrations/schemas/package-configuration-schema.json

Add a JSON Schema for package configuration for IDE validation. 
Can be tested with VSCode by adding the following in `.vscode/settings.json` of a workspace containing package configurations and copying the schema to `schemas/package-configuration-schema.json` of the workspace:
```yaml
{
"yaml.schemas": {
"./schemas/package-configuration-schema.json": [
"source-artifact.yml",
"vcs.yml"
]
},
}
```

Add JSON Schema for package configuration

---

downloader/src/main/kotlin/vcs/Git.kt

It's very likely not the init-step that fails, but the cloning, so do
not initialize submodules again when (re-)trying to clone them without
limiting the depth. This should avoid Git warnings like
warning: 21f92cc4870a08c9ff1a4f7d7e03b5539fca51fb:.gitmodules,
multiple configurations found for 'submodule.sdk.path'. Skipping
second one!

Git: Do not initialize submodules again in the fallback

---

integrations/schemas/curations-schema.json
model/src/test/assets/package-configuration.yml
model/src/test/kotlin/JsonSchemaTest.kt

Moving this from https://github.com/oss-review-toolkit/ort/pull/5395 to a separate PR, as the test won't pass without this being merged first.
This can be tested with this setting in VSCode:
```json
"yaml.schemas": {
"file:///Users/marcel/work/oss/ort/integrations/schemas/curations-schema.json": "*.yml"
}
```

Schemas: Add JSON schema for curations

---

scanner/src/main/kotlin/scanners/fossid/FossId.kt

The authenticator is needed to add credentials to the Git URL passed
to FossID. Recent changes in the scanner infrastructure have obviously
caused that the ORT authenticator has not always been installed when a
new FossID scan is created. The scan then fails due to missing
credentials.

FossId: Explicitly install the ORT authenticator

---

analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt

It is a common mistake by SPDX document authors to omit the VCS-specific
prefix in download locations that refer to VCS locations instead of
artifacts, so warn about this at least in the Git case.
[1]: https://spdx.github.io/spdx-spec/package-information/#77-package-download-location-field

SpdxDocumentFile: Warn about artifact download locations that look like Git

---

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output-windows.yml
analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pip-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pipenv-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pipenv-python3-expected-output.yml
analyzer/src/funTest/kotlin/managers/PipFunTest.kt
analyzer/src/main/kotlin/managers/Pip.kt

Add more fields that could contain a link to the source code repository
as fallback URLs for Python packages.
Fixes #509.

Pip: Add more VCS fallback URLs for packages

---

integrations/schemas/repository-configuration-schema.json
model/src/test/kotlin/JsonSchemaTest.kt

To test this, you can use this configuration in VSCode `settings.json`:
For the .ort.yml:
```json
"yaml.schemas": {
"file:///Users/marcel/work/oss/ort/integrations/schemas/repository-configuration-schema.json": "*.ort.yml"
}
```

JSON Schemas: Use references in repository configuration schema

---

integrations/schemas/resolutions-schema.json
model/src/test/kotlin/JsonSchemaTest.kt

Taken from the repository configuration schema. The resolutions schema
in the .ort.yml schema will be replaced with a reference in a follow-up
commit.

Schemas: Add JSON schema for resolutions

---

analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml

The "multipart-post" project has been transferred from the "nicksieger"
user to the "socketry" organization on GitHub.

BundlerFunTest: Update expected test results

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
downloader/src/main/kotlin/vcs/Subversion.kt
utils/ort/src/main/kotlin/OkHttpClientHelper.kt
utils/ort/src/main/kotlin/Utils.kt
utils/ort/src/test/kotlin/UtilsTest.kt

Now that there is the more convenient `requestPasswordAuthentication()`
helper function, inline `installAuthenticatorAndProxySelector()` which
anyway had arbitrary semantics in returning just the proxy selector.

Inline the `installAuthenticatorAndProxySelector()` helper function

---

Dockerfile

Dockerfile: Avoid copying the distribution TAR by mounting it instead

---

downloader/src/main/kotlin/Downloader.kt
scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
scanner/src/main/kotlin/experimental/ScanController.kt

When scanning with package scanners, consolidate packages by their provenance, to scan the same provenance only once. See the commit messages for details.

ExperimentalScanner: Consolidate packages for package scanners

---

.github/workflows/build-and-test.yml

This helps to understand where which coverage information comes from.

github/workflows: Set codecov flags according to job names

---

.mailmap

Add his new e-mail address at EPAM and also cover all his addresses
present in the Git log.

.mailmap: Add Thomas' e-mail addresses

---

model/src/main/kotlin/LicenseFinding.kt
model/src/main/kotlin/config/ScannerConfiguration.kt
model/src/main/resources/reference.conf
model/src/test/kotlin/LicenseFindingTest.kt
scanner/src/funTest/assets/dummy-expected-output-for-analyzer-result.yml
scanner/src/main/kotlin/scanners/Askalono.kt
scanner/src/main/kotlin/scanners/BoyterLc.kt
scanner/src/main/kotlin/scanners/Licensee.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
scanner/src/main/kotlin/scanners/scanoss/ScanOss.kt
scanner/src/main/kotlin/scanners/scanoss/ScanOssResultParser.kt
scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt
scanner/src/test/kotlin/scanners/scanoss/ScanOssResultParserTest.kt

Scanners might return invalid SPDX license expressions. This causes
issues when reading the scanner results. Provide an option that users
can map detected licenses in the scanner configuration.
This functionality is not limited to invalid SPDX expressions. The user
can also map unwanted licenses, like `LicenseRef-scancode-unknown` to
`NOASSERTION`.
The mapping is being done when creating the LicenseFinding after
receiving the results from the scanners. This has the advantage that
internally, ORT handles only valid SPDX expressions. The disadvantage
of that approach is, that mapped licenses are stored in the
ScanResultStorage which might become invalid when the detected license
mapping in the scanner configuration is changed.
Resolves https://github.com/oss-review-toolkit/ort/issues/5345. …

ScannerConfiguration: Add option to provide detected license mappings

---

analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
analyzer/src/main/kotlin/managers/utils/SpdxDocumentCache.kt
analyzer/src/main/kotlin/managers/utils/SpdxResolvedDocument.kt
analyzer/src/test/kotlin/managers/utils/SpdxDocumentCacheTest.kt
analyzer/src/test/kotlin/managers/utils/SpdxResolvedDocumentTest.kt

Do not crash in `mapDefinitionFiles()` if an SPDX document cannot be
parsed, and while at it also improve the error reporting for unparseable
SPDX documents.

SpdxDocumentFile: Improve error handling

---

model/src/main/resources/reference.conf
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/fossid/FossIdConfig.kt
scanner/src/test/kotlin/scanners/fossid/FossIdConfigTest.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt

Remove the unused package filter options and do some minor cleanup. See the commit messages for details.

FossId: Remove package filter options

---

cli/src/main/kotlin/commands/ScannerCommand.kt
model/src/main/kotlin/config/ScanStorageConfiguration.kt
model/src/main/resources/reference.conf
scanner/src/funTest/kotlin/storages/PostgresStorageFunTest.kt
scanner/src/main/kotlin/PathScanner.kt
scanner/src/main/kotlin/ScanResultsStorage.kt
scanner/src/main/kotlin/storages/PostgresStorage.kt

The database pool size is implicitly configured by the number of storage
threads. Before, this value was hard-coded to 5 threads. As this might
not fit the user's database setup, make the value
configurable.

PostresStorage: Make the number of storage threads configurable

---

advisor/src/main/kotlin/AdviceProviderFactory.kt
model/src/main/kotlin/config/AdvisorConfiguration.kt
model/src/main/kotlin/config/AnalyzerConfiguration.kt
model/src/main/kotlin/config/OrtConfiguration.kt
model/src/main/kotlin/config/ReporterConfiguration.kt
model/src/main/kotlin/config/ScannerConfiguration.kt
scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/experimental/ExperimentalScanner.kt
scanner/src/main/kotlin/experimental/ScannerWrapper.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/test/kotlin/PathScannerTest.kt
scanner/src/test/kotlin/experimental/ExperimentalScannerTest.kt

Replace the different typealiases for `Map<String, String>` used in
several configuration classes with one global typealias for options.

model: Add a global typealias for options

---

.codecov.yml

For details see [1]. This should help getting coverage right if not all
tests are run.
[1]: https://docs.codecov.com/docs/carryforward-flags

Codecov: Enable carry foward of partial coverage information

---

scanner/src/main/kotlin/experimental/NestedProvenanceScanResult.kt

This fixes a bug where `additionalData` were not in the OrtResults when
using the experimental scanners, despite being set by a scanner.

NestedProvenanceScanResult: Pass `additionalData` to the merged results

---

model/src/main/kotlin/LicenseFinding.kt
model/src/test/kotlin/LicenseFindingTest.kt

The functionality to map detected licenses can be used to map non-SPDX
licenses returned from scanners. However, it is also intended to be used
to map unwanted but valid licenses. Therefore, apply the mapping also to
valid SPDX expressions.
This is a fixup for https://github.com/oss-review-toolkit/ort/commit/0b8377dafdcae2cf48958876ff848c8c1d1b9d07.

LicenseFinding: Apply detected license mapping to valid SPDX expressions

---

clients/fossid-webapp/src/main/kotlin/Extensions.kt

When the report cannot be generated, log the headers of the response
received from the FossID server for better error logging.

fossid-webapp: Improve FossID reporter error logging

---

helper-cli/src/main/kotlin/commands/scanstorage/DeleteCommand.kt

Change the SELECT statement to retrieve stored scan results with a
specific license to use the configured schema name.
This is a fixup for 5cae85a7dbab35a20de26134f2cb0e13055a447a.

DeleteCommand: Remove hard coded database schema name

---

analyzer/src/funTest/assets/projects/synthetic/gomod-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/gomod-subpkg-expected-output.yml
analyzer/src/main/kotlin/managers/GoMod.kt
helper-cli/src/main/kotlin/commands/repoconfig/GenerateScopeExcludesCommand.kt

Eliminate over-reporting of dependencies I discovered while investigating #5021.

GoMod: Drop the "all" scope, simplify and clean-up a bit

---

cli/src/funTest/kotlin/OrtMainFunTest.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
model/src/main/kotlin/config/AnalyzerConfiguration.kt
model/src/main/resources/reference.conf

Allow to enable and disable specific package managers in the analyzer
configuration. This can still be overridden by the respective command
line options of the analyzer command.
The refactoring in this change is also a preparation for adding more
package manager specific configuration options later on.

model: Allow to enable and disable package managers in the configuration

---

model/src/main/kotlin/LicenseFinding.kt
model/src/test/kotlin/LicenseFindingTest.kt

The regex used before, using a negative lookbehind to determine the word
boundaries of a license, did not work in some cases, when special
characters are used in the license expression.
Replace this regex with another one that checks either for whitespaces
before and after the license expression or for the beginning or the end
of the string, respectively.

LicenseFinding: Fix regex to replace the detected license finding

---

analyzer/src/main/kotlin/Analyzer.kt

Ensure that the analyzer result is not built before all package managers
are finished.

Analyzer: Prevent a race condition

---

Dockerfile
analyzer/src/funTest/assets/projects/synthetic/poetry-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/poetry/poetry.lock
analyzer/src/funTest/assets/projects/synthetic/poetry/pyproject.toml
analyzer/src/funTest/kotlin/managers/PoetryFunTest.kt
analyzer/src/main/kotlin/managers/Poetry.kt
analyzer/src/main/resources/META-INF/services/org.ossreviewtoolkit.analyzer.PackageManagerFactory
analyzer/src/test/kotlin/PackageManagerTest.kt

Added a package manager class Poetry to handle Python's projects that use Poetry and functional tests 
Fixes #1699

Analyzer: Add support for Poetry package manager

---

README.md
analyzer/src/funTest/assets/projects/synthetic/gomod/go.mod
analyzer/src/main/kotlin/managers/GoMod.kt

Extend the logic for parsing the output for `go list -m all` to properly
handle lines for replaced modules [1]. Adjust the test asset to cover a
replacement. Also remove the mention of this limitation from the
documentation as replacements are now properly handled.
[1] https://go.dev/ref/mod#go-mod-file-replace
Fixes #4445.

GoMod: Handle the replace directive

---

analyzer/src/funTest/assets/projects/synthetic/gomod-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/gomod-subpkg-expected-output.yml
analyzer/src/main/kotlin/managers/GoMod.kt

These are improvements on top of recent work done for fixing #5021.

GoMod: Distinguish main module from development-only dependencies

---

clients/fossid-webapp/src/main/kotlin/EntityResponseBody.kt
clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
clients/fossid-webapp/src/test/assets/return-type/mappings/apiphp-delete_scan.json
clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt

Please refer to individual commit messages for details.
This PR fixes the following exception:
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.Integer` from Array value (token `JsonToken.START_ARRAY`)
at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 49] (through reference chain: org.ossreviewtoolkit.clients.fossid.EntityResponseBody["data"]) 
```

fossid-webapp: Fix deserialization error on `deleteScan` response

---

clients/fossid-webapp/src/main/kotlin/EntityResponseBody.kt

Commit https://github.com/bosch-io/oss-review-toolkit/commit/62d6ddf875784bcf7ad3b085c13601a7a52c6b63 wrongly changed the type of this property due to a
misinterpretation of a FossID changelog: Its type is in fact an array in
most of the responses, and an object in the response of `deleteScan` in
case the scan does not exist.
Ignore this parameter, as ORT does not use this property at all.

fossid-webapp: Remove property `messageParameters`

---

analyzer/src/main/kotlin/managers/Conan.kt
analyzer/src/main/kotlin/managers/GoMod.kt

`run()` already calls `requireSuccess()` internally.

Strip superfluous `requireSuccess()` calls

---

analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/managers/DotNet.kt
analyzer/src/main/kotlin/managers/NuGet.kt
model/src/main/kotlin/config/AnalyzerConfiguration.kt
model/src/test/kotlin/config/AnalyzerConfigurationTest.kt
model/src/test/kotlin/config/OrtConfigurationTest.kt

Make sure that package manager names used within `AnalyzerConfiguration` are case-insensitive. See the commit messages for details.

AnalyzerConfiguration: Make the package managers case-insensitive

---

helper-cli/src/main/kotlin/commands/repoconfig/GenerateScopeExcludesCommand.kt

The 'vendor' scope contains all modules needed for building and testing
the main module while the 'main' scope contains only the main module
dependencies. So, only 'main' should not be excluded.

GenerateScopeExcludesCommand: Add the 'vendor' scope for GoMod

---

model/src/main/kotlin/DependencyGraphNavigator.kt
model/src/main/kotlin/DependencyNode.kt
model/src/test/kotlin/DependencyGraphNavigatorTest.kt
reporter/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
reporter/src/funTest/assets/evaluated-model-reporter-test-input.yml
reporter/src/funTest/kotlin/reporters/evaluatedmodel/EvaluatedModelReporterFunTest.kt
reporter/src/main/kotlin/reporters/WebAppReporter.kt
reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModel.kt
reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModelMapper.kt
reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModelReporter.kt

This PR addresses a problem with out-of-memory errors we face during report generation for large projects: For complex dependency graphs, the generation of the evaluated model for the WebApp reporter consumes a huge amount of memory, since the condensed graph gets unwrapped again.
The reporters dealing with the evaluated model now accept a new _deduplicateDependencyTree_ parameter. When set to *true* (the default is *false*) the dependency tree does no longer contain duplicate subtrees; when a duplicate subtree occurs, only the root node is inserted. This is similar to the way dependency trees are displayed by Gradle.

Evaluated model: Strip dependency trees

---

build.gradle.kts

This is a fixup for ab6ae6dd to enable at least the JSON report again as
the `version-catalog-update` plugin depends on it, see [1].
[1]: https://github.com/littlerobots/version-catalog-update-plugin/issues/59#issuecomment-1167333757

Gradle: Enable the JSON report for the `versions` plugin again

---

.github/workflows/build-and-test.yml
analyzer/src/funTest/kotlin/managers/PubFunTest.kt
utils/test/src/main/kotlin/TestTags.kt

The only Analyzer funTest that was not running in Docker so far was the
`PubFunTest`, but as of https://github.com/oss-review-toolkit/ort/commit/16f029416a79e9a64e7f8a2ded1f425b25daccd9 this works.

Remove the `NoDockerTag` for running Analyzer funTests outside of Docker

---

analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/PackageManagerDependencyResult.kt
analyzer/src/main/kotlin/managers/Pub.kt

This is the first step in generalizing the way that Pub uses to get Gradle and Cocoapods dependencies so that it can also be used for other package managers. To keep the diff small I will do it in several smaller PRs.

Analyzer: Automatically determine package manager order

---

clients/fossid-webapp/src/main/kotlin/model/Scan.kt

The `isBlindAudit` property of a FossID `Scan` is either null, "0" or "1".
Therefore, it needs to be specially handled for deserialization.
This commit fixes an `InvalidFormatException` from Jackson that occurs
when deserializing archived scans.

fossid-webapp: Convert `isBlindAudit` from numeric String

---

cli/src/main/kotlin/commands/AnalyzerCommand.kt

Logging using `log` is only allowed on ORT classes.

AnalyzerCommand: Use the logger from the parent class

---

model/src/main/kotlin/PackageCuration.kt
model/src/test/kotlin/PackageCurationTest.kt

Using `isSatisfiedBy(String)` defaults to `SemverType.STRICT`, which
doesn't allow versions without a patch. Specify the `SemverType`
explicitly to avoid this issue.
While at it, also print a warning if a version or a version range cannot
be parsed.

PackageCuration: Fix version range check for versions without a patch

---

docs/config-file-curations-yml.md

Make this option more visible, as it can be used to fix other scanner
issues.

config-file-curations-yml: Document curations that cause the scanner to skip packages

---

analyzer/src/main/kotlin/managers/Pip.kt

The PyPI JSON API was changed to only include the URLs for the current
version on the version specific JSON pages [1].
[1]: https://github.com/pypi/warehouse/pull/11775

Pip: Fix getting the binary and source artifacts

---

clients/osv/build.gradle.kts
clients/osv/src/funTest/assets/vulnerabilities-by-commit-expected-result.json
clients/osv/src/funTest/assets/vulnerabilities-by-name-and-version-expected-result.json
clients/osv/src/funTest/assets/vulnerability-by-id-expected-result.json
clients/osv/src/funTest/kotlin/OsvServiceFunTest.kt
clients/osv/src/main/kotlin/OsvApiClient.kt
clients/osv/src/main/kotlin/OsvService.kt
clients/osv/src/test/kotlin/ModelTest.kt

Add a retrofit based REST API client and a wrapper for simplicity and
information hiding. The implementation is based on [1], even though it
has some inconsistencies with the real behavior, see [2].
[1] https://osv.dev/docs/
[2] https://github.com/google/osv.dev/issues/466
This is an enabler for #3599.

clients/osv: Implement querying the OSV API

---

analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt

When requesting curations for a certain coordinate the ClearlyDefined
API [1] sometimes also return curations for other coordinates. For
example, the response for "maven/mavencentral/org.ow2.asm/asm/7.0" also
contains curations for other versions of the same package, but also for
other packages that start with "asm", like "asm-tree". This means, that
the same curations can be contained multiple times in a response, if
multiple coordinates are sent at once.
As a result, it can happen that ORT adds the same curation multiple
times to a package. To prevent this, filter duplicate curations before
returning the result.
[1]: https://api.clearlydefined.io/api-docs/#/curations/post_curations_

ClearlyDefinedPackageCurationProvider: Filter duplicate curations

---

README.md

Even if the link is set to not expire (by date), the link will become
invalid after 100 people have used it.
Fixes #5539.

README: Update the Slack invite link

---

advisor/build.gradle.kts
advisor/src/funTest/assets/retrieve-package-findings-expected-result.json
advisor/src/main/kotlin/advisors/Osv.kt
gradle/libs.versions.toml

ORT's data model for the severity of a vulnerability is quite generic.
The wide flexibiltiy it provides makes it unclear how to best map the
obtained values from the provider to that data model.
The use of `VulnerabilityReference.severity` in [1] indicates that a
float score value is a valid option. So, change the mapping to float for
now as that is easier to understand - even though this is a lossy
transformation.
In the longer run, ORT's vulnerability data model should be improved to
support vectors in a less generic stricter typed way.
[1] https://github.com/oss-review-toolkit/ort/blob/470e2f323b516389bd96a63a81c67b74891a36f8/model/src/main/kotlin/VulnerabilityReference.kt#L58-L63
This is part of #3599.

Osv: Somewhat improve the mapping of the severity

---

clients/osv/src/main/kotlin/Model.kt

It was mandatory by accident, see [1] and also [2].
[1] https://github.com/ossf/osv-schema/blob/main/validation/schema.json
[2] https://github.com/google/osv.dev/issues/502#issuecomment-1182696991
Part of #3599.

clients/osv: Make the `ranges` property optional

---

advisor/build.gradle.kts
advisor/src/funTest/assets/retrieve-package-findings-expected-result.json
advisor/src/funTest/kotlin/OsvFunTest.kt
advisor/src/main/kotlin/advisors/Osv.kt
clients/osv/src/main/kotlin/Model.kt

Please see the individual commits.
Part of #3599.

Osv: Add a fallback for the severity

---

clients/osv/src/main/kotlin/OsvApiClient.kt

The class has been renamed to `Vulnerability` recently by [1]. As there
is also a `Vulnerability` class in `Model.kt` undo the rename to avoid
confusion.
[1] 064c5898868e590b5fc736670bebea2a8f3ff95d

OsvApiClient: Revert a rename of the `Id` class

---

utils/spdx/src/main/resources/declared-license-mapping.yml

Found in [1].
[1]: https://repo1.maven.org/maven2/com/google/re2j/re2j/1.7/re2j-1.7.pom

declared-license-mapping: Map `Go License` to `BSD-3-Clause`

---

analyzer/src/main/kotlin/managers/Pub.kt

See: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#305-july-13-2022

Pub: Upgrade bootstrapped Flutter version to 3.0.5

---

model/src/main/resources/reference.conf
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/fossid/FossIdConfig.kt
scanner/src/test/kotlin/scanners/fossid/FossIdConfigTest.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt

When there is an error during a FossID scan, the default behavior is to
delete the scan to avoid cluttering the FossID instance. While useful,
this makes error analysis of runs difficult. Therefore, this commit adds
an option to keep failed scans.

fossid-webapp: Add a property to keep failed scans

---

analyzer/src/main/kotlin/AnalyzerResultBuilder.kt
analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt

This fixes a problem introduced by 7088e06a to support references
between different package managers. The corner case that a result does
not contain any dependencies caused an exception when navigating over
the dependency graph.
Resolves #5557.
Signed-off-by: Oliver Heger <oliver.heger@bosch.io>

AnalyzerResultBuilder: Fix a problem with results without dependencies

---

analyzer/src/funTest/kotlin/managers/GoDepFunTest.kt

The tests fail on my machine because the string value assigned to
`gitHubProject` starts with "git@". On CI the tests succeed.
Strip the user from the VCS URL before mapping it to the project name,
to make that problem disappear.

GoDepFunTest: Fix-up the expected result

---

advisor/src/funTest/kotlin/OsvFunTest.kt
advisor/src/main/kotlin/advisors/Osv.kt
analyzer/src/funTest/assets/projects/synthetic/glide-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/godep-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/godeps-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/gomod-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/gomod-subpkg-expected-output.yml
analyzer/src/main/kotlin/managers/GoDep.kt
analyzer/src/main/kotlin/managers/GoMod.kt
analyzer/src/test/kotlin/managers/GoModTest.kt
model/src/main/kotlin/utils/Extensions.kt

Note: The label "breaking" has been set because any ORT configuration referring to Go packages by ID need alignment, like e.g. curations for Go packages. See also https://github.com/oss-review-toolkit/ort-config/pull/43.
Fixes #5533.

Use "Go" as value for `Identifier.type` for all Go packages

---

advisor/src/main/kotlin/advisors/Osv.kt

It is hard to track the current value of non-final `var`s, which is why
their use is discouraged. So use `let` instead.

Osv: Avoid using `var` by using `let`

---

advisor/src/funTest/kotlin/OsvFunTest.kt
analyzer/src/funTest/assets/projects/synthetic/glide-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/godep-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/godeps-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/gomod-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/gomod-subpkg-expected-output.yml
analyzer/src/main/kotlin/managers/GoDep.kt
analyzer/src/main/kotlin/managers/GoMod.kt
analyzer/src/main/kotlin/managers/utils/GoSupport.kt
analyzer/src/test/kotlin/managers/GoModTest.kt

Map the Go package / module version strings to semver compatible version strings. See individual commits.
Note: A reason for doing so, besides consistency, is to allow for passing the version strings as-is to any third-party advisor backend API. OSV can handle the `v` prefixes, but maybe not all backends can.
Fixes #5532.
_edit: The change is breaking, because any ORT configuration which uses version strings for Go packages need to be adjusted._

GoMod/GoDep: Normalize package versions

---

advisor/src/main/kotlin/advisors/Osv.kt

The `v` suffix is now dropped by the package managers `GoMod` and
`GoDep`, so the code became redundant.

Osv: Drop some left over code

---

.dockerignore
README.md

This is a fixup for 470e2f3. Instead of hard-coding the updated link
also here, just refer to the link from the badge instead, so going
forward only a single link has to be maintained.

README: Update a second reference to our Slack workspace

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt

A ProjectBuildingException obviously does not always contain a
defined pomFile. This causes a NullPointerException in the log
output.

MavenSupport: Fix a potential NPE in a log statement

---

downloader/src/main/kotlin/VcsHost.kt
downloader/src/test/kotlin/VcsHostTest.kt

Azure DevOps supports so-called artifact feeds [1]. URLs pointing to
such feeds are no VCS URLs and thus must not be modified. So, add an
isApplicable() implementation for AZURE_DEVOPS to ignore those URLs.
[1] https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/feeds?view=azure-devops

VcsHost: Add special handling for Azure DevOps packages URLs

---

cli/build.gradle.kts
gradle/libs.versions.toml

Graal updates

---

evaluator/src/main/kotlin/RuleSet.kt
evaluator/src/test/kotlin/DependencyRuleTest.kt
evaluator/src/test/kotlin/PackageRuleTest.kt
evaluator/src/test/kotlin/RuleTest.kt

Currently, instances of `RuleSet` get constructed in two ways:
1. Tests call the constructor directly.
2. `rules.kts` calls the functions `ruleSet()` which in turn creates the
instance.
Both, the constructor as well as the mentioned function, have
(redundant) default parameter values. Change the construction in tests
to also utilize `ruleSet()` and eliminate the now unnecessary default
values for the constructor parameters.
Context of #5621.

RuleSet: Eliminate redundant default values for constructor paramaters

---

evaluator/src/main/kotlin/OrtResultRule.kt
evaluator/src/main/kotlin/RuleSet.kt

Previously, the `OrtResult` instance was passed twice, via the
constructor parameters `ruleSet.ortResult` and `ortResult`. So, remove
the parameter `ortResult` to eliminate the redundancy, but keep it as a
property for convenience and to not break any implementations, e.g.
`rules.kts`.
Context: #5621.

OrtResultRule: Eliminate a redundant constructor parameter

---

analyzer/src/main/kotlin/managers/GoMod.kt

The previous algorithm exhibits the following issues when run on graphs
with cycles, in particular when the amount of edges is large:
1. Cycles of length 1 lead to infinite recursion.
2. The algorithm is inefficient in terms of execution time and memory
allocation, as it creates a copy of the
`predecessorNodes` set per recursion.
3. When run against [1] the execution of `toPackageReferenceForest()`
didn't finish within 15 minutes, causing high CPU load and memory
consumption.
If GoMod used the dependency graph format already, the solution would be
as simple as calling `DependencyGraphBuilder.breakCycles()`. Fix the
problem by copying the code of `DependencyGraphBuilder.breakCycles()` as
a temporary quick fix. This saves effort, because refactoring GoMod to
use the dependency graph is …

GoMod: Fix the algorithm for handling cycles

---

examples/evaluator-rules/src/main/resources/example.rules.kts

Extract each policy rule into a separate top level function. This reduces the level of nesting and increases the abstraction level of the rule set creation code. Now that code provides a nice overview over all policy rules. While at it, the naming of rules has been made a tad more consistent.
Changes are in context of #5621 as preparation for adding further rules.

Example-rules: Refactor for readability

---

Dockerfile
README.md
analyzer/src/funTest/assets/projects/synthetic/pnpm-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pnpm-workspaces-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pnpm-workspaces/package.json
analyzer/src/funTest/assets/projects/synthetic/pnpm-workspaces/pnpm-lock.yaml
analyzer/src/funTest/assets/projects/synthetic/pnpm-workspaces/pnpm-workspace.yaml
analyzer/src/funTest/assets/projects/synthetic/pnpm-workspaces/src/app/package.json
analyzer/src/funTest/assets/projects/synthetic/pnpm-workspaces/src/packages/package-a/package.json
analyzer/src/funTest/assets/projects/synthetic/pnpm-workspaces/src/packages/package-b/package.json
analyzer/src/funTest/assets/projects/synthetic/pnpm/package.json
analyzer/src/funTest/assets/projects/synthetic/pnpm/pnpm-lock.yaml
analyzer/src/funTest/kotlin/managers/PnpmFunTest.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/Pnpm.kt
analyzer/src/main/kotlin/managers/utils/NodeSupport.kt
analyzer/src/main/kotlin/managers/utils/NpmDependencyHandler.kt
analyzer/src/main/resources/META-INF/services/org.ossreviewtoolkit.analyzer.PackageManagerFactory
analyzer/src/test/kotlin/PackageManagerTest.kt

This PR adds support for [PNPM](https://pnpm.io/).
The implementation is loosely based on #2128.
In contrast to #5594 it does not use `pnpm list` to avoid an out of memory issue for large projects, see: https://github.com/pnpm/pnpm/issues/3518.
This implementation relies on the `pnpm install` `--shamefully-hoist` option to create a similar `node_modules` directory structure as NPM and Yarn create it, and then reuses most of NPM's analyzer implementation.

Add Analyzer for PNPM

---

evaluator/src/main/kotlin/OrtResultRule.kt

For consistency with the other rule classes, add an `issue` function to
`OrtResultRule`.
Fixes #5573.

OrtResultRule: Add issue function

---

Dockerfile
gradle/wrapper/gradle-wrapper.properties

Switch to Gradle's "bin" distribution to reduce the download size

---

analyzer/src/funTest/assets/projects/synthetic/pnpm-workspaces-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pnpm-workspaces/src/non-workspace/package-c/package.json
analyzer/src/funTest/assets/projects/synthetic/pnpm-workspaces/src/non-workspace/package-c/pnpm-lock.yaml
analyzer/src/funTest/assets/projects/synthetic/pnpm-workspaces/src/non-workspace/package-c/pnpm-workspace.yaml
analyzer/src/funTest/kotlin/managers/PnpmFunTest.kt
analyzer/src/main/kotlin/managers/utils/NodeSupport.kt

Empty `pnpm-workspace.yaml` files can be used to specify regular
projects within a PNPM workspace setup. Handle this case when searching
for workspace modules.

NodeSupport: Handle empty `pnpm-workspace.yaml` files

---

analyzer/src/main/kotlin/managers/Conan.kt

If "conanfile.txt" and "conanfile.py" both exist in the same repository,
calling `conan.info` defaults to using "conanfile.py". This causes
issues if the currently analyzed file is "conanfile.txt". To fix this,
pass the name of the currently analyzed definition file to "conan info".

Conan: Pass the definition file name when calling `conan info`

---

analyzer/src/main/kotlin/managers/utils/PubCacheReader.kt

PubCacheReader: Make `pubCacheRoot` private to address an inspection hint

---

utils/ort/src/main/kotlin/Logger.kt

Logger: Remove an obsolete `Suppress` annotation

---

utils/ort/src/main/kotlin/OkHttpClientHelper.kt

This reverts commit 66de71f as it did not produce the expected helpful
log output, and the leaked connection has been resolved anyway, see [1].
[1]: https://github.com/oss-review-toolkit/ort/issues/5236

Revert "OkHttpClientHelper: Set OkHttp's logging to "fine" in ORT's "debug" log level"

---

.reuse/dep5
NOTICE

The copyright list for the NOTICE file was compiled with a combination of plain text search and manually from the [dep5](https://github.com/oss-review-toolkit/ort/blob/main/.reuse/dep5) file.
Command used for [ripgrep](https://github.com/BurntSushi/ripgrep):
```
rg --hidden --no-filename --no-line-number --iglob \!utils/spdx/src/main/resources/licenses/ 'Copyright \(C\)' | sort | uniq
```
I also tried to compile the list using ORT itself:
```
ort --info scan --package-types PROJECT -i ort/analyzer-result.yml -o ort/
```
This resulted in a list which is too large, and would require quite some exclusions in the `.ort.yml`.
```
❯ grep 'statement:' scan-result.yml | sort | uniq | wc -l
1746
```

Add NOTICE file

---

cli/src/main/kotlin/commands/RequirementsCommand.kt

Do not set the exit code to 2 if a tool version cannot be determined,
and the tool does not set a version requirement.

RequirementsCommand: Do not fail if no specific version is requested

---

analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm-version-urls/package-lock.json
analyzer/src/funTest/assets/projects/synthetic/npm-version-urls/package.json
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/Pnpm.kt

This allows to handle packages that were never published to the NPM
registry but only ever referenced by (short) repository URL.
Fixes #5632.

Npm: Do not fail hard if enriching incomplete data from the NPM registry fails

---

Dockerfile
analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/python-inspector-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/python-inspector/requirements.txt
analyzer/src/funTest/kotlin/managers/PipFunTest.kt
analyzer/src/main/kotlin/managers/Pip.kt

This PR replaces pipdeptree with python-inspector to resolve Python packages dependencies found in requirement files. 
python-inspector can resolve dependencies for any target Python version and OS (and not only the one running the tool).
In this integration in ORT, it replaces pipdeptree pretty much in place as python-inspector implements a similar output data structure by design to ease the integration.
Reference: https://github.com/nexB/python-inspector
Reference: https://github.com/oss-review-toolkit/ort/issues/4637
Reference: https://github.com/oss-review-toolkit/ort/issues/3671
Signed-off-by: Tushar Goel <tushar.goel.dav@gmail.com>
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

Replace pipdeptree with python-inspector #4637 #3671

---

batect
batect.cmd

See [1].
[1]: https://github.com/batect/batect/releases/tag/0.80.0

Upgrade Batect to version 0.80.0

---

.github/workflows/build-and-test.yml

The download progress bar looks broken in CI logs, so just disable it.

github/workflows: Quietly bootstrap the Batect distribution

---

helper-cli/src/main/kotlin/commands/packageconfig/CreateCommand.kt
helper-cli/src/main/kotlin/utils/PathExcludeGenerator.kt

Add a simple heuristic which generates path excludes (which likely
apply). The heuristic for now only maps directory names to path excludes
and will be extended in upcoming changes.

CreateCommand: Allow for generating path excludes

---

.ort.yml
docs/config-file-ort-yml.md
docs/config-file-package-configuration-yml.md
examples/curations.ort.yml
helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
model/src/main/kotlin/config/PathExclude.kt
model/src/main/kotlin/utils/FindingCurationMatcher.kt
model/src/test/assets/package-configuration.yml
model/src/test/kotlin/config/ExcludesTest.kt
model/src/test/kotlin/config/PathExcludeTest.kt
model/src/test/kotlin/config/RepositoryConfigurationTest.kt
reporter/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
reporter/src/funTest/assets/static-html-reporter-test-expected-output.html
reporter/src/funTest/assets/static-html-reporter-test-input.yml

The changes migrate all externally facing glob expressions, e.g. for
- path excludes
- license finding curations 
- parameter for the `ListLicensesCommand` of the `helper-cli`
..., to use the `AntPathMatcher` which makes the asterisk match also zero path segments, which previously hasn't been working. 
For example, `**/file.ext` now matches `file.ext`. Further on, `**` now only matches path segments / directories, but not parts of the filename anymore. So for example, from now on `**.java` doesn't work anymore and `**/*.java` should be used instead.
Fixes #4357.

Path matching improvements

---

model/src/main/kotlin/utils/OrtResultExtensions.kt

The last use of `collectConcludedLicenses` and `collectDeclaredLicenses`
has been removed in 6146b42.

OrtResultExtensions: Remove unused functions

---

scanner/src/main/kotlin/Scanner.kt

`OrtResult.getPackages()` only returns packages from an analyzer result,
and as of https://github.com/oss-review-toolkit/ort/commit/01c598a04c5745dc7408f6f84b619bc62d13592e package ids cannot clash with project ids, so there is
no need to filter out projects here.

Scanner: Remove a superfluous package filter

---

model/src/main/kotlin/ScanResult.kt

This solves a bug where the [FossIdReporter] could not generate the
reports because the additional data was missing.

ScanResult: Preserve additional data when filtering scan results

---

batect
batect.cmd

See [1].
[1]: https://github.com/batect/batect/releases/tag/0.80.1

Upgrade Batect to version 0.80.1

---

downloader/src/main/kotlin/vcs/GitWorkingTree.kt

GitWorkingTree: Properly close the Git object after getting the remote URL

---

batect
batect.cmd

See [1].
[1]: https://github.com/batect/batect/releases/tag/0.81.0

Upgrade Batect to version 0.81.0

---

downloader/src/main/kotlin/vcs/GitWorkingTree.kt

JGit's `getWorkTree()` is annotated as `@NonNull`, so the fallback in
the null-case does not make any sense.

GitWorkingTree: Remove a superfluous null-fallback

---

batect
batect.cmd

See [1].
[1]: https://github.com/batect/batect/releases/tag/0.81.1

Upgrade Batect to version 0.81.1

---

helper-cli/src/main/kotlin/commands/packageconfig/CreateCommand.kt

Sort the generated path excludes in the same way as the `SortCommand`
sorts the entries of package configurations.

CreateCommand: Sort the generated path excludes

---

cli/src/funTest/kotlin/ExamplesFunTest.kt
model/src/main/kotlin/utils/OrtResultExtensions.kt
reporter/src/main/kotlin/reporters/freemarker/FreemarkerTemplateProcessor.kt

This is a split-out of minor probably uncontroversial changes from #5679, to reduce the size of that other PR.

Minor preparations for the implementation of file checks

---

downloader/src/main/kotlin/vcs/Subversion.kt

There should be single spaces at the begin and end for readability.

Subversion: Trivially improve / align the comments for named paramaters

---

.github/workflows/build-and-test.yml
.github/workflows/static-analysis.yml

This is a fix regarding failing build CIs (e.g. [this one](https://github.com/oss-review-toolkit/ort/runs/7860071001?check_suite_focus=true)) 
`burrunan/gradle-cache-action` has some issues caching because by default it removes some files. Related issue: https://github.com/burrunan/gradle-cache-action/issues/35
This can be easily fixed using [`gradle-build-action`](https://github.com/gradle/gradle-build-action
). It gives the boolean option to cache ([Read Docs](https://github.com/gradle/gradle-build-action#caching)), By Default, caching is enabled.
- Change of GitHub Action
- I have set `cache-disabled: false` (to be more readable & to educate people about the functionality of this)
- Change of GitHub Action (not required though, but it should be consistent to get rid of future errors)

fix: CI to use grade-build caching errors

---

analyzer/src/main/kotlin/managers/Composer.kt

Hi,
Since Composer has been updated to version 2, it is necessary to ignore `composer-runtime-api`, along with `composer-plugin-api`.
See https://getcomposer.org/doc/articles/composer-platform-dependencies.md#runtime-package-composer-runtime-api for more details.
Thanks,
Camille 
Signed-off-by: Camille Moulin <cmoulin@inno3.fr>

Analyzer: Ignore composer-runtime-api

---

analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml

ConanFunTest: Update the expected output

---

cli/src/funTest/kotlin/ExamplesFunTest.kt
evaluator/build.gradle.kts
evaluator/src/main/kotlin/OrtResultRule.kt
evaluator/src/main/kotlin/ProjectSourceRule.kt
evaluator/src/main/kotlin/RuleSet.kt
evaluator/src/main/kotlin/SourceTreeResolver.kt
evaluator/src/test/kotlin/ProjectSourceRuleTest.kt
examples/evaluator-rules/src/main/resources/example.rules.kts

Note: The project's source tree will be cloned in the evaluator only if the rules needed it / if the file checks are actually used.
This implements parts of https://github.com/oss-review-toolkit/ort/issues/5621.

Evaluator: Allow making arbitrary file checks on the project's source, take 2

---

model/src/test/kotlin/JsonSchemaTest.kt

Validate the `ort-configuration-schema.json` against the `reference.yml` file.
This test will pass once https://github.com/oss-review-toolkit/ort/pull/5757 is merged.

JsonSchemaTest: Add a test that validates the ort-configuration-schema

---

scanner/src/main/kotlin/experimental/ScanController.kt

The `issues` map was introduced with 4ba16b6, but was merged without the documentation.

ScanController: Add missing documentation for the `issues` map

---

integrations/schemas/analyzer-configuration-schema.json

Analyzer configurations can be used in the main ORT configurations file as well as in the repository configuration. Move the analyzer configurations to a separate schema to be able to reuse them.
The referencing of this extracted schema will be done in a follow-up commit.

Schemas: Create separate analyzer configuration schema 

---

clients/osv/src/funTest/kotlin/OsvServiceFunTest.kt

So far this was only done for "getVulnerabilityForId() returns the expected vulnerability for the given ID". Consistently do this in all tests to avoid breakages due changes in array order only.

OsvServiceFunTest: Be lenient about the array order in all tests

---

.github/workflows/build-and-test.yml
.github/workflows/static-analysis.yml

The cache for dependencies downloaded by Gradle from the setup-java action interferes with the gradle-build-action, see [1].
[1]: https://github.com/gradle/gradle-build-action/issues/433

github/workflows: Disable setup-java's Gradle cache

---

cli/src/funTest/kotlin/ExamplesFunTest.kt
evaluator/src/main/kotlin/ProjectSourceRule.kt
evaluator/src/test/kotlin/ProjectSourceRuleTest.kt
examples/evaluator-rules/src/main/resources/example.rules.kts

Extend the `ProjectSourceRule` to allow making further types of file checks and illustrate the use of each respective new API
with a policy rule derived from a real world use case.
Implements parts of #5621.

evaluator: Extend the API for making file checks against the project's source code

---

helper-cli/src/main/kotlin/utils/PathExcludeGenerator.kt

This PR is a preparation for extending the generation to match filenames, (in addition to just full directories).
Part of #5763.

PathExcludeGenerator: Minor preparations

---

cli/src/main/kotlin/commands/ScannerCommand.kt

So far the option to scan only projects or packages was ignored by the experimental scanner.

ScannerCommand: Respect packageTypes option in experimental scanner

---

clients/fossid-webapp/src/main/kotlin/Extensions.kt
clients/fossid-webapp/src/main/kotlin/PostRequestBody.kt
clients/fossid-webapp/src/main/kotlin/VersionedFossIdService.kt
clients/fossid-webapp/src/main/kotlin/VersionedFossIdService2021dot2.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt

The original motivation of changing something was to eliminate the redundant spread operators in all callers of `runScan()`.
When dropping the redundant spread operators the callers which provided multiple pairs as varargs became a tad hard to read.
So, this PR refactors to use the type `Map` for the options, and thereby eliminates the rundant spread operators.

Minor FossId improvements

---

scanner/src/main/kotlin/ScannerCriteria.kt

The term "object" sounds a lot like a singleton in Kotlin context, so avoid that term and reword by using e.g. the term "instance".

ScannerCriteria: Improve docs by avoiding the word "object"

---

cli/src/main/kotlin/OrtMain.kt

in https://github.com/oss-review-toolkit/ort-gitlab-ci/blob/main/scripts/set-defaults.sh#L12 the default log level is set to info.
if you set it to warn the ort cli will report an error because --warn is not allowed on the command line
To have more compability with the ort-gitlab-ci project this change will help a lot
Signed-off-by: Jürgen Wischer <33184634+unclejay80@users.noreply.github.com>

possibility to call cli with --warn option - compability with ort-gitlab-ci

---

advisor/src/funTest/kotlin/OsvFunTest.kt

The queries for the Packagist ecosistem have started working on the backend-side, see [1].
[1] https://github.com/google/osv.dev/issues/497

OsvFunTest: Ensure that queries for Composer packages work

---

cli/src/main/kotlin/OrtMain.kt
helper-cli/src/main/kotlin/HelperMain.kt

This is a follow-up to 6933ea7 with the same rationale. While at it, also sort the entries alphabetically.

(helper-)cli: Consistently allow all used log levels to be set explicitly

---

model/src/main/kotlin/AdvisorRecord.kt
model/src/test/kotlin/AdvisorRecordTest.kt

The old format has become legacy in march 2021. So drop the support for deserializing it to simplify the code. The value of such old advisor data is questionable anyway.
Also note that vulnerabilities also had a legacy format from 2021 for which the support already has been dropped.
[1] https://github.com/oss-review-toolkit/ort/commit/d297c58f8afe76fd6567ec6fda610b2461c19b1e

AdvisorRecord: Drop deserialization backwards compatibility

---

scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt

See the commit messages for details. This is preparation for removing the legacy scanner.

FossIdTest improvements

---

evaluator/src/main/kotlin/ProjectSourceRule.kt
evaluator/src/test/kotlin/ProjectSourceRuleTest.kt

Part of https://github.com/oss-review-toolkit/ort/issues/5621.

ProjectSourceRule: Add a matcher for the project's VCS type

---

utils/scripting/src/main/kotlin/ScriptRunner.kt

ScriptRunner: Add the `sourcePath` and `location` of compile errors to the log

---

advisor/src/funTest/kotlin/OsvFunTest.kt
advisor/src/main/kotlin/advisors/Osv.kt
clients/osv/src/main/kotlin/Model.kt

Adjust the mapping to enable queries for "Pub", which was missing in the initial implementation.
Note that there are currently just two entries in the database [1], so the impact is small.
[1] https://osv.dev/list

Osv: Enable queries for the 'Pub' ecosystem

---

analyzer/src/test/assets/package-curations.yml
docs/config-file-curations-yml.md
docs/getting-started.md
examples/curations.yml
integrations/schemas/curations-schema.json
model/src/main/kotlin/Hash.kt

The model for the `Hash` class has been changed in 2019.
Use the new format throughout the code base and drop handling of the legacy format to reduce technical debt.

Hash: Drop support for deserializing the legacy format

---

model/build.gradle.kts
model/src/main/kotlin/VcsInfo.kt
model/src/test/kotlin/VcsInfoTest.kt

The last change to the format has been made in June 2021, see [1]. As support for deserializing legacy ORT formats dating back to about more than a year ago has been dropped in recent changes, remove also this deserializer to reduce technical debt.
Note: The deserializer had been introduced for assigning empty strings as default values to properties with absent values [2]. As the serializer always serializes all properties, that mechanism is not needed (anymore).
[1] https://github.com/oss-review-toolkit/ort/commit/abd41579bd1e882870350dbcc7db781e22ec5c56 
[2] https://github.com/oss-review-toolkit/ort/commit/66aa368e7cbddf94e090555ba115f92e9b8ebc45
Node: I've added the `breaking change` label as it removes deserializing legacy format. However, it is not really breaking as it's been broken …

VcsInfo: Drop support for deserializing the legacy format

---

helper-cli/src/test/kotlin/PathExcludeGeneratorTest.kt

Make the terminology in test case names consistent.

PathExcludeGeneratorTest: Consistently use the term `directory` in test cases

---

build.gradle.kts

For background information see [1].
[1]: https://github.com/oss-review-toolkit/ort/issues/5818

Gradle: Force SnakeYaml to stick to version 1.31

---

model/src/main/kotlin/PackageCurationData.kt

"this" sounds like an instance of `PackageCurationData`, but what is meant is the `Package` instance the `PackageCurationData` gets applied to.

PackageCurationData: Refer to "the" instead of "this" package

---

utils/common/src/main/kotlin/Utils.kt
utils/common/src/test/kotlin/UtilsTest.kt

Part of https://github.com/oss-review-toolkit/ort/issues/5763.

Fix an NPE with `getCommonParentFile()`

---

evaluator/src/main/kotlin/DependencyRule.kt

Some rules might only need to look at the direct dependencies.

DependencyRule: Add a helper function to get the direct dependencies

---

Dockerfile

This is not necessary anymore as of 22e10db.

Dockerfile: Do not patch the Gradle distribution

---

build.gradle.kts
scripts/docker_build.sh

This prevents Git from determining the ORT version relative to arbitrary tags like the recently added "legacy-dockerfile" tag.

Require ORT versions to start with a digit

---

utils/ort/src/main/kotlin/OrtAuthenticator.kt
utils/ort/src/main/kotlin/UserInfoAuthenticator.kt
utils/ort/src/test/kotlin/UtilsTest.kt

When a URL contains credentials (in the 'userInfo' part of the URL), the Authenticator should use them and stop searching for credentials. This commit extracts the credentials from the URL and use them for password authentication.

OrtAuthenticator: Use credentials in URL when provided

---

model/src/main/kotlin/licenses/LicenseClassifications.kt

This enables using the serialization in https://github.com/oss-review-toolkit/ort-config/issues/59.

LicenseClassifications: Exclude properties from serialization

---

analyzer/src/main/kotlin/managers/Conan.kt
analyzer/src/main/kotlin/managers/Pub.kt
utils/common/src/main/kotlin/CommandLineTool.kt
utils/common/src/main/kotlin/MaskedString.kt
utils/common/src/main/kotlin/ProcessCapture.kt
utils/common/src/test/kotlin/MaskedStringTest.kt
utils/common/src/test/kotlin/ProcessCaptureTest.kt

Since Conan uses `ProcessCapture` to run `conan user` commands, the whole command line including the password is logged. This PR adds a mechanism to mask specific arguments when using `ProcessCapture`, so that sensitive information can be hidden.

Conan: Do not log passwords

---

helper-cli/src/main/kotlin/commands/packageconfig/CreateCommand.kt

Allow for generating excludes only for offending file / license findings.
Part of https://github.com/oss-review-toolkit/ort/issues/5763.

helper-cli: Add options for configuring the path exclude generation

---

scripts/import_certificates.sh

Add missing wildcard to enable copying of certificates into the proper directory for update-ca-certificates to install.
Without the wildcard the cp command explicitly looks for the prefix that is never supposed to be a concrete file.
Fixes error message `cp: cannot stat 'proxy-': No such file or directory`
Signed-off-by: Jens Erdmann <jens.erdmann@web.de>

import_certificates.sh: Fix Copying of Certificates

---

utils/spdx/src/main/kotlin/SpdxExpression.kt

SpdxExpression: Fix spelling in `getLicenseUrl()` docs

---

.ort.yml
utils/common/src/test/kotlin/FileMatcherTest.kt

The migration from `Java`'s path matcher to `AntPathMatcher` was a breaking change (unintended) for patterns which
match groups of subpatterns. Migrate existing patterns to the new notation and add a test case illustrating the current behavior.
Fixes: #5901.

Re-align path exclude patterns with the changed behavior

---

advisor/src/main/kotlin/advisors/Osv.kt
cli/src/funTest/kotlin/OrtMainFunTest.kt
clients/fossid-webapp/src/main/kotlin/model/identification/identifiedFiles/IdentifiedFile.kt
clients/fossid-webapp/src/main/kotlin/model/identification/markedAsIdentified/MarkedAsIdentifiedFile.kt
clients/osv/src/main/kotlin/OsvService.kt
model/src/main/kotlin/Project.kt
model/src/main/kotlin/config/FileStorageConfiguration.kt
model/src/test/kotlin/DependencyTreeNavigatorTest.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
model/src/test/kotlin/utils/DependencyGraphConverterTest.kt
notifier/src/test/kotlin/modules/JiraNotifierTest.kt
utils/common/src/main/kotlin/Extensions.kt
utils/spdx/src/test/kotlin/SpdxDeclaredLicenseMappingTest.kt
utils/spdx/src/test/kotlin/SpdxSimpleLicenseMappingTest.kt

More preparations for running Detekt with type resolution

---

docs/config-file-ort-yml.md

As the implementation has been changed to use `AntPathMatcher` instead of `Java`'s path matcher, align also the link to the documentation, see also https://github.com/oss-review-toolkit/ort/pull/5907.
Relates to #5901.

docs/config-file-ort-yml.md: Update a link for the glob patterns

---

model/src/main/kotlin/AdvisorRecord.kt
model/src/main/kotlin/ScanRecord.kt

Align the implementations in `AdvisorRecord` and `ScanRecord` with the (less redundant) one in `AnalyzerResult`.
Part of #5681.

model: Align the `hasIssues` implementations

---

model/src/main/kotlin/ScanResult.kt
model/src/main/kotlin/utils/Extensions.kt

These have been probably left over from the recent legacy scanner removal.

Drop some unused ScanResult related functions

---

model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/fossid/FossIdConfig.kt
scanner/src/main/kotlin/scanners/fossid/FossIdUrlProvider.kt
scanner/src/test/kotlin/scanners/fossid/FossIdConfigTest.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
scanner/src/test/kotlin/scanners/fossid/FossIdUrlProviderTest.kt

In our setup, we have cases in which FossID requires a different URL to scan a project than the repository URL used by ORT. To support such cases, this PR adds a mechanism based on regular expressions to map repository URLs to different URLs. To enable this, the FossID-specific scanner configuration can list an arbitrary number of mapping regular expressions. These are applied to the URL of the current package before it is passed to FossID.

FossID: Support URL mappings

---

scanner/src/main/kotlin/provenance/NestedProvenanceResolver.kt
scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
scanner/src/main/kotlin/utils/WorkingTreeCache.kt

Ignore the VCS path when initializing the working tree. The scanner
implementation always scans full repositories, so sparse checkout are
not required. This improves the performance if an analyzer repositories
contains many projects in different directories, because previously one
working tree for each of them would have been created during scanning.
Now only one working tree is created for this repository.
Add a check to the `PackageProvenanceResolver` to verify that the VCS
path from the package metadata exists, because the working tree would
now not throw an exception anymore if it does not exist.

WorkingTreeCache: Ignore the VCS path

---

reporter/src/funTest/assets/asciidoc-template-reporter-expected-result.adoc
reporter/src/main/resources/templates/asciidoc/disclosure_document.ftl

Fixes the issue seen in below screenshot:

Add linebreak so "==Dependencies" is correctly displayed as headline

---

cli/src/main/resources/logback.xml
helper-cli/src/main/resources/logback.xml
scanner/src/main/kotlin/scanners/fossid/FossIdUrlProvider.kt
scanner/src/test/kotlin/scanners/fossid/FossIdUrlProviderTest.kt

Add encoding to FossId credentials in URL mappings

---

scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt

Add the reasons why revision candidates could not be resolved to the exception that is thrown if no revision could be resolved. This ensures that these reasons do not only appear in the log output but also in the `OrtIssue` which will be added to the reports.

DefaultPackageProvenanceResolver: Improve error reporting

---

analyzer/build.gradle.kts
analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
analyzer/src/funTest/assets/projects/external/spdx-tools-python-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pip-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pipenv-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pipenv-python3-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/poetry-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/python-inspector-expected-output.yml
analyzer/src/funTest/kotlin/managers/PipFunTest.kt
analyzer/src/funTest/kotlin/managers/utils/PythonInspectorFunTest.kt
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/managers/DotNet.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/NuGet.kt
analyzer/src/main/kotlin/managers/Pip.kt
analyzer/src/main/kotlin/managers/Yarn2.kt
analyzer/src/main/kotlin/managers/utils/PythonInspector.kt

Get the metadata of Python packages from the python-inspector output. There are two follow-ups for this PR planned:
* Change the default values for `operatingSystem` and `pythonVersion` to use the current operating system and the installed Python version.
* Update the Dockerfile with the new reduced requirements for the Python installation.

Pip: Get package metadata from python-inspector

---

downloader/src/main/kotlin/vcs/GitWorkingTree.kt

The implementation followed the approach to create one instance of
`Repository` for each use and close it at the end of the respective
usage, see [1].
Recently, a minor refactoring was done to prevent forgetting to close
the `Repository` instance after use, see [2]. Unfortunately, `repo` was
turned into a `lazy` property, so that only one `Repository` instance
gets created in total. This yields an uncaught exception like e.g. [3],
because closed `Repository` instances must not be used.
Address the issue by fixing up [2] to create a new `Repository` instance
again for each use.
[1] https://github.com/oss-review-toolkit/ort/commit/4bac08f19d67b169171d0cd63139fc298f932112
[2] https://github.com/oss-review-toolkit/ort/commit/7dd7e61df7cb08bbd9a8a5f77cff2c20cb560d56
[3] …

GitWorkingTree: Fix an isse with `repo.use`

---

helper-cli/src/main/kotlin/utils/PathExcludeGenerator.kt
helper-cli/src/main/kotlin/utils/Utils.kt
helper-cli/src/test/kotlin/PathExcludeGeneratorTest.kt
helper-cli/src/test/kotlin/UtilsTest.kt

Make the behavior a bit less dependent on the the order of the hard-coded patterns, and hopefully return simpler patterns.

GeneratePathExcludeCommand: Add a preference for filename patterns

---

evaluator/src/test/kotlin/ProjectSourceRuleTest.kt
evaluator/src/test/kotlin/TestData.kt
model/src/main/kotlin/ScanSummary.kt
model/src/test/kotlin/licenses/TestData.kt
reporter/src/funTest/kotlin/TestData.kt
reporter/src/funTest/kotlin/reporters/spdx/SpdxDocumentReporterFunTest.kt
reporter/src/test/kotlin/reporters/OpossumReporterTest.kt
reporter/src/test/kotlin/reporters/fossid/FossIdReporterTest.kt
reporter/src/test/kotlin/reporters/freemarker/FreeMarkerTemplateProcessorTest.kt
scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
scanner/src/funTest/kotlin/storages/AbstractProvenanceBasedStorageFunTest.kt
scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt
scanner/src/funTest/kotlin/storages/ClearlyDefinedStorageFunTest.kt
scanner/src/test/kotlin/ScannerTest.kt
scanner/src/test/kotlin/provenance/NestedProvenanceScanResultTest.kt
scanner/src/test/kotlin/storages/CompositeStorageTest.kt

This eliminates repetition of default values in scan summary constructions.
It prepares for further refactoring steps.
Part of #5681.

Introduce and use `ScanSummary.EMPTY`

---

gradle/libs.versions.toml

See [1].
[1]: https://github.com/Kotlin/dokka/releases/tag/v1.7.20

Gradle: Upgrade the Dokka plugin to version 1.7.20

---

analyzer/src/funTest/assets/projects/synthetic/gradle-android-cyclic-expected-output-app.yml
analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
analyzer/src/funTest/kotlin/managers/BabelFunTest.kt
utils/ort/src/main/kotlin/Utils.kt

Note: This moves forwards scanning ORT with ORT, e.g. #5696.

analyzer: Use the HTTPS instead of the Git protocol in VCS processed 

---

analyzer/src/main/kotlin/managers/Pub.kt

The version is printed on stdout, not on stderr. This fixes the issue
that no version is detected when running `requirements.

Pub: Use stdout instead of stderr to get version

---

analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-app.yml
analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-lib.yml
analyzer/src/funTest/assets/projects/synthetic/maven-expected-output-root.yml
analyzer/src/funTest/assets/projects/synthetic/maven/pom.xml
analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
analyzer/src/test/kotlin/managers/utils/MavenSupportTest.kt

For POMs that do not set an SCM URL itself, the fixup of the SCM does
not work if the parent SCM does not set an `connection`, but only the
`url`. This results in an unwanted original SCM URL.
For instance, spring-boot-starter-parent [1] only sets the `url` and not
the `connection`. This results in an original SCM `url` like
'https://github.com/spring-projects/spring-boot/childArtifactName'.
The issue this causes is, that the `Project`'s `VcsInfo` is merged with
this original SCM's URL as `fallbackUrl`, causing the path to be set to
`childArtifactName`, which is not available in the child repository.
Fix this issue, by also taking the `url` into account when replacing the
SCM with the parent's one.
[1]: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.7. …

MavenSupport: Also take the `url` into account when fixing the SCM

---

analyzer/src/main/kotlin/managers/Pip.kt

Pip: Improve error messages for option values

---

analyzer/src/main/kotlin/managers/Gradle.kt

At debug level, log progress from the Gradle build. This is useful to determine whether a build is actually hanging or just slow.

Gradle: Add a progress listener

---

analyzer/src/main/kotlin/managers/utils/PythonInspector.kt

If the python-inspector runs into an exception only the stacktrace is printed by default. Meaningful error messages are only printed if the "--verbose" flag is provided.

PythonInspector: Enable verbose output

---

utils/common/src/main/kotlin/Os.kt

Just use the single real match group instead for this local helper function. While at it, also avoid the non-null assertion.

Os: Avoid the need to name the match group explicitly in `expandVariable`

---

build.gradle.kts

Kotlin 1.7.20 changed its behavior and warns about Kotlin script files that are "used along with regular Kotlin sources", which fails the build as ORT treats warnings as errors. Restore the old behavior to allow such script files.

Gradle: Allow Kotlin script files in source root again

---

downloader/src/main/kotlin/Downloader.kt
scanner/src/main/kotlin/provenance/ProvenanceDownloader.kt

Other properties than `RemoteArtifact` from the former `Package` were only used for logging, and the provenance-based scanner does set the package's `id` to an empty value anyway, so simplify the code by just taking the necessary `RemoteArtifact` as a function parameter.

Change `downloadSourceArtifact` to take a `RemoteArtifact`

---

integrations/jenkins/Jenkinsfile

This demonstrates how to use the `ort-config` repository to provide an example configuration.

Jenkinsfile: Use the `ort-config` repository by default

---

cli/src/main/kotlin/commands/EvaluatorCommand.kt

Make the default value more visible by handling it as part of clikt's options instead of handling a `null` value manually later.

EvaluatorCommand: Leverage clikt's `default` for the rules file option

---

analyzer/src/main/kotlin/managers/CocoaPods.kt

When the pod command can't find any .podspec file for a pod, an empty package will be returned for which only the identifier is set. The empty pURL property in the `Package` object can cause failures later in the Advisor, when requesting vulnerabilities for packages using the pURL. Therefore, it's necessary to set the correct pURL for an empty package explicitly, because when using `Package.EMPTY` it's always empty.

CocoaPods: Set the correct pURL for an empty package

---

analyzer/src/main/kotlin/managers/utils/PythonInspector.kt

Make `homepageUrl` and `declaredLicense` nullable as they can be `null` in the python-inspector output.

PythonInspector: Make some properties nullable

---

analyzer/src/main/kotlin/managers/utils/PythonInspector.kt

The `classifiers` property can be missing in the python-inspector output so provide a default value.

PythonInspector: Provide default value for classifiers

---

cli/src/main/kotlin/commands/EvaluatorCommand.kt

The command allows overriding all curations by the ones provided via the option `--package-curations-file` or `--package-curations-dir`. Make that override work no matter if the curations are empty, to allow for "clearing" the curations.

EvaluatorCommand: Fix-up replacing curations

---

analyzer/src/main/kotlin/managers/GoMod.kt

Go stamps binaries with version control information. Disable this by providing `-buildvcs=false` [1] when running go list because it is not required to gather dependency information and can lead to this error:
error obtaining VCS status: exit status 128
Fixes #5982.
[1]: https://pkg.go.dev/cmd/go

GoMod: Add `-buildvcs=false` when running `go list`

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt

Do not add blank license strings to the list of declared licenses.

MavenSupport: Filter blank declared licenses

---

analyzer/src/main/kotlin/managers/utils/PythonInspector.kt

The `license` property can be missing in the python-inspector output so make it nullable and provide a default value.

PythonInspector: Make license nullable

---

model/src/test/kotlin/config/OrtConfigurationTest.kt

The name was still referring to the HOCON format which has been replaced by YAML.

OrtConfigurationTest: Fix a test name

---

analyzer/src/main/kotlin/managers/Npm.kt

Cache the results of the `npm view` call to improve performance in scans with many projects that have many overlapping dependencies.

Npm: Cache the results of `npm view`

---

analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/utils/NpmDependencyHandler.kt

Run the external process to lookup remote package details in a separate coroutine asynchronously. In the cache, only store the Deferred with the result. This should reduce contention on the cache map, since it is no longer necessary to wait for the process to finish.
Extract the caching logic to a new function that invokes the original getRemotePackageDetails() function. That way subclasses benefit from the caching mechanism as well.

Npm: Improve loading of remote package details

---

model/src/main/kotlin/licenses/ResolvedLicense.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt

When searching the copyright findings for a statement the code was erroneously using the processed statement instead of the unprocessed statement. If the processed statement was different to the original statement this lead to an exception, because the map of original statements to their findings did not contain an entry with that key. Also, this error limited the list of findings in the `ResolvedCopyright` to those which exactly match the processed statement.
This is fixup for 3e9d11d.

ResolvedLicense: Fix `toResolvedCopyrights()`

---

model/src/main/kotlin/ScanSummary.kt

The `ScanRecord` class has been removed in 9d9a449.

ScanSummary: Fix an old reference to `ScanRecord`

---

model/src/main/kotlin/utils/FileArchiver.kt
utils/common/src/main/kotlin/FileMatcher.kt

Generally refer to `FileMatcher`, and only from there refer to the `AntPathMatcher` implementation as a detail.

Fix glob pattern docs to not refer to `FileSystem.getPathMatcher` anymore

---

cli/src/main/kotlin/OrtMain.kt
cli/src/main/kotlin/commands/EvaluatorCommand.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
downloader/src/main/kotlin/VersionControlSystem.kt
model/src/main/kotlin/ScanSummary.kt
model/src/main/kotlin/config/FileArchiverConfiguration.kt
model/src/main/kotlin/config/LicenseFilePatterns.kt
model/src/main/kotlin/config/OrtConfiguration.kt
model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/main/kotlin/utils/OrtResultExtensions.kt
model/src/main/kotlin/utils/RootLicenseMatcher.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
reporter/src/main/kotlin/ReporterInput.kt
reporter/src/main/kotlin/reporters/freemarker/FreemarkerTemplateProcessor.kt
utils/test/src/main/kotlin/Extensions.kt

Align with the `licenseFilePatterns` configuration option name, which is shorter and "name" is somewhat implied by "pattern" anyway.

Rename `LicenseFilenamePatterns` to `LicenseFilePatterns`

---

downloader/build.gradle.kts
downloader/src/main/kotlin/vcs/Git.kt
gradle/libs.versions.toml

The used `org.eclipse.jgit.ssh.apache.agent` artifact has build-in
ssh-agent support. As of https://github.com/oss-review-toolkit/ort/commit/43ff39eea3627f4586ecf53f1791d91154698ec3 there should have been no need anymore
to avoid "keyboard-interactive" prompts as the `CredentialsProvider` is
explicit set to ORT's own `AuthenticatorCredentialsProvider` only.
Resolves #6029.

downloader: Migrate from JSch to MINA as the SSH backend for JGit

---

analyzer/src/main/kotlin/managers/Bundler.kt

Miscellaneous Bundler improvements

---

cli/src/funTest/kotlin/OrtMainFunTest.kt
cli/src/main/kotlin/OrtMain.kt
model/src/main/kotlin/config/OrtConfiguration.kt
model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
utils/common/src/main/kotlin/EnvironmentVariableFilter.kt
utils/common/src/main/kotlin/ProcessCapture.kt
utils/common/src/test/kotlin/EnvironmentVariableFilterTest.kt
utils/common/src/test/kotlin/ProcessCaptureTest.kt

This PR addresses #5973. Refer to the single commits for further details.

Filter environment variables when creating child processes

---

scanner/src/main/kotlin/Scanner.kt

This avoids log output like:
Creating file archives for 0 package(s).
Created file archives for 0 package(s) in 1.969us.

Scanner: Return early if there are no missing archives

---

advisor/src/main/kotlin/advisors/NexusIq.kt

NexusIQ sometimes seems to need more time to process certain requests. To prevent failing requests, increase the timeout.
Notes:
- The processing time seems to depend on the type of packages that are queried. We noted increasing processing times for Go packages, but others may be affected as well.
- Reducing the bulk request size did not have a major impact.
Instead of hard-coding the timeout, it could also be made configurable, but this seems to be a bit of an overkill.

NexusIq: Increase the read timeout for requests

---

analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt

Replace the `mapFromUrl()` function with an extension function that
leverages `downloadText()` to simplify the code a bit.

NuGetSupport: Simplify the code to map object values from URLs

---

helper-cli/src/main/kotlin/commands/repoconfig/GenerateScopeExcludesCommand.kt

See also https://docs.conan.io/en/1.35/devtools/build_requires.html.

GenerateScopeExcludesCommand: Add the scope 'build_requires' for Conan

---

model/src/main/kotlin/config/LicenseFilePatterns.kt

Do not show this (redudant) property in the output of [1].
[1] `ort config --show-active`

LicenseFilePatterns: Exclude `allLicenseFilenames` from serialization

---

model/src/main/kotlin/config/ScanStorageConfiguration.kt

This makes it less likely to use the wrong storage type, because provenance based scanning has become default recently.

ScanStorageConfiguration: Default to provenance based storage

---

evaluator/src/main/kotlin/Rule.kt
model/src/main/kotlin/OrtResult.kt

This allows using the logic without a Rule context from the policy rules.

Rule: Extract some matcher logic to OrtResult to enable re-use

---

model/src/main/kotlin/config/PostgresConnection.kt

Clean-up the output of `ort config --show-active` a bit.

PostgresConnection: Exclude some default value from serialization

---

evaluator/src/main/kotlin/Rule.kt
evaluator/src/test/kotlin/RuleTest.kt
model/src/main/kotlin/OrtResult.kt

**Breaking change:** Policy rules which use `labelContains()` must be changed to use `hasLabel()` instead.

Unify hasLabel() and labelContains()

---

analyzer/src/funTest/kotlin/AnalyzerFunTest.kt
analyzer/src/main/kotlin/Analyzer.kt
model/src/test/kotlin/config/AnalyzerConfigurationTest.kt
model/src/test/kotlin/config/PackageManagerConfigurationTest.kt

Analyzer: Fix `mustRunAfter` to eventually hang when configured globally 

---

analyzer/src/main/resources/scripts/init.gradle

When comparing dependency trees, the count of sub dependencies should not include BOM dependencies, since they are skipped by the `fetchDependency` function.
This solves a bug where an Android project shipping 'androidx.appcompat:appcompat:1.5.1' would hang indefinitely. This is because, for instance, 'kotlinx-coroutines-android:1.6.1' depends on 'kotlinx-coroutines-core:1.6.1, kotlin-stdlib-jdk8:1.6.0 and kotlinx-coroutines-bom:1.6.1'. Since no ORT dependency is created for 'kotlinx-coroutines-bom' because it's a BOM file, it should also not be taken in account when comparing dependency trees. Otherwise, comparison would always fail, leading to a cache miss and overgrowth of the latter.

init.gradle: Ignore BOM dependencies when comparing dependency trees

---

analyzer/src/funTest/assets/projects/synthetic/dotnet-direct-dependencies-only-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output-with-nuspec.yml
analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/nuget-direct-dependencies-only-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/nuget-expected-output.yml
analyzer/src/main/kotlin/managers/DotNet.kt
analyzer/src/main/kotlin/managers/NuGet.kt
analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt

The relationship between the the logic in NugetSupport and the package managers using it was partially of cyclic nature.
Also the code has some tight coupling making it overall relatively hard to work with. 
This PR removes these cyclic things and removes a few further hurdles in order to enable further refactoring and clean-up.
So, the goal is: enable further refactoring (with less complexity).
Breaking change: Because the issue message has been changed slightly. Resolution might need adjustments, see change in `dotnet-expected-output-with-nuspec.yml` for how to adjust the test.

NuGetSupport: Refactoring first couple of steps

---

build.gradle.kts

Directly get the version property instead of the version of the plugin property. This aligns with other code and is slightly simpler.

Gradle: Trivially align the way to get a plugin's version

---

model/src/main/kotlin/utils/FindingsMatcher.kt

Using `$NOASSERTION` in a string looks awfully similar to the literal "NOASSERTION". Make more clear that this is not the literal string but a variable by reducing the import to `SpdxConstants`.

FindingsMatcher: Do not import `NOASSERTION` directly

---

.detekt.yml
analyzer/src/main/kotlin/managers/Pub.kt
clients/clearly-defined/src/main/kotlin/Enums.kt
clients/fossid-webapp/src/main/kotlin/model/status/DownloadStatus.kt
downloader/src/main/kotlin/vcs/GitWorkingTree.kt
gradle/libs.versions.toml
model/src/main/kotlin/utils/FindingCurationMatcher.kt
model/src/test/kotlin/ProjectTest.kt
reporter/src/main/kotlin/reporters/freemarker/FreemarkerTemplateProcessor.kt
utils/spdx/build.gradle.kts
utils/spdx/src/main/kotlin/SpdxLicense.kt
utils/spdx/src/main/kotlin/SpdxLicenseException.kt

The `ComplexMethod` rule was renamed to `CyclomaticComplexMethod`, and revisiting the `threshold` revealed that it can be lowered compared to before (but still needs to be higher than the default of 15).
New rules demand annotated declarations to be on separate lines and to be separated by blank lines, like
@SerialName("npm")
NPM,
@SerialName("crate")
CRATE,
While this notation makes sense if the declarations are documented (and thus already separated by blank lines), for undocumented declarations (esp. as part of `@Serializable` classes) a more compact notation makes sense:
@SerialName("package_name") val packageName: String,
@SerialName("installed_version") val installedVersion: String,
Disable rules that prevent this notation, as it is already used e.g. in the `PythonInspector` class. …

Upgrade Detekt to version 1.22

---

model/src/main/kotlin/licenses/LicenseClassifications.kt
model/src/test/kotlin/licenses/LicenseClassificationsTest.kt

Make the `Map` contain all category names as keys in order to simplify
its use.

LicenseClassification: Ensure `licensesByCategory` contains all keys

---

utils/spdx/src/test/kotlin/SpdxExpressionTest.kt

Extend a few tests that so far only implicitly checked that no exception is thrown to do actual assertions on the results.

SpdxExpressionTest: Add some more assertions

---

analyzer/src/main/kotlin/managers/Cargo.kt
analyzer/src/main/kotlin/managers/Carthage.kt
analyzer/src/main/kotlin/managers/Composer.kt
analyzer/src/main/kotlin/managers/GoMod.kt
analyzer/src/main/kotlin/managers/Gradle.kt
analyzer/src/main/kotlin/managers/Pub.kt
downloader/src/main/kotlin/vcs/MercurialWorkingTree.kt
scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
scanner/src/test/kotlin/scanners/scancode/ScanCodeTest.kt
utils/common/src/main/kotlin/CommandLineTool.kt
utils/common/src/main/kotlin/Extensions.kt

Leading / trailing or multiple consecutive inner spaces led to empty arguments which, when passed to ScanCode, cause weird behavior, like the result file not being written. Fix that stripping any / multiple spaces when splitting options.
Fixes #6102.

ScanCode: Strip all spaces when parsing (non-)configuration options

---

docker/legacy/Dockerfile

*Edit:* [Here](https://docs.docker.com/engine/reference/builder/#copy---link)'s another good explanation of the used feature.

docker/legacy: Make use of linked copies to speed up the build

---

model/src/main/kotlin/licenses/ResolvedLicense.kt
model/src/test/kotlin/licenses/ResolvedLicenseTest.kt

The `associateBy()` was unintentionally deduplicating original findings with the same statement. Fix that by using `groupBy()` (and `flatMapTo()`) instead. Also add a test for the wanted behavior. See [1] for the original report with another proposed fix; this fix is more minimal.
[1]: https://github.com/oss-review-toolkit/ort/pull/6104

ResolvedLicense: Fix a regression in `toResolvedCopyrights()`

---

batect
batect.cmd

See [1].
[1]: https://github.com/batect/batect/releases/tag/0.83.0

Upgrade Batect to version 0.83.0

---

Dockerfile
docker/set_apt_proxy.sh

To accomplish the last step of docker multi stage change, we need take small step to achieve the result of the draft PR https://github.com/oss-review-toolkit/ort/pull/6041, as too big to change in a single step.
This initial needed changes accomplish:
- Updated the version of dockerfile spec to accept build-contexts ( buildx )
- Add extra packages to base to eliminate the need of a builder image, reducing build time after cached and providing the minimal packages needed to language package managers  build native bindings, mostly cargo, ruby and python 
- Make base image run as non-privileged user instead of root
- Add proxy script for apt, as now image is user based and apt will run in sudo mode
- Modify permissions on android deploy dir, as now need to be run as user, and github actions …

docker: Prepare base layer to non privileged user

---

build.gradle.kts
model/src/main/kotlin/Mappers.kt

Since version 1.32 [1] SnakeYAML sets the limit for incoming data to 3MB. Since Jackson 2.14 [2] it is possible to override this default, so hardcode the limit to 1GB to allow parsing large ORT result files.
[1]: https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes
[2]: https://github.com/FasterXML/jackson-dataformats-text/issues/337

Set the code point limit for SnakeYAML to 1GB

---

renovate.json

Do this for the same reason as for Docker, see a0b489a.

Renovate: Disable Batect updates

---

renovate.json

ORT is stuck on Java 11, see [1].
[1]: https://github.com/oss-review-toolkit/ort/pull/4948

Renovate: Ignore Spring 6 which requires Java 17

---

renovate.json

This still leaves "batect-wrapper" enabled to receive updates to Batect
itself. This implements https://github.com/oss-review-toolkit/ort/commit/0e66cf28397d7bf4bdf42ed5279c5cba8a9045b6 properly which was reverted in https://github.com/oss-review-toolkit/ort/commit/7aa61bf96b2b2752da785c47445883e65494bb91.

  Renovate: Disable updates to (Docker base images in) Batect files

---

analyzer/src/main/kotlin/Analyzer.kt

The inner log statement is also triggered initially when `finishedPackageManagers` is empty, so the almost identical log messages were shown both. Remove the outer one to avoid that duplication.

Analyzer: Remove a duplicate log message

---

utils/spdx/src/main/resources/declared-license-mapping.yml

Found in [1].
[1]: https://repo1.maven.org/maven2/org/tmatesoft/sqljet/sqljet/1.1.15/sqljet-1.1.15.pom

declared-license-mapping: Add mapping for GPL-3.0-only

---

downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt
downloader/src/test/kotlin/vcs/GitTest.kt

GitWorkingTreeFunTest: Make testing for remote branches less flaky

---

cli/src/main/kotlin/OrtCommand.kt
cli/src/main/kotlin/OrtMain.kt
cli/src/main/kotlin/commands/AdvisorCommand.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
cli/src/main/kotlin/commands/ConfigCommand.kt
cli/src/main/kotlin/commands/DownloaderCommand.kt
cli/src/main/kotlin/commands/EvaluatorCommand.kt
cli/src/main/kotlin/commands/NotifierCommand.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
cli/src/main/kotlin/commands/RequirementsCommand.kt
cli/src/main/kotlin/commands/ScannerCommand.kt
cli/src/main/kotlin/commands/UploadCurationsCommand.kt
cli/src/main/kotlin/commands/UploadResultToPostgresCommand.kt
cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
cli/src/main/resources/META-INF/services/org.ossreviewtoolkit.cli.OrtCommand

This allows to provide external subcommands to ORT at runtime.

cli: Turn commands into plugins

---

build.gradle.kts

Starting with IntelliJ IDEA 2022.3, an IDE build creates "classpath.index" per module which Gradle does not know how to handle and fails with
Entry classpath.index is a duplicate but no duplicate handling
strategy has been set.
Solve that by setting an appropriate duplicate handling strategy to exclude all but the first file. Also see [1].
[1]: https://youtrack.jetbrains.com/issue/IDEA-305759

Gradle: Set a duplicate handling strategy (to handle "classpath.index")

---

downloader/src/main/kotlin/vcs/Git.kt

According to the class documentation of `WorkingTree`, the `workingDir` does not necessarily need to be the root directory of the tree. However, the `.gitmodules` file should be interpreted as such only if it resides in the root directory of the tree.
Note: Discovered in context of #6166.

Git: Fix a potential issue with updateSubmodules()

---

cli/src/main/kotlin/OrtMain.kt

Similar to like in the analyzer and evaluator commands for their specific configuration files, print which main ORT configuration file is being looked for to assist with debugging.

OrtMain: Print which ORT config file is being looked for

---

helper-cli/build.gradle.kts
helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/classifications/ImportCommand.kt
helper-cli/src/main/kotlin/commands/classifications/LicenseClassificationsCommand.kt
helper-cli/src/main/kotlin/commands/classifications/MergeCommand.kt
model/src/main/kotlin/licenses/LicenseClassifications.kt
model/src/test/kotlin/licenses/LicenseClassificationsTest.kt

Add a `helper-cli` commands to import and merge license classifications

---

analyzer/src/funTest/assets/projects/synthetic/gomod-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/gomod/go.mod
analyzer/src/funTest/assets/projects/synthetic/gomod/go.sum
analyzer/src/main/kotlin/managers/GoMod.kt

Change `getModuleInfos` to return a map which associates the module paths to the related module info. The keys of the map contain both, the paths of replaced modules and those of their replacements. This fixes support for replace directives which do not only replace the version but also the path of a module. Previously, this caused a `NoSuchElementException` because module infos where only associated to the path of the replacing module, but the output of `go mod graph` also contains the paths of replaced modules.
Fixes #5604.

GoMod: Fix support for replace directives

---

docs/config-file-license-classifications-yml.md
docs/dir-custom-license-texts.md
docs/getting-started.md

Scanners do not get bootstrapped anymore as of 721ee9d, so replace that part of the docs with a link to ScanCode installation docs.

getting-started: Remove the hint about ScanCode getting bootstrapped

---

README.md

Ticket linked with limitations[1] has been closed as Python version is now configurable.
[1]: https://github.com/oss-review-toolkit/ort/issues/3671
Signed-off-by: Thomas Steenbergen <thomas_steenbergen@epam.com>

README: Remove limitations for Python analyzer

---

model/src/test/kotlin/config/OrtConfigurationTest.kt

Minor `OrtConfigurationTest` improvements

---

cli/src/main/kotlin/OrtMain.kt

This may help to debug permission issues as the ORT_DATA_DIR might not always point to below the current user's home directory (which would contain the user name).

OrtMain: Also explicitly print the user under which ORT is running

---

analyzer/src/funTest/kotlin/managers/Extensions.kt

Filtering a `Set` should again result in a `Set`.

Extensions: Make `filterReferencedPackages()` return a `Set`

---

analyzer/src/funTest/kotlin/managers/BundlerFunTest.kt
analyzer/src/funTest/kotlin/managers/ComposerFunTest.kt
analyzer/src/funTest/kotlin/managers/GoDepFunTest.kt
analyzer/src/funTest/kotlin/managers/PubFunTest.kt
analyzer/src/test/kotlin/PackageManagerTest.kt

In contrast to comparing the size to 0, this also shows the unexpected content.

analyzer: Prefer the `beEmpty` matcher

---

cli/src/main/kotlin/OrtMain.kt

Change the first letter to avoid confusing the "O" for an "A".
Feel free to propose another style, but it kept annoying me that I always read "ART" instead of "ORT".

OrtMain: Make the ASCII font more readable

---

cli/src/main/kotlin/commands/EvaluatorCommand.kt

Use the `packageCurationsDir` and `packageCurationsFile` options to check if the curations should be replaced, instead of the unrelated `packageConfigurationOption`.
This is fixup for 84ef89f.

EvaluatorCommand: Fix the check if package curations should be replaced

---

reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModelReporter.kt

EvaluatedModelReporter: Remove unused measureTimedValue

---

analyzer/src/funTest/kotlin/curation/ClearlyDefinedPackageCurationProviderFunTest.kt
analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt

The test talks to the real servers and thus should be a functional test. This makes room for `ClearlyDefinedPackageCurationProviderMockTest` to drop "Mock" from its name in turn.

analyzer: Make `ClearlyDefinedPackageCurationProviderTest` a `funTest`

---

downloader/src/main/kotlin/vcs/Git.kt
utils/common/src/main/kotlin/Extensions.kt
utils/common/src/test/kotlin/ArchiveUtilsTest.kt
utils/common/src/test/kotlin/ExtensionsTest.kt
utils/ort/src/funTest/kotlin/storage/LocalFileStorageFunTest.kt
utils/scripting/src/main/kotlin/OrtScriptCompilationConfiguration.kt

Make the `safeMkdirs` function fluent because it allows nicer code in some places.

common-utils: Make safeMkdirs fluent

---

utils/common/src/main/kotlin/ArchiveUtils.kt

ArchiveUtils: Use the fluent `safeMkdirs()` in one more place

---

.github/workflows/build-and-test.yml
Dockerfile
batect.yml

It is common practice to mount a host-side ORT config directory into the Docker container at `/home/ort/.ort/config`. While Docker infers the permissions for the `config` directory from the corresponding directory on the host, for the intermediate `.ort` directory (which did not exist in the container prior to this change) there is no corresponding directory on the host, so Docker uses `root:root` ownership. Fix the ownership to be `ort:ort` by ensuring that the `.ort` directory exists in the container.

Dockerfile: Ensure that the `.ort` data directory exists

---

.gitmodules
Dockerfile
analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
analyzer/src/funTest/kotlin/managers/PnpmFunTest.kt
analyzer/src/funTest/kotlin/managers/SbtFunTest.kt
batect.yml
build.gradle.kts
docker/legacy/Dockerfile
model/src/test/assets/sbt-multi-project-example-graph-old.yml
model/src/test/assets/sbt-multi-project-example-graph.yml
model/src/test/kotlin/AbstractDependencyNavigatorTest.kt
utils/test/src/main/kotlin/Utils.kt

This basically reapplies the commit reverted in 960f702 as it was agreed in the community meeting that by now Java 17 should be the default [1], but the Java version should be configurable via a Docker build argument. Users that need to analyze projects incompatible with Java 17 should use `--build-arg JAVA_VERSION=11` with `docker build` to restore the previous behavior.
[1]: https://github.com/oss-review-toolkit/ort/wiki/Community-Meeting#2022-12-15-last-meeting-before-holiday-season

Docker: Use Java 17 by default to build and run ORT

---

utils/spdx/src/main/resources/declared-license-mapping.yml

[1]: https://github.com/iziz/libPhoneNumber-iOS/blob/0.9.15/libPhoneNumber-iOS.podspec#L10

Add a non-ambiguous declared license mapping to `Apache-2.0`

---

advisor/src/test/kotlin/advisors/GitHubDefectsTest.kt
analyzer/src/test/kotlin/managers/CarthageTest.kt
analyzer/src/test/kotlin/managers/utils/MavenDependencyHandlerTest.kt
downloader/src/test/kotlin/vcs/GitTest.kt
scanner/src/test/kotlin/scanners/fossid/FossIdUrlProviderTest.kt
utils/ort/src/test/kotlin/OkHttpClientHelperTest.kt
utils/ort/src/test/kotlin/UtilsTest.kt

Always unmock mocked objects and static functions so that they are not leaked.

Make sure that static and object mocks are canceled

---

model/src/test/assets/result-with-issues-graph.yml
model/src/test/assets/result-with-issues-scopes.yml

Correct the serialized value of `has_issues` for test input files that actually have issues (in references or scopes). Note that this is "just" an inconsistency that does not matter in test as the value of `has_issues` is not deserialized but determined programmatically.

model: Fix inconsistent `has_issues` in test input files

---

analyzer/src/main/kotlin/managers/Bower.kt
analyzer/src/main/kotlin/managers/CocoaPods.kt
analyzer/src/main/kotlin/managers/Composer.kt
analyzer/src/main/kotlin/managers/Conan.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/Pipenv.kt
analyzer/src/main/kotlin/managers/Pnpm.kt
analyzer/src/main/kotlin/managers/Pub.kt
analyzer/src/main/kotlin/managers/Sbt.kt
analyzer/src/main/kotlin/managers/Stack.kt
analyzer/src/main/kotlin/managers/Yarn.kt
analyzer/src/main/kotlin/managers/Yarn2.kt
analyzer/src/main/kotlin/managers/utils/PythonInspector.kt
cli/src/main/kotlin/commands/RequirementsCommand.kt
downloader/src/main/kotlin/VersionControlSystem.kt
downloader/src/main/kotlin/vcs/Git.kt
gradle/libs.versions.toml
model/src/main/kotlin/PackageCuration.kt
scanner/src/funTest/kotlin/storages/AbstractProvenanceBasedStorageFunTest.kt
scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt
scanner/src/main/kotlin/ScannerCriteria.kt
scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
scanner/src/test/kotlin/ScannerCriteriaTest.kt
scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
utils/common/src/main/kotlin/CommandLineTool.kt

Switch to the Semver4j fork

---

evaluator/src/main/kotlin/ProjectSourceRule.kt
evaluator/src/main/kotlin/RuleSet.kt
evaluator/src/test/kotlin/ProjectSourceRuleTest.kt

When executing multiple project source rules which access the project's source tree, the sources get cloned once per `ProjectSourceRule` instance contained in the `RuleSet`. These redundant clone operations slow down the execution without need.
Ensure that project sources are cloned at most once per rule set or rather evaluator run respectively.
Fixes: #6064.

evaluator: Clone project sources at most once

---

helper-cli/src/main/kotlin/commands/ListCopyrightsCommand.kt
utils/ort/src/main/kotlin/CopyrightStatementsProcessor.kt
utils/ort/src/test/kotlin/CopyrightStatementsProcessorTest.kt

There is no reason for the in-memory representation to be sorted, so sort
only the "visualizations" for the serialized result in
`CopyrightStatementsProcessorTest` and the console output in
`ListCopyrightsCommand`.

CopyrightStatementsProcessor: Do not use sorted maps / sets in the `Result`

---

README.md

The LGTM service has been long deprecated, see [1]. As soon as CodeQL (the successor on GitHub side) fully supports Kotlin 1.8, ORT will take it into use, see [2].
[1]: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/ [2]: https://github.com/oss-review-toolkit/ort/pull/6134

README: Remove the LGTM badge

---

analyzer/build.gradle.kts
cli/build.gradle.kts
evaluator/build.gradle.kts
helper-cli/build.gradle.kts

This silences false-positive error messages in IntellJ [1]. This commit addresses files which were forgotten in e66786e.
[1]: https://youtrack.jetbrains.com/issue/KTIJ-19369

Gradle: Suppress DSL_SCOPE_VIOLATION

---

model/src/main/kotlin/Mappers.kt

Increase the code point limit because ORT result files can exceed 1GB for large projects.
Fixes #6316.

Mappers: Increase the code point limit for SnakeYAML to 2GB

---

analyzer/src/main/kotlin/managers/GoMod.kt

Signed-off-by: Frank Viernau <frank_viernau@epam.com>

GoMod: Consistently Spell "Go" with capitalized first character

---

cli/build.gradle.kts
gradle/libs.versions.toml
helper-cli/build.gradle.kts

Running ORT via its shadow JAR exhibits bugs, e.g. #6318, which do not exist when using ORT via its normal distribution or distribution archive. The latter comes with a shell script which takes care of setting the options for running ORT propertly, e.g. the classpath, and should be used as replacement for the shadow JAR.
Note: The shadow JAR had been introduced as replacement for a custom fat JAR task, see a41a44715e9e7efea90d6d1f2942d319b51cf6ba.
Closes #6318.

gradle: Remove the task for packaging the broken shadow JAR

---

analyzer/src/main/kotlin/curation/FilePackageCurationProvider.kt
analyzer/src/test/kotlin/curation/FilePackageCurationProviderTest.kt
cli/src/main/kotlin/commands/EvaluatorCommand.kt
helper-cli/src/main/kotlin/commands/packagecuration/SetCommand.kt

While the previous implementation did an `isDirectory` check, the implementation was still calling the `FilePackageCurationProvider` constructor directly which assumes all `File` instances to really be files.
Address that by instead relying on the existing logic in `from()`, and creating another convenience `from()` function that takes a `FilePackageCurationProviderConfig`.

FilePackageCurationProvider: Fix creating directory providers from config

---

analyzer/src/main/kotlin/curation/FilePackageCurationProvider.kt
model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt

This avoids the need for `$ORT_CONFIG_DIR/curations.yml` to be present.

FilePackageCurationProvider: Filter out non-existing files

---

.commitlintrc.yml
.github/workflows/static-analysis.yml
renovate.json

See [1]. This is a preparation for release automation including release
notes. At the same time, configure Renovate to use "deps" as the type
and no scope at all, see [2].
[1]: https://www.conventionalcommits.org/
[2]: https://docs.renovatebot.com/semantic-commits/
Co-authored-by: Martin Nonnenmacher <martin.nonnenmacher@gmail.com>

ci(github): Start enforcing of Conventional Commits

---

.ort.yml

This PR is in the context of scanning ORT with ORT. Sonatype NexusIQ which we use currently as advisor issues a number of vulnerabilities for ORT. In this PR I try to address some of them by resolutions in `.ort.yml` that (according to my analysis and understanding) should not affect ORT in the way it is using the affected components.
There are other vulnerabilities though which probably cannot be handled by such resolutions in general, since they may depend on the concrete context or environment in which ORT is used.

Address some vulnerabilities reported for ORT using resolutions in .ort.yml

---

analyzer/src/main/kotlin/managers/Pip.kt

The code currently inputs operatingSystem of macOS as "mac" when running python-inspector.
However, python-inspector expects the option of macOS to be "macos".
Signed-off-by: Michael Yoo <vbtkdpf148@gmail.com>

Pip: fix operating system name for macOS

---

.ort.yml

chore(.ort.yml): Align a comment to `GenerateScopeExcludesCommand`

---

build.gradle.kts

Be on the safe side and only gather "dependencies" tasks whose type is `DependencyReportTask`.

chore(Gradle): Also specifiy the type for "dependencies" tasks

---

.ort.yml
analyzer/build.gradle.kts

This is a follow-up of #6338. It suppresses some more vulnerabilities by excluding a scope for generation of GraphQL clients and adding a constraint to enforce a higher version of a transitive gson dependency.

Address some more vulnerabilities findings

---

.ort.yml

One more resolution for a vulnerability:
This is related to JRuby. Affected is the bundler gem in an earlier version than the one bundled with the current JRuby dependency.

chore(ort.yml): Add a vulnerability resolution for an invalid match

---

.github/workflows/build-and-test.yml
downloader/src/main/kotlin/vcs/GitWorkingTree.kt

The nested repository information and the scanner cache require that the VCS path is empty, which is typically done when resolving a submodule (from the local path to the upstream repo).
This resolution is not possbile if the submodule is not initialized.
Closes: #6146 

GitWorkingTree: Clear VCS path if submodule is not initialized.

---

.commitlintrc.yml
advisor/src/main/kotlin/Advisor.kt
advisor/src/test/kotlin/AdvisorTest.kt
cli/src/main/kotlin/commands/AdvisorCommand.kt

Add an `advise` function that is easier to use programmatically, see the commit messages for details.
**Breaking change:**
The function `Advisor.retrieveFindings()` was renamed to `Advisor.advise()`.

Improve Advisor API

---

.commitlintrc.yml

Scopes with mixed case like "FossID" should be allowed, but they seem to match none of the supported case styles [1], so simply disable the rule completely, even if that allows unwanted spaces in the scope name.
[1]: https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md#scope-case

fix(commitlint): Disable `scope-case` checks

---

model/src/main/resources/reference.yml

docs: Fix minor missing quotes in `reference.yml`

---

advisor/src/main/kotlin/Advisor.kt
cli/src/main/kotlin/commands/AdvisorCommand.kt

With this change, the Advisor can be better integrated with code that is already using coroutines. This also aligns the API with other ORT components like the Scanner.
BREAKING CHANGE: Clients now have to start coroutines.

refactor(Advisor)!: Make advise functions suspendable

---

gradle.properties
utils/spdx/src/main/kotlin/SpdxLicense.kt
utils/spdx/src/main/kotlin/SpdxLicenseException.kt
utils/spdx/src/main/resources/exceptions/x11vnc-openssl-exception
utils/spdx/src/main/resources/licenses/FSFULLRWD
utils/spdx/src/main/resources/licenses/Knuth-CTAN
utils/spdx/src/main/resources/licenses/checkmk
utils/spdx/src/main/resources/licenses/libutil-David-Nugent

Generated files were updated by running `./gradlew generateSpdxEnums`.

Gradle: Upgrade the SPDX license list to version 3.19

---

analyzer/src/funTest/assets/projects/synthetic/conan-py/lockfile.lock
analyzer/src/funTest/kotlin/managers/ConanFunTest.kt
analyzer/src/funTest/kotlin/managers/SpdxDocumentFileFunTest.kt
analyzer/src/main/kotlin/managers/Conan.kt
model/src/main/resources/reference.yml

Require a lockfile if a path to the lockfile is configured in `config.yml`.
Only lockfiles located in the same directory as the definition file are
supported.
The test for Conan lockfiles cannot complete successfully when ran
locally as `package id` differs depending on operating system. The
`package id` in the test is set to the one calculated on Linux.
Signed-off-by: Oleksandr Yarosevych <fixed-term.oleksandr.yarosevych@bosch.io>

Conan: Add support for Conan lockfiles

---

reporter/src/main/kotlin/reporters/opossum/OpossumReporter.kt
reporter/src/test/kotlin/reporters/opossum/OpossumReporterTest.kt

Mainly, migrate from accessing the legacy dependency representation to using the dependency navigator, to remove technical debt and to enable and make further simplifications.

Migrate the Opossum reporter to the dependency navigator

---

build.gradle.kts

The change is non-functional as the default value is `false`. However, it simplifies enabling the streams during development.

chore(build.gradle): Explicitly disable standard streams in tests

---

cli/src/funTest/kotlin/OrtMainFunTest.kt

Also rename the result variable to fit the code to a single line and for consistency with other test cases in this file.

OrtMainFunTest: Inline a variable

---

analyzer/src/main/kotlin/managers/Unmanaged.kt

fix(analyzer): Correctly determine the project name from Windows paths

---

downloader/src/main/kotlin/vcs/GitWorkingTree.kt

fix(GitWorkingTree): Ensure to use invariant paths for local "remotes"

---

analyzer/src/main/kotlin/managers/Unmanaged.kt

This is a fix for 07c8633a in #6402 which changed the way the name for unmanaged projects was generated. This approach threw an IllegalArgumentException for all VCS URLs not of type file://. To fix this, obtain the project name from the path of the VCS URI.
I could successfully test the new way to obtain the project name in our setup; however, I am not sure how this looks like under Windows.

fix(Unmanaged): Fix ID generation for unmanaged projects

---

analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/test/assets/npm-err.txt
analyzer/src/test/assets/test-package-no-deps.json
analyzer/src/test/kotlin/managers/NpmTest.kt

When parsing the output of the command to install NPM dependencies, do not expect that the output starts with the expected error level, but read the whole text if necessary. Otherwise, important error information can be missed if the output starts with a hint.

fix(Npm): Correctly parse the output of the 'npm' command

---

cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
evaluator/src/main/kotlin/PackageRule.kt
helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
helper-cli/src/main/kotlin/utils/Extensions.kt
model/src/main/kotlin/CuratedPackage.kt
model/src/main/kotlin/OrtResult.kt

Get rid of the "not always correctly working" [1] `toUncuratedPackage()` by utilizing the original uncurated packages from the `OrtResult`. While at it, do a couple of clean-ups for related `OrtResult` getters and their callers.
[1] https://github.com/oss-review-toolkit/ort/issues/5637.
BREAKING CHANGE: Only for programmatic use of ORT:
1. uncurated packages should be obtained now from the `OrtResult` instead of from the removed `toUncuratedPackage()`.
2. Some API functions get renamed, so the name change must be reflected.

Fix an issue with CuratedPackage.toUncuratedPackage()

---

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml

It got broken by 93ae76a29df6e2fa529c77fea14fd9c5a8ae3cec by accident.

test(GitRepoFunTest): Fix-up an expected result file

---

analyzer/src/main/resources/scripts/init.gradle

In a previous commit ([1]), support for Composite build was added using Gradle Internal API. Unfortunately, this introduced a regression for all projects using Gradle < 7.2.0 which could not be analyzed anymore. This commit fixes the regression by using reflection to call the internal API.
For projects running Gradle < 7.2.0 and using the composite build feature, the behavior is restored to the previous one i.e. it will throw a `NullPointerException` when accessing the group ID of a subproject from an included build.
Solves https://github.com/oss-review-toolkit/ort/issues/6419.
[1]: https://github.com/oss-review-toolkit/ort/commit/6cce314c695e9e4071ef3f8a7956b2683cf2b9d5

fix(Gradle): Fix regression when project uses Gradle < 7.2.0

---

analyzer/src/main/kotlin/managers/Pub.kt
analyzer/src/main/kotlin/managers/utils/PubCacheReader.kt
analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt
downloader/src/main/kotlin/VcsHost.kt
downloader/src/test/kotlin/VcsHostTest.kt

Support Pub dependencies which are loaded from a Git repository.
This implements part of https://github.com/oss-review-toolkit/ort/issues/5268 (only Git packages, but Pub supports additional sources).

feat(Analyzer): Support Pub dependencies from Git

---

cli/src/main/kotlin/commands/AnalyzerCommand.kt

Log the file path of the actually use repository configuration instead of the default file location.

AnalyzerCommand: Fix a file path in the log output

---

.github/codeql/codeql-config.yml
.github/workflows/build-and-test.yml
utils/scripting/src/main/kotlin/OrtScriptCompilationConfiguration.kt

See [1].
[1]: https://github.blog/changelog/2022-11-28-codeql-code-scanning-launches-kotlin-analysis-support-beta/

github/workflows: Enable CodeQL analysis for Kotlin / Java

---

analyzer/src/main/kotlin/PackageCurationProvider.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt

The values of the IDs default to the values of `type` which are all in camel case. So, consistently use camel case for all IDs.

refactor(PackageCurationProvider): Align on camel case IDs

---

analyzer/src/main/kotlin/Analyzer.kt

This allows identifying slow providers. While at it, promote the log level to info, as it seems a better fit.

feature(Analyzer): resolveConfiguration() improvements

---

advisor/build.gradle.kts
analyzer/build.gradle.kts

The projects from the clients sub-directory are used for the low-level implementations only. An exception is the "model" project where conversion functions use ClearlyDefined classes as part of their API.

fix(Gradle): Change client projects to be implementation dependencies

---

cli/src/main/kotlin/commands/AnalyzerCommand.kt

Similar to package manager, also print the list of enabled package curation providers.

refactor(AnalyzerCommand): Print the ids of enabled curation providers

---

analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/PackageCurationProvider.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/ResolvedConfiguration.kt

Conistently order the package curations or the providers repsectively by higherst-priority first. This avoids confusion compared to dealing with inconsistent ordering. This way only the logic which actually applies the curations needs to reverse the curations.
Add or update the KDoc of all releated functions and properties so that the order is always specified.
BREAKING CHANGE: There is no backwards compatibility for de-serializing ORT files prior to this change. Deserialization is possible, but leads to reversing the curation order. Note that recently deserialization has been broken anyway and very soon there will be another breaking change. So, it does not really matter whether this change is breaking as we decided for breaking it anyway.

refactor(Analyzer)!: Improve package curation ordering

---

analyzer/src/funTest/kotlin/curation/ClearlyDefinedPackageCurationProviderFunTest.kt
analyzer/src/funTest/kotlin/curation/OrtConfigPackageCurationProviderFunTest.kt
analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/PackageCurationProvider.kt
analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
analyzer/src/main/kotlin/curation/OrtConfigPackageCurationProvider.kt
analyzer/src/main/kotlin/curation/SimplePackageCurationProvider.kt
analyzer/src/main/kotlin/curation/Sw360PackageCurationProvider.kt
analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt
analyzer/src/test/kotlin/curation/FilePackageCurationProviderTest.kt
cli/src/main/kotlin/commands/UploadCurationsCommand.kt
model/src/main/kotlin/utils/Extensions.kt
scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt

> **Note**
> This is a **breaking change** in the sense that the `PackageCurationProvider` interface now takes a collection of `Package`s instead of `Identifiers`.

Change the curation provider API to take packages instead of ids

---

analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/PackageCurationProvider.kt
analyzer/src/main/kotlin/PackageCurationProviderFactory.kt
analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
analyzer/src/main/kotlin/curation/FilePackageCurationProvider.kt
analyzer/src/main/kotlin/curation/OrtConfigPackageCurationProvider.kt
analyzer/src/main/kotlin/curation/SimplePackageCurationProvider.kt
analyzer/src/main/kotlin/curation/Sw360PackageCurationProvider.kt
cli/src/main/kotlin/commands/EvaluatorCommand.kt
helper-cli/src/main/kotlin/commands/packagecuration/SetCommand.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/utils/PackageCurationProvider.kt

Simplify adding provider IDs to `OrtResult` in a following PR. 
Note that the provider now lives next to `PackageConfigurationProvider`.

analyzer: Move `CurationProvider` to the `model` module

---

advisor/src/main/kotlin/advisors/VulnerableCode.kt
advisor/src/test/assets/__files/vulnerable-code/response_junit.json
advisor/src/test/assets/__files/vulnerable-code/response_log4j.json
advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
clients/vulnerable-code/src/main/kotlin/VulnerableCodeService.kt

While older versions of VulnerableCode used to return official identifiers (like CVEs) for vulnerabilities, this is no longer the case. Instead, internal IDs are used. There is, however, information about aliases which contains such official identifiers. This PR evaluates this information and tries to generate more meaningful IDs for vulnerabilities to be displayed in reports.
_Note_: The presence of alias information in query results is a rather new feature which is not yet part of the latest release of VulnerableCode. There is a related issue [1]. So, there may still be changes in the final release version. The results used by the tests are obtained from the public VulnerableCode instance which already includes this information. The changes in the PR are compatible with older versions, …

VulnerableCode: Uses aliases instead of internal vulnerability IDs

---

model/src/test/kotlin/PackageProviderTest.kt

For now, this just substitutes the Maven-specific test that has been removed from `UtilsTest` as part of f9bfe65.

test(model): Add a `PackageProviderTest`

---

advisor/src/test/assets/ort-analyzer-result.yml
analyzer/src/main/kotlin/Analyzer.kt
cli/src/funTest/assets/gradle-all-dependencies-expected-result-with-curations.yml
cli/src/funTest/assets/semver4j-ort-result.yml
cli/src/main/kotlin/commands/EvaluatorCommand.kt
helper-cli/src/main/kotlin/commands/packagecuration/SetCommand.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/ResolvedConfiguration.kt
model/src/main/kotlin/utils/ConfigurationResolver.kt
model/src/test/assets/analyzer-result-with-dependency-graph.yml
model/src/test/assets/gradle-all-dependencies-expected-result.yml
model/src/test/assets/result-with-issues-graph-old.yml
model/src/test/assets/result-with-issues-graph.yml
model/src/test/assets/result-with-issues-scopes.yml
model/src/test/assets/sbt-multi-project-example-graph-old.yml
model/src/test/assets/sbt-multi-project-example-graph.yml
reporter/src/funTest/assets/gradle-all-dependencies-result.yml
reporter/src/funTest/assets/static-html-reporter-test-input.yml
scanner/src/funTest/assets/analyzer-result.yml
scanner/src/funTest/assets/dummy-expected-output-for-analyzer-result.yml

Keep the association between curations and providers (IDs) in the `OrtResult` to enable
1. Tracability of curations back to providers
2. supporting additional use cases
- replace curations for specific provider with given ones
- re-request curations for given provider IDs
BREAKING CHANGE: No backwards compatibility for de-serializing ORT files. This is ok as backwards compatibility has been broken very recently, so it's not a big deal to extend this by a couple of days. The file format change is limited to `OrtResult.resolvedConfiguration`.

OrtResult: Associate package curations with provider IDs

---

model/src/main/kotlin/OrtResult.kt

refactor(OrtResult): Use getUncuratedPackages() again

---

model/src/main/kotlin/OrtResult.kt

Better express that the expectation is to take a package, and avoid negation of both terms.

refactor(OrtResult): Improve readability a bit with `takeUnless`

---

model/src/main/kotlin/OrtResult.kt

It makes sense to keep this function for programatic use of ORT, for consistency with `getScanResultsForId()`.

fix(OrtResult): Suppress an unused warning

---

README.md

The fat JAR build was removed in [1], so there is no more `ort.jar` being built by JitPack. Also see [2] for some context.
[1]: https://github.com/oss-review-toolkit/ort/pull/6322
[2]: https://github.com/oss-review-toolkit/ort/issues/6512

docs(README): Remove the hint about `ort.jar` from JitPack

---

gradle/libs.versions.toml

This reverts commit fec5dc5 due to an "illegal unicode escape" issue [1].
[1]: https://github.com/antlr/antlr4/issues/2569#issuecomment-1437290697

Revert "deps: update dependency org.antlr:antlr4 to v4.12.0"

---

model/src/main/kotlin/PackageCuration.kt
model/src/test/kotlin/PackageCurationTest.kt

Neither the package's nor the curation's version are guaranteed to use
valid semvers. Semver4j's `coerce()` function creates a valid semver in
cases when this is not wanted, e.g. 1.2.3.4 is parsed as 1.2.3 and
therefore a package curation for 1.2.3.9 would be seen as applicable.
Remove the coercing to valid semvers to avoid applying incorrect package
curations.

fix(PackageCuration): Don't apply curations with different version

---

analyzer/src/main/kotlin/PackageCurationProviderFactory.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/ResolvedConfiguration.kt

This PR finally implements support for package curations in repository configurations, for the use case of re-running the evaluator after making local changes to both, local and global package curations. 

Gracefully handle package curations when replacing repository configurations or curations

---

utils/spdx/build.gradle.kts

Starting with Gradle 8, it became an error to rely on implicit task dependencies like the one of "sourcesJar" on "generateGrammarSource" (see [1]). Make that dependency explicit in the same way as already for "compileKotlin" to fix the JitPack build of sources artifacts (see [2]). Also align code comments while at it.
[1]: https://github.com/gradle/gradle/issues/19555
[2]: https://jitpack.io/com/github/oss-review-toolkit/ort/90858686d8/build.log

fix(Gradle): Make an ANTRL task dependency explicit

---

reporter-web-app/package.json
reporter-web-app/yarn.lock
reporter/src/funTest/kotlin/reporters/WebAppReporterFunTest.kt

Use "yarn upgrade-interactive --latest" command to Update the
dependencies in package.json
backward-incompatible updates might need some code changes but in this
commit the dependancies that are updated don't show any errors and the
app runs successfully after the updates
Signed-off-by: Menatalla Elnemr <menatalla.elnemr@hella.com>

deps(reporter-web-app): backward-incompatible Yarn updates

---

cli/build.gradle.kts
helper-cli/build.gradle.kts

Avoid
WARN FilenoUtil : Native subprocess control requires open access to
the JDK IO subsystem
by adding the required options to the runtime JVM arguments.

fix(Gradle): Avoid a runtime warning with JDK 17

---

analyzer/src/funTest/assets/projects/synthetic/bundler-expected-output-lockfile.yml
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/managers/Bundler.kt
analyzer/src/main/kotlin/managers/Carthage.kt
analyzer/src/main/kotlin/managers/CocoaPods.kt
analyzer/src/main/kotlin/managers/GoDep.kt
analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
analyzer/src/main/kotlin/managers/utils/PythonInspector.kt

Align the fallback project names that are used when the name cannot be determined from the project's metadata. This also reduces the risk of duplicate identifiers for some package managers. See the commit messages for details.
**Breaking change:**
Project names could change for the Bundler, Carthage, and GoDep package managers.

Fallback project names

---

analyzer/src/main/resources/scripts/init.gradle

This is safer in case the interface name changes and makes more clear where the name comes from.

refactor(init.gradle): Do not hard-code an interface name

---

analyzer/src/main/kotlin/PackageManager.kt
build.gradle.kts
helper-cli/src/main/kotlin/utils/PathExcludeGenerator.kt

Since 33fdca9 test from the `test` source sets were not executed
anymore, because no test framework was configured. Fix this by
configuring JUnit Jupiter as test framework.
Note that it is not necessary to declare the test framework for the
`funTest` suite because additional test suites use JUnit Jupiter by
default [1].
[1]: https://docs.gradle.org/8.0/userguide/jvm_test_suite_plugin.html#sec:declare_an_additional_test_suite

build: Fix executing tests

---

advisor/src/main/kotlin/advisors/NexusIq.kt
advisor/src/main/kotlin/advisors/OssIndex.kt
advisor/src/main/kotlin/advisors/VulnerableCode.kt

It is possible that a package declares an empty string as PURL, e.g. for non-published packages. This results in a `Bad Request`. Avoid this by filtering the packages, before requesting the package details.

Advisors: Ensure only non-empty PURLs are used in requests

---

helper-cli/src/main/kotlin/commands/classifications/ImportCommand.kt

Add DoubleOpen as license classification provider

---

README.md

Outline in a few bullet points what a user can do with ORT.
Based on materials I have used at conferences and meetups to explain what ORT does in a nutshell and how its different from other solutions on the market.
This is the first pull request of a series of changes to make ORT documentation more complete and easier to understand. In follow up commits some of the words will be turned into links to new sections of the documentation.

docs(README): Include use cases in introduction

---

analyzer/src/main/kotlin/managers/Conan.kt

Change the globs to match Conan definition files to contain a wildcard after `conanfile` to also find files named like `conanfile-xyz.py`.

Conan: Allow wildcards in definition file names

---

reporter/src/main/kotlin/ReporterInput.kt
reporter/src/main/kotlin/Statistics.kt
reporter/src/main/kotlin/StatisticsCalculator.kt
reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModel.kt
reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModelMapper.kt

This can be useful for outputting a short summary, e.g. for an ORT run on CI.

feat(FreeMarkerTemplateReporter): Pass `statistics` to the templates

---

reporter/src/main/kotlin/reporters/freemarker/FreemarkerTemplateProcessor.kt

Prepare for a further refactoring mainly focusing on reducing the size of `processTemplatesInternal()` to
make things easier to grasp.
Context: #6569.

FreemarkerTemplateProcessor: Improve the code a bit

---

analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt
scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt

This should reduce the overall runtime of these tests a bit.

test(ClearlyDefined): Reduce the duration of simulated timeouts

---

docs/getting-started.md

The output filename was recently changed by 96f0866 which missed this occurrence.

docs(getting-started): Fix-up left over

---

gradle/libs.versions.toml

This brings an upgrade of the Psych YAML library to version 5.1.0 [1], which also fixes a too restrictive SnakeYAML version comparison [2], which is in turn a prerequisite to upgrade to SnakeYAML 2.0 [3].
[1]: https://github.com/jruby/jruby/releases/tag/9.4.1.0
[2]: https://github.com/jruby/jruby/issues/7703
[3]: https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes

deps(Gradle): Upgrade to JRuby 9.4.1.0

---

analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pip-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pipenv-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/pipenv-python3-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/poetry-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/python-inspector-expected-output.yml
analyzer/src/main/kotlin/managers/utils/PythonInspector.kt

Actually use `requirementsName` if there is no `setupName`, improve the project name if there are both, and always use the relative path to the analyzer as a fallback.
Fixes #6524.
> **Note**
> This is a **breaking change** under some circumstances Python projects my get assigned different ids than before, which might affect existing curations.

fix(PythonInspector): Improve the way project names are derived

---

scanner/build.gradle.kts
utils/spdx/build.gradle.kts

Gradle 8 started to ship with Kotlin 1.8, which deprecated several constructs. Replace these with their current counterparts.

fix(Gradle): Stop using deprecated constructs in Kotlin DSL

---

downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt

Make `GitWorkingTreeFunTest` resilient towards newly added remote Git tags

---

advisor/src/main/kotlin/advisors/GitHubDefects.kt
advisor/src/test/kotlin/advisors/GitHubDefectsTest.kt
clients/github-graphql/src/main/kotlin/GitHubService.kt
clients/github-graphql/src/test/kotlin/GitHubServiceTest.kt

This simplifies the current code as well as some upcoming further refactoring.

refactor(GitHubService): Make `ENDPOINT` a `String`

---

detekt-rules/src/main/kotlin/OrtPackageNaming.kt

build(detekt-rules): Fix `OrtPackageNaming` on Windows

---

model/src/main/kotlin/config/RepositoryAnalyzerConfiguration.kt
model/src/main/kotlin/config/RepositoryConfiguration.kt
model/src/test/kotlin/config/AnalyzerConfigurationTest.kt

Add a `RepositoryAnalyzerConfiguration` class that contains the same properties as `AnalyzerConfiguration` with the difference that they are all nullable. This fixes the merging of the global analyzer configuration with the analyzer configuration from the repository configuration, because now all properties can be ignored if they are null.
Previously, if any analyzer property was set in the repository configuration, `allowDynamicVersions` and `skipExcluded` were initialized with their default values and overwrote the global configuration.

fix(analyzer): Only use values configured in repository configuration

---

analyzer/src/main/kotlin/managers/GoDep.kt

Use `requireLockfile` to align the implementation and the related error message with other package managers.

refactor(GoDep): Use the `requireLockfile` helper function

---

scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt

That convenience function was added in Semver library version 4.3.0.

refactor(ScanCodeResultParser): Make use of `isApiCompatible()`

---

utils/common/src/main/kotlin/ArchiveUtils.kt
utils/common/src/test/kotlin/ArchiveUtilsTest.kt

Previously, the determined `ZipArchiveEntry` name was empty when packing a single file. Fix this by calculating the relative path correctly in that case.

fix(ArchiveUtils): Correct the entry name when packing a single file

---

docs/config-file-copyright-garbage-yml.md
examples/copyright-garbage.yml
model/src/main/kotlin/config/CopyrightGarbage.kt
model/src/main/kotlin/licenses/LicenseInfoResolver.kt

Allow to match Copyright garbage by `Regex` patterns

---

helper-cli/src/main/kotlin/commands/ImportCopyrightGarbageCommand.kt

`Locale` constructors are deprecated as of Java 19. Alternatives are the `Builder` class or the static `of` method [1], but the latter is only available as of Java 19. So use the former `Builder` approach for compatibility. Resolves #6631.
[1]: https://simplelocalize.io/blog/posts/java-internationalization/#locale-class-changes

fix(ImportCopyrightGarbageCommand): Stop using `Locale` constructors

---

analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm-expected-output-scope-excludes.yml
analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
analyzer/src/funTest/kotlin/managers/BabelFunTest.kt
analyzer/src/funTest/kotlin/managers/NpmFunTest.kt
analyzer/src/funTest/kotlin/managers/NpmVersionUrlFunTest.kt
analyzer/src/main/kotlin/managers/Npm.kt

This improves the logic added in 5311dcd by grouping on arbitrary secondary prefix instead of hard-coding them. This also creates a separate issue for each deprecated packages for a better overview.

feat(Npm): Group related lines when parsing issues

---

analyzer/src/funTest/assets/projects/synthetic/gomod-no-deps-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/gomod-no-deps/go.mod
analyzer/src/funTest/kotlin/managers/GoModFunTest.kt
analyzer/src/main/kotlin/managers/GoMod.kt

This is part of #6615. For that issue to be fixed GoMod needs to work in case of:
- unused dependencies + used dependencies
- only unused dependencies
- no dependencies at all

GoMod: Fix analyzing projects without deps

---

analyzer/src/main/kotlin/managers/GoMod.kt
analyzer/src/main/kotlin/managers/utils/Graph.kt

The `GoMod` class was quite large and extracting the `Graph` class to a separate file removes a bit of distraction for the reader.

refactor(GoMod): Extract the `Graph` class and improve it a bit

---

build.gradle.kts

This way running
./gradlew -q :cli:run --args="--generate-completion=bash" > \
integrations/completions/ort-completion.bash
does not write the "Building ORT version" string to the file.

build(Gradle): Change version logging to `lifecycle`

---

analyzer/src/funTest/kotlin/managers/DotNetFunTest.kt
analyzer/src/funTest/kotlin/managers/NuGetFunTest.kt
analyzer/src/main/kotlin/managers/Bundler.kt
analyzer/src/main/kotlin/managers/Conan.kt
analyzer/src/main/kotlin/managers/DotNet.kt
analyzer/src/main/kotlin/managers/Gradle.kt
analyzer/src/main/kotlin/managers/Npm.kt
analyzer/src/main/kotlin/managers/NuGet.kt
analyzer/src/main/kotlin/managers/Pip.kt
analyzer/src/main/kotlin/managers/Pub.kt
analyzer/src/main/kotlin/managers/Yarn2.kt
analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt

These are useful for programmatic use of the package managers.
Where it is offered, also slightly rearrange related code blocks of constants to they are at the top of the file, with public ones going first.

refactor(analyzer): Make all constants for option key names public

---

utils/spdx/build.gradle.kts

Do not print the full URL for more clear console output and to align with the SPDX download. Also show the total number of license list entries afterwards.

build(spdx-utils): Improve logging for ScanCode license list download

---

scanner/src/main/kotlin/scanners/scancode/ScanCode.kt

Support for ScanCode version 2 has been dropped a while ago [1]. So, set a lower bound for clarity.
[1] https://github.com/oss-review-toolkit/ort/commit/4663b01813494a716a767f96af89996f76b4be24

ScanCode: Set a lower bound for the required version

---

analyzer/build.gradle.kts
analyzer/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml

This is necessary now due to `test` dependencies no more leaking into `funTest` as of 508701e.

build(analyzer): Fix `funTest` to see the text fixtures

---

gradle/libs.versions.toml

Strip the "Impl" suffix as there is nothing else than the (logback-classic) implementation.

build(Gradle): Simplify the version constant for Logback

---

utils/spdx/src/main/kotlin/SpdxExpression.kt
utils/spdx/src/test/kotlin/SpdxExpressionTest.kt

This reverts commit 2ce43220f4e8dce5d6421b4527c7ab513dd8345d. In some circumstances, the new license choice implementation leads to infinite loop during Evaluator runs.

revert(SpdxExpression): Revert changes to the license choice

---

renovate.json

Configure the renovate-bot to use the existing "dependencies" label on PRs that update dependencies as another way to filter for these PRs.

feat(renovate): Use the existing "dependencies" label

---

clients/osv/src/main/kotlin/Model.kt

The API recently started returning data using schema version 1.4.0, see [1]. So, incorporate the changes as per change log [2] to ensure that deserialization still works.
Fixes: #6708.
[1]: https://github.com/oss-review-toolkit/ort/pull/6681/commits/4301c660c339be92e1a747f30bb0e31d02e23139
[2]: https://ossf.github.io/osv-schema/#change-log

fix(clients/osv): Support latest vulnerability schema version 1.4.0

---

plugins/package-curation-providers/build.gradle.kts
plugins/package-managers/build.gradle.kts

Add the missing configuration to include the dependencies of the `package-curation-providers` and `package-managers` platform projects in the generated POM files.

fix(plugins): Include dependencies in POM files of platform projects

---

analyzer/build.gradle.kts
gradle/libs.versions.toml
plugins/package-managers/gradle/build.gradle.kts

Perspectively, the Maven-2-compatibility-layer should not be used with a
Maven 3 core, see [1], so prepare for that split for more fine-grained
dependencies.
[1]: https://issues.apache.org/jira/browse/MNG-6561

build(Gradle): Decouple `maven-core` from `maven-compat`

---

cli/src/main/kotlin/commands/ReporterCommand.kt
model/src/main/kotlin/utils/DefaultResolutionProvider.kt
reporter/src/funTest/kotlin/reporters/opossum/OpossumReporterFunTest.kt

**Breaking API change:**
The `add()` function of the `DefaultResolutionProvider` was removed.

Refactor default resolution provider

---

README.md

Unfortunately, it does not work to enforce this by adding
org.gradle.configureondemand = false
to the project's `gradle.properties` as any global property would take precedence, see [1].
[1]: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties

docs(README): Note to disable Gradle's "configuration on demand"

---

scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/ScannerCriteria.kt

**To be merged after** #6665.
Fixes #6581.
BREAKING CHANGE:
- The scanner will now fail hard if this mis-configuration accurs instead of tolerating it with caching "disabled".

Scanner: Fail early on misconfigured criteria and version

---

model/src/main/kotlin/utils/DefaultResolutionProvider.kt

Add the missing handling of vulnerability resolutions to `DefaultResolutionProvider.getResolutions()`.

fix(model): Handle vulnerability resolutions in `DefaultResolutionProvider`

---

model/src/main/kotlin/config/HttpFileStorageConfiguration.kt

fix(HttpFileStorageConfiguration): Do not require configured `headers`

---

analyzer/src/funTest/assets/projects/synthetic/npm-expected-output-scope-excludes.yml
analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
analyzer/src/funTest/kotlin/managers/CocoaPodsFunTest.kt
analyzer/src/funTest/kotlin/managers/ConanFunTest.kt
analyzer/src/funTest/kotlin/managers/DotNetFunTest.kt
analyzer/src/funTest/kotlin/managers/GoDepFunTest.kt
analyzer/src/funTest/kotlin/managers/GoModFunTest.kt
analyzer/src/funTest/kotlin/managers/MavenFunTest.kt
analyzer/src/funTest/kotlin/managers/NpmFunTest.kt
plugins/package-managers/python/src/funTest/kotlin/PipFunTest.kt
plugins/package-managers/python/src/funTest/kotlin/PipenvFunTest.kt
plugins/package-managers/python/src/funTest/kotlin/PoetryFunTest.kt
utils/test/src/main/kotlin/Utils.kt

tests: Continue moving to `patchExpectedResult2()`

---

analyzer/src/funTest/assets/projects/synthetic/glide-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/godep-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/godeps-expected-output.yml
analyzer/src/funTest/kotlin/managers/GoDepFunTest.kt
analyzer/src/funTest/kotlin/managers/NpmFunTest.kt
analyzer/src/funTest/kotlin/managers/NpmVersionUrlFunTest.kt
analyzer/src/funTest/kotlin/managers/NuGetFunTest.kt
analyzer/src/funTest/kotlin/managers/PnpmFunTest.kt
analyzer/src/funTest/kotlin/managers/SbtFunTest.kt
analyzer/src/funTest/kotlin/managers/SpdxDocumentFileFunTest.kt
analyzer/src/funTest/kotlin/managers/Yarn2FunTest.kt
analyzer/src/funTest/kotlin/managers/YarnFunTest.kt
analyzer/src/testFixtures/kotlin/Extensions.kt
cli/src/funTest/assets/git-repo-expected-output.yml
cli/src/funTest/kotlin/AnalyzerFunTest.kt
cli/src/funTest/kotlin/OrtMainFunTest.kt
plugins/package-managers/carthage/src/funTest/assets/projects/synthetic/carthage-expected-output.yml
plugins/package-managers/carthage/src/funTest/kotlin/CarthageFunTest.kt
plugins/package-managers/pub/src/funTest/kotlin/PubFunTest.kt

`GoDepFunTest` is still left as todo for a future PR.

Migrate remaining test code to `patchExpectedResult2()`

---

analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/testFixtures/kotlin/Extensions.kt
cli/src/funTest/kotlin/OrtMainFunTest.kt
cli/src/funTest/kotlin/PackageManagerFunTest.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
helper-cli/src/main/kotlin/utils/Extensions.kt

Use that property in places where `PackageManager.All.values` was accessed directly as otherwise some tests would start failing as soon as the first package manager is introduced that is disabled by default.

refactor: Introduce a lazy `PackageManager.ENABLED_BY_DEFAULT` property

---

reporter/src/main/kotlin/reporters/freemarker/asciidoc/AsciiDocTemplateReporter.kt
reporter/src/main/kotlin/reporters/freemarker/asciidoc/PdfTemplateReporter.kt

Also shorten some variable names as these are not full attributes but only their values, and use `toString()` instead of `path` to better express that a string is needed here (although both calls internally do the same thing).

refactor(PdfTemplateReporter): Make setting attribute values more compact

---

analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/resources/META-INF/services/org.ossreviewtoolkit.analyzer.PackageManagerFactory
cli/src/funTest/kotlin/PackageManagerFunTest.kt
plugins/package-managers/build.gradle.kts
plugins/package-managers/unmanaged/build.gradle.kts
plugins/package-managers/unmanaged/src/main/kotlin/Unmanaged.kt
plugins/package-managers/unmanaged/src/main/resources/META-INF/services/org.ossreviewtoolkit.analyzer.PackageManagerFactory
settings.gradle.kts

Move the Unmanaged package manager to its own plugin project

---

advisor/src/main/kotlin/advisors/VulnerableCode.kt
advisor/src/test/assets/__files/vulnerable-code/response_invalid_uri.json
advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt

There are some packages for which VulnerableCode returns vulnerabilities with URL references that cannot be converted to URIs, since they contain invalid characters. In such cases, no meaningful advisor result was generated. Prevent this by handling exceptions when converting to URIs.

fix(VulnerableCode): Handle invalid URLs in references

---

plugins/package-managers/gradle-plugin/src/main/kotlin/GradleModelExtensions.kt
plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt

Let `GradleInspector` filter all dependencies metadata configurations

---

reporter/src/main/kotlin/reporters/spdx/SpdxDocumentModelMapper.kt

fix(reporter): Filter SPDX `licenseInfoFromFiles` for valid entries

---

model/src/main/kotlin/Mappers.kt

The previous style with the private variables was very condensed. As the variables are only use once, simply inline them to make more clear that all of this is only needed to construct a `YAMLMapper`.

refactor(model): Inline `YAMLFactory` and `LoaderOptions`

---

cli/src/funTest/assets/projects/synthetic/spdx-project-xyz-expected-output-subproject-conan.yml
plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan-expected-output-py.yml
plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml
plugins/package-managers/conan/src/main/kotlin/Conan.kt

fix(conan): Do not hard-code the VCS type to "Git"

---

reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
reporter/src/main/kotlin/reporters/spdx/SpdxDocumentModelMapper.kt

As a single SPDX package cannot capture the same amount of metadata as an
ORT package can, the `SpdxDocumentModelMapper` creates up to three SPDX
packages for a single ORT package: A binary package, a VCS source package,
and a source artifact package. The latter two copy all properties from the
binary package while adjusting esp. the `downloadLocation`. As part of
these adjustments, the licenses were reset to `NOASSERTION` until now.
However, that is inconsistent and misleading, as there has been an attempt
made to determine the declared license from metadata, and metadata is
usually stored in definition files along with the source code. Thus,
source packages should contain `licenseDeclared` from the binary package
at least as a subset.
Note that detected licenses, if any, would go into …

fix(SpdxDocumentModelMapper): Only reset concluded licenses for sources

---

analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
cli/src/funTest/kotlin/ExamplesFunTest.kt
cli/src/main/kotlin/commands/AdvisorCommand.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
cli/src/main/kotlin/commands/ScannerCommand.kt
examples/notifications/src/main/resources/example.notifications.kts
helper-cli/src/main/kotlin/commands/ListPackagesCommand.kt
helper-cli/src/main/kotlin/commands/repoconfig/RemoveEntriesCommand.kt
helper-cli/src/main/kotlin/utils/Extensions.kt
model/src/main/kotlin/AdvisorRecord.kt
model/src/main/kotlin/AnalyzerResult.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/ScannerRun.kt
model/src/main/kotlin/utils/OrtResultExtensions.kt
model/src/test/kotlin/AdvisorRecordTest.kt
model/src/test/kotlin/OrtResultTest.kt
plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
reporter/src/main/kotlin/StatisticsCalculator.kt
reporter/src/main/kotlin/reporters/freemarker/FreemarkerTemplateProcessor.kt

Rename several `collect...` functions to `get...` and do some minor refactorings. See the commit messages for details.
**Breaking API change**:
Several `OrtResult` functions have changed their name.

`OrtResult` function renamings

---

docs/reporters/asciidoc-templates.md

docs(reporters): Remove the link to the XHTML AsciiDoc backend

---

plugins/package-curation-providers/clearly-defined/src/main/kotlin/ClearlyDefinedPackageCurationProvider.kt

The custom comment was used as a work-around to document the provider the curation is coming from. But now that the resolved configuration contains the provider explicitly, this is not needed anymore.

chore(clearly-defined): Remove ORT's comment from curations

---

.reuse/dep5
reporter-web-app/package.json

Clean up Copyright statements

---

cli/src/main/kotlin/commands/AnalyzerCommand.kt

This is useful to quickly check which package managers a code base is using. Also make the preceding status message a bit more useful in that context.

feat(cli): Add a dry run option to the analyzer command

---

plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt

This aligns with the current `Gradle` behavior.

fix(gradle-plugin): Treat unresolved dependencies as errors

---

model/src/main/kotlin/DependencyGraph.kt

Align the default values of the `createScopes()` functions. In the dependency tree representation usually scopes names are unqualified.

refactor(model)!: Unqualify scope names by default

---

integrations/jenkins/Jenkinsfile

Do not create `NOTICE_SUMMARY` as `NOTICE_DEFAULT` should be enough, but create the PDF report(s) to demonstrate theming.

build(Jenkinsfile): Adjust the generated report types

---

analyzer/src/main/kotlin/managers/GoDep.kt
plugins/package-managers/bundler/src/main/kotlin/Bundler.kt
plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt

Disregard empty URIs when creating VCS info. This deals with a change in SnakeYaml 2.0 (used by Jackson 2.15) that deserializes YAML maps with missing values as empty values instead of previously null values.

fix(bundler): Make GemSpec parsing more robust

---

model/src/test/kotlin/PackageCurationTest.kt

While this is not mentioned in the spec [1], it makes sense to match four digit versions to three digit version ranges.
[1]: https://ant.apache.org/ivy/history/2.1.0/settings/version-matchers.html

test(PackageCurationTest): Add test for 4-digit version range applicability

---

plugins/package-managers/gradle-inspector/README.md

These issues have been resolved meanwhile, see e.g. [1] and [2].
[1]: https://github.com/oss-review-toolkit/ort/pull/6845
[2]: https://github.com/oss-review-toolkit/ort/pull/6896

docs(gradle-inspector): Remove the section about build issues

---

scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt

The underlying `PackageProvenanceResolver` already uses the same prefix for the message, leading to duplications like
Could not resolve provenance for package '...': IOException: Could not
resolve provenance for '...' for source code origins [VCS, ARTIFACT].
Simplify that by omitting the first sentence.

refactor(scanner): Simplify the message for provenance issues

---

cli/src/funTest/kotlin/PackageManagerFunTest.kt

This fixes a test flakiness and aligns with the assertions for other package managers.

test(cli): Ignore the order in found NuGet definition files

---

scanner/src/funTest/assets/dummy-expected-output-for-analyzer-result.yml

test(scanner): Fix an expected result

---

cli/build.gradle.kts
examples/notifications/build.gradle.kts
helper-cli/build.gradle.kts

These comments have not been used consistently (on the first exclusive repository entry), and the Gradle behavior (which is not going to change) is known by now, so just remove the comment.

docs(Gradle): Remove the comments about repeated repository declarations

---

cli/build.gradle.kts
cli/src/main/kotlin/OrtMain.kt
cli/src/main/kotlin/commands/AnalyzerCommand.kt
cli/src/main/kotlin/commands/DownloaderCommand.kt
cli/src/main/kotlin/commands/EvaluatorCommand.kt
cli/src/main/kotlin/commands/NotifierCommand.kt
cli/src/main/kotlin/commands/ReporterCommand.kt
cli/src/main/kotlin/commands/RequirementsCommand.kt
cli/src/main/kotlin/commands/ScannerCommand.kt
cli/src/main/kotlin/commands/UploadCurationsCommand.kt
cli/src/main/kotlin/commands/UploadResultToPostgresCommand.kt
cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
plugins/commands/advisor/build.gradle.kts
plugins/commands/advisor/src/main/kotlin/AdvisorCommand.kt
plugins/commands/api/src/main/kotlin/utils/Extensions.kt

Avoid the logger implementation to become part of the API by aligning with remaining code that uses a non-public companion object to make use of logging.

refactor(cli): Do not expose the logger as a public property

---

plugins/package-managers/nuget/src/main/kotlin/NuGet.kt
plugins/package-managers/nuget/src/main/kotlin/utils/NuGetInspector.kt

This is useful if multiple NuGet projects share a global configuration that is stored outside of the project directories.

feat(nuget-package-manager): Support absolute `nuget.config` files

---

utils/common/src/main/kotlin/Utils.kt

Part of #6943, e.g. files under `VCS_DIRECTORIES` will be excluded from the file listings.

utils: Improve the listing of VCS directories

---

advisor/src/main/kotlin/advisors/Osv.kt

The optional PURL is recommended to be specified if known, see [1].
[1]: https://ossf.github.io/osv-schema/#affectedpackage-field

feat(Osv): Also pass the PURL if known

---

integrations/schemas/ort-configuration-schema.json
model/src/main/kotlin/config/FileListingStorageConfiguration.kt
model/src/main/kotlin/config/ScannerConfiguration.kt
model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
scanner/src/main/kotlin/FileListing.kt
scanner/src/main/kotlin/ScanController.kt
scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/provenance/ProvenanceDownloader.kt
scanner/src/main/kotlin/utils/FileListingResolver.kt
scanner/src/test/assets/expected-file-listing.yml
scanner/src/test/kotlin/utils/FileListingResolverTest.kt

Create and store the file listings `(path, sha1)` for each resolved provenance. 
These can be consumed in future iterations (see #6945) for improving the generated SBOMs.
Resolves: #6943.
I've scanned the HEAD of the main branch of npm mime-types which resolved to 335 provenances. The total size of all file listings in the Postgres database is 5605372 bytes. So, about 16.4kb per file listing in average.
BREAKING CHANGE: One does not have to, but should configure a storage backend in `~/.ort/config/config.yml`.
If one doesn't do so, ORT falls back to storing the file listings under `~/.ort` which may not be
desired. See the modified `reference.yml` for how the new configuration feature looks like.

scanner: Create and store file listings for each resolved provenance

---

cli/src/main/kotlin/commands/AnalyzerCommand.kt

Previously, enabled package managers were determined based only on the global configuration.

fix(AnalyzerCommand): Regard package manager configuration from `.ort.yml`

---

build.gradle.kts
gradle/libs.versions.toml

The official "dokka" plugin keeps having Gradle related issues, in
particular out of memory issues. Switch to the unofficial "dokkatoo"
successor [1] to resolve these issues. For simplicity, drop the
dokka-related external link configuration; it needs to be revisited if
and how this needs to be configured with dokkatoo, too. Also generalize
the names of the wrapper tasks to not explicitly mention "dokka"
anymore.
With dokkatoo, run e.g.
./gradlew dokkatooGeneratePublicationHtml
to generate HTML documentation files, or run
./gradlew docsHtmlJar
to bundle all HTML documentation into a JAR.
[1]: https://github.com/adamko-dev/dokkatoo

build(Gradle): Switch from the "dokka" to the "dokkatoo" plugin

---

advisor/src/funTest/assets/retrieve-package-findings-expected-result.json
advisor/src/funTest/kotlin/OsvFunTest.kt
advisor/src/main/kotlin/AdviceProvider.kt
advisor/src/main/kotlin/Advisor.kt
advisor/src/main/kotlin/advisors/GitHubDefects.kt
advisor/src/main/kotlin/advisors/NexusIq.kt
advisor/src/main/kotlin/advisors/OssIndex.kt
advisor/src/main/kotlin/advisors/Osv.kt
advisor/src/main/kotlin/advisors/VulnerableCode.kt
advisor/src/test/kotlin/AdvisorTest.kt
advisor/src/test/kotlin/advisors/GitHubDefectsTest.kt
advisor/src/test/kotlin/advisors/OssIndexTest.kt
advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt

Please have a look at the individual commit messages for the details. 
> **Note**
> This is a breaking change for advisor API users / implementors of advisor plugins as the return value of `retrievePackageFindings()` changes.

Simplify `retrievePackageFindings()`'s return value

---

model/src/main/kotlin/ScannerRun.kt
reporter/src/main/kotlin/Statistics.kt
reporter/src/main/kotlin/StatisticsCalculator.kt
scanner/src/main/kotlin/Scanner.kt

Statistics / ScannerRun: Do not use sorted data structures

---

.jitpack.yml

In https://github.com/oss-review-toolkit/ort/pull/6993, the Dokka task has been replaced by `dokkatoo`. Hence the Jitpack configuration must be adapted.
Example of failing Jitpack build:
https://jitpack.io/com/github/oss-review-toolkit/ort/48888c6b17/build.log

build(jitpack): Change the excluded Dokka task name

---

.jitpack.yml

Exclude the `dokkatooGeneratePublicationJavadoc` task which `docsJavadocJar` depends on instead to fix a build error.

build(JitPack): Fix the docs task exclusion

---

model/src/main/kotlin/licenses/LicenseClassifications.kt

Using an (immutable) sorted set is not necessary.

refactor(LicenseClassifications): Turn `categoryNames` into a `Set`

---

advisor/src/main/kotlin/Advisor.kt
evaluator/src/test/kotlin/TestData.kt
model/src/main/kotlin/AdvisorRecord.kt
model/src/test/kotlin/AdvisorRecordTest.kt
plugins/reporters/freemarker/src/test/kotlin/FreeMarkerTemplateProcessorTest.kt
reporter/src/testFixtures/kotlin/TestData.kt

Part of https://github.com/oss-review-toolkit/ort/issues/6235 .

Do not use a sorted map in `AdvisorRecord`

---

plugins/reporters/opossum/src/main/kotlin/OpossumReporter.kt
utils/ort/src/main/kotlin/OrtProxySelector.kt
utils/ort/src/test/kotlin/OrtProxySelectorTest.kt

Adhere to Java naming conventions and do not upper-case "URL" as part of function names.

refactor!: Use camel-case for URLs in function names

---

analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
model/src/main/kotlin/Scope.kt
model/src/main/kotlin/utils/SortedSetConverters.kt

Stop `Scope` to implement `Comparable`

---

plugins/package-managers/gradle-plugin/src/main/kotlin/MavenModelExtensions.kt

As a somewhat related remark, also see [1] for another Kotlin vs Java serialization issue (that ORT is not currently affected by).
[1]: https://blog.stylingandroid.com/kotlin-serializable-objects/

docs(gradle-plugin): Improve the comment about set serialization

---

plugins/package-managers/gradle-inspector/build.gradle.kts
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-android-cyclic-expected-output-app.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-android-expected-output-app.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-android-expected-output-lib.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-android-expected-output-root.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-bom-expected-output.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-composite-expected-output.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-expected-output-app-2.14.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-expected-output-app-3.4.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-expected-output-app.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-expected-output-lib.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-expected-output-root.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-expected-output-scopes-excludes.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-expected-output-unsupported-version.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-library-expected-output-app.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-library-expected-output-lib.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-library-expected-output-root.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/multi-kotlin-project-expected-output-cli.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/multi-kotlin-project-expected-output-core.yml
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/multi-kotlin-project-expected-output-root.yml
plugins/package-managers/gradle-inspector/src/funTest/kotlin/Extensions.kt
plugins/package-managers/gradle-inspector/src/funTest/kotlin/GradleAndroidFunTest.kt
plugins/package-managers/gradle-inspector/src/funTest/kotlin/GradleBomFunTest.kt
plugins/package-managers/gradle-inspector/src/funTest/kotlin/GradleCompositeFunTest.kt
plugins/package-managers/gradle-inspector/src/funTest/kotlin/GradleFunTest.kt
plugins/package-managers/gradle-inspector/src/funTest/kotlin/GradleKotlinScriptFunTest.kt
plugins/package-managers/gradle-inspector/src/funTest/kotlin/GradleLibraryFunTest.kt

Add functional tests for the GradleInspector

---

plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
utils/common/src/main/kotlin/Extensions.kt
utils/common/src/test/kotlin/ExtensionsTest.kt

Some projects like [1] use JVM arguments that are deprecated. For example, `MaxPermSize` has been deprecated since Java 1.8, but the project still uses it despite targeting Java 11 [2]. As the Gradle Tooling API would fail to launch in such cases, replace `MaxPermSize` with its successor `MaxMetaspaceSize`.
Note that while by default the Gradle Tooling API "will use the JVM and JVM arguments that the target build is configured to use" [3], both `setJvmArguments()` and `addJvmArguments()` override that default [4]. So in order to modify the JVM arguments configured for a project, they need to be read and changed manually.
[1]: https://github.com/vector-im/element-android/blob/591b08f/gradle.properties#L11
[2]: https://github.com/vector-im/element-android/blob/591b08f/dependencies.gradle#L5- …

feat(gradle-inspector): Replace deprecated JVM arguments for projects

---

clients/fossid-webapp/src/main/kotlin/model/result/Snippet.kt
clients/fossid-webapp/src/test/assets/return-type/mappings/apiphp-list_scan_ignored_snippets.json
clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
scanner/src/main/kotlin/scanners/fossid/FossId.kt

Today, FossID has returned me the following snippet:
```
"223": {
"id": "223",
"created": "2023-05-24 14:09:29",
"scan_id": "0",
"scan_file_id": "25435949",
"file_id": "8269975",
"match_type": "ignored",
"reason": "file not found",
"author": null,
"artifact": null,
"version": null,
"purl": null,
"artifact_license": null,
"artifact_license_category": null,
"release_date": null,
"mirror": null,
"file": "",
"file_license": null,
"url": null,
"hits": null,
"size": "0",
"updated": "2023-05-24 14:09:29",
"cpe": null,
"score": "",
"match_file_id": null,
"classification": "null",
"highlighting": "null"
},
```
This pull request adapts ORT to support such snippets.

fix(fossid-webapp): Make some Snippet properties nullable 

---

README.md

Since writing the Development section in the README, the IntelliJ UI for importing a project has changed, especially in the welcome dialog, which is what new IntelliJ users see first.
This MR aims to address these changes, in order to make it easier for new developers to contribute to ORT, and also attempt to make the instructions more legible.
Signed-off-by: Jens Keim <jens.keim@forvia.com>

Readme: Update IntelliJ import instructions

---

model/src/main/kotlin/Identifier.kt
model/src/main/kotlin/TextLocation.kt

At least for these classes, no risk is imposed by implementing `Comparable` and putting instances in sorted collections.

docs: Comment which comparators are in line with `equals()`

---

model/src/main/kotlin/config/FileListStorageConfiguration.kt

This is a fix-up for 92acfc8ae730693f86e88612e524997024b3faa5.
BREAKING CHANGE: It still works if you don't do anything. However, if you want to re-use your existing table entries, then just rename your database table accordingly.

fix(FileListStorageConfiguration): Fix-up the database table name

---

advisor/src/test/assets/ort-analyzer-result.yml
analyzer/src/funTest/assets/projects/external/sbt-multi-project-example-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template-expected-output.yml
analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
cli/src/funTest/assets/git-repo-expected-output.yml
cli/src/funTest/assets/gradle-all-dependencies-expected-result-with-curations.yml
cli/src/funTest/assets/projects/synthetic/spdx-project-xyz-expected-output-subproject-conan.yml
cli/src/funTest/assets/semver4j-ort-result.yml
model/src/main/kotlin/AdvisorRecord.kt
model/src/main/kotlin/AnalyzerResult.kt
model/src/main/kotlin/PackageReference.kt
model/src/main/kotlin/ScannerRun.kt
model/src/test/assets/analyzer-result-with-dependency-graph.yml
model/src/test/assets/gradle-all-dependencies-expected-result.yml
model/src/test/assets/result-with-issues-graph-old.yml
model/src/test/assets/result-with-issues-graph.yml
model/src/test/assets/result-with-issues-scopes.yml
model/src/test/assets/sbt-multi-project-example-graph-old.yml
model/src/test/assets/sbt-multi-project-example-graph.yml
model/src/test/kotlin/AdvisorRecordTest.kt
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm-workspaces-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2-workspaces-expected-output.yml
plugins/package-managers/pub/src/funTest/assets/projects/synthetic/pub-expected-output-multi-module.yml
plugins/package-managers/pub/src/funTest/assets/projects/synthetic/pub-expected-output-with-flutter-android-and-cocoapods.yml
plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml
plugins/reporters/opossum/src/funTest/assets/reporter-test-input.yml
plugins/reporters/static-html/src/funTest/assets/reporter-test-input.yml
plugins/reporters/web-app/src/funTest/assets/dummy-expected-output-for-analyzer-result.yml
scanner/src/funTest/assets/analyzer-result.yml
scanner/src/funTest/assets/dummy-expected-output-for-analyzer-result.yml

Besides removing redundancy, this prepares for introducing logic inside `OrtResult` on which `hasIssues()` would need to depend on, which is not possible, because the `*Run` classes do not have access to the enclosing `OrtResult` instance.
Context: #5950.

OrtResult: Remove several serialized `has_issues` properties

---

utils/spdx/src/main/kotlin/model/SpdxFile.kt

According to the SPDX 2.3 specification [1] the field `licenseInfoInFiles` is not mandatory, but should default to `NOASSERTION`. While the SPDX 2.2 specification does not mention the default value, the field is also optional in this version [2].
[1]: https://github.com/spdx/spdx-spec/blob/5c893ae8010d5d972ecdf1af953a95d9f53de415/schemas/spdx-schema.json#L561-L574
[2]: https://github.com/spdx/spdx-spec/blob/2dffb51097904e03d5e9b19782e9d1b5cd7c9682/schemas/spdx-schema.json#L453-L459

fix(SpdxFile): Default `licenseInfoInFiles` to `NOASSERTION`

---

scanner/src/main/kotlin/provenance/NestedProvenanceScanResult.kt

The logic contained within the `merge()` function will be needed when `OrtResult`s internal representation is changed to store the results by provenance. It is supposed to be used to `map` the internal representation back to the current one.
Part of: #5950.

Make the logic within `NestedProvenanceScanResult.merge()` re-usable

---

model/src/main/kotlin/HashAlgorithm.kt
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
plugins/reporters/spdx/src/funTest/kotlin/SpdxDocumentReporterFunTest.kt
plugins/reporters/spdx/src/main/kotlin/Extensions.kt
plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
utils/spdx/src/main/kotlin/Extensions.kt
utils/spdx/src/main/kotlin/model/SpdxPackage.kt

See [1] for the background discussion.
[1]: https://github.com/oss-review-toolkit/ort/discussions/7064

Write out checksums for SPDX binary / source packages

---

scanner/src/main/kotlin/ScanController.kt
scanner/src/main/kotlin/Scanner.kt

ScanController: Stop mixing provenance resolution issues of different type

---

build.gradle.kts

This is a fixup for c903fbf to allow more packages to be accessible at runtime via reflection. While at it, slightly align the argument syntax to other similar code.

fix(Gradle): Avoid a JVM >= 17 warning when running tests

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/ConvertOrtFileCommand.kt
helper-cli/src/main/kotlin/commands/DownloadResultsFromPostgresCommand.kt
helper-cli/src/main/kotlin/commands/ExtractRepositoryConfigurationCommand.kt
helper-cli/src/main/kotlin/commands/GetPackageLicensesCommand.kt
helper-cli/src/main/kotlin/commands/ListLicenseCategoriesCommand.kt
helper-cli/src/main/kotlin/commands/ListPackagesCommand.kt
helper-cli/src/main/kotlin/commands/SetDependencyRepresentationCommand.kt
helper-cli/src/main/kotlin/commands/TransformResultCommand.kt
helper-cli/src/main/kotlin/commands/classifications/LicenseClassificationsCommand.kt
helper-cli/src/main/kotlin/commands/dev/DevCommand.kt
helper-cli/src/main/kotlin/commands/dev/RewriteTestAssetsCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/ExportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/ImportLicenseFindingCurationsCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/ImportPathExcludesCommand.kt
helper-cli/src/main/kotlin/commands/packagecuration/SetCommand.kt
helper-cli/src/main/kotlin/commands/repoconfig/RepositoryConfigurationCommand.kt
helper-cli/src/main/kotlin/commands/scanstorage/ScanStorageCommand.kt

This can be helpful for development.

feat(helper-cli): Add a command to re-serialize the test assets

---

scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
scanner/src/test/kotlin/scanners/fossid/FossIdLicenseMappingTest.kt
utils/ort/src/main/kotlin/DeclaredLicenseProcessor.kt

Currently, the mapping of licenses from FossID identified / "marked as
identified" files and from FossID's snippets fails if the license cannot
be mapped to SPDX, for instance 'Apache 2.0'.
In this case, the FossID scanner creates issues in the scan results.
This commit changes the logic to use the `DeclaredLicenseProcessor` to
map these licenses to syntactically correct SPDX expressions. It also
adds a unit test to cover this part of the code that was previously
uncovered.
Please note that mapping of non-mappable license from identified /
"marked as identified" files still leads to the creation of an issue.
However, fewer issues should be now created with the new logic.

fix(fossid-webapp): Fix FossID license mapping 

---

model/src/main/kotlin/utils/ScanResultUtils.kt
model/src/test/kotlin/licenses/TestData.kt
scanner/src/main/kotlin/provenance/NestedProvenanceScanResult.kt
utils/test/src/main/kotlin/Utils.kt

Some further smaller preparations and fixes for storing scan results "by provenance" in `OrtResult`.
Please see the individual commits.
Part of: #5950.

Minor scanner improvements

---

helper-cli/src/main/kotlin/commands/SetDependencyRepresentationCommand.kt
plugins/commands/build.gradle.kts
plugins/commands/compare/build.gradle.kts
plugins/commands/compare/src/main/kotlin/CompareCommand.kt
plugins/commands/compare/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
plugins/commands/config/src/main/kotlin/ConfigCommand.kt
plugins/commands/upload-curations/src/main/kotlin/UploadCurationsCommand.kt
settings.gradle.kts
utils/common/src/main/kotlin/Utils.kt

Compare command

---

scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
scanner/src/test/kotlin/scanners/fossid/FossIdLicenseMappingTest.kt

With the introduction of snippet findings in the scan results, some
issues are also present in the result because licenses from FossID
snippets cannot always be mapped to SPDX, for instance "RETURNN license"
or "Apache 2-0".
While the usage of the declared license mapping file helped to
alleviate some of these issues, several remained, polluting the webapp
report.
Opening a support ticket at FossID to have them correct the license,
while being the correct solution, does not scale regarding the amount of
licenses to correct.
Therefore, this commit lowers for now the severity of these issues to
`HINT` and map them to `NO_ASSERTION`. This is a temporary solution
until a snippet curation mechanism is introduced to be able to correct
those licenses.
FYI @MarcelBochtler.

fix(fossid-webapp): Set severity to HINT when snippet license cannot be mapped

---

plugins/commands/downloader/src/main/kotlin/DownloaderCommand.kt

The downloader can be configured to just download the sources of specified license categories.
Prefer the concluded license if one exists, when deciding if a package should be downloaded.

fix(Downloader): Prefer license category of concluded license

---

utils/spdx/build.gradle.kts

This fixup for 6a73769 addresses the error [1]:
Reason: Task ':utils:spdx-utils:compileTestKotlin' uses this output of
task ':utils:spdx-utils:generateTestGrammarSource' without declaring
an explicit or implicit dependency. This can lead to incorrect results
being produced, depending on what order the tasks are executed.
[1]: https://github.com/oss-review-toolkit/ort/actions/runs/5288598268/jobs/9570557290#step:4:5223

build(Gradle): Extend the ANTLR work-around to all source sets

---

model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt

Add the missing `commandLineNonConfig` option for ScanCode to the reference.yml and explain the difference to the `commandLine` option.

docs(model): Add ScanCode `commandLineNonConfig` to reference.yml

---

scanner/src/main/kotlin/ScanContext.kt
scanner/src/main/kotlin/Scanner.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt

In a future commit, the FossID scanner will use the `Excludes` contained in the configuration to generate ignore rules for the scan.

feat(scanner): Expose the Excludes to the scanner 

---

model/src/funTest/kotlin/utils/PostgresProvenanceFileStorageFunTest.kt
model/src/main/kotlin/utils/FileArchiver.kt
model/src/main/kotlin/utils/FileProvenanceFileStorage.kt
model/src/main/kotlin/utils/PostgresProvenanceFileStorage.kt
model/src/main/kotlin/utils/ProvenanceFileStorage.kt
scanner/src/main/kotlin/utils/FileListResolver.kt
utils/common/src/main/kotlin/ArchiveUtils.kt
utils/common/src/test/kotlin/ArchiveUtilsTest.kt

Improvements to archive handling and storages

---

downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt

Make the test resilient with regard to newly added remote branches by
only asserting that all expected branches are amongst the returned
branches.

test(downloader): Make `GitWorkingTreeFunTest` less flaky

---

cli/src/funTest/assets/semver4j-ort-result.yml
model/src/main/kotlin/AdvisorRecord.kt
model/src/main/kotlin/AnalyzerResult.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/ProvenanceResolutionResult.kt
model/src/main/kotlin/ScannerRun.kt
model/src/main/kotlin/utils/Extensions.kt
model/src/main/kotlin/utils/SortedSetConverters.kt
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml
plugins/reporters/opossum/src/funTest/assets/reporter-test-input.yml
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
plugins/reporters/static-html/src/funTest/assets/reporter-test-input.yml
plugins/reporters/web-app/src/funTest/assets/dummy-expected-output-for-analyzer-result.yml
scanner/src/funTest/assets/dummy-expected-output-for-analyzer-result.yml
scanner/src/funTest/assets/dummy-expected-scan-results-for-analyzer-result.yml
scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
scanner/src/main/kotlin/ScanController.kt
scanner/src/main/kotlin/Scanner.kt
scanner/src/test/kotlin/ScannerTest.kt
utils/test/src/main/kotlin/Utils.kt

This PR changes `OrtResult`s internal representation to store scan results by provenance, which eliminates redundancies in case multiple packages share the same provenance. It keeps `OrtResults` API _as-is_. That is, client code using `OrtResult.getScanResults()` or `OrtResult.getScanResults(id)` remains _as-is_, thereby hiding the complexities of the new internal representation completely. Also, information about the sub-repository structure is now available for all packages in `OrtResult`.
**Breaking change:** 
1. "old" ORT files containing a `ScannerRun` won't de-serialize anymore.
2. The scanner cannot output package verification codes anymore. This will be fixed again, by computing
these codes on-the-fly from file lists which are not present yet but will be added soon.
Fixes #5950.

OrtResult: Store scan results "by provenance"

---

build.gradle.kts
cli/src/main/resources/logback.xml
helper-cli/src/main/resources/logback.xml
plugins/reporters/fossid/build.gradle.kts
plugins/reporters/fossid/src/main/kotlin/FossIdSnippetReporter.kt
plugins/reporters/fossid/src/main/resources/META-INF/services/org.ossreviewtoolkit.reporter.Reporter
plugins/reporters/fossid/src/main/resources/templates/asciidoc/fossid_snippet.ftl
plugins/reporters/fossid/src/main/resources/templates/freemarker_implicit.ftl
plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt

Example report (with how-to-fix hints):
[AsciiDoc_fossid_snippets.zip](https://github.com/oss-review-toolkit/ort/files/11742794/AsciiDoc_fossid_snippets.zip)

feat(reporter): Implement the FossID snippet reporter

---

scanner/src/main/kotlin/scanners/fossid/FossId.kt
scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
scanner/src/main/kotlin/scanners/fossid/Utils.kt
scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
scanner/src/test/kotlin/scanners/fossid/LegacyRulesTest.kt
scanner/src/test/kotlin/scanners/fossid/MapIgnoreRulesTest.kt

Currently, the ignore rules are carried over from the last successful delta
scan. Since this process can lead to loss of rules when a new branch is
scanned, and to promote "configuration as code", this commit changes the
logic to create the ignore rules from the path excludes present in the
.ort.yml file.
ORT excludes path patterns is based on [1] and FossID supports only a
subset of it. Hence, this commit adds the mapping of this subset to the
FossID scanner. If a path exclude cannot be mapped to an ignore rule, an
issue is added to the scan summary.
Since it is not expected for the user to have already an .ort.yml
configured with path excludes, the rules of the last successful delta scan
are still carried over but, for each rule not existing as a path exclude,
an issue is also added to …

feat(fossid-webapp): Generate ignore rules from path excludes 

---

docs/hints-for-use-with-docker.md

By default the output is written inside the container.
See our [Slack conversation](https://ort-talk.slack.com/archives/C9NNJ54B1/p1686238330683709?thread_ts=1686195720.781609&cid=C9NNJ54B1).

Show how to route output to current directory

---

analyzer/src/main/kotlin/Extensions.kt
plugins/commands/analyzer/src/main/kotlin/AnalyzerCommand.kt

Move the function to determine the enabled package managers to the public API of the analyzer to make it available when programmatically using ORT.

refactor: Move a private CLI helper function to the public analyzer API

---

downloader/build.gradle.kts

The JGit upgrade in 115f241 excludes the `sshd-{core,common}` dependencies [1] in favor of keeping only the dependency on `sshd-osgi`. As svnkit also depends on `sshd-{core,common}`, this "sometimes" seems to cause JGit to use the wrong `sshd-common` dependency, namely svnkit's instead of its own [2]. Avoid that by aligning on the (newer) `sshd-common` that is included in JGit's `sshd-osgi` dependency.
Fixes #7177.
[1]: https://git.eclipse.org/r/c/jgit/jgit/+/201879/3/org.eclipse.jgit.ssh.apache/pom.xml
[2]: https://bugs.eclipse.org/bugs/show_bug.cgi?id=582109

build(downloader): Exclude `sshd-{core,common}` dependencies

---

plugins/reporters/ctrlx/src/main/kotlin/CtrlXAutomationModel.kt

Allow any syntactically correct license string. Resolves #7183.

feat(ctrlx-reporter): Be more lenient for SPDX expressions

---

plugins/commands/advisor/src/main/kotlin/AdvisorCommand.kt

Fix vulnerability count

---

model/src/main/kotlin/ScanSummary.kt

Snipped findings have recently been added to `ScanSummary`, but the `filter*()` functions have not been updated to also filter snippet findings. There seems to be no good reason why snippet findings shouldn't be filtered, so add the missing implementation.
Part of #7206.

fix(scanner): Consistently filter file findings in `ScanSummary`

---

Dockerfile

Arm64 are able to install scancode-toolkit-mini

fix(arm64): Use scancode-toolkit-mini for arm64 arch

---

advisor/src/main/kotlin/Advisor.kt
advisor/src/test/kotlin/AdvisorTest.kt

Previously, the code counted the number of distinct advisor results instead of the number of distinct vulnerabilities.

fix(advisor): Log the correct number of distinct vulnerabilities

---

gradle.properties
settings.gradle.kts

The property was introduced in ba8c2f1 to be able to configure a shorter cache retention time on CI. But with the switch to GitHub actions and 4fbcd31, caching is now anyway limited to a single build, also see [1].
[1]: https://github.com/gradle/gradle-build-action/issues/406#issuecomment-1612078906

build(Gradle): Remove the `buildCacheRetentionDays` logic

---

cli/src/funTest/assets/semver4j-ort-result.yml
model/src/main/kotlin/FileList.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/ScannerRun.kt
model/src/main/kotlin/utils/SortedSetConverters.kt
model/src/test/kotlin/ScannerRunTest.kt
plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml
plugins/reporters/opossum/src/funTest/assets/reporter-test-input.yml
plugins/reporters/static-html/src/funTest/assets/reporter-test-input.yml
plugins/reporters/web-app/src/funTest/assets/dummy-expected-output-for-analyzer-result.yml
scanner/src/funTest/assets/scanner-integration-all-pkgs-expected-ort-result.yml
scanner/src/funTest/assets/scanner-integration-expected-file-lists.yml
scanner/src/funTest/assets/scanner-integration-subset-pkgs-expected-ort-result.yml
scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
scanner/src/main/kotlin/ScanController.kt
scanner/src/main/kotlin/Scanner.kt
utils/test/src/main/kotlin/Utils.kt

The file lists are an enabler for
1. Computing SPDX package verification codes on-the-fly.
2. Adding file findings to SPDX reports
3. Several `helper-cli` automation opportunities like e.g. `PathExcludeGenerator`
Fixes: #6944.
**Breaking change:** `OrtResult` de-serialization is not backwards compatible.

OrtResult: Include file lists for all known provenances in `ScannerRun`

---

.github/workflows/static-analysis.yml

Since 32ee335 this is not limited to copyright and license header checks anymore.

build(GitHub): Give a job a better name

---

plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelMapper.kt
plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedScanResult.kt
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
plugins/reporters/spdx/src/main/kotlin/Extensions.kt
plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt

Compute the SPDX package verification code based on the file lists which have been added to `OrtResult` recently.
Fixes: #6948.

SpdxDocumentReporter: Compute SPDX verification codes on-the-fly

---

utils/spdx/src/main/kotlin/model/SpdxFile.kt
utils/spdx/src/main/kotlin/model/SpdxPackage.kt
utils/spdx/src/main/kotlin/model/SpdxSnippet.kt

As clarified in the 2.3 specs (see [1] vs. [2]), an absent `copyrightText` should be interpreted as `NOASSERTION`.
[1]: https://spdx.github.io/spdx-spec/v2.2.2/package-information/#717-copyright-text-field
[2]: https://github.com/spdx/spdx-spec/blob/development/v2.2/schemas/spdx-schema.json#L311

fix(spdx-utils): Make `copyrightText` default to `NOASSERTION`

---

scanner/src/main/kotlin/utils/FileListResolver.kt

Do not follow symbolic links to directories, because that leads to
undesired entries resulting from undesired duplicate traversal. Also,
ignore symbolic links to files, because the file it points to is
included already anyway if it is within the VCS or it is to be ignored
if it is not within.
Note: Programatically creating a symbolic link fails with [1] Operation
not permitted, which is why this commit does not have unit test
coverage.
[1] `Path.createSymbolicLinkPointingTo()`
Fixes: #7225.
**Important note:** Please delete existing file lists from your storage to make this change have effect also for
previously created file list.

fix(scanner): Ignore any symbolic links when creating file lists

---

plugins/scanners/askalono/src/main/kotlin/Askalono.kt
plugins/scanners/boyterlc/src/main/kotlin/BoyterLc.kt
plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
plugins/scanners/fossid/src/test/kotlin/FossIdLicenseMappingTest.kt
plugins/scanners/licensee/src/main/kotlin/Licensee.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOss.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOssResultParser.kt
plugins/scanners/scanoss/src/test/kotlin/ScanOssResultParserTest.kt
scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt

The `detectedLicenseMapping` is part of the global `ScannerConfiguration`, so also apply it globally on the `ScanSummary` returned by the scanners instead of leaving it to each scanner implementation to apply the mapping.

refactor(scanner): Apply the detected license mapping globally

---

detekt-rules/build.gradle.kts

Make the configuration refinement of the "jar" task compatible with Gradle's new configuration cache [1] by getting `StyledTextOutputFactory` via dependency injection.
[1]: https://docs.gradle.org/current/userguide/configuration_cache.html

build(Gradle): Make task configuration compatible with the cache

---

plugins/reporters/web-app-template/src/components/SummaryView.js

This allows on one hand the view to be more consistent, by always showing the same tab, and on the other hand allows to check resolved issues, even if there are no open issues left.
resolves #6232

feat(web-app-reporter): Always show issue tab

---

plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt

The FossId pending files were present in the scan result as issues with severity `HINT`. Now, the scan result contains the pending file's snippets.
However, counting the unique pending files having snippets is not an option since some pending files could have no snippet at all. Therefore, add a single issue with severity `HINT` with the count of pending files.
This is a breaking change.

fix(fossid-webapp): Remove issues for each pending file

---

model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt

Use `ResolvedCopyrightFinding` instead of just `CopyrightFinding` as type, to prepare for an upcoming change which needs to know for each of the entries whether it is excluded by any path exclude.
Part of #6947.

refactor(model): Change the type of unmatched copyrights

---

plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt
plugins/scanners/askalono/src/main/kotlin/Askalono.kt
plugins/scanners/boyterlc/src/main/kotlin/BoyterLc.kt
plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt
plugins/scanners/licensee/src/main/kotlin/Licensee.kt
plugins/scanners/scancode/src/test/kotlin/ScanCodeTest.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOss.kt
scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
scanner/src/main/kotlin/CommandLinePathScannerWrapper.kt
scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/ScannerWrapper.kt
scanner/src/test/kotlin/ScannerTest.kt

E.g. scan storages may need to access a CLI scanner's name without getting the version, which triggers running the local tool. This was not possible before as getting `ScannerDetails` contains the version. Solve that by storing the detail properties individually and constructing `ScannerDetails` only where needed.

refactor(scanner): Store scanner details in separate properties

---

helper-cli/src/main/kotlin/commands/classifications/ImportCommand.kt

The code introduced for the default value of `prefix` introduced by [1] is executed before the command line is parsed. So, the `provider` property is accessed before it is initialized. This cause an `InvalidStateException` each time `orthw` is executed. No matter which (sub-)command is run.
Revert [1] to fix this.
[1] ee63c878aa6cc6964d77eb862a723247f5002fe3.

fix(helper-cli): Stop failing with an `IllegalStateException`

---

model/src/main/kotlin/utils/Extensions.kt
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
plugins/reporters/spdx/src/funTest/kotlin/SpdxDocumentReporterFunTest.kt
plugins/reporters/spdx/src/main/kotlin/Extensions.kt
plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt
utils/spdx/src/main/kotlin/model/SpdxFile.kt

Extend the SPDX document reporter to include file information for
dependencies for all files which have at least one license or copyright
finding. Make the file information include the detected licenses,
copyright statements as well as the mandatory sha1 checksums.
Also an option to disable this feature, as it may not always be desired to include file information.
Fixes #6947.

SpdxDocumentReporter: Include file information for dependencies

---

cli/src/funTest/kotlin/OrtMainFunTest.kt
helper-cli/build.gradle.kts
helper-cli/src/main/kotlin/commands/GetPackageLicensesCommand.kt
helper-cli/src/main/kotlin/commands/ListCopyrightsCommand.kt
helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
model/src/main/kotlin/config/OrtConfiguration.kt
model/src/main/kotlin/config/ProviderPluginConfiguration.kt
model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
plugins/commands/evaluator/build.gradle.kts
plugins/commands/evaluator/src/main/kotlin/EvaluatorCommand.kt
plugins/commands/reporter/src/main/kotlin/ReporterCommand.kt
plugins/package-configuration-providers/api/build.gradle.kts
plugins/package-configuration-providers/api/src/main/kotlin/PackageConfigurationProviderFactory.kt
plugins/package-configuration-providers/api/src/main/kotlin/SimplePackageConfigurationProvider.kt
plugins/package-configuration-providers/api/src/test/kotlin/SimplePackageConfigurationProviderTest.kt
plugins/package-configuration-providers/build.gradle.kts
plugins/package-configuration-providers/dir/build.gradle.kts
plugins/package-configuration-providers/dir/src/main/kotlin/DirPackageConfigurationProvider.kt
plugins/package-configuration-providers/dir/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.packageconfigurationproviders.api.PackageConfigurationProviderFactory
plugins/package-curation-providers/api/src/main/kotlin/PackageCurationProviderFactory.kt

Move the package-configuration provider to a separate plugin.
This allows adding more providers through the plugin API, for instance adding the package-configurations from [ort-config](https://github.com/oss-review-toolkit/ort-config)

package-configuration provider plugin

---

plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt

Use the dedicated field for representing that a file corresponds to a package, instead of the more verbose generic relationship (in the SPDX Document report).
This fix-up corresponds to #6947.

fix(spdx): Fix-up representing the relationship of files and packages

---

cli/src/funTest/assets/semver4j-ort-result.yml
model/src/main/kotlin/ScannerRun.kt
model/src/main/kotlin/utils/SortedSetConverters.kt
plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml
plugins/reporters/opossum/src/funTest/assets/reporter-test-input.yml
plugins/reporters/static-html/src/funTest/assets/reporter-test-input.yml
plugins/reporters/web-app/src/funTest/assets/scan-result-for-synthetic-gradle-lib.yml
scanner/src/funTest/assets/scanner-integration-all-pkgs-expected-ort-result.yml
scanner/src/funTest/assets/scanner-integration-subset-pkgs-expected-ort-result.yml
scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt
scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
scanner/src/main/kotlin/Scanner.kt
utils/test/src/main/kotlin/Utils.kt

When a project scanner is configured alongside a package scanner, the scan results could be duplicated if the provenances of those packages are overlapping (e.g. in the case of repositories with Git submodules). This commit addresses the bug by constructing a map of packages with their scanners and filtering the scan results using this map.
Fixes #7231.
**Breaking change: OrtResult deserialization is not backwards compatible.**

fix(scanner): Filter scan results by scanner name

---

README.md
utils/test/src/main/kotlin/Matchers.kt

I tested the command with (the default) BSD `cut` and with GNU `cut`.

docs: Add instructions how to take over actual test results on macOS

---

scanner/src/main/kotlin/Scanner.kt

Move the `archiver` and `fileListStorage` to the constructor of the `Scanner` class. This makes it possible to provide alternative implementations when using ORT programmatically.

refactor(scanner): Move storages to the `Scanner` constructor

---

model/src/funTest/kotlin/utils/PostgresProvenanceFileStorageFunTest.kt
model/src/main/kotlin/utils/FileArchiver.kt
model/src/main/kotlin/utils/FileProvenanceFileStorage.kt
model/src/main/kotlin/utils/PostgresProvenanceFileStorage.kt
model/src/main/kotlin/utils/ProvenanceFileStorage.kt
scanner/src/main/kotlin/utils/FileListResolver.kt

Add a size argument to the `putData` function of the `ProvenanceFileStorage` which represents the size of the input stream to be written.
This is a precondition for being able to use the PostgreSQL large object storage as a backend for the storage [1] which is a requirement in the ongoing ORT Server development.
The current implementations of `ProvenanceFileStorage` do not require the size of the input stream, but the size is easily available for all callers of the `putData` function.
[1]: https://www.postgresql.org/docs/current/lo-interfaces.html

feat(model): Require size when writing to `ProvenanceFileStorage`

---

plugins/scanners/scancode/build.gradle.kts
plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
plugins/scanners/scancode/src/main/kotlin/ScanCodeErrorMappers.kt
plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModel.kt
plugins/scanners/scancode/src/main/kotlin/ScanCodeResultParser.kt
plugins/scanners/scancode/src/test/kotlin/ScanCodeResultParserTest.kt

Migrate the Scancode result parser to kotlinx-serialization

---

downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt
plugins/package-managers/pub/src/funTest/assets/projects/external/dart-http-expected-output.yml

The test now is not very meaningful anymore as only `main` is expected, but this is just a quick fix to make the test pass again as a more sophisticated test requires larger refactoring (probably by using a dedicated new repository).

test(downloader): Update `GitWorkingTreeFunTest` results

---

analyzer/build.gradle.kts
analyzer/src/funTest/kotlin/PackageManagerFunTest.kt

This is a better fit than the `cli` module as no dependency on the CLI is required. The needed dependency on all package manager plugins can be added as a `funTestImplementation` only.

refactor: Move the `PackageManagerFunTest` to the `analyzer` module

---

model/src/main/kotlin/ScanSummary.kt

When the SPDX expressions are mapped into a `MutableSet`, then `equals` gets called on each added SPDX expression instance. Equals in turn calls `validChoicesForDnf()` which is quite slow.
Turn the property into a lazy one, to remove the performance penalty from code paths which do not access that `licenses` property.

fix(ScanSummary): Turn `licenses` into a `lazy` initialized property

---

model/src/main/kotlin/utils/Extensions.kt
plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/dep-tree-expected-output.yml
plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/regular-expected-output.yml

According to the purl-spec and ossindex, the name of CocoaPods is "CocoaPods" not "Pod".
[1] https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#cocoapods
[2] https://ossindex.sonatype.org/ecosystem/cocoapods

fix(model): Use the correct PURL type for CocoaPods

---

model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt

Applying license choices is a slow operation, in particular `validChoices()` and `validChoicesForDnf()`. So, not executing the logic for applying the license choice in case the given flattened `licenseChoices` improves the performance quite a bit.
Furthermore, given some large SPDX expression the logic has been observed to execute for minutes at maximum CPU load eventually ending with a crash, for yet unknown reason. This change fixes that issue in case no license choice is given for the particular package.

fix(ResolvedLicenseInfo): Eliminate unneeded DNF computations

---

plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-expected-output-unsupported-version.yml
plugins/package-managers/gradle/src/funTest/assets/projects/synthetic/gradle-expected-output-unsupported-version.yml

The tests that use these files have been disabled for a while, and they were not deserializable anymore due to changes in the issues section. Fix these to make the files deserializable again.

test(Gradle): Fix expected results for disabled tests

---

plugins/package-managers/nuget/src/funTest/assets/nuget-expected-output.yml
plugins/package-managers/nuget/src/main/kotlin/utils/NuGetInspector.kt

If `nuget-inspector` returns an empty PURL, fall back to creating one using ORT's usual mechanism.

fix(nuget-inspector): Do not use empty PURLs

---

buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts

Newer Kotlin versions now have an enum for that [1].
[1]: https://kotlinlang.org/docs/gradle-compiler-options.html#types-for-compiler-options

refactor(Gradle): Stop hard-coding the maximum JVM target for Kotlin

---

README.md
utils/test/src/main/kotlin/Matchers.kt

The `patch`command is more powerful as it can apply patch "fuzzily" (see e.g. [1]). This enables applying patches whose diff context contains `<REPLACE_*` placeholders in the old expected result, but not in the actual / new expected result.
[1]: https://stackoverflow.com/q/6336440/1127485

docs(test): Use `patch` instead of `git apply` to update expected results

---

utils/spdx/src/main/resources/declared-license-mapping.yml

Found in [1].
[1]: https://repo.maven.apache.org/maven2/com/mysql/mysql-connector-j/8.0.32/mysql-connector-j-8.0.32.pom

Map 'GPL-2.0-only WITH Universal-FOSS-exception-1.0' 

---

plugins/reporters/ctrlx/src/main/kotlin/CtrlXAutomationModel.kt
plugins/reporters/ctrlx/src/test/kotlin/CtrlXAutomationModelTest.kt
utils/spdx/src/main/kotlin/Extensions.kt

Fix SPDX expression validation in the CtrlX Automation reporter, again

---

plugins/scanners/fossid/src/main/kotlin/Utils.kt
plugins/scanners/fossid/src/test/kotlin/MapIgnoreRulesTest.kt

Fix the FossID ignore rule creation for directories using a dot in the
name. While the regex is far from perfect [1], this fixes the very common
use case of ignoring `.git/` and `.idea/` directories.
[1]: For instance, `**/example/` is not added as directory ignore rule.

fix(FossId): Allow directories with dots to be added as ignore rules

---

helper-cli/src/main/kotlin/commands/classifications/FilterCommand.kt
helper-cli/src/main/kotlin/commands/classifications/LicenseClassificationsCommand.kt

This allows for merging only a subset of a classification file into another one, when used in combination with the already existing merge command.

feat(helper-cli): Add a command to filter license classifications

---

model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
plugins/scanners/scancode/src/main/kotlin/ScanCodeResultParser.kt

Remove the feature to toggle parsing of ScanCode license expressions. Starting with ScanCode output format version 3, license expressions are first class citizens in ScanCode results, making this feature cumbersome to maintain.
Note that the web-app report still would not show license expressions anyway (see issue #5017).
> **Note**
> This is a breaking change for the configuration as the `parseLicenseExpressions` option for ScanCode is being removed. Users that rely on `parseLicenseExpressions = false` for historic reasons might need to update license curations to properly use expressions.

refactor(scanner)!: Always parse ScanCode license expressions

---

cli/src/funTest/assets/gradle-all-dependencies-expected-result-with-curations.yml
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/ResolvedConfiguration.kt
model/src/main/kotlin/utils/ConfigurationResolver.kt

The `curations` property is supposed to contain the curations in the order they were provided by the package curation provider, therefore change the type from set to list to preserve the order.

refactor(model)!: Make curations a list in `ResolvedPackageCurations`

---

model/src/main/kotlin/utils/ClearlyDefinedUtils.kt
model/src/main/kotlin/utils/Extensions.kt
model/src/main/kotlin/utils/PurlUtils.kt
plugins/reporters/asciidoc/src/main/resources/templates/asciidoc/defect_report.ftl
plugins/reporters/asciidoc/src/main/resources/templates/asciidoc/disclosure_document.ftl
plugins/reporters/asciidoc/src/main/resources/templates/asciidoc/vulnerability_report.ftl

Please have a look at the individual commit messages for the details. 
> **Note**
> This is a breaking API change as FreeMarker templates may need to be adjusted as indicate din this PR if the `toPurl()` extension function is used.

Move ClearlyDefined and PURL coordinate mapping code to separate files

---

plugins/package-managers/spdx/src/main/kotlin/SpdxDocumentFile.kt
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
utils/spdx/src/main/kotlin/SpdxConstants.kt

SPDX creator tool adjustments

---

plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result-with-findings.json
plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result-without-findings.json
plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result.json
plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result.xml
plugins/reporters/cyclonedx/src/funTest/kotlin/CycloneDxReporterFunTest.kt
plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt
utils/spdx/src/main/kotlin/model/SpdxDocument.kt

Add CycloneDX metadata

---

utils/spdx/build.gradle.kts

`URL`'s `equals()` and `hashCode()` methods can perform a DNS lookup to resolve the host name, which may cause significant delays. So avoid using `URL` instances as keys in maps by using `URI` instances instead.

refactor(spdx-utils): Avoid storing URLs as keys in maps
