oss-review-toolkit/ort

- analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
- downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt
> GitWorkingTreeFunTest: Update expected results, again

- advisor/src/main/kotlin/Advisor.kt
- analyzer/src/main/kotlin/Analyzer.kt
- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- analyzer/src/test/kotlin/PackageManagerTest.kt
- cli/src/funTest/kotlin/OrtMainFunTest.kt
- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- helper-cli/src/main/kotlin/utils/Extensions.kt
- reporter/src/main/kotlin/Reporter.kt
- scanner/src/main/kotlin/ScannerWrapper.kt
> `ServiceLoader`-related improvements for the CLI commands

- cli/src/funTest/kotlin/OrtMainFunTest.kt
> Add tests for `Unmanaged`

- utils/ort/src/main/kotlin/CopyrightStatementsProcessor.kt
> Continued `CopyrightStatementsProcessor` improvements

- integrations/jenkins/Jenkinsfile
> Jenkins description sentences

- scanner/src/main/kotlin/ScanController.kt
> ScanController: Minor improvements

- ADOPTERS.md
As discussed today with @tsteenbe, we'd like to show that Deutsche Telekom is using ORT.
Please let me know if you need any changes to the description!
> Add Deutsche Telekom to ADOPTERS.md

- advisor/src/main/kotlin/AdviceProviderFactory.kt
- advisor/src/main/kotlin/advisors/GitHubDefects.kt
- advisor/src/main/kotlin/advisors/OssIndex.kt
- advisor/src/main/kotlin/advisors/Osv.kt
- advisor/src/main/kotlin/advisors/VulnerableCode.kt
- analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
- cli/src/main/kotlin/commands/UploadCurationsCommand.kt
- clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
- clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- clients/fossid-webapp/src/test/kotlin/FossId2021dot2Test.kt
- clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
- clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
- clients/fossid-webapp/src/test/kotlin/FossIdReportTest.kt
- clients/fossid-webapp/src/test/kotlin/FossIdRulesTest.kt
- clients/oss-index/src/main/kotlin/OssIndexService.kt
- clients/osv/src/main/kotlin/OsvApiClient.kt
- clients/osv/src/main/kotlin/OsvService.kt
- clients/scanoss/src/main/kotlin/ScanOssService.kt
- reporter/src/main/kotlin/reporters/fossid/FossIdReporter.kt
- reporter/src/test/kotlin/reporters/fossid/FossIdReporterTest.kt
- scanner/src/funTest/kotlin/storages/ClearlyDefinedStorageFunTest.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/main/kotlin/scanners/scanoss/ScanOssConfig.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdConfigTest.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
- scanner/src/test/kotlin/scanners/scanoss/ScanOssConfigTest.kt
> Client service code alignments

- helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
- utils/ort/src/main/kotlin/CopyrightStatementsProcessor.kt
- utils/ort/src/test/assets/copyright-statements-expected-output.yml
- utils/ort/src/test/kotlin/CopyrightStatementsProcessorTest.kt
> CopyrightStatementsProcessor: Make `process()` deterministic

- README.md
- utils/common/src/main/kotlin/EnvironmentVariableFilter.kt
> Environment variable filter improvements

- .gitattributes
- helper-cli/src/main/kotlin/utils/PathExcludeGenerator.kt
- helper-cli/src/test/kotlin/PathExcludeGeneratorTest.kt
> Fix path exclude generation on Windows

- cli/src/main/kotlin/commands/ConfigCommand.kt
Exit with code 2 (code 1 is reserved for errors that prevent the program
from functioning at all) if the configuration does not pass the syntax
check.
> ConfigCommand: Add a simple option to check the syntax

- README.md
> README: Slightly improve some reporter docs

- advisor/src/main/kotlin/advisors/VulnerableCode.kt
- advisor/src/test/kotlin/AbstractAdviceProviderFactoryTest.kt
- advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
- clients/vulnerable-code/src/main/kotlin/VulnerableCodeService.kt
- integrations/jenkins/Jenkinsfile
- integrations/schemas/ort-configuration-schema.json
- model/src/main/kotlin/config/AdvisorConfiguration.kt
- model/src/main/resources/reference.yml
- model/src/test/kotlin/config/AdvisorConfigurationTest.kt
> Support the public VulnerableCode instance 

- model/src/main/kotlin/config/ScanStorageConfiguration.kt
- model/src/main/resources/reference.yml
- model/src/test/kotlin/config/OrtConfigurationTest.kt
> Improve documentation for storage types

- analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
- analyzer/src/funTest/kotlin/managers/BabelFunTest.kt
> BabelFunTest: Fix the failing test

- cli/src/main/kotlin/commands/ScannerCommand.kt
> ScannerCommand: Make it explicit that the shown number is the version

- evaluator/src/main/kotlin/osadl/CompatibilityMatrix.kt
- evaluator/src/main/resources/rules/osadl-matrix-with-explanations.json
- evaluator/src/test/kotlin/osadl/CompatibilityMatrixTest.kt
> Update the OSADL matrix to release 2022-11-18

- analyzer/src/funTest/assets/projects/synthetic/pub-expected-output-with-flutter-android-and-cocoapods.yml
- analyzer/src/main/kotlin/managers/Pub.kt
See: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#338-nov-09-2022
> Pub: Upgrade bootstrapped Flutter version to 3.3.8

- scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
- scanner/src/main/kotlin/Scanner.kt
> Scanner chores

- advisor/src/test/kotlin/advisors/OssIndexTest.kt
- advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
- analyzer/src/main/kotlin/managers/GoMod.kt
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- cli/src/funTest/kotlin/ExamplesFunTest.kt
- model/src/test/kotlin/OrtResultTest.kt
- model/src/test/kotlin/config/RepositoryConfigurationTest.kt
- reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModel.kt
- reporter/src/test/kotlin/reporters/freemarker/FreeMarkerTemplateProcessorTest.kt
- scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt
- utils/spdx/build.gradle.kts
> Prefer the more speaking `first()` over `[0]`

- utils/ort/src/main/kotlin/CopyrightStatementsProcessor.kt
- utils/ort/src/test/kotlin/CopyrightStatementsProcessorTest.kt
> Accept an uppercase "(C)" as part of the Copyright prefix

- docs/notice-templates.md
- docs/reporters/asciidoc-templates.md
- docs/reporters/notice-templates.md
> Fix reporter docs

- scripts/import_certificates.sh
> Import certificates improvements

- integrations/jenkins/Jenkinsfile
- model/src/main/kotlin/config/ScannerConfiguration.kt
- scanner/src/main/kotlin/ScanStorages.kt
> Support ClearlyDefined as a scan storage in the Jenkins pipeline

- analyzer/src/main/kotlin/managers/Yarn.kt
- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- utils/common/src/main/kotlin/DiskCache.kt
> Introduce a Yarn info cache

- scanner/build.gradle.kts
- scanner/src/main/kotlin/scanners/scanoss/ScanOss.kt
This is a preparation for getting rid of the BuildConfig completely.
> scanner: Read the ScanOss library version from the JAR

- cli/src/main/kotlin/commands/ConfigCommand.kt
> ConfigCommand: Add a simple conversion from HOCON to YAML

- cli/src/main/kotlin/OrtMain.kt
- helper-cli/src/main/kotlin/HelperMain.kt
- integrations/jenkins/Jenkinsfile
> Align log levels in frontends

- renovate.json
This is a fixup for cf95fef. Closes #6133.
> Fix the Renovate configuration

- .github/workflows/build-and-test.yml
- build.gradle.kts
- cli/src/main/kotlin/commands/ScannerCommand.kt
- gradle.properties
- gradle/libs.versions.toml
- scanner/build.gradle.kts
- scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
- scanner/src/main/kotlin/CommandLinePathScannerWrapper.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/ScannerWrapper.kt
- scanner/src/main/kotlin/scanners/Askalono.kt
- scanner/src/main/kotlin/scanners/BoyterLc.kt
- scanner/src/main/kotlin/scanners/Licensee.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCode.kt
- scanner/src/main/kotlin/scanners/scanoss/ScanOss.kt
- scanner/src/test/kotlin/ScannerTest.kt
> Remove bootstrapping of scanners

- Dockerfile
> docker: Sanitize Golang in docker

- .dockerignore
Signed-off-by: Helio Chissini de Castro <heliocastro@gmail.com>
>  dockerignore: Extend dockerignore to avoid ort source invalidation on build

- .detekt.yml
- cli/src/main/kotlin/OrtMain.kt
- helper-cli/src/main/kotlin/HelperMain.kt
> Wildcard cleanups

- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
> Some smaller CLI code improvements

- build.gradle.kts
- utils/scripting/src/main/kotlin/OrtScriptCompilationConfiguration.kt
> Mark ORT scripts as non-standalone

- analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
Improve the readabiliy of getAllPackageData() a bit.
> NuGetSupport: Factor out getPackageData()

- analyzer/src/funTest/kotlin/managers/NuGetFunTest.kt
Pass a lambda to the constructor in order to reduce the level of nesting.
> NuGetFunTest: Eliminate the init block

- analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
Make it obvious that version ranges and wildcards are not supported, to potentially safe some debugging time.
See also [1], [2].
[1] https://learn.microsoft.com/en-us/nuget/concepts/package-versioning 
[2] https://github.com/oss-review-toolkit/ort/issues/6183
> NuGetSupport: Improve the message of an OrtIssue

- README.md
> README: Briefly explain where to get the CLI fat JAR from JitPack

- cli/src/funTest/kotlin/OrtMainFunTest.kt
- cli/src/main/kotlin/OrtMain.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- evaluator/src/main/kotlin/Evaluator.kt
> EvaluatorCommand: Support a rule file and a rule resource at the same time

- docs/license-handling.md
> license-handling: Add a cross-link to license choice docs

- model/src/test/kotlin/PackageCurationTest.kt
- utils/common/src/main/kotlin/Extensions.kt
- utils/common/src/test/kotlin/ExtensionsTest.kt
> SemVer-related clean-ups

- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/WorkingTree.kt
- downloader/src/test/kotlin/VersionControlSystemTest.kt
> Improve the prioritization in `getRevisionCandidates()`

- scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
This better documents which versions of ScanCode use what key.
> ScanCodeResultParser: Set the copyright key name depending on the version

- downloader/src/funTest/kotlin/vcs/GitDownloadFunTest.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/test/kotlin/VersionControlSystemTest.kt
- scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
> Do not treat non-existing VCS revisions as non-fixed 

- Dockerfile
> docker: Move all languages components to independent layer

- evaluator/src/main/resources/rules/osadl.rules.kts
Also reformat the messages slightly along the way to consistently use interpolation for variables.
> osadl.rules: Use named parameters for issues for clarity

- README.md
In exchange, add a paragraph to the general "Storage Backends" introduction.
> README: Remove the outdated "Experimental Scanner" section

- utils/spdx/src/main/resources/declared-license-mapping.yml
- utils/spdx/src/main/resources/simple-license-mapping.yml
> Separate ambiguous license mappings

- analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- analyzer/src/main/kotlin/managers/utils/SpdxResolvedDocument.kt
- downloader/src/main/kotlin/VcsHost.kt
> Simplify code that falls back from `getOrNull()`

- analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
- cli/src/main/kotlin/commands/UploadCurationsCommand.kt
- clients/clearly-defined/build.gradle.kts
- clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
- clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
> Introduce extension functions for chunked ClearlyDefined service requests

- README.md
> README: Document the FossId and EvaluatedModel reporters

- scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
- scanner/src/main/kotlin/utils/WorkingTreeCache.kt
> Miscellanous console output tweaking

- analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
> PipFunTest: Update expected Django test results

- utils/common/src/main/kotlin/ArchiveUtils.kt
Skip unpacking of archive entries that point to outside of the target directory. This addresses a CodeQL finding.
> ArchiveUtils: Guard against unpacking malicious archives

- utils/ort/src/main/kotlin/Utils.kt
- utils/ort/src/test/kotlin/UtilsTest.kt
> Minor improvements to `filterVersionNames()`

- analyzer/src/main/kotlin/managers/Yarn.kt
- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- cli/src/main/kotlin/OrtMain.kt
- model/src/main/kotlin/Mappers.kt
- utils/common/src/main/kotlin/Extensions.kt
- utils/common/src/main/kotlin/Utils.kt
- utils/ort/src/main/kotlin/OkHttpClientHelper.kt
Add convenience properties for converting values to mebibytes and gibibytes.
> utils: Add extension properties to convert values to mebi- and gibibytes

- utils/ort/src/test/kotlin/OkHttpClientHelperTest.kt
> OkHttpClientHelperTest: Add a test for getting different clients

- utils/ort/src/main/kotlin/storage/HttpFileStorage.kt
Executing `ort scan` inside Docker on a GitHub Runner with the storages for scan results, provenances and file archives configured as HTTP file storages, all pointing to a certain JFrog instance runs into [1] consistently. Many times accessing the storage succeeds but sometimes it fails. Given a medium sized analyzer result as scanner input, the problem always reproduces.
While the root cause is not understood, increasing the connect timeout of the HTTP client fixes the issue. Use that as a work around without changing the default HTTP clients configuration to keep the impact of this change limited.
Fixes: #6261.
> HttpFileStorage: Increase the connect timeout from 10 to 30 seconds

- scanner/src/test/kotlin/ScannerTest.kt
Use blocks to configure mocks to improve overview. This makes it easier to see which scaffolding belongs to which mock.
> ScannerTest: Configure mocks with blocks

- analyzer/src/funTest/assets/projects/external/git-repo-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
- analyzer/src/funTest/kotlin/managers/NpmFunTest.kt
- analyzer/src/funTest/kotlin/managers/NpmVersionUrlFunTest.kt
- analyzer/src/main/kotlin/managers/Npm.kt
- utils/test/src/main/kotlin/Utils.kt
> Npm: Map CLI warning / error messages to ORT issues

- analyzer/src/main/resources/META-INF/plexus/components.xml
> analyzer: Add "apk" (Android applications) as a known Maven packaging

- utils/ort/src/main/kotlin/storage/HttpFileStorage.kt
> HttpFileStorage: Reduce keep alive duration

- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
> AdvisorCommand: Print a summary of how many packages are vulnerable

- analyzer/src/funTest/assets/projects/synthetic/gradle-android-cyclic-expected-output-app.yml
- analyzer/src/funTest/assets/projects/synthetic/gradle-android-cyclic/build.gradle
- analyzer/src/funTest/assets/projects/synthetic/gradle-android/build.gradle
- analyzer/src/funTest/kotlin/managers/BabelFunTest.kt
- analyzer/src/funTest/kotlin/managers/BowerFunTest.kt
- analyzer/src/funTest/kotlin/managers/CargoFunTest.kt
- analyzer/src/funTest/kotlin/managers/CargoSubcrateFunTest.kt
- analyzer/src/funTest/kotlin/managers/ConanFunTest.kt
- analyzer/src/funTest/kotlin/managers/DotNetFunTest.kt
- analyzer/src/funTest/kotlin/managers/GradleAndroidFunTest.kt
- analyzer/src/funTest/kotlin/managers/GradleBomFunTest.kt
- analyzer/src/funTest/kotlin/managers/GradleFunTest.kt
- analyzer/src/funTest/kotlin/managers/GradleKotlinScriptFunTest.kt
- analyzer/src/funTest/kotlin/managers/GradleLibraryFunTest.kt
- analyzer/src/funTest/kotlin/managers/NpmFunTest.kt
- analyzer/src/funTest/kotlin/managers/NpmVersionUrlFunTest.kt
- analyzer/src/funTest/kotlin/managers/NuGetFunTest.kt
- analyzer/src/funTest/kotlin/managers/PnpmFunTest.kt
- analyzer/src/funTest/kotlin/managers/PubFunTest.kt
- analyzer/src/funTest/kotlin/managers/Yarn2FunTest.kt
- analyzer/src/funTest/kotlin/managers/YarnFunTest.kt
- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- analyzer/src/main/resources/scripts/init.gradle
- analyzer/src/test/kotlin/managers/utils/NpmDependencyHandlerTest.kt
- model/src/main/kotlin/Mappers.kt
- utils/ort/src/test/assets/copyright-statements-expected-output.yml
> Gradle Android fixes

- analyzer/src/funTest/kotlin/managers/BabelFunTest.kt
- analyzer/src/funTest/kotlin/managers/BowerFunTest.kt
- analyzer/src/funTest/kotlin/managers/BundlerFunTest.kt
- analyzer/src/funTest/kotlin/managers/CargoFunTest.kt
- analyzer/src/funTest/kotlin/managers/CargoSubcrateFunTest.kt
- analyzer/src/funTest/kotlin/managers/CarthageFunTest.kt
- analyzer/src/funTest/kotlin/managers/ComposerFunTest.kt
- analyzer/src/funTest/kotlin/managers/ConanFunTest.kt
- analyzer/src/funTest/kotlin/managers/GoModFunTest.kt
- analyzer/src/funTest/kotlin/managers/GradleAndroidFunTest.kt
- analyzer/src/funTest/kotlin/managers/GradleBomFunTest.kt
- analyzer/src/funTest/kotlin/managers/GradleFunTest.kt
- analyzer/src/funTest/kotlin/managers/GradleKotlinScriptFunTest.kt
- analyzer/src/funTest/kotlin/managers/GradleLibraryFunTest.kt
- analyzer/src/funTest/kotlin/managers/MavenFunTest.kt
- analyzer/src/funTest/kotlin/managers/NpmFunTest.kt
- analyzer/src/funTest/kotlin/managers/NpmVersionUrlFunTest.kt
- analyzer/src/funTest/kotlin/managers/NuGetFunTest.kt
- analyzer/src/funTest/kotlin/managers/PnpmFunTest.kt
- analyzer/src/funTest/kotlin/managers/SbtFunTest.kt
- analyzer/src/funTest/kotlin/managers/Yarn2FunTest.kt
- analyzer/src/funTest/kotlin/managers/YarnFunTest.kt
- analyzer/src/main/kotlin/managers/Bundler.kt
- analyzer/src/main/kotlin/managers/Pub.kt
- analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
- analyzer/src/main/kotlin/managers/Yarn2.kt
- analyzer/src/main/kotlin/managers/utils/NpmSupport.kt
- analyzer/src/test/kotlin/managers/BundlerTest.kt
> Default to the highest Bundler version that lockfiles (if any) were bundled with

- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
> Improve CLI statistics a bit

- model/src/main/kotlin/VulnerabilityReference.kt
> Support CVSS version 3.1

- cli/src/main/kotlin/OrtMain.kt
- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/ConfigCommand.kt
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/NotifierCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- cli/src/main/kotlin/commands/UploadResultToPostgresCommand.kt
- cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
- model/src/main/kotlin/config/OrtConfiguration.kt
- reporter/src/main/kotlin/reporters/freemarker/asciidoc/AdocTemplateReporter.kt
- reporter/src/main/kotlin/reporters/freemarker/asciidoc/AsciiDocTemplateReporter.kt
> Remove the CLI's `GlobalOptions`

- build.gradle.kts
- gradle.properties
> Kotlin 1.8 chores

- README.md
> README: Add related tools

- Dockerfile
- docker/legacy/Dockerfile
- scripts/export_proxy_certificates.sh
- scripts/import_proxy_certs.sh
> Improvements to certificate handling in Docker

- analyzer/src/main/kotlin/managers/Cargo.kt
- analyzer/src/main/kotlin/managers/Composer.kt
- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- model/src/test/kotlin/licenses/LicenseClassificationsTest.kt
- reporter/src/funTest/kotlin/reporters/freemarker/NoticeTemplateReporterFunTest.kt
> No sorted set fixups

- advisor/src/test/kotlin/advisors/GitHubDefectsTest.kt
- advisor/src/test/kotlin/advisors/OssIndexTest.kt
- analyzer/src/test/kotlin/PackageManagerTest.kt
- helper-cli/src/test/kotlin/PathExcludeGeneratorTest.kt
- helper-cli/src/test/kotlin/UtilsTest.kt
- model/src/test/kotlin/utils/FindingsMatcherTest.kt
- scanner/src/funTest/kotlin/storages/AbstractProvenanceBasedStorageFunTest.kt
- scanner/src/test/kotlin/scanners/scanoss/ScanOssScannerDirectoryTest.kt
- scanner/src/test/kotlin/scanners/scanoss/ScanOssScannerFileTest.kt
- utils/spdx/src/test/kotlin/SpdxExpressionTest.kt
> Miscellaneous small test improvements

- helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
> CreateAnalyzerResultCommand: Migrate to provenance based storage

- README.md
- cli/src/main/kotlin/OrtMain.kt
- helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
- helper-cli/src/main/kotlin/commands/DownloadResultsFromPostgresCommand.kt
- helper-cli/src/main/kotlin/commands/GetPackageLicensesCommand.kt
- helper-cli/src/main/kotlin/commands/ListStoredScanResultsCommand.kt
- helper-cli/src/main/kotlin/commands/scanstorage/DeleteCommand.kt
- integrations/completions/ort-completion.fish
The paths for these properties have changed by [1].
[1] https://github.com/oss-review-toolkit/ort/commit/4ea98636ff2e510bafc9fd8300433ed0cf204304
> Fix-up a left-over from postgres storage config properties

- .commitlintrc.yml
- analyzer/src/funTest/kotlin/curation/ClearlyDefinedPackageCurationProviderFunTest.kt
- analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
- analyzer/src/main/kotlin/curation/Sw360PackageCurationProvider.kt
- clients/clearly-defined/src/main/kotlin/Definition.kt
- model/src/main/resources/reference.yml
- model/src/test/kotlin/config/OrtConfigurationTest.kt
> Allow to configure a minimum ClearlyDefined license score

- README.md
Signed-off-by: Frank Viernau <frank_viernau@epam.com>
> README.md: Slightly improve the short description of the evaluator

- cli/src/main/kotlin/commands/DownloaderCommand.kt
The new option `--skip-excluded` allows the `DownloadCommand` to ignore downloading excluded packages/projects (via `RepositoryConfiguration`). By default the option is set to true and can be negate with `--include-excluded`.
> feat(DownloadCommand): Add a `--skip-excluded` option

- .github/workflows/build-and-test.yml
- .github/workflows/static-analysis.yml
Align with the default Java version used in Docker builds as of 29d6e76.
> ci(GitHub): Build with Java 17

- downloader/src/funTest/kotlin/vcs/CvsWorkingTreeFunTest.kt
- downloader/src/funTest/kotlin/vcs/MercurialWorkingTreeFunTest.kt
- downloader/src/funTest/kotlin/vcs/SubversionWorkingTreeFunTest.kt
- downloader/src/main/kotlin/vcs/CvsWorkingTree.kt
- downloader/src/test/kotlin/vcs/GitTest.kt
> Fix `funTest-non-analyzer` to be hanging

- analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
> ClearlyDefinedPackageCurationProvider: Minor code style fixes

- utils/spdx/build.gradle.kts
- utils/spdx/src/main/resources/exceptions/GStreamer-exception-2005
- utils/spdx/src/main/resources/exceptions/GStreamer-exception-2008
- utils/spdx/src/main/resources/licenses/GPL-2.0-with-classpath-exception
- utils/spdx/src/main/resources/licenses/MS-LPL
- utils/spdx/src/main/resources/licenses/mpi-permissive
- utils/spdx/src/main/resources/licenses/wxWindows
> Remove license provider work around

- build.gradle.kts
> Small Gradle build improvements

- README.md
- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
> fix(README): Remove the example about the fat JAR, which was removed

- analyzer/src/funTest/kotlin/curation/ClearlyDefinedPackageCurationProviderFunTest.kt
- analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
- clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
- clients/clearly-defined/src/main/kotlin/Definition.kt
> ClearlyDefined fixes

- integrations/jenkins/Jenkinsfile
> Fix the `Jenkinsfile` to not use `--clearly-defined-curations` anymore

- docs/config-file-curations-yml.md
> fix(docs): Correct `--package-curations-dir` value to be a directory

- model/src/main/resources/reference.yml
> docs(reference.yml): Clarify on some priorities implied by ordering

- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
> Minor improvements to printing info in the CLI

- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
Add server url and scan id to scan results
> FossID: add server url and scan id to scan results

- clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
- clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
- scanner/src/funTest/kotlin/storages/ClearlyDefinedStorageFunTest.kt
- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
> ClearlyDefined harvest API fixes

- downloader/src/main/kotlin/VersionControlSystem.kt
- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- downloader/src/test/kotlin/VersionControlSystemTest.kt
> Mercurial: Fix a problem with testing whether a VCS URL is applicable

- downloader/src/main/kotlin/vcs/Cvs.kt
- downloader/src/main/kotlin/vcs/Git.kt
- downloader/src/main/kotlin/vcs/Mercurial.kt
- scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
> Migrate from `Pattern` to `Regex`

- evaluator/build.gradle.kts
> build(Gradle): Add a simple evaluator task to update the OSADL matrix

- clients/clearly-defined/build.gradle.kts
- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
> Simplify `ClearlyDefinedStorage` exception handling

- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- analyzer/src/test/kotlin/managers/utils/MavenSupportTest.kt
> Support more edge-cases of invalid Maven SCM connection URLs

- analyzer/src/main/kotlin/curation/FilePackageCurationProvider.kt
> Ignore empty curation files

- analyzer/src/main/kotlin/managers/Npm.kt
> style(Npm): Trivially improve formatting for a better overview

- clients/osv/src/funTest/assets/vulnerability-by-id-expected-result.json
Fix a failing test.
Signed-off-by: Frank Viernau <frank_viernau@epam.com>
> test(OsvServiceFunTest): Update the expected result

- evaluator/src/main/kotlin/PackageRule.kt
> Fix-up `PackageRule.uncuratedPkg` to be not null again

- clients/osv/src/funTest/assets/vulnerabilities-by-name-and-version-expected-result.json
> test(OsvServiceFunTest): Update expected results

- downloader/src/funTest/kotlin/vcs/GitWorkingTreeFunTest.kt
> test(GitWorkingTreeFunTest): Update expected test results

- analyzer/src/main/kotlin/managers/GoDep.kt
- build.gradle.kts
- scanner/src/main/kotlin/provenance/ProvenanceDownloader.kt
- utils/common/src/main/kotlin/Extensions.kt
> Use `copyToRecursively()` from Kotlin 1.8

- docs/config-file-ort-yml.md
- model/src/main/resources/reference.yml
- model/src/test/kotlin/config/OrtConfigurationTest.kt
Refer to the single commits for further information.
> Document the skipExcluded option of the Analyzer

- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
- docs/getting-started.md
- evaluator/src/main/kotlin/osadl/CompatibilityMatrix.kt
> Miscecllanoues code inspection fixes

- clients/clearly-defined/src/main/kotlin/Enums.kt
> Prepare the ClearlyDefined client for upcoming improvements

- clients/osv/src/funTest/assets/vulnerabilities-by-name-and-version-expected-result.json
> test(OsvServiceFunTest): Update expected test results

- model/src/main/kotlin/utils/Extensions.kt
> ClearlyDefined type mapping fixes

- evaluator/src/main/resources/rules/matrixseqexpl.json
This was done by running
$ ./gradlew :evaluator:updateOsadlMatrix
> feat(evaluator): Update the OSADL matrix to version 2023-02-09

- utils/common/build.gradle.kts
- utils/common/src/main/resources/META-INF/services/javax.script.ScriptEngineFactory
- utils/ort/build.gradle.kts
- utils/spdx/build.gradle.kts
- utils/test/build.gradle.kts
> Gradle module dependency fixes

- analyzer/src/funTest/kotlin/curation/ClearlyDefinedPackageCurationProviderFunTest.kt
- analyzer/src/funTest/kotlin/curation/OrtConfigPackageCurationProviderFunTest.kt
- analyzer/src/main/kotlin/Analyzer.kt
- analyzer/src/main/kotlin/PackageCurationProvider.kt
- analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
- analyzer/src/main/kotlin/curation/OrtConfigPackageCurationProvider.kt
- analyzer/src/main/kotlin/curation/SimplePackageCurationProvider.kt
- analyzer/src/main/kotlin/curation/Sw360PackageCurationProvider.kt
- analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt
- analyzer/src/test/kotlin/curation/FilePackageCurationProviderTest.kt
> Simplify and clarify the API of package curation providers

- clients/clearly-defined/src/main/kotlin/Extensions.kt
- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
> More preparations for upcoming ClearlyDefined changes

- docs/config-file-curations-yml.md
- examples/curations.ort.yml
- examples/curations.yml
- integrations/schemas/curations-schema.json
> Fix some left-overs from renaming `is_meta_data_only`

- model/src/main/kotlin/OrtResult.kt
> Improvements for `OrtResult`'s project and package getters 

- clients/osv/src/funTest/assets/vulnerabilities-by-name-and-version-expected-result.json
- clients/osv/src/funTest/kotlin/OsvServiceFunTest.kt
> Fix the `OsvServiceFunTest`

- scanner/src/funTest/kotlin/provenance/DefaultNestedProvenanceResolverFunTest.kt
- scanner/src/funTest/kotlin/provenance/DefaultPackageProvenanceResolverFunTest.kt
> Add tests for resolving (nested) SVN provenance

- analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt
- cli/src/main/kotlin/commands/UploadCurationsCommand.kt
- model/src/main/kotlin/PackageProvider.kt
- model/src/main/kotlin/utils/Extensions.kt
- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
> Stop hard-coding ClearlyDefined providers

- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output-windows.yml
- analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
> test(PipFunTest): Update expected test results

- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
- utils/common/src/main/kotlin/Utils.kt
- utils/common/src/test/kotlin/UtilsTest.kt
> Make use of `PackageProvider`  for Maven

- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
See commit messages for details.
> fix(MavenSupport): Use authentication when requesting remote artifacts 

- model/src/main/kotlin/PackageProvider.kt
Make sure the entries are in alphabetical order within each of the two sections.
> style(PackageProvider): Fix-up the order of enum entries

- cli/src/funTest/kotlin/ExamplesFunTest.kt
- cli/src/funTest/kotlin/OrtMainFunTest.kt
- helper-cli/src/main/kotlin/utils/PathExcludeGenerator.kt
- model/src/main/kotlin/config/ScannerConfiguration.kt
- model/src/test/kotlin/JsonSchemaTest.kt
- utils/ort/src/main/kotlin/Constants.kt
> Make more use of file name constants

- analyzer/src/main/kotlin/managers/Bower.kt
- analyzer/src/main/kotlin/managers/Composer.kt
- analyzer/src/main/kotlin/managers/Stack.kt
- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- analyzer/src/main/kotlin/managers/utils/NpmSupport.kt
- analyzer/src/main/kotlin/managers/utils/NuGetSupport.kt
- analyzer/src/test/kotlin/PackageManagerTest.kt
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- model/src/main/kotlin/VcsType.kt
- model/src/test/kotlin/PackageTest.kt
- model/src/test/kotlin/VcsInfoTest.kt
- scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt
> Avoid the creation of new `VcsType` instances for known types

- utils/common/src/main/kotlin/DirectoryStash.kt
> Stash to a temporary directory instead of a parent directory by default

- advisor/src/main/kotlin/advisors/Osv.kt
- clients/osv/src/main/kotlin/Model.kt
> OSV ecosystem updates

- analyzer/src/funTest/assets/projects/synthetic/gradle-android-cyclic-expected-output-app.yml
- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- analyzer/src/main/resources/scripts/init.gradle
> Improvements to Gradle project analysis

- advisor/src/main/kotlin/advisors/Osv.kt
> chore(Osv): Improve the wording of a `TODO` statement 

- analyzer/src/funTest/kotlin/managers/PubFunTest.kt
- cli/src/funTest/kotlin/OrtMainFunTest.kt
- utils/test/src/main/kotlin/Utils.kt
> test: De-duplicate getAssetFile()

- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
Previously, failures to look up remote artifacts were unconditionally cached as empty artifacts. While it is hard to reliably determine the root cause of a failed lookup, in the case that all candidate URLs do not end with a known extension it is very likely that ORT ran into a bug in the context of #4694. Ease debugging such cases by not anymore caching failed lookups due to missing file extensions, and generally improve the logging when returning an empty remote artifact.
> feat(MavenSupport): Improve the caching logic for empty remote artifacts

- reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModelMapper.kt
- reporter/src/main/kotlin/reporters/evaluatedmodel/StatisticsCalculator.kt
> evaluated model: minor improvements

- detekt-rules/build.gradle.kts
- detekt-rules/src/main/kotlin/OrtPackageNaming.kt
- detekt-rules/src/test/kotlin/OrtImportOrderTest.kt
- detekt-rules/src/test/kotlin/OrtPackageNamingTest.kt
- gradle/libs.versions.toml
> Detekt: Add tests and support deeper nested module structures

- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
> Add a test for handling a `SocketTimeoutException` in the `ClearlyDefinedStorage`

- reporter/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
- reporter/src/main/kotlin/ReporterInput.kt
- reporter/src/main/kotlin/Statistics.kt
- reporter/src/main/kotlin/StatisticsCalculator.kt
- reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedModelMapper.kt
- reporter/src/main/kotlin/reporters/freemarker/FreemarkerTemplateProcessor.kt
This allows accessing that value from the reporters, templates as well as from within the WebApp.
> feat(reporter): Add "severe" issue and violation counts to `Statistics`

- reporter/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
- reporter/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
- reporter/src/funTest/assets/static-html-reporter-test-input.yml
- reporter/src/main/kotlin/Statistics.kt
- reporter/src/main/kotlin/StatisticsCalculator.kt
> reporter: Add execution duration to statistics

- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
Also drop the word "URL" from the log messages while at it, as these are
not URL strings in the strict sense.
> refactor(MavenSupport): Log the project for invalid SCM URLs

- clients/osv/src/funTest/kotlin/OsvServiceFunTest.kt
> Make `OsvServiceFunTest` resilient towards changes in backend specific data

- gradle/wrapper/gradle-wrapper.properties
See [1].
[1]: https://github.com/gradle/gradle/releases/tag/v8.0.2
> build: Upgrade Gradle to version 8.0.2

- advisor/src/funTest/kotlin/OsvFunTest.kt
- advisor/src/main/kotlin/advisors/GitHubDefects.kt
- advisor/src/main/kotlin/advisors/NexusIq.kt
- advisor/src/main/kotlin/advisors/OssIndex.kt
- advisor/src/main/kotlin/advisors/Osv.kt
- advisor/src/main/kotlin/advisors/VulnerableCode.kt
- advisor/src/test/kotlin/advisors/OssIndexTest.kt
- model/src/main/kotlin/config/AdvisorConfiguration.kt
- model/src/test/kotlin/config/AdvisorConfigurationTest.kt
> Various smaller alignments across the advisor implementations

- notifier/build.gradle.kts
- notifier/src/main/kotlin/modules/MailNotifier.kt
- notifier/src/test/kotlin/modules/JiraNotifierTest.kt
- notifier/src/test/kotlin/modules/MailNotifierTest.kt
> Notifier tests

- scanner/src/main/kotlin/scanners/scancode/ScanCodeResultParser.kt
- scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt
While parsing newer output format versions might not throw exceptions, results may be incomplete (see #6617 for the context). Avoid confusion by warning in that case.
> feat(ScanCodeResultParser): Warn about unsupported versions

- advisor/src/main/kotlin/advisors/OssIndex.kt
- advisor/src/main/kotlin/advisors/Osv.kt
- model/src/main/kotlin/config/AdvisorConfiguration.kt
> fix(Osv): Make the configuration optional again

- utils/spdx/src/main/resources/declared-license-mapping.yml
Found in [1].
[1]: https://repo1.maven.org/maven2/org/hibernate/hibernate-core/5.3.14.Final/hibernate-core-5.3.14.Final.pom
> feat(declared-license-mapping): Add 'LGPL-2.1-or-later' mapping

- analyzer/src/funTest/kotlin/managers/PubFunTest.kt
- analyzer/src/main/kotlin/managers/Conan.kt
- analyzer/src/main/kotlin/managers/Gradle.kt
- analyzer/src/main/kotlin/managers/Pub.kt
- analyzer/src/main/kotlin/managers/Yarn2.kt
- model/src/main/kotlin/config/AnalyzerConfiguration.kt
- model/src/test/kotlin/config/AnalyzerConfigurationTest.kt
> Decouple Pub from Gradle

- reporter/src/funTest/kotlin/reporters/opossum/OpossumReporterFunTest.kt
- reporter/src/main/kotlin/reporters/opossum/OpossumReporter.kt
OpossumUI changed its standard input format to `.opossum` which is a zipped file containing an `input.json` and an optional `output.json` (see [OpossumUI](https://github.com/opossum-tool/OpossumUI/blob/main/USER_GUIDE.md#dot_opossum)). The Opossum reporter is adapted accordingly, i.e., it generates a `report.opossum` file containing an `input.json` with the ort result while the `output.json` is ignored.
> feat(reporter): opossum reporter writes `.opossum` files

- analyzer/src/funTest/assets/projects/synthetic/gomod-unused-deps-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/gomod-unused-deps/go.mod
- analyzer/src/funTest/assets/projects/synthetic/gomod-unused-deps/go.sum
- analyzer/src/funTest/kotlin/managers/GoModFunTest.kt
- analyzer/src/main/kotlin/managers/GoMod.kt
**Note: Must be merged after** #6642.
> GoMod: Fix analyzing projects with unused dependencies

- analyzer/src/main/kotlin/managers/Pub.kt
Flutter packages typically also include native dependencies for Android (Gradle) and iOS (CocoaPods). A new configuration option allows to limit the analyzer to the Pub dependencies only.
> feat(Analyzer): Add option to Pub to skip native Flutter dependencies

- analyzer/src/main/kotlin/managers/GoMod.kt
> GoMod: Fix some comments

- Dockerfile
- docker/legacy/Dockerfile
- scripts/set_gradle_proxy.sh
- Rename proxy $USER variable to prevent collisions with system environment
- Remove trailing slashes from proxy port variables
> Fix several proxy configuration errors in Docker

- cli/src/main/kotlin/commands/ScannerCommand.kt
- clients/fossid-webapp/src/main/kotlin/Extensions.kt
- clients/fossid-webapp/src/main/kotlin/model/identification/identifiedFiles/License.kt
- scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/main/kotlin/scanners/fossid/FossIdNamingProvider.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
Please refer to individual commits messages.
> FossID: Change the delta scan matching logic

- build.gradle.kts
- cli/build.gradle.kts
- helper-cli/build.gradle.kts
- reporter/build.gradle.kts
- scanner/build.gradle.kts
> Gradle test configuration improvements

- advisor/build.gradle.kts
- build.gradle.kts
- cli/build.gradle.kts
- clients/clearly-defined/build.gradle.kts
- clients/github-graphql/build.gradle.kts
- clients/nexus-iq/build.gradle.kts
- clients/oss-index/build.gradle.kts
- clients/osv/build.gradle.kts
- clients/scanoss/build.gradle.kts
- clients/vulnerable-code/build.gradle.kts
- evaluator/build.gradle.kts
- gradle/libs.versions.toml
- plugins/package-managers/python/build.gradle.kts
- plugins/package-managers/python/src/main/kotlin/Pip.kt
- scanner/build.gradle.kts
> Build health improvements

- helper-cli/src/main/kotlin/commands/ImportCopyrightGarbageCommand.kt
> helper-cli: Fix the command for importing copyright garbage

- analyzer/src/main/kotlin/managers/Sbt.kt
> feat(Sbt): Add a fallback to find POMs for older SBT versions

- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- clients/nexus-iq/src/main/kotlin/NexusIqService.kt
- clients/oss-index/src/main/kotlin/OssIndexService.kt
> HTTP client builder improvements

- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- model/src/main/kotlin/ResolvedConfiguration.kt
- model/src/main/kotlin/utils/OrtResultExtensions.kt
> Add resolutions to `ResolvedConfiguration`

- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- model/src/main/kotlin/ResolvedConfiguration.kt
- model/src/main/kotlin/utils/OrtResultExtensions.kt
> Add package configurations to the resolved configuration

- model/src/main/kotlin/DependencyGraph.kt
- model/src/main/kotlin/PackageReference.kt
- model/src/main/kotlin/config/RepositoryConfiguration.kt
- model/src/main/kotlin/utils/JsonIncludeValueFilters.kt
> Json value filter improvements

- reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
- reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
- reporter/src/main/kotlin/reporters/spdx/SpdxDocumentModelMapper.kt
> feat(SpdxDocumentModelMapper): Add detected licenses as "info from files"

- analyzer/src/funTest/assets/projects/synthetic/godeps-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output-scope-excludes.yml
- analyzer/src/funTest/kotlin/managers/GoDepFunTest.kt
- analyzer/src/funTest/kotlin/managers/NpmFunTest.kt
- analyzer/src/funTest/kotlin/managers/PnpmFunTest.kt
- analyzer/src/funTest/kotlin/managers/SbtFunTest.kt
- analyzer/src/funTest/kotlin/managers/YarnFunTest.kt
- analyzer/src/testFixtures/kotlin/Extensions.kt
- cli/build.gradle.kts
- cli/src/funTest/kotlin/AnalyzerFunTest.kt
- cli/src/funTest/kotlin/ExamplesFunTest.kt
- plugins/package-managers/carthage/src/funTest/kotlin/CarthageFunTest.kt
- plugins/package-managers/pub/src/funTest/kotlin/PubFunTest.kt
...plus a couple of clean-ups. See individual commits.
> test(GoDepFunTest): Make use of `patchExpectedResult2()`

- analyzer/src/main/kotlin/PackageManagerFactory.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- utils/common/src/main/kotlin/PluginManager.kt
> Allow to disable plugins by default

- cli/src/main/kotlin/OrtCommand.kt
- cli/src/main/kotlin/commands/AdvisorCommand.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- cli/src/main/kotlin/commands/ConfigCommand.kt
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- cli/src/main/kotlin/commands/EvaluatorCommand.kt
- cli/src/main/kotlin/commands/NotifierCommand.kt
- cli/src/main/kotlin/commands/ReporterCommand.kt
- cli/src/main/kotlin/commands/ScannerCommand.kt
- cli/src/main/kotlin/commands/UploadResultToPostgresCommand.kt
- cli/src/main/kotlin/commands/UploadResultToSw360Command.kt
I am planning more refactorings to the commands also in the context of the required changes for the resolved configuration, so there is more to come.
> Minor CLI improvements

- analyzer/src/funTest/kotlin/managers/PnpmFunTest.kt
- analyzer/src/funTest/kotlin/managers/SbtFunTest.kt
- cli/src/funTest/kotlin/OrtMainFunTest.kt
- scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
- utils/test/src/main/kotlin/Utils.kt
> test: Clean-up turning actual result to yaml

- analyzer/build.gradle.kts
> Analyzer build chores

- analyzer/src/funTest/assets/projects/synthetic/npm-expected-output-no-lockfile.yml
- analyzer/src/main/kotlin/Analyzer.kt
- analyzer/src/main/kotlin/PackageManager.kt
- cli/src/funTest/assets/git-repo-expected-output.yml
- plugins/package-managers/gradle-inspector/README.md
- plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
- plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt
- plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelImpl.kt
> Some follow-up `GradleInspector` improvements

- plugins/package-managers/gradle/src/funTest/kotlin/GradleAndroidFunTest.kt
- plugins/package-managers/gradle/src/funTest/kotlin/GradleFunTest.kt
> Gradle chores

- plugins/package-managers/composer/src/main/kotlin/Composer.kt
> Ignore all PHP composer platform dependencies

- model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt
- model/src/test/kotlin/licenses/DefaultLicenseInfoProviderTest.kt
After adding a package curation which narrows down the VCS path of a package, one has to re-run the scanner to see the impact of that curation on the detected licenses. If the new VCS path is a subdirectory of the old VCS path a re-scan is not necessary, because the scan result for the corresponding package does cover the curated VCS path.
Filter the scan result (again) in the `DefaultLicenseInfoProvider` so that the effect of the changes can be seen by only re-running the evaluator. This reduces the turn around time for seeing the effect of changes when using workflows similar to `orthw`.
> feat(model): Re-filter scan summary when VCS path was narrowed down

- plugins/package-managers/gradle-plugin/src/main/kotlin/GradleModelExtensions.kt
- plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt
> Gradle plugin refactorings

- analyzer/src/main/kotlin/Analyzer.kt
- plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
> `GradleInspector` project type fixes

- plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
- plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt
> Inspector vs Gradle alignments

- plugins/package-managers/gradle-plugin/src/main/kotlin/GradleModelExtensions.kt
- plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt
> More minor improvements to filtering Gradle configurations

- utils/test/src/main/kotlin/Utils.kt
The value is never null anymore, so remove `replaceIfNotNull()`.
> refactor(test-utils): Simplify `patchExpectedResult()`

- utils/test/src/main/kotlin/Utils.kt
> Improvements to patching results

- helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
- helper-cli/src/main/kotlin/utils/Extensions.kt
> helper-cli: Support compound expressions in `ListLicensesCommand`

- reporter/src/funTest/kotlin/reporters/freemarker/PlainTextTemplateReporterFunTest.kt
- reporter/src/funTest/kotlin/reporters/opossum/OpossumReporterFunTest.kt
- reporter/src/funTest/kotlin/reporters/spdx/SpdxDocumentReporterFunTest.kt
> Minor fixes for `generateReport()`

- reporter/src/funTest/kotlin/Extensions.kt
- reporter/src/funTest/kotlin/reporters/CycloneDxReporterFunTest.kt
> CycloneDX cleanups

- .gitattributes
- .reuse/dep5
- README.md
- plugins/package-managers/spdx/.gitattributes
> Fixups for the move of the SPDX package manager

- helper-cli/src/test/kotlin/utils/PathExcludeGeneratorTest.kt
- helper-cli/src/test/kotlin/utils/UtilsTest.kt
- model/src/main/kotlin/Mappers.kt
> Miscellanoues minor fixes

- cli/src/main/kotlin/OrtMain.kt
- integrations/jenkins/Jenkinsfile
> Further `Jenkinsfile`  improvements

- docs/config-file-curations-yml.md
> docs: Fix a broken reference

- evaluator/build.gradle.kts
- plugins/package-managers/gradle-plugin/build.gradle.kts
> Make building the fat Gradle plugin JAR more reliable 

- plugins/reporters/build.gradle.kts
- plugins/reporters/opossum/build.gradle.kts
- plugins/reporters/opossum/src/funTest/assets/static-html-reporter-test-input.yml
- plugins/reporters/opossum/src/funTest/kotlin/OpossumReporterFunTest.kt
- plugins/reporters/opossum/src/main/kotlin/OpossumReporter.kt
- plugins/reporters/opossum/src/main/resources/META-INF/services/org.ossreviewtoolkit.reporter.Reporter
- plugins/reporters/opossum/src/test/kotlin/OpossumReporterTest.kt
- reporter/src/main/resources/META-INF/services/org.ossreviewtoolkit.reporter.Reporter
- settings.gradle.kts
FYI @maxhbr & @lennartclaas, this is part of #6602.
> Move the Opossum reporter to its own project

- cli/build.gradle.kts
- reporter/build.gradle.kts
> Remove unused repos

- gradle/libs.versions.toml
- reporter-web-app/build.gradle.kts
> Pin the Node.js version in order to be able to upgrade Kotlin

- .jitpack.yml
This seems to work now, see https://jitpack.io/com/github/oss-review-toolkit/ort/jitpack-vs-yarn-1c558acea3-1/build.log.
> build(jitpack): Build with the reporter-web-app

- plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
- plugins/package-managers/gradle-plugin/src/main/kotlin/MavenModelExtensions.kt
- plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt
> GradleInspector fixes in preparation for adding functional tests

- .github/workflows/build-and-test.yml
- reporter-web-app/build.gradle.kts
> Workflow caching improvements

- helper-cli/src/main/kotlin/commands/SetDependencyRepresentationCommand.kt
Support input files of type PackageManagerResult. Those files are used by some tests. With a new conversion function it is now possible to convert such files to AnalyzerResult files using both the dependency tree or graph formats.
This PR is created in the context of using input files for Gradle functional tests for the new Gradle inspector implementation.
> feat(helper-cli): Extend SetDependencyRepresentationCommand

- build.gradle.kts
- cli/build.gradle.kts
- detekt-rules/build.gradle.kts
- evaluator/build.gradle.kts
- helper-cli/build.gradle.kts
- plugins/package-managers/gradle-inspector/build.gradle.kts
- reporter-web-app/build.gradle.kts
- scanner/build.gradle.kts
> Some build fixes for the GradleInspector

- analyzer/src/testFixtures/kotlin/Extensions.kt
- plugins/package-managers/nuget/src/funTest/assets/nuget-expected-output.yml
- plugins/package-managers/nuget/src/funTest/kotlin/NuGetFunTest.kt
- plugins/package-managers/nuget/src/main/kotlin/NuGet.kt
- plugins/package-managers/nuget/src/main/kotlin/utils/NuGetInspector.kt
> Improve NuGet error / warning mapping

- utils/ort/src/funTest/kotlin/storage/LocalFileStorageFunTest.kt
- utils/ort/src/main/kotlin/storage/LocalFileStorage.kt
- utils/ort/src/main/kotlin/storage/XZCompressedLocalFileStorage.kt
> Do not require a file storage directory to exist 

- advisor/src/main/kotlin/advisors/VulnerableCode.kt
- evaluator/src/main/kotlin/PackageRule.kt
- model/src/main/kotlin/VulnerabilityReference.kt
- model/src/test/kotlin/VulnerabilityTest.kt
- reporter-web-app/src/models/WebAppVulnerability.js
> Improve `VulnerabilityReference.getSeverityString()`

- analyzer/src/main/kotlin/managers/GoDep.kt
- analyzer/src/main/kotlin/managers/GoMod.kt
> Go dep vs mod docs

- helper-cli/src/main/kotlin/commands/SubtractScanResultsCommand.kt
- helper-cli/src/main/kotlin/commands/repoconfig/ImportLicenseFindingCurationsCommand.kt
- helper-cli/src/main/kotlin/utils/Extensions.kt
- model/src/main/kotlin/OrtResult.kt
- plugins/reporters/fossid/src/main/kotlin/FossIdReporter.kt
- plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt
- plugins/reporters/opossum/src/main/kotlin/OpossumReporter.kt
- reporter/src/main/kotlin/ReportTableModelMapper.kt
> Introduce and use `OrtResult.getScanResults()`

- .dockerignore
- Dockerfile-legacy
> Fixes to argument handling in the legacy Dockerfile

- README.md
- docs/reporters/asciidoc-templates.md
- docs/reporters/plain-text-templates.md
- mlc_config.json
- plugins/package-managers/spdx/src/funTest/assets/projects/synthetic/README.md
- plugins/reporters/web-app-template/README.md
> docs(reporter): Fix broken links to web-app related reporters

- cli/src/main/kotlin/commands/DownloaderCommand.kt
> Implement concurrent downloads in the CLI

- scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
> Make `resolveSourceArtifact()` a suspend function 

- build.gradle.kts
- cli/build.gradle.kts
- clients/github-graphql/src/main/kotlin/GitHubService.kt
- downloader/src/test/kotlin/vcs/GitTest.kt
- helper-cli/src/main/kotlin/commands/classifications/ImportCommand.kt
- plugins/package-managers/carthage/src/main/kotlin/Carthage.kt
- plugins/package-managers/carthage/src/test/kotlin/CarthageTest.kt
- utils/ort/src/test/kotlin/UtilsTest.kt
- utils/spdx/build.gradle.kts
> Add support for building ORT with Java 20

- plugins/reporters/static-html/src/main/kotlin/StaticHtmlReporter.kt
- reporter/src/main/kotlin/ReportTableModelMapper.kt
First couple of improvements to prepare for further ones.
> ReportTableModelMapper: First couple of style improvements

- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
- helper-cli/src/main/kotlin/commands/SetDependencyRepresentationCommand.kt
- model/src/main/kotlin/Mappers.kt
- model/src/test/kotlin/IdentifierTest.kt
- model/src/test/kotlin/config/AdvisorConfigurationTest.kt
- model/src/test/kotlin/config/LicenseFindingCurationTest.kt
- model/src/test/kotlin/config/ReporterConfigurationTest.kt
- model/src/test/kotlin/config/RepositoryConfigurationTest.kt
- plugins/package-managers/bundler/src/main/kotlin/Bundler.kt
- plugins/package-managers/node/src/funTest/kotlin/NpmFunTest.kt
- plugins/package-managers/node/src/funTest/kotlin/NpmVersionUrlFunTest.kt
- plugins/package-managers/nuget/src/main/kotlin/utils/NuGetInspector.kt
- utils/spdx/src/test/kotlin/SpdxExpressionTest.kt
- utils/test/src/main/kotlin/Extensions.kt
> Use `fromYaml()` in production code

- advisor/src/main/kotlin/advisors/NexusIq.kt
- advisor/src/main/kotlin/advisors/OssIndex.kt
> Start refactoring NexusIq/OssIndex advisors a bit

- analyzer/src/funTest/assets/projects/synthetic/gomod-workspaces-main-module-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/gomod-workspaces-sub-module-expected-output.yml
- analyzer/src/funTest/assets/projects/synthetic/gomod-workspaces/go.mod
- analyzer/src/funTest/assets/projects/synthetic/gomod-workspaces/go.sum
- analyzer/src/funTest/assets/projects/synthetic/gomod-workspaces/go.work
- analyzer/src/funTest/assets/projects/synthetic/gomod-workspaces/go.work.sum
- analyzer/src/funTest/assets/projects/synthetic/gomod-workspaces/main.go
- analyzer/src/funTest/assets/projects/synthetic/gomod-workspaces/other-module/go.mod
- analyzer/src/funTest/assets/projects/synthetic/gomod-workspaces/other-module/go.sum
- analyzer/src/funTest/assets/projects/synthetic/gomod-workspaces/other-module/main.go
- analyzer/src/funTest/kotlin/managers/GoModFunTest.kt
- analyzer/src/main/kotlin/managers/GoMod.kt
> GoMod: Allow for analyzing modules which are part of a multi-module workspace

- advisor/src/main/kotlin/AdviceProvider.kt
- advisor/src/main/kotlin/advisors/NexusIq.kt
- advisor/src/main/kotlin/advisors/OssIndex.kt
- advisor/src/main/kotlin/advisors/VulnerableCode.kt
> refactor(nexus-iq/oss-index): Improve exception handling

- advisor/src/main/kotlin/advisors/OssIndex.kt
- clients/nexus-iq/src/main/kotlin/NexusIqService.kt
- clients/oss-index/src/main/kotlin/OssIndexService.kt
- integrations/schemas/ort-configuration-schema.json
- model/src/main/kotlin/config/AdvisorConfiguration.kt
- model/src/main/resources/reference.yml
> Support authentication for the OssIndex advisor

- model/src/main/kotlin/utils/Extensions.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
> fix(fossid-webapp): Don't create issue when the URL cannot be mapped

- clients/fossid-webapp/src/main/kotlin/model/result/Snippet.kt
- model/src/main/kotlin/utils/Snippet.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
> Change the Snippet Provenance to KnownProvenance

- utils/spdx/build.gradle.kts
See [1] for details.
[1]: https://github.com/antlr/antlr4/issues/4128
> fix(Gradle): Work around an ANTLR encoding bug on Windows

- analyzer/src/main/kotlin/managers/utils/PackageManagerDependencyHandler.kt
> Small `PackageManagerDependency` improvements

- analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
- cli/src/main/kotlin/commands/DownloaderCommand.kt
- downloader/src/main/kotlin/Downloader.kt
- helper-cli/src/main/kotlin/commands/VerifySourceArtifactCurationsCommand.kt
- plugins/package-managers/bundler/src/main/kotlin/Bundler.kt
- plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
- plugins/package-managers/pub/src/main/kotlin/Pub.kt
- plugins/package-managers/stack/src/main/kotlin/Stack.kt
- scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
- utils/ort/src/main/kotlin/OkHttpClientHelper.kt
> **Note**
> While the implementation is not complete, it has already served me well, so I didn't want to hold it back.
> Implement a basic dry-run option for the downloader

- analyzer/src/main/kotlin/PackageManager.kt
- build.gradle.kts
- cli/src/main/kotlin/OrtMain.kt
- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- scanner/src/funTest/kotlin/provenance/DefaultPackageProvenanceResolverFunTest.kt
- utils/spdx/src/main/kotlin/model/SpdxAnnotation.kt
- utils/spdx/src/main/kotlin/model/SpdxChecksum.kt
- utils/spdx/src/main/kotlin/model/SpdxFile.kt
- utils/spdx/src/main/kotlin/model/SpdxRelationship.kt
> Prepare for upgrading to a newer Detekt version

- build.gradle.kts
- clients/fossid-webapp/src/main/kotlin/model/result/LicenseCategory.kt
- model/src/main/kotlin/Snippet.kt
- plugins/package-curation-providers/clearly-defined/src/main/kotlin/ClearlyDefinedPackageCurationProvider.kt
- plugins/reporters/ctrlx/build.gradle.kts
- plugins/reporters/ctrlx/src/funTest/kotlin/CtrlXAutomationReporterFunTest.kt
- plugins/reporters/ctrlx/src/main/kotlin/CtrlXAutomationModel.kt
- plugins/reporters/ctrlx/src/main/kotlin/CtrlXAutomationReporter.kt
> Some Jackson vs kotlinx-serialization stuff

- cli/src/funTest/kotlin/OrtMainFunTest.kt
- cli/src/main/kotlin/commands/AnalyzerCommand.kt
- integrations/jenkins/Jenkinsfile
> Small curation provider related improvements

- advisor/src/test/kotlin/AdvisorTest.kt
- analyzer/src/testFixtures/kotlin/Extensions.kt
- plugins/package-managers/nuget/src/main/kotlin/utils/NuGetInspector.kt
- scanner/src/main/kotlin/FileList.kt
> Sorted cleanups

- plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelMapper.kt
The dependency graph API offers functions for iterating over the dependencies of nodes or project scopes. They return sequences of `DependencyNode`s with the caveat that the consumption of a `DependencyNode` of the sequence has finished, it's data is no more guaranteed to be valid. In fact, the instance is re-used to represent the next item of the sequence.
So, the `sort()` calls introduced by [1] made the iteration iterate N times over the "same" node which broke the dependency tree. This broke the tree view in the WebApp, see the "Tree" tab at the very top.
Fix the problem by just calling `getStableReference()`. This basically disables the object pooling and leaves a bit more work to the garbage collector.
This is a fix-up for [1] and fixes one aspect of #7042.
[1] …
> fix(EvaluatedModelMapper): Fix an issue related to object pooling

- clients/osv/src/main/kotlin/Model.kt
- clients/osv/src/main/kotlin/OsvApiClient.kt
- clients/scanoss/src/main/kotlin/ScanOssService.kt
- clients/scanoss/src/main/kotlin/model/Model.kt
- clients/scanoss/src/main/kotlin/model/ScanResponse.kt
- clients/vulnerable-code/build.gradle.kts
- clients/vulnerable-code/src/main/kotlin/VulnerableCodeService.kt
- plugins/package-managers/nuget/src/main/kotlin/utils/NuGetInspector.kt
- plugins/package-managers/python/src/main/kotlin/utils/PythonInspector.kt
> Make use of a kotlinx-serialization JSON naming strategy

- plugins/package-managers/gradle-inspector/src/funTest/kotlin/GradleAndroidFunTest.kt
- plugins/package-managers/gradle/src/funTest/kotlin/GradleAndroidFunTest.kt
- scanner/src/funTest/kotlin/scanners/scancode/ScanCodeScannerFunTest.kt
- utils/test/src/main/kotlin/TestTags.kt
> Remove barely used test tags

- scanner/src/main/kotlin/provenance/NestedProvenanceScanResult.kt
> Improve the `merge()` of `NestedProvenanceScanResult`

- build.gradle.kts
- gradle/libs.versions.toml
> Small build system improvements

- model/src/main/kotlin/licenses/LicenseInfoResolver.kt
- model/src/main/kotlin/utils/Extensions.kt
- model/src/main/kotlin/utils/FindingCurationMatcher.kt
- scanner/src/main/kotlin/provenance/NestedProvenanceScanResult.kt
> Minor `NestedProvenanceScanResult` improvements

- clients/fossid-webapp/src/main/kotlin/model/result/MatchedLines.kt
- clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
- scanner/src/main/kotlin/scanners/fossid/FossId.kt
- scanner/src/main/kotlin/scanners/fossid/FossIdConfig.kt
- scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdConfigTest.kt
- scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
- utils/common/src/main/kotlin/Extensions.kt
- utils/common/src/test/kotlin/ExtensionsTest.kt
- utils/ort/src/main/kotlin/CopyrightStatementsProcessor.kt
> feat(fossid-webapp): Add the matched lines to the snippets findings 

- plugins/package-managers/node/src/test/kotlin/NpmTest.kt
Use the correct NPM command per OS when mocking.
> fix(NpmTest): Make the test succeed on Windows

- model/src/main/kotlin/utils/JsonIncludeValueFilters.kt
- plugins/package-managers/node/src/main/kotlin/utils/NpmDependencyHandler.kt
> Simplify `equals()` implementations

- scanner/src/main/kotlin/scanners/fossid/FossIdScanResults.kt
Please have a look at the individual commit messages for the details.Please ensure that your pull request adheres to our [contribution guidelines](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md). Thank you!
> fix(fossid-webapp): Fix swapped source paths

- scanner/src/main/kotlin/ScanController.kt
- utils/common/src/main/kotlin/Utils.kt
- utils/spdx/src/main/kotlin/Utils.kt
> fix(scanner): Sort packages with the same provenance

- analyzer/src/main/kotlin/PackageManager.kt
- utils/common/src/main/kotlin/Utils.kt
> refactor: Turn some hard-coded directories into sets

- utils/spdx/src/main/kotlin/Utils.kt
> Minor SPDX `calculatePackageVerificationCode()` improvements

- model/src/main/kotlin/config/FileArchiverConfiguration.kt
- model/src/main/kotlin/config/FileListStorageConfiguration.kt
- scanner/src/main/kotlin/utils/FileListResolver.kt
> Leave compression of file lists to the storage implementation

- build.gradle.kts
> Some Gradle build improvements

- model/src/main/kotlin/config/FileListStorageConfiguration.kt
- model/src/main/kotlin/utils/FileProvenanceFileStorage.kt
- model/src/main/kotlin/utils/PostgresProvenanceFileStorage.kt
- model/src/main/kotlin/utils/ProvenanceFileStorage.kt
> `ProvenanceFileStorage`-related improvements

- plugins/package-curation-providers/clearly-defined/src/funTest/kotlin/ClearlyDefinedPackageCurationProviderFunTest.kt
The tests fail quite frequently randomly on CI. Try to reduce this annoyance by adding a retry mechanism. Start with 3 retries with a 3 seconds interval.
> test(clearly-defined): Try to make a test less flaky

- build.gradle.kts
- plugins/reporters/web-app/build.gradle.kts
- utils/spdx/build.gradle.kts
> Improve the work-around for code generated by ANTLR

- .github/workflows/static-analysis.yml
- cli/src/funTest/kotlin/AnalyzerFunTest.kt
- cli/src/funTest/kotlin/OrtMainFunTest.kt
- plugins/package-managers/pub/src/funTest/kotlin/PubFunTest.kt
- plugins/package-managers/spdx/src/funTest/kotlin/SpdxDocumentFileFunTest.kt
- utils/spdx/build.gradle.kts
> Detekt type resolution fixes

- .github/workflows/static-analysis.yml
These are more disturbing than helpful.
> ci(GitHub): Disable Qodana PR comments

- scanner/src/main/kotlin/ScanController.kt
- scanner/src/main/kotlin/Scanner.kt
This is follow-up to the implementation of #5950.
> Minor `ScanController` improvements

- model/src/main/kotlin/OrtResult.kt
- model/src/main/kotlin/utils/Extensions.kt
- model/src/main/kotlin/utils/SortedSetConverters.kt
> Minor fixes and preparations for adding file lists to `OrtResult`

- plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
- plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
- plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
- plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml
Add an issue resolution to the test data for the evaluated model test, because previously it was untested if issue resolutions are processed correctly.
> test(evaluated-model): Add an issue resolution

- scanner/src/main/kotlin/scanners/fossid/Utils.kt
- scanner/src/test/kotlin/scanners/fossid/MapIgnoreRulesTest.kt
> fix(fossid-webapp): Accept path excludes for files with a '-'

- buildSrc/src/main/kotlin/ort-plugins-conventions.gradle.kts
- gradle.properties
- plugins/commands/build.gradle.kts
- plugins/package-curation-providers/build.gradle.kts
- plugins/package-managers/build.gradle.kts
- plugins/reporters/build.gradle.kts
- plugins/scanners/askalono/build.gradle.kts
- plugins/scanners/askalono/src/funTest/kotlin/AskalonoFunTest.kt
- plugins/scanners/askalono/src/main/kotlin/Askalono.kt
- plugins/scanners/askalono/src/main/resources/META-INF/services/org.ossreviewtoolkit.scanner.ScannerWrapperFactory
- plugins/scanners/boyterlc/build.gradle.kts
- plugins/scanners/boyterlc/src/funTest/kotlin/BoyterLcFunTest.kt
- plugins/scanners/boyterlc/src/main/kotlin/BoyterLc.kt
- plugins/scanners/boyterlc/src/main/resources/META-INF/services/org.ossreviewtoolkit.scanner.ScannerWrapperFactory
- plugins/scanners/build.gradle.kts
- plugins/scanners/licensee/build.gradle.kts
- plugins/scanners/licensee/src/funTest/kotlin/LicenseeFunTest.kt
- plugins/scanners/licensee/src/main/kotlin/Licensee.kt
- plugins/scanners/licensee/src/main/resources/META-INF/services/org.ossreviewtoolkit.scanner.ScannerWrapperFactory
- scanner/build.gradle.kts
- scanner/src/funTest/kotlin/scanners/AbstractPathScannerWrapperFunTest.kt
- scanner/src/main/resources/META-INF/services/org.ossreviewtoolkit.scanner.ScannerWrapperFactory
- scanner/src/testFixtures/kotlin/AbstractPathScannerWrapperFunTest.kt
- scanner/src/testFixtures/resources/LICENSE
- settings.gradle.kts
> Start migrating scanner plugins to separate projects

- scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
> Minor `ScannerIntegrationTest` improvements

- README.md
- utils/test/src/main/kotlin/Matchers.kt
> Explain how to copy and paste actual test results on Windows

- .gitattributes
- .github/workflows/static-analysis.yml
- build.gradle.kts
- plugins/reporters/asciidoc/src/funTest/assets/.gitattributes
- plugins/reporters/asciidoc/src/main/resources/templates/.gitattributes
- plugins/reporters/cyclonedx/src/funTest/assets/.gitattributes
- plugins/reporters/evaluated-model/src/funTest/assets/.gitattributes
- plugins/reporters/fossid/src/main/resources/templates/.gitattributes
- plugins/reporters/freemarker/src/funTest/assets/.gitattributes
- plugins/reporters/freemarker/src/main/resources/templates/.gitattributes
- plugins/reporters/gitlab/src/funTest/assets/.gitattributes
- plugins/reporters/spdx/src/funTest/assets/.gitattributes
- plugins/reporters/static-html/src/funTest/assets/.gitattributes
- plugins/reporters/web-app-template/.gitattributes
- plugins/reporters/web-app/src/funTest/assets/.gitattributes
> Gitattribute fixes

- cli/src/funTest/assets/semver4j-ort-result.yml
- evaluator/src/test/kotlin/TestData.kt
- model/src/main/kotlin/AdvisorDetails.kt
- plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml
- plugins/reporters/freemarker/src/test/kotlin/FreeMarkerTemplateProcessorTest.kt
- plugins/reporters/opossum/src/funTest/assets/reporter-test-input.yml
- plugins/reporters/static-html/src/funTest/assets/reporter-test-input.yml
> Advisor details improvements

- plugins/scanners/fossid/src/main/kotlin/FossId.kt
> fix(fossid-webapp): Do not generate an issue for .git ignore rules

- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
> Generalize the ClearlyDefined scan storage implementation

- model/src/main/kotlin/ScanSummary.kt
- scanner/src/funTest/assets/scanner-integration-subset-pkgs-expected-ort-result.yml
- scanner/src/main/kotlin/Scanner.kt
> scanner: Stop including irrelevant file findings in `ScannerRun`

- README.md
- plugins/package-managers/pub/src/funTest/assets/projects/external/dart-http-expected-output.yml
- utils/test/src/main/kotlin/Matchers.kt
> Update expected Pub test results

- advisor/src/funTest/kotlin/OsvFunTest.kt
- advisor/src/main/kotlin/advisors/Osv.kt
- clients/osv/src/main/kotlin/Model.kt
- clients/osv/src/main/kotlin/OsvService.kt
> Fix OSV mit working with PURLs

- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/GitValueSources.kt
- buildSrc/src/main/kotlin/LicenseUtils.kt
- buildSrc/src/main/kotlin/ort-base-conventions.gradle.kts
> Make Git operations during the build compatible with the Gradle configuration cache

- model/src/main/kotlin/TextLocation.kt
- plugins/scanners/askalono/src/main/kotlin/Askalono.kt
- plugins/scanners/boyterlc/src/main/kotlin/BoyterLc.kt
- scanner/src/main/kotlin/CommandLinePathScannerWrapper.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/testFixtures/kotlin/AbstractPathScannerWrapperFunTest.kt
> Generally relativize text locations for scan results

- cli/src/main/resources/logback.xml
- plugins/reporters/fossid/src/main/resources/templates/asciidoc/fossid_snippet.ftl
> Various FossID fixes

- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
This way, non-CLI scanners are logged as unsupported.
> refactor(scanner): Filter for CLI scanners earlier

- Dockerfile
- Dockerfile-legacy
> Dockerfile cleanups

- qodana.yml
See [1].
[1]: https://youtrack.jetbrains.com/issue/QD-6348
> Upgrade the Qodana linter to version 2023.2-eap

- model/src/main/kotlin/ScannerRun.kt
- model/src/main/kotlin/utils/ScanResultUtils.kt
- scanner/src/main/kotlin/provenance/NestedProvenanceScanResult.kt
> fix(scanner): Do not crash when merging "incomplete" scan results

- model/src/main/kotlin/ScannerRun.kt
This a follow-up for #7277. See the individual commits.
> ScannerRun: Simplify merging scan results

- plugins/scanners/fossid/src/main/kotlin/FossId.kt
Currently, the mapped URL is only used for creating scans. It must be also used when searching for existing scans.
While at it, rename the variable to describe it better.
> fix(fossid-webapp): Use the mapped URL when searching for existing scans

- scanner/src/funTest/kotlin/storages/ClearlyDefinedStorageFunTest.kt
The tests randomly fail with HTTP status 429 (too many requests). Add an exponential retry similar to the one in
`ClearlyDefinedPackageCurationProviderFunTest`.
> test(scanner): Try to make a test less flaky

- plugins/reporters/spdx/src/main/kotlin/Extensions.kt
This was accidentally left over by c246552.
> fix(spdx): Remove an unused function

- scanner/src/main/kotlin/Scanner.kt
> Minor scanner improvements

- plugins/package-configuration-providers/build.gradle.kts
> fix(Plugins): Apply correct plugin for package-configuration-providers

- plugins/scanners/askalono/src/main/kotlin/Askalono.kt
- plugins/scanners/askalono/src/main/kotlin/AskalonoResultModel.kt
- plugins/scanners/boyterlc/src/main/kotlin/BoyterLc.kt
- plugins/scanners/boyterlc/src/main/kotlin/BoyterLcResultModel.kt
- plugins/scanners/licensee/src/main/kotlin/Licensee.kt
- plugins/scanners/licensee/src/main/kotlin/LicenseeResultModel.kt
> Migrate remaining scan result parsers to kotlinx-serialization

- plugins/scanners/fossid/src/main/kotlin/FossId.kt
> Two FossID fixes

- plugins/reporters/fossid/src/main/kotlin/FossIdSnippetReporter.kt
- plugins/reporters/fossid/src/main/resources/templates/asciidoc/fossid_snippet.ftl
> Two Snippet Reporter fixes

- model/src/main/kotlin/ScannerRun.kt
For larger scan results this operation may take a couple of seconds. Add log output in order to indicate what is being processed.
> chore(scanner): Log the beginning and end of merging scan results

- model/src/main/kotlin/AdvisorSummary.kt
- model/src/main/kotlin/AnalyzerResult.kt
- model/src/main/kotlin/ScanSummary.kt
- plugins/package-curation-providers/file/src/main/kotlin/FilePackageCurationProvider.kt
- plugins/package-managers/gradle/src/main/kotlin/Gradle.kt
- plugins/package-managers/gradle/src/main/kotlin/GradleDependencyHandler.kt
- plugins/package-managers/gradle/src/test/kotlin/GradleDependencyHandlerTest.kt
- plugins/package-managers/node/src/main/kotlin/Npm.kt
- plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
- utils/common/src/main/kotlin/Extensions.kt
> Miscellaneous minor fixes

- model/src/main/kotlin/utils/Extensions.kt
- plugins/package-curation-providers/clearly-defined/src/main/kotlin/ClearlyDefinedPackageCurationProvider.kt
- plugins/package-managers/spm/src/funTest/assets/projects/synthetic/spm-expected-output-app.yml
- plugins/package-managers/spm/src/funTest/assets/projects/synthetic/spm-expected-output-lib.yml
- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
> ClearlyDefined and PURL related improvements / fixes

- model/src/main/kotlin/Hash.kt
- model/src/main/kotlin/utils/Extensions.kt
- model/src/test/kotlin/IdentifierTest.kt
- plugins/package-managers/spdx/src/funTest/assets/projects/synthetic/spdx-project-xyz-expected-output.yml
- plugins/package-managers/spdx/src/main/kotlin/SpdxDocumentFile.kt
> Fix PURLs created by the `SpdxDocumentFile` package manager

- helper-cli/src/main/kotlin/commands/dev/RewriteTestAssetsCommand.kt
> Trivial `RewriteTestAssetsCommand` improvements

- model/src/main/resources/reference.yml
- plugins/package-configuration-providers/ort-config/build.gradle.kts
- plugins/package-configuration-providers/ort-config/src/main/kotlin/OrtConfigPackageConfigurationProvider.kt
- plugins/package-configuration-providers/ort-config/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.packageconfigurationproviders.api.PackageConfigurationProviderFactory
- plugins/package-configuration-providers/ort-config/src/test/kotlin/OrtConfigPackageConfigurationProviderFunTest.kt
Add a package-configuration provider for [ort-config](https://github.com/oss-review-toolkit/ort-config)
> feat(Plugins): Add package-configuration provider for ort-config

- plugins/scanners/scanoss/src/main/kotlin/ScanOss.kt
Form field "file" was missing while sending wfp file
> fix(scanoss): Fix issue on form file field #7320

- README.md
I'm not so confirmed with JAVA so I had a problem with `-Xmx=8g` because I think it should be `-Xmx8g`.
> docs: Improve memory settings description

- helper-cli/src/main/kotlin/commands/GetPackageLicensesCommand.kt
- helper-cli/src/main/kotlin/commands/ListCopyrightsCommand.kt
- helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
- plugins/commands/evaluator/src/main/kotlin/EvaluatorCommand.kt
- plugins/commands/reporter/src/main/kotlin/ReporterCommand.kt
- plugins/package-configuration-providers/api/src/main/kotlin/SimplePackageConfigurationProvider.kt
- plugins/package-configuration-providers/ort-config/build.gradle.kts
- plugins/package-configuration-providers/ort-config/src/main/kotlin/OrtConfigPackageConfigurationProvider.kt
> Replace `DirectoryPackageConfigurationProvider` with `DirPackageConfigurationProvider`

- plugins/commands/evaluator/src/main/kotlin/EvaluatorCommand.kt
This extends the idea from 778d601 to allow combining e.g. multiple rules resources. While at it, drop the manual `isFile` check as that is already done on the clikt option.
> feat(evaluator): Allow to specify multiple rules from the same resource

- buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- plugins/reporters/web-app/build.gradle.kts
See [1]. Address some deprecations that result in warnings along the way.
[1]: https://docs.gradle.org/8.3/release-notes.html
> build: Update Gradle to version 8.3

- gradle/libs.versions.toml
- plugins/commands/upload-result-to-postgres/src/main/kotlin/UploadResultToPostgresCommand.kt
- scanner/src/main/kotlin/provenance/PostgresNestedProvenanceStorage.kt
- scanner/src/main/kotlin/provenance/PostgresPackageProvenanceStorage.kt
- scanner/src/main/kotlin/storages/ProvenanceBasedPostgresStorage.kt
- scanner/src/main/kotlin/storages/utils/JsonbSupport.kt
- scanner/src/main/kotlin/storages/utils/ScanResultDao.kt
> Use Exposed's JSONB support

- plugins/scanners/scancode/src/test/kotlin/ScanCodeTest.kt
> ScanCode test chores

- buildSrc/src/main/kotlin/ort-base-conventions.gradle.kts
- buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
> Configure Maven Central publishing / signing

- utils/spdx/src/main/resources/declared-license-mapping.yml
Found in [1].
[1]: https://github.com/tox-dev/filelock/blob/3.9.0/pyproject.toml#L28
> feat(declared-license-mapping): Add 'The Unlicense (Unlicense)'

- utils/spdx/src/main/resources/declared-license-mapping.yml
Found in [1].
[1]: https://github.com/python-hyper/uritemplate/blob/3.0.0/setup.py#L15
> feat(declared-license-mapping): Add 'Apache or BSD' mapping

- model/src/main/kotlin/utils/ScanResultUtils.kt
In particular, fix the reference and do not document the special case code that was removed during PR review.
> docs(ScanResultUtils): Improve docs for `mergeAdditionalData()`

- clients/fossid-webapp/src/main/kotlin/Extensions.kt
> Fossid webapp chores

- model/src/main/kotlin/config/IssueResolution.kt
- model/src/main/kotlin/config/RuleViolationResolution.kt
- model/src/test/kotlin/config/IssueResolutionTest.kt
- model/src/test/kotlin/config/RuleViolationResolutionTest.kt
- model/src/test/kotlin/config/VulnerabilityResolutionTest.kt
> Improve resolution tests

- clients/fossid-webapp/src/main/kotlin/Extensions.kt
- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- clients/fossid-webapp/src/test/assets/return-type/mappings/apiphp-mark_as_identified.json
- clients/fossid-webapp/src/test/assets/return-type/mappings/apiphp-unmark_as_identified.json
- clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
This commit adds support for the functions `mark_as_identified` and `unmark_as_identified`.
> feat(fossid-webapp): Support two new API functions

- utils/spdx/build.gradle.kts
See #7359 for background information.
> feat(Gradle): Support proxy authentication for `JsonSlurper`

- plugins/commands/evaluator/src/main/kotlin/EvaluatorCommand.kt
- plugins/commands/evaluator/src/test/kotlin/EvaluatorCommandTest.kt
> Fix evaluator rules option parsing

- build.gradle.kts
- buildSrc/src/main/kotlin/GitValueSources.kt
- gradle/libs.versions.toml
- scripts/docker_build.sh
- scripts/docker_run.sh
- scripts/import_certificates.sh
> Calculate the SemVer from Conventional Commits

- buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts
> GraalVM tuning

- plugins/package-managers/pub/src/main/kotlin/Pub.kt
> chore: provide context when Flutter download fails

- cli/src/funTest/kotlin/OrtMainFunTest.kt
- plugins/commands/advisor/src/main/kotlin/AdvisorCommand.kt
- plugins/commands/analyzer/src/main/kotlin/AnalyzerCommand.kt
- plugins/commands/api/src/main/kotlin/utils/Extensions.kt
- plugins/commands/compare/src/main/kotlin/CompareCommand.kt
- plugins/commands/config/src/main/kotlin/ConfigCommand.kt
- plugins/commands/downloader/src/main/kotlin/DownloaderCommand.kt
- plugins/commands/evaluator/src/main/kotlin/EvaluatorCommand.kt
- plugins/commands/reporter/src/main/kotlin/ReporterCommand.kt
- plugins/commands/requirements/src/main/kotlin/RequirementsCommand.kt
- plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt
- plugins/commands/upload-curations/src/main/kotlin/UploadCurationsCommand.kt
- plugins/commands/upload-result-to-postgres/src/main/kotlin/UploadResultToPostgresCommand.kt
> Use the Clikt `test` extension

- .github/workflows/release.yml
- buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts
- buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
- buildSrc/src/main/kotlin/ort-library-conventions.gradle.kts
- buildSrc/src/main/kotlin/ort-publication-conventions.gradle.kts
> Create a publishing workflow

- buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts
- buildSrc/src/main/kotlin/ort-library-conventions.gradle.kts
- buildSrc/src/main/kotlin/ort-plugins-conventions.gradle.kts
- buildSrc/src/main/kotlin/ort-publication-conventions.gradle.kts
> Fix the publication of platform modules

- docusaurus/src/components/HomepageFeatures/index.js
- docusaurus/src/pages/index.js
> Minor website improvements

- .github/workflows/release.yml
> Automate the creation of a GitHub release with distributions attached

- plugins/commands/config/src/main/kotlin/ConfigCommand.kt
- plugins/commands/migrate/build.gradle.kts
- plugins/commands/migrate/src/main/kotlin/MigrateCommand.kt
- plugins/commands/migrate/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/package-curation-providers/ort-config/src/main/kotlin/OrtConfigPackageCurationProvider.kt
> Introduce a `migrate` subcommand

- advisor/src/main/kotlin/advisors/Osv.kt
- clients/osv/src/main/kotlin/OsvService.kt
> OSV logging improvements

- clients/osv/src/main/kotlin/Model.kt
> osv: Align the model with latest OSV JSON spec version

- .dockerignore
> Improvements to the `.dockerignore` file

- plugins/commands/migrate/src/main/kotlin/MigrateCommand.kt
Apply the path conventions from the ort-config repository also to package configuration files.
> feat(migrate): Add path conventions for package configuration files

- renovate.json
- website/package-lock.json
- website/package.json
> Disable renovate for website

- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/external-sources-expected-output.yml
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/external-sources/Podfile
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/external-sources/Podfile.lock
- plugins/package-managers/cocoapods/src/funTest/kotlin/CocoaPodsFunTest.kt
- plugins/package-managers/cocoapods/src/main/kotlin/CocoaPods.kt
Please have a look at the individual commit messages for the details. 
Big thanks to @ksg97031 for reporting #7523 and proposing an initial solution in https://github.com/oss-review-toolkit/ort/pull/7544. This PR applies a simpler fix, plus two more.
> More CocoaPods fixes

- model/src/main/kotlin/Provenance.kt
- model/src/main/kotlin/utils/DependencyGraphBuilder.kt
- utils/spdx/src/main/kotlin/model/SpdxExternalReference.kt
This improves symmetry with accompanying data classes in the same hierarchy, see [1] and [2].
[1]: https://kotlinlang.org/docs/whatsnew19.html#stable-data-objects-for-symmetry-with-data-classes
[2]: https://kotlinlang.org/docs/whatsnew1820.html#preview-of-data-objects-for-symmetry-with-data-classes
> chore: Use data objects in sealed hierarchies

- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/external-sources-expected-output.yml
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/version-resolution-expected-output.yml
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/version-resolution/Podfile
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/version-resolution/Podfile.lock
- plugins/package-managers/cocoapods/src/funTest/kotlin/CocoaPodsFunTest.kt
- plugins/package-managers/cocoapods/src/main/kotlin/CocoaPods.kt
> fix(CocoaPods): Do not add version constraints as concrete versions

- .github/actions/ortdocker/action.yml
- .github/workflows/docker-ort-runtime-ext.yml
- .github/workflows/docker-ort-runtime.yml
Fix mainly indentation but also some other formatting issues.
> chore: Fix formatting of workflow files

- plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt
- scanner/src/main/kotlin/ScanResultsStorage.kt
> Improve scan storage logging

- cli/src/funTest/kotlin/OrtMainFunTest.kt
- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
> Address Kotlin inspection hints

- website/docs/guides/sw360-integration.md
> SW360 clarifications

- buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts
- cli/build.gradle.kts
- gradle/libs.versions.toml
> Explicit dependencies

- plugins/commands/requirements/src/main/kotlin/RequirementsCommand.kt
> fix(RequirementsCommand): Account for new scanner constructors

- plugins/scanners/askalono/src/main/kotlin/Askalono.kt
- plugins/scanners/boyterlc/src/main/kotlin/BoyterLc.kt
- plugins/scanners/fossid/src/main/kotlin/FossId.kt
- plugins/scanners/licensee/src/main/kotlin/Licensee.kt
- plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
- plugins/scanners/scanoss/src/main/kotlin/ScanOss.kt
- scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
- scanner/src/funTest/kotlin/storages/AbstractProvenanceBasedStorageFunTest.kt
- scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt
- scanner/src/main/kotlin/ScanResultsStorage.kt
- scanner/src/main/kotlin/ScanStorage.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/ScannerMatcher.kt
- scanner/src/main/kotlin/ScannerWrapper.kt
- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
- scanner/src/main/kotlin/storages/NoStorage.kt
- scanner/src/main/kotlin/storages/PostgresStorage.kt
- scanner/src/main/kotlin/storages/ProvenanceBasedPostgresStorage.kt
- scanner/src/test/kotlin/ScannerMatcherTest.kt
- scanner/src/test/kotlin/ScannerTest.kt
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
> Rename scanner criteria to matcher

- scanner/src/main/kotlin/ScanResultsStorage.kt
- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
- scanner/src/test/assets/cd_definitions.json
- scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt
> Fixes to ClearlyDefined storage scanner matching

- clients/fossid-webapp/src/main/kotlin/Extensions.kt
- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- clients/fossid-webapp/src/test/assets/return-type/mappings/apiphp-add_component_identification.json
- clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
The function `addComponentIdentification` allows to add a component identification to a pending file.
> feat(fossid-webapp): Support a new API function

- clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
- clients/clearly-defined/src/main/kotlin/Coordinates.kt
- scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
> Simplify ClearlyDefined APIs taking coordinates

- plugins/package-managers/pub/src/funTest/assets/projects/external/dart-http-expected-output.yml
- plugins/package-managers/pub/src/funTest/assets/projects/synthetic/flutter-project-with-android-and-cocoapods/pubspec.lock
- plugins/package-managers/pub/src/funTest/assets/projects/synthetic/pub-expected-output-with-flutter-android-and-cocoapods.yml
- plugins/package-managers/pub/src/main/kotlin/Pub.kt
See [1] for a changelog.
[1]: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#flutter-313-changes
> feat(flutter): Upgrade bootstrapped Flutter version to 3.13.6

- cli/build.gradle.kts
- plugins/commands/analyzer/build.gradle.kts
- plugins/commands/evaluator/build.gradle.kts
- plugins/commands/reporter/build.gradle.kts
> Stop hard-coding plugin dependencies

- utils/ort/src/main/kotlin/storage/S3FileStorage.kt
> Minor S3 storage fixups

- analyzer/src/funTest/kotlin/PackageManagerFunTest.kt
- analyzer/src/main/kotlin/Analyzer.kt
> Some small chores

- gradle/libs.versions.toml
- plugins/package-managers/cargo/build.gradle.kts
- plugins/package-managers/cargo/src/funTest/assets/projects/synthetic/cargo-expected-output.yml
- plugins/package-managers/cargo/src/funTest/assets/projects/synthetic/cargo-subcrate-client-expected-output.yml
- plugins/package-managers/cargo/src/funTest/assets/projects/synthetic/cargo-subcrate-lib-expected-output.yml
- plugins/package-managers/cargo/src/main/kotlin/Cargo.kt
- plugins/package-managers/cargo/src/main/kotlin/CargoLockFile.kt
- plugins/package-managers/cargo/src/main/kotlin/CargoManifest.kt
- plugins/package-managers/cargo/src/main/kotlin/CargoMetadata.kt
> Migrate Cargo support to kotlinx-serialization

- scanner/src/main/kotlin/Scanner.kt
Do not only catch exceptions during download, but also when archiving.
Adjust the source of the issue accordingly to not name the "Downloader",
but more generically the "Scanner".
Fixes #7366.
> fix(scanner): Catch archiver exceptions

- analyzer/src/main/kotlin/managers/GoMod.kt
> Minor gomod improvements

- advisor/src/funTest/kotlin/VulnerableCodeFunTest.kt
- advisor/src/main/kotlin/advisors/VulnerableCode.kt
- advisor/src/test/assets/__files/vulnerable-code/response_junit.json
- clients/vulnerable-code/src/main/kotlin/VulnerableCodeService.kt
> Update VulnerableCode property names

- advisor/src/funTest/kotlin/VulnerableCodeFunTest.kt
Add assertions about severities reported by the NVD. See [1] for context.
[1]: https://github.com/oss-review-toolkit/ort/issues/7742
> test(VulnerableCode): Improve the funTest template

- .mailmap
> Mailmap updates

- helper-cli/src/main/kotlin/commands/repoconfig/GenerateScopeExcludesCommand.kt
- model/src/main/kotlin/config/ScopeExcludeReason.kt
> helper-cli: Extend scope exclude generation for Poetry

- model/src/main/kotlin/utils/FileArchiver.kt
- plugins/package-managers/gradle/src/main/kotlin/Gradle.kt
- plugins/package-managers/nuget/src/main/kotlin/utils/NuGetInspector.kt
- plugins/package-managers/python/src/main/kotlin/Poetry.kt
- plugins/package-managers/python/src/main/kotlin/utils/PythonInspector.kt
- scanner/src/main/kotlin/provenance/ProvenanceDownloader.kt
- scanner/src/main/kotlin/utils/FileListResolver.kt
- scanner/src/test/kotlin/utils/FileListResolverTest.kt
> Delete temporary `FileListResolver` directories

- plugins/reporters/trustsource/build.gradle.kts
- plugins/reporters/trustsource/src/funTest/assets/expected-report.json
- plugins/reporters/trustsource/src/funTest/kotlin/TrustSourceReporterFunTest.kt
- plugins/reporters/trustsource/src/main/kotlin/TrustSourceReporter.kt
> Add a basic functional test for the expected TrustSource report

- model/src/main/kotlin/vulnerabilities/Cvss4Rating.kt
- model/src/main/kotlin/vulnerabilities/VulnerabilityReference.kt
- model/src/test/kotlin/vulnerabilities/Cvss4RatingTest.kt
- model/src/test/kotlin/vulnerabilities/VulnerabilityReferenceTest.kt
As is it the same as CVSS 3's, just add alternative names to the `Cvss3Rating` enum.
> feat(vulnerabilities): Support the CVSS4 qualitative severity rating scale

- analyzer/src/main/kotlin/Extensions.kt
- plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
- plugins/scanners/fossid/src/main/kotlin/Utils.kt
- utils/common/src/main/kotlin/Extensions.kt
> Log about configured but unavailable package managers 

- analyzer/src/main/kotlin/PackageManager.kt
This implicitly also improves the logging scope, as the `logger` is now not anymore called on an anonymous `SimpleFileVisitor` instance.
> refactor(analyzer): Port Java's `walkFileTree()` to Kotlin's `walk()`

- website/docs/configuration/package-curations.md
> docs: Document setting metadata about a package's authors

- NOTICE
> Some `NOTICE` file edits

- integrations/jenkins/Jenkinsfile
> Allow to specify a VCS path for configuration in the Jenkins pipeline

- .mailmap
- integrations/jenkins/Jenkinsfile
- utils/ort/src/main/kotlin/Environment.kt
- utils/ort/src/main/kotlin/NetRcAuthenticator.kt
> Fix `user.home` when running ORT via Jenkins in a Docker-in-Docker scenario

- plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt
- scanner/src/main/kotlin/ScanContext.kt
- scanner/src/main/kotlin/Scanner.kt
> Teach package scanners about non-reference packages

- plugins/commands/requirements/src/main/kotlin/RequirementsCommand.kt
> Small improvements to the requirements command

- plugins/commands/requirements/src/main/kotlin/RequirementsCommand.kt
> Teach the requirements command to also list plugins

- plugins/commands/compare/src/main/kotlin/CompareCommand.kt
Check individual commit messages for details.
> feat(CompareCommand): Add a new compare method `SEMANTIC_DIFF`

- helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
- helper-cli/src/main/kotlin/utils/Extensions.kt
> helper-cli: Fix a crash with listing licenses

- integrations/jenkins/Jenkinsfile
> Allow to set arbitrary environment variables in Jenkins stages

- integrations/jenkins/Jenkinsfile
- plugins/advisors/vulnerable-code/src/funTest/kotlin/VulnerableCodeFunTest.kt
- plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt
> VulnerableCode configuration updates

- cli/src/main/kotlin/OrtMain.kt
- plugins/commands/api/src/main/kotlin/utils/SeverityStatsPrinter.kt
Thanks @Etsija for pointing this out!
> Avoid a duplicate plural "s" in the summary sentence printed to the console

- plugins/package-managers/node/src/main/kotlin/utils/NpmDetection.kt
- plugins/package-managers/node/src/test/kotlin/utils/NpmDetectionTest.kt
This restores the previous behavior before f99e2ed. Slightly improve some code comments while at it.
> fix(node): Default to NPM if there is no indication for any Node manager

- scanner/src/funTest/assets/scanner-integration-all-pkgs-expected-ort-result.yml
- scanner/src/funTest/assets/scanner-integration-expected-scan-results.yml
- scanner/src/funTest/assets/scanner-integration-subset-pkgs-expected-ort-result.yml
- scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
> Dummy scanner improvements

- reporter/src/main/kotlin/DefaultLicenseTextProvider.kt
- reporter/src/main/kotlin/LicenseTextProvider.kt
- utils/spdx/src/main/kotlin/Utils.kt
> Do not take blank file contents as license texts

- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
> feat(Fossid-webapp): Increase the read timeout for `listMatchedLines`

- model/src/main/kotlin/OrtResult.kt
- model/src/main/kotlin/utils/DefaultResolutionProvider.kt
> docs: Some KDoc fixes

- model/src/main/kotlin/utils/FindingsMatcher.kt
- model/src/test/kotlin/utils/FindingsMatcherTest.kt
- plugins/commands/reporter/src/main/kotlin/ReporterCommand.kt
- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt
- plugins/reporters/static-html/src/main/kotlin/StaticHtmlReporter.kt
- utils/spdx/src/main/kotlin/Utils.kt
> feat(model): Associate licenses and exceptions from the same expression

- plugins/reporters/fossid/src/main/kotlin/FossIdReporter.kt
- plugins/reporters/fossid/src/main/resources/templates/asciidoc/fossid_snippet.ftl
- plugins/reporters/fossid/src/test/kotlin/FossIdReporterTest.kt
Refer to the individual commits for further information.
> FossID reporter improvements

- evaluator/src/main/resources/rules/osadl.rules.kts
- website/docs/configuration/ort-yml.md
This is a follow-up to e5e0f3f.
> fix(evaluator): Apply repository license choices to the project

- model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt
From the signature it's been unclear what the `String` property is about.
> refactor(model): Make a function signature a bit more speaking

- plugins/package-managers/go/src/main/kotlin/GoMod.kt
- plugins/package-managers/go/src/test/kotlin/GoModTest.kt
> Minor cleanups within `GoMod`

- plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt
- plugins/advisors/vulnerable-code/src/test/kotlin/VulnerableCodeTest.kt
> Fixup more URLs reported by VulnerableCode

- .github/workflows/release.yml
- .github/workflows/static-analysis.yml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts
- buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
- buildSrc/src/main/kotlin/ort-library-conventions.gradle.kts
- buildSrc/src/main/kotlin/ort-publication-conventions.gradle.kts
- gradle/libs.versions.toml
> Improve publish to Maven Central

- model/src/main/kotlin/ScanResult.kt
- model/src/main/kotlin/Snippet.kt
- model/src/main/kotlin/config/DownloaderConfiguration.kt
- model/src/main/kotlin/config/ScannerConfiguration.kt
- scanner/src/main/kotlin/ScannerWrapper.kt
> Small improvements to mostly scanner documentation

- plugins/package-managers/python/src/main/kotlin/Pip.kt
- plugins/package-managers/python/src/main/kotlin/Poetry.kt
- plugins/package-managers/python/src/test/kotlin/PoetryTest.kt
> Minor python improvements

- model/src/main/kotlin/utils/PurlExtensions.kt
- model/src/main/kotlin/utils/PurlUtils.kt
- model/src/test/kotlin/utils/PurlExtensionsTest.kt
- plugins/reporters/asciidoc/src/main/resources/templates/asciidoc/defect_report.ftl
- plugins/reporters/asciidoc/src/main/resources/templates/asciidoc/disclosure_document.ftl
- plugins/reporters/asciidoc/src/main/resources/templates/asciidoc/vulnerability_report.ftl
> Purl extras

- plugins/scanners/fossid/src/main/kotlin/FossId.kt
- plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/ScannerWrapper.kt
- scanner/src/test/kotlin/ScannerTest.kt
> Fossid simplifications

- integrations/jenkins/Jenkinsfile
> docs(jenkins): Document that VulnerableCode is enabled by default

- website/docs/configuration/ort-yml.md
- website/docs/getting-started/installation.md
- website/docs/getting-started/runtime-requirements.md
- website/docs/getting-started/tutorial.md
- website/docs/getting-started/usage.md
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Upgrade Docusaurus to 3.1.0 and merge the tutorial into the docs. See the commit messages for details.
> Upgrade docusaurus to 3.1.0

- utils/ort/src/test/kotlin/CopyrightStatementsProcessorTest.kt
> Minor test improvements for copyright statements processor

- plugins/package-managers/spm/src/funTest/assets/projects/synthetic/spm-expected-output-lib.yml
- scanner/src/main/kotlin/Scanner.kt
> Add a closing quote when logging the scanner name

- plugins/package-managers/spm/src/funTest/assets/projects/synthetic/spm-expected-output-app.yml
- plugins/package-managers/spm/src/funTest/assets/projects/synthetic/spm-expected-output-lib.yml
- plugins/package-managers/spm/src/main/kotlin/Spm.kt
- plugins/package-managers/spm/src/main/kotlin/SpmModel.kt
> Several SPM related fixes

- plugins/package-managers/gradle-inspector/README.md
- plugins/package-managers/gradle-plugin/src/main/kotlin/GradleModelExtensions.kt
- plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt
> Improve the `GradleInspector` to also take repositories from Gradle settings into account

- model/src/main/resources/reference.yml
- model/src/test/kotlin/config/OrtConfigurationTest.kt
Signed-off-by: Dinesh Ravi <dineshr93@gmail.com>
follow up of https://github.com/oss-review-toolkit/ort/pull/8003
1. removed merge commit
2. Inserted `forceOverwrite` in alphabhetical order as @mnonnenmacher  mentioned
3. Added `ortConfig.forceOverwrite shouldBe true` in OrtConfigurationTest.kt
> feat(config): Add forceOverwrite option to reference.yml

- website/docs/getting-started/installation.md
- website/docusaurus.config.js
Improve the installation docs, see the commit messages for details.
> Improve installation docs

- plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-project.yml
- plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/project-with-lockfile/Package.resolved
- plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/project-with-lockfile/Package.swift
- plugins/package-managers/swiftpm/src/main/kotlin/SwiftPm.kt
Prepare for implementing #8167.
> SwiftPM: Illustrate how dependencies with branch name are handled

- model/src/main/kotlin/Hash.kt
The documented behavior is already covered by a test.
> docs(model): Fix the docs of `Hash.create()` for blank values

- plugins/package-managers/swiftpm/src/main/kotlin/SwiftPm.kt
- plugins/package-managers/swiftpm/src/main/kotlin/SwiftPmModel.kt
Primarily prepare for implementing [1], remove a bit of code redundancy.
[1] https://github.com/oss-review-toolkit/ort/issues/8167
> SwiftPM model and mapping improvements

- model/src/main/resources/reference.yml
- model/src/test/kotlin/config/OrtConfigurationTest.kt
- plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt
- plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCodeConfiguration.kt
See [1] for background information. Also [2] is good related read.
[1]: https://github.com/nexB/vulnerablecode/issues/1411
[2]: https://www.baeldung.com/okhttp-timeouts
> feat(vulnerable-code): Make the read timeout configurable

- plugins/package-managers/swiftpm/src/main/kotlin/SwiftPm.kt
> SwiftPM: A couple of minor fixes

- plugins/scanners/askalono/src/main/kotlin/Askalono.kt
Maybe not all errors imply no results to be present, so be on the safe side and allow both to be present.
> chore(askalono): Allow results and errors both to be present

- gradle.properties
- plugins/reporters/web-app-template/build.gradle.kts
> Enable Gradle's configuration cache for faster builds 

- plugins/package-managers/swiftpm/src/main/kotlin/SwiftPm.kt
> SwiftPM: `toVcsInfo()` fixes

- plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-project-without-deps.yml
- plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-project-without-lockfile.yml
- plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/project-without-deps/Package.swift
- plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/project-without-deps/Sources/MyPackage/my-package.swift
- plugins/package-managers/swiftpm/src/funTest/kotlin/SwiftPmFunTest.kt
> SwiftPM: Test a corner case

- integrations/jenkins/Jenkinsfile
> Custom Docker build args support for Jenkins

- helper-cli/src/main/kotlin/commands/repoconfig/GenerateScopeExcludesCommand.kt
> helper-cli: Add some more scope exclude patterns

- model/src/main/kotlin/licenses/ResolvedLicense.kt
- utils/spdx/src/main/kotlin/SpdxExpression.kt
> License docs improvements

- .github/workflows/release.yml
- gradle.properties
> Revert enabling the Gradle configuration cache

- .mailmap
- NOTICE
> Update bosch notice file entries

- model/src/main/kotlin/HashAlgorithm.kt
- model/src/test/kotlin/HashAlgorithmTest.kt
- plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
- plugins/package-managers/node/src/test/kotlin/utils/NpmSupportTest.kt
- utils/spdx/build.gradle.kts
- utils/spdx/src/main/kotlin/SpdxConstants.kt
- utils/spdx/src/test/kotlin/UtilsTest.kt
> Some `HashAlgorithm` refactoring

- plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm-babel-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm-expected-output-scope-excludes.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm-version-urls-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm-workspaces-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn-workspaces-expected-output.yml
- plugins/package-managers/node/src/funTest/kotlin/NpmFunTest.kt
- plugins/package-managers/node/src/funTest/kotlin/NpmVersionUrlFunTest.kt
- plugins/package-managers/node/src/funTest/kotlin/PnpmFunTest.kt
- plugins/package-managers/node/src/main/kotlin/Npm.kt
> Improve the Vcs Info fallback mechanism for node package managers

- model/src/main/kotlin/utils/FindingsMatcher.kt
- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt
- plugins/reporters/static-html/src/main/kotlin/StaticHtmlReporter.kt
- utils/spdx/src/main/kotlin/SpdxExpression.kt
- utils/spdx/src/main/kotlin/parser/SpdxExpressionParser.kt
- utils/spdx/src/test/kotlin/SpdxExpressionTest.kt
- utils/spdx/src/test/kotlin/parser/SpdxExpressionParserTest.kt
Reactor compound expressions to have multiple children, see the commit messages for details.
> Refactor compound expressions

- plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt
> docs(vulnerable-code): Document the read timeout option

- plugins/package-managers/sbt/src/main/kotlin/Sbt.kt
> Sbt clean ups

- utils/common/src/main/kotlin/Redirection.kt
- utils/common/src/test/kotlin/RedirectionTest.kt
> Redirect standard streams by byte array again

- .github/workflows/release.yml
- buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts
> Release tgz distributions

- plugins/package-managers/python/src/main/kotlin/Pip.kt
> Support the `.python-version` file

- model/src/main/kotlin/config/LicenseFindingCuration.kt
Use the minimal possible visibility.
> refactor(model)!: Reduce the visibility of two converters

- plugins/scanners/fossid/src/main/kotlin/FossId.kt
- plugins/scanners/fossid/src/test/kotlin/FossIdSnippetChoiceTest.kt
If a file has ALL its snippet findings source locations ranges qualified in the .ort.yml file, either with ORIGINAL_FINDING, NO_RELEVANT_FINDING or a combination of both, it is marked as identified.
> feat(fossid-webapp): Mark files with all qualified snippets as identified

- .github/workflows/build-and-test.yml
> build(GitHub): Reactivate unified test result diffs

- plugins/package-managers/pub/src/main/kotlin/Pub.kt
See [1] for a changelog.
[1]: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#3193-march-07-2024
Fixes #8428
> feat(flutter): Upgrade flutter version to 3.19.3

- plugins/package-managers/cargo/src/main/kotlin/Cargo.kt
- plugins/package-managers/cargo/src/main/kotlin/CargoLockfile.kt
- plugins/package-managers/composer/src/main/kotlin/Composer.kt
- plugins/package-managers/conan/src/main/kotlin/Conan.kt
- plugins/package-managers/go/src/main/kotlin/GoDep.kt
- plugins/package-managers/go/src/main/kotlin/GoDepLockfile.kt
- plugins/package-managers/node/src/main/kotlin/Npm.kt
- plugins/package-managers/node/src/main/kotlin/Pnpm.kt
- plugins/package-managers/node/src/main/kotlin/Yarn.kt
- plugins/package-managers/node/src/main/kotlin/utils/NpmDetection.kt
- plugins/package-managers/node/src/test/kotlin/utils/NpmDetectionTest.kt
- plugins/package-managers/pub/src/main/kotlin/Pub.kt
Also rename function and classes in line with recent renaming done by 6c6ddbf and 1ddb89b.
> refactor(package-managers): Align on `Lockfile` instead of `LockFile`

- plugins/scanners/fossid/src/main/kotlin/FossId.kt
- plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
- plugins/scanners/fossid/src/test/kotlin/FossIdSnippetChoiceTest.kt
When one or several source locations of a 'marked as identified' file have been deleted from the snippet choice section of the .ort.yml file, put again the file to the 'pending' state. Its snippets will be then listed as for all pending files.
To find out if some locations have been removed, the comment in the marked as identified file is used to compare the location counts with the entries in the .ort.yml file.
Please note that FossID UI should not be used by the user to manually change the file state: The snippet choice feature is non-interactive and doing so would disturb the logic.
> feat(fossid-webapp): Identify snippet choice entries that have been removed

- model/src/main/kotlin/config/Excludes.kt
- model/src/main/kotlin/config/PathExclude.kt
- model/src/test/kotlin/config/ExcludesTest.kt
> Path excludes cleanup

- model/src/main/kotlin/utils/DatabaseUtils.kt
- plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
- plugins/scanners/fossid/src/test/kotlin/TestUtils.kt
- scanner/src/main/kotlin/ScannerMatcher.kt
- scanner/src/main/kotlin/storages/AbstractPackageBasedScanStorage.kt
> Code scanning cleanups

- model/src/main/kotlin/utils/ConfigurationResolver.kt
> Minor improvements to the configuration resolver

- build.gradle.kts
- buildSrc/src/main/kotlin/LicenseUtils.kt
- downloader/src/main/kotlin/VcsHost.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- helper-cli/src/main/kotlin/commands/VerifySourceArtifactCurationsCommand.kt
- model/src/main/kotlin/OrtResult.kt
- model/src/main/kotlin/PackageCuration.kt
- model/src/main/kotlin/ScanSummary.kt
- model/src/main/kotlin/utils/DependencyGraphBuilder.kt
- model/src/main/kotlin/utils/DependencyGraphConverter.kt
- plugins/advisors/github/src/main/kotlin/GitHubDefects.kt
- plugins/package-configuration-providers/dir/src/main/kotlin/DirPackageConfigurationProvider.kt
- plugins/package-curation-providers/file/src/main/kotlin/FilePackageCurationProvider.kt
- plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
- plugins/package-managers/bazel/src/main/kotlin/StarlarkParser.kt
- plugins/package-managers/cargo/src/main/kotlin/Cargo.kt
- plugins/package-managers/conan/src/main/kotlin/Conan.kt
- plugins/package-managers/pub/src/main/kotlin/utils/PubCacheReader.kt
- plugins/reporters/fossid/src/main/kotlin/FossIdSnippetReporter.kt
- plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt
- plugins/scanners/fossid/src/main/kotlin/FossId.kt
- plugins/scanners/fossid/src/main/kotlin/FossIdConfig.kt
- scanner/src/main/kotlin/ScanController.kt
- utils/common/src/main/kotlin/Extensions.kt
- utils/ort/src/main/kotlin/Utils.kt
> Address K2 inspection hints

- plugins/package-managers/cargo/src/main/kotlin/Cargo.kt
- plugins/package-managers/cargo/src/main/kotlin/CargoLockfile.kt
- plugins/package-managers/cargo/src/main/kotlin/CargoMetadata.kt
> Cargo refactorings

- plugins/commands/requirements/src/main/kotlin/RequirementsCommand.kt
> Improve `requirements` version status output

- plugins/reporters/fossid/src/main/resources/templates/asciidoc/fossid_snippet.ftl
- website/docs/configuration/snippet-choice.md
> Snippet choices documentation fixes

- LICENSES/CC-BY-4.0.txt
- LICENSES/MIT.txt
Align with the corresponding files in the
utils/spdx/src/main/resources/licenses
directory.
> chore(reuse): Align formatting of files in the `LICENSES` directory

- plugins/package-managers/node/src/test/kotlin/utils/NpmSupportTest.kt
> test(node): Create JSON object from JSON strings

- integrations/jenkins/Jenkinsfile
- plugins/commands/reporter/src/main/kotlin/ReporterCommand.kt
> Expose report formats and their options as Jenkins pipeline job parameters 

- cli/src/funTest/kotlin/OrtMainFunTest.kt
- plugins/commands/api/src/main/kotlin/utils/Extensions.kt
- plugins/commands/evaluator/src/main/kotlin/EvaluatorCommand.kt
- utils/scripting/src/main/kotlin/ScriptRunner.kt
> Evaluator chores

- .github/workflows/website-deploy.yml
- .github/workflows/website-test.yml
> ci(github): Hard-code Ubuntu 22.04 for website deployment

- plugins/version-control-systems/git/src/main/kotlin/Git.kt
- plugins/version-control-systems/git/src/main/kotlin/GitWorkingTree.kt
This partly reverts c4a628d which introduced an URL replacement when getting nested provenance for Git working trees. That was only necessary because Git's `insteadOf` was not properly configured for submodules: `git config` needs to be called for each submodule separately instead of using Git's `-c` option.
> fix(git): Properly configure `insteadOf` for submodules

- plugins/commands/requirements/src/main/kotlin/RequirementsCommand.kt
- plugins/package-managers/gradle-inspector/src/funTest/kotlin/GradleFunTest.kt
- plugins/package-managers/gradle/src/funTest/kotlin/GradleFunTest.kt
- plugins/package-managers/sbt/src/funTest/kotlin/SbtFunTest.kt
- plugins/version-control-systems/git/src/funTest/kotlin/GitFunTest.kt
- plugins/version-control-systems/git/src/main/kotlin/Git.kt
> Introduce a separate `GitCommand` class

- plugins/package-managers/pub/src/funTest/assets/projects/external/dart-http-expected-output.yml
- plugins/package-managers/pub/src/funTest/assets/projects/synthetic/pub-expected-output-with-flutter-android-and-cocoapods.yml
- plugins/package-managers/pub/src/funTest/kotlin/PubFunTest.kt
This reverts commit 6de1aae as 0206c8f now frees additional disk space.
> Revert "test(pub): Temporarily disable `PubFunTest`"

- model/src/main/kotlin/OrtResult.kt
- model/src/test/kotlin/OrtResultTest.kt
- plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
- plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
- plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
> model: Handle `Issue.affectedPath` in `OrtResult`

- .github/workflows/build-and-test.yml
> Some Gradle CI build improvements

- plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml
- plugins/reporters/opossum/src/funTest/assets/reporter-test-input.yml
- plugins/reporters/static-html/src/funTest/assets/reporter-test-input.yml
> test(reporters): Fix-up an inconsistent scan issue

- model/src/main/kotlin/AdvisorResult.kt
- plugins/advisors/osv/src/main/kotlin/Osv.kt
- plugins/reporters/asciidoc/src/main/resources/templates/asciidoc/vulnerability_report.ftl
> Advisor results optimizations

- plugins/package-managers/node/src/main/kotlin/Npm.kt
- utils/spdx/src/main/kotlin/model/SpdxDocument.kt
- utils/spdx/src/main/kotlin/model/SpdxFile.kt
- utils/spdx/src/main/kotlin/model/SpdxPackage.kt
- utils/spdx/src/main/kotlin/model/SpdxSnippet.kt
> SPDX vs NPM project-package name improvements

- clients/scanoss/src/main/kotlin/ScanOssService.kt
fix: Update the official REST API URL
Updated API URL value.
> fix(scanoss): Update the official REST API URL

- plugins/reporters/web-app-template/src/App.css
- plugins/reporters/web-app-template/src/components/IssuesTable.jsx
- plugins/reporters/web-app-template/src/components/VulnerabilitiesTable.jsx
> Web-app chores

- plugins/reporters/static-html/src/main/kotlin/StaticHtmlReporter.kt
- plugins/reporters/static-html/src/main/kotlin/TablesReport.kt
- plugins/reporters/static-html/src/main/kotlin/TablesReportModelMapper.kt
> reporter: Further clean-up the code of the static HTML plugin

- buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
- plugins/scanners/scanoss/build.gradle.kts
Refactor the code a little bit along the way.
> build(gradle): Use the dedicated `optIn` DSL for Kotlin compiler options

- plugins/reporters/static-html/src/funTest/assets/static-html-reporter-test-expected-output.html
- plugins/reporters/static-html/src/main/kotlin/TablesReportModelMapper.kt
> feat(static-html): Also show advisor issues in the project tables

- model/src/main/kotlin/OrtResult.kt
- plugins/reporters/static-html/src/funTest/assets/static-html-reporter-test-expected-output.html
This fixes the logic introduced by 6a84fa2.
> fix(model): Fix-up filtering excluded issues

- utils/spdx/src/main/kotlin/SpdxExpression.kt
- utils/spdx/src/test/kotlin/SpdxExpressionTest.kt
> Some spdx-utils improvements

- plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelMapper.kt
> feat(evaluated-model): Allow for shorter turn-around times seeing narrowed down VCS paths in findings

- clients/osv/src/funTest/assets/vulnerabilities-by-commit-expected-result.json
- plugins/package-managers/pub/src/funTest/assets/projects/external/dart-http-expected-output.yml
> Test result updates

- plugins/package-managers/node/src/main/kotlin/Yarn2.kt
> Yarn2 chores

- plugins/package-managers/pub/src/main/kotlin/Pub.kt
- plugins/package-managers/pub/src/main/kotlin/utils/PubCacheReader.kt
> Add Flutter version option

- model/src/main/kotlin/FileFormat.kt
- model/src/test/kotlin/FileFormatTest.kt
> chore(model): Reject reading multiple YAML documents per file

- .github/workflows/docker-build.yml
> Fix Docker builds for external PRs

- plugins/scanners/fossid/src/main/kotlin/FossId.kt
- plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt
Generate ignore rules from path excludes in _.ort.yml_ also if FossID delta scans are disabled.
> fix(fossid-webapp): Generate ignore rules also for non-delta scans

- scanner/src/main/kotlin/Scanner.kt
- scanner/src/test/kotlin/ScannerTest.kt
When calling storage writers to store provenance scan results produced by package scanners, make sure that writers are invoked only once for each distinct combination of provenance and scan result. Before this change, if there were multiple root projects in a repository, the writers were called for each of them with the same scan result. This could lead to duplication when storing results.
> fix(scanner): Store only distinct results of package scanners

- plugins/scanners/fossid/src/main/kotlin/FossId.kt
- plugins/scanners/fossid/src/main/kotlin/Utils.kt
- plugins/scanners/fossid/src/test/kotlin/LegacyRulesTest.kt
- plugins/scanners/fossid/src/test/kotlin/MapIgnoreRulesTest.kt
> FossId refactorings

- clients/bazel-module-registry/src/funTest/kotlin/BazelModuleRegistryClientFunTest.kt
- clients/bazel-module-registry/src/main/kotlin/BazelModuleRegistryService.kt
- clients/bazel-module-registry/src/main/kotlin/LocalBazelModuleRegistryService.kt
- clients/bazel-module-registry/src/main/kotlin/RemoteBazelModuleRegistryService.kt
- plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-local-registry/.bazelrc
- plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-local-registry/MODULE.bazel.lock
- plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-local-registry/registry/bazel_registry.json
- plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
- plugins/package-managers/bazel/src/main/kotlin/BazelModel.kt
- plugins/package-managers/bazel/src/test/kotlin/BazelTest.kt
> Bazel improvements

- clients/dos/src/main/kotlin/DosClient.kt
- plugins/package-configuration-providers/dos/src/main/kotlin/DosPackageConfigurationProvider.kt
> DOS chores

- clients/bazel-module-registry/build.gradle.kts
- clients/clearly-defined/build.gradle.kts
- clients/dos/build.gradle.kts
- clients/github-graphql/build.gradle.kts
- clients/nexus-iq/build.gradle.kts
- clients/oss-index/build.gradle.kts
- clients/osv/build.gradle.kts
- clients/scanoss/build.gradle.kts
- clients/vulnerable-code/build.gradle.kts
- evaluator/build.gradle.kts
- gradle/libs.versions.toml
- plugins/advisors/osv/build.gradle.kts
- plugins/package-managers/bazel/build.gradle.kts
- plugins/package-managers/cargo/build.gradle.kts
- plugins/package-managers/go/build.gradle.kts
- plugins/package-managers/nuget/build.gradle.kts
- plugins/package-managers/python/build.gradle.kts
- plugins/package-managers/swiftpm/build.gradle.kts
- plugins/reporters/ctrlx/build.gradle.kts
- plugins/reporters/gitlab/build.gradle.kts
- plugins/reporters/trustsource/build.gradle.kts
- plugins/scanners/askalono/build.gradle.kts
- plugins/scanners/boyterlc/build.gradle.kts
- plugins/scanners/dos/build.gradle.kts
- plugins/scanners/licensee/build.gradle.kts
- plugins/scanners/scancode/build.gradle.kts
- plugins/scanners/scanoss/build.gradle.kts
- scanner/build.gradle.kts
> Gradle cleanups

- plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
- plugins/package-managers/bazel/src/main/kotlin/BazelModel.kt
> Bazel chores

- plugins/package-managers/stack/src/main/kotlin/Model.kt
- plugins/package-managers/stack/src/main/kotlin/Stack.kt
> Stack chores

- gradle/libs.versions.toml
- plugins/package-managers/bundler/build.gradle.kts
- plugins/package-managers/bundler/src/funTest/assets/projects/synthetic/bundler-expected-output-gemspec.yml
- plugins/package-managers/bundler/src/main/kotlin/Bundler.kt
- plugins/package-managers/bundler/src/main/kotlin/Model.kt
- plugins/package-managers/bundler/src/test/kotlin/BundlerTest.kt
> Migrate Bundler to KxS

- plugins/scanners/dos/src/main/kotlin/DosScanner.kt
- plugins/scanners/fossid/src/main/kotlin/FossId.kt
> Allow to configure scan storage settings for DOS

- plugins/package-managers/stack/src/main/kotlin/Stack.kt
- plugins/package-managers/stack/src/test/kotlin/StackTest.kt
> Further stack improvements

- clients/dos/src/main/kotlin/DosClient.kt
- clients/dos/src/main/kotlin/DosModel.kt
- plugins/scanners/dos/src/main/kotlin/DosScanner.kt
- plugins/scanners/dos/src/test/kotlin/DosScannerTest.kt
> DOS: Send declared license in requests

- plugins/package-managers/stack/build.gradle.kts
- plugins/package-managers/stack/src/main/kotlin/Model.kt
- plugins/package-managers/stack/src/main/kotlin/Stack.kt
> Migrate Stack from Jackson to KxS

- plugins/package-managers/stack/src/main/kotlin/Stack.kt
> Stack follow ups

- renovate.json
> Renovate chores

- plugins/reporters/ctrlx/build.gradle.kts
- plugins/reporters/ctrlx/src/main/kotlin/CtrlXAutomationModel.kt
> Ctrl-X reporter build improvements

- .github/workflows/build-and-test.yml
- .github/workflows/static-analysis.yml
- README.md
> Add an OpenSSF Scorecard

- plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt
> More CycloneDX improvements

- plugins/package-managers/cocoapods/build.gradle.kts
- plugins/package-managers/cocoapods/src/main/kotlin/Lockfile.kt
> Cocoapods: Also port the lockfile parsing to KxS

- plugins/package-managers/conan/build.gradle.kts
- plugins/package-managers/conan/src/main/kotlin/Conan.kt
> conan: Finish the porting from Jackson to KxS

- model/src/main/kotlin/HashAlgorithm.kt
This allows to simply code a bit and to implement consistency checks for string lengths.
> refactor(model): Teach hash algorithms about their value string size

- plugins/package-managers/bower/src/main/kotlin/Bower.kt
- plugins/package-managers/bower/src/main/kotlin/Model.kt
> Bower: Miscellaneous clean-ups

- renovate.json
- website/package-lock.json
- website/package.json
> Update website to Docusaurus 3.4.0

- model/src/main/kotlin/Scope.kt
- plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
- plugins/package-managers/bower/src/main/kotlin/Bower.kt
- plugins/package-managers/cocoapods/src/main/kotlin/CocoaPods.kt
- plugins/package-managers/pub/src/funTest/kotlin/PubFunTest.kt
- plugins/package-managers/stack/src/main/kotlin/Stack.kt
> Bower: Further simplify and clarify

- plugins/package-managers/composer/src/main/kotlin/Composer.kt
- plugins/package-managers/composer/src/main/kotlin/Model.kt
> Composer chores

- plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt
Make use of a new CycloneDX API to create formats from extensions.
> refactor(cyclonedx): Map extension strings to typed formats

- plugins/scanners/scanoss/build.gradle.kts
- plugins/scanners/scanoss/src/main/kotlin/ScanOssResultParser.kt
- plugins/scanners/scanoss/src/test/kotlin/ScanOssResultParserTest.kt
- plugins/scanners/scanoss/src/test/kotlin/ScanOssScannerDirectoryTest.kt
> Scanoss parser fixes

- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt
> Add more SPDX creation info options

- plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModelMapper.kt
This fixes scan results eventually being swallowed on Windows with ScanCode 32.
> fix(scancode): Make path comparisons separator-agnostic

- buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
- model/src/main/kotlin/Hash.kt
- model/src/main/kotlin/HashAlgorithm.kt
- plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
- plugins/package-managers/spdx/src/test/kotlin/utils/SpdxResolvedDocumentTest.kt
- utils/common/src/main/kotlin/Extensions.kt
- utils/common/src/test/kotlin/ExtensionsTest.kt
- utils/scripting/src/main/kotlin/OrtScriptCompilationConfiguration.kt
- utils/spdx/src/main/kotlin/Utils.kt
> refactor: Use hex coding from Kotlin's stdlib

- website/docs/tools/reporter.md
This is not related to making sounds.
> docs(website): Fix the full AOSD reporter name

- model/src/main/kotlin/LicenseFinding.kt
- model/src/main/kotlin/Snippet.kt
- plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt
- plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
- plugins/scanners/fossid/src/test/kotlin/FossIdLicenseMappingTest.kt
- plugins/scanners/scanoss/src/main/kotlin/ScanOssResultParser.kt
@nnobelis, please confirm that this aligns the mapping to the ORT model with how the FossID implementation does it.
> fix(scanoss): Support multiple line ranges per snippet

- plugins/package-managers/composer/src/main/kotlin/Composer.kt
> Minor Composer improvements

- clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
- clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
> Small ClearlyDefined related clean-ups

- website/docs/tools/analyzer.md
> Analyzer clarifications

- plugins/package-managers/pub/src/main/kotlin/Pub.kt
> Minor Pub imtprovements

- downloader/src/main/kotlin/WorkingTreeCache.kt
- plugins/package-managers/gradle-inspector/build.gradle.kts
- plugins/package-managers/gradle/build.gradle.kts
- plugins/package-managers/sbt/build.gradle.kts
- utils/common/src/test/kotlin/ExtensionsTest.kt
> Add tests for recurively deleting directories

- analyzer/src/main/kotlin/AnalyzerResultBuilder.kt
- analyzer/src/main/kotlin/Extensions.kt
- analyzer/src/main/kotlin/PackageManagerDependency.kt
- analyzer/src/main/kotlin/PackageManagerDependencyHandler.kt
- analyzer/src/main/kotlin/ResolvableDependencyNode.kt
- analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
- plugins/package-managers/pub/src/main/kotlin/Pub.kt
- plugins/package-managers/spdx/src/main/kotlin/SpdxDocumentFile.kt
> Refactor package manager dependency handling for readability

- analyzer/src/main/kotlin/PackageManagerDependency.kt
- analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
- model/src/main/kotlin/DependencyGraphNavigator.kt
> Dependency graph chores

- clients/osv/src/main/kotlin/Model.kt
> Small OSV improvements

- integrations/completions/ort-completion.fish
- plugins/advisors/nexus-iq/src/main/kotlin/NexusIq.kt
- plugins/advisors/oss-index/src/main/kotlin/OssIndex.kt
- plugins/advisors/oss-index/src/test/kotlin/OssIndexTest.kt
- plugins/advisors/osv/src/funTest/assets/retrieve-package-findings-expected-result.json
- plugins/advisors/osv/src/main/kotlin/Osv.kt
- plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt
- plugins/api/src/main/kotlin/OrtPlugin.kt
- plugins/api/src/main/kotlin/PluginDescriptor.kt
- plugins/compiler/src/main/kotlin/PluginSpecFactory.kt
- plugins/package-configuration-providers/dir/src/main/kotlin/DirPackageConfigurationProvider.kt
- plugins/package-configuration-providers/dos/src/main/kotlin/DosPackageConfigurationProvider.kt
- plugins/package-configuration-providers/ort-config/src/main/kotlin/OrtConfigPackageConfigurationProvider.kt
- plugins/package-curation-providers/clearly-defined/src/main/kotlin/ClearlyDefinedPackageCurationProvider.kt
- plugins/package-curation-providers/file/src/main/kotlin/FilePackageCurationProvider.kt
- plugins/package-curation-providers/ort-config/src/main/kotlin/OrtConfigPackageCurationProvider.kt
- plugins/package-curation-providers/sw360/src/main/kotlin/Sw360PackageCurationProvider.kt
> Make plugin ID configurable

- model/src/main/kotlin/vulnerabilities/VulnerabilityReference.kt
- model/src/test/kotlin/AdvisorResultTest.kt
> Small vulnerability model improvements

- plugins/package-managers/node/src/main/kotlin/Yarn2.kt
> Yarn2: Improve some variable names

- plugins/package-managers/node/src/main/kotlin/utils/NpmSupport.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/PackageInfo.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
- plugins/package-managers/node/src/main/resources/META-INF/services/org.ossreviewtoolkit.analyzer.PackageManagerFactory
- plugins/package-managers/node/src/test/kotlin/yarn2/Yarn2Test.kt
> Yarn2: Improve code for deserializing `yarn info` output

- plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/multi-kotlin-project-expected-output-cli.yml
- plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/multi-kotlin-project-expected-output-core.yml
- plugins/package-managers/gradle-inspector/src/main/kotlin/GradleDependencyHandler.kt
- plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt
> Some `GradleInspector` fixes

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/ort-base-conventions.gradle.kts
- gradle/libs.versions.toml
- plugins/package-managers/gradle-plugin/build.gradle.kts
> Use the `reproducible-builds` Gradle plugin

- plugins/advisors/osv/src/funTest/assets/retrieve-package-findings-expected-result.json
- plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output-archive-override.yml
Data was dumped with
jsonMapper.writerWithDefaultPrettyPrinter().writeValueAsString(packageFindings)
> test(osv): Update expected results

- plugins/package-managers/sbt/src/main/kotlin/Sbt.kt
> Allow to configure the SBT version, and Java version / home

- plugins/package-managers/gradle-inspector/src/funTest/kotlin/GradleFunTest.kt
- plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
- plugins/package-managers/gradle/src/funTest/kotlin/GradleFunTest.kt
- plugins/package-managers/gradle/src/main/kotlin/Gradle.kt
- plugins/package-managers/sbt/src/main/kotlin/Sbt.kt
- utils/common/src/main/kotlin/Os.kt
- utils/ort/src/main/kotlin/Environment.kt
- utils/ort/src/main/kotlin/JavaBootstrapper.kt
- utils/ort/src/test/kotlin/JavaBootstrapperTest.kt
- utils/scripting/src/main/kotlin/OrtScriptCompilationConfiguration.kt
- utils/test/src/main/kotlin/Utils.kt
> Improve JDK detection for bootstrapping

- plugins/package-managers/go/src/main/kotlin/GoMod.kt
Reduce a bit of code duplication by merging these functions. While at it, rename the function to `getModuleInfo()` as "information" has no plural, and keep the sequence for possible optimizations.
> refactor(go): Combine `getProjectName()` into `getModuleInfo()`

- plugins/package-managers/node/src/main/kotlin/Npm.kt
- plugins/package-managers/node/src/main/kotlin/PackageJson.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
- plugins/package-managers/node/src/test/kotlin/PackageJsonTest.kt
> fix(node): Support deserializing `PackageJson.author` from an array

- clients/clearly-defined/src/main/kotlin/CoordinatesSerializer.kt
- plugins/package-managers/pub/src/main/kotlin/Pubspec.kt
- plugins/reporters/gitlab/src/main/kotlin/GitLabLicenseModel.kt
> Minor KxS clean-ups

- integrations/schemas/ort-configuration-schema.json
- model/src/main/kotlin/config/LicenseFilePatterns.kt
- model/src/main/kotlin/config/ProviderPluginConfiguration.kt
- model/src/main/kotlin/licenses/LicenseInfoResolver.kt
- model/src/main/kotlin/utils/PathLicenseMatcher.kt
- model/src/main/resources/reference.yml
- model/src/test/kotlin/config/OrtConfigurationTest.kt
> Some `LicenseFilePatterns` improvements

- clients/osv/src/main/kotlin/Model.kt
- clients/osv/src/main/kotlin/OsvService.kt
- model/src/main/kotlin/utils/PurlExtensions.kt
- model/src/test/kotlin/utils/PurlUtilsTest.kt
- plugins/advisors/osv/src/main/kotlin/Osv.kt
- plugins/advisors/vulnerable-code/src/funTest/kotlin/VulnerableCodeFunTest.kt
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/dep-tree-expected-output.yml
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/external-sources-expected-output.yml
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/regular-expected-output.yml
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/version-resolution-expected-output.yml
- plugins/package-managers/go/src/funTest/assets/projects/synthetic/gomod/go-as-dep-with-transitive-deps-expected-output.yml
- plugins/package-managers/go/src/funTest/assets/projects/synthetic/gomod/project-with-tests-expected-output.yml
- plugins/package-managers/go/src/funTest/assets/projects/synthetic/gomod/submodules-expected-output.yml
- plugins/package-managers/go/src/funTest/assets/projects/synthetic/gomod/subpkg-expected-output.yml
- plugins/package-managers/go/src/funTest/assets/projects/synthetic/gomod/workspaces-main-module-expected-output.yml
- plugins/package-managers/go/src/funTest/assets/projects/synthetic/gomod/workspaces-sub-module-expected-output.yml
- plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-only-lockfile-v1.yml
- plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-only-lockfile-v2.yml
- plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-only-lockfile-v3.yml
- plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-project-with-lockfile.yml
> Fix `Identifier` to purl conversion

- plugins/scanners/dos/src/main/kotlin/DosScanner.kt
Use recursive downloading to ensure the whole source will be scanned.
> fix(dos): Edit downloading the source to be scanned

- plugins/package-managers/node/src/main/kotlin/Yarn.kt
> feat(yarn): Also log warnings output by `yarn info`

- utils/common/src/main/kotlin/Extensions.kt
Slightly align the wording of code comments while at it. Fixes https://github.com/oss-review-toolkit/ort/issues/9334.
> fix(utils): Support deleting read-only files on Windows

- plugins/reporters/spdx/src/main/kotlin/Extensions.kt
- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt
- utils/spdx/src/main/kotlin/model/SpdxAnnotation.kt
- utils/spdx/src/main/kotlin/model/SpdxChecksum.kt
- utils/spdx/src/main/kotlin/model/SpdxCreationInfo.kt
- utils/spdx/src/main/kotlin/model/SpdxExternalDocumentReference.kt
- utils/spdx/src/main/kotlin/model/SpdxExternalReference.kt
- utils/spdx/src/main/kotlin/model/SpdxExtractedLicenseInfo.kt
- utils/spdx/src/main/kotlin/model/SpdxFile.kt
- utils/spdx/src/main/kotlin/model/SpdxPackage.kt
- utils/spdx/src/main/kotlin/model/SpdxPackageVerificationCode.kt
- utils/spdx/src/main/kotlin/model/SpdxRelationship.kt
- utils/spdx/src/main/kotlin/model/SpdxSnippet.kt
> Miscellaneous SPDX improvements

- plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt
- plugins/reporters/freemarker/src/main/resources/templates/plain-text/NOTICE_DEFAULT.ftl
> Freemarker Template related improvements

- plugins/advisors/vulnerable-code/src/funTest/kotlin/VulnerableCodeFunTest.kt
> Minor VulnerableCode improvements

- plugins/scanners/dos/src/main/kotlin/DosScanner.kt
Please see individual commit messages for details.
> dos: Small changes to help with debugging issues

- analyzer/src/main/kotlin/AnalyzerResultBuilder.kt
Consistently implement the builder pattern.
> refactor(AnalyzerResultBuilder): Introduce an `addProject()` function

- plugins/package-managers/node/src/main/kotlin/PackageJson.kt
> Simplify `package.json` parsing

- plugins/package-managers/conan/src/main/kotlin/Conan.kt
Modularize code to prepare for adding more functionality.
> refactor(conan): Split the function to configure remote authentication

- analyzer/src/main/kotlin/PackageManager.kt
- analyzer/src/test/kotlin/PackageManagerTest.kt
- plugins/package-managers/bower/src/main/kotlin/Bower.kt
- plugins/package-managers/cargo/src/funTest/assets/projects/synthetic/cargo-expected-output.yml
- plugins/package-managers/cargo/src/main/kotlin/Cargo.kt
- plugins/package-managers/conan/src/main/kotlin/Conan.kt
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/babel-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/node-modules-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/package-lock-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/shrinkwrap-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/babel-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/project-with-lockfile-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/babel-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/project-with-lockfile-expected-output.yml
- plugins/package-managers/node/src/funTest/kotlin/npm/NpmFunTest.kt
- plugins/package-managers/node/src/main/kotlin/NpmSupport.kt
- plugins/package-managers/node/src/main/kotlin/PackageJson.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
- plugins/package-managers/node/src/test/kotlin/NpmSupportTest.kt
- plugins/package-managers/node/src/test/kotlin/PackageJsonTest.kt
- plugins/package-managers/pub/src/main/kotlin/Pub.kt
- plugins/package-managers/stack/src/funTest/assets/projects/external/quickcheck-state-machine-expected-output.yml
- plugins/package-managers/stack/src/main/kotlin/Stack.kt
> Parse NPM author email and URL from string primitives 

- clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
- clients/fossid-webapp/src/test/kotlin/FossId2021dot2Test.kt
- clients/fossid-webapp/src/test/kotlin/FossId2023dot1Test.kt
- clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
- clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
- clients/fossid-webapp/src/test/kotlin/FossIdRulesTest.kt
> Some small test simplifictions

- model/src/main/kotlin/utils/DependencyGraphBuilder.kt
- plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
- plugins/package-managers/gradle/src/main/kotlin/Gradle.kt
- plugins/package-managers/maven/src/main/kotlin/Maven.kt
- plugins/package-managers/node/src/main/kotlin/npm/Npm.kt
- plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt
- plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
> Minor dependency graph related improvements

- clients/vulnerable-code/src/main/kotlin/VulnerableCodeService.kt
- plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt
- plugins/advisors/vulnerable-code/src/test/kotlin/VulnerableCodeTest.kt
> Revert a code change that was triggered by a VulnerableCode API bug

- advisor/src/main/kotlin/AdviceProviderFactory.kt
- plugins/commands/advisor/src/main/kotlin/AdvisorCommand.kt
- plugins/package-configuration-providers/api/src/main/kotlin/PackageConfigurationProviderFactory.kt
- plugins/package-curation-providers/api/src/main/kotlin/PackageCurationProviderFactory.kt
> Small KSP-based plugin fixes

- plugins/advisors/vulnerable-code/src/funTest/kotlin/VulnerableCodeFunTest.kt
This is a follow-up to fbfcd0c, apparently the vector data was also wrong.
> test(vulnerable-code): Update expected results

- utils/spdx/src/main/kotlin/SpdxExpression.kt
- utils/spdx/src/test/kotlin/SpdxExpressionChoiceTest.kt
> fix(spdx-utils): Avoid endless recursions with the `and` operator

- clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
- plugins/reporters/aosd/src/funTest/assets/aosd20/aosd.NPM-%40ort-project-with-findings-1.0.json
- plugins/reporters/aosd/src/funTest/assets/aosd20/aosd.NPM-%40ort-project-without-findings-1.0.json
- plugins/reporters/aosd/src/funTest/kotlin/Aosd20ReporterFunTest.kt
- plugins/reporters/aosd/src/main/kotlin/Aosd20Model.kt
- plugins/reporters/ctrlx/src/main/kotlin/CtrlXAutomationReporter.kt
- plugins/reporters/trustsource/src/main/kotlin/TrustSourceReporter.kt
> AOSD chores

- model/src/main/kotlin/config/OrtConfiguration.kt
- utils/ort/src/main/kotlin/OkHttpClientHelper.kt
> Miscellaneous chores

- plugins/package-managers/node/src/main/kotlin/NpmSupport.kt
- plugins/package-managers/node/src/main/kotlin/npm/ModuleInfo.kt
- plugins/package-managers/node/src/main/kotlin/npm/NpmDependencyHandler.kt
- plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
- plugins/package-managers/node/src/test/kotlin/NpmSupportTest.kt
> Small Node imps

- plugins/advisors/osv/src/funTest/kotlin/OsvFunTest.kt
- plugins/advisors/vulnerable-code/src/funTest/kotlin/VulnerableCodeFunTest.kt
- plugins/api/README.md
- plugins/api/src/main/kotlin/PluginDescriptor.kt
- plugins/compiler/src/main/kotlin/PluginFactoryGenerator.kt
- plugins/compiler/src/main/kotlin/PluginSpecFactory.kt
- plugins/package-curation-providers/clearly-defined/src/funTest/kotlin/ClearlyDefinedPackageCurationProviderFunTest.kt
- plugins/package-curation-providers/ort-config/src/funTest/kotlin/OrtConfigPackageCurationProviderFunTest.kt
- plugins/reporters/asciidoc/src/funTest/kotlin/DocBookTemplateReporterFunTest.kt
- plugins/reporters/asciidoc/src/funTest/kotlin/HtmlTemplateReporterFunTest.kt
- plugins/reporters/asciidoc/src/funTest/kotlin/ManPageTemplateReporterFunTest.kt
- plugins/reporters/asciidoc/src/funTest/kotlin/PdfTemplateReporterFunTest.kt
- plugins/reporters/cyclonedx/src/funTest/kotlin/CycloneDxReporterFunTest.kt
- plugins/reporters/evaluated-model/src/funTest/kotlin/EvaluatedModelReporterFunTest.kt
- plugins/reporters/opossum/src/funTest/kotlin/OpossumReporterFunTest.kt
- plugins/reporters/opossum/src/test/kotlin/OpossumReporterTest.kt
- plugins/reporters/web-app/src/funTest/kotlin/WebAppReporterFunTest.kt
Please see the commit message for details.
> Simplify creation of plugin instances in tests

- plugins/reporters/web-app-template/build.gradle.kts
- plugins/reporters/web-app/build.gradle.kts
> Make cross-project sharing of web-app outputs more reliable

- model/src/main/resources/reference.yml
Consistently put the dash in the column that starts the sequence / list.
> chore(model): Align the YAML sequence / list style in `reference.yml`

- utils/ort/src/main/kotlin/JavaBootstrapper.kt
> Fix Java bootstrapping for Temurin

- plugins/reporters/cyclonedx/src/main/kotlin/BomExtensions.kt
- plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt
- plugins/reporters/cyclonedx/src/main/kotlin/Utils.kt
> Reorganize existing CycloneDX code

- plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result-with-findings.json
- plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result-without-findings.json
- plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result.json
- plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result.xml
- plugins/reporters/cyclonedx/src/funTest/kotlin/CycloneDxReporterFunTest.kt
- plugins/reporters/cyclonedx/src/main/kotlin/BomExtensions.kt
- plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt
- reporter/src/testFixtures/kotlin/TestData.kt
> Add the dependency graph to CycloneDX SBOMs

- plugins/reporters/cyclonedx/src/main/kotlin/BomExtensions.kt
- plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt
While at it, also set author information for package components.
See [1] for context.
[1]: https://github.com/oss-review-toolkit/ort/issues/7449
> feat(cyclonedx): Set basic supplier information

- plugins/package-managers/composer/src/main/kotlin/Composer.kt
> Composer improvements

- plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
- plugins/version-control-systems/mercurial/src/main/kotlin/Mercurial.kt
- plugins/version-control-systems/mercurial/src/main/kotlin/MercurialWorkingTree.kt
Prefer to use properly isolated commands.
> refactor: Replace some remaining custom `ProcessCapture` calls

- plugins/package-managers/bower/src/funTest/kotlin/BowerFunTest.kt
- plugins/package-managers/bower/src/main/kotlin/Bower.kt
- plugins/package-managers/bower/src/main/kotlin/BowerDependencyHandler.kt
- plugins/package-managers/bower/src/main/kotlin/Model.kt
> Migrate Bower to the dependency graph API 

- utils/common/src/main/kotlin/FileMatcher.kt
> Some small `FileMatcher` improvements

- .github/workflows/build-and-test.yml
- buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
- evaluator/src/main/kotlin/ProjectSourceRule.kt
- plugins/package-managers/node/src/test/kotlin/NpmDetectionTest.kt
- plugins/package-managers/node/src/test/kotlin/yarn2/Yarn2Test.kt
> Run unit tests on Windows

- plugins/package-managers/bower/src/main/kotlin/BowerDependencyHandler.kt
Also see [1].
[1]: https://jfrog.com/help/r/jfrog-artifactory-documentation/deploy-bower-packages
> docs(bower): Clarify a misleading TODO regardig source artifacts

- website/docs/tools/advisor.md
> website: Advisor docs fixes

- plugins/package-managers/bundler/src/main/kotlin/Bundler.kt
This is a generic function provided by the core of KxS that works with `Json` as well as `Yaml`.
> chore(bundler): Use `StringFormat`'s `decodeFromString`

- plugins/package-managers/gradle/src/main/kotlin/GradleDependencyHandler.kt
- plugins/package-managers/maven/src/main/kotlin/Maven.kt
- plugins/package-managers/maven/src/main/kotlin/utils/MavenDependencyHandler.kt
- plugins/package-managers/maven/src/test/kotlin/utils/MavenDependencyHandlerTest.kt
- plugins/package-managers/sbt/src/main/kotlin/Sbt.kt
- plugins/package-managers/spdx/src/main/kotlin/utils/SpdxResolvedDocument.kt
> Project type preparations

- plugins/package-managers/cocoapods/src/funTest/kotlin/CocoaPodsFunTest.kt
- plugins/package-managers/cocoapods/src/main/kotlin/CocoaPods.kt
- plugins/package-managers/cocoapods/src/main/kotlin/Lockfile.kt
- plugins/package-managers/cocoapods/src/main/kotlin/PodDependencyHandler.kt
- plugins/package-managers/cocoapods/src/main/kotlin/Podspec.kt
> Migrate Cocoapods to use the dependency graph

- plugins/reporters/web-app-template/build.gradle.kts
> deps(web-app-template): Sync the Node / Yarn versions with Docker

- plugins/package-managers/cargo/src/main/kotlin/Cargo.kt
> Some minor Cargo improvements

- plugins/package-managers/cargo/src/main/kotlin/Cargo.kt
Virtual workspaces do not define any packages and thus can simply be filtered out without loosing any information.
Resolves #8874.
> feat(cargo): Handle virtual workspaces

- plugins/package-managers/node/src/main/kotlin/NpmSupport.kt
- plugins/package-managers/node/src/main/kotlin/npm/ModuleInfo.kt
- plugins/package-managers/node/src/main/kotlin/npm/Npm.kt
- plugins/package-managers/node/src/main/kotlin/npm/NpmDependencyHandler.kt
- plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt
- plugins/package-managers/node/src/main/kotlin/pnpm/PnpmDependencyHandler.kt
- plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
- plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
> Node package manager improvements

- website/src/pages/index.js
- website/src/pages/index.module.css
> Fix link color on website

- plugins/package-managers/bazel/src/main/kotlin/StarlarkParser.kt
- plugins/scanners/fossid/src/main/kotlin/FossIdConfig.kt
> Be explicit what to map unparsable booleans to

- plugins/package-curation-providers/clearly-defined/src/main/kotlin/ClearlyDefinedPackageCurationProvider.kt
- plugins/package-curation-providers/ort-config/src/main/kotlin/OrtConfigPackageCurationProvider.kt
End them all with "Package Curation Provider".
> chore(package-curation-providers): Align the display names

- README.md
- website/docs/license.md
> README improvements

- model/src/main/kotlin/PackageCurationData.kt
Do not refer to the `PackageCuration` class here.
> docs(PackageCurationData): Fix the docs for `apply()`

- buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
- website/docs/development.md
> Improve the "detektAll" task

- analyzer/src/main/kotlin/AnalyzerResultBuilder.kt
- plugins/reporters/web-app/src/funTest/assets/scan-result-for-synthetic-gradle-lib.yml
- scanner/src/funTest/assets/scanner-integration-all-pkgs-expected-ort-result.yml
- scanner/src/funTest/assets/scanner-integration-expected-scan-results.yml
- scanner/src/funTest/assets/scanner-integration-subset-pkgs-expected-ort-result.yml
- scanner/src/main/kotlin/ScanStorages.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/provenance/NestedProvenanceStorage.kt
- scanner/src/main/kotlin/provenance/PackageProvenanceStorage.kt
> Capitalize hard-coded issue sources

- plugins/commands/analyzer/src/main/kotlin/AnalyzerCommand.kt
> feat(AnalyzerCommand): Sort output of found definition files

- examples/curations.yml
> docs(examples): Illustrate how to set the Black Duck origin-id

- plugins/commands/advisor/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/analyzer/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/compare/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/config/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/downloader/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/evaluator/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/migrate/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/notifier/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/reporter/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/requirements/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/scanner/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/upload-curations/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/upload-result-to-postgres/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
- plugins/commands/upload-result-to-sw360/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.commands.api.OrtCommand
> chore(commands): Remove obsolete service loader files

- plugins/advisors/black-duck/src/funTest/kotlin/BlackDuckFunTest.kt
- plugins/advisors/black-duck/src/main/kotlin/BlackDuck.kt
- plugins/advisors/oss-index/src/main/kotlin/OssIndex.kt
- plugins/advisors/oss-index/src/test/kotlin/OssIndexTest.kt
- plugins/advisors/osv/src/main/kotlin/Osv.kt
- plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt
- plugins/advisors/vulnerable-code/src/test/kotlin/VulnerableCodeTest.kt
- plugins/package-configuration-providers/dos/src/main/kotlin/DosPackageConfigurationProvider.kt
- plugins/package-curation-providers/clearly-defined/src/funTest/kotlin/ClearlyDefinedPackageCurationProviderFunTest.kt
- plugins/package-curation-providers/clearly-defined/src/main/kotlin/ClearlyDefinedPackageCurationProvider.kt
- plugins/package-curation-providers/clearly-defined/src/test/kotlin/ClearlyDefinedPackageCurationProviderTest.kt
- plugins/package-curation-providers/ort-config/src/main/kotlin/OrtConfigPackageCurationProvider.kt
- plugins/package-curation-providers/sw360/src/main/kotlin/Sw360PackageCurationProvider.kt
- plugins/version-control-systems/git/src/main/kotlin/Git.kt
- plugins/version-control-systems/git/src/main/kotlin/GitRepo.kt
- plugins/version-control-systems/mercurial/src/main/kotlin/Mercurial.kt
- utils/common/src/main/kotlin/CommandLineTool.kt
> Minor plugin improvements

- Dockerfile
- plugins/version-control-systems/git/src/main/kotlin/Git.kt
> feat(Dockerfile): Install the `rng-tools5` package 

- analyzer/src/main/kotlin/Analyzer.kt
- downloader/src/main/kotlin/VersionControlSystem.kt
- model/src/test/kotlin/licenses/ResolvedLicenseInfoTest.kt
- scanner/src/main/kotlin/Scanner.kt
> Companion import chores

- utils/ort/src/test/kotlin/DeclaredLicenseProcessorTest.kt
- utils/spdx/build.gradle.kts
- utils/spdx/src/main/kotlin/SpdxDeclaredLicenseMapping.kt
- utils/spdx/src/main/kotlin/SpdxExpression.kt
- utils/spdx/src/main/kotlin/SpdxLicense.kt
- utils/spdx/src/main/kotlin/SpdxLicenseException.kt
- utils/spdx/src/main/kotlin/SpdxSimpleLicenseMapping.kt
- utils/spdx/src/main/resources/deprecated-license-mapping.yml
- utils/spdx/src/test/kotlin/SpdxExpressionTest.kt
- utils/spdx/src/test/kotlin/SpdxSimpleLicenseMappingTest.kt
> Improvements to SPDX license mappings

- website/docs/tools/analyzer.md
> Improvements to the docs on the website

- plugins/package-managers/maven/src/main/kotlin/Tycho.kt
- plugins/package-managers/maven/src/main/kotlin/utils/P2ArtifactTracker.kt
- plugins/package-managers/maven/src/test/kotlin/utils/P2ArtifactTrackerTest.kt
> Tycho chores

- buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts
- buildSrc/src/main/kotlin/ort-library-conventions.gradle.kts
> GraalVM improvements

- build.gradle.kts
- buildSrc/src/main/kotlin/GeneratePluginDocsTask.kt
> Plugin docs Gradle task improvements

- plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt
- plugins/package-managers/python/src/main/kotlin/Pip.kt
- plugins/package-managers/python/src/main/kotlin/Pipenv.kt
- plugins/package-managers/python/src/main/kotlin/Poetry.kt
> Lockfile vs definition file improvements

- .github/workflows/native-build.yml
- .github/workflows/website-deploy.yml
- .github/workflows/website-test.yml
> Workflow chores

- .github/workflows/native-build.yml
- buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts
> Use GraalVM 24 for the native build

- plugins/package-managers/node/src/main/kotlin/NodePackageManager.kt
- plugins/package-managers/node/src/main/kotlin/npm/ModuleInfo.kt
- plugins/package-managers/node/src/main/kotlin/pnpm/ModuleInfo.kt
- plugins/package-managers/node/src/main/kotlin/yarn/ModuleInfo.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
> Minor node chores

- website/docusaurus.config.js
- website/src/pages/index.js
> Website title page improvements

- model/src/main/kotlin/config/PackageConfiguration.kt
Explain the relationship to `RepositoryConfiguration`.
> docs(model): Improve `PackageConfiguration` class docs

- cli/src/funTest/kotlin/OrtMainFunTest.kt
- model/src/main/kotlin/config/OrtConfiguration.kt
- model/src/test/kotlin/config/OrtConfigurationTest.kt
- plugins/commands/config/src/main/kotlin/ConfigCommand.kt
> Remove the `OrtConfigurationWrapper` class

- plugins/version-control-systems/git/src/main/kotlin/Git.kt
When trying to fetch only the requested revision, each failed attempt introduces a daily of a few seconds. For example, if the provided revision is a branch name, the attempts to use it as a ref spec directly and then to use it as a tag name both fail which delays the subsequent fetch attempts.
Change the algorithm to only try to use the revision as a ref spec directly if it is a valid SHA1, and to load the available ref specs to verify if the revision matches a tag or branch name.
This makes cloning a little bit faster in case the provided revision is a branch name. In case it is a tag name the difference is neglible because loading the available ref specs also takes a bit of time. Also cloning is a bit faster if the revision is neither a SHA1, tag name, or branch name, because the …
> refactor(git): Do not try to fetch ref specs that do not exist

- buildSrc/src/main/kotlin/GitValueSources.kt
- plugins/version-control-systems/git/src/main/kotlin/Git.kt
- plugins/version-control-systems/git/src/main/kotlin/GitRepo.kt
- plugins/version-control-systems/git/src/main/kotlin/GitWorkingTree.kt
> Jgit chores

- plugins/version-control-systems/git/src/main/kotlin/Git.kt
- plugins/version-control-systems/mercurial/src/main/kotlin/Mercurial.kt
- plugins/version-control-systems/mercurial/src/main/kotlin/MercurialWorkingTree.kt
> Improvements to VCS CLI handling

- plugins/package-managers/maven/src/main/kotlin/tycho/Tycho.kt
- plugins/package-managers/maven/src/test/kotlin/tycho/TychoTest.kt
As an optimization, the Tycho implementation had a feature to exclude submodules from the Maven build if they are matched by path excludes and the `skip_excluded` flag is set in the Analyzer configuration. However, this mechanism was not working as expected; it caused the Tycho build to fail with errors about unresolvable modules.
Therefore, drop this optimization and always build all modules.
> fix(Maven): Do not exclude modules during a Tycho build

- downloader/src/main/kotlin/VcsHost.kt
- evaluator/src/main/kotlin/RuleSet.kt
- model/src/main/kotlin/PackageCurationData.kt
- model/src/main/kotlin/utils/Extensions.kt
- plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
- plugins/package-managers/bazel/src/main/kotlin/StarlarkParser.kt
- plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModel.kt
- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt
- scanner/src/main/kotlin/storages/AbstractPackageBasedScanStorage.kt
- utils/spdx/src/main/kotlin/SpdxExpression.kt
- utils/spdx/src/main/kotlin/parser/SpdxExpressionLexer.kt
> Sonar chores

- plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt
- plugins/scanners/askalono/src/main/kotlin/Askalono.kt
- plugins/scanners/boyterlc/src/main/kotlin/BoyterLc.kt
- plugins/scanners/licensee/src/main/kotlin/Licensee.kt
- plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
> Scanner CLI improvements

- scanner/src/funTest/kotlin/storages/AbstractPackageBasedScanStorageFunTest.kt
- scanner/src/main/kotlin/ScannerMatcher.kt
- scanner/src/test/kotlin/ScannerMatcherTest.kt
> Scanner matcher improvements

- model/src/main/kotlin/DependencyGraphNavigator.kt
This PR changes the traversal of the dependency graph.
Before, there was a performance issue that causes Reporter runtimes of >1h. Unfortunately, I cannot provide the ORT result from that project.
Using the ORT result from ORT Server, the CycloneDX SBOM is now created in less than 2 seconds on my machine, while the implementation on main takes ~20 seconds.
This can be reproduced with the [attached ORT result](https://github.com/user-attachments/files/19735469/ort-server-ort-result.zip).
> fix(DependencyGraph): Avoid redundant processing of nodes

- model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
- model/src/test/kotlin/licenses/ResolvedLicenseInfoTest.kt
- plugins/reporters/aosd/src/main/kotlin/Aosd21Reporter.kt
- utils/spdx/src/main/kotlin/SpdxExpression.kt
> Improve reducing SPDX expressions

- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/workspaces-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/workspaces/packages/pkg1/package.json
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/workspaces/yarn.lock
- plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
> Yarn: Fix analyzing workspace projects with interdependent packages

- plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
The disk cache has been used in a way that considers the entries to be globally valid. However, when different registries are used, the same module ID may refer to different packages. So, the use of a disk cache may lead to incorrect results.
Prevent that by using an in-memory cache which reduces the lifetime of the entries to the one of the current analysis. This aligns with `Npm.kt` and `Yarn.kt`.
Part of: #9261.
> feat(yarn): Drop the disk cache in favor of a non-persistent one

- plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
**Before**
**After**
Part of: #9261.
> yarn: Speed-up requesting package details

- plugins/package-managers/node/src/main/kotlin/npm/Npm.kt
- plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt
- plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
> Node chores

- plugins/package-managers/node/src/main/kotlin/PackageJson.kt
While add it drop a double "See".
> docs(node): Re-align a code comment

- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2Command.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2DependencyHandler.kt
A small preparation for a following larger clean-up.
Part of: https://github.com/oss-review-toolkit/ort/issues/9261.
> Minor Yarn2 clean up

- plugins/package-managers/bundler/src/main/kotlin/Bundler.kt
- plugins/package-managers/bundler/src/main/resources/resolve_dependencies.rb
- plugins/package-managers/bundler/src/main/resources/root_dependencies.rb
> Some Bundler improvements

- plugins/package-managers/node/src/main/kotlin/Scope.kt
- plugins/package-managers/node/src/main/kotlin/npm/Npm.kt
- plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt
- plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
Part of: https://github.com/oss-review-toolkit/ort/issues/9261.
> node: Improve and align the code for handling scopes a bit

- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/project-with-lockfile-skip-excluded-scopes-expected-output.yml
- plugins/package-managers/node/src/funTest/kotlin/yarn/YarnFunTest.kt
- plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
- plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
**Performance**
Compare also: https://github.com/oss-review-toolkit/ort/pull/10197.
Part of: https://github.com/oss-review-toolkit/ort/issues/9261.
> Yarn: Implement skipping of excluded scopes

- buildSrc/src/main/kotlin/ort-publication-conventions.gradle.kts
- gradle/libs.versions.toml
- plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt
- plugins/reporters/spdx/src/funTest/kotlin/SpdxDocumentReporterFunTest.kt
- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
- plugins/reporters/static-html/src/funTest/kotlin/StaticHtmlReporterFunTest.kt
- plugins/reporters/static-html/src/main/kotlin/StaticHtmlReporter.kt
- utils/ort/build.gradle.kts
- utils/ort/src/main/kotlin/Constants.kt
- utils/ort/src/main/kotlin/Environment.kt
- utils/ort/src/main/kotlin/JavaBootstrapper.kt
- utils/ort/src/main/kotlin/OkHttpClientHelper.kt
> Use a more portable way to embed the ORT version 

- plugins/package-managers/node/src/main/kotlin/NodePackageManagerSupport.kt
- plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
> Yarn2: Improve the code for getting the remote package details

- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/project-with-lockfile-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/project-with-lockfile-skip-excluded-scopes-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/workspaces-expected-output.yml
- plugins/package-managers/node/src/main/kotlin/NodePackageManagerSupport.kt
- plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/WorkspaceInfo.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2DependencyHandler.kt
Part of: https://github.com/oss-review-toolkit/ort/issues/9261.
> node: Re-write large parts of Yarn2 to reduce complexity

- plugins/package-managers/node/src/main/kotlin/PackageJson.kt
- plugins/package-managers/node/src/test/kotlin/PackageJsonTest.kt
> feat(node): Tolerate empty arrays for dependencies in PackageJson files

- plugins/package-managers/node/src/main/kotlin/NodePackageManager.kt
- plugins/package-managers/node/src/main/kotlin/NodePackageManagerSupport.kt
- plugins/package-managers/node/src/main/kotlin/npm/Npm.kt
> Further minor node chores

- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/project-with-lockfile-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/project-with-lockfile-skip-excluded-scopes-expected-output.yml
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/project-with-lockfile/package.json
- plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/project-with-lockfile/yarn.lock
- plugins/package-managers/node/src/main/kotlin/yarn2/PackageInfo.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
> Yarn2: Support virtual dependencies

- analyzer/src/main/kotlin/Analyzer.kt
- analyzer/src/main/kotlin/PackageManager.kt
- plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
- plugins/package-managers/cargo/src/main/kotlin/Cargo.kt
- plugins/package-managers/composer/src/funTest/kotlin/ComposerFunTest.kt
- plugins/package-managers/composer/src/main/kotlin/Composer.kt
- plugins/package-managers/conan/src/main/kotlin/Conan.kt
- plugins/package-managers/go/src/main/kotlin/GoMod.kt
- plugins/package-managers/maven/src/main/kotlin/Maven.kt
- plugins/package-managers/maven/src/main/kotlin/tycho/Tycho.kt
- plugins/package-managers/maven/src/test/kotlin/MavenTest.kt
- plugins/package-managers/maven/src/test/kotlin/tycho/TychoTest.kt
- plugins/package-managers/node/src/main/kotlin/NodePackageManager.kt
- plugins/package-managers/node/src/main/kotlin/NodePackageManagerDetection.kt
- plugins/package-managers/node/src/main/kotlin/npm/Npm.kt
- plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt
- plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
- plugins/package-managers/sbt/src/main/kotlin/Sbt.kt
- plugins/package-managers/spdx/src/funTest/kotlin/SpdxDocumentFileFunTest.kt
- plugins/package-managers/spdx/src/main/kotlin/SpdxDocumentFile.kt
- plugins/package-managers/swiftpm/src/main/kotlin/SwiftPm.kt
- utils/common/src/main/kotlin/MiscUtils.kt
> Fix the Node package manager fallback in case not all managers are enabled

- renovate.json
> Tweak Renovate

- plugins/package-managers/node/src/main/kotlin/ModuleInfoResolver.kt
- plugins/package-managers/node/src/main/kotlin/Utils.kt
- plugins/package-managers/node/src/main/kotlin/npm/Npm.kt
- plugins/package-managers/node/src/main/kotlin/npm/NpmDependencyHandler.kt
- plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt
- plugins/package-managers/node/src/main/kotlin/pnpm/PnpmDependencyHandler.kt
- plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
- plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
- plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2DependencyHandler.kt
Note: Performance is not affected by this PR.
> Node: Properly use the `workingDir` when executing the `* info` commands

- model/src/main/kotlin/TextLocation.kt
- plugins/reporters/fossid/src/main/resources/templates/asciidoc/fossid_snippet.ftl
- plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt
- plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
> `TextLocation` improvements

- plugins/package-managers/cocoapods/build.gradle.kts
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/react-native-expected-output.yml
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/react-native/ios/Podfile
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/react-native/ios/Podfile.lock
- plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/react-native/package.json
- plugins/package-managers/cocoapods/src/funTest/kotlin/CocoaPodsFunTest.kt
- plugins/package-managers/cocoapods/src/main/kotlin/CocoaPods.kt
- plugins/package-managers/cocoapods/src/main/kotlin/PodDependencyHandler.kt
> Cocoapods: Add some support for React Native

- plugins/package-managers/cocoapods/src/main/kotlin/PodDependencyHandler.kt
Reduce the level of nesting. Also note that the `return` within the else block was previously superfluous.
> chore(cocoapods): Avoid an else block for readability

- analyzer/src/funTest/kotlin/PackageManagerFunTest.kt
- plugins/commands/evaluator/src/test/kotlin/EvaluateCommandTest.kt
> Plugin IDs handling improvements

- gradle/gradle-daemon-jvm.properties
> Add Gradle daemon toolchain URLs

- model/src/main/kotlin/utils/DependencyGraphBuilder.kt
- model/src/test/kotlin/utils/DependencyGraphBuilderTest.kt
Use a more readable representation of IDs.
> chore(model): Improve the failure message when checking references

- Dockerfile
> fix(docker): Correct the .NET version being printed

- model/src/main/kotlin/utils/Extensions.kt
- model/src/main/kotlin/utils/PathLicenseMatcher.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/main/kotlin/utils/Utils.kt
> Model chores

- utils/ort/src/main/kotlin/CopyrightStatementsProcessor.kt
> `CopyrightStatementsProcessor` readability improvements

- utils/ort/src/main/kotlin/CopyrightStatementsProcessor.kt
> Minor copyright statements processor clean ups

- plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
Code the fallback to empty set only once.
> refactor(bazel): Slightly simplify a case distinction

- plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModel.kt
- plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModelMapper.kt
- plugins/scanners/scancode/src/main/kotlin/ScanCodeResultParser.kt
- plugins/scanners/scancode/src/main/kotlin/model/CopyrightEntry.kt
- plugins/scanners/scancode/src/main/kotlin/model/FileEntry.kt
- plugins/scanners/scancode/src/main/kotlin/model/LicenseEntry.kt
- plugins/scanners/scancode/src/main/kotlin/model/ScanCodeResult.kt
> ScanCode result model improvements

- plugins/compiler/src/main/kotlin/PluginFactoryGenerator.kt
- plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
- plugins/scanners/scancode/src/main/kotlin/ScanCodeConfig.kt
> chore(scancode): Make `commandLineNonConfig` non-nullable to simplify code

- plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan2-expected-output-py.yml
- plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan2-expected-output-txt.yml
TBD if this is required.
EDIT: it seems it is. Please review.
> test(conan): Update expected results

- plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
> gradle-inspector: Avoid a type cast

- plugins/reporters/spdx/src/funTest/kotlin/SpdxDocumentReporterFunTest.kt
- plugins/reporters/spdx/src/main/kotlin/Extensions.kt
- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt
> Add a reporter option to write SPDX 2.3

- plugins/reporters/spdx/src/funTest/kotlin/SpdxDocumentReporterFunTest.kt
- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt
- utils/spdx-document/src/main/kotlin/model/SpdxDocument.kt
> SpdxDocumentReporter test improvements

- plugins/reporters/spdx/src/main/kotlin/Extensions.kt
- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
- plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt
> Minor `Spdx-2.3` follow ups

- plugins/scanners/scancode/src/main/kotlin/model/FileEntry.kt
- plugins/scanners/scancode/src/main/kotlin/model/LicenseEntry.kt
> Minor ScanCode improvements

- clients/fossid-webapp/src/main/kotlin/Extensions.kt
- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- clients/fossid-webapp/src/main/kotlin/model/RemoveUploadContentResponse.kt
- clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
- clients/fossid-webapp/src/test/resources/return-type/mappings/apiphp-extract-archives.json
- clients/fossid-webapp/src/test/resources/return-type/mappings/apiphp-remove_uploaded_content.json
- clients/fossid-webapp/src/test/resources/return-type/mappings/apiphp-remove_uploaded_content_error.json
- clients/fossid-webapp/src/test/resources/return-type/mappings/apiphp-upload_file.json
- clients/fossid-webapp/src/test/resources/return-type/mappings/apiphp-upload_file_chunk1.json
- clients/fossid-webapp/src/test/resources/return-type/mappings/apiphp-upload_file_chunk2.json
This is preliminary work for solving https://github.com/oss-review-toolkit/ort/issues/4242.
> FossID: add 3 new API functions to the FossID client

- cli/src/main/resources/logback.xml
- clients/fossid-webapp/src/main/kotlin/Extensions.kt
- clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
- plugins/scanners/fossid/src/main/kotlin/FossId.kt
- plugins/scanners/fossid/src/main/kotlin/FossIdConfig.kt
- plugins/scanners/fossid/src/main/kotlin/events/CloneRepositoryHandler.kt
- plugins/scanners/fossid/src/main/kotlin/events/EventHandler.kt
- plugins/scanners/fossid/src/main/kotlin/events/UploadArchiveHandler.kt
- plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt
- plugins/scanners/fossid/src/test/kotlin/TestUtils.kt
> FossID: Archive upload mode

- plugins/scanners/fossid/src/main/kotlin/events/CloneRepositoryHandler.kt
- plugins/scanners/fossid/src/test/kotlin/events/CloneRepositoryHandlerTest.kt
> FossID chores

- plugins/package-managers/swiftpm/src/main/kotlin/SwiftPm.kt
- plugins/package-managers/swiftpm/src/main/kotlin/SwiftPmModel.kt
> Minor Swift follow-up improvements

- plugins/scanners/dos/src/main/kotlin/DosScanner.kt
- plugins/scanners/dos/src/test/kotlin/DosScannerTest.kt
- scanner/src/main/kotlin/Scanner.kt
- scanner/src/test/kotlin/ScannerTest.kt
This PR introduces a change for package scanners, where an exception from `scanPackage` is caught and an issue is saved to the `OrtResult`. This allows to not have to save a fake result for a failing scan of a specific provenance in order to attempt the scanning of other provenances. This PR also changes the behavior of the DOS scanner so that it no longer saves fake results if a scan fails.
I realize that the first commit may be too simple, in some cases it probably doesn't make sense to try the scanning of other provenances at all, so perhaps a specific kind of exception is needed that should be thrown further in the `onFailure` block, but I'm opening this for discussion already.
> A change to exception handling for package scanners & don't create fake results for failed scans on DOS scanner

- scanner/src/main/kotlin/Scanner.kt
- scanner/src/test/kotlin/ScannerTest.kt
In case of a failure from `scanProvenance`, catch the exception and save an issue to the `OrtResult` instead of failing completely. This will make the behavior consistent with recent changes to path scanners [1] and package scanners [2].
[1]: https://github.com/oss-review-toolkit/ort/pull/10475/commits/fd11299777bd7c34a126d79a387b61e5a0f5a523
[2]: https://github.com/oss-review-toolkit/ort/pull/10696/commits/cab6feb448aa9420c8ed1b29c249f4b51497af5b
> refactor(scanner): Catch an exception from `scanProvenance`

- model/src/main/kotlin/Defect.kt
- model/src/main/kotlin/DependencyGraph.kt
- model/src/main/kotlin/Package.kt
- model/src/main/kotlin/PackageReference.kt
- model/src/main/kotlin/Project.kt
- model/src/main/kotlin/config/RepositoryConfiguration.kt
- model/src/main/kotlin/vulnerabilities/VulnerabilityReference.kt
- plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt
> Jackson-related improvements

- gradle/libs.versions.toml
- utils/test/build.gradle.kts
- utils/test/src/main/kotlin/SystemEnvironmentExtensions.kt
In particular, stick to a configurable `OverrideMode` to be able to share this with ORT Server which depends on that feature.
> feat(test-utils): Stay closer to upstream `SystemEnvironmentExtensions`

- analyzer/src/main/kotlin/Analyzer.kt
- integrations/completions/ort-completion.bash
- integrations/completions/ort-completion.fish
- integrations/completions/ort-completion.zsh
- plugins/commands/compare/src/main/kotlin/CompareCommand.kt
- scanner/src/funTest/resources/scanner-integration-all-pkgs-expected-ort-result.yml
- scanner/src/funTest/resources/scanner-integration-subset-pkgs-expected-ort-result.yml
- scanner/src/main/kotlin/Scanner.kt
- utils/ort/src/main/kotlin/Environment.kt
> Remove `toolVersions` from `Environment`

- model/src/main/kotlin/OrtResult.kt
- model/src/test/kotlin/OrtResultTest.kt
- model/src/test/kotlin/PackageCurationTest.kt
> Increase test coverage for declared license mappings

- plugins/scanners/scanoss/src/main/kotlin/ScanOssResultParser.kt
- plugins/scanners/scanoss/src/test/kotlin/ScanOssResultParserTest.kt
- plugins/scanners/scanoss/src/test/kotlin/ScanOssScannerDirectoryTest.kt
> feat(scanoss): Add extra information to snippets

- integrations/schemas/ort-configuration-schema.json
- model/src/main/kotlin/config/LicenseFilePatterns.kt
- model/src/main/resources/reference.yml
Relates to #6399. This will cause these files to get archived, but not used yet by default.
> feat(model): Add the concept of NOTICE file patterns

- plugins/scanners/fossid/src/main/kotlin/FossId.kt
- plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt
- plugins/scanners/fossid/src/test/kotlin/TestUtils.kt
> FossID fixes

- .flox/.gitattributes
- .flox/.gitignore
- .flox/env.json
- .flox/env/manifest.lock
- .flox/env/manifest.toml
- .github/workflows/build-and-test.yml
- downloader/src/funTest/kotlin/VersionControlSystemFunTest.kt
- downloader/src/test/kotlin/VersionControlSystemTest.kt
> Use Flox to run unit tests on Linux / non-Windows in a minimal / isolated environment

- clients/osv/src/main/kotlin/Model.kt
- clients/osv/src/main/kotlin/OsvService.kt
> Support OSV credit type

- plugins/package-managers/pub/src/funTest/assets/projects/external/dart-http-expected-output.yml
- plugins/package-managers/sbt/src/funTest/assets/projects/external/multi-project-expected-output.yml
> Update expected results for Pub and Sbt

- plugins/package-managers/bundler/src/main/kotlin/Bundler.kt
- plugins/package-managers/bundler/src/main/resources/resolve_dependencies.rb
- plugins/package-managers/bundler/src/main/resources/root_dependencies.rb
> Bundler improvements

- REUSE.toml
> Reuse 6 fixes
