plugins/package-configuration-providers/build.gradle.kts

These are set via the `ort-plugins-conventions` plugin already. This
fixes the `ort-config` plugin to be part of the platform.

chore(package-configuration-providers): Remove superfluous declarations

---

advisor/src/funTest/assets/retrieve-package-findings-expected-result.json
clients/osv/src/funTest/assets/vulnerabilities-by-commit-expected-result.json
clients/osv/src/funTest/assets/vulnerabilities-by-name-and-version-expected-result.json
clients/osv/src/funTest/assets/vulnerability-by-id-expected-result.json
clients/osv/src/main/kotlin/Model.kt
clients/osv/src/main/kotlin/Serializers.kt
clients/osv/src/test/assets/vulnerability/examples/1.json
clients/osv/src/test/assets/vulnerability/examples/2.json
clients/osv/src/test/assets/vulnerability/examples/3.json
clients/osv/src/test/assets/vulnerability/examples/4.json
clients/osv/src/test/assets/vulnerability/examples/5.json
clients/osv/src/test/assets/vulnerability/examples/6.json
clients/osv/src/test/assets/vulnerability/examples/7.json

Some, but not all, OSV requests now return "typed" events where the
event type and value are serialized to separate fields. This is the
natural serialization format that kotlinx-serialization would use for
the `Event` class via the auto-generated deserializer.
However, some queries still return the single-line format for events.
This means the auto-generated deserializer should be used by default, and
a custom deserializer that understands the single-line format should be
used as a fallback. The current approach of a low-level `KSerializer`
is not very suitable to handle this case, as trying to decode one format
would advance in the input, leaving incomplete input to the fallback
deserializer if the first deserializer fails.
To solve this, a `JsonTransformingSerializer` is used instead …

fix(osv): Account for typed events being introduced in the model

---

clients/osv/src/funTest/assets/vulnerabilities-by-commit-expected-result.json
clients/osv/src/funTest/assets/vulnerabilities-by-name-and-version-expected-result.json
clients/osv/src/funTest/assets/vulnerability-by-id-expected-result.json
clients/osv/src/main/kotlin/Model.kt
clients/osv/src/main/kotlin/Serializers.kt
clients/osv/src/test/assets/vulnerability/examples/1.json
clients/osv/src/test/assets/vulnerability/examples/2.json
clients/osv/src/test/assets/vulnerability/examples/3.json
clients/osv/src/test/assets/vulnerability/examples/4.json
clients/osv/src/test/assets/vulnerability/examples/5.json
clients/osv/src/test/assets/vulnerability/examples/6.json
clients/osv/src/test/assets/vulnerability/examples/7.json

The mix of single-field and typed event serializations that was seen was caused by creating the new expected results with the wrong serializer. Reverting those parts of the expected results shows that the actual results do not require the serializer changes.
To see how the diff of 5f8f378c should have looked like, run
git diff 5f8f378c^ HEAD -- clients/osv/src
on this commit.

chore(osv-client): Revert unnecessary changes from 5f8f378c

---

plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt

Use Kotest's build-in `shouldTimeout` which is implemented the same way as the replaced code, and use `runInterruptible` [1] instead of `launch` to avoid the "illusion that the blocking code gets canceled" [2].
[1]: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/run-interruptible.html
[2]: https://github.com/Kotlin/kotlinx.coroutines/issues/3875#issuecomment-1705218477

test(fossid): Improve timeout testing for blocking code

---

plugins/commands/evaluator/src/test/kotlin/EvaluatorCommandTest.kt

This allows to set the environment in an ORT-independent way. Note that only those environment variables provided to `test` are visible to the command unless `includeSystemEnvvars` is enabled, see [1].
[1]: https://ajalt.github.io/clikt/testing/

refactor(EvaluatorCommandTest): Migrate to `CliktCommand.test`

---

scripts/docker_build.sh

Mac BSD based grep tool has different options and behaviour than Linux GNU based, so a solution with basic sed and grep was needed.

 Change to grep/sed solution due Mac grep difference

---

plugins/package-managers/gradle-inspector/README.md

The `-P` is a global option that has to come before `analyze`.

docs(gradle-inspector): Fix the order of example CLI arguments

---

plugins/package-managers/python/src/funTest/kotlin/utils/PythonInspectorFunTest.kt
plugins/package-managers/python/src/main/kotlin/utils/PythonInspector.kt

Remove the default function arguments for the Python version and OS from `inspect()` as they are too easily being confused with the configured package manager options and their default values.

refactor(PythonInspector): Remove default arguments

---

plugins/scanners/fossid/src/main/kotlin/Utils.kt
plugins/scanners/fossid/src/test/kotlin/MapIgnoreRulesTest.kt

The commit b194cf37 added a change for supporting '.' in directory names. Currently, the dash symbol is also no supported. Therefore, the current commit simplifies the logic to allow all special characters in the directory name, by simplifying the regular expression.
This is a breaking change as the directory name "directory/sub1/sub2" is not accepted anymore and won't be mapped to a directory ignore rule. The directory name must now always end with '/', i.e. "directory/sub1/sub2/".

fix(fossid-webapp)!: Simplify the pattern for directories in ignore rules

---

helper-cli/src/funTest/assets/create-analyzer-result-from-pkg-list-expected-output.yml
helper-cli/src/funTest/assets/package-list.yml
helper-cli/src/funTest/kotlin/commands/CreateAnalyzerResultFromPackageListCommandFunTest.kt
helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/CreateAnalyzerResultFromPackageListCommand.kt

The command defines a data model called `SimpleDefinitionFile` which is
read as input using any of the known file extensions. It outputs an
analyzer result with a single project containing the provided
dependencies as a flat list.
When a project does not use a package manager, currently the only way of
scanning it with ORT is to craft SPDX files and running the analyzer
against them. This command tries to provide a minimalistic alternative
to fullfil the requirements of the underlying need.
Note: This is a first experimental version. Furthermore, `VcsInfo` is deliberately not used, in order to:
1. avoid nesting to in turn make it easier to generate the input file.
2. make all attributes optional.

helper-cli: Add a command to generate a flat analyzer result

---

plugins/reporters/spdx/src/main/kotlin/Extensions.kt

This eliminates one type of violation of the SPDX spec V 2.2 from produced documents.

SpdxDocumentReporter: Adhere to detected licenses when computing extracted license info

---

helper-cli/src/funTest/kotlin/commands/CreateAnalyzerResultFromPackageListCommandFunTest.kt

Note that a future version of clikt will also support a vararg for `test` for convenience [1]. According code can be migrated once that version is available.
[1]: https://github.com/ajalt/clikt/pull/451

refactor(helper-cli): Replace the custom `runMain` with `CliktCommand.test`

---

plugins/reporters/trustsource/build.gradle.kts
plugins/reporters/trustsource/src/main/kotlin/TrustSourceModel.kt
plugins/reporters/trustsource/src/main/kotlin/TrustSourceReporter.kt
plugins/reporters/trustsource/src/main/resources/META-INF/services/org.ossreviewtoolkit.reporter.Reporter

This adds the reporter plugin for the TrustSource JSON format. 
To use it, simply specify 'TrustSource' in the list of report formats (-f).

Add TrustSource reporter plugin

---

buildSrc/src/main/kotlin/ort-publication-conventions.gradle.kts

Without these, the check performed by Sonatype Nexus when closing a staging repository for releasing fails.

build(Gradle): Add more POM metadata required for publishing

---

buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
clients/fossid-webapp/build.gradle.kts
clients/nexus-iq/build.gradle.kts
clients/oss-index/build.gradle.kts
clients/osv/build.gradle.kts
clients/scanoss/build.gradle.kts
clients/vulnerable-code/build.gradle.kts

These clients all have `create()` functions that take an `OkHttpClient`, so OkHttp should be an API dependency and not just a transitive dependency of Retrofit.
As a positive side-effect this bumps the OkHttp version from 3.14.9 (as used by Retrofit) to the current version used by ORT, getting rid of some reported vulnerabilities. See [1] for why Retrofit is stuck on OkHttp version 3 although version 4 is binary compatible [2].
[1]: https://github.com/square/retrofit/pull/3767#issuecomment-1720031134
[2]: https://github.com/square/retrofit/issues/3384#issuecomment-1645583665

build(clients): Add OkHttp as an explicit API dependency

---

plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
plugins/reporters/spdx/src/main/kotlin/Extensions.kt

The description for the `filesAnalyzed` attribute says that "If false, the package shall not contain any files.", see [1]. This in turn implies that `licenseInfoInFiles` must be empty in that case.
Running [2] against an SPDX document which has a package with `filesAnalyzed=false` and a non-empty value for `licenseInfoInFiles` yields an error saying that the document is not valid for mentioned reason.
Fix that issue by reporting non-empty `licenseInfoInFiles` only for VCS and source artifact packages.
[1] https://github.com/spdx/spdx-spec/blob/development/v2.2.1/chapters/package-information.md#78-files-analyzed-field-
[2] https://github.com/spdx/tools-python

fix(reporter): Align setting `licenseInfoInFiles` with the spec v2.2

---

clients/osv/src/main/kotlin/Model.kt

The `Osv` backend returns JSON data compliant with spec version 1.6.0, while ORT's handling hasn't been updated to that (latest) version.
For example, the root cause of [2] is that `Reference.Type` is lacking the value `EVIDENCE`.
Align only the values of `Reference.Type` with version 1.6.0 in order to fix [2] quickly. In a future change, remaining alignments, if any, should be made.
[1] https://github.com/ossf/osv-schema/blob/v1.6.0/validation/schema.json
[2] https://github.com/oss-review-toolkit/ort/issues/7531
Fixes #7531.
---
Follow-up work: #7534.

fix(osv): Align `Reference.Type` with spec version 1.6.0

---

.github/workflows/build-and-test.yml
.github/workflows/release.yml

Create release notes

---

plugins/package-curation-providers/ort-config/src/funTest/kotlin/OrtConfigPackageCurationProviderFunTest.kt

Update the NuGet identifiers used in the
`OrtConfigPackageCurationProviderFunTest` as they were updated in the ort-config repository [1].
[1]: https://github.com/oss-review-toolkit/ort-config/pull/136

test(ort-config-package-curation-provider): Update NuGet identifiers

---

advisor/src/funTest/kotlin/OsvFunTest.kt
downloader/src/test/kotlin/VersionControlSystemTest.kt

Minor test improvements

---

plugins/package-managers/cocoapods/src/main/kotlin/CocoaPods.kt

Both the default and the regex query string matching logic actually match substrings case-insensitively. So if a package name is a substring of another package name, invalid matches could occur. To circumvent that, force the regex to be a full match.

fix(CocoaPods): Restrict package name matching to full matches

---

model/src/main/kotlin/SnippetFinding.kt
model/src/main/kotlin/utils/SortedSetConverters.kt
plugins/reporters/fossid/src/main/resources/templates/asciidoc/fossid_snippet.ftl
plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt
plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
plugins/scanners/fossid/src/test/kotlin/FossIdLicenseMappingTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdSnippetMappingTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOssResultParser.kt
plugins/scanners/scanoss/src/test/kotlin/ScanOssResultParserTest.kt
plugins/scanners/scanoss/src/test/kotlin/ScanOssScannerDirectoryTest.kt

Following the [17.07 Kotlin Developer meeting](https://github.com/oss-review-toolkit/ort/wiki/Kotlin-Developer-Meeting#2023-07-17), it was agreed that, _before the Snippet Choice feature is implemented in ORT_, the snippet model has to be changed to group the snippets by the source file location including the line ranges.

fix(fossid-webapp): Group snippets by source file matching lines 

---

plugins/reporters/spdx/src/main/kotlin/Extensions.kt

Allow for passing just the `type` as alternative to passing `infix` and `suffix` separately, to slightly simplify the caller code.

refactor(spdx): Add an overload for `toSpdxId()`

---

website/docs/license.md

License page has only a link but no mention of what license ORT is using

Missing license info

---

clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
plugins/package-curation-providers/clearly-defined/src/funTest/kotlin/ClearlyDefinedPackageCurationProviderFunTest.kt
scanner/src/funTest/kotlin/storages/ClearlyDefinedStorageFunTest.kt

A manual harvest was triggered for `semver4j` on ClearlyDefined today by myself for testing, so the expected ScanCode result data needs to be updated.

test(ClearlyDefinedStorageFunTest): Update expected results

---

Dockerfile
Dockerfile-legacy

There are projects which use Git LFS for
`gradle/wrapper/gradle-wrapper.jar`.  Without Git LFS installed, an analysis of the project yields an empty project without dependencies.
Fix that issue by installing Git LFS.

fix(docker): Install Git LFS

---

scanner/src/funTest/kotlin/storages/ClearlyDefinedStorageFunTest.kt
scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt

ClearlyDefined returns VCS URLs like [1] which makes the provenance matcher fail as it checks for [2] (plus the revision independently). Properly parse the VCS URL returned by ClearlyDefined to fix this.
[1]: https://github.com/vdurmont/semver4j/tree/88912638db3f6112a2b345f1638ced33a0a606e1
[2]: https://github.com/vdurmont/semver4j.git

fix(ClearlyDefinedStorage): Properly parse returned VCS URLs

---

.github/workflows/docker-ort-runtime-ext.yml
.github/workflows/docker-ort-runtime.yml
scripts/docker_build.sh

Main version is caught in the same manner as the
docker_build script, with gradlew.
Tag event will create the version with defined tag.

docker: set correct version for runtime

---

.github/workflows/docker-ort-runtime-ext.yml
.github/workflows/docker-ort-runtime.yml

depends on:  https://github.com/oss-review-toolkit/ort/pull/7581
Intermediary Docker images will be built nightly at 04:00 and be tagged as <VERSION>-SNAPSHOT.
Same to workflow_dispatch events.
Push tag events will tag Docker images to the release version.

chore(docker): Adjust build frequency

---

analyzer/src/main/kotlin/managers/utils/MavenSupport.kt
analyzer/src/test/kotlin/managers/utils/MavenSupportTest.kt

Only remove the project name as a prefix from paths to single directories. For any deeper path, assume that it really exists.
Fixes #7594.

fix(MavenSupport): Improve the logic to fixup project paths in SCM URLs

---

plugins/package-managers/gradle-model/build.gradle.kts

This needs to be published as it is not only a dependency of the embedded `gradle-plugin`, but also of the `gradle-inspector` and the "legacy" `gradle-package-manager`, see how [1] refers to it (under the wrong group name, as publishing conventions were not applied so far).
[1]: https://repo.maven.apache.org/maven2/org/ossreviewtoolkit/plugins/package-managers/2.0.0/package-managers-2.0.0.pom

build(Gradle): Fix publishing the `gradle-model` artifact

---

notifier/build.gradle.kts

The reason also is in the Git history, but this is more visible.

chore(notifier): Explain why `slf4j-log4j12` is excluded

---

Dockerfile

Python typecode-libmagic need a fallback on platforms that don't have the library plugin capability, mostly linux/aarch64 images. Ubuntu specific need the libmagic1 system library and file utility.

chore(deps): Add libmagic as fallback for typecode-libmagic

---

model/src/main/kotlin/utils/PurlUtils.kt

The commit https://github.com/bosch-io/oss-review-toolkit/commit/7da5ae93606390b4967755121a8932826931098a changed the visibility of `createPurl`, `toPurl` has
become the only public ORT function for plugins to generate Purls.
Since this function does not support qualifiers nor subpath, these two
parameters have to be added to the function signature with default values.

feat(PurlUtils): Add optional parameters to `toPurl`

---

plugins/package-managers/python/src/funTest/assets/projects/synthetic/poetry-expected-output.yml
plugins/package-managers/python/src/main/kotlin/Poetry.kt

In order to do it's job, `Poetry.kt` generates a requirements file and then relies on `Pip.kt` to do the analysis. The resulting `ProjectAnalyzerResult`s uses the paths to these generated requirements files as definiton file paths. This does not make sense, because:
1. The generation of the files is an implementation detail.
2. The generated files do not exist in the code repository which can lead to confusion, in particular also these get referenced from ORT configuration / path excludes.
Fix that by patching up the `ProjectAnalyzerResult`s to recover the original definition file name.

refactor(poetry): Improve the definition file paths

---

cli/src/funTest/kotlin/OrtMainFunTest.kt
cli/src/main/kotlin/OrtMain.kt
helper-cli/src/funTest/kotlin/commands/CreateAnalyzerResultFromPackageListCommandFunTest.kt

Clikt simplifications

---

plugins/package-managers/python/src/funTest/assets/projects/synthetic/poetry-expected-output.yml
plugins/package-managers/python/src/main/kotlin/Poetry.kt

Do not use the filename of the generated requirements file as part of the identifier for a rationale analog to [1]. Furthermore, use include the definition file path relative to the analyzer root to ensure that the project ID is unique within the ORT file.
While at it, stop re-using any logic for deriving the identifier from `Pip`, because some parts of the logic do not make sense to use. For example, it does not make sense to derive a name and a version from a sibling setup.py, because that would be unrelated to the poetry lockfile being analyzed.
Note: This change could be regarded as a left-over from [1].
[1] d647cc7ffc1a83c607c46055c7fe8882ec88b16c

refactor(Poetry): Improve the IDs of projects

---

build.gradle.kts

Docker tags do not support "+" as part of their name [1], so turn e.g. "3.0.1-SNAPSHOT+003.sha.cc0865e" into "3.0.1-003.sha.cc0865e" by using the build part as the pre-release part. SemVer sorting rules [2] are still so that 3.0.1-003.sha.cc0865e < 3.0.1.
[1]: https://github.com/moby/moby/issues/16304
[2]: https://semver.org/#spec-item-11

build: Drop the build part from the SemVer to get rid of the "+"

---

plugins/package-configuration-providers/dir/src/main/kotlin/DirPackageConfigurationProvider.kt
plugins/package-curation-providers/clearly-defined/src/main/kotlin/ClearlyDefinedPackageCurationProvider.kt
plugins/package-curation-providers/file/src/main/kotlin/FilePackageCurationProvider.kt

These are property-only classes which are a perfect fit for data classes.

chore(providers): Turn config classes into data classes

---

scanner/src/main/kotlin/ScanController.kt
scanner/src/main/kotlin/ScanStorages.kt
scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/provenance/NestedProvenance.kt
scanner/src/main/kotlin/provenance/NestedProvenanceScanResult.kt
scanner/src/test/kotlin/provenance/NestedProvenanceScanResultTest.kt

All known provenance information is immutable, so there is no need to have a function recreate the set on each call. Use a property instead, name it `allProvenances` to avoid the need for the `@JsonIgnore` annotation, and inline some related code for simplicity while at it.

refactor(scanner)!: Use a property that holds all nested provenances

---

analyzer/src/funTest/assets/projects/synthetic/gomod-dangling-embed-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/gomod-dangling-embed/go.mod
analyzer/src/funTest/assets/projects/synthetic/gomod-dangling-embed/main.go
analyzer/src/funTest/kotlin/managers/GoModFunTest.kt
analyzer/src/main/kotlin/managers/GoMod.kt

The `GoMod` integration does not execute `go generate/go build`, so the embed directive in `main.go` points to a non-existing file. When `GoMod` executes [1] it failed [2] with the previously used Go version 1.20.5. As of [3], with Go version 1.21.1, that issue is fixed.
Add a test to ensure it keeps on working.
Note: It is essential to pass `json=Module` instead of not just
`-json` [4], because otherwise the issue would still persist on
Go 1.21.1.
Fixes #5560.
[1] `go list -deps -json=Module -buildvcs=false ./...`
[2] `pattern file.txt: no matching`
[3] 47e45202a2cd04396fe929b8ac856c98f1b94649
[4] 43ad3a777c6b4f59c487faf255ca590e7d48822d
Please ensure that your pull request adheres to our [contribution guidelines](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md). …

fix(analyzer): Add a test for dangling embed directives / GoMod

---

helper-cli/src/main/kotlin/commands/GetPackageLicensesCommand.kt
helper-cli/src/main/kotlin/commands/ListStoredScanResultsCommand.kt
helper-cli/src/main/kotlin/commands/packageconfig/CreateCommand.kt
scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt
scanner/src/funTest/kotlin/storages/ClearlyDefinedStorageFunTest.kt
scanner/src/main/kotlin/ScanResultsStorage.kt
scanner/src/main/kotlin/ScanStorage.kt
scanner/src/main/kotlin/ScanStorages.kt
scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
scanner/src/main/kotlin/storages/FileBasedStorage.kt
scanner/src/main/kotlin/storages/NoStorage.kt
scanner/src/main/kotlin/storages/PostgresStorage.kt
scanner/src/main/kotlin/storages/Sw360Storage.kt
scanner/src/test/kotlin/ScannerTest.kt
scanner/src/test/kotlin/storages/ClearlyDefinedStorageTest.kt

A *package* based reader should indeed take a `Package` for all its `read()` functions. This aligns with the existing `read()` function that takes a `ScannerCriteria`, and it is a requirement for a proper implementation of `ClearlyDefinedStorage` which uses coordinates with a "provider" for lookup that can only be correctly constructed when provenance information is available. So far the `ClearlyDefinedStorage` hard-codes some assumptions in this regard, which will be corrected in upcoming changes.

refactor(PackageBasedScanStorageReader)!: Align `read()` to take a `Package`

---

plugins/commands/requirements/build.gradle.kts
plugins/commands/requirements/src/funTest/kotlin/RequirementsCommandFunTest.kt

Add a test case to verify that all supported classes can be instantiated to protect against errors if the constructor signatures change, like the one fixed in 9dfa198.

test(requirements): Add a test to verify that classes can be instantiated

---

.github/workflows/docker-ort-runtime-ext.yml
.github/workflows/docker-ort-runtime.yml

After move to scheduled build, main images are building only on push and workflow_dispatch events.
Noticed after some mistake PR done on Ort Github CI repository.

fix(docker): Enable build on schedule event

---

helper-cli/src/main/kotlin/commands/repoconfig/GenerateScopeExcludesCommand.kt
plugins/package-managers/python/src/funTest/assets/projects/synthetic/poetry-expected-output.yml
plugins/package-managers/python/src/main/kotlin/Pip.kt
plugins/package-managers/python/src/main/kotlin/Poetry.kt
plugins/package-managers/python/src/main/kotlin/utils/PythonInspectorExtensions.kt

Extend the implementation to also report dev dependencies.
Fixes #7626.
Note: This is a best effort implementation which intentionally does not refactor any python inspector related code, 
because the implementation in the long run should probably be anyway changed to support the lockfile format / 
pyproject.toml directly.

Poetry: Also analyze the dev dependencies

---

plugins/package-managers/pub/src/main/kotlin/Pub.kt

feat(pub): Add support for bootstrapping Flutter on macOS

---

plugins/commands/requirements/src/main/kotlin/RequirementsCommand.kt
plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt
plugins/scanners/askalono/src/funTest/kotlin/AskalonoFunTest.kt
plugins/scanners/askalono/src/main/kotlin/Askalono.kt
plugins/scanners/boyterlc/src/funTest/kotlin/BoyterLcFunTest.kt
plugins/scanners/boyterlc/src/main/kotlin/BoyterLc.kt
plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/main/kotlin/FossIdConfig.kt
plugins/scanners/fossid/src/main/kotlin/FossIdNamingProvider.kt
plugins/scanners/fossid/src/main/kotlin/FossIdUrlProvider.kt
plugins/scanners/licensee/src/funTest/kotlin/LicenseeFunTest.kt
plugins/scanners/licensee/src/main/kotlin/Licensee.kt
plugins/scanners/scancode/src/funTest/kotlin/ScanCodeScannerFunTest.kt
plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
plugins/scanners/scancode/src/main/kotlin/ScanCodeConfig.kt
plugins/scanners/scancode/src/test/kotlin/ScanCodeTest.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOss.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOssConfig.kt
plugins/scanners/scanoss/src/test/kotlin/ScanOssScannerDirectoryTest.kt
plugins/scanners/scanoss/src/test/kotlin/ScanOssScannerFileTest.kt
scanner/src/main/kotlin/ScannerMatcher.kt
scanner/src/main/kotlin/ScannerWrapperFactory.kt
scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
scanner/src/test/kotlin/ScannerMatcherTest.kt

Use the `TypedConfigurablePluginFactory` interface as base for the `ScannerWrapperFactory` to further align the plugin APIs. While at it, extract the logic to parse the scanner matcher properties to a central place to not have to repeat the properties in the configuration classes for all scanner wrappers. This also makes it possible to use `Unit` as configuration class for scanners that do not offer any configuration options.
As this change makes the configuration classes of the scanner wrappers part of the public API, they must not be `internal` anymore.
Scanners that provide secret configuration options will be migrated to read them from the `secrets` map instead of the `options` map in later commits.
**Breaking API change:**
The `ScannerWrapperFactory` API was changed so all scanner …

refactor(scanner)!: Use the configurable plugin API for scanner wrappers

---

analyzer/src/funTest/assets/projects/synthetic/gomod-submodules-embed-expected-output.yml
analyzer/src/funTest/assets/projects/synthetic/gomod-submodules/app/go.mod
analyzer/src/funTest/assets/projects/synthetic/gomod-submodules/app/go.sum
analyzer/src/funTest/assets/projects/synthetic/gomod-submodules/app/main.go
analyzer/src/funTest/assets/projects/synthetic/gomod-submodules/utils/go.mod
analyzer/src/funTest/assets/projects/synthetic/gomod-submodules/utils/go.sum
analyzer/src/funTest/assets/projects/synthetic/gomod-submodules/utils/texts.go
analyzer/src/funTest/kotlin/managers/GoModFunTest.kt

This illustrates that local module dependencies are currently not supported, and prepares for supporting it in a following change.
This is a preparation for implementing #7649.

test(analyzer): Test detecting local module dependencies with GoMod

---

.github/workflows/docker-ort-runtime-ext.yml
.github/workflows/docker-ort-runtime.yml

To avoid confusion over the 'latest' tag always set for daily builds, these builds will be tagged as 'snapshot' instead of 'latest', together with the current snapshot version.
The 'latest' docker tag will only occur with the version release during a push tag event.

feat(docker): Change the image tagging process

---

cli/src/funTest/assets/semver4j-ort-result.yml
integrations/schemas/ort-configuration-schema.json
model/src/main/kotlin/config/PluginConfiguration.kt
model/src/main/kotlin/config/ProviderPluginConfiguration.kt
model/src/main/kotlin/config/ScannerConfiguration.kt
model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt
plugins/reporters/web-app/src/funTest/assets/scan-result-for-synthetic-gradle-lib.yml
plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/main/kotlin/FossIdConfig.kt
plugins/scanners/fossid/src/test/kotlin/FossIdConfigTest.kt
plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOss.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOssConfig.kt
plugins/scanners/scanoss/src/test/kotlin/ScanOssConfigTest.kt
scanner/src/funTest/assets/scanner-integration-all-pkgs-expected-ort-result.yml
scanner/src/funTest/assets/scanner-integration-subset-pkgs-expected-ort-result.yml
scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/ScannerWrapper.kt

Take the secret options into use for scanner wrapper plugins. Please see the commit messages for details.
**Breaking change:**
The configuration for scanner wrappers was changed, see the diff of the `reference.yml` in this PR for examples.

Scanner: Take secret options into use

---

buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts

The recent GraalVM releases support Java 20 (and 21), so the task can be reconfigured unconditionally.

build: Remove a work-around for older GraalVM releases

---

Dockerfile-legacy

The other Docker files already use that version.

build(Docker): Align the `python-inspector` version on 0.9.8

---

Dockerfile-legacy
plugins/package-managers/pub/src/funTest/kotlin/PubFunTest.kt
plugins/package-managers/stack/src/funTest/kotlin/StackFunTest.kt

Temporarily remove Stack from the Dockerfile-legacy and disable the `StackFunTest` as GitHub runners are running out of disk space and the Stack installation requires a lot. Other candidates would have been Pub or SPM as they also take a lot of disk space, but those package managers are more actively used.

chore(stack)!: Temporarily remove Stack from Dockerfile-legacy and disable Stack and Pub tests

---

model/src/main/kotlin/config/ScannerConfiguration.kt

This is a fixup for 712c448 to allow for deserializing older results.

fix(model): Keep the old "options" as a alias for "config"

---

Dockerfile-legacy
plugins/package-managers/python/src/funTest/assets/projects/synthetic/poetry-no-dev-group-expected-output.yml
plugins/package-managers/spm/src/funTest/assets/projects/synthetic/spm-expected-output-lib.yml

Recently, PRs got merged where fun tests runs in Docker have been skipped. These two issues seem to have slipped through.
Note: I've verified locally that PoetryFunTest produces the same diff for `python-inspector` version 0.9.6 and 0.9.8.

fix: Failing fun tests running inside Docker

---

plugins/package-managers/nuget/src/funTest/assets/nuget-expected-output.yml
plugins/package-managers/nuget/src/main/kotlin/utils/NuGetInspectorExtensions.kt

For unclear reasons, the length of the error message increased
significantly, and it includes now varying "DevOps Activity IDs". Limit
the length of error / warning messages to the first line only to work
around that.

test(nuget): Limit length of excessive error messages

---

README.md
gradle/libs.versions.toml
integrations/schemas/ort-configuration-schema.json
model/src/main/kotlin/config/FileStorageConfiguration.kt
model/src/main/kotlin/config/S3FileStorageConfiguration.kt
model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
model/src/test/kotlin/config/ScannerConfigurationTest.kt
utils/ort/build.gradle.kts
utils/ort/src/funTest/kotlin/storage/S3FileStorageFunTest.kt
utils/ort/src/main/kotlin/storage/S3FileStorage.kt

Add support for using AWS S3 as online cache for scan results.
Provides a S3FileStorage class which extends [FileStorage](https://github.com/oss-review-toolkit/ort/blob/main/utils/ort/src/main/kotlin/storage/FileStorage.kt) and uses official Amazon's  [AWS Java SDK](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/examples-s3.html) to store scan results.
Issue oss-review-toolkit/ort#730

Add an AWS S3 scan result storage

---

plugins/commands/scanner/build.gradle.kts
plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt

Slightly change the logic for selecting the default scanner: If there is only a single scanner available, use that one, otherwise try to use ScanCode as usual.

build(scanner): Do not hard-code the dependency on scanner plugins

---

analyzer/src/funTest/assets/projects/synthetic/gomod-submodules-embed-expected-output.yml
analyzer/src/funTest/kotlin/managers/GoModFunTest.kt
analyzer/src/main/kotlin/managers/GoMod.kt
analyzer/src/testFixtures/kotlin/Extensions.kt

The only way of referencing a module on the local file system from another is by specifying a relative or absolute path via a replace directive. This is currently not supported by ORT's Go Modules integration.
Implement that support, so that a reference inbetween two modules on the local file system gets represent as a `PackageReference` between the corresponding `Project`s (in ORT speak). However, keep on failing in case a referenced module is not located within the analysis root, because that would violate ORT's package manager API.
Fixes #7649.

analyzer: Support references to local modules with `GoMod`

---

plugins/package-configuration-providers/api/src/main/kotlin/PackageConfigurationProviderFactory.kt
plugins/package-curation-providers/api/src/main/kotlin/PackageCurationProviderFactory.kt
scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt

Resolve plugin config vs classpath exceptions

---

cli/build.gradle.kts

Use a Gradle 8.4 `dependencyScope` [1] to extend the `runtimeClasspath` with the `pluginClasspath`. This improves the solution from 1708ac3 by supporting to run ORT from Gradle or the IDE with platform projects / plugins in the classpath, but still do not publish them as part of the "dependencyManagement" in the POM. See [2] for context.
[1]: https://docs.gradle.org/8.4/release-notes.html#easier-to-create-role-focused-configurations
[2]: https://github.com/gradle/gradle/issues/10861#issuecomment-576562961

build: Include platform projects when running from Gradle or the IDE

---

plugins/scanners/fossid/src/main/kotlin/FossIdConfig.kt

The properties to detect license declarations and copyright statements were both named "detectLicenseDeclarations". Rename the latter accordingly.

fix(fossid): Fix a copy & paste error in a property name

---

advisor/src/main/kotlin/advisors/VulnerableCode.kt
advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt

Apparently, VulnerableCode sometimes returns URLs that use blackslash escaping instead of percent escaping. Fix this up.
Resolves #7364.

feat(VulnerableCode): Fixup wrongly escaped URLs

---

model/src/main/kotlin/AdvisorRecord.kt

Do not leave the `summary` and `description` at their `null` default values but take them from the first vulnerability. Update the documentation accordingly and also generally improve the wording while at it.

fix(AdvisorRecord): Merge all properties of vulnerabilities

---

gradle/libs.versions.toml
plugins/package-managers/go/build.gradle.kts
plugins/package-managers/go/src/main/kotlin/GoDep.kt
plugins/package-managers/go/src/main/kotlin/GoDepLockFile.kt

This allows to get rid of toml4j which had no releases since 2017 and
depends on GSON, which has vulnerabilities.

refactor(go): Migrate GoDep TOML parsing to kotlinx-serialization

---

qodana.yml

This is currently the latest version, see [1].
[1]: https://hub.docker.com/r/jetbrains/qodana-jvm-community/tags

chore(Qodana): Use the non-EAP version of the JVM linter

---

Dockerfile-legacy

Building the legacy docker on CI does not work anymore because the way
how Node.js has to be installed has changed, see [1]. So, migrate the
installation accordingly.
[1] https://github.com/nodesource/distributions/issues/1576#issuecomment-1698012034

chore(docker): Fix installing Node.js in the legacy image

---

plugins/package-managers/node/src/main/kotlin/Npm.kt

NPM's peer dependencies are not regular dependencies in a "peer" scope, but 'Some way of saying, "I only work when plugged in to version 1.2.x of my host package, so if you install me, be sure that it's alongside a compatible host."' [1]. So they are more like what Gradle would call a "dependency constraint" [2].
As any recent version of NPM "will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree" [3], ORT's NPM implementation will pick them up when parsing the installed modules, so no further handling is needed.
Resolves #95.
[1]: https://nodejs.org/en/blog/npm/peer-dependencies#the-solution-peer-dependencies
[2]: https://docs.gradle.org/current/userguide/dependency_management_terminology.html#sub:terminology_dependency_constrain …

docs(Npm): Do not say to implement dedicated support for peer dependencies

---

plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result-with-findings.json
plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result.json
plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result.xml
plugins/reporters/cyclonedx/src/funTest/kotlin/CycloneDxReporterFunTest.kt
plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt
reporter/src/testFixtures/kotlin/TestData.kt

This PR adds support for CycloneDX vulnerabilities in Reporter.
Closes #4531

Support the CycloneDX vulnerability extension in Reporter

---

plugins/package-managers/python/src/funTest/assets/projects/synthetic/pip-expected-output.yml
plugins/package-managers/python/src/funTest/assets/projects/synthetic/pip/requirements.txt
plugins/package-managers/python/src/funTest/assets/projects/synthetic/pipenv-expected-output.yml
plugins/package-managers/python/src/funTest/assets/projects/synthetic/pipenv/Pipfile
plugins/package-managers/python/src/funTest/assets/projects/synthetic/pipenv/Pipfile.lock
plugins/package-managers/python/src/funTest/assets/projects/synthetic/python-inspector-expected-output.yml
plugins/package-managers/python/src/funTest/assets/projects/synthetic/python-inspector/requirements.txt
plugins/package-managers/python/src/funTest/kotlin/utils/PythonInspectorFunTest.kt

When Python inspector 0.9.8 and above analyzes a project containing `markupsafe` version 1.0.0 as dependency (with option `--analyze-setup-py-insecurely`), then it crashes for unknown reason, see also [1]. Upgrading `markupsafe` to 1.1.0 works around that issue. Do so, in order to prepare for upgrading Python inspector.
[1] https://github.com/nexB/python-inspector/issues/133

test(python): Upgrade `markupsafe` to version 1.1.0

---

scanner/src/main/kotlin/Scanner.kt

Scan function refactoring

---

model/src/main/kotlin/vulnerabilities/VulnerabilityReference.kt

This is a fixup for 8b6fe4f which introduced the `severityRating` property.

fix(VulnerabilityReference): Do not deserialize a lazy property

---

renovate.json

These come almost on a daily basis without usually bringing any value to ORT.

ci(renovate): Disable patch-level updates for the AWS S3 dependency

---

plugins/package-managers/node/src/funTest/kotlin/NpmFunTest.kt

These probably went unnoticed so far due to a bug in Detekt.

chore(NpmFunTest): Remove two unused imports

---

README.md
website/docs/development.md
website/docusaurus.config.js

Replace Slack invite links with dedicated subdomain on ORT website so URL is easier to update once invite limit is reached.

chore: Use new ORT slack subdomain

---

plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result.json
plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result.xml
plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt
reporter/src/testFixtures/kotlin/TestData.kt

This PR populates the [score](https://cyclonedx.org/docs/1.5/json/#vulnerabilities_items_ratings_items_score) and [method](https://cyclonedx.org/docs/1.5/json/#vulnerabilities_items_ratings_items_method) properties for the vulnerability rating when reporter generates a CycloneDX SBOM report.

Populate score and method properties for vulnerability ratings in CycloneDX SBOM report

---

plugins/package-managers/cargo/src/main/kotlin/CargoLockFile.kt

This fixes a bug introduced by the port to kotlinx-serialization [1]. Resolves #7825.
[1]: https://github.com/oss-review-toolkit/ort/pull/7709

fix(cargo): Allow `metadata` to be missing again

---

plugins/commands/evaluator/src/main/kotlin/EvaluatorCommand.kt

Previously, the docs referred to package configurations which did not make sense, see also [1]. 
[1] 910454160c51bb783a6b40496ba68c782901e835

docs(evaluator): Fix-up the docs for two CLI options

---

helper-cli/src/main/kotlin/utils/Extensions.kt
model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt
model/src/main/kotlin/utils/ScanResultUtils.kt
model/src/test/kotlin/licenses/DefaultLicenseInfoProviderTest.kt
model/src/test/kotlin/utils/ScanResultUtilsTest.kt

Make the impact of narrowing down a VCS path visible in the `list-licenses` command, without requiring a re-scan.

feat(helper-cli): Re-filter scan summaries by the VCS path

---

cli/build.gradle.kts

Without this, building the distribution would not necessarily build the advisor plugins.

fix: Add advisor plugins to the plugin classpath for distribution

---

helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
helper-cli/src/main/kotlin/utils/Extensions.kt

helper-cli: Fix listing licenses for packages with no scan result

---

scanner/src/main/kotlin/Scanner.kt

A user does not know that the reference package has its path removed, so the original message sounded as if the package is scanned as a substitute for others. Clarify that by rewording the log message.

docs(scanner): Improve logging for packages with incomplete scan results

---

cli/src/funTest/kotlin/ExamplesFunTest.kt
integrations/schemas/ort-configuration-schema.json
model/src/main/kotlin/config/PluginConfiguration.kt
model/src/main/kotlin/config/ReporterConfiguration.kt
model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
model/src/test/kotlin/config/ReporterConfigurationTest.kt
plugins/commands/reporter/src/main/kotlin/ReporterCommand.kt
plugins/reporters/asciidoc/src/funTest/kotlin/PdfTemplateReporterFunTest.kt
plugins/reporters/asciidoc/src/main/kotlin/AsciiDocTemplateReporter.kt
plugins/reporters/ctrlx/src/main/kotlin/CtrlXAutomationReporter.kt
plugins/reporters/cyclonedx/src/funTest/kotlin/CycloneDxReporterFunTest.kt
plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt
plugins/reporters/evaluated-model/src/funTest/kotlin/EvaluatedModelReporterFunTest.kt
plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelReporter.kt
plugins/reporters/fossid/src/main/kotlin/FossIdReporter.kt
plugins/reporters/fossid/src/main/kotlin/FossIdSnippetReporter.kt
plugins/reporters/fossid/src/test/kotlin/FossIdReporterTest.kt
plugins/reporters/freemarker/src/funTest/kotlin/PlainTextTemplateReporterFunTest.kt
plugins/reporters/freemarker/src/main/kotlin/PlainTextTemplateReporter.kt
plugins/reporters/gitlab/src/funTest/kotlin/GitLabLicenseModelReporterFunTest.kt
plugins/reporters/gitlab/src/main/kotlin/GitLabLicenseModelReporter.kt
plugins/reporters/opossum/src/funTest/kotlin/OpossumReporterFunTest.kt
plugins/reporters/opossum/src/main/kotlin/OpossumReporter.kt
plugins/reporters/spdx/src/funTest/kotlin/SpdxDocumentReporterFunTest.kt
plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt
plugins/reporters/static-html/src/main/kotlin/StaticHtmlReporter.kt
plugins/reporters/trustsource/src/main/kotlin/TrustSourceReporter.kt
plugins/reporters/web-app/src/main/kotlin/WebAppReporter.kt
reporter/src/main/kotlin/Reporter.kt

Some reporter implementations need access to secrets. Therefore, align the `ReporterConfiguration` class with the configuration classes for Advisor and Scanner which use `PluginConfiguration` to distinguish between plain options and secrets.

feat(reporter)!: Support secrets in reporter options

---

clients/osv/src/main/kotlin/Model.kt
plugins/advisors/osv/src/funTest/kotlin/OsvFunTest.kt
plugins/advisors/osv/src/main/kotlin/Osv.kt

advisor: Add the missing handling to query the Hackage ecostem to Osv

---

plugins/package-managers/maven/src/main/kotlin/utils/MavenDependencyHandler.kt
plugins/package-managers/maven/src/main/kotlin/utils/MavenSupport.kt

Adress some inspection hints

---

plugins/package-managers/maven/src/main/kotlin/utils/MavenSupport.kt

This is and should not be used outside of this class.

refactor(maven)!: Make the `container` property private

---

model/src/main/kotlin/PackageCurationData.kt

The property has been renamed five month ago [^1] and it's easy to make the needed alignments, see [^2]. So, drop this last remaining `@JsonAlias` annotation to eliminate technical debt.
[^1]: https://github.com/oss-review-toolkit/ort/commit/b9e8b63ace7215f042a80b41f5c8b5fcbedaebea
[^2]: https://github.com/oss-review-toolkit/ort-config/pull/96
BREAKING CHANGE: Align your `ort-config` curations as illustrated in [^2].
**Note: Should be merged after [^2].**

refactor(PackageCurationData)!: Drop support for legacy property name

---

plugins/commands/requirements/src/main/kotlin/RequirementsCommand.kt
plugins/scanners/askalono/src/funTest/kotlin/AskalonoFunTest.kt
plugins/scanners/askalono/src/main/kotlin/Askalono.kt
plugins/scanners/boyterlc/src/funTest/kotlin/BoyterLcFunTest.kt
plugins/scanners/boyterlc/src/main/kotlin/BoyterLc.kt
plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt
plugins/scanners/licensee/src/funTest/kotlin/LicenseeFunTest.kt
plugins/scanners/licensee/src/main/kotlin/Licensee.kt
plugins/scanners/scancode/src/funTest/kotlin/ScanCodeScannerFunTest.kt
plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
plugins/scanners/scancode/src/test/kotlin/ScanCodeTest.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOss.kt
plugins/scanners/scanoss/src/test/kotlin/ScanOssScannerDirectoryTest.kt
plugins/scanners/scanoss/src/test/kotlin/ScanOssScannerFileTest.kt
scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/ScannerMatcher.kt
scanner/src/main/kotlin/ScannerWrapper.kt
scanner/src/main/kotlin/ScannerWrapperConfig.kt
scanner/src/main/kotlin/ScannerWrapperFactory.kt
scanner/src/test/kotlin/ScannerTest.kt
scanner/src/test/kotlin/ScannerWrapperConfigTest.kt

Add properties to configure for each scanner if scan results are read from or written to the configured scan storages. Please see the commit messages for details.
**Breaking API change:**
* The `ScannerWrapperFactory.create()` function now gets a `ScannerWrapperConfig` instead of a `ScannerMatcherConfig`.
* The `ScannerWrapper` interface now requires implementing the two new properties `readFromStorage: Boolean` and `writeToStorage: Boolean`.

Add properties to configure if scan results are read from or written to the scan storages

---

.github/workflows/build-and-test.yml
batect.yml

As all package manager implementations are split out to plugin projects by now, "core" analyzer functional tests do not require external tools anymore and can be run outside of Docker.

test: Run analyzer functional tests outside of Docker

---

plugins/version-control-systems/git/src/main/kotlin/GitRepo.kt

This fixes the "fatal: unable to detect ssh version" error when parsing some OpenSSH version strings, see [1]. Also account for the `--repo-branch` option being renamed to `--repo-rev`.
[1]: https://gerrit.googlesource.com/git-repo/+/90f574f02e0b8432de2ad03951ea74df3464dc38

deps(git-repo): Upgrade to the latest stable git-repo release

---

Dockerfile-legacy

 chore(docker): Extract .NET version to a variable

---

.github/workflows/build-and-test.yml

This is already being done as part of `wrapper-validation.yml`.

chore(github): Remove the duplicate Batect wrapper validation

---

plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
utils/spdx/src/main/kotlin/Utils.kt
utils/spdx/src/test/kotlin/UtilsTest.kt

ScanCode 32.0.0 started to prepend its `*.LICENSE` files with YAML-encoded metadata, see [1]. This is a hot fix to remove this header, if present, from the license files. A better solution will be implemented later as part of a larger refactoring of license providers.
Different ScanCode versions also differ in whether license files come with a final newline or not. Align on not having a final newline to make tests pass either way.
[1]: https://github.com/nexB/scancode-toolkit/pull/3100

fix: Remove any YAML front matter from ScanCode license files

---

plugins/commands/evaluator/src/main/kotlin/EvaluatorCommand.kt

Make the evaluator command print the rules used as part of configuration 

---

scanner/src/main/kotlin/Scanner.kt

Strictly speaking, scanning has not yet started at the time of logging. Change the wording accordingly, and adapt the logging on finishing accordingly.

chore(scanner): Trivially improve the wording of log messages

---

plugins/package-managers/go/src/main/kotlin/GoMod.kt
plugins/package-managers/go/src/test/kotlin/GoModTest.kt

Uppercase-letters in version strings of dependent Go modules caused the analyzer to crash. 
With this fix, uppercase-letters are now properly escaped as any other paths of the Go modules in the file system.

fix(analyzer): Support uppercase-letters in Go module version

---

plugins/reporters/opossum/src/main/kotlin/OpossumReporter.kt
plugins/reporters/opossum/src/test/kotlin/OpossumReporterTest.kt

Do not directly call the low-level `getLicenseText()` function, but get the license texts via the provider passed as part of reporter input.

fix(opossum): Get license texts via the provider

---

Dockerfile-legacy

Make `ANDROID_CMD_VERSION` a build argument in `Dockerfile-legacy` so that the version is configurable when building the image.

feat(docker): Make Android SDK version a build arg in Dockerfile-legacy

---

utils/ort/src/main/kotlin/Environment.kt
utils/ort/src/main/kotlin/Utils.kt

These properties are tightly related to environment variables, so it makes more sense to keep them there. Slightly improve their documentation while at it.

refactor(utils): Move ORT directory properties to `Environment`

---

integrations/jenkins/Jenkinsfile

Later steps use the `usernamePassword()` pipeline function [1] which assumes credentials to be composed of a username and password for HTTP authentication. Clarify this to avoid users specifying e.g. SSH credentials which would result in
ERROR: Credentials 'jenkins-ssh' is of type 'SSH Username with private
key' where 'com.cloudbees.plugins.credentials.common.StandardUsername
PasswordCredentials' was expected
[1]: https://www.jenkins.io/doc/pipeline/steps/credentials-binding/

docs(jenkins): Clarify that the credentials type should be for HTTP

---

helper-cli/build.gradle.kts

Use the same approach as for the main CLI to ensure that plugins required at runtime are bundled with the distribution.

fix(helper-cli): Use the "pluginClasspath" approach to bundle plugins

---

reporter/src/main/kotlin/ReportTableModel.kt
reporter/src/main/kotlin/ReportTableModelMapper.kt

Minor StaticHTML reporter code improvements

---

model/src/main/kotlin/config/ScannerConfiguration.kt
scanner/src/funTest/assets/scanner-integration-all-pkgs-expected-ort-result.yml
scanner/src/funTest/assets/scanner-integration-subset-pkgs-expected-ort-result.yml

Sort `ScannerConfiguration.detectedLicenseMapping` during serialization to have a stable order in ORT result files. This helps when comparing ORT result files from different sources.

feat(model): Sort the detected license mapping during serialization

---

helper-cli/src/main/kotlin/utils/PathExcludeGenerator.kt
helper-cli/src/test/assets/path-exclude-gen/expected-exclude-patterns.txt
helper-cli/src/test/assets/path-exclude-gen/expected-file-exclude-patterns.txt

The `package.json` is included in the distributed artifacts.

fix(helper-cli): Remove `package.json` from path exclude generator

---

plugins/reporters/static-html/src/main/kotlin/ReportTableModel.kt
plugins/reporters/static-html/src/main/kotlin/ReportTableModelMapper.kt
plugins/reporters/static-html/src/main/kotlin/StaticHtmlReporter.kt

Make the model internal and turn it to a class, to simplify cleaning up the code in a following PR.

reporter: Prepare `ReportTabelModelMapper` for some clean-ups

---

advisor/src/main/kotlin/AdviceProviderFactory.kt
advisor/src/main/kotlin/Advisor.kt
analyzer/src/funTest/kotlin/PackageManagerFunTest.kt
analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/Extensions.kt
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/main/kotlin/PackageManagerFactory.kt
analyzer/src/testFixtures/kotlin/Extensions.kt
cli/src/funTest/kotlin/AnalyzerFunTest.kt
cli/src/funTest/kotlin/OrtMainFunTest.kt
helper-cli/src/main/kotlin/utils/Extensions.kt
plugins/commands/advisor/src/main/kotlin/AdvisorCommand.kt
plugins/commands/api/src/main/kotlin/OrtCommand.kt
plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt
plugins/package-configuration-providers/api/src/main/kotlin/PackageConfigurationProviderFactory.kt
plugins/package-curation-providers/api/src/main/kotlin/PackageCurationProviderFactory.kt
plugins/package-managers/pub/src/main/kotlin/Pub.kt
scanner/src/main/kotlin/ScannerWrapper.kt
scanner/src/main/kotlin/ScannerWrapperFactory.kt
scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt

Plugin cleanups

---

plugins/commands/requirements/src/funTest/kotlin/RequirementsCommandFunTest.kt
plugins/commands/requirements/src/main/kotlin/RequirementsCommand.kt

Add a test for core plugins to be found 

---

plugins/commands/compare/src/main/kotlin/CompareCommand.kt

Compare command chores

---

.github/workflows/release.yml

This works around multiple staging repositories being created when publishing.

build(github): Disable parallelization when publishing

---

plugins/package-managers/node/src/main/kotlin/Npm.kt
plugins/package-managers/node/src/main/kotlin/utils/NpmSupport.kt

The originally linked and newly linked NPM docs are somewhat contradictory in this regard, but actual tests show that local NPM projects indeed do not need to have a version set in order for `npm install` / `npm ci` to work, so avoid ORT crashing with a `NullPointerException` in this case.
For now, only address the issue for a missing `version` field by falling back to "0.0.0" which should never be used for a package with a real (semantic) version. The version must be set to something non-empty to satisfy the `require()` statement in line 393.
A future improvement should also handle a missing `name` field and fall back to a project name derived from the project's path (and probably other properties). However, that should be done consistently for all package managers via a global helper …

fix(node): Do not crash on projects that do not set a version

---

integrations/jenkins/Jenkinsfile

This reverts commit 7aac204 as it causes an NPE when triggering the job programmatically:
java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:209)
at com.cloudbees.plugins.credentials.matchers.IdMatcher.<init>(IdMatcher.java:58)
at com.cloudbees.plugins.credentials.CredentialsMatchers.withId(CredentialsMatchers.java:135)
at com.cloudbees.plugins.credentials.CredentialsParameterValue.lookupCredentials(CredentialsParameterValue.java:111)

Revert "chore(jenkins): Omit empty string default values"

---

model/src/main/kotlin/ScanSummary.kt
model/src/test/kotlin/ScanSummaryTest.kt
plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModelMapper.kt
plugins/scanners/scancode/src/test/kotlin/ScanCodeResultParserTest.kt

Eliminate some irrelevant issues from the report, to reduce the need for manually creating irrelevant resolutions. 
Note: The stored scan results do not have the `affectedPath` set. However, the deserialization of scan results has been          
adjusted so that `affectedPath` is properly set during deserialization and there the filtering works even for old 
stored scan results.
Part of #7921.

scanner: Adhere to `Issue.affectedPath` when filtering scan issues

---

clients/fossid-webapp/src/main/kotlin/model/Project.kt

It seems that with latest FossID releases the comment property is now optional. No public changelog is available though.

feat(fossid-webapp): Make the comment of a project optional

---

plugins/commands/advisor/src/main/kotlin/AdvisorCommand.kt
plugins/commands/downloader/src/main/kotlin/DownloaderCommand.kt
plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt

This is a follow-up to 67297b2.

chore(commands): Deprecate the `--skip-excluded` options

---

utils/ort/src/main/kotlin/Utils.kt
utils/ort/src/test/kotlin/UtilsTest.kt

So far ignorable suffixes were only ignored from the given (tag) names. Extend the logic to also ignore them from the given version.

feat(ort-utils): Find names even if the version has an (ignorable) suffix

---

plugins/package-managers/carthage/src/funTest/assets/projects/synthetic/carthage-expected-output.yml
plugins/package-managers/carthage/src/funTest/kotlin/CarthageFunTest.kt

Make the test pass also when run from a fork by not depending on the upstream GitHub organization name.

test(carthage): Make the test independent of the GitHub org ORT is hosted

---

model/src/main/kotlin/utils/ConfigurationResolver.kt
model/src/main/kotlin/utils/DefaultResolutionProvider.kt
model/src/main/kotlin/utils/ResolutionProvider.kt
plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelMapper.kt
plugins/reporters/static-html/src/main/kotlin/ReportTableModelMapper.kt

Use shorter names and make the naming consistent with the overloaded `isResolved()` function.

refactor(model)!: Improve `ResolutionProvider`s getter names

---

buildSrc/build.gradle.kts
gradle/libs.versions.toml

Although listed under `libraries`, these are actually Maven coordinates for Gradle plugins, which is necessary in order to use them in precompiled plugin scripts. To make that more clear, append "Plugin" to their names.

build(Gradle): Rename catalog entries that are actually plugins

---

helper-cli/src/main/kotlin/commands/repoconfig/GenerateRuleViolationResolutionsCommand.kt
helper-cli/src/main/kotlin/commands/repoconfig/RemoveEntriesCommand.kt
helper-cli/src/main/kotlin/utils/Extensions.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/utils/DefaultResolutionProvider.kt
model/src/test/kotlin/OrtResultTest.kt
plugins/commands/reporter/src/main/kotlin/ReporterCommand.kt
plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml
plugins/reporters/opossum/src/funTest/kotlin/OpossumReporterFunTest.kt

Preparations for removing `ReporterInput.resolutionProvider`

---

plugins/commands/analyzer/src/main/kotlin/AnalyzerCommand.kt

For the special case if only one package manager is enabled and the input is a file instead of directory, resolve the repository configuration file correctly, i.e. relative to the parent, as there is no explicit analyzer root directory in this case.

fix(analyzer-command): Resolve repo config correctly if input is a file

---

.github/workflows/release.yml

Publishing already closes the staging repository at Sonatype, but releasing to production requires an extra step, see [1].
[1]: https://vanniktech.github.io/gradle-maven-publish-plugin/central/#__tabbed_6_3

ci(github): Enable auto-release of artifacts from staging to production

---

buildSrc/src/main/kotlin/ort-plugins-conventions.gradle.kts

build(Gradle): Do not apply the built-in `maven-publish` plugin anymore

---

buildSrc/settings.gradle.kts

This silences the following warning which was introduced with e769b0b:
Project accessors enabled, but root project name not explicitly set
for 'buildSrc'. Checking out the project in different folders will
impact the generated code and implicitly the buildscript classpath,
breaking caching.

build(Gradle): Explicitly set name for `buildSrc` module

---

downloader/src/main/kotlin/Downloader.kt

A VCS download can only return a `RepositoryProvenance` and an artifact download can only return an `ArtifactProvenance`. The previous code could have also raised the question how `Provenance?` and `UnknownProvenance` are semantically different, which is now not the case anymore as only a `KnownProvenance` is ever returned.

refactor(downloader): Use more specific provenance return types

---

scanner/src/main/kotlin/ScanController.kt
scanner/src/main/kotlin/Scanner.kt

As of 5559fdd this is the same as `getNestedProvenance()`.

refactor(scanner): Remove `findNestedProvenance()`

---

model/src/main/kotlin/OrtResult.kt
plugins/commands/reporter/src/main/kotlin/ReporterCommand.kt
plugins/reporters/evaluated-model/src/funTest/kotlin/EvaluatedModelReporterFunTest.kt
plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelMapper.kt
plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt
plugins/reporters/opossum/src/funTest/assets/reporter-test-input.yml
plugins/reporters/opossum/src/funTest/kotlin/OpossumReporterFunTest.kt
plugins/reporters/static-html/src/funTest/assets/reporter-test-input.yml
plugins/reporters/static-html/src/funTest/assets/static-html-reporter-test-expected-output.html
plugins/reporters/static-html/src/funTest/kotlin/StaticHtmlReporterFunTest.kt
plugins/reporters/static-html/src/main/kotlin/ReportTableModelMapper.kt
reporter/src/main/kotlin/ReporterInput.kt
reporter/src/main/kotlin/StatisticsCalculator.kt

As of the addition of `OrtResult.resolvedConfiguration`, the ORT result is self-contained WRT to package configurations,
resolutions and curations. So, in theory the `OrtResult` can be passed to each respective `Reporter` without 
any accompanying provider, e.g. `ResolutionProvider`, `CurationProvider` as you name it. This would be less complicated to handle: e.g. make the `ReporterCommand` first include all the data in `OrtResult` and then pass around the `OrtResult` to the reporters.
If you look at the functions `OrtResult.getOpenIssues()` or `OrtResult.getResolutions()`, these consider only resolutions from the repository configuration, but not the ones from the resolved configuration. So, the result of these functions can normally only be used by further processing it with some …

Remove `ReporterInput.resolutionProvider` 

---

plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm-workspaces/pnpm-workspace.yaml
plugins/package-managers/node/src/main/kotlin/utils/NpmDetection.kt
plugins/package-managers/node/src/test/kotlin/utils/NpmDetectionTest.kt

Otherwise paths will not be matched correctly. This fixes a regression from f99e2ed which did contain the `removeSuffix("/")` call, at least for PNPM.

fix(node): Strip a trailing "/" before creating globs

---

utils/spdx/src/main/kotlin/SpdxExpression.kt

Make the difference between these function more clear by implementing one based on the other. This also reduces similar code across the class hierarchy a bit.

refactor(spdx-utils): Implement `licenses()` based on `decompose()`

---

model/src/main/kotlin/utils/PurlExtensions.kt

This is a fixup for 758fd7a to be able to use these functions from plugins.

chore(model): Make newly added PURL extension function public

---

utils/common/src/main/kotlin/ArchiveUtils.kt

This works around [1]. Still keep the `isFile` check to be on the safe side and e.g. skip links.
Resolves #8098.
[1]: https://issues.apache.org/jira/browse/COMPRESS-657

fix(common-utils): Do not extract TAR directory entries as files

---

plugins/package-managers/cargo/src/main/kotlin/Cargo.kt

Ignore metadata entries that do not start with "checksum ".

fix(cargo): Only read checksum metadata entries as hashes

---

plugins/reporters/web-app-template/src/components/IssuesTable.js

Issue messages are mostly pre-formatted tool output, with linebreaks and alignment in the string. Wrapping the messages in `<pre>` blocks preserves this when displaying the messages, making them easier to read and understand.

Use `<pre>` block for issue messages

---

model/src/main/kotlin/Provenance.kt
plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt
scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/ScannerWrapper.kt
scanner/src/main/kotlin/provenance/ProvenanceDownloader.kt
scanner/src/test/kotlin/ScannerTest.kt

Previously, package scanner implementations did not get any information about which VCS path a package is located at in a VCS repository. However, that information might still be required, e.g. to point to the exact "file tree" for browsing the code of a package.
So keep the VCS path as part of the package. Now that package scanners do also get the (nested) provenance, that should be used to determine the root repository the package is located at.
The only package scanner implementation in ORT's code base is for FossId, which already handles a non-empty path by skipping the package as FossId cannot limit scans to sub-paths.

fix(scanner): Keep the VCS path for a package scanner's reference package

---

helper-cli/src/main/kotlin/commands/ListCopyrightsCommand.kt
helper-cli/src/main/kotlin/utils/Extensions.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt
model/src/main/kotlin/utils/OrtResultExtensions.kt
model/src/test/kotlin/licenses/DefaultLicenseInfoProviderTest.kt
model/src/test/kotlin/licenses/LicenseViewTest.kt
plugins/commands/evaluator/src/main/kotlin/EvaluatorCommand.kt
plugins/commands/reporter/src/main/kotlin/ReporterCommand.kt
plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelMapper.kt
reporter/src/main/kotlin/ReporterInput.kt

This PR first of all ensures that the `evaluator` and `reporter` and `list-copyrights` commands add all package configurations to the `OrtResult` before passing it around, and applies resulting simplifications.
This prepares for changing `OrtResult.getIssues()` to filter the issues by path excludes in a following PR.
As a I nice side effect, package configurations are now only resolved once per CLI command run instead of multiple times. 
Part of #7921.

Remove `ReporterInput.packageConfigurationProvider`

---

helper-cli/src/main/kotlin/commands/CreateAnalyzerResultFromPackageListCommand.kt

The only thing this command consumes from the configuration are the entries for package curation providers.

docs(helper-cli): Fix-up a copy and paste mistake

---

utils/spdx/src/main/kotlin/SpdxExpression.kt
utils/spdx/src/test/kotlin/SpdxExpressionTest.kt

Simplifications to determining valid license choices

---

README.md

Use official project name as listed on project website[1] to improve inclusion of ORT in GitHub/Google search results.
[1]: https://www.swift.org/package-manager

docs(README): Rename Swift package manager

---

plugins/package-managers/spm/src/funTest/assets/projects/synthetic/spm-expected-output-app.yml
plugins/package-managers/spm/src/funTest/assets/projects/synthetic/spm-expected-output-lib.yml
plugins/package-managers/spm/src/main/kotlin/Spm.kt
plugins/package-managers/spm/src/main/kotlin/SpmModel.kt
plugins/package-managers/spm/src/test/kotlin/SpmTest.kt

Ensure identifiers of dependencies are unique, stop using arbitrarily chosen organization name as namespace, and overall simplify the derivation of identifiers. The identifiers become pretty much aligned with the ones from `GoMod`.
Part of #8123.

SPM: Improve the format for identifiers

---

integrations/jenkins/Jenkinsfile

This can be used e.g. from the web-app report's "About" screen to jump back to the build that created the report.

feat(jenkins): Add a label to link back the the build URL

---

plugins/package-managers/spm/src/main/kotlin/Spm.kt
plugins/package-managers/spm/src/main/kotlin/SpmModel.kt

Primarily separate the models for `Package.resolved` (lockfile) and `Package.swift` (definitionFile) in order to prepare for
handling multiple file format versions of `Package.resolved`. Furthermore, clarify miscellaneous related things a bit.
Part of #8123.

Further `Spm` improvements

---

plugins/package-managers/pub/src/main/kotlin/Pub.kt

If `readPackageInfoFromCache` returns `EMPTY_JSON_NODE`, then `textValue()` throws java.lang.NullPointerException

fix(pub): Do not rely on the package `name` to be present

---

analyzer/src/main/kotlin/managers/utils/PackageManagerDependencyHandler.kt

Kotlin contracts are already enabled via the Kotlin conventions plugin on the compiler task level.

chore(analyzer): Remove an unneeded annotation

---

clients/osv/src/funTest/assets/vulnerability-by-id-expected-result.json
plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-lockfile-v3.yml
utils/test/src/main/kotlin/Utils.kt

Also fix the `REPLACE_ABSOLUTE_DEFINITION_FILE_PATH` placeholder to be invariant, just like `REPLACE_DEFINITION_FILE_PATH` is.

test(swiftpm): Avoid a hard-coded path in test results

---

plugins/package-managers/node/src/main/kotlin/Npm.kt
plugins/package-managers/node/src/main/kotlin/Pnpm.kt

This generalizes the `maxDepth`-related work-around done for PNPM to fix a similar issue for Yarn if the `node_modules` directory hierarchy contains cyclic links. This is done by maintaining a temporary set of visited "real" directories.
The issue was interesting to debug as the infinite loop caused by circular links was only triggered when actually evaluating the lazy sequence created by `File.walk()`.
While at it, make the filtering for `package.json` a bit more strict by requiring it to be a file.
Fixes #6531.

fix(node): Do not follow cyclic directory links

---

plugins/version-control-systems/git/src/main/kotlin/Git.kt

Fix resetting a Git working tree to the latest revision of a branch

---

plugins/package-managers/swiftpm/src/funTest/kotlin/SwiftPmFunTest.kt

This got accidentally broken by a recent commit.

test(swiftpm): Fix-up a test case name

---

plugins/package-managers/node/src/main/kotlin/Npm.kt

NPM issue mapping improvements

---

utils/spdx/src/main/resources/exception-mapping.yml

Small improvements to exception mapping data

---

Dockerfile

The Swift version is replicated in three file locations. The version became inconsistent by accident, see [1].
[1]: https://github.com/oss-review-toolkit/ort/pull/8023

chore(docker): Re-align `SWIFT_VERSION`

---

plugins/package-managers/pub/src/funTest/assets/projects/external/dart-http-expected-output.yml
plugins/package-managers/pub/src/funTest/assets/projects/synthetic/pub-expected-output-any-version.yml
plugins/package-managers/pub/src/funTest/assets/projects/synthetic/pub-expected-output-multi-module.yml
plugins/package-managers/pub/src/funTest/assets/projects/synthetic/pub-expected-output-with-flutter-android-and-cocoapods.yml
plugins/package-managers/pub/src/main/kotlin/Pub.kt

Add support for source artifacts for hosted packages. See the commit messages for details.

Pub: Parse source artifacts for hosted packages

---

plugins/package-managers/pub/src/funTest/assets/projects/external/dart-http-expected-output.yml
plugins/package-managers/pub/src/funTest/assets/projects/synthetic/pub-expected-output-any-version.yml
plugins/package-managers/pub/src/funTest/assets/projects/synthetic/pub-expected-output-with-flutter-android-and-cocoapods.yml
plugins/package-managers/pub/src/main/kotlin/Pub.kt

The repository URLs taken from the pubspec.yaml in the local Pub cache often point to the main or master branch of the repository, for example:
https://github.com/dart-lang/sdk/tree/main/pkg/_fe_analyzer_shared
As there was not a single example where the URL pointed to the correct revision that matches the release of the package, simply ignore the revision.
Fixes #5542.

fix(pub): Do not use the revision from the pubspec.yaml of dependencies

---

cli/src/funTest/kotlin/OrtMainFunTest.kt
integrations/jenkins/Jenkinsfile
model/src/main/kotlin/config/OrtConfiguration.kt
model/src/test/kotlin/JsonSchemaTest.kt
model/src/test/kotlin/config/OrtConfigurationTest.kt
model/src/test/kotlin/config/ReporterConfigurationTest.kt
model/src/test/kotlin/config/ScannerConfigurationTest.kt
plugins/commands/advisor/src/main/kotlin/AdvisorCommand.kt
plugins/commands/analyzer/src/main/kotlin/AnalyzerCommand.kt
plugins/commands/config/src/main/kotlin/ConfigCommand.kt
plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt
utils/ort/src/main/kotlin/Constants.kt

Status code docs improvements

---

model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
plugins/scanners/scancode/src/funTest/kotlin/ScanCodeScannerFunTest.kt
plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
plugins/scanners/scancode/src/main/kotlin/ScanCodeConfig.kt
plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModelMapper.kt
plugins/scanners/scancode/src/test/kotlin/ScanCodeResultParserTest.kt
plugins/scanners/scancode/src/test/kotlin/ScanCodeTest.kt

Add an option to prefer ScanCode's file- over line-level findings 

---

plugins/package-managers/node/src/main/kotlin/Npm.kt

Please have a look at the individual commit messages for the details. 
The second commits is just a proposal, I'm fine to also drop it again.

Further NPM CLI issue adjustments

---

plugins/version-control-systems/git/src/main/kotlin/Git.kt

JGit still does not support sparse checkouts [1], and its `reset` call turns the sparse checkout done by `git checkout` into a full checkout.
So again use the Git CLI to perform the actual reset like done before 8472931, but continue to determine the resolved revision to reset to via JGit.
Fixes #8195.
[1]: https://bugs.eclipse.org/bugs/show_bug.cgi?id=383772

fix(git): Again use the Git CLI to perform the actual `reset`

---

.github/workflows/release.yml
buildSrc/src/main/kotlin/ort-publication-conventions.gradle.kts

Signing is not set up for JitPack, so simply disable it as these are just snapshot builds.

build: Only sign when making official releases

---

plugins/package-curation-providers/ort-config/src/funTest/kotlin/OrtConfigPackageCurationProviderFunTest.kt
plugins/package-curation-providers/ort-config/src/main/kotlin/OrtConfigPackageCurationProvider.kt

Support namespace-level package curations from `ort-config`

---

downloader/src/main/kotlin/Downloader.kt
downloader/src/main/kotlin/VersionControlSystem.kt
helper-cli/src/main/kotlin/commands/scanstorage/DeleteCommand.kt
plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
plugins/scanners/fossid/src/main/kotlin/FossIdUrlProvider.kt
plugins/version-control-systems/git/src/funTest/kotlin/GitDownloadFunTest.kt
plugins/version-control-systems/git/src/main/kotlin/Git.kt
utils/ort/src/main/kotlin/OkHttpClientHelper.kt
utils/ort/src/main/kotlin/storage/HttpFileStorage.kt

URLs cannot contain literal spaces, so there usually is no need to quote them for readability.

chore: Generally do not quote URL as part of messages

---

model/src/main/kotlin/Hash.kt
plugins/package-managers/conan/src/main/kotlin/Conan.kt

Today's failing `ConanFunTest` showed that it can happen that the hash value is uppercase.
Try to make it lowercase in more cases.

Hash value fixes

---

plugins/package-managers/pub/src/main/kotlin/Pub.kt
utils/common/src/main/kotlin/Extensions.kt

Small hash-related improvements

---

integrations/jenkins/Jenkinsfile

Enable this by default for performance reasons of showcasing ORT. For simplicity, only use a single parameter for all tools as there is barely a need to configure this flag differently per tool.

feat(jenkins): Add a parameter to skip excluded scopes and paths

---

plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt
plugins/advisors/vulnerable-code/src/test/kotlin/VulnerableCodeTest.kt

VulnerableCode URL escape fixes

---

plugins/package-managers/swiftpm/src/main/kotlin/SwiftPm.kt
plugins/package-managers/swiftpm/src/main/kotlin/SwiftPmModel.kt

The data model for the top level package and for the nested dependencies is identical. So, there is no need to define a nested `Dependency` class.

refactor(SwiftPM): De-duplicate a class

---

plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-only-lockfile-v1.yml
plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-only-lockfile-v2.yml
plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-only-lockfile-v3.yml
plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-project-with-lockfile.yml
plugins/package-managers/swiftpm/src/main/kotlin/SwiftPm.kt

As a first step, this PR moves from the dependency graph builder to the old way of constructing things, to simplify the following steps. Then, the implementation is enhanced by:
1. Properly set the version strings and revision for the `Package.swift` analysis by creating 
the result based on the lockfile entries, while using the previously used `swift package show-dependencies` entries
only as a fallback.
2. Properly assign all packages to a scope for the lockfile-only analysis. Previously, no links between packages
and projects have been created.
3. Remove the invalid fallback to the `version` for `vcs.revision`.
Note: This PR should be merged after #8233.

SwiftPM enhancements

---

plugins/package-managers/swiftpm/src/main/kotlin/SwiftPm.kt

When a dependency is specified using a branch, running [^1] yields "unspecified" as the version. Use an empty string in this case for consistency.
[^1]: `swift package show-dependencies`

fix(swiftpm): Ignore "unspecified" versions

---

plugins/scanners/askalono/src/main/kotlin/Askalono.kt
plugins/scanners/askalono/src/main/kotlin/AskalonoResultModel.kt

When working on unrelated changes, I noticed that the Askalono wrapper assumes the "result" key is always present. Maybe that used to be the case, but the version I'm using (0.4.6) produces the following structure:
```
{"path":"./COPYING","error":"Confidence threshold not high enough for any known license"}
```

fix(askalono): Correctly handle errors in results

---

build.gradle.kts

This was required for version 0.12.0 by accident, see [1].
[1]: https://github.com/jmongard/Git.SemVersioning.Gradle/issues/51

chore(Gradle): Remove a work-around for the SemVersioning plugin

---

integrations/jenkins/Jenkinsfile

In the "dummy" stage for building the Docker image, change the command to list the plugins, to do something more meaningful than just showing the version.

feat(jenkins): Add optional parameters to install plugins from another job

---

integrations/jenkins/Jenkinsfile
plugins/commands/analyzer/src/main/kotlin/AnalyzerCommand.kt

This can be useful when enabling only a single package manager and pointing the analyzer to a single file for testing analysis of a single project.

feat(jenkins): Allow to specify an input path within the repository

---

plugins/commands/upload-result-to-sw360/src/main/kotlin/UploadResultToSw360Command.kt

The optional infix should be a string without path separators, so simply omit it for simplicity.

fix(sw360): Do not use a path as the temp dir infix

---

.github/workflows/release.yml

Publishing artifacts does not work with the configuration cache yet, see [1].
[1]: https://github.com/gradle/gradle/issues/22779

build(github): Disable the Gradle configuration cache when releasing

---

.github/workflows/release.yml
gradle.properties

Re-enable the Gradle configuration cache when not publishing

---

plugins/version-control-systems/subversion/src/main/kotlin/Subversion.kt

The `initWorkingTree()` function is documented to throw `IOException`, and that is what callers catch. Avoid ORT to crash on a
`UnknownHostException` -> `SVNException` -> `DownloadException`
chain by re-throwing a `IOException` here.

fix(subversion): Throw `IOException` instead of `DownloadException`

---

utils/spdx/src/main/kotlin/model/SpdxDocument.kt
utils/spdx/src/test/kotlin/model/SpdxDocumentTest.kt

While at it, simplify the `SpdxDocument` docs to just point at the Markdown specification for version 2.2.2.

docs(spdx): Consistently refer to patch-level version 2 of SPDX 2.2

---

plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
plugins/package-managers/gradle/src/main/kotlin/Gradle.kt

This fixes parsing JVM args like [1].
[1]: https://github.com/JetBrains/ideavim/blob/e443cb0/gradle.properties#L36

fix(gradle): Unquote JVM args before forwarding them to Gradle

---

plugins/package-managers/gradle/src/main/kotlin/Gradle.kt

Simplify code a bit by working with a map, and also replace a deprecated JVM argument.

chore(gradle): Align JVM args mapping code with `GradleInspector`

---

.github/workflows/build-and-test.yml

Since version 4 the token is no longer optional [1], so forward it from a configured GitHub secret.
[1]: https://github.com/codecov/codecov-action?tab=readme-ov-file#breaking-changes

build(github): Pass a token to Codecov

---

scanner/src/main/kotlin/Scanner.kt

The `downloadRecursively()` function rethrows `IOException` as `DownloadException`, so the latter needs to be catched here.

fix(scanner): Catch a `DownloadException` instead of `IOException`

---

plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt

GradleInspector: Ignore artifacts of zero byte size

---

utils/ort/src/main/kotlin/storage/HttpFileStorage.kt
utils/ort/src/main/kotlin/storage/S3FileStorage.kt

Simplify storage code

---

plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt

In addition to the scan storages, also log the provenance storages at info level.

feat(scanner): Log the configured provenance storages

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
clients/clearly-defined/build.gradle.kts
clients/fossid-webapp/src/main/kotlin/Extensions.kt
clients/nexus-iq/build.gradle.kts
clients/osv/build.gradle.kts
clients/scanoss/build.gradle.kts
clients/vulnerable-code/build.gradle.kts
evaluator/build.gradle.kts
model/src/main/kotlin/Hash.kt
plugins/advisors/osv/build.gradle.kts
plugins/package-managers/cargo/build.gradle.kts
plugins/package-managers/go/build.gradle.kts
plugins/package-managers/nuget/build.gradle.kts
plugins/package-managers/python/build.gradle.kts
plugins/package-managers/swiftpm/build.gradle.kts
plugins/reporters/ctrlx/build.gradle.kts
plugins/reporters/gitlab/build.gradle.kts
plugins/reporters/trustsource/build.gradle.kts
plugins/scanners/askalono/build.gradle.kts
plugins/scanners/boyterlc/build.gradle.kts
plugins/scanners/licensee/build.gradle.kts
plugins/scanners/scancode/build.gradle.kts
scanner/build.gradle.kts

Kotlin Base64-encoding

---

scanner/src/funTest/kotlin/provenance/AbstractNestedProvenanceStorageFunTest.kt
scanner/src/funTest/kotlin/provenance/AbstractPackageProvenanceStorageFunTest.kt
scanner/src/funTest/kotlin/provenance/DefaultNestedProvenanceResolverFunTest.kt
scanner/src/funTest/kotlin/provenance/DefaultPackageProvenanceResolverFunTest.kt
scanner/src/main/kotlin/provenance/FileBasedNestedProvenanceStorage.kt
scanner/src/main/kotlin/provenance/FileBasedPackageProvenanceStorage.kt
scanner/src/main/kotlin/provenance/NestedProvenanceResolver.kt
scanner/src/main/kotlin/provenance/NestedProvenanceStorage.kt
scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
scanner/src/main/kotlin/provenance/PackageProvenanceStorage.kt
scanner/src/main/kotlin/provenance/PostgresNestedProvenanceStorage.kt
scanner/src/main/kotlin/provenance/PostgresPackageProvenanceStorage.kt

Say `write` instead of `put` to match `read` functions and to align with the `ScanStorage` interfaces.

refactor(scanner)!: Align provenance storages on `write` instead of `put`

---

helper-cli/src/main/kotlin/HelperMain.kt
helper-cli/src/main/kotlin/commands/provenancestorage/DeleteCommand.kt
helper-cli/src/main/kotlin/commands/provenancestorage/ProvenanceStorageCommand.kt
scanner/src/funTest/kotlin/provenance/DefaultPackageProvenanceResolverFunTest.kt
scanner/src/main/kotlin/provenance/FileBasedPackageProvenanceStorage.kt
scanner/src/main/kotlin/provenance/PackageProvenanceStorage.kt
scanner/src/main/kotlin/provenance/PostgresPackageProvenanceStorage.kt
utils/ort/src/main/kotlin/storage/FileStorage.kt
utils/ort/src/main/kotlin/storage/HttpFileStorage.kt
utils/ort/src/main/kotlin/storage/LocalFileStorage.kt
utils/ort/src/main/kotlin/storage/S3FileStorage.kt

Add a helper command to delete stored provenance by package id

---

buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts

When running through Gradle, the app's output is redirected to terminal detection does not work. Force color in this case if the host's terminal actually supports color. This way e.g.
./gradlew :cli:run --args="--help"
shows colorful help output.

build(Gradle): Force color for the `run` task if the terminal supports it

---

clients/osv/src/funTest/kotlin/OsvServiceFunTest.kt

Recently, the tests failed because the results kept on alternating between URLs with and without trailing slashes. So, make the test tolerate both in order to reduce the flakyness.

test(osv): Make the test resilient WRT trailing slashes in URLs

---

gradle.properties

fix(gradle): Bump the SPDX license list version to 3.23

---

clients/clearly-defined/build.gradle.kts
clients/clearly-defined/src/main/kotlin/CoordinatesSerializer.kt
clients/clearly-defined/src/main/kotlin/Curation.kt
clients/clearly-defined/src/main/kotlin/Definition.kt
clients/nexus-iq/build.gradle.kts
clients/nexus-iq/src/main/kotlin/NexusIqService.kt
clients/osv/build.gradle.kts
clients/osv/src/main/kotlin/EventSerializer.kt
clients/osv/src/main/kotlin/Model.kt
clients/osv/src/main/kotlin/OsvApiClient.kt
gradle/libs.versions.toml

Migrate from custom kotlinx-serializers for Java types to ks3

---

integrations/schemas/repository-configuration-schema.json
model/src/main/kotlin/config/RepositoryConfiguration.kt
model/src/main/kotlin/config/SnippetChoices.kt
model/src/main/kotlin/config/snippet/Provenance.kt
model/src/main/kotlin/config/snippet/SnippetChoice.kt
model/src/main/kotlin/config/snippet/SnippetChoiceReason.kt
model/src/test/kotlin/config/RepositoryConfigurationTest.kt
scanner/src/main/kotlin/ScanContext.kt
scanner/src/main/kotlin/Scanner.kt
website/docs/configuration/snippet-choice.md

This pull request introduces the Snippet Choice feature to ORT.
Please have a look at the documentation in `website/docs/configuration/snippet-choice.md`.

Snippet Choice

---

plugins/package-managers/node/src/main/kotlin/utils/NpmSupport.kt

This reduces nesting and simplifies an upcoming change.

refactor(node): Restructure `parseNpmVcsInfo()` to use an early return

---

model/src/test/kotlin/utils/FindingsMatcherTest.kt

Do not throw already on the first assertion failure.

test(model): Assert multiple assertions in a test case softly

---

utils/spdx/src/main/kotlin/SpdxExpression.kt

Use SPDX 2.2 links (also see a6ad62b) and generally improve the wording along the way.

docs(spdx-utils): Update class documentation with valid links

---

plugins/scanners/fossid/src/main/kotlin/FossId.kt

Previous versions of FossID could stay blocked in the state NOT_FINISHED while downloading the repository.  Therefore, during the call to `waitDownloadComplete`, a workaround that checks Git output was put in place.
However, with the newest version of FossID (23.3.0), trying to call "trigger scan" when the download is not finished could lead to an error "Downloading scan files from the git repository is NOT FINISHED. Please wait a little and click rescan button.".
Therefore, this commit adds a version check to the workaround.

fix(fossid-webapp): Add a version check in `waitDownloadComplete`

---

plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt

`coerce` needs to be used because FossID versions are not valid semantic versions e.g. "23.3".
This follows discussion on https://github.com/oss-review-toolkit/ort/pull/8352.

fix(fossid-webapp): Replace version comparison with Semver

---

Dockerfile-legacy

Since Cargo package manager has no version requirement, always use the version of Cargo available in Ubuntu.

build(Docker): Remove explicit Cargo version

---

plugins/reporters/web-app-template/src/components/PackageFindingsTable.js

Use localeCompare to sort paths textually.
Currently paths are sorted by their length, which produces an output that is hard to use. It seems much more natural to sort paths textually.
Old behaviour:
New behaviour:

feat(reporter): Sort license finding paths with localeCompare

---

.markdownlint-cli2.yaml
.markdownlint.yaml
README.md

Reformat README

---

plugins/package-managers/spdx/src/main/kotlin/SpdxDocumentFile.kt

Do not hard-code scope relationships to avoid missing new ones that might get added in upcoming SPDX versions.

chore(spdx): Get the scope relationships dynamically

---

plugins/advisors/nexus-iq/src/main/kotlin/NexusIq.kt
plugins/advisors/oss-index/src/main/kotlin/OssIndex.kt
plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt

Do not regenerate the PURL from the package ID, but use the PURL that is already stored as part of the package as that might be a custom PURL, e.g. coming from a curation.
For VulnerableCode, this fixes a regression introduced the the refactoring in 70916bf.
Fixes #8385.

fix(advisors): Use potentially customized PURLs in advisor queries

---

plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
plugins/scanners/fossid/src/test/kotlin/FossIdLicenseMappingTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdSnippetChoiceTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdSnippetMappingTest.kt

License findings from marked as identified files contain only the path, with a missing line range since FossID does not return this information. On the other hand, license findings from chosen snippets  contain the full source location.
If a snippet is chosen but is not present in the snippet results, an issue is added to the ORT scan results.

feat(fossid-webapp): Add license findings from snippet choice

---

utils/test/build.gradle.kts
utils/test/src/main/resources/kotest.properties

See [1] for details.
[1]: https://kotest.io/docs/next/framework/project-config.html#runtime-detection

build: Disable Kotest's classpath scanning for faster test startup

---

plugins/commands/notifier/src/main/kotlin/NotifierCommand.kt

If available, use only the resolved resolutions in the `NotifierCommand` instead of resolving them again. This increases consistency with previously executed ORT commands.

feat(cli): Use the resolved resolutions in `NotifierCommand`

---

downloader/src/main/kotlin/Downloader.kt
examples/curations.yml
model/src/main/kotlin/Package.kt
model/src/main/kotlin/PackageCurationData.kt
model/src/main/kotlin/config/DownloaderConfiguration.kt
model/src/main/kotlin/utils/Extensions.kt
model/src/test/kotlin/PackageCurationDataTest.kt
model/src/test/kotlin/PackageTest.kt
scanner/src/funTest/kotlin/provenance/DefaultPackageProvenanceResolverFunTest.kt
scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
scanner/src/test/kotlin/ScannerTest.kt
website/docs/configuration/package-curations.md

If one wants to scan a certain package with a different source code origin priority, the only work around to make ORT do so was to nullify the "other" provenance. This PR introduces a dedicated, machine readable property which allows to write clean fixes / curations for this use case. This in turn enables to share such curations, e.g. potentially in 'ort-config', and removes the need for this rather ugly work-around.
Fixes #8402.

Allow to set the `sourceCodeOrigins` priority on package granularity

---

plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
plugins/package-managers/gradle/src/main/kotlin/Gradle.kt

Big thanks to @brigaccess for findings and filing https://github.com/gradle/gradle/issues/28464!

Address a possible Gradle progress listener bug

---

scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
scanner/src/test/kotlin/ScannerTest.kt

Drop the `Priority`-suffix to align with the `sourceCodeOriginsProperty` in other places, e.g. in `Package`. Adjust the KDoc to make clear that the given list of source code origins is in order of priority.
While at it, re-word the comment a bit further, and re-align the analog part of the comment in the `PackageProvenanceResolver` interface with the one in the `DefaultPackageProvenanceResolver` class.

refactor(scanner): Rename `sourceCodeOriginsPriority`

---

plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt

Implement a Gradle 8.2 work-around for repository ids

---

plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
plugins/scanners/fossid/src/test/kotlin/FossIdLicenseMappingTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdSnippetMappingTest.kt

Currently, the licenses of the files marked as identified in FossID are mapped to SPDX using the detected license mapping. The licenses of the snippet however is mapped using the declared license mapping. This commit aligns these behaviors to always use the detected license mapping.

fix(fossid-webapp): Align license mapping for snippets

---

clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
clients/nexus-iq/src/main/kotlin/NexusIqService.kt
clients/oss-index/src/main/kotlin/OssIndexService.kt
clients/osv/src/main/kotlin/OsvApiClient.kt
clients/scanoss/src/main/kotlin/ScanOssService.kt
clients/vulnerable-code/src/main/kotlin/VulnerableCodeService.kt
gradle/libs.versions.toml

See [1].
[1]: https://github.com/square/retrofit/releases/tag/2.10.0

build(Gradle): Switch to the official KxS converter for Retrofit

---

model/src/main/kotlin/utils/FindingsMatcher.kt

Allow this to be called from plugins, like package configuration providers that need to fixup the declared license of a license finding curation.

refactor(model): Make an `associateLicensesWithExceptions` overload public

---

plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt

This commit fixes an issue I reported earlier in Slack conversation. Sometimes, POM cannot be resolved by ORT for one reason or another. When this happens, the analysis finishes early, omitting dependencies that have POMs but were unlucky to be listed after the POMless one.
The fix itself is simple: instead of requiring a non-null value in POMs map (through `getValue`), add a warning and leave the fields empty when the returned POM is null.
In my particuar case, ORT fails scanning [1] and [2] without the patch due to Gradle IntelliJ Plugin [3] injecting dependencies without POMs.
[1] https://github.com/JetBrains/Grammar-Kit
[2] https://github.com/JetBrains/ideavim
[3] https://github.com/JetBrains/intellij-platform-gradle-plugin

fix(gradle-plugin): Do not fail with NPE when dependency POMs are missing

---

helper-cli/src/funTest/kotlin/commands/CreateAnalyzerResultFromPackageListCommandFunTest.kt
plugins/scanners/scancode/src/funTest/kotlin/ScanCodeScannerFunTest.kt
scanner/src/test/kotlin/utils/FileListResolverTest.kt

These are cleaned up automatically.

refactor: Use Kotest's own `tempdir()` in tests

---

plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModel.kt

When ScanCode is run with `--license-text`, `matched_text` fields are added to license findings that contain the matched license text. Support reading those fields even if they are not used yet. This enables programmatic use of those fields and / or future use e.g. when deserializing ScanCode results from ClearlyDefined (which runs ScanCode with `--license-text`).

feat(scancode): Support reading `matched_text` fields

---

integrations/schemas/package-managers-schema.json

These two most recently added package managers have not made it to this array yet.

fix/schemas: Add missing entries for package managers

---

plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
plugins/scanners/fossid/src/test/kotlin/FossIdLicenseMappingTest.kt

This call was needed because of the bug fixed by [1]. Therefore, it can now be removed. A test is also added that checks this behavior.
[1]: https://github.com/oss-review-toolkit/ort/pull/8447

fix(fossid-webapp): Remove unecessary call to `normalize`

---

plugins/package-managers/cargo/src/main/kotlin/Cargo.kt
plugins/package-managers/cargo/src/main/kotlin/CargoLockfile.kt
plugins/package-managers/cargo/src/main/kotlin/CargoMetadata.kt

More Cargo improvements

---

renovate.json

`config:base` was renamed to `config:recommended` in release 36.0.0 [1].
[1]: https://github.com/renovatebot/renovate/releases/tag/36.0.0

ci(renovate): Extend from `config:recommended`

---

model/src/main/kotlin/OrtResult.kt
model/src/test/kotlin/OrtResultTest.kt

Align with `getRuleViolations()` and `getVulnerabilities()` and make the API more flexible.
This prepares for filtering the issues by their affected path in a following change.
Context: #7921.

model: Improve and align `OrtResult.getIssues()`

---

model/src/main/kotlin/Mappers.kt
plugins/package-managers/node/src/test/kotlin/utils/NpmSupportTest.kt

test(node): Cover textual repository nodes

---

.github/workflows/build-and-test.yml
.github/workflows/release.yml
.github/workflows/static-analysis.yml
.github/workflows/wrapper-validation.yml

See [1]. Still validate the wrapper only once instead of using (every) `setup-gradle` with `validate-wrappers: true` [2].
[1]: https://github.com/gradle/actions/releases/tag/v3.3.0
[2]: https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#gradle-wrapper-validation

build(github): Migrate to the new Gradle actions

---

helper-cli/src/main/kotlin/commands/repoconfig/GenerateScopeExcludesCommand.kt
helper-cli/src/main/kotlin/commands/repoconfig/RemoveEntriesCommand.kt
helper-cli/src/main/kotlin/utils/Extensions.kt

Small improvements to the `GenerateScopeExcludesCommand`

---

integrations/jenkins/Jenkinsfile

Jenkins pipeline fixes

---

.github/workflows/docker-build.yml

Set infinite fetch depth for the `docker-build` workflow to be sure to get all tags for calculating the correct version.
This is a fixup for 94ef009.

ci(github): Set infinite fetch depth for `docker-build`

---

.github/workflows/build-and-test.yml
.github/workflows/static-analysis.yml

The `arguments` parameter of the `setup-gradle` action is deprecated and will be removed in `setup-gradle@v4` [1].
[1]: https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated

ci(github): Stop using the deprecated `arguments` of `setup-gradle`

---

website/docs/configuration/package-curations.md

The `source_code_origins` property is an array. This is a fix-up of 433778b.

docs(website): Fix-up a package curation example

---

integrations/schemas/ort-configuration-schema.json
model/src/main/kotlin/config/PostgresConnection.kt
model/src/main/kotlin/utils/DatabaseUtils.kt

The implementation has been done based on [1].
Fixes #8543.
[1]: https://github.com/eclipse-apoapsis/ort-server/commit/f0f601e1c20d0e6f94d9e9c0240ea33098410ab8

feat(model): Allow configuring further PostgreSQL connection parameters

---

.codecov.yml

See [1].
[1]: https://docs.codecov.com/docs/pull-request-comments#after_n_builds

Fix CodeCov calls after which to comment

---

model/src/test/kotlin/OrtResultTest.kt

`OrtResultTest` improvements

---

plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml
plugins/reporters/opossum/src/funTest/assets/reporter-test-input.yml
plugins/reporters/static-html/src/funTest/assets/reporter-test-input.yml
plugins/reporters/static-html/src/funTest/assets/static-html-reporter-test-expected-output.html
plugins/reporters/static-html/src/funTest/kotlin/StaticHtmlReporterFunTest.kt

First preparations for implementing #8373.

test(reporters): Add three scan issues to report test assets

---

analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/PackageManager.kt
downloader/src/funTest/kotlin/DownloaderFunTest.kt
downloader/src/main/kotlin/Downloader.kt
plugins/package-managers/node/src/main/kotlin/Npm.kt
plugins/package-managers/sbt/src/main/kotlin/Sbt.kt
plugins/version-control-systems/git/src/funTest/kotlin/GitDownloadFunTest.kt
plugins/version-control-systems/mercurial/src/funTest/kotlin/MercurialDownloadFunTest.kt
plugins/version-control-systems/subversion/src/funTest/kotlin/SubversionDownloadFunTest.kt
utils/spdx/build.gradle.kts

File walk alignments

---

plugins/reporters/static-html/src/main/kotlin/StaticHtmlReporter.kt

This is a fix-up for [1].
[1]: https://github.com/oss-review-toolkit/ort/commit/405fd4351838d98cd82bfb74cebc0505d1bfa0d5

fix(reporter): Fix-up determining the worst severity

---

downloader/src/main/kotlin/VersionControlSystem.kt
plugins/version-control-systems/mercurial/src/main/kotlin/Mercurial.kt
plugins/version-control-systems/subversion/src/main/kotlin/Subversion.kt
scanner/src/funTest/kotlin/provenance/DefaultNestedProvenanceResolverFunTest.kt

Subversion fixes

---

plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelMapper.kt

Consistently use indexed references.
Context: #7921.

EvaluatedModel: Fix-up path excludes serialization

---

evaluator/src/main/kotlin/PackageRule.kt

See [1].
[1]: https://github.com/oss-review-toolkit/ort/security/code-scanning/3458

perf(evaluator): Turn a list into a sequence to address an inspection hint

---

plugins/reporters/web-app-template/src/components/IssuesTable.jsx
plugins/reporters/web-app-template/src/components/RuleViolationsTable.jsx
plugins/reporters/web-app-template/src/components/VulnerabilitiesTable.jsx

Having the excluded state visualized directly next to the package identifier can mis-lead the users into thinking that it means "package is excluded". However, it should mean "issue is excluded". Swap the columns to make this less likely to happen.
Part of: #7921.

WebApp: Swap columns in summary views

---

model/src/main/kotlin/OrtResult.kt
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedIssue.kt
plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelMapper.kt
plugins/reporters/web-app-template/src/components/IssuesTable.jsx
plugins/reporters/web-app-template/src/models/WebAppOrtIssue.js

The effect on the UI is visible only under the issues summary view and is as follows:
1. The excluded state icon of issues now reflects excluded affected paths
2. The filtering of excluded issues now filters out issues with excluded affected paths
Note: This PR can be easily verified by creating a WebApp report from `./plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml`.
Part of: #7921.
1. Excluded scan timeout issue for non-excluded package `Gradle:org.ossreviewtoolkit.gradle.example:lib:1.0.0` now grayed out: 
2. After adjusting the filter for excluded issues, the issue is properly hidden:

WebApp: Reflect excluded affected paths of issues in the UI

---

plugins/package-managers/cargo/src/main/kotlin/Cargo.kt

E.g. when analyzing a single Cargo project in a sub-directory with a `cargo.toml` file that points to "path dependencies" in a parent directory, these dependencies should not be seen as projects but as packages. This restores the behavior from before 7522a0c.
Resolves #8571.

fix(cargo): Treat projects outside the analyer root as packages

---

.github/workflows/build-and-test.yml
plugins/package-managers/gradle-inspector/src/funTest/kotlin/GradleAndroidFunTest.kt
plugins/package-managers/gradle-inspector/src/funTest/kotlin/GradleFunTest.kt
plugins/package-managers/gradle/src/funTest/kotlin/GradleAndroidFunTest.kt
plugins/package-managers/gradle/src/funTest/kotlin/GradleFunTest.kt
plugins/scanners/licensee/src/funTest/kotlin/LicenseeFunTest.kt
plugins/scanners/scancode/src/funTest/kotlin/ScanCodeScannerFunTest.kt
plugins/version-control-systems/git/src/funTest/kotlin/GitDownloadFunTest.kt
plugins/version-control-systems/mercurial/src/funTest/kotlin/MercurialDownloadFunTest.kt
plugins/version-control-systems/subversion/src/funTest/kotlin/SubversionDownloadFunTest.kt

Disable expensive tests for PR and `main` builds 

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature.md

feat(github): Create issue templates

---

.github/workflows/docker-build.yml

Disable pushing of Docker images for the `docker-build` workflow if it was triggered by a pull request. For pull requests the workflow should only verify that the Docker build works, but not publish any images.

ci(github): Do not push Docker images for pull requests

---

model/src/main/kotlin/OrtResult.kt
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
reporter/src/main/kotlin/Statistics.kt
reporter/src/main/kotlin/StatisticsCalculator.kt

Add statistics for the effective licenses to the evaluated model's license stats

---

.github/workflows/build-and-test.yml

This fixes proper Gradle caching of builds in the Docker container, i.e.
the Gradle wrapper is not downloaded again. This is a fixup for 69bdfd9.

ci(github): Make host users and groups available in the container

---

plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelMapper.kt

This is used in the `deduplicateResolutionsAndExcludes()` docs.

docs(evaluated-model): Fix a KDoc reference to `Excludes`

---

reporter/src/main/kotlin/StatisticsCalculator.kt

Minor refactorings in `StatisticsCalculator`

---

plugins/package-managers/carthage/src/funTest/kotlin/CarthageFunTest.kt

Fixup 9e4d666 to not replace `<REPLACE_GITHUB_ORGANIZATION>` with a constant string (which defeats the purpose of adding that placeholder) and use the actual GitHub organization name instead.

test(carthage): Fix the GitHub organization replacement

---

plugins/reporters/web-app-template/src/models/LicenseStatistics.js
plugins/reporters/web-app-template/src/models/WebAppOrtResult.js

PR contains series of changes to prepare showing effective licenses in the Summary tab of the WebApp report.

WebApp: Preparations to be able to show effective licenses in Summary

---

helper-cli/src/main/kotlin/commands/GenerateTimeoutErrorResolutionsCommand.kt
helper-cli/src/main/kotlin/utils/Extensions.kt
model/src/main/kotlin/OrtResult.kt
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-deduplicate-expected-output.yml
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.json
plugins/reporters/evaluated-model/src/funTest/assets/evaluated-model-reporter-test-expected-output.yml
plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml
plugins/reporters/opossum/src/funTest/assets/reporter-test-input.yml
plugins/reporters/static-html/src/funTest/assets/reporter-test-input.yml
plugins/reporters/static-html/src/funTest/assets/static-html-reporter-test-expected-output.html
plugins/reporters/static-html/src/main/kotlin/ReportTableModel.kt
plugins/reporters/static-html/src/main/kotlin/ReportTableModelMapper.kt
plugins/reporters/static-html/src/main/kotlin/StaticHtmlReporter.kt

This PR simplifies the issues summary view, by showing one table per stage (analyzer, scanner, ...) and (only) one issue per table row. The ability to show advisor issues is added as well in a dedicated table. Finally, issue summaries
do filter issues by excluded affected path WRT. path excludes.
Please see individual commit messages for the details.

static-html: Re-design the issues summary table

---

helper-cli/src/main/kotlin/commands/packageconfig/CreateCommand.kt
scanner/src/main/kotlin/storages/PackageBasedFileStorage.kt

fix(helper-cli): Fix broken reading of scan results by identifier

---

plugins/package-managers/python/src/funTest/assets/projects/synthetic/poetry-expected-output.yml
plugins/package-managers/python/src/funTest/assets/projects/synthetic/poetry-no-dev-group-expected-output.yml
plugins/package-managers/python/src/main/kotlin/utils/PythonInspectorExtensions.kt

See e.g. [1] which has `wget-3.2.zip`.
[1]: https://pypi.org/project/wget/#files

fix(python): Support ZIP archives for source artifacts

---

plugins/reporters/static-html/src/funTest/assets/static-html-reporter-test-expected-output.html
plugins/reporters/static-html/src/main/kotlin/TablesReportModelMapper.kt

static-html: Model mapper clean-ups

---

utils/spdx/src/main/kotlin/SpdxExpression.kt

This is a hotfix for not failing SPDX reports to get generated for ScanCode license expressions like
AGPL-3.0-only WITH LicenseRef-scancode-agpl-generic-additional-terms
A proper future fix could be to introduce a license classification provider interface that can query whether a given string is an exception or not.

fix(spdx): Accept "additional-terms" as part of LicenseRef exceptions

---

.github/workflows/static-analysis.yml

See [1].
[1]: https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#example-workflow-for-sarif-files-generated-outside-of-a-repository

ci(github): Fix permissions to upload SARIF results

---

plugins/package-managers/bundler/src/funTest/assets/projects/synthetic/bundler-expected-output-lockfile.yml
plugins/package-managers/bundler/src/funTest/assets/projects/synthetic/lockfile/Gemfile
plugins/package-managers/bundler/src/main/kotlin/Bundler.kt
plugins/package-managers/bundler/src/main/resources/resolve_dependencies.rb

Make parsing of Bundler dependency output more robust

---

plugins/reporters/fossid/src/main/resources/templates/asciidoc/fossid_snippet.ftl
plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt
plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/main/kotlin/FossIdConfig.kt
plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
plugins/scanners/fossid/src/test/kotlin/FossIdConfigTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdLicenseMappingTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdSnippetChoiceTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdSnippetMappingTest.kt
plugins/scanners/fossid/src/test/kotlin/TestUtils.kt

FossID: Limit fossid snippets

---

plugins/reporters/static-html/src/funTest/assets/static-html-reporter-test-expected-output.html
plugins/reporters/static-html/src/main/kotlin/StaticHtmlReporter.kt
plugins/reporters/static-html/src/main/kotlin/TablesReport.kt
plugins/reporters/static-html/src/main/kotlin/TablesReportModelMapper.kt
plugins/reporters/static-html/src/main/resources/static-html-reporter.css

The _issue summary tables_ have been improved recently by [1], to show exactly one issue per row and to adhere  to the excluded state. This change now improves the issues view in the _project tables_  in several ways which also improves consistency in terms of the issue views with the summary tables.
Please see the individual commits for the details and the screenshots below.
[1] https://github.com/oss-review-toolkit/ort/pull/8593
Part of: #7921.
**Before**
- excluded project:
- included project:
**After**
- excluded project:
- included project:

static-html: Re-design the project table(s)

---

.github/workflows/release.yml
README.md
buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts
buildSrc/src/main/kotlin/ort-base-conventions.gradle.kts

Implement signing of ORT releases

---

analyzer/src/main/kotlin/PackageManagerResult.kt
cli/src/funTest/assets/semver4j-ort-result.yml
model/src/main/kotlin/Project.kt
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-android-cyclic-expected-output-app.yml
plugins/package-managers/gradle/src/funTest/assets/projects/synthetic/gradle-android-cyclic-expected-output-app.yml
plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml
plugins/reporters/opossum/src/funTest/assets/reporter-test-input.yml
plugins/reporters/static-html/src/funTest/assets/reporter-test-input.yml
plugins/reporters/web-app/src/funTest/assets/scan-result-for-synthetic-gradle-lib.yml

Make model serialization more deterministic and re-write several test assets

---

clients/osv/src/main/kotlin/Model.kt

Previously, ORT's OSV model was aligned with schema version 1.6.0 [1], see also [2].
[1]: 868b1a243dfee36afb4d829d33b4755bcd0af579
[2]: https://github.com/ossf/osv-schema/blob/v1.6.3/validation/schema.json

feat(clients/osv): Align model with latest OSV schema version 1.6.3

---

.github/workflows/release.yml

Without these, signing is not configured and the respective tasks are not available. This is a fixup for 37ec96b.

ci(github): Make signing properties available to the distribution

---

.github/workflows/build-and-test.yml

See [1].
[1]: https://github.com/github/codeql-action/pull/2281

ci(github): Use a non-deprecated value to configure CodeQL tools

---

utils/scripting/src/main/kotlin/OrtScriptCompilationConfiguration.kt

This allows to use e.g. `logger.debug { ... }` even from the top level of scripts.

feat(scripting): Make the `logger` available by default

---

plugins/reporters/static-html/src/funTest/assets/static-html-reporter-test-expected-output.html
plugins/reporters/static-html/src/main/kotlin/TablesReportModelMapper.kt

Only show the `Issue.message`, but stop showing `Issue.timestamp` and `Issue.severity`, to make the representation more compact and to align with the WebApp report. Note that the timestamp is rarely relevant and the severity is represented by a dedicated styling anyway.

feat(static-html): Make the descriptions of issues more compact

---

plugins/reporters/fossid/src/main/resources/templates/asciidoc/fossid_snippet.ftl
plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt

Freemarker does not support `null`. Hence, use the empty string instead when there is no snippet limit issue.

fix(reporter): Prevent `null` in snippet report template

---

plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt
plugins/scanners/fossid/src/test/kotlin/FossIdSnippetChoiceTest.kt

The current logic is wrong: the snippet limit is applied to ORT snippet findings. However, a snippet finding refers to a single source code location and contains generally multiple snippets. Hence, those snippets must be counted when applying the limit. Please note that the new logic still garantees that all the snippets of a snippet finding are returned, for unity.
This is a fixup for 9223e90e.

fix(fossid-webapp): Count snippets when enforcing the snippet limit

---

model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt

docs(model): Use the new SCANOSS API endpoint also in `reference.yml`

---

clients/osv/src/main/kotlin/Model.kt
plugins/advisors/osv/src/funTest/kotlin/OsvFunTest.kt
plugins/advisors/osv/src/main/kotlin/Osv.kt

Since the package identifiers in OSV's vulnerability data for the SwiftURL ecosystem have become consistent [1], it is now clear how to construct the requests. Simply add the missing mapping and a test to enable retrieving vulnerabilities for Swift packages.
Fixes #7841.
[1] https://github.com/google/osv.dev/issues/1923#issuecomment-2099711017

feat(osv): Enable querying vulnerabilities for the SwiftURL ecosystem

---

model/src/main/kotlin/AdvisorRecord.kt

The callers do not make any assumption about the ordering, so the sorting is not needed.

chore(model): Drop some unnecessary sorting

---

model/src/main/kotlin/DependencyGraph.kt
model/src/main/kotlin/utils/DependencyGraphBuilder.kt
model/src/main/kotlin/utils/SortedSetConverters.kt
model/src/test/assets/result-with-issues-graph.yml
model/src/test/assets/sbt-multi-project-example-graph.yml
model/src/test/kotlin/DependencyGraphTest.kt
plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-android-cyclic-expected-output-app.yml
plugins/package-managers/gradle/src/funTest/assets/projects/synthetic/gradle-android-cyclic-expected-output-app.yml

Make serialized order independent of insertion order in order to remove the need to update the tests when changing insertion order in upcoming changes.
Part of https://github.com/oss-review-toolkit/ort/issues/6235.

model: Serialize dependency graph edges in some explicit order

---

Dockerfile
scripts/docker_build.sh

Docker build script fixes

---

model/src/main/kotlin/licenses/LicenseClassifications.kt
model/src/test/kotlin/DependencyTreeNavigatorTest.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt

refactor: Remove some unnecessary uses of sorted sets

---

model/src/main/kotlin/utils/DependencyGraphBuilder.kt

Avoid a conversion to a `SortedSet` and the `getValue()` made in each iteration.

refactor(utils): Slightly re-write a function

---

clients/clearly-defined/src/main/kotlin/Enums.kt

Based on the hint at [1] and the code at [2], leverage the serializer's descriptor to get the serial name of the element, without doing any "dummy serialization".
[1]: https://github.com/Kotlin/kotlinx.serialization/issues/1482#issuecomment-841308774
[2]: https://github.com/andregasser/bigbone/pull/332/files#diff-8d64fdf06ceb51ff99e649f64c911cf787b07aff678d5d7efd7bf13322db4983R90

refactor(clearly-defined): Get enum serial names more efficiently

---

clients/clearly-defined/src/main/kotlin/Enums.kt

Look up enums for serial names directly instead of searching for them by string representation.

refactor(clearly-defined): Get enums for serial names directly

---

plugins/package-managers/node/src/main/kotlin/Yarn2.kt
plugins/package-managers/node/src/test/kotlin/Yarn2Test.kt

According to the Yarn 2+ documentation, Corepack is the preferred way to install this package manager. If this method is used, the name of the executable has to be determined differently.
[1]: https://yarnpkg.com/corepack

feat(Yarn): Add basic support for Corepack [1].

---

plugins/advisors/osv/src/main/kotlin/Osv.kt
plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan-expected-output-txt.yml

The actual work-around code involving `it.score.startsWith("CVSS:")` was removed in 0546d45, but the comment was left over, so remove it now.
As a side note, the issue has been fixed with release 1.4.3 of the cvss-calculator library, which is what ORT already uses.

docs(osv): Remove an obsolete code comment

---

website/docs/getting-started/tutorial.md

Without this change, generating the report will fail during the next step as the file generated by the evaluator is expected to be stored directly in [evaluator-output-dir], not a subdirectory thereof.

docs(website): Remove superfluous subdirectory

---

plugins/package-managers/conan/src/main/kotlin/Conan.kt
website/docs/tools/analyzer.md

Conan 2 is not yet supported by ORT. Stating this clearly avoids misunderstandings.

Clarify supported Conan versions

---

integrations/schemas/ort-configuration-schema.json
model/src/main/kotlin/config/ScannerConfiguration.kt
model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
plugins/reporters/evaluated-model/src/funTest/assets/reporter-test-input.yml
plugins/reporters/opossum/src/funTest/assets/reporter-test-input.yml
plugins/reporters/static-html/src/funTest/assets/reporter-test-input.yml
plugins/reporters/web-app/src/funTest/assets/scan-result-for-synthetic-gradle-lib.yml
scanner/src/funTest/assets/scanner-integration-all-pkgs-expected-ort-result.yml
scanner/src/funTest/assets/scanner-integration-subset-pkgs-expected-ort-result.yml

The condition that used that option was removed in c71628d, and there is no plan to reintroduce it as the current provenance-based scanner logic works differently.

chore(model): Remove the unused `createMissingArchives` scanner option

---

downloader/src/main/kotlin/VersionControlSystem.kt
downloader/src/test/kotlin/VersionControlSystemTest.kt
plugins/scanners/fossid/src/main/kotlin/FossId.kt

All current (non-test) implementations return a non-null name already as they fall back to a hard-coded name eventually.

refactor(downloader)!: Make `getDefaultBranchName()` non-nullable

---

plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/main/kotlin/FossIdNamingProvider.kt
plugins/scanners/fossid/src/test/kotlin/FossIdNamingProviderTest.kt

Adds branch name (revision) to FossID scan code for easier identification of scanned source code.
As FossID accepts maximum of 255 characters in scan code, branch name is trimmed to size, that is compliant with this constraint.

feat(scanner): Add branch name to FossID scan code

---

downloader/build.gradle.kts
downloader/src/main/kotlin/WorkingTreeCache.kt
plugins/commands/scanner/build.gradle.kts
plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt
scanner/src/funTest/kotlin/provenance/DefaultNestedProvenanceResolverFunTest.kt
scanner/src/funTest/kotlin/provenance/DefaultPackageProvenanceResolverFunTest.kt
scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
scanner/src/main/kotlin/provenance/NestedProvenanceResolver.kt
scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
scanner/src/main/kotlin/provenance/ProvenanceDownloader.kt

Using this makes sense outside of the scanner context, like for downloading configuration repositories.

refactor!: Move the `WorkingTreeCache` from the scanner to the downloader

---

model/src/main/kotlin/PackageCurationData.kt
model/src/test/kotlin/PackageCurationDataTest.kt

Previously, `PackageCuration.apply()` silently ignored declared license mapping entries with invalid SPDX expressions. For example, if one accidentally omits the `LicenseRef-` prefix, the mapping is just silently ignored.
Add a check that all values in the `Map` are valid SPDX expression into the constructor, to fail as early as possible. When used via a `FilePackageCurationProvider`, ORT now fails with the error message pointing to the problematic curation file path.
Fixes: #7828.

feat(model)!: Stop silently ignoring invalid declared license mappings

---

plugins/package-managers/bundler/src/main/kotlin/Bundler.kt

When fetching version data for individual Ruby gems, we don't want to rely on creation order of the gems on RubyGems.org. Instead, we use the standard `ruby` platform as a sensible default (as we do elsewhere).
Partially addresses https://github.com/oss-review-toolkit/ort/issues/8695.

Enforce "ruby" platform when fetching version data

---

build.gradle.kts

This gets rid of the
The deprecated "gradleEnterprise.buildScan.termsOfServiceUrl" API has
been replaced by "develocity.buildScan.termsOfUseUrl"
deprecation warning when running a Gradle build scan.

build(Gradle): Use the new way to opt-in to build scan terms

---

utils/test/src/main/resources/kotest.properties

This should reduce test startup times yet more, see [1].
[1]: https://kantis.github.io/posts/Faster-Kotest-startup/

test: Disable scanning for Kotest project config in third-party JARs

---

plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
plugins/package-managers/gradle/src/main/kotlin/Gradle.kt

Not everything that Gradle outputs to `stderr` is a warning in the sense that results are wrong or something needs to be done. Avoid some potential confusion by only logging `stderr` output at `debug` level, which aligns with logging of `stdout` output.

chore(package-managers): Do not log all Gradle `stderr` output as warnings

---

clients/dos/build.gradle.kts
clients/dos/src/main/kotlin/AuthorizationInterceptor.kt
clients/dos/src/main/kotlin/DosClient.kt
clients/dos/src/main/kotlin/DosModel.kt
clients/dos/src/main/kotlin/DosService.kt
gradle/libs.versions.toml
plugins/package-configuration-providers/dos/README.md
plugins/package-configuration-providers/dos/build.gradle.kts
plugins/package-configuration-providers/dos/src/main/kotlin/DosPackageConfigurationProvider.kt
plugins/package-configuration-providers/dos/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.packageconfigurationproviders.api.PackageConfigurationProviderFactory
settings.gradle.kts

The DOS scanner wrapper will be contributed as a follow-up.

Add the Double Open Server (DOS) client and package configuration provider

---

.github/workflows/release.yml

See [1].
[1]: https://github.blog/changelog/2024-06-25-artifact-attestations-is-generally-available/

feat(github): Attest build provenance for releases

---

plugins/package-managers/node/src/main/kotlin/Pnpm.kt

Pnpm has been upgrade to version 9.x without updating the version requirement, see [1].
[1] afdd4fa09b5cd7da7606b6b6980000457391dd65

fix(analyzer): Re-align the version requirement for pnpm

---

.github/workflows/build-and-test.yml

This should improve the overview about which test(s) failed. See [1].
[1]: https://github.com/test-summary/action

ci(github): Create test summaries for workflow jobs

---

plugins/package-configuration-providers/dos/README.md
plugins/scanners/dos/README.md
plugins/scanners/dos/build.gradle.kts
plugins/scanners/dos/src/main/kotlin/DosScanner.kt
plugins/scanners/dos/src/main/kotlin/DosScannerConfig.kt
plugins/scanners/dos/src/main/kotlin/DosScannerResultParser.kt
plugins/scanners/dos/src/main/resources/META-INF/services/org.ossreviewtoolkit.scanner.ScannerWrapperFactory
plugins/scanners/dos/src/test/kotlin/DosScannerTest.kt
plugins/scanners/dos/src/test/resources/no-results.json
plugins/scanners/dos/src/test/resources/pending.json
plugins/scanners/dos/src/test/resources/ready.json

Add the DOS scanner wrapper

---

.github/workflows/release.yml

Work-around [1] and only attest the main artifacts, not the signature files.
[1]: https://github.com/actions/attest-build-provenance/issues/133

fix(github): Be explicit about artifact paths to attest for

---

clients/bazel-module-registry/src/main/kotlin/LocalBazelModuleRegistryService.kt

Bazel modules are always in a 'modules' directory alongside the `bazel_registry.json` file. See [1].
The latter is still parsed and will be used in a future commit to handle modules with type 'local_path'.
This is a fixup for 59681807ea5c4ab9f468e783f2bdb7fa1de5dd30.
[1]: https://bazel.build/external/registry#index_registry

fix(Bazel): Fix local registry modules path

---

plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel/.bazelrc
plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
plugins/package-managers/bazel/src/test/kotlin/BazelTest.kt

 fix(bazel): Always disable the disk cache 

---

gradle/libs.versions.toml
model/build.gradle.kts
model/src/main/kotlin/FileFormat.kt
model/src/main/kotlin/Mappers.kt
plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt
plugins/version-control-systems/git/build.gradle.kts
plugins/version-control-systems/git/src/main/kotlin/GitRepo.kt

Migrate git-repo manifest parsing from Jackson to KxS

---

plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt

For large documents this can result in an out of memory error, such as [1].
Fixes: #8829.
[1]: `UTF16 String size is [..], should be less than 1073741823`

fix(spdx): Avoid serializing the document into a string

---

plugins/package-managers/bazel/src/main/kotlin/Bazel.kt

fix(bazel): Always disable the wrapper script

---

.github/workflows/release.yml

Work around another restriction of the build attestation action, see [1].
[1]: https://github.com/actions/attest-build-provenance/issues/146

fix(github): Do not use variables as part of attestation subject paths

---

utils/spdx/src/main/kotlin/Extensions.kt
utils/spdx/src/main/kotlin/SpdxExpression.kt
utils/spdx/src/main/kotlin/SpdxOperator.kt

Improve overview a bit my splitting the large `Extensions.kt` and grouping operator code.

refactor(spdx-utils): Move operator-relared code to a separate file

---

.github/workflows/release.yml

fix(github): Use correct syntax for environment variable expansion

---

.github/workflows/scorecard-analysis.yml
.github/workflows/static-analysis.yml

The Scorecard action does not work properly with workflows that define global environment variables [1], so move the job to its own workflow.
[1]: https://github.com/ossf/scorecard-action#workflow-restrictions

ci(github): Move Scorecard analysis to a separate workflow

---

renovate.json

This should silence OpenSSF Scorecard's warnings about a "GitHubAction not pinned by hash".

ci(renovate): Automatically pin GitHub action digests

---

plugins/package-managers/pub/src/main/kotlin/Pub.kt

Use "analyze" instead of "scan" to avoid confusion with ORT's scanner.

chore(pub): Improve function names

---

plugins/package-managers/sbt/src/main/kotlin/Sbt.kt

`sbt projects` was outputting extra lines, which ORT confused as projects
```
[info] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[info] 	* net.java.dev.jna:jna:5.6.0 is selected over {4.5.0, 4.5.0}
[info] 	    +- io.methvin:directory-watcher:0.10.1                (depends on 5.6.0)
[info] 	    +- org.scala-sbt:io_2.12:1.2.2                        (depends on 4.5.0)
[info] 	    +- net.java.dev.jna:jna-platform:4.5.0                (depends on 4.5.0)
```
Project names cannot contain spaces, so using `\S+` (One or more Non-whitespace characters) fixed the issue.

fix(sbt): Filter out garbage from sbt projects command

---

plugins/package-managers/cocoapods/build.gradle.kts
plugins/package-managers/cocoapods/src/main/kotlin/CocoaPods.kt
plugins/package-managers/cocoapods/src/main/kotlin/Podspec.kt

Separate the CocoaPods model from the analyzer.

refactor(cocoapods): Move Podspec to a dedicated file

---

plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt

CycloneDX fixes

---

plugins/package-managers/gradle-plugin/src/main/kotlin/GradleModelExtensions.kt

See [1] for how Kotlin itself ignores the resolution of `dependencySources` configurations. Also, Kotlin 2.0.20 will fix the issue by using detachable vari9ants instead [2].
Fixes #8755.
[1]: https://github.com/JetBrains/kotlin/commit/73b290a94831a1aee547c99ab319fafc311864d7#diff-13384ab95f3c49314bc7e8d26b20c8981d5c514272bbd8c20130b9761be57fb6R724-R729
[2]: https://github.com/JetBrains/kotlin/commit/659a6fbea22557c59f097acc94ec7f99f95e0bf6

fix(gradle): Ignore `dependencySources` configurations during resolution

---

plugins/package-managers/cocoapods/src/main/kotlin/CocoaPods.kt

The code suggests that it works for any amount of scopes, while it may produce duplicates in case `scopes` contains more than one element. Avoid any duplicates by mapping the IDs into a set.

chore(cocoapods): Generalize mapping IDs to packages

---

.github/workflows/static-analysis.yml
buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts

Ensure that Detekt tasks with type resolution do not run in parallel with the default "detekt" task to avoid problems as mentioned in 3c20400.

build(gradle): Add a "detektAll" convenience task

---

downloader/src/main/kotlin/VcsHost.kt
downloader/src/test/kotlin/VcsHostTest.kt

I noticed that generic handling of VCS hosts fails sometimes. For example `VcsHost.getProject("ssh://git@internal.gitlab.custom.com/group/project.git")` returns `git@internal` because domain contains `.gitlab`.
I changed regex search to consider only the `.git` at the end.

 fix(downloader): Support Git URLs with ".git" in domain

---

analyzer/src/main/kotlin/managers/utils/PackageManagerDependencyHandler.kt
plugins/package-managers/spdx/src/funTest/assets/projects/synthetic/illegal-chars-external-refs/illegal_chars/package.spdx.yml
plugins/package-managers/spdx/src/funTest/assets/projects/synthetic/illegal-chars-external-refs/project-xyz.spdx.yml
plugins/package-managers/spdx/src/funTest/assets/projects/synthetic/subproject-conan/project-xyz.spdx.yml
plugins/package-managers/spdx/src/funTest/kotlin/SpdxDocumentFileFunTest.kt
plugins/package-managers/spdx/src/main/kotlin/SpdxDocumentFile.kt
plugins/package-managers/spdx/src/main/kotlin/utils/SpdxResolvedDocument.kt

SpdxDocumentFile: Report issues from subprojects that cannot be mapped to a package ID.

---

buildSrc/src/main/kotlin/ort-base-conventions.gradle.kts

This eliminates a source of failure when eventually migration to the Jira REST API client version 6.

build(gradle): Prepare for eventually using `atlassian.io` artifacts

---

plugins/package-managers/conan/src/main/kotlin/Conan.kt
plugins/package-managers/conan/src/main/kotlin/PackageInfo.kt

Some preparations for porting to KxS plus some code improvements.

Conan improvements

---

plugins/package-managers/bower/build.gradle.kts
plugins/package-managers/bower/src/main/kotlin/Bower.kt
plugins/package-managers/bower/src/main/kotlin/Model.kt

Prepare for migrating to KxS.
Note: Some clean-up including renaming the term 'node' in variable and functions will be done in a following PR.

refactor(bower): Use data classes for deserializing the package list

---

plugins/package-managers/bower/src/main/kotlin/Bower.kt

Bower follow-ups

---

model/src/funTest/kotlin/utils/PostgresProvenanceFileStorageFunTest.kt
model/src/main/kotlin/Hash.kt
model/src/main/kotlin/utils/PurlExtensions.kt
model/src/test/kotlin/HashTest.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
model/src/test/kotlin/utils/PurlExtensionsTest.kt
plugins/package-managers/conan/src/main/kotlin/Conan.kt
plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
plugins/package-managers/maven/src/main/kotlin/utils/MavenSupport.kt
plugins/package-managers/maven/src/test/kotlin/utils/MavenSupportTest.kt
plugins/package-managers/pub/src/funTest/kotlin/PubFunTest.kt
plugins/package-managers/pub/src/main/kotlin/Pub.kt
plugins/package-managers/spdx/src/main/kotlin/utils/SpdxResolvedDocument.kt
reporter/src/testFixtures/kotlin/TestData.kt
utils/test/src/main/kotlin/Utils.kt

Further small Conan improvements

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature.md
README.md

Distinguish more clearly between code and non-code contributions and not only point out the community's Slack workspace, but all channels linked from the issue workflow.

docs(README): Reword the contribution section

---

README.md

This is the counterpart to https://github.com/oss-review-toolkit/.github/pull/4.

docs(README): Add a sentence aboout the governance model

---

README.md

This is a nice visualization of contribution statistics, enriching the
`README.md`'s "Contributing" section.

docs(README): Add a Repobeats contribution statistics image

---

clients/bazel-module-registry/src/main/kotlin/LocalBazelModuleRegistryService.kt
clients/bazel-module-registry/src/main/kotlin/RemoteBazelModuleRegistryService.kt
plugins/package-managers/bazel/build.gradle.kts
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output-local-registry.yml
plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
plugins/package-managers/bazel/src/main/kotlin/BazelModel.kt
plugins/package-managers/bazel/src/main/kotlin/CompositeBazelModuleRegistryService.kt
plugins/package-managers/bazel/src/main/kotlin/MultiBazelModuleRegistryService.kt
plugins/package-managers/bazel/src/test/kotlin/MultiBazelModuleRegistryServiceTest.kt

This PR adds support for multiple registry services defined in the `.bazelrc` file.
Taking over from @nnobelis during his vacation.

Bazel multi registries

---

plugins/package-managers/composer/build.gradle.kts
plugins/package-managers/composer/src/main/kotlin/Composer.kt
plugins/package-managers/composer/src/main/kotlin/Model.kt

This prepares for porting from Jackson to KxS.

Composer: Use data classes for deserialization and simplify a bit on top

---

downloader/src/main/kotlin/VersionControlSystem.kt
plugins/version-control-systems/git/src/funTest/kotlin/GitDownloadFunTest.kt
plugins/version-control-systems/git/src/main/kotlin/Git.kt
plugins/version-control-systems/mercurial/src/funTest/kotlin/MercurialDownloadFunTest.kt
plugins/version-control-systems/mercurial/src/main/kotlin/Mercurial.kt
plugins/version-control-systems/subversion/src/funTest/kotlin/SubversionDownloadFunTest.kt
scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt

The `WorkingTree`'s `workingDir` does not necessarily match the repository root in all cases. Explicitly use `getRootPath()` instead where it matters.

fix(downloader): Correctly get the repository root path

---

.github/workflows/build-and-test.yml

The latest tooling catches up more quickly with new Kotlin versions.

ci(github): Use latest instead of linked CodeQL tooling

---

plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan-expected-output-py.yml
plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan-py/conanfile.py
plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan-py/conanfile.py.license
plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan-py/lockfile.lock
plugins/package-managers/conan/src/main/kotlin/Conan.kt

This change is a (not strictly needed) preparation for Conan 2.x support in ORT.
Updating the Poco recipe to the current version offered by the Conan Center Index allows it to work with both, version 1.x and 2.x of Conan.
The lock file has been created using Conan version 1.64.1:
```shell
rm -rf ~/.conan/data
conan lock create --lockfile-out lockfile.lock conanfile.py
```
Conan Center Index: https://github.com/conan-io/conan-center-index
Commit: f78dc3729f97c1554eae5f3843cabb2e2198c09a

chore(conan): Update test fixture

---

plugins/package-managers/bower/src/main/kotlin/Model.kt
plugins/package-managers/cocoapods/src/main/kotlin/Podspec.kt
plugins/package-managers/composer/build.gradle.kts
plugins/package-managers/composer/src/main/kotlin/Composer.kt
plugins/package-managers/composer/src/main/kotlin/Model.kt
plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModel.kt

Various Composer improvements

---

plugins/reporters/aosd/build.gradle.kts
plugins/reporters/aosd/src/funTest/assets/aosd.NPM-%40ort-project-with-findings-1.0.json
plugins/reporters/aosd/src/funTest/assets/aosd.NPM-%40ort-project-without-findings-1.0.json
plugins/reporters/aosd/src/funTest/assets/aosd.example.json
plugins/reporters/aosd/src/funTest/assets/aosd.schema.json
plugins/reporters/aosd/src/funTest/kotlin/AudiOpenSourceDiagnosticsReporterFunTest.kt
plugins/reporters/aosd/src/main/kotlin/AudiOpenSourceDiagnosticsReporter.kt
plugins/reporters/aosd/src/main/kotlin/Model.kt
plugins/reporters/aosd/src/main/resources/META-INF/services/org.ossreviewtoolkit.reporter.Reporter
plugins/reporters/ctrlx/src/main/kotlin/CtrlXAutomationModel.kt
plugins/reporters/ctrlx/src/main/kotlin/CtrlXAutomationReporter.kt
website/docs/tools/reporter.md

Add a reporter for the AOSD 2 format

---

plugins/scanners/scanoss/build.gradle.kts

This works around [1].
[1]: https://github.com/scanoss/scanoss.java/issues/12

fix(scanoss): Ignore the logging provider from `scanoss'

---

evaluator/src/test/kotlin/osadl/CompatibilityMatrixTest.kt

There also are some OSADL-based tests in `EvaluatorTest`, but better have some explicit test here as well.

test(evaluator): Add two concrete OSADL compatibility matrix tests

---

plugins/package-managers/composer/src/funTest/kotlin/ComposerFunTest.kt
plugins/package-managers/composer/src/main/kotlin/Composer.kt

In addition to 471a65d, also ignore any `composer.json` files from `vendor` directories before resolving dependencies. This avoids packages for dependencies being recognized as projects by the ORT analyzer.

fix(compose): Ignore definition files from vendor directories

---

clients/bazel-module-registry/src/main/kotlin/LocalBazelModuleRegistryService.kt
clients/bazel-module-registry/src/main/kotlin/RemoteBazelModuleRegistryService.kt
plugins/package-managers/bazel/src/main/kotlin/BazelModel.kt
plugins/package-managers/bazel/src/main/kotlin/CompositeBazelModuleRegistryService.kt
plugins/package-managers/bazel/src/main/kotlin/MultiBazelModuleRegistryService.kt
plugins/package-managers/bazel/src/test/kotlin/MultiBazelModuleRegistryServiceTest.kt

Bazel API improvements

---

gradle/libs.versions.toml
plugins/commands/downloader/build.gradle.kts
plugins/commands/downloader/src/main/kotlin/DownloaderCommand.kt

Display progress info for parallel downloads in the CLI

---

plugins/package-managers/conan/src/main/kotlin/Conan.kt

In some cases Conan falls back to an interactive terminal, e.g. when requiring credentials for a remote.
Avoid blocking the ORT process by disabling interactive mode for the Conan CLI and fail instead [1].
[1]: https://docs.conan.io/1/reference/env_vars.html#conan-non-interactive

fix(conan): Ensure that Conan is running in non-interactive mode

---

plugins/reporters/web-app-template/build.gradle.kts

The `+` operator has an overload for pairs as well.

chore(web-app-template): Simplify adding to a map

---

downloader/src/main/kotlin/VersionControlSystem.kt
model/src/main/kotlin/VcsType.kt

The alias names of a VCS should be an implementation detail.

refactor(vcs)!: Make the `aliases` property private

---

.github/workflows/static-analysis.yml
integrations/completions/ort-completion.bash
integrations/completions/ort-completion.fish
integrations/completions/ort-completion.zsh

Add a job that verifies that the generated shell completion scripts are up-to-date and fails otherwise. This ensures that the scripts are always updated when the signature of the CLI commands is changed.

ci: Ensure that the generate shell completion scripts are up-to-date

---

clients/bazel-module-registry/src/main/kotlin/RemoteBazelModuleRegistryService.kt
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-archive-override/MODULE.bazel
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output-archive-override.yml
plugins/package-managers/bazel/src/main/kotlin/Bazel.kt

Bazel improvements

---

README.md

The service behind the badge has been broken for a while now, showing "NetworkError when attempting to fetch resource".

docs(README): Remove the broken TODO badge

---

plugins/advisors/nexus-iq/src/main/kotlin/NexusIq.kt
plugins/advisors/nexus-iq/src/main/kotlin/NexusIqConfiguration.kt
plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt
plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCodeConfiguration.kt

Fix some advisor plugin options to be secrets. This is a fixup for 848e666.

fix(advisors): Make configuration properties secrets

---

plugins/package-managers/pub/build.gradle.kts
plugins/package-managers/pub/src/main/kotlin/Lockfile.kt
plugins/package-managers/pub/src/main/kotlin/Pub.kt
plugins/package-managers/pub/src/main/kotlin/utils/PubCacheReader.kt
plugins/package-managers/pub/src/test/kotlin/utils/PubCacheReaderTest.kt

Simplify migrating to KxS later on. See individual commits.

Pub: Improve the code for the lockfile parsing

---

.github/workflows/docker-build.yml
Dockerfile
NOTICE
scripts/docker_snippets/android.snippet
scripts/docker_snippets/dart.snippet
scripts/docker_snippets/dotnet.snippet
scripts/docker_snippets/haskell.snippet
scripts/docker_snippets/php.snippet
scripts/docker_snippets/sbt.snippet
scripts/docker_snippets/swift.snippet

Docker now provides the way to generate embedded SBOM file through Docker Scout, and the engine underlying the process is same Syft previously used.

feat(docker): Replace Syft for Docker own Scout SBOM generator

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
gradle/libs.versions.toml

As of version 2 this needs to be applied to the individual projects instead of the root project. This makes the `projectHealth` task available again.

build(gradle): Fix applying the dependency analysis plugin

---

plugins/advisors/oss-index/src/test/kotlin/OssIndexTest.kt
plugins/advisors/vulnerable-code/src/test/kotlin/VulnerableCodeTest.kt
plugins/compiler/src/main/kotlin/PluginFactoryGenerator.kt
plugins/package-curation-providers/clearly-defined/src/funTest/kotlin/ClearlyDefinedPackageCurationProviderFunTest.kt
plugins/package-curation-providers/clearly-defined/src/test/kotlin/ClearlyDefinedPackageCurationProviderTest.kt
plugins/package-curation-providers/file/src/main/kotlin/FilePackageCurationProvider.kt

Add the plugin descriptors to the companion objects of the generated plugin factories. See the commit messages for details.

Add the descriptor to the plugin factory companion object

---

helper-cli/src/main/kotlin/utils/Extensions.kt
model/src/main/kotlin/OrtResult.kt
plugins/commands/evaluator/src/main/kotlin/EvaluatorCommand.kt
plugins/commands/reporter/src/main/kotlin/ReporterCommand.kt
plugins/package-configuration-providers/api/build.gradle.kts
plugins/package-configuration-providers/api/src/main/kotlin/CompositePackageConfigurationProvider.kt
plugins/package-configuration-providers/api/src/main/kotlin/PackageConfigurationProvider.kt
plugins/package-configuration-providers/api/src/main/kotlin/PackageConfigurationProviderFactory.kt
plugins/package-configuration-providers/api/src/main/kotlin/SimplePackageConfigurationProvider.kt
plugins/package-configuration-providers/api/src/test/kotlin/SimplePackageConfigurationProviderTest.kt
plugins/package-configuration-providers/dir/build.gradle.kts
plugins/package-configuration-providers/dir/src/main/kotlin/DirPackageConfigurationProvider.kt
plugins/package-configuration-providers/dir/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.packageconfigurationproviders.api.PackageConfigurationProviderFactory
plugins/package-configuration-providers/dos/build.gradle.kts
plugins/package-configuration-providers/dos/src/main/kotlin/DosPackageConfigurationProvider.kt
plugins/package-configuration-providers/dos/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.packageconfigurationproviders.api.PackageConfigurationProviderFactory
plugins/package-configuration-providers/ort-config/build.gradle.kts
plugins/package-configuration-providers/ort-config/src/main/kotlin/OrtConfigPackageConfigurationProvider.kt
plugins/package-configuration-providers/ort-config/src/main/resources/META-INF/services/org.ossreviewtoolkit.plugins.packageconfigurationproviders.api.PackageConfigurationProviderFactory
utils/config/build.gradle.kts
utils/config/src/main/kotlin/ConfigurationResolver.kt
utils/config/src/main/kotlin/OrtResultExtensions.kt

Migrate the package configuration provider API to the new plugin API. See the commit messages for details.

Migrate package configuration providers to new plugin API

---

model/src/main/kotlin/utils/FileArchiver.kt
scanner/src/main/kotlin/utils/FileListResolver.kt
utils/ort/src/funTest/kotlin/storage/LocalFileStorageFunTest.kt
utils/ort/src/funTest/kotlin/storage/XZCompressedLocalFileStorageFunTest.kt
utils/ort/src/main/kotlin/storage/LocalFileStorage.kt
utils/ort/src/main/kotlin/storage/XZCompressedLocalFileStorage.kt

Check if an archive exists in the storage before trying to read it in `FileArchiver.unarchive` and `FileListResolver.resolve`.
This prevents an error message when calling `storage.getData()` and the data does not exist.
Resolves #7041.
Also fix a bug in `XZCompressedFileStorage` which was discovered by the change.

feat(model): Check if an archive exists before trying to download it

---

detekt-rules/src/main/kotlin/OrtImportOrder.kt

Do not call `removeLast()` on an empty list.

build(detekt-rules): Fix the import check for a single dotless import

---

plugins/package-managers/gradle-inspector/src/funTest/assets/projects/synthetic/gradle-expected-output-lib-without-repo.yml
plugins/package-managers/gradle-inspector/src/main/kotlin/GradleDependencyHandler.kt
plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
plugins/package-managers/gradle-model/src/main/kotlin/Extensions.kt
plugins/package-managers/gradle/src/main/kotlin/GradleDependencyHandler.kt
plugins/package-managers/gradle/src/test/kotlin/GradleDependencyHandlerTest.kt

 Migrate the GradleInspector to use the dependency graph 

---

plugins/package-managers/pub/build.gradle.kts
plugins/package-managers/pub/src/main/kotlin/Pub.kt
plugins/package-managers/pub/src/main/kotlin/Pubspec.kt
plugins/package-managers/pub/src/test/kotlin/PubspecTest.kt

Refactor Pub's pubspec parsing to use a data class and KxS / kaml

---

plugins/package-managers/nuget/src/funTest/kotlin/NuGetFunTest.kt
plugins/package-managers/pub/src/funTest/assets/projects/external/dart-http-expected-output.yml

The test currently fails with a 401 (Unauthorized) error when trying to access [1]. Disable it until the root cause is found.
[1]: https://pkgs.dev.azure.com/ms/terminal/_packaging/TerminalDependencies/nuget/v3/index.json

test(nuget): Disable `NuGetFunTest`

---

.github/ISSUE_TEMPLATE/bug.md

Otherwise all bug reports contain the full list of plugins which makes searching e.g. for a specific package manager hard.

docs(issues): Limit `ort requirements` output to commands

---

plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt

docs(gradle-inspector): Mention `javaHome` as part of class docs

---

analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/AnalyzerResultBuilder.kt
analyzer/src/main/kotlin/PackageManager.kt
buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
clients/fossid-webapp/src/test/kotlin/FossId2021dot2Test.kt
clients/fossid-webapp/src/test/kotlin/FossId2023dot1Test.kt
downloader/src/main/kotlin/Downloader.kt
model/src/main/kotlin/DependencyGraph.kt
model/src/main/kotlin/Package.kt
model/src/main/kotlin/PackageReference.kt
plugins/package-managers/composer/src/main/kotlin/Composer.kt
plugins/package-managers/node/src/main/kotlin/Npm.kt
plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModelMapper.kt
utils/common/src/main/kotlin/DirectoryStash.kt
utils/ort/src/main/kotlin/Utils.kt
utils/ort/src/test/kotlin/OrtProxySelectorTest.kt

Passive voice in code comments

---

plugins/package-managers/node/build.gradle.kts
plugins/package-managers/node/src/main/kotlin/PackageJson.kt
plugins/package-managers/node/src/main/kotlin/Yarn.kt
plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt

node: Port all remaining Jackson-based code to KxS

---

plugins/package-configuration-providers/dos/src/main/kotlin/DosPackageConfigurationProvider.kt

Make the `token` configuration option of
`DosPackageConfigurationProvider` a secret. This is a fixup for 4f870c2.

fix(dos): Make the `token` a secret config option

---

Dockerfile
examples/license-classifications.yml
plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt
plugins/package-managers/python/src/main/kotlin/utils/PythonInspectorExtensions.kt
plugins/scanners/dos/README.md
plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModelMapper.kt
utils/spdx/src/main/kotlin/Utils.kt
website/docs/configuration/license-texts.md
website/docs/getting-started/tutorial.md
website/docs/tools/advisor.md
website/docs/tools/scanner.md

Update link references of ownership from `nexB` to `aboutcode-org`

docs: Update link references of ownership

---

renovate.json

Avoid bogus updates of NuGet test projects which should be prevented by ignoring "**/src/funTest/assets/**" already, but that stopped to work.

ci(renovate): Disable NuGet package manager updates

---

utils/spdx/src/main/kotlin/model/SpdxExternalReference.kt
utils/spdx/src/test/kotlin/model/SpdxExternalReferenceTest.kt

This revives the change from [1] for compatibility when reading SPDX files.
[1]: https://github.com/oss-review-toolkit/ort/pull/7839/files#diff-d290822c4f4714ad4b5d29e52d75edfa3c70e3e80e258d69adf0f6a82d8ae9a4

fix(spdx-utils): Support dashed reference category names

---

qodana.yml

This is to check whether the issue at [1] is resolved.
[1]: https://youtrack.jetbrains.com/issue/QD-9917

ci(github): Do not configure a custom linter version anymore

---

Dockerfile

See [1].
[1]: https://codeberg.org/devthefuture/dockerfile-x/src/branch/master/CHANGELOG.md#1-4-2-https-codeberg-org-devthefuture-dockerfile-x-compare-v1-4-1-v1-4-2-2024-08-05

deps(docker): Upgrade the `INCLUDE`-syntax extension

---

scanner/src/main/kotlin/provenance/ProvenanceDownloader.kt

If the `targetDir` is not directly below the `root`, any intermediate directory needs to be created before directories can be moved to it.

fix(scanner): Create intermediate nested provenance directories

---

.github/workflows/release.yml

This is to check whether the feature provides insights on ORT dependents [1].
[1]: https://github.com/oss-review-toolkit/ort/network/dependents

ci(github): Submit the Gradle dependency graph for releases

---

plugins/package-managers/bazel/src/main/kotlin/Bazel.kt

Some projects can explicitly disable the lock file generation by putting 'common --lockfile_mode=off' in their '.bazelrc'. In such projects, running 'bazel mod graph' does not generate a lock file anymore if it is missing. Since ORT requires a lock file to be present, this commit adds a flag to force the (re)generation of the lock file. See [1].
[1]: https://bazel.build/versions/7.1.0/external/lockfile
This fixes the following error:
```
level=INFO  o.o.utils.common.ProcessCapture - Running 'bazel mod graph --output json --disk_cache=' in '/tmp/ort-AnalyzerDownloader-analyzer-worker9834012411938558324'... 
level=ERROR o.o.analyzer.PackageManager - Bazel failed to resolve dependencies for path 'MODULE.bazel': FileNotFoundException: …
```

fix(bazel): Force the generation of a `MODULE.bazel.lock` file

---

plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
plugins/scanners/scancode/src/test/kotlin/ScanCodeTest.kt
scanner/src/main/kotlin/Scanner.kt

ScanCode error handling improvements

---

plugins/package-managers/node/src/main/kotlin/utils/NpmSupport.kt
plugins/package-managers/node/src/test/kotlin/utils/NpmSupportTest.kt

chore(node): Remove the unused `parseNpmLicenses()` function

---

helper-cli/src/main/kotlin/commands/ListPackagesCommand.kt

`orthw` (bash) organizes the OrtResult files and repository configuration separately. So, before running any command on the `OrtResult` the repository configuration needs to be overridden. Extend the `ListPackageCommand` by a dedicated option, analog to other commands such as `ListLicensesCommand`.

feat(helper-cli): Add an option to override the repository configuration

---

website/docs/configuration/ort-yml.md

The previous titles could confuse readers to think that the files would have to be called, for example, `bower.ort.yml`, so only use the package manger names for the titles.

docs(ort.yml): Improve code block titles for examples

---

.github/workflows/release.yml

Apply the work-around from [1] to associate the dependency graph built from tags to the `main` branch.
[1]: https://github.com/gradle/actions/issues/242#issuecomment-2204385972

ci(github): Associate the dependency graph to the `main` branch

---

plugins/package-managers/gradle-inspector/src/main/kotlin/GradleDependencyHandler.kt
utils/ort/src/main/kotlin/OkHttpClientHelper.kt

Support file URLs in downloads 

---

.github/workflows/static-analysis.yml

After upgrading to Ubuntu 24.04 in 90c8fb0 we do not need to setup a specific Python version anymore, but with the pre-installed Python we need to use `pipx` instead of `pip` to install the package.

ci: Simplify the reuse check

---

model/src/main/kotlin/VcsType.kt

See [1] for context and [2] for the package violating the spec [3].
[1]: https://github.com/eclipse-apoapsis/ort-server/issues/1137
[2]: https://github.com/js-sdsl/js-sdsl/blob/07d24014a3cb69adffa717ee1170824ac5b841c3/package.json#L124
[3]: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository

feat(model): Add Git-only VCS host names as Git aliases

---

model/src/main/kotlin/Identifier.kt

It does not make sense to limit the `type` to a package if the next sentence explains that it can be used for a project as well.

docs(model): Clarify an `Identifier`'s project vs. package use

---

plugins/package-managers/pub/src/main/kotlin/Pub.kt

Do not just pick the first Gradle package manager but throw if there are
multiple ones, similar to [1].
[1]: https://github.com/oss-review-toolkit/ort/blob/6d576c3d365e63535b15177bd9a41d5e4b7a51e9/model/src/main/kotlin/DependencyGraphNavigator.kt#L52-L55

chore(pub): Align the Gradle check with `DependencyGraphNavigator`

---

scanner/src/main/kotlin/Scanner.kt

chore(scanner): Remove an unused label

---

utils/ort/src/main/kotlin/DeclaredLicenseProcessor.kt

Only allowing SPDX exceptions is too much of a limitation.
Fixes #9111.

fix: Tolerate `LicenseRef-*` exceptions in declared license mappings

---

plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/workspaces-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/workspaces-expected-output.yml
plugins/package-managers/node/src/funTest/kotlin/YarnFunTest.kt
plugins/package-managers/node/src/main/kotlin/Npm.kt
plugins/package-managers/node/src/main/kotlin/Pnpm.kt
plugins/package-managers/node/src/main/kotlin/utils/NpmDependencyHandler.kt
plugins/package-managers/node/src/test/kotlin/utils/NpmDependencyHandlerTest.kt

Fixes https://github.com/oss-review-toolkit/ort/issues/9196, fixes https://github.com/oss-review-toolkit/ort/issues/8940.
**Important**: Previously, submodules were represented as packages which were not referenced by any project scope. 
As consequence, this could lead to incorrect handling of all their transitive dependencies by the policy rules.

node: Represent workspace submodules as Projects

---

plugins/package-managers/gradle/src/funTest/kotlin/GradleAndroidFunTest.kt
plugins/package-managers/gradle/src/funTest/kotlin/GradleBomFunTest.kt
plugins/package-managers/gradle/src/funTest/kotlin/GradleCompositeFunTest.kt
plugins/package-managers/gradle/src/funTest/kotlin/GradleFunTest.kt
plugins/package-managers/gradle/src/funTest/kotlin/GradleKotlinScriptFunTest.kt
plugins/package-managers/gradle/src/funTest/kotlin/GradleLibraryFunTest.kt

This is a fixup for e34734a to also handle "legacy" Gradle tests. It is unclear why this was not required earlier by CI: Probably due to some caching, which got invalidated with CI's upgrade to Ubuntu 24.04.

test: Ensure to use a compatible Java version for Gradle projects

---

gradle/libs.versions.toml

build(gradle): Remove unused Ktor version catalog entries

---

plugins/package-managers/gradle/src/main/resources/init.gradle

Starting with Gradle 8.2, a property that defines if a Gradle configuration is deprecated can be an empty list instead of just `null`. This is misinterpreted by the Gradle analyzer plugin, and all Gradle configurations are considered deprecated. As a result, no dependencies for no Gradle configurations are returned.
Fixes #9255

fix(gradle): Also check for non-empty resolution alternatives

---

plugins/commands/upload-result-to-sw360/build.gradle.kts
plugins/package-curation-providers/sw360/build.gradle.kts
scanner/build.gradle.kts

Avoid CVE-2024-47554 by manually updating transitive commons-io versions until a new SW360 client version is available.

build(gradle): Update transitive commons-io versions

---

plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/workspaces/package.json

When running `pnpm` in the project directory of the `workspaces` project, it outputs the warning [1]. Remove the `workspaces` tag, as to fix that warning.
[1] `The "workspaces" field in package.json is not supported by pnpm.
Create a "pnpm-workspace.yaml" file instead.`

test(pnpm): Drop the unsupported `workspaces` property

---

plugins/package-managers/maven/src/main/kotlin/utils/MavenSupport.kt
plugins/package-managers/maven/src/test/kotlin/utils/MavenSupportTest.kt

When resolving artifacts using a `ProjectBuilder`, remote repositories from the Eclipse Aether library have to be converted to the model used by the Maven repository system. So far, only the most prominent properties have been converted. In certain constellations, this is not sufficient. In a concrete case, resolution failed for an artifact located in a repository that was defined in a pom of a transitive dependency. For this repository the information about the required proxy was lost, and so network requests caused exceptions.
Fix this by also dealing with the properties related to the proxy and authentication.
Note: It would probably be good to have a synthetic fun test for the problematic constellation, but I don't think it is feasible to create one, since the constellation is rather …

fix(maven): Correctly convert repositories

---

plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt

Do not use that feature before it was added in Gradle 6.8, see [1]. This is a fixup for 8deb4b3.
Fixes #9282.
[1]: https://docs.gradle.org/6.8/release-notes.html#central-declaration-of-repositories

fix(gradle-plugin): Guard `dependencyResolutionManagement` usage

---

utils/spdx/src/main/kotlin/SpdxExpression.kt

See e.g. [1], which is marked as an exception.
[1]: https://scancode-licensedb.aboutcode.org/?search=LicenseRef-scancode-ecma-no-patent

fix(spdx-utils): Accept the "no patent" exception

---

.github/workflows/release.yml

Creating the Sonatype staging repository occasionally fails with a timeout, therefore increase it from the default 1 minute [1] to 5 minutes.
[1]: https://vanniktech.github.io/gradle-maven-publish-plugin/central/#timeouts

ci(release): Increase the timeout for creating the staging repository

---

cli/src/main/kotlin/OrtMain.kt

Do not expose any credentials, e.g. when included in proxy URLs.
Fixes #9294.

fix(cli): Remove credentials from environment variables

---

plugins/package-managers/pub/src/main/kotlin/model/Pubspec.kt
plugins/package-managers/pub/src/test/kotlin/model/PubspecTest.kt

fix(pub): Support deserializing hosted deps without version constraint

---

plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt

In large projects with many dependencies, the GradleInspector plugin often runs out of Java heap space, even when allocated 2 GB. This is due to all dependencies being stored in a large tree structure, which consumes a significant amount of memory.
This change introduces a caching mechanism for dependency subtrees of components. Instead of traversing and storing the entire dependency tree every time, the cache is checked first. If a subtree for a component already exists in the cache, a reference to this cached data is used, reducing memory consumption significantly.
Fixes #9220.

fix(gradle-inspector): Optimize memory by caching dependency subtrees

---

integrations/jenkins/Jenkinsfile

fix(jenkins): Allow to select DOS as a project and package scanner

---

plugins/package-managers/node/src/main/kotlin/Npm.kt
plugins/package-managers/node/src/main/kotlin/utils/NpmDependencyHandler.kt

The code looks like it would run things in parallel, but it executes `getRemotePackageDetails()` strictly sequentially. The pull request which had introduced these constructs [1] also introduced the caching. So, the speed-up observed back then was probably solely due to the added cache. Remove the parallelization constructs to not mislead the reader and to simplify.
[1]: https://github.com/oss-review-toolkit/ort/pull/6009
Part of #9261.

refactor(npm): Remove unused parallelization constructs

---

helper-cli/src/main/kotlin/commands/GetPackageLicensesCommand.kt
model/src/main/kotlin/ScanResult.kt
model/src/main/kotlin/ScanSummary.kt
model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/main/kotlin/utils/FindingsMatcher.kt
model/src/main/kotlin/utils/PathLicenseMatcher.kt
model/src/test/kotlin/utils/PathLicenseMatcherTest.kt
model/src/test/kotlin/utils/RootLicenseMatcherTest.kt
plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelMapper.kt

Rename `RootLicenseMatcher` to `PathLicenseMatcher`

---

plugins/package-managers/node/src/main/kotlin/Npm.kt
plugins/package-managers/node/src/main/kotlin/Yarn.kt
plugins/package-managers/node/src/test/kotlin/YarnTest.kt

Part of https://github.com/oss-review-toolkit/ort/issues/9261.

Yarn info parsing fixes

---

plugins/package-managers/node/src/main/kotlin/Npm.kt
plugins/package-managers/node/src/main/kotlin/utils/NpmDependencyHandler.kt

Move all logger dependencies from `parsePackage()` to the callers, to avoid the need for passing the logger when moving this function outside of `Npm`. And finally perform the move. This prepares for removing the inheritance in node package managers.
Part of #9261.

npm: Prepare to re-use `parsePackage()` from outside of `Npm`

---

model/src/test/kotlin/utils/PurlUtilsTest.kt

Make more clear that these do not actually test code but perform sanity checks on the given test data.

refactor(model): Turn purl test data assertions into sanity checks

---

plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/babel-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/babel/package-lock.json
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/babel-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/babel/package.json
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/babel/pnpm-lock.yaml
plugins/package-managers/node/src/funTest/kotlin/PnpmFunTest.kt
plugins/package-managers/node/src/test/kotlin/utils/NpmDetectionTest.kt

Add the babel test analog to the one for NPM, for comparability.
Part of #9261.

Increase Pnpm's fun test coverage a bit

---

plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/babel-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/project-with-lockfile-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/workspaces-expected-output.yml
plugins/package-managers/node/src/funTest/kotlin/pnpm/PnpmFunTest.kt
plugins/package-managers/node/src/funTest/kotlin/yarn2/Yarn2FunTest.kt
plugins/package-managers/node/src/main/kotlin/Npm.kt
plugins/package-managers/node/src/main/kotlin/pnpm/ModuleInfo.kt
plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt
plugins/package-managers/node/src/main/kotlin/pnpm/PnpmDependencyHandler.kt
plugins/package-managers/node/src/main/resources/META-INF/services/org.ossreviewtoolkit.analyzer.PackageManagerFactory

Rewrite large parts of Pnpm from scratch to figure out all information based on `pnpm` CLI output, and
remove the inheritance from `Npm`. 
Part of #9261.

Make `Pnpm` separate from `Npm`

---

integrations/jenkins/README.md

Add [Copy Artifact](https://plugins.jenkins.io/copyartifact/) as a required plugin since it's not installed/enabled by default in Jenkins >= 2.462.3
Signed-off-by: Grigori Prokhorov <hello@feinberg.it>

docs(integrations): Fix README.md to include required plugin for Jenkins >= 2.462.3

---

evaluator/src/main/kotlin/Evaluator.kt
evaluator/src/main/kotlin/RulesScriptTemplate.kt
notifier/src/main/kotlin/NotificationsScriptTemplate.kt
notifier/src/main/kotlin/Notifier.kt
reporter/src/main/kotlin/HowToFixTextProvider.kt
reporter/src/main/kotlin/HowToFixTextProviderScriptTemplate.kt

This reverts commit 8451714 as IntelliJ still does not properly highlight the syntax / auto-complete with the change, see [1].
The original reason to do 8451714 was meanwhile fixed with Kotlin 2.0.20, see [2], so it should be safe to revert.
[1]: https://youtrack.jetbrains.com/issue/KTIJ-30059
[2]: https://youtrack.jetbrains.com/issue/KT-68336

Revert "refactor(script): Migrate from deprecated `constructorArgs` to properties"

---

plugins/package-managers/node/src/main/kotlin/PackageJson.kt
plugins/package-managers/node/src/test/kotlin/PackageJsonTest.kt

A repository node wihtout a `url` does not make any sense. So, simply discard such nodes to not throw a `MissingFieldException` while keeping `Repository.url` non-nullable.
Fixes #9378.

fix(node): Deserialize `repository: {}` in `package.json` to `null`

---

plugins/package-managers/node/src/main/kotlin/npm/ModuleInfo.kt
plugins/package-managers/node/src/main/kotlin/npm/Npm.kt
plugins/package-managers/node/src/main/kotlin/npm/NpmDependencyHandler.kt
plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
plugins/package-managers/node/src/test/kotlin/yarn/YarnDependencyHandlerTest.kt

Make `Npm` separate from `Yarn`

---

plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt
plugins/advisors/vulnerable-code/src/test/kotlin/VulnerableCodeTest.kt

Even if for a vulnerability a fix is available (in a later version of the package) the checked version of the package stays vulnerable, so still list fixed vulnerabilities.

fix(vulnerable-code): Still get vulnerabilities for which a fix exists

---

clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt
plugins/commands/upload-curations/src/main/kotlin/UploadCurationsCommand.kt
plugins/package-curation-providers/clearly-defined/src/main/kotlin/ClearlyDefinedPackageCurationProvider.kt
scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt

That client has a higher read timeout value and properly sets the user agent.

fix(clearly-defined): Consistently use ORT's OkHttp client for requests

---

.github/workflows/build-and-test.yml

As CodeQL traces `kotlinc` invocations, avoid everything being pulled from the cache which would result in no invocations being made.
See [1] for context.
[1]: https://github.com/github/codeql/issues/17962

ci(github): Disable the build cache for CodeQL analysis

---

analyzer/src/main/kotlin/AnalyzerResultBuilder.kt

This makes links valid / clickable to directly inspect the source.

chore(analyzer): Use permalinks in the error for duplicate projects

---

plugins/advisors/vulnerable-code/src/test/kotlin/VulnerableCodeTest.kt

This is a fixup for 45b40d8. The test passed although the stub was not matched because only the presence of an issue was checked, but not which one. Improve that as well.

test(vulnerable-code): Correct a stub path and assertion condition

---

plugins/package-managers/node/src/funTest/kotlin/npm/NpmFunTest.kt

This was accidentally kept by dfaa896.

test(npm): Remove a left-over replacement

---

plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/node-modules-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/project-with-lockfile-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/project-with-lockfile/package-lock.json
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/project-with-lockfile-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/project-with-lockfile-skip-excluded-scopes-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/project-with-lockfile/pnpm-lock.yaml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/project-with-lockfile-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/project-with-lockfile/yarn.lock
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/workspaces/yarn.lock
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/project-with-lockfile-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/project-with-lockfile-skip-excluded-scopes-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/project-with-lockfile/yarn.lock
plugins/package-managers/node/src/funTest/kotlin/npm/NpmFunTest.kt

Make the results easy to compare.
Part of #9261.

Node: Re-create the lockfiles for the `project-with-lockfile` test projects

---

plugins/advisors/vulnerable-code/src/funTest/kotlin/VulnerableCodeFunTest.kt

The base score of 4.8 indeed seems to be correct according to [1].
[1]: https://nvd.nist.gov/vuln/detail/CVE-2024-48948

test(vulnerable-code): Update expected results

---

plugins/reporters/aosd/src/main/kotlin/Aosd2Reporter.kt
plugins/reporters/aosd/src/main/kotlin/Model.kt

When trying to upload the AOSD 2.0 file generated with ORT to the AOSD platform we encountered some problems.
After always creating a default "part", including empty fields (that where marked as optional but seem to be necessary) and removing hash algorithms other than SHA256 the file can now be uploaded to the Audi AOSD platform.

Fix AOSD2 export

---

clients/clearly-defined/src/funTest/kotlin/ClearlyDefinedServiceFunTest.kt

This should not happen as of 4a41869. Disable these tests until the issue is resolved with the ClearlyDefined folks.

test(clearly-defined): Temporarily disable flaky tests

---

plugins/package-managers/node/src/main/kotlin/pnpm/ModuleInfo.kt

The name and version fields may be absent for projects, while they are not absent for (published) dependencies. Specify a default value to avoid running into an exception during deserialization.
Fixes #9461.

fix(pnpm): Tolerate absent name / version in projects' `package.json`

---

scanner/src/main/kotlin/Scanner.kt
scanner/src/main/kotlin/utils/Utils.kt

Scanners generally do **not** consider the _VCSPath_ when performing an ORT scan on a repository, as they scan the entire repository and its dependencies. The resulting scan data is cached for reuse across multiple scans.
When reusing cached scan results for ORT scans with a specified _VCSPath_, where only a subset of the repository is scanned, it is necessary to filter out extraneous scan results. Helper functions already exist to handle this filtering.
This refactoring extracts these helper functions to enhance reusability by ORT Server.
See discussion here: eclipse-apoapsis/ort-server#1358
No changes in functionality or logic, just pure refactoring in separate (static) functions.

refactor(scanner): Extract VCSPath filtering functions

---

model/src/main/kotlin/DependencyGraphNavigator.kt

@oheger-bosch am I correctly describing the rationale here why traversing is not stopped after finding the first match for a node?

docs(model): Add a comment about the algorithm in `traverse()`

---

model/src/main/kotlin/utils/PurlExtensions.kt
model/src/main/kotlin/utils/PurlUtils.kt
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-7.2-expected-output.yml
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output-archive-override.yml
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output-git-repository.yml
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output-local-path-override.yml
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output-local-registry-with-local-path.yml
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output-local-registry.yml
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output-local-registry2.yml
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output-no-lock-file.yml
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output.yml

See also [1].
[1]: https://github.com/package-url/purl-spec/pull/317

feat(model): Extend `Identifier.toPurl()` with handling for `Bazel`

---

plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt

This PR is only a starter for a series of PRs to make the code simpler and easier to read.
This are preparations which occurred when trying to re-use the `parsePackage()` and `parseProject()` functions used for the other three node managers, but further preparations will be needed..

Yarn2 simplifications

---

clients/clearly-defined/src/main/kotlin/Enums.kt

Be clear that not `null` is returned if no match for an enum is found.

refactor(clearly-defined): Make it explicit that `fromString()` throws

---

model/src/main/kotlin/CompatibilityDependencyNavigator.kt
model/src/main/kotlin/DependencyGraphNavigator.kt
model/src/main/kotlin/DependencyNavigator.kt
model/src/main/kotlin/DependencyTreeNavigator.kt
model/src/main/kotlin/OrtResult.kt
model/src/test/kotlin/AbstractDependencyNavigatorTest.kt
model/src/test/kotlin/CompatibilityDependencyNavigatorTest.kt
plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelMapper.kt
plugins/reporters/static-html/src/main/kotlin/TablesReportModelMapper.kt

Reduce the number of very similar overloads and simplify return types in favor of calling fewer "orthogonal" functions in combination, if required. This also aligns the naming of functions to be more consistent.

model(refactor)!: Simplify the `DependencyNavigator` API

---

plugins/reporters/aosd/src/main/kotlin/Aosd21Reporter.kt

fix(aosd): Fix the default descriptor argument for the AOSD 2.1 reporter

---

plugins/reporters/opossum/build.gradle.kts
plugins/reporters/opossum/src/funTest/kotlin/OpossumReporterFunTest.kt
plugins/reporters/opossum/src/main/kotlin/OpossumModel.kt
plugins/reporters/opossum/src/main/kotlin/OpossumReporter.kt
plugins/reporters/opossum/src/test/kotlin/OpossumReporterTest.kt

[FOR REVIEW]: Best reviewed commit by commit. First commit of this PR contains the actual changes. Second commit just moves code around to improve readability.
**Context**
Closes #8839
**Summary** 
Migrates the `OpossumReporter` plugin away from Jackson serialization to use kotlinx serialization.
To get properly typed data structures for serialization the previous untyped `Map<*, *>`s are substituted by properly typed data classes. This leads to the creation of an `OpossumInputCreator` class that holds intermediate data structures needed for processing of the Reporter input.
**Test Plan**
1) Automated tests:
OpossumReporterTest 
OpossumReporterFunTest
2) Manual test: Compare two opossum files with ORT builds from main and this branch
repeat for each branch:
```
./gradlew installDist …
```

Migrate the Opossum reporter to KxS

---

REUSE.toml

The migration in 97a81dd5 added `precedence = "aggregate"`, probably to resemble the old behavior. However, the most natural and also new default behavior is to use the license declaration that is closest [1] to the file.
Fixes #8771, because now the `conanfile.py.license` information takes precedence over the matching entry in the root's `REUSE.toml` file.
[1]: https://reuse.software/spec-3.3/#reusetoml

fix(reuse): Use the default "precedence" of "closest"

---

plugins/package-managers/gradle-inspector/src/main/kotlin/GradleDependencyHandler.kt

At this point ORT does not know if the belonging artifact actually exists, and for non-existing artifacts it is natural to not have a checksum file published, so lower this to only a debug log.

chore(gradle-inspector): Lower logging of missing checkums to debug

---

buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
gradle/gradle-daemon-jvm.properties

This reverts commit c9d114c as the issue cannot be reproduced anymore with Fedora 41 and Gradle 8.11.1.

Revert "fix(gradle): Be specific about using Adoptium / Temurin as the JDK"

---

model/src/main/kotlin/Project.kt
plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/babel-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/node-modules-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/project-with-lockfile-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/shrinkwrap-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/shrinkwrap-skip-excluded-scopes-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/version-urls-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/babel-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/project-with-lockfile-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/project-with-lockfile-skip-excluded-scopes-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/workspaces-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/babel-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/project-with-lockfile-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn/workspaces-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/project-with-lockfile-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/project-with-lockfile-skip-excluded-scopes-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/yarn2/workspaces-expected-output.yml
plugins/package-managers/node/src/main/kotlin/NpmSupport.kt
plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt

Add the `description` property to project's, analog to the one in packages and implement support in all node package managers.
Fixes #9443.

Introduce a Project description property and support for it in node

---

plugins/reporters/asciidoc/src/main/kotlin/AsciiDocTemplateReporter.kt
plugins/reporters/asciidoc/src/main/kotlin/PdfTemplateReporter.kt
plugins/reporters/freemarker/src/main/kotlin/PlainTextTemplateReporter.kt

This is a fixup for 27f0dae and 88aa4a0. In those commits the reporter options `template.id` and `template.path` were renamed to `templateIds` and `templatePaths` but the aliases for backward compatibility have been set wrongly.

fix(reporter): Fix aliases for renamed reporter options

---

.mailmap
helper-cli/src/funTest/assets/create-analyzer-result-from-pkg-list-expected-output.yml
helper-cli/src/funTest/assets/package-list.yml
helper-cli/src/main/kotlin/commands/CreateAnalyzerResultFromPackageListCommand.kt

Support injecting `purls` for packages when creating an analyzer result from a `PackageList`, to allow using the analyzer results as-is with purl-based advisors, such as OSV and (the upcoming) BlackDuck.
Related to: #8739.

helper-cli: Allow to specify purls in package lists used for creating analyzer results

---

helper-cli/src/funTest/assets/create-analyzer-result-from-pkg-list-expected-output.yml
helper-cli/src/funTest/kotlin/commands/CreateAnalyzerResultFromPackageListCommandFunTest.kt

The test has been missing back when the functionality was added.
Done in context of: #8739.

helper-cli: Test that curations are added when creating an analyzer results from package lists

---

website/docs/configuration/package-configurations.md

fix: Typo in evaluator call example

---

scanner/src/test/kotlin/FileListTest.kt

Since f38b42d the `FileListResolverTest` does not implicitly test the serialization of file lists anymore, so add a separate test case for that.

test(scanner): Add a test for serializing `FileList`

---

advisor/build.gradle.kts
advisor/src/main/kotlin/Advisor.kt
advisor/src/test/kotlin/AdvisorTest.kt
plugins/advisors/osv/build.gradle.kts
plugins/advisors/osv/src/funTest/assets/retrieve-package-findings-expected-result.json
plugins/advisors/osv/src/funTest/kotlin/OsvFunTest.kt
plugins/advisors/osv/src/main/kotlin/Osv.kt
plugins/advisors/vulnerable-code/src/funTest/kotlin/VulnerableCodeFunTest.kt
plugins/advisors/vulnerable-code/src/main/kotlin/VulnerableCode.kt
plugins/advisors/vulnerable-code/src/test/kotlin/VulnerableCodeTest.kt

Centrally normalize vulnerability data 

---

advisor/src/main/kotlin/Advisor.kt

It can be confusing to use `let` if the goal is not to map the (anyway discarded) return value, so use `also` instead to emphasize that just some additional work (logging in this case) is done.

chore(advisor): Prefer `also` over `let` when not mapping

---

plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt

As no more inheritance is involved, also `open` modifiers are not needed anymore.

chore(node): Remove unneeded `open` modifiers from Yarn code

---

plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt

Do not require an exact match of method names, but map according to CVSS prefixes known to ORT.
Resolves #9556.

fix(cyclonedx): Improve mapping of vulnerability methods

---

model/src/main/kotlin/Project.kt

fix(model): Keep the description when converting a project to a package

---

helper-cli/src/main/kotlin/commands/CreateAnalyzerResultFromPackageListCommand.kt

The recent addition of `dependency.purl` [1] made providing that `purl` mandatory. That should have been optional so that the change is non-breaking. Fix that by adding a default value.
[1] b1a157d7dfa8889cc1a7d143f04ee514e58443da

fix(helper-cli): Add a default value for `Dependency.purl`

---

plugins/reporters/spdx/src/main/kotlin/Extensions.kt

Same for the originator. This is a fixup for eead59c.

fix(spdx): Use a single space after the person prefix for the supplier

---

plugins/version-control-systems/git/src/main/kotlin/GitRepo.kt
plugins/version-control-systems/mercurial/src/main/kotlin/Mercurial.kt

The fact that CLIs are used is an implementation detail that should be hidden away as much as possible.
Note that because these changes are in plugins (and not in public API of core modules), they should not be regarded as breaking changes.

refactor(version-control-systems): Reduce visibility of `CommandLineTool`s

---

plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
plugins/package-managers/bower/src/main/kotlin/Bower.kt
plugins/package-managers/cargo/src/main/kotlin/Cargo.kt
plugins/package-managers/cocoapods/src/main/kotlin/CocoaPods.kt
plugins/package-managers/composer/src/main/kotlin/Composer.kt
plugins/package-managers/conan/src/main/kotlin/Conan.kt
plugins/package-managers/go/src/main/kotlin/GoMod.kt
plugins/package-managers/node/src/main/kotlin/npm/Npm.kt
plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt
plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
plugins/package-managers/node/src/test/kotlin/npm/NpmTest.kt
plugins/package-managers/python/src/main/kotlin/Pipenv.kt
plugins/package-managers/python/src/main/kotlin/Poetry.kt
plugins/package-managers/sbt/src/main/kotlin/Sbt.kt
plugins/package-managers/stack/src/main/kotlin/Stack.kt
plugins/package-managers/stack/src/test/kotlin/StackTest.kt
plugins/package-managers/swiftpm/src/main/kotlin/SwiftPm.kt

Make more clear that package manager implementation *are* not CLIs, but eventually *use* CLIs. This is a better separation of concerns and reduces the sizes of the main classes.
Do the refactoring for all but `Pub` and `Yarn2` for now as these require more work.
Note that `CommandLineTool` implementations in plugins can at maximum be `internal` for the `ort requirements` command to work.

refactor(package-managers): Prefer composition for `CommandLineTool`s

---

plugins/reporters/cyclonedx/src/main/kotlin/BomExtensions.kt

fix(cyclonedx): Avoid a `StackOverflowError` due to dependency cycles

---

analyzer/src/main/kotlin/Analyzer.kt
clients/clearly-defined/src/main/kotlin/ClearlyDefinedService.kt
plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
plugins/reporters/fossid/src/main/kotlin/FossIdReporter.kt
plugins/scanners/fossid/src/main/kotlin/FossId.kt
scanner/src/main/kotlin/Scanner.kt

`Dispatchers.IO` has a default thread limit of 64. This can lead to thread starvation resulting in deadlocks, if more than 64 coroutines doing blocking calls are running in parallel. Exceeding this limit can also negatively impact performance if no blocking calls are involved.
To fix this, use `limitedParallelism` [1] to limit the amount of coroutines running at the same time, and to make use of the elasticity feature of `Dispatchers.IO` [2].
This commit applies a conservative limit of 20 to places where `Dispatchers.IO` is used and many parallel coroutines are started. This value can later be adjusted if it has negative impact on performance.
[1]: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-dispatcher/limited-parallelism.html
[2]: …

fix: Use limited parallelism to prevent thread starvation

---

utils/common/src/main/kotlin/FileMatcher.kt

This is a fixup for 32ab460 which forgot about the intended optimization done by the previous implementation.

chore(common-utils):  Only decide once which `match()` to call

---

plugins/package-managers/composer/src/main/kotlin/Composer.kt
plugins/package-managers/composer/src/main/kotlin/LockfileProvider.kt

Introduce a `LockfileProvider` that ensures a lockfile to be present by either using the existing one, or enabling the creation of one and creating it. A self-created lockfile is deleted afterwards, and any modifications to the definition file are reverted.

fix(composer): Restore any modified files after analysis

---

plugins/advisors/oss-index/build.gradle.kts
plugins/advisors/oss-index/src/test/kotlin/OssIndexTest.kt
plugins/advisors/osv/src/funTest/kotlin/OsvFunTest.kt
utils/test/src/main/kotlin/Utils.kt

Minor advisor test improvements

---

plugins/reporters/spdx/src/funTest/kotlin/SpdxDocumentReporterFunTest.kt
plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
utils/spdx/src/main/kotlin/model/SpdxCreationInfo.kt

fix(reporter): Only write major / minor SPDX license list version info

---

utils/common/src/test/kotlin/EnvironmentVariableFilterTest.kt

Test `EnvironmentVariableFilter` with an empty deny list

---

helper-cli/src/main/kotlin/commands/classifications/ImportCommand.kt
plugins/advisors/vulnerable-code/src/test/kotlin/VulnerableCodeTest.kt
plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
plugins/package-managers/carthage/src/test/kotlin/CarthageTest.kt
plugins/version-control-systems/git/src/test/kotlin/GitTest.kt
utils/ort/src/main/kotlin/OkHttpClientHelper.kt
utils/ort/src/main/kotlin/storage/S3FileStorage.kt
utils/ort/src/test/kotlin/UtilsTest.kt
utils/spdx/build.gradle.kts

For the difference see [1].
[1]: https://www.baeldung.com/java-uri-create-and-new-uri

chore: Align on constructing URIs without `create()`

---

renovate.json

Change the commit message topic to `{{depName}}` instead of the default `dependency {{depName}}` [1]. "dependency" is redundant as the conventional commit type is already "deps".
[1]: https://docs.renovatebot.com/configuration-options/#commitmessagetopic

ci(renovate): Shorten the commit message for Gradle dependencies

---

model/src/main/kotlin/utils/SortedCollectionConverters.kt
plugins/package-managers/conan/src/main/kotlin/Conan.kt
plugins/reporters/opossum/src/main/kotlin/OpossumReporter.kt

Avoid any confusion what `this` refers to for these (extension) functions.

chore(opossum): Prefer `add` functions when building collections

---

scripts/docker_run.sh

Use the same image root that `docker_build.sh` uses by default.

fix(scripts): Use the default image root when running Docker

---

plugins/package-managers/bazel/src/main/kotlin/Bazel.kt

This is a fixup for 8516d2a. However, note [1] about the version always saying "redacted".
[1]: https://github.com/bazelbuild/buildtools/issues/831

fix(bazel): Correctly get the Buildozer version

---

model/src/main/kotlin/DependencyGraphNavigator.kt
plugins/reporters/aosd/src/main/kotlin/Aosd21Reporter.kt

Fix AOSD transitive linking

---

gradle/libs.versions.toml
notifier/build.gradle.kts

Probably because the latest version of `jira-rest-java-client-app` is not hosted on Maven Central [1], Renovate seems to have missed this.
As the client relies on `jakarta.ws.rs:jakarta.ws.rs-api:2.1.6` to be available transitively, which is not the case anymore with `org.glassfish.jersey.core:jersey-common:2.42`, add that dependency directly until [2] is resolved.
[1]: https://mvnrepository.com/artifact/com.atlassian.jira/jira-rest-java-client-app
[2]: https://ecosystem.atlassian.net/browse/JRJC-262

deps: Upgrade the JIRA REST client to version 6.0.1

---

plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
plugins/scanners/scancode/src/test/kotlin/ScanCodeTest.kt

ScanCode's raw JSON results are not exposed by ORT and thus not looked at by humans. So disable pretty-printing for the chance of a tad quicker result generation.

chore(scancode): Print JSON raw results non-pretty

---

buildSrc/src/main/kotlin/ort-base-conventions.gradle.kts

build(gradle): Remove an unneeded artifact version filter

---

plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result-with-findings.json
plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result-without-findings.json
plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result.json
plugins/reporters/cyclonedx/src/funTest/assets/cyclonedx-reporter-expected-result.xml
plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt

Increase the default schema version from 1.5 to 1.6 which is currently the latest version [1]. For the release notes see [2].
[1]: https://cyclonedx.org/about/history/
[2]: https://cyclonedx.org/news/cyclonedx-v1.6-released/

feat(cyclonedx): Change the default schema version to 1.6

---

utils/spdx/src/test/kotlin/SpdxExpressionChoiceTest.kt

This test was observed to take longer on Windows, see e.g. [1].
[1]: https://github.com/oss-review-toolkit/ort/actions/runs/12388007556/job/34578512435#step:5:4691

test(spdx-utils): Increase a test timeout a bit

---

analyzer/src/main/kotlin/PackageManager.kt

Specifically, clarify that the `projectType` does not refer to dependencies.

docs(analyzer): Improve `PackageManager` class documentation

---

model/src/main/kotlin/Issue.kt
plugins/scanners/fossid/src/main/kotlin/FossIdScanResults.kt

When FossID reports non-SPDX licenses, it is hard to find the file that initially contained this invalid license.
Improve the user experience by adding the file path to the issue message.

chore(fossid): Add file path with invalid licenses to the error messages

---

plugins/reporters/aosd/src/main/kotlin/Aosd21Reporter.kt

These are not collections SPDX of expressions.

chore(aosd): Rename a few variables to singular

---

utils/spdx/src/main/kotlin/SpdxExpression.kt
utils/spdx/src/test/kotlin/SpdxCompoundExpressionTest.kt
utils/spdx/src/test/kotlin/SpdxExpressionChoiceTest.kt

Simplify redundant SPDX choices

---

model/src/main/kotlin/licenses/LicenseInfoResolver.kt
model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt

Include authors for package dependencies when both `concluded_license` and `authors` are curated, and ORT is configured with the `addAuthorsToCopyrights` option enabled. This ensures that package authors appear under the respective concluded license in the Disclosure Document.
This behaviour applies when the Scanner option `skipConcluded` is enabled, having the effect that the scan stage is skipped for the particular package dependency in this case, and if either the _concluded_ license is different from the _declared_ license or if no license is _declared_ at all.
Fixes #9599.

fix(reporter): Add authors to concluded license

---

Dockerfile
utils/spdx/src/main/kotlin/Utils.kt

Dump the ScanCode license texts to directory _/opt/scancode-license-data_ when creating the ORT docker container. Use this directory as fallback option if the ScanCode license texts cannot be located by the existing heuristic algorithm.
Fixes #8147.

fix(scancode): No ScanCode license texts in disclosure document

---

analyzer/src/main/kotlin/PackageManager.kt
model/src/main/kotlin/config/RepositoryConfiguration.kt

While ORT does not really make use of the term "product" in its docs yet, start to use that term to clarify that repo config is not specific to a "project" in the ORT sense (i.e. something defined by a single definition file), but to the sum of the projects in a repository that form a "product" and that are captured by an analysis.

docs: Clarify that repo config is specific to a "product"

---

notifier/build.gradle.kts

Prevent consumers of the notifier to upgrade the Jakarta REST API because the Jira library requires version 2.1.x which still has the "javax" instead of the "jakarta" package namespace.

build(notifier): Make the Jakarta REST API dependency a constraint

---

model/src/main/kotlin/CuratedPackage.kt
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/PackageCurationData.kt

chore(model): Minor package related fixes

---

buildSrc/src/main/kotlin/ort-base-conventions.gradle.kts
gradle/libs.versions.toml
integrations/completions/ort-completion.fish
model/src/main/resources/reference.yml
plugins/advisors/black-duck/build.gradle.kts
plugins/advisors/black-duck/src/funTest/assets/recorded-responses.json
plugins/advisors/black-duck/src/funTest/assets/retrieve-package-findings-expected-result.yml
plugins/advisors/black-duck/src/funTest/kotlin/BlackDuckFunTest.kt
plugins/advisors/black-duck/src/funTest/kotlin/ResponseCachingComponentServiceClient.kt
plugins/advisors/black-duck/src/main/kotlin/BlackDuck.kt
plugins/advisors/black-duck/src/main/kotlin/BlackDuckConfiguration.kt
plugins/advisors/black-duck/src/main/kotlin/ComponentServiceClient.kt
plugins/advisors/black-duck/src/main/kotlin/ExtendedComponentService.kt
website/docs/tools/advisor.md

Add an initial version of the integration of BlackDuck as security vulnerability provider.
Note: The implementation will be iterated upon, e.g. a curation mechanism to manually specify an origin will
be added in a following PR.

feat(advisor): Add BlackDuck as advisor

---

examples/curations.yml
helper-cli/src/funTest/assets/create-analyzer-result-from-pkg-list-expected-output.yml
helper-cli/src/funTest/assets/package-list.yml
helper-cli/src/main/kotlin/commands/CreateAnalyzerResultFromPackageListCommand.kt
model/src/main/kotlin/Package.kt
model/src/main/kotlin/PackageCurationData.kt
model/src/test/kotlin/PackageCurationDataTest.kt
model/src/test/kotlin/PackageCurationTest.kt
website/docs/configuration/package-curations.md

Allow setting arbitrary key-value pairs on a `Package`, which is not interpreted by ORT's core.
The property can be useful for ORT plugins (not necessarily public), policy rules, notice templates and so forth.
Also, in cases where introducing a dedicated property under `Package` makes sense, this mechanism can be used as a temporary work-around to remove the introduction of the dedicated property from any critical development path.
Fixes #8725.

feat(model): Add a generic labeling mechanism for packages

---

model/src/main/kotlin/PackageCuration.kt
model/src/main/kotlin/PackageCurationData.kt

The term "target" was misleading as it could be the target of the curation application, or the target where to store the result. Clarify that by calling it the `basePackage`. Also rename `original` to `base` to align with that, and slightly rework some docs while at it.

chore(model): Rename package curation `apply` variables for clarity

---

website/docusaurus.config.js
website/src/pages/index.js

fix(website): Move a link out of the tagline variable

---

plugins/commands/reporter/src/main/kotlin/ReporterCommand.kt

Rework console output to use some color, and print the duration only once per report format as it is not measured per file format. Also prefer echoing over logging in the CLI frontend.

feat(ReporterCommand): Use console colors for the result summary

---

helper-cli/src/main/kotlin/commands/dev/RewriteTestAssetsCommand.kt
model/src/main/kotlin/utils/Extensions.kt
plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt
plugins/compiler/src/main/kotlin/PluginFactoryGenerator.kt
plugins/package-managers/bazel/src/main/kotlin/Bazel.kt
plugins/package-managers/carthage/src/main/kotlin/Carthage.kt
plugins/package-managers/maven/src/test/kotlin/utils/MavenDependencyHandlerTest.kt
plugins/package-managers/nuget/src/main/kotlin/utils/NuGetInspectorExtensions.kt
plugins/package-managers/python/src/main/kotlin/Poetry.kt
plugins/reporters/opossum/src/main/kotlin/OpossumModel.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOssResultParser.kt
utils/ort/src/funTest/kotlin/storage/S3FileStorageFunTest.kt
utils/ort/src/main/kotlin/UserInfoAuthenticator.kt

If non-string types are not parsable but have a default value, do not throw but fall back to that value.

chore: Prefer the char-version of `split()` for single chars

---

plugins/package-managers/cargo/src/main/kotlin/Cargo.kt

a7078fe updated Cargo to support lockfile version 4, however we also maintain an allow-list of lockfile versions for which we understand the checksum computation. Add version 4 to this allow-list.

fix(cargo): Add lockfile version 4 to allow-list

---

plugins/package-managers/node/src/main/kotlin/NpmSupport.kt
plugins/package-managers/node/src/main/kotlin/npm/Npm.kt
plugins/package-managers/node/src/main/kotlin/npm/NpmDependencyHandler.kt
plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt
plugins/package-managers/node/src/main/kotlin/pnpm/PnpmDependencyHandler.kt

Node-related improvements

---

plugins/package-managers/node/src/main/kotlin/NpmSupport.kt
plugins/package-managers/node/src/main/kotlin/npm/NpmDependencyHandler.kt
plugins/package-managers/node/src/main/kotlin/pnpm/PnpmDependencyHandler.kt

Make more clear that this is about *getting* package details, and use only "Fun" to resemble the corresponding Kotlin keyword.

chore(node): Rename the typealias to get package details

---

plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/main/kotlin/FossIdNamingProvider.kt
plugins/scanners/fossid/src/test/kotlin/FossIdConfigTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdNamingProviderTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt

Various FossID refactorings to prepare for simplifying the configuration. See the commit messages for details.

Various FossID refactorings

---

plugins/package-managers/gradle-inspector/src/main/kotlin/GradleDependencyHandler.kt
plugins/package-managers/gradle-inspector/src/main/kotlin/GradleInspector.kt
plugins/package-managers/gradle-model/src/main/kotlin/Extensions.kt
plugins/package-managers/gradle/src/main/kotlin/Gradle.kt
plugins/package-managers/gradle/src/main/kotlin/GradleDependencyHandler.kt
plugins/package-managers/gradle/src/test/kotlin/GradleDependencyHandlerTest.kt
plugins/package-managers/python/src/main/kotlin/Pip.kt
plugins/package-managers/python/src/main/kotlin/Pipenv.kt
plugins/package-managers/python/src/main/kotlin/Poetry.kt
plugins/package-managers/sbt/src/main/kotlin/Sbt.kt

Project type usage preparations

---

cli/src/funTest/kotlin/AnalyzerFunTest.kt
downloader/build.gradle.kts
downloader/src/main/kotlin/VersionControlSystem.kt
downloader/src/main/kotlin/VersionControlSystemFactory.kt
downloader/src/test/kotlin/VersionControlSystemTest.kt
plugins/commands/downloader/src/main/kotlin/DownloaderCommand.kt
plugins/version-control-systems/git/build.gradle.kts
plugins/version-control-systems/git/src/funTest/kotlin/GitDownloadFunTest.kt
plugins/version-control-systems/git/src/funTest/kotlin/GitFunTest.kt
plugins/version-control-systems/git/src/funTest/kotlin/GitRepoDownloadFunTest.kt
plugins/version-control-systems/git/src/funTest/kotlin/GitWorkingTreeFunTest.kt
plugins/version-control-systems/git/src/main/kotlin/Git.kt
plugins/version-control-systems/git/src/main/kotlin/GitConfig.kt
plugins/version-control-systems/git/src/main/kotlin/GitRepo.kt
plugins/version-control-systems/git/src/main/resources/META-INF/services/org.ossreviewtoolkit.downloader.VersionControlSystemFactory
plugins/version-control-systems/git/src/test/kotlin/GitTest.kt
plugins/version-control-systems/mercurial/build.gradle.kts
plugins/version-control-systems/mercurial/src/main/kotlin/Mercurial.kt
plugins/version-control-systems/mercurial/src/main/resources/META-INF/services/org.ossreviewtoolkit.downloader.VersionControlSystemFactory
plugins/version-control-systems/subversion/build.gradle.kts
plugins/version-control-systems/subversion/src/main/kotlin/Subversion.kt
plugins/version-control-systems/subversion/src/main/resources/META-INF/services/org.ossreviewtoolkit.downloader.VersionControlSystemFactory
utils/common/src/funTest/kotlin/SafeDeleteRecursivelyFunTest.kt

Migrate VCS plugins to new plugin API

---

model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/main/kotlin/FossIdConfig.kt
plugins/scanners/fossid/src/main/kotlin/FossIdNamingProvider.kt
plugins/scanners/fossid/src/main/kotlin/FossIdUrlProvider.kt
plugins/scanners/fossid/src/test/kotlin/FossIdConfigTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdNamingProviderTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdSnippetChoiceTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt
plugins/scanners/fossid/src/test/kotlin/TestUtils.kt

Refactor the FossID config to prepare for migrating scanners to the new plugin API. See the commit messages for details.

Refactor FossID config

---

analyzer/src/main/kotlin/Analyzer.kt
model/src/main/kotlin/DependencyGraphNavigator.kt

This removes the assumption that package manager names start with the name of the type of project they manage in favor of collecting all root indices that match the project and ensuring that they only stem from a single manager.

chore(DependencyGraphNavigator): Avoid relying on manager name prefixes

---

model/src/main/kotlin/config/ScannerConfiguration.kt
scanner/src/funTest/assets/scanner-integration-all-pkgs-expected-ort-result.yml
scanner/src/funTest/assets/scanner-integration-subset-pkgs-expected-ort-result.yml
scanner/src/main/kotlin/Scanner.kt

Based on #9435, it was stated that we could simply apply curations to files not listed in the license findings. The current PR is one such design but **breaks backwards compatibility**. I would like some feedback on how it would be preferred to deal with this. 
Below I state some of the approaches I have thought of. Any feedback is welcomed.
- detects files without license and these are not added to the output of the scanner (as requested in #9435. As such, the evaluator reports errors for files without license. (**breaks backwards compatibility**)
- if we add curations, curations are applied to the unlicensed files (this is simply because of the curation mechanism)
- unlicensed files use the default value `NONE` when created as part of a `LicenseFinding`.
- **Not complete, missing tests, …

feat(scanner): Add flag to scanner to detect unlicensed files

---

downloader/src/main/kotlin/VersionControlSystem.kt
downloader/src/test/kotlin/VersionControlSystemTest.kt

When looking up a VCS implementation by repository URL or by a working tree directory from the cache, also consider the requested VCS configurations.
Fixes #9795.

fix(vcs): Consider VCS configurations in cache lookup

---

website/docs/tools/analyzer.md

This is used in production and not experimental anymore, despite some missing features, see the open tasks at [1].
[1]: https://github.com/oss-review-toolkit/ort/issues/264

docs(website): Remove the note about Bazel support being experimental

---

.github/workflows/static-analysis.yml

The issue with Ubuntu 24.04 was fixed [1].
[1]: https://github.com/UmbrellaDocs/action-linkspector/issues/32

chore(github): Use `ubuntu-24.04` for Linkspector

---

plugins/reporters/spdx/src/funTest/assets/disclosure-cli-expected-output.spdx.yml
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.json
plugins/reporters/spdx/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml
plugins/reporters/spdx/src/main/kotlin/Extensions.kt
plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt

In an SPDX report, the information of the project itself is converted to an SPDX package entity as it is done for external dependencies as well. However, this project entity does neither contain the attribute `licenseInfoFromFiles` nor does it contain file-level information even though the scanner found (and e.g. the web app report contains) licenses. Only detected copyright statements are included in the field `copyrightText`.
~If the property `file.information.enabled` is set, file-level information for the scanned project is included.~
If the property `fileInformationEnabled` is set to true in the `SpdxDocumentReporter`, file-level information for the scanned project is included.
I would like some feedback on this addition, which is linked to #8485 :) Thanks
These are the minimum set …

feat(spdx): Add file level information to SPDX projects

---

plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt

Only create one 'OrtDependency' for each 'ResolvedComponentResult'. The 'ResolvedComponentResult' is immutable and therefore all 'OrtDependency' object derived from the same 'ResolvedComponentResult' have the same content. Hence, we can reuse these objects to save memory and computation time.
Without this, large builds seem to run forever:
https://github.com/oss-review-toolkit/ort/issues/9763
This PR is a refined version of the fix posted in the error description of https://github.com/oss-review-toolkit/ort/issues/9763

fix: add cache for OrtDependency model objects to OrtModelBuilder

---

plugins/advisors/black-duck/src/funTest/assets/recorded-responses.json
plugins/advisors/black-duck/src/funTest/kotlin/BlackDuckFunTest.kt
plugins/advisors/black-duck/src/funTest/kotlin/ResponseCachingComponentServiceClient.kt
plugins/advisors/black-duck/src/main/kotlin/BlackDuck.kt
plugins/advisors/black-duck/src/main/kotlin/BlackDuckOriginId.kt
plugins/advisors/black-duck/src/main/kotlin/ComponentServiceClient.kt
plugins/advisors/black-duck/src/main/kotlin/ExtendedComponentService.kt

Black Duck: Add a mechanism to set the origin-id for a package via a label curation.

---

analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/PackageManager.kt
analyzer/src/test/kotlin/AnalyzerTest.kt
analyzer/src/testFixtures/kotlin/TestUtils.kt
plugins/package-managers/gradle/src/main/kotlin/Gradle.kt
plugins/package-managers/maven/src/funTest/kotlin/MavenFunTest.kt
plugins/package-managers/maven/src/main/kotlin/Maven.kt
plugins/package-managers/maven/src/main/kotlin/utils/MavenSupport.kt
plugins/package-managers/node/src/main/kotlin/npm/Npm.kt
plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt
plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
plugins/package-managers/sbt/src/main/kotlin/Sbt.kt
utils/common/src/main/kotlin/DiskCache.kt

Maven support disk cache fixes

---

plugins/advisors/black-duck/src/funTest/assets/recorded-responses.json
plugins/advisors/black-duck/src/funTest/kotlin/BlackDuckFunTest.kt
plugins/advisors/black-duck/src/funTest/kotlin/ResponseCachingComponentServiceClient.kt
plugins/advisors/black-duck/src/main/kotlin/BlackDuckOriginId.kt

Black Duck: Support origin-id queries using the "conan" namespace

---

analyzer/src/main/kotlin/PackageManager.kt

fix(PackageManager)!: Use the `projectType` also when resultion failed

---

plugins/package-managers/pub/src/main/kotlin/Pub.kt

Pub project type fixes

---

plugins/package-managers/node/src/funTest/kotlin/npm/NpmFunTest.kt
plugins/package-managers/node/src/funTest/kotlin/pnpm/PnpmFunTest.kt
plugins/package-managers/node/src/funTest/kotlin/yarn/YarnFunTest.kt
plugins/package-managers/node/src/funTest/kotlin/yarn2/Yarn2FunTest.kt

Use `StringSpec`s instead of `WordSpec`s as the latter were used to nest all tests as a whole only.

style(node): Remove one level of nesting from tests

---

plugins/package-managers/node/src/main/kotlin/yarn/ModuleInfo.kt
plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
plugins/package-managers/node/src/test/kotlin/yarn/YarnDependencyHandlerTest.kt

Yarn chores

---

analyzer/src/main/kotlin/AnalyzerResultBuilder.kt
analyzer/src/testFixtures/kotlin/TestUtils.kt
model/src/main/kotlin/DependencyGraphNavigator.kt

Address some nits

---

plugins/advisors/black-duck/src/main/kotlin/BlackDuck.kt

Log the query parameter (purl or origin-id) to make obvious how the origin is of each respective package is determined.

feat(black-duck): Make the log output show how the origin is determined

---

plugins/advisors/black-duck/build.gradle.kts
plugins/advisors/black-duck/src/main/kotlin/BlackDuck.kt
plugins/advisors/black-duck/src/test/assets/.gitattributes
plugins/advisors/black-duck/src/test/assets/BDSA-2024-5272-parsed.yml
plugins/advisors/black-duck/src/test/assets/BDSA-2024-5272.json
plugins/advisors/black-duck/src/test/kotlin/BlackDuckTest.kt

black-duck: Properly de-duplicate vulnerability references

---

analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
model/src/main/kotlin/DependencyGraph.kt
model/src/main/kotlin/DependencyGraphNavigator.kt
model/src/main/kotlin/Project.kt
model/src/main/kotlin/utils/DependencyGraphBuilder.kt
model/src/main/kotlin/utils/DependencyGraphConverter.kt
model/src/test/kotlin/DependencyGraphTest.kt
model/src/test/kotlin/utils/DependencyGraphBuilderTest.kt

Changes to qualified scopes for dependency graphs

---

integrations/schemas/package-manager-configuration-schema.json
integrations/schemas/repository-configurations/analyzer-configuration-schema.json
integrations/schemas/repository-configurations/package-manager-configuration-schema.json
model/src/test/assets/analyzer-repository-configuration.ort.yml
model/src/test/assets/package-manager-repository-configuration.ort.yml
model/src/test/kotlin/JsonSchemaTest.kt

By reusing the analyzer configuration schema, the properties incorrectly used camel case notation, change it to snake case.
While at it, remove the `Sw360Configuration` from the schema, which is not part of the analyzer configuration model.
Resolves #7680

docs(schema): Fix the JSON schema for the repository configuration

---

integrations/schemas/repository-configuration-schema.json

This is a fixup for 8dbd4258f37e74cef86c8dfb5afe88852e184a8c.
Unfortunately I missed to correct the actual reference 🙄

docs(schema): Use reference to correct analyzer configuration schema

---

plugins/advisors/black-duck/src/funTest/assets/recorded-responses.json
plugins/advisors/black-duck/src/funTest/assets/retrieve-package-findings-expected-result.yml
plugins/advisors/black-duck/src/funTest/kotlin/BlackDuckFunTest.kt

advisor:black-duck: Test enhancements

---

model/src/main/kotlin/Provenance.kt

In preparation to split the `KnownProvenance` hierarchy further, for now introduce a `RemoteProvenance` that bundles the `RepositoryProvenance` and `ArtifactProvance`. Later an additional `LocalProvance` will be introduced.
For more context see https://github.com/oss-review-toolkit/ort/issues/8803#issuecomment-2236958430.
This PR succeeds #9476.
Signed-off-by: Jens Keim <jens.keim@forvia.com>

feat(Provenance): Add a `RemoteProvenance` sub-interface

---

plugins/advisors/black-duck/src/main/kotlin/ExtendedComponentService.kt

While the function is a proper work-around for the issue in the overridden function, the function is not called anymore by the Black Duck advisor.
Part of:  #8739.

chore(black-duck): Remove an unnecessary override

---

plugins/version-control-systems/git/src/main/kotlin/Git.kt

Also see [1] for some more background information about why SSH connections can otherwise block "if there is less entropy available than requested".
[1]: https://stackoverflow.com/a/59097932/1127485

fix(Git): Work around a bug with JGit vs MINA

---

plugins/package-managers/composer/src/main/kotlin/Composer.kt

Better explain the idea behind the algorithm, also to highlight the difference to similar code in the `GoMod` analyzer [1], which omits definition files also from "vendor" directories that do not have another definition file as a sibling.
[1]: https://github.com/oss-review-toolkit/ort/blob/01f19307c486f63012ad8b86c08f323622d87abd/plugins/package-managers/go/src/main/kotlin/GoMod.kt#L104-L111

docs(Composer): Improve the comment about filtering vendored dependencies

---

analyzer/src/test/kotlin/AnalyzerResultBuilderTest.kt
model/src/main/kotlin/Project.kt

Chores with respect to resolving project scopes

---

plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/nested-project-expected-output.yml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/nested-project/package.json
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/nested-project/pnpm-lock.yaml
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/nested-project/sub/package.json
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/nested-project/sub/pnpm-lock.yaml
plugins/package-managers/node/src/funTest/kotlin/pnpm/PnpmFunTest.kt
plugins/package-managers/node/src/main/kotlin/pnpm/ModuleInfo.kt
plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt
plugins/package-managers/node/src/test/assets/pnpm-list.json
plugins/package-managers/node/src/test/assets/pnpm-multi-list.json
plugins/package-managers/node/src/test/kotlin/NpmDetectionTest.kt
plugins/package-managers/node/src/test/kotlin/pnpm/ModuleInfoTest.kt

This PR changes the parsing of the PNPM `list` output to handle the special case of nested projects; here the command does not produce syntactically correct JSON. This is related to #9784.
I ran a scan with these changes on an internal project that was failing before, and the generated reports looked at least reasonable. However, I am no expert for PNPM and thus cannot be sure whether the nested project is actually handled correctly. The successful fun tests should prove that no unrelated functionality was broken.

PNPM: Handle projects with nested subprojects

---

model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
plugins/reporters/ctrlx/src/funTest/kotlin/CtrlXAutomationReporterFunTest.kt
plugins/reporters/ctrlx/src/main/kotlin/CtrlXAutomationReporter.kt

feat(ctrlx-reporter): Allow licenses filtering based on the classifications

---

evaluator/src/main/kotlin/ProjectSourceRule.kt
helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
helper-cli/src/main/kotlin/utils/PathExcludeGenerator.kt
model/src/main/kotlin/config/PathExclude.kt
model/src/main/kotlin/utils/FindingCurationMatcher.kt
utils/common/src/main/kotlin/FileMatcher.kt

Minor file matcher improvements

---

clients/fossid-webapp/src/main/kotlin/model/Project.kt
clients/fossid-webapp/src/test/assets/2024.2/mappings/apiphp-get_project.json
clients/fossid-webapp/src/test/kotlin/FossId2024dot2Test.kt

The `isArchived` property of a FossID Project had changed type with release 2024.2 from Integer to Boolean.
This commit fixes an `InvalidFormatException` from Jackson that occurs when deserializing scans returned by a FossID instance running the new version.
Please note that the new model support both property types thanks to the special deserializer `IntBooleanDeserializer`.
One of the test data in 'return-type/mappings' still contain the old data type to reflect this backward compatibility.

Support FossID 2024.2

---

plugins/package-managers/spdx/src/funTest/assets/projects/synthetic/spdx-project-cyclic-expected-output.yml
plugins/package-managers/spdx/src/funTest/assets/projects/synthetic/spdx-project-xyz-expected-output-subproject-conan.yml
plugins/package-managers/spdx/src/funTest/assets/projects/synthetic/spdx-project-xyz-expected-output.yml
plugins/package-managers/spdx/src/funTest/kotlin/SpdxDocumentFileFunTest.kt
plugins/package-managers/spdx/src/main/kotlin/SpdxDocumentFile.kt

In 01f1930 the identifier type used for projects and packages created by the `SpdxDocumentFile` package manager was renamed from `SdpxDocumentFile` to `SpdxDocument`. This breaks all existing package curations and package configurations which is especially problematic when they are contained in `.ort.yml` files of repositories which cannot be centrally managed.
Revert the renaming until a solution is found to make such renamings backward compatible.

feat(spdx)!: Revert renaming of `SpdxDocumentFile` to `SpdxDocument`

---

helper-cli/src/main/kotlin/commands/GetPackageLicensesCommand.kt
model/src/main/kotlin/PackageCurationData.kt
model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
plugins/reporters/opossum/src/main/kotlin/OpossumReporter.kt
plugins/reporters/spdx/src/main/kotlin/Extensions.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOssResultParser.kt
utils/spdx/src/main/kotlin/SpdxExpression.kt

There are multiple code locations which use `reduce` together with `and()` to concatenate a given collection of expressions to a compound SPDX expression. If `n` expressions are given, then `n - 1` SPDX compound expressions instances get constructed via `n - 1` `and()` calls.
As of [1] each `and()` execution started to invoke `equals()` at the very beginning. Dependening on the expression this can be very expensive. For example if the expression is contains OR operator(s) and is bit larger, then the call tree becomes quite heavy-weight. It's comprised of recursive `validChoices()` calls which insert expressions into sets which in turn leads to further `equals()` calls and so forth.
When upgrading ORT from version 28.0.0 to 45.0.0 a performance the evaluator hadn't finished after running …

fix(spdx-utils): Fix performance issue in callers of `and()`

---

model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
model/src/test/kotlin/licenses/ResolvedLicenseInfoTest.kt
model/src/test/kotlin/licenses/TestUtils.kt

Ensure that the concatenation within the implementation runs reasonably fast.

Test performance of `effectiveLicense()` and related function

---

model/src/test/kotlin/licenses/ResolvedLicenseInfoTest.kt

That comment is already part of the `runCancellable` function, and other callers of that function also do not duplicate that comment.

docs(model): Remove a duplicate comment

---

buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
gradle/wrapper/gradle-wrapper.properties

While ORT usually sticks to final versions, this release candidate fixes a very annoying issue [1] where Gradle picks the wrong Java toolchain to run its daemon.
Also see the upgrade instructions [2] for the dropped `testType` property.
[1]: https://github.com/gradle/gradle/issues/30652
[2]: https://docs.gradle.org/8.13-rc-1/userguide/upgrading_version_8.html#changes_8.13

build: Upgrade to Gradle 8.13 RC1

---

model/src/main/kotlin/config/PackageConfiguration.kt
model/src/test/kotlin/config/PackageConfigurationTest.kt

Make the matching of the identifier type in package configurations case insensitive to align with package curations.

feat(model): Match the type case insensitive in package configurations

---

model/src/test/kotlin/licenses/ResolvedLicenseInfoTest.kt

This also avoids the need for the `toList()` conversion.

chore(model): Prefer `entries` over `values()` for enums

---

integrations/completions/ort-completion.bash
integrations/completions/ort-completion.fish
integrations/completions/ort-completion.zsh
plugins/commands/plugins/build.gradle.kts
plugins/commands/plugins/src/main/kotlin/PluginsCommand.kt

Add a command to list all installed plugins and their configuration options.
The command is limited to plugins using the new plugin API, missing plugins will be added once they are migrated.

feat(cli): Add a command to list installed plugins

---

model/src/main/kotlin/licenses/LicenseInfoResolver.kt
scanner/src/main/kotlin/utils/Utils.kt
utils/common/src/main/kotlin/ArchiveUtils.kt

In all cases except for user-facing console output, string representations for paths should be invariant to the OS, as ORT is often comparing paths by string, e.g. VCS paths for repository provenances.

chore: Avoid the use of `toRelativeString()`

---

Dockerfile

fix(docker): Pre-create "$HOME/.gradle" for proper permissions

---

scanner/src/main/kotlin/ScannerMatcher.kt

The `coerce()` function provides similar lenient parsing, see [1].
[1]: https://github.com/semver4j/semver4j/blob/01f63c7efce49fa03258065bb7d3f737a7bc0819/src/test/java/org/semver4j/SemverTest.java#L751-L802

chore(scanner): Simplify Semver parsing with `coerce()`

---

model/src/main/kotlin/utils/DependencyGraphBuilder.kt

Map to a set to be able to compare two sets for equality. This now compares the sets "bidirectionally" and also returns early if `dependencies1` does not contain all of `dependencies2.keys`.

chore(DependencyGraphBuilder): Slightly improve dependency comparison

---

clients/fossid-webapp/src/main/kotlin/model/report/Model.kt
plugins/reporters/fossid/src/main/kotlin/FossIdReporter.kt

With version 24.2 of FossID, the full HTML report type is removed in favor of the Excel report type. Since the latter was already present in previous versions of FossID, it can safely be chosen for the default report type, preserving backward compatibility with previous FossID versions.

fix(reporter): Change default FossID report type

---

plugins/package-managers/maven/src/funTest/assets/projects/synthetic/tycho-expected-output-scope-excludes.yml
plugins/package-managers/maven/src/funTest/assets/projects/synthetic/tycho-expected-output.yml
plugins/package-managers/maven/src/main/kotlin/Tycho.kt

By default, the `maven-dependency-plugin` does not list dependencies (and their transitive dependencies) again if they have been listed before, effectively de-duplicating the dependency tree, also see #4720.
This de-duplication, however, is something that ORT's `DependencyGraph` should handle on its own. So, disable this de-duplication by running in `verbose` mode [1].
[1]: https://maven.apache.org/plugins/maven-dependency-plugin/tree-mojo.html#verbose

fix(maven): Avoid deduplication in Tycho dependency trees

---

model/src/test/kotlin/licenses/ResolvedLicenseInfoTest.kt

Double the timeout for the two performance related tests for SPDX expressions because they often time out on the GitHub Windows runners. Increasing the timeout should be fine because the tests are supposed to prevent performance regressions on a much larger scale.

test(model): Increase timeout for performance tests

---

plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt

This is a fixup for ff6ca62 which renamed the plugin options for the `SpdxDocumentReporter` without defining aliases for their old names.

fix(spdx): Add missing aliases for config options

---

plugins/advisors/oss-index/build.gradle.kts

This is already done globally via test suite conventions [1] (in order to always have `kotest.properties` on the test classpath).
[1]: https://github.com/oss-review-toolkit/ort/blob/cd855bef34c68613d1b33601130678b39ce912e3/buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts#L61

build(advisors): Do not explicitly depend on `testUtils`

---

website/docs/tools/analyzer.md
website/docusaurus.config.js
website/package-lock.json
website/package.json

Website: Replace Algolia with local search

---

plugins/reporters/web-app-template/src/components/ResultsTable.jsx

This is a fix-up for 403d1bc where due to copy-paste mistake the concluded license for a package is not shown in the table view.
Closes #9980.

fix(web-app-template): Fix concluded license in table view

---

utils/spdx-document/src/main/kotlin/model/SpdxExternalReference.kt

The existing URL pointed to the head of `main` in which the file path does not exist currently. Adjust the link to point to the analog page of the revision tagged with `v2.2.2`, for consistency with other references to these docs.

docs(spdx-document): Fix-up a URL

---

plugins/scanners/scanoss/build.gradle.kts
plugins/scanners/scanoss/src/main/kotlin/ScanOss.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOssConfig.kt
plugins/scanners/scanoss/src/test/kotlin/ScanOssScannerDirectoryTest.kt
plugins/scanners/scanoss/src/test/kotlin/ScanOssScannerFileTest.kt

Before 40fa386 the API key effectively was optional as a missing key was turned into an empty string via
val apiKey = secrets[API_KEY_PROPERTY].orEmpty()
Restore that behavior by using the empty string as a default value.

fix(scanoss): Make the API key optional again

---

plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-7.2-expected-output.yml
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output-archive-override.yml
plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output.yml

Apparently, some VCS URLs were added upstream.

test(bazel): Update expected results

---

cli/build.gradle.kts

This allows to build the CLI with only the analyzer as a sub-command to reduce the distribution to less than half the size:
./gradlew -P cliAnalyzerOnly=true :cli:installDist
An analyzer-only distribution is useful for workflows where individual development teams in a company are supposed to only run the analyzer, but all further ORT tools are run centrally.

build(cli): Add a Gradle property to build an analyzer-only distribution

---

.github/workflows/website-deploy.yml
.github/workflows/website-test.yml
build.gradle.kts
buildSrc/src/main/kotlin/GeneratePluginDocsTask.kt
buildSrc/src/main/kotlin/LicenseUtils.kt
website/docs/development.md
website/docs/license.md
website/docs/plugins/.gitignore
website/docs/plugins/_category_.yml
website/docs/plugins/advisors/_category_.yml
website/docs/plugins/package-configuration-providers/_category_.yml
website/docs/plugins/package-curation-providers/_category_.yml
website/docs/plugins/package-managers/_category_.yml
website/docs/plugins/reporters/_category_.yml
website/docs/plugins/scanners/_category_.yml
website/docs/related-tools.md

Add a Gradle task to generate plugin docs for the website from the generated JSON descriptions of plugins. The generated docs are not committed and instead generated when deploying the website.
The generated docs look like this:

docs(website): Add generated plugin docs

---

.github/workflows/native-build.yml

While the generated executable does not work fully as expected yet (e.g. due to missing reflection configuration), this offers a convenient way to build the executable without a local GraalVM development setup.

ci(github): Add a workflow to build a native Analyzer-only executable

---

plugins/api/README.md

This was noticed during the upgrade of the MockVCS plugin [1] to the new plugin API, thanks to https://github.com/oss-review-toolkit/ort-package-manager-plugin/pull/142.
[1] https://github.com/pepper-jk/ort-mock-vcs-plugin
Signed-off-by: Jens Keim <jens.keim@forvia.com>

docs(PluginAPI): Fix plugin compiler path in Readme

---

utils/ort/src/main/kotlin/OrtAuthenticator.kt

In `OrtAuthenticator`, use an already installed `Authenticator` as a fallback if the requested credentials cannot be found otherwise. This allows extending the authentication mechanism, which may be needed by environments that integrate ORT, for instance ORT Server.

feat(utils): Support a fallback `Authenticator`

---

plugins/reporters/web-app-template/build.gradle.kts

Use the new version properties to configure Node and Yarn as a preparation for upgrading to Kotlin 2.1.20. Update comments accordingly, and only apply the `YarnPlugin` now as it applies the `NodeJsRootPlugin` itself.

build(web-app-template): Update syntax for version properties

---

helper-cli/src/funTest/assets/create-analyzer-result-from-pkg-list-expected-output.yml
helper-cli/src/funTest/assets/package-list.yml
helper-cli/src/main/kotlin/commands/CreateAnalyzerResultFromPackageListCommand.kt

When a project does not use a package manager (supported by ORT), the helper-cli provides on alternative way to create an analyzer result from a package list file. Allow to also inject the `declaredLicense` to enable corresponding use cases.

feat(helper-cli): Extend `PackageList` by a `declaredLicense` set

---

plugins/package-managers/node/src/main/kotlin/npm/Npm.kt
plugins/package-managers/node/src/main/kotlin/npm/NpmDependencyHandler.kt

Obtaining the package details via `npm info` is a performance bottleneck of ORT's NPM package manager. Request the package details for all packages upfront, in parellel to reduce execution time. Experiments on a development machine show that execution of `NpmFunTest` now takes `1 min 13 sec` instead of `3 min 47 sec`.
Fixes: #9950.
**before**
**after**

feat(npm): Speed-up getting the remote package details

---

plugins/compiler/src/main/kotlin/JsonSpecGenerator.kt

In case `configClass` is null, write `null` instead of "null".

fix(plugins): Do not write "null" as string for `configClass`

---

gradle/libs.versions.toml

Note that only the Maven artifact publishing location changed, but the Java packages names are still the same.

deps(gradle): Upgrade SVNKit to the new "com" artifact group

---

gradle/libs.versions.toml
plugins/package-managers/maven/build.gradle.kts

When fetching metadata for snapshot artifacts, Tycho seems to use Wagon to download this data from repositories. So, the Wagon HTTP provider needs to be present on the classpath.
The exact circumstances when Tycho uses Wagon are unclear; but analyzing a real-life project failed with an error message that no wagon could be found supporting the protocol "https". Adding this artifact to the classpath fixed the issue.

fix(Maven): Add the Maven Wagon HTTP provider

---

cli/src/main/kotlin/OrtMain.kt
model/src/main/kotlin/config/OrtConfiguration.kt
utils/ort/src/main/kotlin/Environment.kt

The previous code did always output values for `ORT_CONFIG_DIR` and `ORT_DATA_DIR` even if these variables were not set, in which case their internal defaults were shown. This is confusion when dealing with reports from users, as it is unclear whether these variables were actually set.
Change the code to only show values for these variables if they really were set, aligning with the behavior for third-party variables shown.
While at it, also show `ORT_TOOLS_DIR` if set.

fix(cli): Do not output ORT_* environment variables unless set

---

helper-cli/src/funTest/assets/create-analyzer-result-from-pkg-list-expected-output.yml
helper-cli/src/funTest/assets/package-list.yml
helper-cli/src/main/kotlin/commands/CreateAnalyzerResultFromPackageListCommand.kt

When a project does not use a package manager (supported by ORT), the helper-cli provides one alternative way to create an analyzer result from a package list file. Allow to also inject the concluded license to support the corresponding use cases without the need for using separate curations.

feat(helper-cli): Extend PackageList by a concluded license

---

buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts

This should make debugging classpath ordering related issues easier.

build(gradle): Ensure a deterministic classpath order for the pathing JAR

---

plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt

An example use case is when `Package.labels` contains an identifier string.

feat(freemarker): Add a helper function for constructing `Identifier`s

---

evaluator/src/main/kotlin/PackageRule.kt
evaluator/src/test/kotlin/PackageRuleTest.kt

This can be useful to reduce the severity for declared license mapping issues, in case the package has a concluded license.
Note: Add a way to dynamically add a package to the `OrtResult` defined in `TestData.kt` in order avoid enhancing that test data with the details of this particular test.

feat(evaluator): Add the matcher `PackageRule.hasConcludedLicense()`

---

plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt

Package labels can be used for injecting custom data into any plain text report. So, make it more convenient for the '.ftl' to access the labels.

feat(freemarker): Add `val PackageModel.labels` for convenient access

---

utils/ort/src/main/kotlin/OrtAuthenticator.kt

In b2d09a69, `OrtAuthenticator` has been extended to fall back to the originally installed authenticator if no matching credentials can be found. It turned out that this is not sufficient for all scenarios in which ORT is invoked programmatically. Especially ORT Server needs more control over the authentication mechanism and sometimes needs to override credentials returned by ORT's implementation.
Therefore, make `OrtAuthenticator` an open class and support overriding the list of delegate authenticators. This gives integrating code much more flexibility to set up authentication.

feat(utils): Make `OrtAuthenticator` extensible

---

gradle.properties

This is the default now as of KSP 2.1.20-2.0.0 [1], which was taken into use in https://github.com/oss-review-toolkit/ort/commit/00f5279c020a955cca7f0e990768447a257f5995.
[1]: https://github.com/google/ksp/releases/tag/2.1.20-2.0.0

build(gradle): Do not explicitly enable KSP 2

---

helper-cli/src/main/kotlin/commands/GetPackageLicensesCommand.kt
model/src/main/kotlin/PackageCurationData.kt
model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt
model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt
model/src/main/kotlin/utils/FindingsMatcher.kt
plugins/reporters/opossum/src/main/kotlin/OpossumReporter.kt
plugins/reporters/spdx/src/main/kotlin/Extensions.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOssResultParser.kt
utils/spdx/src/main/kotlin/Extensions.kt
utils/spdx/src/main/kotlin/SpdxExpression.kt
utils/spdx/src/main/kotlin/parser/SpdxExpressionParser.kt
utils/spdx/src/test/kotlin/SpdxExpressionChoiceTest.kt

@fviernau, I realized only after my second commit that you already introduced `concat()`-based functions like `andOrNull()` which serve a similar purpose as the function I'm introducing. The last commit removes your functions in favor of mine, as I felt it to be a bit more generic, and it avoids potential confusions when reading "andOrNull", where "Or" could be misinterpreted as an SPDX operator. Please have a look.

Add functionality to deal with a "main license"

---

plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-only-lockfile-v3-with-SPM-registry-dependency.yml
plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/only-lockfile-v3-with-SPM-registry-dependency/Package.resolved
plugins/package-managers/swiftpm/src/funTest/kotlin/SwiftPmFunTest.kt
plugins/package-managers/swiftpm/src/main/kotlin/SwiftPm.kt

Currently only the `location` field is used to derive the `name` of a Swift PM dependency. For dependencies fetched over a [Package Registry Service (Swift PM registry)](https://forums.swift.org/t/swift-package-registry-service/37219) the `location` field is empty which leads to incomplete and invalid results. For those dependencies the `identity` needs to be used instead.
_Technical notes:_
- Screenshots of a broken and fixed scan with SPM registries involved:
broken:
fixed:
_Note:_ Like seen, the scan also stops resolving the broken SPM registries further which results in much shorter scan results.
- Test outcome of the newly added test without the fix:
expected:
```yml
project:
id: "SwiftPM::src/funTest/assets/projects/synthetic/only-lockfile-v3-with-SPM-registry-dependency/Package.reso …
```

fix(swiftpm): Use `identity` as `name` for Swift PM registry dependencies

---

plugins/package-managers/maven/src/main/kotlin/tycho/P2ArtifactResolver.kt
plugins/package-managers/maven/src/main/kotlin/tycho/P2RepositoryContentLoader.kt
plugins/package-managers/maven/src/main/kotlin/tycho/TargetHandler.kt
plugins/package-managers/maven/src/main/kotlin/tycho/Tycho.kt
plugins/package-managers/maven/src/main/kotlin/tycho/XmlParser.kt
plugins/package-managers/maven/src/test/kotlin/tycho/P2ArtifactResolverTest.kt
plugins/package-managers/maven/src/test/kotlin/tycho/TargetHandlerTest.kt
plugins/package-managers/maven/src/test/kotlin/tycho/TychoTest.kt

This PR adds a special handling to the Tycho implementation for Maven artifacts declared in a Tycho target platform file. Currently, such dependencies are not processed correctly because Tycho references them using alternative identifiers. To fix this, more information is parsed from target file, and some mapping logic is applied.

Tycho target dependencies

---

analyzer/src/testFixtures/kotlin/TestUtils.kt
plugins/package-managers/go/src/funTest/kotlin/GoModFunTest.kt
plugins/package-managers/maven/src/funTest/kotlin/TychoFunTest.kt
plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm/workspaces-expected-output.yml
plugins/package-managers/node/src/funTest/kotlin/pnpm/PnpmFunTest.kt
plugins/package-managers/node/src/funTest/kotlin/yarn/YarnFunTest.kt
plugins/package-managers/node/src/funTest/kotlin/yarn2/Yarn2FunTest.kt

test: Improve analysis of multiple definition files

---

plugins/reporters/asciidoc/src/funTest/kotlin/PdfTemplateReporterFunTest.kt

Let Kotest show the actual failure, if any, instead of swallowing it.

test(asciidoc): Improve `Result` assertions

---

model/src/main/kotlin/config/FileStorageConfiguration.kt
model/src/main/kotlin/config/S3FileStorageConfiguration.kt
model/src/main/resources/reference.yml
utils/ort/src/main/kotlin/storage/S3FileStorage.kt

I tried getting the S3 backend to work with our own Ceph S3 cluster, but it didn't work. It's due to pathStyleAccess being disabled per default in the AWS SDK. I also cleaned up the client builder conditions a bit.

feat(scanner): Improve S3 storage support

---

build.gradle.kts
gradle/libs.versions.toml

The task to update dependencies has been fully taken over by Renovate. Local users may want to give [1] a try instead.
[1]: https://github.com/bishiboosh/caupain

build(gradle): Remove the `versions` plugin

---

plugins/commands/plugins/src/main/kotlin/PluginsCommand.kt

This allows to easily diff the textual output to compare changes in plugin IDs.

feat(commands): Make the `plugins` output more easily comparable

---

model/src/test/kotlin/PackageCurationTest.kt

This should be merged after upgrading to a semver4j version that includes https://github.com/semver4j/semver4j/pull/343.

test(model): Add a test for curation versions with leading zeros

---

utils/ort/src/main/kotlin/JavaBootstrapper.kt

Fix `NullPointerException` in the Java Analyzer's JDK bootstrapping mechanism when the foojay discovery client returns incomplete JDK candidate data. Improve robustness by skipping or safely handling incomplete records during JDK selection.
Log output in ORT Server:
````
level=ERROR logger=o.o.analyzer.PackageManager 
message="Gradle Inspector failed to resolve dependencies for path 'android/build.gradle': 
NullPointerException: Cannot invoke \"io.foojay.api.discoclient.pkg.Distribution.getName()\" because \"this.distribution\" is null"
````

fix(analyzer): Handle incomplete JDK records from foojay

---

clients/fossid-webapp/src/main/kotlin/model/result/LicenseCategory.kt

New versions of FossID sometimes return 'NON_LICENSE' as a License Category. This makes such responses parsable.

feat(fossid): Add NON_LICENSE category to LicenseCategory

---

plugins/scanners/scanoss/src/main/kotlin/ScanOss.kt
plugins/scanners/scanoss/src/test/assets/exclusionTest/ArchiveUtils.kt
plugins/scanners/scanoss/src/test/assets/exclusionTest/ScannerFactory.kt
plugins/scanners/scanoss/src/test/assets/exclusionTest/server.go
plugins/scanners/scanoss/src/test/assets/filesToScan/ArchiveUtils.kt
plugins/scanners/scanoss/src/test/assets/filesToScan/ScannerFactory.kt
plugins/scanners/scanoss/src/test/kotlin/ScanOssScannerDirectoryTest.kt
plugins/scanners/scanoss/src/test/kotlin/ScanOssTest.kt
plugins/scanners/scanoss/src/test/kotlin/TestUtils.kt

This PR enhances SCANOSS scanner by implementing:
* Exclusion pattern support: Respects path patterns in .ort.yml to exclude files during scans
* Snippet choice processing: Converts ORT's SnippetChoices to SCANOSS rule types
This builds on top of the SCANOSS SDK migration completed in the previous PR #10265

Add exclusion patterns and snippet choice support to SCANOSS scanner

---

plugins/scanners/scanoss/src/main/kotlin/ScanOss.kt
plugins/scanners/scanoss/src/main/kotlin/ScanOssConfig.kt
plugins/scanners/scanoss/src/test/kotlin/TestUtils.kt

This PR changes the SCANOSS scanner's `readFromStorage` property to be explicitly set to `false`, following the same approach implemented for other snippet scanners like FossId.
The consensus for snippet scanners is that their results should never come from the scan storage. This change complements the previous commit (oss-review-toolkit/ort@e5571b4) that set the matcher property to null.

Set SCANOSS readFromStorage property to false and remove it from config

---

buildSrc/src/main/kotlin/ort-base-conventions.gradle.kts

See the note at [1] which says
SIG-Repo is now https://repo.blackduck.com/
All users should update their configurations to use the new
repo.blackduck.com domain.
Also see the FAQ at [2].
[1]: https://sig-repo.synopsys.com/
[2]: https://community.blackduck.com/s/article/Black-Duck-Domain-Change-FAQ

build(gradle): Use the new Black Duck repository URL

---

.github/workflows/release.yml
buildSrc/src/main/kotlin/ort-publication-conventions.gradle.kts

OSSRH is reaching end of life on June 30, 2025. To prepare for that, the self-migration [1] has been performed, and thus the publishing host needs to be changed from the default https://oss.sonatype.org [2] to the Central Portal.
[1]: https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/#self-service-migration
[2]: https://github.com/vanniktech/gradle-maven-publish-plugin/blob/705be5b9f40d91624af277df293ca1c754c86ca4/plugin/src/main/kotlin/com/vanniktech/maven/publish/SonatypeHost.kt#L39

build(gradle): Prepare for publishing to the new Central Portal

---

utils/ort/src/main/kotlin/Utils.kt
utils/ort/src/test/kotlin/UtilsTest.kt

This PR improves the authentication mechanism in ORT to pass a URL to the Authenticator if it is available. So far, only the host is used which has the consequence that only a single set of credentials can be used per host.

Use the URL for authentication if available

---

buildSrc/src/main/kotlin/GeneratePluginDocsTask.kt

ORT configuration files use YAML instead of JSON, so use YAML for the example configs for plugins.

docs(website): Use YAML instead of JSON for plugin configs

---

buildSrc/src/main/kotlin/GeneratePluginDocsTask.kt

While at it, stick to the default `it` for the option. This is a fixup for b71980e that silences a compiler warning.

chore(buildSrc): Remove an unused index

---

plugins/package-managers/python/src/main/kotlin/utils/PythonUtils.kt

Not constructing a temporary map but just a pair is slightly shorter.

style(python): Align on adding single map entries as a pair

---

model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt

In 67beb24, a change was introduced to compute the main license of a package. This significantly increased the generation times for the SPDX reports for some projects containing packages with many license findings. The problem was in the aggregating of detected licenses where many relative paths to files with license findings were constructed.
To address this issue, use a cache for already constructed paths. This makes the report generation fast again.
Resolves #10317.

fix(reporter): Fix a performance issue with generating SPDX reports

---

clients/fossid-webapp/src/main/kotlin/EntityResponseBody.kt
clients/fossid-webapp/src/main/kotlin/Extensions.kt
clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt
clients/fossid-webapp/src/main/kotlin/model/CreateScanResponse.kt
clients/fossid-webapp/src/test/kotlin/FossId2024dot2Test.kt
clients/fossid-webapp/src/test/kotlin/FossIdClientNewProjectTest.kt
clients/fossid-webapp/src/test/kotlin/FossIdClientReturnTypeTest.kt
clients/fossid-webapp/src/test/resources/return-type/mappings/apiphp-create_scan.json
clients/fossid-webapp/src/test/resources/return-type/mappings/apiphp-get_project_error.json
plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/test/kotlin/FossIdSnippetChoiceTest.kt
plugins/scanners/fossid/src/test/kotlin/FossIdTest.kt
plugins/scanners/fossid/src/test/kotlin/TestUtils.kt

For some requests, failure responses returned by FossID could not be deserialized. This made diagnosing failures really hard, since the deserialization exception swallowed the original response. To improve this situation, add logic to handle failure responses at least in some cases.
This PR has still some limitations. Especially, requests for which the result value is ignored (type `EntityResponseBody<Nothing>`) do not work with this approach. Creating this as draft as a proposal, so that there is a chance that anybody comes up with a better solution - or it is decided that this can be merged as is, since it provides some improvements.

feat(FossId): Improve failure handling

---

plugins/scanners/fossid/src/main/kotlin/FossId.kt

This commit adds handling for situation, where project exists in FossID, but ORT user have no access granted.

feat(fossid): Extend logging for FossID project access issues

---

.github/workflows/docker-build.yml
build.gradle.kts

Simplify retrieving the current ORT version by creating a separate task. This is helpful for automated tasks where the exact version is required.

build: Replace printVersion gradle task with an ORT specific version

---

buildSrc/src/main/kotlin/ort-publication-conventions.gradle.kts

These are only needed locally. This speeds up publishing and works around a bogus "Dependency version information is missing" error on Sonatype Central Portal when publishing releases.
Note that the lookup in `components` throws instead of returning `null` if "java" is not present.
Also see [1] which explains to do the same for test fixtures, which in fact are just feature variants.
[1]: https://docs.gradle.org/current/userguide/java_testing.html#ex-disable-publishing-of-test-fixtures-variants

build(gradle): Do not publish "funTest" feature variants

---

gradle/libs.versions.toml
model/build.gradle.kts
model/src/main/kotlin/utils/FileArchiver.kt
model/src/test/kotlin/utils/FileArchiverTest.kt

Binary license files are now detected and excluded during license info resolution. In previous cases, such files caused the reporter to enter an endless loop during report generation, as the archiver attempted to include the binary content in the report.
To verify this behavior, a test file named LICENSE-BIN is added to archive.zip. It contains 4 arbitrary bytes created with a hex editor to simulate a non-text license file.
Apache Tika is introduced to detect MIME types and distinguish between text and non-text files. This ensures that only valid, readable license files are processed and included in the final report.

Exclude binary license files to prevent reporter hang

---

plugins/package-managers/spdx/src/main/kotlin/utils/SpdxDocumentCache.kt
plugins/reporters/spdx/src/funTest/kotlin/SpdxDocumentReporterFunTest.kt
plugins/reporters/spdx/src/funTest/resources/spdx-document-reporter-expected-output.spdx.json
plugins/reporters/spdx/src/funTest/resources/spdx-document-reporter-expected-output.spdx.yml
plugins/reporters/spdx/src/main/kotlin/Extensions.kt
utils/spdx-document/src/main/kotlin/model/SpdxAnnotation.kt
utils/spdx-document/src/main/kotlin/model/SpdxChecksum.kt
utils/spdx-document/src/main/kotlin/model/SpdxCreationInfo.kt
utils/spdx-document/src/main/kotlin/model/SpdxDocument.kt
utils/spdx-document/src/main/kotlin/model/SpdxExternalDocumentReference.kt
utils/spdx-document/src/main/kotlin/model/SpdxExternalReference.kt
utils/spdx-document/src/main/kotlin/model/SpdxExtractedLicenseInfo.kt
utils/spdx-document/src/main/kotlin/model/SpdxFile.kt
utils/spdx-document/src/main/kotlin/model/SpdxPackage.kt
utils/spdx-document/src/main/kotlin/model/SpdxPackageVerificationCode.kt
utils/spdx-document/src/main/kotlin/model/SpdxRelationship.kt
utils/spdx-document/src/main/kotlin/model/SpdxSnippet.kt

Validation is still called as part of `init`, so there is no change in behavior currently. However, this refactoring prepares for eventually doing validation not at construction time of the class, to allow e.g. for writing SPDX documents with invalid SPDX expressions for later validation by external tools like [1] instead of failing report generation completely.
[1]: https://tools.spdx.org/app/validate/

Improvements to SPDX report validation

---

plugins/package-managers/bazel/src/funTest/assets/projects/synthetic/bazel-expected-output-conan-package-manager-disabled.yml
plugins/package-managers/bazel/src/funTest/kotlin/BazelFunTest.kt
plugins/package-managers/bazel/src/main/kotlin/Bazel.kt

Since the package managers are run in parallel, conflicts could arise when accessing data in CONAN_HOME. Therefore, always run Bazel after Conan.
This is a fixup for 56a6d180b731518c745ffe27ed8663be2cee5d20.
See also the discussion at [1].
[1]: https://github.com/oss-review-toolkit/ort/pull/10357

fix(bazel): Always run Bazel after the Conan package manager

---

plugins/scanners/askalono/src/main/kotlin/Askalono.kt
plugins/scanners/askalono/src/main/kotlin/AskalonoResultModel.kt
plugins/scanners/boyterlc/src/main/kotlin/BoyterLc.kt
plugins/scanners/boyterlc/src/main/kotlin/BoyterLcResultModel.kt

If the only customization is to ignore unknown keys, prefer to use the class annotation instead, which nicely documents the class to be potentially incomplete as not all properties are needed.

chore(scanner): Partly avoid the need for custom serial formats

---

clients/fossid-webapp/src/main/kotlin/FossIdRestService.kt

Increase the read timeout for the generate report call to prevent timeouts on larger reports or when fossid is overloaded.

feat(fossid): Increase read timeout for report generation

---

scanner/build.gradle.kts

As reported by `./gradlew -p scanner projectHealth` and double-checked.

deps(scanner): Remove unused dependencies

---

clients/dos/src/main/kotlin/DosClient.kt
clients/dos/src/main/kotlin/DosModel.kt
plugins/scanners/dos/src/main/kotlin/DosScanner.kt
plugins/scanners/dos/src/main/kotlin/DosScannerConfig.kt
plugins/scanners/dos/src/test/kotlin/DosScannerTest.kt

The `fetchConcluded` option will be removed from the endpoint on DOS API, so remove the option from the DOS scanner configuration, and the `options` parameter from the `ScanResultsRequestBody` class.
This option was an experimental feature in the early development, and was mainly used to see the effects of the license conclusions before the DOS API also supported being used as a package configurations provider. There will be changes coming to the access to license conclusions on DOS API as users will be allowed to create their own license conclusions, and these will be linked to the organization the user belongs in, and the license conclusions will then be returned based on which organization they are queried for, so the scan results endpoint will be changed to only return the actual …

refactor(dos): Remove `fetchConcluded` option

---

buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts

This allows running the CLI JARs with the regular "java -jar ..." approach.

build(gradle): Properly set the "Main-Class" attribute for applications

---

buildSrc/src/main/kotlin/GeneratePluginDocsTask.kt

Avoid the impression that optional plugin values could be explicitly set to null.
Fixes #10484.

docs(plugins): Mark optional plugin values

---

plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/react-native-expected-output.yml
plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/react-native/ios/Podfile
plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/react-native/ios/Podfile.lock
plugins/package-managers/cocoapods/src/main/kotlin/CocoaPods.kt
plugins/package-managers/cocoapods/src/main/kotlin/PodDependencyHandler.kt

Check individual commit messages for details.

fix(cocoapods): Resolve CocoaPods dependencies defined via :path: entries

---

plugins/package-managers/cocoapods/src/main/kotlin/PodDependencyHandler.kt
plugins/package-managers/maven/src/main/kotlin/Maven.kt
plugins/package-managers/maven/src/main/kotlin/utils/MavenSupport.kt
plugins/package-managers/sbt/src/main/kotlin/Sbt.kt
plugins/version-control-systems/git/src/main/kotlin/GitRepo.kt
utils/common/src/main/kotlin/FileUtils.kt
utils/common/src/test/kotlin/ExtensionsTest.kt

Use the function in more places by generalizing it for files with the `generateSequence()`-approach used in `PodDependencyHandler`.

refactor: Generalize `searchUpwardsForSubdirectory()` for files

---

model/src/main/kotlin/ScannerRun.kt
model/src/test/kotlin/ScannerRunTest.kt
plugins/reporters/evaluated-model/src/funTest/resources/evaluated-model-reporter-test-deduplicate-expected-output.yml
plugins/reporters/evaluated-model/src/funTest/resources/evaluated-model-reporter-test-expected-output.json
plugins/reporters/evaluated-model/src/funTest/resources/evaluated-model-reporter-test-expected-output.yml
plugins/reporters/evaluated-model/src/funTest/resources/reporter-test-input.yml
plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelMapper.kt
scanner/src/main/kotlin/ScanController.kt
scanner/src/main/kotlin/Scanner.kt
scanner/src/test/kotlin/ScannerTest.kt

Add a new `issues` property to the `ScannerRun` class and collect issues from completely failing scans for path scanners in the issues map instead of creating and storing empty scan results.
Please see the individual commits for details.

Fix issue with scan results from failed scans being reused even if scan problem is resolved

---

.github/workflows/build-and-test.yml

This allows to more easily identify Windows-specific failures, when seeing that tests on Linux succeed.

ci(github): Do not fail fast for the (unit) test matrix

---

settings.gradle.kts
version-catalog/build.gradle.kts

This allows programmatic users of ORT libraries to consume them by only declaring the version once, and not for all libraries. Also no custom library declarations are needed anymore on the consumer side.
For details see [1].
[1]: https://docs.gradle.org/current/userguide/version_catalogs.html#sec:version-catalog-plugin

feat(gradle): Publish a version catalog for ORT

---

plugins/scanners/fossid/src/main/kotlin/FossIdUrlProvider.kt
plugins/scanners/fossid/src/test/kotlin/FossIdUrlProviderTest.kt

When querying the authenticator for the credentials of a repository to be scanned by FossID, do not use a URL with a user info component, which may be present after applying URL mapping. This will trigger ORT's `UserInfoAuthenticator` and yield invalid results.

fix(fossid): Do not pass a URL with user info to the authenticator

---

plugins/reporters/spdx/src/funTest/kotlin/SpdxDocumentReporterFunTest.kt
utils/test/src/main/kotlin/Matchers.kt

Validating both, JSON and YAML, against the schema is valuable in particular with regard to the recently introduced patching the `SPDX-2.3` output to `SPDX-2.2` which potentially could be inhanced with JSON or YAML format specific code.

test(spdx-reporter): Test the validity of the YAML against the schema

---

website/docs/configuration/package-configurations.md

The enum constant is `SourceCodeOrigin.ARTIFACT`, not `SourceCodeOrigin.SOURCE_ARTIFACT`.

docs(website): Fix wrong `SourceCodeOrigin` value for source artifacts

---

buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts

The GraalVM native build tools add an output to the `run` task which causes it to be up-to-dateable. Still ensure that Gradle (and IntelliJ) always execute the task.

build(gradle): Ensure that the `run` task is always executed

---

detekt-rules/build.gradle.kts

Do not issue the warning if the JAR was rebuilt, which might occur when the global project version has changed, but no code of Detekt rules.

build(gradle): Only warn about new Detekt rules if they were recompiled

---

plugins/package-managers/python/src/main/kotlin/utils/PythonInspector.kt

Unfortunately, the `python-inspector` prints credentials when using `--verbose` e.g. [1]:
```
repos:
PypiSimpleRepository(
index_url='https://example.com',
credentials={'login': 'user', 'password': 'secret'}
)
```
As a stop-gap measure, remove the `--verbose` option to avoid printing these credentials.
[1]: https://github.com/aboutcode-org/python-inspector/blob/4a91a4d4d5c3006927fe16476a853c2e1890a6d2/src/python_inspector/api.py#L280

chore: Remove verbose logging from `python-inspector`

---

plugins/reporters/spdx/src/main/kotlin/Extensions.kt

Wraps `SpdxChecksum` creation in `runCatching` to handle validation failures, preventing failure of SPDX report generation when checksum validation fails.
This PR should fix #10659. More context is provided there.

fix(spdx): Convert hash value to lowercase when creating SpdxChecksum

---

plugins/scanners/fossid/src/main/kotlin/events/CloneRepositoryHandler.kt
plugins/scanners/fossid/src/test/kotlin/events/CloneRepositoryHandlerTest.kt

Deduplicate and normalize ignore rules by removing the trailing "/*" from directory rules and also remove duplicate directory,file and extension rules.
This prevents a problem where FossID reports an error when ignore rules are created that already exist.
_"Scanner job '177452' failed."
java.lang.IllegalArgumentException: Could not 'create ignore rules'. Additional information: Rule already exists._

fix(fossid-webapp): Deduplicate and normalize ignore rules

---

plugins/version-control-systems/git/src/main/kotlin/GitWorkingTree.kt

Also support "unnamed" remotes that are URLs. Such remotes are for example created by the GitHub CLI when running `gh pr checkout ...`.

fix(git): Improve the logic to determine the remote URL

---

scanner/src/funTest/kotlin/scanners/ScannerIntegrationFunTest.kt
scanner/src/main/kotlin/Scanner.kt

When the SpdxDocumentFile package manager is used, the *project* and all contained *packages* often resolve to the **same VCS provenance** (e.g. the root of the Git repository).
Before this change ORT stored two separate `ScanResult`s for such a provenance – one keyed to the project, one keyed to the package.
That caused two follow-on problems:
* Both results appeared in the `OrtResult`, so evaluators saw **duplicate findings** for the *same* source tree.
* Because projects and packages are handled by different rules the package result was additionally **padded with a `SpdxConstants.NONE` finding** whenever `includeFilesWithoutFindings` was enabled. The evaluator therefore compared *real* license findings from the project result with `NONE` from the package result and failed with a …

feat(scanner): Merge duplicate scan results that share a provenance

---

utils/common/src/main/kotlin/IterableUtils.kt
utils/common/src/test/kotlin/IterableUtilsTest.kt

`Iterable<T>.getDuplicates(keySelector)` returned no results when the receiver was a `Set`, even if different elements shared the same key. The early‑exit shortcut has been removed, so logical duplicates are now reported correctly.
Changes
* Drop Set fast‑path in `getDuplicates(keySelector)`; keep it only for the zero‑arg variant where it is safe.
* Align zero‑arg implementation and add regression tests.

fix(utils): detect key‑based duplicates in Set inputs

---

analyzer/src/funTest/kotlin/PackageManagerFunTest.kt
analyzer/src/main/kotlin/Analyzer.kt
analyzer/src/main/kotlin/PackageManager.kt
cli-helper/src/main/kotlin/utils/Extensions.kt
integrations/schemas/repository-configuration-schema.json
model/src/main/kotlin/OrtResult.kt
model/src/main/kotlin/config/Includes.kt
model/src/main/kotlin/config/RepositoryConfiguration.kt
model/src/main/kotlin/config/config/PathInclude.kt
model/src/main/kotlin/config/config/PathIncludeReason.kt
model/src/main/kotlin/utils/JsonIncludeValueFilters.kt
model/src/test/kotlin/OrtResultTest.kt
model/src/test/kotlin/config/IncludesTest.kt
scanner/src/main/kotlin/ScanContext.kt
scanner/src/main/kotlin/Scanner.kt
website/docs/configuration/ort-yml.md

This is the implementation corresponding to the decision made in the core dev meeting on [17/06/2025](https://github.com/oss-review-toolkit/ort/wiki/Kotlin-Developer-Meeting#2025-06-17).

Add ORT includes support

---

model/src/main/kotlin/ScannerRun.kt
model/src/test/kotlin/ScannerRunTest.kt
plugins/package-managers/pub/src/main/kotlin/Pub.kt
scanner/src/main/kotlin/Scanner.kt
utils/ort/src/main/kotlin/Environment.kt

By now no `ScannerWrapper` implements `CommandLineTool` anymore, so get the versions directly from the `ScannerDetails`.
While at it, already set `toolVersions` in the internal `scan()` function, which avoids a copy of the `ScannerRun`s later on.

fix(scanner): Correct setting scanner tool versions

---

cli/src/main/resources/logback.xml
clients/fossid-webapp/src/main/kotlin/LoggingInterceptor.kt

Under some specific circumstances (when upload mode is enabled but the archive is not big enough to trigger the upload in chunks), OkHttp removes the content type header. Since this header is used to determine if a request body should be logged or not, this could crash the scanner when the request logging is enabled and the LoggingInterceptor tries to log binary content. This commit fixes this behavior by adding an extra check on the actual request body.
Note: I didn't find out why OkHttp removes this header. I found [this link](https://stackoverflow.com/questions/65712843/okhttp-does-not-allow-for-setting-of-content-type) but it does not apply here.
Anyway the extra protection brought by this PR does not hurt.

fix(fossid-webapp): Fix request Logging

---

gradle.properties

See [1].
[1]: https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_warnings

build(gradle): Always show all warnings to identify issues early

---

NOTICE
plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-lockfile-v3-with-SPM-registry-configuration.yml
plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/expected-output-registry-configuration.yml
plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/lockfile-v3-with-SPM-registry-configuration/.swiftpm/configuration/registries.json
plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/lockfile-v3-with-SPM-registry-configuration/Package.resolved
plugins/package-managers/swiftpm/src/funTest/assets/projects/synthetic/registry-configuration/registries.json
plugins/package-managers/swiftpm/src/funTest/kotlin/SwiftPmFunTest.kt
plugins/package-managers/swiftpm/src/main/kotlin/SwiftPm.kt
plugins/package-managers/swiftpm/src/main/kotlin/SwiftPmModel.kt

Read the project local and global swift registry configurations to provide the source artifact URL for dependencies fetched over a Swift PM Registry
This PR provides a follow-up of https://github.com/oss-review-toolkit/ort/pull/10124. This PR will now provide the `sourceArtifactUrl` for dependencies fetched over a Swift PM registry, which is required if the ORT scanner is turned on in a project.
We've tested the fix internally with several projects using Swift PM over registry and it worked great.

feat(swiftpm): Provide URL to artifact on Swift PM registry

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/ort-base-conventions.gradle.kts
gradle/libs.versions.toml

With Gradle 9, building JARs is reproducible by default [1].
[1]: https://docs.gradle.org/9.0.0/release-notes.html#archive-tasks-produce-reproducible-archives-by-default

build(gradle): Remove the reproducible-builds plugin

---

.github/workflows/build-and-test.yml

Upgrade for more modern tools, see [1]. For information, GitHub will make "latest" point to "windows-2025" end of September 2025.
[1]: https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md

ci(github): Switch "windows-2022" to "windows-2025"

---

plugins/scanners/fossid/src/main/kotlin/events/UploadArchiveHandler.kt

This makes `UploadArchiveHandlerTest` pass on Windows again.

fix(scanners): Determine paths invariantly for Windows

---

plugins/commands/scanner/src/main/kotlin/ScanCommand.kt

Scanners should be printed below instead of next to each other.

fix(scanner): Fix the CLI printing scanner names

---

scanner/src/main/kotlin/Scanner.kt
scanner/src/test/kotlin/ScannerTest.kt

Return `null` instead of an empty `ScannerRun` if no work needs to be done in order to be able to easily determine if any `ScannerRun`s need to be merged.
Fixes #10685.

refactor(scanner): Do not return an empty `ScannerRun` from `scan()`

---

.github/workflows/release.yml

This reverts commit f6771fa as it did not help to make the release process work again.

Revert "ci(release): Disable the dependency grap generation"

---

plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/main/kotlin/events/CloneRepositoryHandler.kt
plugins/scanners/fossid/src/main/kotlin/events/EventHandler.kt
plugins/scanners/fossid/src/main/kotlin/events/UploadArchiveHandler.kt

This is a fixup for af95c97626d9a0365e75a9da52668c4b53ba17e1, which removed the credentials from the repository URL before adding it to the scan comment. Since the `CloneRepositoryHandler` used to take the URL from the comment, it does not have the credentials to clone the repository anymore.
To fix this, extend the `EventHandler` interface, so that the original URL with credentials can be explicitly passed and used for the cloning.

fix(fossid): Use the URL with credentials when cloning the repo

---

plugins/package-managers/python/src/main/kotlin/utils/PythonInspector.kt
plugins/package-managers/python/src/main/kotlin/utils/PythonInspectorExtensions.kt

With the introduction of commit 0b9fa5b, null purl's output given by python-inspector causes a crash on pdt file parsing.
Fixes: #10734

fix(python-inspector): Null check for purl before mapping it

---

gradle/libs.versions.toml
plugins/package-managers/maven/build.gradle.kts

Added dependency `net.i2p.crypto:eddsa` to resolve `DownloadException` as reported in https://github.com/oss-review-toolkit/ort/issues/10748.
The root error `NoSuchAlgorithmException: EdDSA provider not supported` is caused by a missing dependency as outlined [here](https://stackoverflow.com/questions/65566138/apache-mina-sshd-ssh-client-always-prints-eddsa-provider-not-supported/65566139#65566139) by @sschuberth.

deps(gradle): Add org.bouncycastle library

---

plugins/package-managers/pub/src/main/kotlin/PubCacheReader.kt
plugins/package-managers/pub/src/test/kotlin/PubCacheReaderTest.kt

I came across with some corner cases when teams are using custom package repositories in their `pubspec.yaml`
```
dependency_overrides:
flutter_compass:
url: https://github.com/marcotta/flutter_compass.git
path: "."
dependencies:
flutter_compass: ^0.7.0
private_package:
hosted:
name: private_package
url: https://internal.tool.company/api/pub/repository
version ^1.0.0
```
These packages will end up in `.pub-cache` directory
```
.pub-cache % find . -type d -name "*flutter_compass*"
./git/flutter_compass-d10156058a1536dc66410619e82c7c4846d3f942
.pub-cache % find . -type d -name "*private_package*"
./hosted/internal.tool.company%47api%47pub/repository%47/private_package-1.0.0
```

fix(pub): Improve support for custom package repositories

---

plugins/package-managers/bazel/src/main/kotlin/Bazel.kt

This prevents an `IndexOutOfBoundsException` when the integrity property is blank.

fix(bazel): Handle empty `integrity` in source.json

---

model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
plugins/scanners/fossid/src/main/kotlin/FossId.kt
plugins/scanners/fossid/src/main/kotlin/FossIdConfig.kt
plugins/scanners/fossid/src/test/kotlin/TestUtils.kt

Add 'treatPendingIdentificationsAsError' configuration option to allow treating pending identifications in FossID as errors instead of hints.

feat(fossid): Add option to treat pending identifications as errors

---

model/src/main/resources/reference.yml
model/src/test/kotlin/config/OrtConfigurationTest.kt
plugins/scanners/fossid/src/main/kotlin/FossIdConfig.kt
plugins/scanners/fossid/src/main/kotlin/events/UploadArchiveHandler.kt
plugins/scanners/fossid/src/test/kotlin/TestUtils.kt

This allows users to retain content when needed for debugging or analysis purposes while maintaining the default cleanup behavior.

feat(fossid): Add parameter to disable content deletion after scan

---

Dockerfile

Some projects may have a hard build dependency on this crate (see [1]).
[1]: https://crates.io/crates/cargo-credential-netrc

feat(docker): Add cargo-credential-netrc to the Docker image

---

detekt-rules/src/main/kotlin/OrtImportOrder.kt

Fix the issue that auto-correction of the `OrtImportOrder` rule added backticks when import aliases are used. For example, the import
import org.example.SomeClass as AliasName
was rewritten as
import org.example.`SomeClass as AliasName`

fix(detekt): Fix alias handling in auto-correction of import order

---

plugins/reporters/spdx/src/main/kotlin/Extensions.kt

The `SpdxExtractedLicenseInfo` class requires that the license text is not empty. However, in some situations it can be that a license text from a `LicenseFactProvider` is empty, for example, if a ScanCode license text contains only YAML front matter, or if a custom license text file is empty. To not fail the SPDX reporter in this situation, simply check if a license text is empty before creating the `SpdxExtractedLicenseInfo`.

fix(spdx-reporter): Do not try to add empty license texts

---

plugins/reporters/freemarker/src/main/kotlin/FreemarkerTemplateProcessor.kt

Hi!
We thought it would be handy to have a helper function for the freemaker templates, to filter only classified licenses. Would be cool to integrate it with ORT if you are interested!
Thanks!

feat: Add funct to filter for classified licenses

---

buildSrc/src/main/kotlin/ort-application-conventions.gradle.kts
buildSrc/src/main/kotlin/ort-kotlin-conventions.gradle.kts
scanner/src/main/kotlin/Scanner.kt

Generalize a work-around to always run `JavaExec` tasks 

---

model/src/main/kotlin/utils/FileArchiver.kt
model/src/test/kotlin/utils/FileArchiverTest.kt

The detection mechanism may detects any plain text file as `text/x-web-markdown` in case it has `.md` as filename extension. Fix the filtering to make any `text/*` type pass.
Note: Looking at `FileArchiverTest`, the code seems to assume that the
detection is independent of the filename extension, which does
not hold. It seems to make sense to incorporate this finding into
the test code.
Fixes: #10850.

fix(scanner): Ensure file archiver archives any text files

---

plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/project-with-lockfile/package-lock.json
plugins/package-managers/node/src/funTest/assets/projects/synthetic/npm/project-with-lockfile/package.json
plugins/package-managers/node/src/main/kotlin/npm/Npm.kt

If `npm install` and `npm list` runs without errors, the installation of the modules should be fine. So, it is ok to ignore module infos for not installed modules, for example platform specific optional dependencies which do not match the host's platform.
Fixes: #10815.

fix(npm): Ignore module infos for not installed modules

---

.github/workflows/native-build.yml

This has a lot of improvements for native image generation, see [1].
[1]: https://www.graalvm.org/release-notes/JDK_25/

ci(github): Upgrade to GraalVM 25

---

plugins/license-fact-providers/api/src/main/kotlin/CompositeLicenseFactProvider.kt
plugins/license-fact-providers/api/src/main/kotlin/LicenseText.kt
plugins/license-fact-providers/dir/src/main/kotlin/DirLicenseFactProvider.kt
plugins/license-fact-providers/dir/src/test/kotlin/DirLicenseFactProviderTest.kt
plugins/license-fact-providers/scancode/src/funTest/kotlin/ScanCodeLicenseFactProviderFunTest.kt
plugins/license-fact-providers/scancode/src/main/kotlin/ScanCodeLicenseFactProvider.kt
plugins/license-fact-providers/scancode/src/test/kotlin/ScanCodeLicenseFactProviderTest.kt
plugins/license-fact-providers/spdx/src/main/kotlin/SpdxLicenseFactProvider.kt
plugins/license-fact-providers/spdx/src/test/kotlin/SpdxLicenseFactProviderTest.kt
plugins/reporters/aosd/src/main/kotlin/Aosd20Reporter.kt
plugins/reporters/aosd/src/main/kotlin/Aosd21Reporter.kt
plugins/reporters/ctrlx/src/main/kotlin/CtrlXAutomationReporter.kt
plugins/reporters/cyclonedx/src/main/kotlin/Utils.kt
plugins/reporters/opossum/src/main/kotlin/OpossumReporter.kt
plugins/reporters/spdx/src/main/kotlin/Extensions.kt

Ensure in all license fact providers that returned license texts are not blank. Also use a value class `LicenseText` to model this in the API of `getLicenseText()`, this ensures that all consumers can rely on the text not being blank, and that if a provider implements that wrong, it will fail immediately instead of leading to follow-up errors.

refactor(license-fact-provider): Ensure that license texts are not blank

---

plugins/package-managers/bazel/src/funTest/kotlin/BazelDetectionFunTest.kt

This test depends on the `buildozer` tool.

test(bazel): Rename to "BazelDetectionFunTest" as it is in `funTest`

---

downloader/src/main/kotlin/VersionControlSystem.kt

Determining the `VersionControlSystem` from `VcsType` or URL should work statically without any underlying external tool to be available at this point. If at all, the whole `VersionControlSystem` plugin should not load if a required external tool is not available.

fix(downloader): Determining the VCS type should not require availability

---

.github/workflows/static-analysis.yml

This has the benefit of Renovate-based updates to specific versions.

ci(github): Use the `reuse-action` instead of calling `lint` manually
